### ISSUE TITLE
ScriptHost Development Mode

### ISSUE THREAD

**Issue by mathewc** [Azure/azure-webjobs-sdk-script#100]
Need to implement a time based "dev mode" that configures the ScriptHost optimally for interactive use. For example:

- sets host settings to optimal development settings (i.e. `config.UseDevelopmentMode()`)
- enables file logging/log streaming and verbose logging (we don't want file logging on always for perf)

Idea is that when UI is actively connected to the host it enters this mode and stays there as long as the UI remains actively connected.

**Comment by davidebbo** [comment]
We should expose that in a way that the Portal can easily set. It would be nice if this could just happen when using portal interactively, and go away on its one when stepping away. We can think through potential solutions. e.g. there could be some kind of useDevModeUntil prop which portal would keep setting 15 minutes into the future, without taking the chance of it being left in that mode unintentionally.

**Comment by mathewc** [comment]
That's the plan, let's discuss. I know we can't leave file logging always on as it is now.

**Comment by fabiocav** [comment]
This would also help drive the flag indicating whether to compile code without optimizations and emitting PDBs

**Comment by davidebbo** [comment]
@fabiocav that one is a bit more subtle. If we always generate PDB's when someone uses the portal, how would one not generated PDBs (outside of git push scenarios)? :)

**Comment by fabiocav** [comment]
This would mostly apply to cold start/restart scenarios. If we're loading the host as a result of a trigger firing when the portal is not loaded, we could compile with no PDBs and with optimizations enabled.

**Comment by davidebbo** [comment]
You're right. I didn't account for the site instance being so short lived.

**Comment by paulbatum** [comment]
Punting to post beta.
