### ISSUE TITLE
Not able to execute 1000 records using azure function App

### ISSUE THREAD

**Issue by sai-alladi** [Azure/azure-webjobs-sdk-script#1003]
Please provide a succinct description of the issue.
We have created a Http Triggered function app which basically calling from Logic apps followed by trigger . When we are processing small amount of data say 100 records the logic app (which contains internally function apps, which is around 3 to 5 function apps ) executing without any exception (we tried with consumption plan and app service paln). But when we tried with 1000 record set it started throwing an erros (500 and 502). Even we tried with App Service Environment aswell, we are facing same issue. 
Provide the steps required to reproduce the problem

1. Create some http triggered fucntion apps (say 4 to 5 function apps)
2. Create Http Request Logic app followed by actions (consume functions which you have created in 1 step) 
3. Trigger a logic app continuously for 100 records, 1000 records.
4. for 100 records it's  not giving an error but 1000 records it's throwing an error.

#### Expected behavior

the server should not throw an error , 

#### Actual behavior

It's throwing an errors HTTP 500 ,502 some times

**Comment by mathewc** [comment]
Can you provide more details on the 1000 rows of data? How many bytes, format, etc.? We need to construct a repro. If you have some sample data to help us repro that would be great.

**Comment by paulbatum** [comment]
@mathewc I have a direct mail thread with Sai.
