### ISSUE TITLE
Host occasionally gets in a state where it fails to detect filesystem changes

### ISSUE THREAD

**Issue by paulbatum** [Azure/azure-webjobs-sdk-script#1009]
Today I was able to inspect a function app that had entered into a state where it continued to execute existing functions just fine, but any changes to the filesystem of the app were not detected. 

I tried:
1. Touching a function.json file
2. Creating a new .csx file
3. Touching the debug_sentinel file

In all three cases, the host process appeared to ignore the file change. I was not able to find any host restart events for (1), any compilation events for (2) or any updates to the host log file based on (3).

We need to look at implementing some type of monitor to ensure that the host filewatch behavior is working correctly e.g. once a minute the host touches a special file that it has a file watch setup for. If no filewatch event is received for the update, then the host logs the anomaly and reinitializes all outstanding filewatchers.

**Comment by fabiocav** [comment]
@mathewc and I had discussed the above in the past and I think we have an opportunity for some optimizations here as well. I'll see if I can get something together tonight.

**Comment by fabiocav** [comment]
Resolved (mitigated) by #1037 
Refer to PR summary for details.
