### ISSUE TITLE
CLI: Allow configuring CORS when running webhost locally

### ISSUE THREAD

**Issue by christopheranderson** [Azure/azure-webjobs-sdk-script#1012]
We can't test Azure Functions being used in HTTP scenarios like SPAs without CORS being able to be configured to something like "http://localhost:8080" or whatever. Ideally we could set this list; in the worst case we could allow all.

**Comment by ahmelsayed** [comment]
`func host start --cors http://localhost:8080,http://www.test-cors.org,https://functions.azure.com`
