### ISSUE TITLE
How to run WebJobs in .net core

### ISSUE THREAD

**Issue by VenkateshSrini** [Azure/azure-webjobs-sdk-script#1013]
Hi All,

Can you please tell me what are the steps that needs to be done web jobs using .NET core and Node.js. Do we need to install anything locally.

Thanks and regards
Venkatesh

**Comment by fabiocav** [comment]
@VenkateshSrini .NET Core is not currently supported, so this isn't a supported scenario at the moment. As we plan that migration, we'll have issues tracking that work on this repo.

**Comment by VenkateshSrini** [comment]
@fabiocav,
What are the steps to run this in local

**Comment by fabiocav** [comment]
We have some instructions on building, developing and running locally here:
https://github.com/Azure/azure-webjobs-sdk-script/wiki#build--test

The easiest way to run local is to use our CLI:
https://www.npmjs.com/package/azure-functions-cli

Or, the newly announced VS Tooling for Azure Functions:
https://blogs.msdn.microsoft.com/webdev/2016/12/01/visual-studio-tools-for-azure-functions/

**Comment by VenkateshSrini** [comment]
Thank you
