### ISSUE TITLE
Azure function parallel run and scaleout

### ISSUE THREAD

**Issue by zsole** [Azure/azure-webjobs-sdk-script#1019]
Please provide a succinct description of the issue.

#### Repro steps

Provide the steps required to reproduce the problem

1. Step A

2. Step B

#### Expected behavior

Provide a description of the expected behavior.

#### Actual behavior

Provide a description of the actual behavior observed. 

#### Known workarounds

Provide a description of any known workarounds.

#### Related information 

Provide any related information 

* Programming language used 
* Links to source

**Comment by christopheranderson** [comment]
Closing this because the information in the issue hasn't been filled out.
