### ISSUE TITLE
Azure Blob trigger throws "hostAccount" : value cannot be null when Function app files are uploaded

### ISSUE THREAD

**Issue by ship2moon** [Azure/azure-webjobs-sdk-script#1020]
Please provide a succinct description of the issue.

1. Create a Function App
2. Upload all files via Kudu API as zip file
3. Open Function App in browser and ensure all files are uploaded with proper content in each files
4. When opening C# trigger code (.csx) file in Function App Editor, a floating popup error says:
"Function ($YourFunctionName) Error: Microsoft.Azure.WebJobs.Host: Error indexing method 'Functions.YourFunctionName'. Microsoft.Azure.WebJobs.Host: Value cannot be null. Parameter name: hostAccount. Session Id: xxxxxxxxxxx

Timestamp: 2016-12-02T18:35:00.083Z""

#### Expected behavior

The Function App should start triggering with the expected behavior

#### Actual behavior

1. Viewing the C# trigger code, displays an error in a floating popup dialog
2. Function trigger not working

#### Known workarounds

No workarounds as of now.

#### Related information 

Found the code in this Git fork which throws the error: https://github.com/Azure/azure-webjobs-sdk/blob/dev/src/Microsoft.Azure.WebJobs.Host/Blobs/Triggers/BlobTriggerBinding.cs#L70

But I don't know where is this getting set. 

* Languages used: C#, PowerShell
* Source that caused this issue: Actually this is not a issue in source code. 
But here is how my function.json looks like:
{
  "bindings": [
    {
      "name": "blobParameterInMyFunctionApp",
      "type": "blobTrigger",
      "direction": "in",
      "path": "storageContainerName",
      "connection": "storageAccountName_STORAGE"
    }
  ],
  "disabled": false
}

**Comment by fabiocav** [comment]
I just want to confirm, since the SO posts mentions, that you're creating this function app using an ARM template (automation). Is that correct? Or was the app created on the portal?

**Comment by ship2moon** [comment]
No, I didn't use the ARM template. I used the New-AzureRmResource command with -kind parameter set to "functionapp".

**Comment by fabiocav** [comment]
I see.

I've added an answer on SO, but this is being caused by some missing environment settings that are required by the runtime. You can still split those operations, where you use an ARM template to provision the Function App with the settings it needs and use the Kudu API to then push the function if that's a workflow that works better for you.

**Comment by ship2moon** [comment]
Thanks for the quick turn around.
That's a workaround that I will definitely consider. But my customer doesn't want to go with the ARM template way at all, if there is a provision to go via Azure PowerShell by any means.

**Comment by ship2moon** [comment]
Thanks Fabio! I got to know that irrespective of whatever function that we create, a function app needs a storage account which is mandatory!
