### ISSUE TITLE
Host restart when necessary to pick up a different assembly version

### ISSUE THREAD

**Issue by paulbatum** [Azure/azure-webjobs-sdk-script#1023]
When working with changes to a project.json file or private/shared assemblies, its often necessary to manually restart the host process. The most common case is when an assembly that is already loaded by the host process is changed, e.g. changing a version number in a project.json file, or dropping a new version of a dll into a bin folder. Unfortunately the need for a restart is often not obvious the user, and doing the actual restart is slow (multiple clicks to get to the restart command, can take 30 seconds for the restart to take effect).

The experience would be much better if the host could detect common cases where a restart of the process is necessary such as:
1. The project.lock.json file changed (maybe compare a before/after hash of the file?)
2. A new version of a private/shared dll was installed

The host would then log a message and perform the restart.

**Comment by fabiocav** [comment]
Documenting here to document the discussed approach (will keep this updated as we iterate, if required).

A restart will be triggered when:

1. A NuGet restore occurs and:
  1. There was a `project.lock.json` file present (this was not the initial package install)
  2. The resolved dependencies differ from the previous run (the pre-restore and post-restore lock files are different)
2. Private assembly files change (files with the supported assembly extensions `.dll` or `.exe`)
3. Shared assemblies in directories specified in the `watchDirectories` host property

**Comment by lindydonna** [comment]
@paulbatum I assume that you assigned yourself since you're trying to find a new owner?

**Comment by fabiocav** [comment]
@lindydonna @paulbatum I'm actually a bit in limbo with a couple of other tasks and because of some investigation I've been doing on other issues, would be in a good position to knock this one out pretty quickly. 

I'll leave it assigned to Paul but will plan to take this if not reassigned.
