### ISSUE TITLE
CLI: provide a better error message when there's an invalid connection string for AzureWebJobsStorage 

### ISSUE THREAD

**Issue by lindydonna** [Azure/azure-webjobs-sdk-script#1024]
#### Repro steps

1. Create a Azure Function project in Visual Studio

2. Use an invalid connection string for AzureWebJobsStorage in appsettings.json

#### Expected behavior

Error message saying that the connection string for `AzureWebJobsStorage` is invalid

#### Actual behavior

In a loop, you get the following:

```Reading host configuration file 'C:\CDriveCode\Visual Studio Projects\FunctionApp2\host.json'
ScriptHost initialization failed
```

**Comment by lindydonna** [comment]
@soninaren Would this be handled by your fix in the SDK?

**Comment by soninaren** [comment]
No, this is not handled by the SDK fix. Actually we are getting this error. 
`Settings must be of the form "name=value".`
But it is swallowed here 
https://github.com/Azure/azure-webjobs-sdk-script/blob/dev/src/WebJobs.Script/Host/ScriptHost.cs#L503

**Comment by ahmelsayed** [comment]
This issue was moved to Azure/azure-functions-cli#5
