### ISSUE TITLE
EventHub batch processing

### ISSUE THREAD

**Issue by sergsalo** [Azure/azure-webjobs-sdk-script#1029]
It seems like Azure Functions' EventHub binding doesn't allow processing of more than one message at a time, when custom webjob does. This slows down processing dramatically. Are there any plans to add a way to process batch of event hub messages?

Signature for Azure Functions binding: 
`Run(string myEventHubMessage, TraceWriter log)`

Something like: 
`Run(string[] myEventHubMessages, TraceWriter log)`

**Comment by mathewc** [comment]
This is already supported. In a C# function, you can bind to `EventData[] events` or `string[] events`. If this doesn't work for you, please reopen the bug with full details.

**Comment by sergsalo** [comment]
According to this article https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-event-hubs, only next signature is supported:
`public static void Run(string myEventHubMessage, TraceWriter log)`

It is supported in WebJobs itself, but not in Azure Functions' plugin for EventHubs, seems like to me.

**Comment by mathewc** [comment]
The docs don't enumerate all the possible signatures that are supported (many are). The docs should be improved I agree to list the possibilities.

When you say "seems like to me" do you mean you actually tried binding to `EventData[] events` and it doesn't work?

**Comment by sergsalo** [comment]
I will try and let you know.

**Comment by sergsalo** [comment]
It works, but requires "WindowsAzure.ServiceBus":"3.4.2" nuget package to be imported. Thanks.
