### ISSUE TITLE
Log execution timing per trigger type to FunctionsMetrics

### ISSUE THREAD

**Issue by paulbatum** [Azure/azure-webjobs-sdk-script#1030]
We already capture duration per function execution, but no metrics are emitted. Ideally the metrics table would include execution latency.

**Comment by lindydonna** [comment]
The full resolution of this issue is blocked by the next infrastructure update.

**Comment by christopheranderson** [comment]
@mathewc - is this deployed yet?

**Comment by mathewc** [comment]
No - there is a PR out here for it https://github.com/Azure/azure-webjobs-sdk-script/pull/1155. However I can't deploy this until @pragnagopa does some event definition work that this relies on. She said she'd have that done soon.
