### ISSUE TITLE
IoT Hub Triggers?

### ISSUE THREAD

**Issue by 1N50MN14** [Azure/azure-webjobs-sdk-script#1033]
We're porting our AWS Lambda code base to Azure Functions, have not been able to find the relevant documentation for IoT Hub triggers. I'm wondering if we're missing on something here or is it so that IoT Hub triggers are not supported? 

Thanks

**Comment by mathewc** [comment]
We've got an open issue [here](https://github.com/Azure/azure-webjobs-sdk-script/issues/413) tracking this. We don't have IoT Hub trigger yet, but we do have EventHub triggers as you can see.

Feel free to chime in on that other issue and track there for progress.
