### ISSUE TITLE
Log entries are sometimes duplicated

### ISSUE THREAD

**Issue by davidebbo** [Azure/azure-webjobs-sdk-script#1036]
As we found, in some cases, apps get into a state where every log entry appears twice identically in the Azure logs (not user facing logs). And in very rare cases, I've seen them tripled.

**Comment by mathewc** [comment]
I'll get to the bottom of this

**Comment by mathewc** [comment]
Closing this because we don't believe there is a runtime issue here. We have an internal thread going on this - it appears that this is an MDS infrastructure issue.
