### ISSUE TITLE
Always seems to set content type to Application/json

### ISSUE THREAD

**Issue by AndyCross** [Azure/azure-webjobs-sdk-script#1038]
Run this: https://github.com/Azure/azure-webjobs-sdk-script/blob/d485616f4919fa22e984365a82fd3fab12869692/sample/HttpTrigger/index.js#L24

The content type set is always application/json

Is the sample current?

**Comment by lindydonna** [comment]
@mamaso Please investigate, could be related to changes in content negotiation. 

Investigation should be in this milestone though fix might not be.

**Comment by mamaso** [comment]
I can't repro this, @AndyCross are you using the latest version of functions (~1)?

**Comment by mathewc** [comment]
I can't repro this either in production. Closing as no repro.
