### ISSUE TITLE
Event Hub trigger against node.js function ends in deadlock

### ISSUE THREAD

**Issue by timfpark** [Azure/azure-webjobs-sdk-script#1040]
#### Repro steps

1. Set up an Azure Function and configure an app setting with key name "AzureWebJobsEventHubReceiver" to a connection string for an Azure Event Hub with existing events in it.  (Contact me directly for mine if that makes it easier.)

2. Set up continuous integration with https://github.com/timfpark/af-eh-test

3. Go to the monitor tab
 
#### Expected behavior

Expected to see messages relayed to the log.

#### Actual behavior

No log messages and Azure function runs to the 5 minute maximum.

#### Known workarounds

Provide a description of any known workarounds.

#### Related information 

Used node.js with 1.0 Azure Functions engine.

**Comment by tohling** [comment]
Can you try to look at the log entries in the log files directly and confirm that you are seeing all `Function started (<some guid>) `and no corresponding `Function completed (<some guid>) `for your Function executions?

Here are the steps to access the log files for your Function:

1. Visit Function portal and open your Function app.
2. Click on **Function app settings -> Go to Kudu**.  This will launch the Kudu console. 
3. Click on **LogFiles->Application->Functions->Function-><YourFunctionName>**
4. Open the most recent log file to view all the log entries.  

While there may be many consecutive `Function started (<some guid>) `entries, there should be corresponding `Function completed (some guid>)` entries for all successfully executed Functions.  If you are not seeing this or are seeing errors in your log entries, then your Function execution did not complete successfully.

**Comment by lindydonna** [comment]
Assigning to @tohling for investigation.

**Comment by tohling** [comment]
When there are large number of events and the Function has a configuration that does not process events in batches will experience the problem that customer is reporting.  Log entries will show mostly Function started (<some guid>), without corresponding Function completed (<some guid>) entries.  The events that triggered each function invocation does not seem to be check-pointed.  Additionally, these invocations eventually time out.

Updating the function.json and index.js content to process events in batches seem to resolve the issue.  I have suggested this change to the customer and am awaiting his response.

@mathewc , specific to the EventHub scenario, where in the typical scenario, we would be processing large number of events, would it be better to remove the single event processing template and just provide the batch approach in the template?

**Comment by tohling** [comment]
Customer confirmed that issue is resolved when events are processed in batches.
