### ISSUE TITLE
CLI: keep console window open if there's a crash

### ISSUE THREAD

**Issue by lindydonna** [Azure/azure-webjobs-sdk-script#1064]
When launching the CLI from Visual Studio, if there's a CLI bug or other error that causes the host to crash, the window closes immediately. Investigate whether there's a way to keep the window open from the CLI. 

Alternatively, we could change the way Visual Studio launches the exe.

**Comment by ahmelsayed** [comment]
is there a sample repro I can run for a crash within a function that takes the app down? I tested 8ad8ea0947ba13568707af59090fc78b6a7b0f99 by adding a random nullref and it seems to work, but I want to verify with some real scenario.
