### ISSUE TITLE
CLI: host error messages do not appear in console window

### ISSUE THREAD

**Issue by lindydonna** [Azure/azure-webjobs-sdk-script#1066]
Reported by @paulbatum. He had to look at host log files in %tmp%\LogFiles.

**Comment by lindydonna** [comment]
@ahmelsayed I moved this to 0.10 since hopefully it's an easy fix. I forgot to tag it as CLI earlier.

**Comment by ahmelsayed** [comment]
sorry I don't think I remember what this is for. Is there a repro I can try?

**Comment by paulbatum** [comment]
@ahmelsayed To repro, paste this into host.json:

```
  "eventHub": {
    "maxBatchSize": 1,
    "prefetchCount": 2
  }
```

**Comment by ahmelsayed** [comment]
Do I have to have an eventHub function? this doesn't generate any errors for me in both the console and `%tmp%\LogFiles`. I'm testing with the latest CLI+host though. I don't know if something else might be different.

**Comment by paulbatum** [comment]
You probably need an event hub function. I doubt these settings are read otherwise.

**Comment by ahmelsayed** [comment]
ah I see. I can repro now.

@fabiocav \ @mathewc  I'll need some help from you guys. [this line](https://github.com/Azure/azure-webjobs-sdk-script/blob/8a09f3719ff82dd69b3670dd25fbacf3dab7b1a1/src/WebJobs.Script/Host/ScriptHostManager.cs#L161) is the offender. It get's the exception, in this case it's a `System.ArgumentOutOfRangeException` with this message `The value supplied must be between 10 and 2147483647.\r\nParameter name: PrefetchCount\r\nActual value was 2.`  but it doesn't print it to the console. It just prints `A ScriptHost error has occurred` 
What is the right fix here?

**Comment by ahmelsayed** [comment]
This issue was moved to Azure/azure-functions-cli#4
