### ISSUE TITLE
Document all App Settings in one place

### ISSUE THREAD

**Issue by davidebbo** [Azure/azure-webjobs-sdk-script#1077]
Was looking at @paulbatum's answer to http://stackoverflow.com/questions/41381486/how-to-disable-azure-function-homepage mentioning `AzureWebJobsDisableHomepage`, and could not find it documented anywhere (couple of mentions in #843 and #848).

We should create a one-stop page with all the settings, similar to what we have on https://github.com/projectkudu/kudu/wiki/Configurable-settings.

**Comment by jeremy001181** [comment]
has this been worked on? if so, what is the link to the doc?

**Comment by fabiocav** [comment]
@jeremy001181 this is assigned, but hasn't been addressed yet. We hope to have an initial draft available in the public Wiki very soon.

**Comment by mathewc** [comment]
I've added a new wiki page here: https://github.com/Azure/azure-webjobs-sdk-script/wiki/Configuration-Settings. I'll add all the current settings there, and we'll add new ones there going forward.
