### ISSUE TITLE
Azure Function not triggered by Event Hub

### ISSUE THREAD

**Issue by navilwayne** [Azure/azure-webjobs-sdk-script#1079]
Hi Folks

-  I have a Event Hub Trigger function app with consumption plan. It was working, when I open the portal in UI & continue to run for 3-4 hours , after that it automatically sleeps, when no request coming to event hub.  I am facing the same issue for last 2 weeks.
- Next day when request come again , it is not triggering, until I open portal.

- I have to swap forcefully from Consumption Plan to App Service Plan to run this.

When we can expect fix for Consumption Plan????

Thanks.

**Comment by christopheranderson** [comment]
Related post - https://github.com/Azure/Azure-Functions/issues/122

Addressed now as EntityPath issue
