### ISSUE TITLE
Function Graceful Shutdown Support

### ISSUE THREAD

**Issue by mathewc** [Azure/azure-webjobs-sdk-script#108]
Related to https://github.com/Azure/azure-webjobs-sdk-script/pull/106.

There is remaining work to do to get e2e graceful shutdown working. We also need to flow the CT into JobHost - we're not doing that currently (JobHost.Start in ScriptHostManager). Doing so allows the end to end scenario to work - In your C# function you can bind to CancellationToken to receive shutdown notification and do graceful shutdown within a single function (as in [sample here](https://github.com/Azure/azure-webjobs-sdk-samples/blob/master/BasicSamples/MiscOperations/Functions.cs)). We might also find a way to support this in other languages as well, i.e. have the various language invokers monitor the cancellation token and do the right thing.

**Comment by fabiocav** [comment]
Makes sense. I'll get this done this morning.

**Comment by fabiocav** [comment]
Resolved by #111
