### ISSUE TITLE
Improve handling when a site is deleted and recreated with same storage account

### ISSUE THREAD

**Issue by davidebbo** [Azure/azure-webjobs-sdk-script#1080]
Steps:

- Create app from portal
- Delete the app but not the storage account
- Recreated an app with the same name, pointing to the existing storage account

At this point, the app is busted because it still has the `D:\home\data\Functions\secrets\host.json` for the old app, with a mismatched machine key.

Things we can improve here:

- Find some way to prevent users from getting into this situation in the first place. Not exactly sure how, but let's think about it.
- Better logging. I found that there were no entries in the function logs at all.
- Better error message coming back to the user. All they get now is "We are unable to reach your function app", and they have no idea what's wrong.

**Comment by christopheranderson** [comment]
Suggestion: Change creation workflow to append GUID to the Azure Files Share name to prevent repeat shares.

**Comment by lindydonna** [comment]
FYI @davidebbo, I've created this issue to track (plus one in TFS): https://github.com/projectkudu/AzureFunctionsPortal/issues/893. I think we can close this item as a duplicate.

**Comment by lindydonna** [comment]
Resolved by https://github.com/projectkudu/AzureFunctionsPortal/issues/893
