### ISSUE TITLE
Upgrade `~0.9` -> `1` breaks app settings unless loaded via external file in F#

### ISSUE THREAD

**Issue by mjgpy3** [Azure/azure-webjobs-sdk-script#1088]
Values being read from App settings in F# are coming through as `null`.

#### Repro steps

  1. Add an app setting to a functions app
  2. In an F# function's `run.fsx` attempt to read the app setting using something like
```fsharp
let mySetting = System.Environment.GetEnvironmentVariable("MY_APP_SETTING")
```
 3. Run the function app and observe (via `log.Info` for example) that `mySetting` is `null`.

#### Expected behavior

`mySetting` has the value that was configured in the function app settings.

#### Actual behavior

`mySetting` is `null`.

#### Known workarounds

It seems that putting this loading code in an external, shared `fsx` file (e.g. `../shared/settings.fsx`) then using `#load "../shared/settings.fsx"`, then `open Settings` causes the app settings values to come through. I'm not sure if it's a timing issue or something else.

**Comment by christopheranderson** [comment]
We cannot repro. I just ran this:

```
#r "System.Net.Http"
#r "Newtonsoft.Json"

open System.Net
open System.Net.Http
open Newtonsoft.Json

type Named = {
    name: string
}

let Run(req: HttpRequestMessage, log: TraceWriter) =
    async {
        log.Info(sprintf 
            "F# HTTP trigger function processed a request.")

        let mySetting = System.Environment.GetEnvironmentVariable("FUNCTIONS_EXTENSION_VERSION");
        log.Info(mySetting);

        // Set name to query string
        let name =
            req.GetQueryNameValuePairs()
            |> Seq.tryFind (fun q -> q.Key = "name")

        match name with
        | Some x ->
            return req.CreateResponse(HttpStatusCode.OK, "Hello " + x.Value);
        | None ->
            let! data = req.Content.ReadAsStringAsync() |> Async.AwaitTask

            if not (String.IsNullOrEmpty(data)) then
                let named = JsonConvert.DeserializeObject<Named>(data)
                return req.CreateResponse(HttpStatusCode.OK, "Hello " + named.name);
            else
                return req.CreateResponse(HttpStatusCode.BadRequest, "Specify a Name value");
    } |> Async.RunSynchronously
```

Got the value logged properly:

```
2017-01-09T18:37:46.481 Function started (Id=3e5827b6-f9df-4bdf-a611-97351f100217)
2017-01-09T18:37:46.481 F# HTTP trigger function processed a request.
2017-01-09T18:37:46.481 ~1
2017-01-09T18:37:47.269 Function completed (Success, Id=3e5827b6-f9df-4bdf-a611-97351f100217)
```

Closing no repro for now

**Comment by mjgpy3** [comment]
Thanks for trying that out!

One difference is that I was doing something along the lines of
```fsharp
open System.Net
open System.Net.Http
open Newtonsoft.Json

let mySetting = System.Environment.GetEnvironmentVariable("FUNCTIONS_EXTENSION_VERSION");

type Named = {
    name: string
}

let Run(req: HttpRequestMessage, log: TraceWriter) =
  log.Info (sprintf "%A" mySetting)
```

Specifically, I was setting `mySetting` inside of the `#else` of a `!COMPILED` precompiler directive, in order to differentiate the deployed Azure Functions environment and my local environment.

Do you think that could be making the difference? Is putting such `let`s not allowed outside of `Run`, or inside of `!COMPILED`?
