### ISSUE TITLE
Improve logging of Function Timeouts

### ISSUE THREAD

**Issue by mamaso** [Azure/azure-webjobs-sdk-script#1090]
Currently a function which times out is not treated as a success or failure, we should emit an event to track these failures

**Comment by paulbatum** [comment]
@mamaso Can you clarify, is this about how the execution of the function is represented in our storage based logging and how it appears to the user on the monitoring tab? Or is this about our internal telemetry?

**Comment by mamaso** [comment]
I believe both.

Currently the core sdk logs that there is a function failure when there is a timeout.  However, at the script host level this is untracked, i.e. there is no 'Function completed (Failure/Timeout ...)' event.

I can show you in FunctionsLogs if you like, @christopheranderson also had a viz which showed the issue.

**Comment by paulbatum** [comment]
OK so for every timeout I think we want two things:
1. FunctionsLog entry indicating the execution timed out
2. FunctionsMetrics timeout entry

Sounds good?

**Comment by mamaso** [comment]
Yep, sounds good!

**Comment by paulbatum** [comment]
@mamaso Well @fabiocav and @mathewc think there should be an entry in FunctionsLog... you don't see it?

**Comment by christopheranderson** [comment]
@mamaso - poke

**Comment by mamaso** [comment]
Ah, missed some clarification here, we have the FunctionsLog entry, but we don't have a FunctionsMetrics timeout entry
