### ISSUE TITLE
Add ability to capture console output

### ISSUE THREAD

**Issue by mamaso** [Azure/azure-webjobs-sdk-script#1095]
Useful for debugging purposes
- could capture EDGE_DEBUG output
- could log outside of context scope (any initialization code outside the user's exported function)
- capture debug output from any node modules

Globally scoped, hacky, but helpful to track down issues

**Comment by mathewc** [comment]
What is EDGE_DEBUG output, and this other debug output from modules you refer to? Can you give some examples?

**Comment by christopheranderson** [comment]
Related: https://feedback.azure.com/forums/355860/suggestions/19710157
