### ISSUE TITLE
function.json errors are not surfaced in function level log

### ISSUE THREAD

**Issue by davidebbo** [Azure/azure-webjobs-sdk-script#110]
Steps:

- Create a new js http function
- In the binding file, change `"type": "httpTrigger"` to `"type": "httpTrigger2"`
- In develop tab, click Run

Result: you get a 404, acting as if the function doesn't exist.

The host log shows the real problem:

```
2016-03-16T17:11:28 The following 1 functions are in error:
http: 'httpTrigger2' is not a valid binding type.
```

We need to show this as a function level error.

Note that this is distinct from #109 and #71, which caused the whole host to die. Here, the host is healthy, but this one function failed with bad error handling.

**Comment by mathewc** [comment]
Need to find out if @ahmelsayed did the portal work to consume the function status API I mentioned. That would address this.

**Comment by davidebbo** [comment]
Is there a portal bug tracking this? If not, please open one, with info on what API looks like.

**Comment by mathewc** [comment]
Created portal bug https://github.com/projectkudu/WebJobsPortal/issues/104
