### ISSUE TITLE
Allow selection of start time for Trigger functions

### ISSUE THREAD

**Issue by martinabbott** [Azure/azure-webjobs-sdk-script#1100]
When creating a trigger Function, the trigger fires immediately for any resources that have been added to the trigger location since the Function App was created.

This can cause issues as it is possible to create a situation where you re-process information already handled by another function, since the portal allows you to create one pointing to a location already watched by another function.

Would it be possible to implement something like in Stream Analytics so that when you create a trigger function, you could declare that it starts processing immediately, or only when new resources are added from the point of creation of the function rather than the Function App.

**Comment by christopheranderson** [comment]
We kind of understand what you're asking, but could you provide a specific scenario to help us know what exactly you want? Do you want 2 Functions to independently process the same info or not?

**Comment by martinabbott** [comment]
Hey @christopheranderson, not really needing to process the same info, there may be a use case for that but in my case I found this to be a problem when I was trying to get something else working. In my case I needed to create a new function for one that was not working (since found out that somehow it had become disabled although I don't know why), so I created a new function and it started processing ALL files currently in the folder.

In my case, and I'd expect in others, this was not desirable as it meant reprocessing all the files. I let the process run to completion without any additional code in the trigger, but it was still not ideal.

In my mind I see this almost like the checkpoint process in Event Hub where when I create processing I can say start from now, start from custom date, start from last run, like in Stream Analytics.

**Comment by mathewc** [comment]
What kind of trigger are you dealing with here?

I'll say that the discovery process for each trigger type is implemented differently. Not all underlying sources (e.g. Queues, ServiceBus) are going to support checkpointing, so there really isn't a generalized mechanism for us to put in place.

**Comment by martinabbott** [comment]
In my case it is Blob trigger, but yes it only makes sense where the underlying trigger type is against a source that is essentially a stream of data.

In that instance, of course anything that has transient messages, Queues and Service Bus as you say as examples, won't work because the message read by the trigger is volatile.

**Comment by mathewc** [comment]
For BlobTrigger, you're right that currently it will trigger on any blobs existing in the target container that haven't already been processed. The determination of whether a blob has been processed is done by us maintaining "receipts" in a system blob container azure-webjobs-hosts. These receipts are scoped per function app, so you're right that if you have 2 different function apps each with a function monitoring the same container, both will process the blobs.

@christopheranderson If this turns out to be something we want to enable, we should move this to the SDK repo.

**Comment by martinabbott** [comment]
Hey @mathewc I'm thinking more along the lines of a new function in a new Function App being written to take the place of some other solution that has already processed files, rather than 2 functions processing the same blob trigger which I can imagine may cause a lot of problems.

However, the solution is the same, an ability to be able to define a "start date" from which to start processing new files rather than just processing all files.

Regarding the scoping, I've had 2 functions in the same Function App both process the same files, although this was in a Function App where the original function had become disabled somehow, so I don't know if there is a separate thing there.

**Comment by paulbatum** [comment]
@martinabbott I know its somewhat hacky, but a common workaround for this scenario is to setup your new function but to remove the actual processing logic. It would trigger over all your blobs but it doesn't do anything other than record that its processed all those blobs. Then you go ahead and re-add your processing logic.

We have some long term plans around significant modifications of how blob triggers work internally. These modifications are likely to change the default behavior to only process new blobs. If this pans out it will be a permanent solution to this issue. In the meantime, the above workaround is probably the best option.

Please reopen if you think further discussion is necessary!
