### ISSUE TITLE
Python Queue Function Unable to Locate Modules

### ISSUE THREAD

**Issue by paulbatum** [Azure/azure-webjobs-sdk-script#1110]
_From @MisterJames on January 6, 2017 21:16_

I am using Python 2.7 and have a module which cannot install via `pip`. I have created a wheel using [these instructions](https://blogs.msdn.microsoft.com/azureossds/2015/06/29/install-native-python-modules-on-azure-web-apps-api-apps/) and uploaded the wheel into a `wheelhouse` directory in the function.
 
![image](https://cloud.githubusercontent.com/assets/1197383/21732982/dbb94bc8-d421-11e6-99df-e0162add2dc5.png)

And here is the wheel in that directory:

![image](https://cloud.githubusercontent.com/assets/1197383/21733013/f6bb0498-d421-11e6-932d-d4dd5561cdbf.png)

I've added a `requirements.txt` to the root of the function with the following content:

    --find-links wheelhouse
    yara-python==3.5.0

If I run `d:\python27\python.exe -m pip install -r requirements.txt` from the Kudu console I see the following error:

    error: Microsoft Visual C++ 9.0 is required (Unable to find vcvarsall.bat). Get it from http://aka.ms/vcpython27

But I don't think the above is a fruitful path to follow as I won't have the rights I need to get vc++ installed methinks.  And my understanding was that if the wheel were being used, that it shouldn't need a compile at this juncture.

I have added a `import yara` statement to the top of my Python script. If I try to save/run the Function from the Azure Portal, I see the following error in the logs:

    2017-01-06T21:03:22.454 Exception while executing function: Functions.buildRule. Microsoft.Azure.WebJobs.Script: Traceback (most recent call last):
    File "D:\home\site\wwwroot\buildRule\run.py", line 2, in <module>
    import yara
    ImportError: No module named yara

Is there another way to bring in this dependency? Is there a way to hint to Python/Functions that I want to use the precompiled wheel?  

_Copied from original issue: Azure/azure-webjobs-sdk-templates#388_

**Comment by paulbatum** [comment]
_From @tohling on January 6, 2017 23:27_

Resolving the error "_Unable to find vcvarsall.bat_" requires the installation of [Microsoft Visual C++ Compiler for Python 2.7](https://www.microsoft.com/en-us/download/details.aspx?id=44266) (See Details section)

Even if we were able to install this package, there are 2 issues worth noting:

1. Under the **System Requirements** section, it states,

    **Supported Operating System**
    Windows 7, Windows 8, Windows 8.1

    The Azure Functions infrastructure runs on Windows Server 2012.  There may still be issues during runtime.

2. We may engage VS team for an update, but under the **Details** section, it states,
"This compiler package is entirely unsupported..."

Have you tried using Python 3 to see if it will resolve the issue?  Here are the instructions: https://github.com/Azure/azure-webjobs-sdk-script/wiki/Using-a-custom-version-of-Python

**Comment by paulbatum** [comment]
_From @MisterJames on January 8, 2017 5:6_

Great, thanks for the suggestions @tohling, I'll explore this to see if Python 3 is a solution here.

**Comment by christopheranderson** [comment]
Will reopen if there is further issues
