### ISSUE TITLE
Don't return "application/json" when respnse JSON start with arry by HTTP trigger 

### ISSUE THREAD

**Issue by kuniteru** [Azure/azure-webjobs-sdk-script#1116]
I use PHP on Azure Functions with HTTP trigger.

Azure Functions has an issue when Function responses JSON object that start with array.
I expect to get response with "application/json" Content-Type when I send like this request, but Function returns "application/xml".
[JSON example]
```json
[
  {
    "faceId": "2e2a4644-7b63-4af8-bfde-2076e48603cd",
    "faceRectangle": {
      "top": 135,
      "left": 514,
      "width": 59,
      "height": 59
    }
  },
  {
    "faceId": "3b072d97-117a-4b7c-906f-8074a4fb32f8",
     "faceRectangle": {
       "top": 106,
       "left": 165,
       "width": 55,
       "height": 55
    },
  }
]
```
Such JSON format is returned by Face API(Detect) of Microsoft Cognitive Services.
https://dev.projectoxford.ai/docs/services/563879b61984550e40cbbe8d/operations/563879b61984550f30395236

**Comment by mathewc** [comment]
I was able to reproduce this behavior - something does seem wrong here. @mamaso do you have time to look into this? If a JSON array payload is returned from a PHP script, we should be handling it correctly, as we do when a JSON object is returned.

**Comment by mamaso** [comment]
Yep I'll take a look.
