### ISSUE TITLE
Add Automatic Dependency Download to Functions

### ISSUE THREAD

**Issue by solvingJ** [Azure/azure-webjobs-sdk-script#1119]
If my understanding of dependency management in Azure Webjobs/Functions is incorrect, then this feature request might be invalid, otherwise it seems a very logical feature request. 

Continuous Integration (Deploy from GIT) is a brilliant concept:
-The Azure Platform clones, builds, and executes code directly from source. 
-Developers can simply push new code, and it updates the production environment

There are many complexities with building a system to do this, therefor it's impressive and I'm excited about using it.  The option to bypass the build step in CI/CD systems like Jenkins (when possible) feels like a step forward as an industry. 

However, it seems an obvious expectation from a system that builds and executes code from source, that it automatically download dependencies from the relevant package manager before building and running.  I would go as far as to call it a basic requirement, although that's debatable.

My understanding is that the developer must currently go "out-of-band" and manually invoke the relevant package manager (via Kudu, or shell script etc).  There's also an option to include your dependencies in the GIT repo for your function, or "upload" them manually to the environment.   None of these options seem acceptable in my opinion. 

Please add automatic dependency download for all supported languages into the platform because:

1.  The elegance and efficiency of the whole workflow is drastically diminished without it
2.  It's likely that the vast majority of Azure functions will have dependencies 
3.  Compared to the other features of Azure Functions, it seems trivial to implement

**Comment by solvingJ** [comment]
I now believe that this is already done for C# during the dynamic compilation process based on this SO post.  Can anyone confirm?

[http://stackoverflow.com/questions/36411536/how-can-i-use-nuget-packages-in-my-azure-functions](http://stackoverflow.com/questions/36411536/how-can-i-use-nuget-packages-in-my-azure-functions)

Can anyone clarify the same question for NodeJS/JavaScript?
 
Thus, this request might only apply to a later time when deeper runtime support for PHP, Python, Java, and other languages are being added.

**Comment by fabiocav** [comment]
@solvingJ automatic package restore is indeed handled by the runtime for .NET functions (C#/F#).

In the context of CD/CI, App Service (which is what Azure Functions is built on) will restore Node packages specified in a `packages.json` file at the site root. So that is handled as well.
