### ISSUE TITLE
I'd like some reference style docs

### ISSUE THREAD

**Issue by SteveALee** [Azure/azure-webjobs-sdk-script#1120]
The [docs](https://docs.microsoft.com/en-us/azure/azure-functions) are good but are firmly in the examples / tutorials camp. This very useful but in one case I've really wanted more formal ref style docs - namely the ```res``` and ```req``` arg bindings for HTTPTriggers, specifically for the nodejs bindings

We can see from the [javascript code](https://github.com/Azure/azure-webjobs-sdk-script/blob/master/src/WebJobs.Script/Content/Script/http/response.js) that the ```res``` supports several properties and methods but ```req``` is pretty mysterious as the properties seem to be dynamically added.

Ideally something like the win32 sdk docs would exist. 

I guess life with open source is a little more fluid (or is that complex) than having the docs only as we do with closed source. Do we treat the code as the docs? And if so, can we assume all methods we see are part of a fairly stable contract so are unlikely to change with subsequent versions? 

Or are some considered temp or internal so should not be used?  I can't say "undocumented" with open source hehe  :-)

**Comment by SyntaxC4** [comment]
Hi Steve, It looks like you've tracked this bug in multiple places. Can we consolidate on https://github.com/Azure/Azure-Functions/issues/156 as the tracking Issue?

**Comment by SyntaxC4** [comment]
@christopheranderson - We can close this issue down as it's tracked in Azure-Functions.

**Comment by SteveALee** [comment]
@SyntaxC4 Thanks, yes indeed. I tried to find I over there and thought I must have not actually submitted. It was a mistake to do it here!

Closing as Duplicate of Azure/Azure-Functions#156
