### ISSUE TITLE
'Never Finished' function timeout in non-Dynamic SKU

### ISSUE THREAD

**Issue by laurence-hudson-tessella** [Azure/azure-webjobs-sdk-script#1121]
I am currently experiencing timeouts for non-trivial queue triggered azure functions when running in a non-Dynamic SKU. While it is clear that dynamic/consumption plans (#18) are intended to have max run time of 5 minutes, it looks like traditional app service plans are not supposed have a timeout (#657, #661).

I'm consistently seeing a timeout of ~8 minutes followed by a retry of the function.

My host.json does not specify a timeout (although I tried adding a 1h setting, but it had no impact).

My host.json does set queues.maxDequeueCount=1. Given this it seems wrong that the function continues to invoke repeatedly.

Am I missing something? Are these timeouts expected for this type of app service plan?

#### Expected behavior

Function invokes from a queue item.
Function runs until complete (no timeout set in `host.json` & not running in dynamic/consumption plan)
Function status changes to 'Success' (or 'Failed')

#### Actual behavior

Function invokes from a queue item.
After ~8 minutes the function invocation status changes to "Never Finished". 
After ~2 more minutes the a new function invocation starts triggered from the same queue item (new context guid)
Repeat forever (or a least a few days).

Example function invocation log:
```
FUNCTION	STATUS	STATUS DETAIL
model ({"modelRunId":"UAS ...)	Running	4 minutes ago (2 minutes running time)
model ({"modelRunId":"UAS ...)	Never Finished	14 minutes ago ( running time)
model ({"modelRunId":"UAS ...)	Never Finished	29 minutes ago ( running time)
model ({"modelRunId":"UAS ...)	Never Finished	39 minutes ago ( running time)
model ({"modelRunId":"UAS ...)	Never Finished	49 minutes ago ( running time)
model ({"modelRunId":"UAS ...)	Never Finished	59 minutes ago ( running time)
```

#### Related information 
Function Language=JS
FUNCTIONS_EXTENSION_VERSION=~1
WEBSITE_NODE_DEFAULT_VERSION=6.5.0
WEBSITE_NPM_DEFAULT_VERSION=3.7.3
Always On=On
Platform=64-bit
App Service Plan=Standard: 1 Large
queues.maxDequeueCount=1

**Comment by paulbatum** [comment]
@brettsam can you take a look at this and see if you can figure out if its timeout related? I wonder if instead the process is crashing and thats why the status appears as never finished.

**Comment by brettsam** [comment]
@laurence-hudson-tessella -- can you tell me your **Function App** name either directly or [indirectly](https://github.com/projectkudu/kudu/wiki/Reporting-your-site-name-without-posting-it-publicly)? Then I can dig into some logs to see if I can figure out what's happening.

**Comment by brettsam** [comment]
@laurence-hudson-tessella -- are you able to share any more info with us? If so, I can try to see if I can narrow down what you were seeing.

**Comment by lindydonna** [comment]
@laurence-hudson-tessella Closing due to lack of customer response. Please reopen if you see the issue again, along with the **Function App** name
