### ISSUE TITLE
Invoke API should return an invocation id

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-webjobs-sdk-script#1122]
Please provide a succinct description of the issue.
We need a way to query logs for a specific invocation. This is a requirement for azure extension for [Serverless ](https://github.com/serverless/serverless)framework.
Runtime needs to be updated to return an invocationId on [invoke operation via admin api](https://github.com/Azure/azure-webjobs-sdk-script/blob/7c7c96d8de5dc6f340f683d3912e63dc216f3008/src/WebJobs.Script.WebHost/Controllers/AdminController.cs#L35).

* Programming language used 
* Links to source

**Comment by christopheranderson** [comment]
We already have logs in the dashboard which we can grab. We need an invocation id to be returned from invoke API.

**Comment by christopheranderson** [comment]
closing in favor of new issue
