### ISSUE TITLE
Precompiled Azure Functions with Dependency Error

### ISSUE THREAD

**Issue by justinyoo** [Azure/azure-webjobs-sdk-script#1133]
Hi, Team.

I know how to use `precompiled` Azure Functions by following the [official document](https://github.com/Azure/azure-webjobs-sdk-script/wiki/Precompiled-functions). It just works fine.

However, when I put the `TraceWriter` instance like:

    using System.Linq;
    using System.Net;
    using System.Net.Http;
    using System.Threading.Tasks;
    
    using Microsoft.Azure.WebJobs.Host;
    
    namespace PrecompiledLibraries
    {
        public class MyHttpTrigger
        {
            public static async Task<HttpResponseMessage> Run(HttpRequestMessage req, TraceWriter log)
            {
                log.Info($"C# HTTP trigger function processed a request. RequestUri={req.RequestUri}");
    
                // parse query parameter
                string name = req.GetQueryNameValuePairs()
                    .FirstOrDefault(q => string.Compare(q.Key, "name", true) == 0)
                    .Value;
    
                // Get request body
                dynamic data = await req.Content.ReadAsAsync<object>();
    
                // Set name to query string or body data
                name = name ?? data?.name;
    
                return name == null
                    ? req.CreateResponse(HttpStatusCode.BadRequest, "Please pass a name on the query string or in the request body")
                    : req.CreateResponse(HttpStatusCode.OK, "Hello " + name);
            }
        }
    }

It throws an error like below:

![](https://i.stack.imgur.com/Y3PJz.png)

> The following 1 functions are in error:
>
> HttpTriggerCSharp: Could not load file or assembly 'Microsoft.Azure.WebJobs.Host, Version=1.1.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.

That library actually a dependency of Azure Functions and there's no need to load.

Not sure this is a bug of either:

* Azure Functions itself,
* Azure Functions CLI,
* Visual Studio Tooling, or
* something else

Could you have a look into this, please?

**Comment by christopheranderson** [comment]
Could you provide the Function.json and the directory structure/files you are using when you run locally?

**Comment by fabiocav** [comment]
Can you also try to upgrade your reference to the WebJobs SDK 2.0.0 and give it another shot.

**Comment by justinyoo** [comment]
@christopheranderson @fabiocav Thanks! Once I update the reference SDK version to 2.0.0-beta2, it works. We might need to document the version of referencing SDK for external assemblies.

**Comment by fabiocav** [comment]
We have a couple of ideas to make that better than just relying on docs. One of them being a meta-package you can reference that would ensure you have the right dependencies.

**Comment by christopheranderson** [comment]
Resolved
