### ISSUE TITLE
Referencing Nuget in External Assembly and Azure Function throws a runtime exception

### ISSUE THREAD

**Issue by petrce** [Azure/azure-webjobs-sdk-script#1137]
#### Repro steps
If I am using the same type from custom Nuget Library (net46 classic .csproj) in **both External Assembly and Azure Function** and I am using this Nuget type for calling a method from External Assembly the Azure Function fails locally in VS2015.

e.g.:
```
#r "..\lib\NotificationService.dll"
using <NugetLibrary>;

public static void Run(<TypeFromNugetlibrary> itemFinishedEvent, TraceWriter log)
{
  var notificationService = new NotificationService();
  notificationService.ProcessMail(itemFinishedEvent);
}
```

#### Expected behavior

No error displayed.

#### Actual behavior

Error during local debugging:
```
Function completed (Failure, Id=acf0c57c-5289-4074-a139-fc037b556b26)
A ScriptHost error has occurred
Exception while executing function: Functions.MessageTrigger. mscorlib: Exceptio
n has been thrown by the target of an invocation. f-MessageTrigger__-1951563235:
 Could not load file or assembly '<Nuget Library>, Ver
sion=1.0.8.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
The system cannot find the file specified.
Exception while executing function: Functions.MessageTrigger
Executed 'Functions.MessageTrigger' (Failed, Id=acf0c57c-5289-4074-a139-fc037b55
6b26)
  Function had errors. See Azure WebJobs SDK dashboard for details. Instance ID
is 'acf0c57c-5289-4074-a139-fc037b556b26'
```

#### Known workarounds

add post-build step to your external assembly, e.g.:
`xcopy /Y $(TargetDir)<Nuget library dll name>.* $(SolutionDir)src\AzureFunction\lib`

and add to your function:
`#r "..\lib\<Nuget library dll name>.dll"`

**Comment by davidgouge** [comment]
I've seen this same behaviour with the WindowsAzure.Storage nuget package but have so far been unable to reliably reproduce.  The FusionLog in the exception shows that the 'old' version of the DLL that's supplied in the same folder of func.exe is the one that is trying to load instead of the nuget one.

**Comment by fabiocav** [comment]
@petrce this is a current limitation of the VS tools and will be addressed in the next release. 

There's an existing issue tracking this here: https://github.com/Azure/Azure-Functions/issues/90, you can watch for updates there.
