### ISSUE TITLE
Nuget Packages Not Found in Precompiled Azure Function

### ISSUE THREAD

**Issue by ansario** [Azure/azure-webjobs-sdk-script#1143]
When using Application Insights 2.2.0 in an Azure Function csx, there is no issue. When using the same in a pre compiled Azure Function, an error is thrown: 

#### Repro steps

Create an Azure Function and simply instantiate a Telemetry Client in a csx file. This should work fine. Doing the same in a precompiled function results in an error.

#### Expected behavior

No Error

#### Actual behavior

Exception while executing function: Functions.Trigger. mscorlib:
 Exception has been thrown by the target of an invocation. Test.
AzureFunctions: Could not load file or assembly 'Microsoft.ApplicationInsights,
Version=2.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its
 dependencies. The system cannot find the file specified.

#### Known workarounds

Add the compiled nuget package dlls at the same level as the compiled function, not a lower bin directory as an external reference would be added.

#### Additional Information

Clearing the nuget folder and reinstalling packages does not help.

**Comment by fabiocav** [comment]
For precompiled functions, there's no package resolution at runtime. The behavior here is similar to deploying other application types (console, web, etc.) where its dependencies should be deployed with it. 

You want to deploy everything that is in the output of your project.
