### ISSUE TITLE
[NodeJS]Creating documentdb client in javascript function is taking upto 20secs

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-webjobs-sdk-script#1147]
Sometimes, creating documentdb client in javascript function is taking upto 20secs. This does not happen consistently. Does not repro when running locally. 
Need to investigate further.

#### Repro steps

Provide the steps required to reproduce the problem

1. Create a javascript funtion: TimerTrigger.

2. Add pacakage.json including dependency on documentdb module

Function code:

module.exports = function (context, myTimer) {
    var timeStamp = new Date().toISOString();
    
    if(myTimer.isPastDue)
    {
        context.log('JavaScript is running late!');
    }
    context.log('JavaScript timer trigger function ran!', timeStamp);   
    
	var DocumentClient = require('documentdb').DocumentClient;
 
	var host = "DocDBEndpoint";
	var masterKey = "DocDb master key"; 
    var docDbClient = new DocumentClient(host, { masterKey: masterKey });
    context.log("created docdb client");
 context.done();
};

#### Expected behavior

no delay in creating docDb client.

#### Actual behavior

From the logs:
2017-01-24T19:10:00.869 Function started (Id=a5faa2c0-a69a-424e-a99a-88756161db15)
2017-01-24T19:10:20.620 created docdb client

Sometimes takes up to 20secs

Provide any related information 

Language: Nodejs
* Links to source

**Comment by yvele** [comment]
@pragnagopa Maybe related to https://github.com/Azure/azure-webjobs-sdk-script/issues/298 ?

**Comment by pragnagopa** [comment]
@yvele - Yes. Does not repro in AppService plan.

**Comment by pragnagopa** [comment]
Closing this a dup of #298

**Comment by anthonychu** [comment]
@pragnagopa I notice you are requiring documentdb inside the function. What happens if you move that line to the top of the file?
