### ISSUE TITLE
Standard Web App logging UI can cause confusion with Functions logging story

### ISSUE THREAD

**Issue by lindydonna** [Azure/azure-webjobs-sdk-script#1148]
_From @davidebbo on January 23, 2017 20:35_

This came up in https://github.com/Azure/azure-webjobs-sdk-script/issues/691.

In a Function App, you can go to the general Web App loggins UI, and turn on logging to blob storage. The problem is that the Function runtime does not make use of this kind of logging, so this is effectively useless.

When the Portal is open, it does cause a cryptic log entry to be created every minute, e.g.

    2017-01-23T20:11:15,Information,FuncCreateBlobOnTimer,8756fe,636207990758093661,0,9524,3,Sending response: 200.0 OK,

These entries are unrelated to the running functions, and seem to be caused by the Portal pining the status API. So they are totally useless to user.

We need to decide what we want to do with those Web App logging options in the portal, as right now they're a source of confusion.

_Copied from original issue: projectkudu/AzureFunctionsPortal#885_

**Comment by lindydonna** [comment]
_From @christopheranderson on January 23, 2017 21:42_

The simple answer is to disable this. 

If we wanted this feature to work, it likely has to be part of the Diagnostics Log feature we discussed, but we're still not sure what the story for App Service is.

**Comment by lindydonna** [comment]
@davidebbo Do you have any objections with disabling this UI altogether?

**Comment by davidebbo** [comment]
I think it's the simplest approach now.

**Comment by lindydonna** [comment]
Closing due to wrong issue moved
