### ISSUE TITLE
Enhance host ID generation to allow the same set of characters as a Function App name

### ISSUE THREAD

**Issue by lindydonna** [Azure/azure-webjobs-sdk-script#1150]
From @mathewc in issue: https://github.com/projectkudu/AzureFunctionsPortal/issues/883

> The Function runtime imposes some restrictions on the format for HostId, and HostId is derived from the Function App name by default. E.g. runtime restrictions on HostId are [here](https://github.com/Azure/azure-webjobs-sdk/blob/663a508e8a851629c26a51e7de3af36629dfd120/src/Microsoft.Azure.WebJobs.Host/Executors/HostIdValidator.cs#L20).

> This can result in issues where someone can successfully create a Function App in the portal, but it fails at runtime - we've had cases of this.

> Ideally we'd find a way to prevent names we know are going to fail. This is somewhat complicated by the fact that we have logic that derives the HostId from the Function App name [here](https://github.com/Azure/azure-webjobs-sdk-script/blob/be7b649e5b62c90bc852be377d77729913476808/src/WebJobs.Script.WebHost/App_Start/WebHostResolver.cs#L153).

The right fix is to change the script host to handle these characters. Otherwise, we need to do the following:
- Change the Web Apps RP to disallow these function app names at the API layer
- Update Ibiza and FunkyUX to validate
- Update Visual Studio

**Comment by mathewc** [comment]
Many of the character restrictions on HostID are due to the fact that host ID is used in the names of several different storage artifacts (e.g. blob names, queue names, etc.). We can't break any of that - lots of downstream assumptions are made on the current longstanding restrictions.

**Comment by lindydonna** [comment]
@mathewc Is there a way to escape these illegal characters?  If not, we have to start a fairly big chunk of work to disallow them.

**Comment by fabiocav** [comment]
@lindydonna  can you provide some examples of Function-App name? Was there any customer pushback?

**Comment by lindydonna** [comment]
Won't fix for now
