### ISSUE TITLE
Set a Content-Type 

### ISSUE THREAD

**Issue by Sampath-Lokuge** [Azure/azure-webjobs-sdk-script#1151]
Hi,

I have followed [Background image thumbnail processing with Azure Functions and NodeJS](http://www.stevenfollis.com/2016/09/24/background-image-processing-with-azure-functions-and-nodejs/) article to create Azure functions.It is working fine. The problem which I have is, how to set the `Content-Type` on the thumbnailed image.At this moment it is Stream.

**function.json**

```
{
  "bindings": [
    {
      "name": "myBlob",
      "type": "blobTrigger",
      "direction": "in",
      "path": "project2-photos-original/{name}",
      "connection": "thumbnailfunction_STORAGE",
      "dataType": "binary"
    },
    {
      "type": "blob",
      "name": "$return",
      "path": "project2-photos-thumbnail/{name}",
      "connection": "thumbnailfunction_STORAGE",
      "direction": "out"
    }
  ],
  "disabled": false
}
```

I have tried as shown below.But it is not working.

**index.json**

```
var Jimp = require("jimp");

module.exports = (context, myBlob) => {

    // Read image with Jimp
    Jimp.read(myBlob).then((image) => {

        // Manipulate image
        image
            .resize(200, Jimp.AUTO)
            .greyscale()
            .getBuffer(Jimp.MIME_JPEG, (error, stream) => {
   
                if (error) {
                    context.log(`There was an error processing the image.`);
                    context.done(error);
                }
                else {
                                
                     context.res = { headers: {
                        'Content-Type': Jimp.MIME_JPEG
                     }};
                    context.log(`Successfully processed the image`);
                    context.done(null, stream);

                }

            });

    });

};


```

 ![Alt Text](http://i.imgur.com/dVC0nZi.png)

**Comment by mamaso** [comment]
Hey @Sampath-Lokuge 

I responded to your [stackoverflow post](http://stackoverflow.com/questions/41858321/set-thumbnail-image-content-type)

Couple quick things, `stream` is not a stream, it's a buffer.  That's good, because we don't support returning strings from node functions just yet.

Also, you can set the content type on the response object (`context.res`) via `context.res.type('text/plain')` or `context.res.set('content-type', 'text/plain')`

**Comment by Sampath-Lokuge** [comment]
Hi @mamaso

Still, it is not working for me.This is the final code.please check whether is that ok or not?

```
var Jimp = require("jimp");

module.exports = (context, myBlob) => {

    // Read image with Jimp
    Jimp.read(myBlob).then((image) => {

        // Manipulate image
        image
            .resize(200, Jimp.AUTO)
            .greyscale()
            .getBuffer(Jimp.MIME_JPEG, (error, stream) => {

                // Check for errors
                if (error) {
                    context.log(`There was an error processing the image.`);
                    context.done(error);
                }
                else {
                   
                 
                    var buffer = stream; // make sure you're using buffer
                    context.res.type(Jimp.MIME_JPEG).raw(buffer);
                    context.log(`Successfully processed the image`);
                }

            });

    });

};
```

**Comment by mamaso** [comment]
Ah, my mistake, I thought that you were using an http response binding.  I see that you're using a blob output binding.

Unfortunately there isn't a way to specify the content type for a blob from node.  You could chose to drop the blob output binding and explicitly use the azure storage sdk inside your function to store the blob, which would give you access to the blob.

Also, a C# function has the ability to set content-type on a blob as it can use the `CloudBlockBlob` type in a binding, but that doesn't help you in this node scenario.

**Comment by Sampath-Lokuge** [comment]
Hi @mamaso

On node there is a way to do that.

```
var Jimp = require("jimp");

var express = require("express");
var app = express();

app.get("/my-dynamic-image", function(req, res){
    Jimp.read("lenna.png", function(err, lenna) {
        lenna.resize(64, 64).quality(60).getBuffer(Jimp.MIME_JPEG, function(err, buffer){
             res.set("Content-Type", Jimp.MIME_JPEG);
             res.send(buffer);
         });
    });
});

app.listen(3000);
```

Don't we have a way to convert this into Azure function? Can't we use it like this?

```
context.res = { headers: {
                        'Content-Type': Jimp.MIME_JPEG
                     }}; 

```

**Comment by mamaso** [comment]
It depends on what your goal is: do you want to send an http response with the blob as body and content type set correctly? Yes, it can be done (that's what the node example is doing).

If you want to store the blob in azure storage with a content type, that is not possible via node (unless if you use the azure storage sdk).

**Comment by mamaso** [comment]
It seems that you're using your function to create the thumbnails, once they're created and uploaded in the blob (which your original function should accomplish, without the content-type) I think you can use an `<img src="path/to/blob/thumbnail">` in your UI (assuming html based).

**Comment by Sampath-Lokuge** [comment]
Hi @mamaso

Yes, it is HTML based.I have tried that.Hence it is a file type (Stream), it's automatically downloaded instead of showing on the UI. But if we have an image type then no problem, we can show it on the UI. That is the issue right now.

**Comment by Sampath-Lokuge** [comment]
Hi @mamaso 

You're right.That is my bad.Thanks a lot for your support.Have a nice day ahead!

**Comment by mamaso** [comment]
Great, happy to help, have a good one!
