### ISSUE TITLE
Fix content-disposition parsing

### ISSUE THREAD

**Issue by mamaso** [Azure/azure-webjobs-sdk-script#1152]
As it stands, `content-disposition: attachment; filename="test.txt"` will fail to parse.

Need to figure out a way to support valid
```
new ContentDispositionHeaderValue("attachment")
{
  Filename: "test.txt"
}
```
instead of [current parsing](https://github.com/Azure/azure-webjobs-sdk-script/blob/dev/src/WebJobs.Script/Binding/HttpBinding.cs#L305)

**Comment by mathewc** [comment]
How did you find this one - was it user reported?

**Comment by mamaso** [comment]
Was running through this scenario: http://stackoverflow.com/questions/41830321/outputting-a-file-with-an-azure-function

**Comment by securityvoid** [comment]
@mamaso @mathewc How does one handle this in a NodeJS azure function? I'm running into this same issue in NodeJS. The string seems properly formatted like the example here and its kicking out:

```
Exception while executing function: Functions.app-function-createReport. System.Net.Http: The format of value 'attachment; filename=myfile.xml' is invalid.
Exception while executing function: Functions.app-function-createReport

```

I've tried both the format with the quotes around the filename and without.

**Comment by mathewc** [comment]
The same fix will apply to all languages. We haven't released the fix yet however.

**Comment by securityvoid** [comment]
@mathewc Is there any work around? or is the work around just to drop the filename?

**Comment by mathewc** [comment]
I don't believe so - as you can see from the bug, the value will fail to parse as is. Hopefully we'll get this fix released soon.

**Comment by mamaso** [comment]
If you remove the filename piece it will parse and you can get a download, but it won't have the name or extension you want.
