### ISSUE TITLE
Azure Functions emits error when encountering duplicated fields foo=bar&foo=baz

### ISSUE THREAD

**Issue by rayluo** [Azure/azure-webjobs-sdk-script#1154]
Please provide a succinct description of the issue.

#### Repro steps

Provide the steps required to reproduce the problem

1. I create my first Azure Functions (an HTTP trigger function, using Python, deployed from github, into US WEST, ...)

2. Trigger my function with duplicated parameters in URL. Such as `https://myapp.azurewebsites.net/api/myfunc?foo=bar&foo=baz`

#### Expected behavior

My function will be called and let me handle the input query string.

#### Actual behavior

* Got an error page in my browser

>    This XML file does not appear to have any style information associated with it. The document tree is shown below.
>    <Error>
>    <Message>An error has occurred.</Message>
>    </Error>

* From the Azure Functions backend log, I see:

       mscorlib An item with the same key has already been added

#### Known workarounds

None.

#### Possible fix

The current situation is caused by the Azure Functions implementation tries to map the query_string (or HTTP POST body, for that matter) into environment variables, and these variables can not have duplicated names. I don't know if we can map them in environment variables in a meaningful way, but at the very least, we can try to fit only one value into that env variable, and then provide the raw QUERY_STRING (which is missing today) for developers to dig them out, just as the old school CGI did.

#### Related information 

Provide any related information 

* Programming language used: Python
* Links to source: Available upon request.

**Comment by mathewc** [comment]
Yeah, we should map duplicated query params in a "last one wins" fashion, and make the raw query string available to your function via REQ_QUERY (as we do for individual REQ_QUERY_XXX params).

**Comment by mathewc** [comment]
Duplicate query parameters will no longer cause errors. The behavior is now "last wins". In addition, I've made the original URL and query string available via REQ_ORIGINAL_URL and REQ_QUERY variables.
