### ISSUE TITLE
Build issues

### ISSUE THREAD

**Issue by dsyme** [Azure/azure-webjobs-sdk-script#116]
I had a few issues building clean. Various screenshots below.

Steps that solved this issue:

1. Running ``build.cmd`` multiple times
2. Updating Web Developer Tools in Visual Studio 2015
3. ``msbuild WebJobs.Script.proj /t:EnableSkipStrongNames`` (thanks Mathew!)

p.s. Could we enable a CI build on this repo to help make sure it continues to build clean?

![pic1](https://cloud.githubusercontent.com/assets/7204669/13845467/14c16766-ec38-11e5-9dff-07ad6539a02f.png)

![pic2](https://cloud.githubusercontent.com/assets/7204669/13845469/17829d80-ec38-11e5-868d-01b1bc2325be.png)

![pic3](https://cloud.githubusercontent.com/assets/7204669/13845501/4fed28a2-ec38-11e5-87b5-015cf66f2404.PNG)

**Comment by mathewc** [comment]
Can you build successfully in VS? For the last error run "msbuild WebJobs.Script.proj /t:EnableSkipStrongNames". Also run all this from an admin VS Developer Command Prompt window.

**Comment by dsyme** [comment]
Thanks @mathewc!  As I edited up above, here are the steps to solve the issue:

1. Running ``build.cmd`` multiple times
2. Updating Web Developer Tools in Visual Studio 2015
3. ``msbuild WebJobs.Script.proj /t:EnableSkipStrongNames`` (thanks Mathew!)
