### ISSUE TITLE
Please increase max payload size from Azure Logic Apps to Azure Functions

### ISSUE THREAD

**Issue by back5576** [Azure/azure-webjobs-sdk-script#1161]
Please provide a succinct description of the issue.

#### Repro steps

Provide the steps required to reproduce the problem

1. Step A
Make a Logic App that produces a payload with a size >15MB. In my test I watch an SFTP folder and then upload files of different sizes.

2. Step B
Make an Azure Function that accepts a payload and responds with just a JSON message with metadata like size.

3. Step C
Have "Step A" logic app invoke "Step B" azure function.

#### Expected behavior

Invocation with payloads up to 50MB should succeed

#### Actual behavior

At a threshold around 15MB, the invoke Azure Function step in the Logic App returns a statusCode 500 error with message "An error has occurred".

#### Known workarounds

Provide a description of any known workarounds.

#### Related information 

Provide any related information 

* Programming language used 
* Links to source

**Comment by mamaso** [comment]
similar issue to #1063

**Comment by fabiocav** [comment]
@pragnagopa  Can we match the limits set by Logic Apps (just watch for the limitation of App Service)

**Comment by mamaso** [comment]
If we match logic apps it should be pretty simply, just a couple changes in web.config. 

From a little investigation I did, in order to make it a configurable setting would require some hackery of setting unlimited size in web.config and then rejecting requests based on request size (after looking at host/function.json) ourselves.

**Comment by fabiocav** [comment]
Need to coordinate any updates with @safihamid to make sure the AF proxy matches what is set here.

**Comment by davidebbo** [comment]
@fabiocav and I experimented, and there are two distinct request lengths limit: ASP.NET and IIS.

Script runtime explicitly sets the ASP.NET  limit:

    <httpRuntime targetFramework="4.5" maxRequestLength="16384" />

Which means 16MB.

And the IIS limit defaults to 30MB but can be changed, e.g.

```xml
  <system.webServer>
      <security>
         <requestFiltering>
            <requestLimits maxAllowedContentLength="999999999" />
         </requestFiltering>
      </security>
  </system.webServer>
```

After increasing both, we were able to upload a file of size 72,121,872, but it failed with a size of 141,011,376, which must have hit some other limit somewhere.
