### ISSUE TITLE
Invalid EventHub Name/Connection causing excessive error logs

### ISSUE THREAD

**Issue by mathewc** [Azure/azure-webjobs-sdk-script#1162]
Create an EventHub triggered function from our template with an invalid hub/connection info. This seems to put the host into a fast retry error loop that generates excessive logs.

**Comment by mamaso** [comment]
Looked at this a bit, basically the webjobs sdk throws an exception at runtime when it tries to start the EventHubListener for a non-existent event hub.

We could add a test for existence in the core sdk in EventHubConfiguration.AddReceiver() when the connection string is specified. In functions, this occurs in ServiceBusScriptBindingProvider GetAttributes call, which bubbles up to GetFunctionDescriptors in ScriptHost.  That should log the error in the offending EventHub function and not kill the host.

**Comment by mathewc** [comment]
Thanks for taking a look. While we could add binding specific handling like you suggest, I think if we wanted to handle this across the board for all bindings including extensions, we'd make fundamental changes to the core SDK listener startup path to catch listener errors - I've logged a bug for that here: https://github.com/Azure/azure-webjobs-sdk/issues/996.
