### ISSUE TITLE
Node cannot respond with application/json that is a string or a buffer

### ISSUE THREAD

**Issue by ricklove** [Azure/azure-webjobs-sdk-script#1164]
Node Response cannot be a buffer or string. It must be an object in order for the response to not corrupt the body.

#### Repro steps

I had a precalculated json file that I wanted to return from a node server.

```
{
    "value": true
}
```

On my first attempt, I obtained corrupt data:

```
const fs = require('fs');
const path = require('path');

module.exports = function (context, req) {
    context.log('JavaScript HTTP trigger function processed a request.');

    let localPath = path.resolve(__dirname, 'data.json');

    context.log(__dirname);

    fs.readFile(localPath, (err, data) => {

        var body = data;

        // Prevent Json Body Corruption
        // body = body.toString();
        // body = JSON.parse(body);

        context.done(null, {
            headers:{
                'Content-Type' : 'application/json'
            },
            body: body
        });
    });
};
```

#### Expected behavior

It should return the file contents:

```
{
    "value": true
}
```

#### Actual behavior

It returns a corrupt body:

```
"ew0KICAgICJ2YWx1ZSI6IHRydWUNCn0="
```

#### Known workarounds

Converting the buffer to a string and then parsing it to an object works:

```
        // Prevent Json Body Corruption
        body = body.toString();
        body = JSON.parse(body);
```

#### Related:

This only occurs if mime type is "application/json". I have served other mime types with the buffer without any problem:

- text/html
- text/css
- application/x-javascript
- image/jpeg
- image/png
- image/x-icon

**Comment by mathewc** [comment]
Try specifying the `isRaw` property on your response:

```javascript
        context.done(null, {
            headers:{
                'Content-Type' : 'application/json'
            },
            body: body,
            isRaw: true
        });
```

**Comment by ricklove** [comment]
Yes, that solved the problem. Thanks!

Perhaps there is a cheap way to throw a server error in this instance and add that message to the console and response.
