### ISSUE TITLE
Some error conditions don't get logged at all in the Functions logs

### ISSUE THREAD

**Issue by davidebbo** [Azure/azure-webjobs-sdk-script#1167]
Logic App ran into a scenario where requests to a function failed with 400. Those 400 can be seen in the Worker IIS log, but there is no trace of them at all in the Functions logs. So I suspect that we have some code paths that can fail without a trace, making it very difficult to understand what happened.

We should review our logic and make sure that any http request coming into the runtime gets logged.

**Comment by securityvoid** [comment]
I've had a lot of trouble with the reliability of application logging. I feel like it sporadically just doesn't work, vs. being a specific type of log, but that definitely does not make any sense.

e.g. Right now I'm trying to troubleshoot a function that runs fine/works locally with:
`func run`

but fails to work on Azure. First thing in the actual function is:
` context.log("BEFORE EVERYTHING!");`

And nothing is logged to the function log, or anywhere I can see.

I've spent the last 2-3 hrs trying to get something to hit some log so I can figure out what is wrong and update the code.

In the past when I had this issue, I could swear all I did was restart the app a few times and I started getting the logging. However, I was unable to get that to work this time.

**Comment by securityvoid** [comment]
Now everything is logging properly for that function. All I did was change the code to something extremely simple (e.g. static context.res, context.done and immediate return), it logged properly. I then slowly backed up to how the code was before to see if I could isolate what was wrong. The old code fully logged.

**Comment by mathewc** [comment]
@securityvoid Are you talking about logs not being written to log files, or to the logs window in the portal?

**Comment by securityvoid** [comment]
@mathewc All of the above. Searched the file system from SCM, tried watching the logs from the portal, tried watching the logs from Visual Studio. When they finally wrote out they were under logfiles/function/function/MyFunctionname, but nothing was created there prior.

**Comment by securityvoid** [comment]
I've got the same situation again where nothing is logging. Is there anything I can do to help you isolate what's happening here?

**Comment by fabiocav** [comment]
This should be addressed in our last build which is about to be released in the next few days.

@securityvoid if you still run into this issue once that by the end of the week, can you please let us know (perhaps with a new issue) so we can investigate?
