### ISSUE TITLE
Add default timeout for Dedicated Apps to prevent runaway functions

### ISSUE THREAD

**Issue by mamaso** [Azure/azure-webjobs-sdk-script#1170]
I think we should add a relaxed default timeout back to Dedicated apps in a future breaking release.

Had a customer issue where their python function would timeout every 20 hours or so, requiring a site restart (he did not know about the configurable function timeout setting).

As it's now configurable (it was not in the time of #657), users can remove it if it negatively affects their scenario, but it should save some apps from being completely stalled.

**Comment by fabiocav** [comment]
@mamaso can you clarify scenario? Do you have Always-On enabled?

**Comment by mamaso** [comment]
`I finally have finished my Python function that monitors an Azure subscription for modifications but there seems to be an issue with it hanging.  What I have noticed is that after about 20 hours of executing the function every N seconds it the script hangs and never finishes.  The next morning I will come in and restart the service and it works great for another 20 hours.  `

Customer had Always On enabled, no default timeout set.

I think we should enable a default timeout on dedicated to prevent situations like this requiring manual restarts.  If someone wants to run a function that long they can remove the timeout setting.

**Comment by fabiocav** [comment]
I agree. Having a sensible limit by default is likely the desired behavior here.

@lindydonna @christopheranderson thoughts?

**Comment by lindydonna** [comment]
Agreed. @christopheranderson probably has a better sense of what the value should be. 10 minutes?  15 minutes?

**Comment by donquijotedelamancha** [comment]
Please allow azure functions on Consumption plan to run with timeout greater than 5min. This is too restrictive for certain applications.

**Comment by lindydonna** [comment]
Shouldn't change the host behavior, should instead add an entry in host.json

**Comment by lindydonna** [comment]
Created https://github.com/Azure/azure-webjobs-sdk-script/issues/1232 to track adding the setting in host.json.
