### ISSUE TITLE
Generic WebHook doesn't respect HTTP method settings

### ISSUE THREAD

**Issue by SyntaxC4** [Azure/azure-webjobs-sdk-script#1177]
There is a mismatch between what can be set from within the functions portal and what is actually accepted from the **Generic WebHook (Generic JSON)** template. Outlined below is the experience for triggering a Generic WebHook with a **GET** request, however, I believe the remainder of the VERBS should be tested as well.

## Repro steps

1. Create a Function App.
1. Create a new Function
1. Select GenericWebHook-CSharp
1. Click on Integrate
1. Dropdown *Allowed HTTP methods* and select Selected Methods
1. Ensure that only GET is selected
1. Click Save
1. In a command shell run the following:

```cli
curl -G <function-url>
```

## Expected behavior

The Azure Function would be triggered.

## Actual behavior

The Azure Function is not triggered, instead I am met with the following error.
```json
{"Message":"The HTTP 'GET' method is not supported by the 'GenericJsonWebHookReceiver' WebHook receiver."}
```

**Comment by mathewc** [comment]
Yeah, WebHooks only support POST, and this error comes from the WebHooks library we use. This should be a portal bug to restrict the UI for WebHooks. Nothing for us to do in the runtime.
