### ISSUE TITLE
Generic Web Hook doesn't support route template

### ISSUE THREAD

**Issue by SyntaxC4** [Azure/azure-webjobs-sdk-script#1178]
Please provide a succinct description of the issue.

#### Repro steps

1. Create a Function App.
1. Create a new Function
1. Select GenericWebHook-CSharp
1. Click on Integrate
1. Type 'abc' into the route template box
1. Click Save.
1. Type the following into the command, or run from postman

```cli 
curl -d {} -X POST <function-url>
```

#### Expected behavior

The Azure Function would execute using the abc route.

#### Actual behavior

The Azure Function doesn't recognize that the code is passed in and prompts for a password.

```json
{
  "Message": "The 'code' query parameter provided in the HTTP request did not match the expected value."
}
```

**Comment by mathewc** [comment]
No repro. You have to include your code query param in your URL. E.g. I just tried your repro steps and my function works fine using `https://function-fun.azurewebsites.net/api/abc?code=<mycode>`
