### ISSUE TITLE
File Watcher not reliable by itself

### ISSUE THREAD

**Issue by christopheranderson** [Azure/azure-webjobs-sdk-script#1179]
Occasionally, you can add a file and the file watcher doesn't get triggered. For a long running host, that means that it will look like the Function wasn't added. This leads to a weird case where the portal sees the function, it's on the file system, but the host never restarted itself.

#### Repro steps

This doesn't repro consistently. You need to attempt to add a file and have the filewatcher fail.

#### Expected behavior

The host loads my function when I add it to disk

#### Actual behavior

The host sometimes misses new Functions being added

#### Known workarounds

Poke the file again a bit later and the host should see it then.

#### Related information 

My app (chrande427) recently suffered from this. Function Host last restarted on 1/29, function added on 1/30, no restart in the logs. Poke the run.csx for missing function on 2/3, host restarts, function discovered.

#### Suggested fix

Poll the file system periodically to check that the filewatchers haven't failed. 

When the portal starts getting 404s for missing function info, ask the host to check if it's wrong.

**Comment by mathewc** [comment]
No repro.
