### ISSUE TITLE
context.bindings.res ignored in HTTP output binding 

### ISSUE THREAD

**Issue by ggailey777** [Azure/azure-webjobs-sdk-script#1184]
When you have an HTTP output binding named `res`, the response message set via this named output binding (e.g. `context.bindings.res`) is ignored. Only a response message set via `context.res` is honored. This works when the binding name is other than **res**.

#### Repro steps

Provide the steps required to reproduce the problem

1. Create an HTTP output binding on a function, as follows:

       {
         "type": "http",
          "name": "res",
         "direction": "out"
       }

2. Set a response message on the output binding as follows:

        module.exports = function (context, req) {
            context.bindings.res = { status: 202, body: "Request succeeded!" };
            context.log("response: " + JSON.stringify(context.bindings.res));
            context.done();
        };

#### Expected behavior

A 202 response message "Request succeeded!" is received as the output.

#### Actual behavior

An empty 200 response is received.

#### Known workarounds

Instead use the `context.res` object for the response.

**Comment by mathewc** [comment]
I believe we may have regressed this when we added the fluent api support for Node.js requests. What might be happening is that our runtime is now defaulting context.res to an empty instance, and that is being interpreted as if you have set it, and it overrides what you set via the actual binding. We’ll need to add some tests that cover your matrix.

**Comment by mamaso** [comment]
Yep, we supply a default context.res object now in order to expose helper functions, which explains this behavior (it must be picked up before context.bindings).

We could have the wrapper code remove the context.res object after the function call if it detects that it has not been used, or we could change the binding resolution logic (I'll probably take this route first).
