### ISSUE TITLE
Issues with function.json regex schema validation

### ISSUE THREAD

**Issue by mathewc** [Azure/azure-webjobs-sdk-script#1188]
In our WebJobs.Script sln I'm getting build info output like the following. E.g. for the shown ApiHubFileTrigger function, it's telling me I need to use mobileTable:

![capture](https://cloud.githubusercontent.com/assets/1056548/22718933/ee5a7726-ed57-11e6-92f1-b8cda7ab65a7.PNG)

**Comment by mathewc** [comment]
While we're in there fixing the schema validation stuff, can we also fix that regex issue we saw with ^^ $$?

**Comment by mamaso** [comment]
This validates with schema store tests and vscode schema, so it appears to be a visual studio implementation specific bug.

The schema should be interpreting the binding as 'dynamic', but it seems to be disregarding that.

I'll have a go at restructuring the schema to fix this.

**Comment by fabiocav** [comment]
Even if we manage to find a workaround by restructuring, If you can validate that this is a VS specific issue, we we should route it appropriately as it should be fixed there.

Also, if this is truly a VS specific issue and the workaround/restructuring also increases the complexity of what we'll have to maintain, I'd rather just wait for this to be addressed in VS.

**Comment by mamaso** [comment]
@fabiocav agree with all your points. For clarity, I want to investigate a workaround to simplify the schema so it can be consistently parsed, not complexify it :)
