### ISSUE TITLE
autoRenewTimeout in host.json doesn't work

### ISSUE THREAD

**Issue by SILENCE226** [Azure/azure-webjobs-sdk-script#1191]
From #1026 , autoRenewTimeout is now open to be configurable.
However, the Function App still get triggered again by same message in queue

#### Repro steps

Provide the steps required to reproduce the problem

1. Set **Lock Duration** to 2 mins

2. set **host.json** in https://<yourfunctionappname>.scm.azurewebsites.net/dev/wwwroot/host.json :
    "autoRenewTimeout": "00:00:30"

#### Expected behavior
renew the lock every 30 seconds
and same message should not be triggered again

#### Actual behavior

Function App get triggered again after 2 mins

#### Known workarounds
n/a

### Information
Function App version:
physicalPath="D:\Program Files (x86)\SiteExtensions\Functions\1.0.10690"

**Comment by mathewc** [comment]
Just to be sure, you have your setting in a `serviceBus` object like:

```javascript
    "serviceBus": {
      "autoRenewTimeout": "00:00:30"
    }
```

**Comment by SILENCE226** [comment]
@mathewc yes, it's the whole settings:
```json
{
      "functionTimeout": "02:00:00",
  
      "serviceBus": {
            "maxConcurrentCalls": 16,
            "prefetchCount": 100,
            "autoRenewTimeout": "00:00:30"
      }
}
```

**Comment by brettsam** [comment]
The docs for [AutoRenewTimeout](https://docs.microsoft.com/en-us/dotnet/api/microsoft.servicebus.messaging.onmessageoptions#Microsoft_ServiceBus_Messaging_OnMessageOptions_AutoRenewTimeout) say:

> Gets or sets the maximum duration within which the lock will be renewed automatically. This value should be greater than the longest message lock duration; for example, the LockDuration Property.

Set this value to the length of time that you want the renewals to take place, which is typically longer than your LockDuration (or else it doesn't do much, as you are seeing). If your Lock Duration is 2 minutes, try setting `autoRenewTimeout` to something like `00:04:00` to make sure it's working as expected.

**Comment by SILENCE226** [comment]
I was misunderstanding the meaning of **autoRenewTimeout**.
now it works as expect.
Thanks for detailed explanation!
