### ISSUE TITLE
Provide trigger/input resource cleanup binding option

### ISSUE THREAD

**Issue by mamaso** [Azure/azure-webjobs-sdk-script#1192]
Found this question interesting: http://stackoverflow.com/questions/42129429/how-to-delete-a-blob-using-azure-functions

It could be useful to provide a binding cleanup option, i.e. delete the processed blob (or other resource) after the function returns.

**Comment by mathewc** [comment]
This isn't an actionable issue for this repo. This would have to be an option exposed by the binding itself. E.g. blob trigger would have to expose a knob. Can you move the suggestion to there?

FYI - FileTrigger extension exposes an AutoDelete feature like this: https://github.com/Azure/azure-webjobs-sdk-script/issues/465

**Comment by fabiocav** [comment]
@mathewc should this be closed? moved elsewhere?

**Comment by mamaso** [comment]
moved to https://github.com/Azure/azure-webjobs-sdk/issues/1080
