### ISSUE TITLE
Python function freezes

### ISSUE THREAD

**Issue by einsmein** [Azure/azure-webjobs-sdk-script#1198]
My function freezes(?). It doesn't stop, when I look at Monitor pane, it's still running. It doesn't show any error, raises no exception, neither does it produce any result. However, the function would keep running (as in it doesn't complete and still show three blue dots in Monitor) until I restart an instance. I checked log files and it doesn't have any more log than what is shown in portal. From logs, it looks like the function just hangs in one line and doesn't execute the next.

#### Repro steps
Not sure how to reproduce this. It happens at different steps during executions. Sometimes when calling an API (which is the case most of the times), sometimes when checking blob existence in Storage (done via BlockBlobService), sometimes when saving the results. 

#### Expected behavior
The program should keep looping, make API call, return the result and save to storage. I tested locally and API calls work perfectly fine.

* python
* I also posted my issue and app name here but haven't got any response http://stackoverflow.com/questions/42162631/azure-function-freezes/42166295#42166295

**Comment by lindydonna** [comment]
@mamaso Could you follow up?

**Comment by mamaso** [comment]
Here's the error I'm seeing in logs:

```
Microsoft.Azure.WebJobs.Host.FunctionInvocationException: Exception while executing function: Functions.QueueTriggerPython_search ---> System.ApplicationException: D:\home\site\wwwroot\env\Lib\site-packages\requests\packages\urllib3\util\ssl_.py:334: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  SNIMissingWarning
D:\home\site\wwwroot\env\Lib\site-packages\requests\packages\urllib3\util\ssl_.py:132: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecurePlatformWarning
D:\home\site\wwwroot\env\Lib\site-packages\requests\packages\urllib3\util\ssl_.py:132: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecurePlatformWarning
D:\home\site\wwwroot\env\Lib\site-packages\requests\packages\urllib3\util\ssl_.py:132: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecurePlatformWarning
D:\home\site\wwwroot\env\Lib\site-packages\requests\packages\urllib3\util\ssl_.py:132: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecurePlatformWarning
Traceback (most recent call last):
  File "D:\home\site\wwwroot\QueueTriggerPython_search\run.py", line 49, in <module>
    twp_.retrieve_since_id(output_container, search_query, tweets_per_query, since_id)
...
```

More details about this error can be found [here](https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings).

The error is due to the default version of python, which is `2.7.8`.  We run on top of app service, so you can configure python as in [these docs](https://docs.microsoft.com/en-us/azure/app-service-web/web-sites-python-configure).

If configuration does not solve the problem, you can disable or capture the warnings as shown in the urllib3 logs.
