### ISSUE TITLE
Azure function error.Anonymously Hosted DynamicMethods Assembly: Cannot perform runtime binding on a null reference.

### ISSUE THREAD

**Issue by umerjaved** [Azure/azure-webjobs-sdk-script#1202]
Please provide a succinct description of the issue.
I am writing a simple Azure function using Http-Csharp template. It is expected to take a QR code input and return base64string.
#### Repro steps

Provide the steps required to reproduce the problem

1. When provide test input, (see attached screenshot) 

2. And click Run, it is supposed to return a base64string, (see attached screenshot for expected outcome)

#### Expected behavior
It is supposed to return a base64string. (See attached screenshot). I have also attached function supporting files

![error](https://cloud.githubusercontent.com/assets/16427070/22969549/ccd49842-f366-11e6-8f1c-c25c5e1ae04c.png)
![expected test](https://cloud.githubusercontent.com/assets/16427070/22969548/ccd42902-f366-11e6-98c5-3736c1d1732b.png)

[Run.txt](https://github.com/Azure/azure-webjobs-sdk-script/files/776686/Run.txt)
[Project.txt](https://github.com/Azure/azure-webjobs-sdk-script/files/776687/Project.txt)
[project.lock.txt](https://github.com/Azure/azure-webjobs-sdk-script/files/776689/project.lock.txt)
[Funcrion.txt](https://github.com/Azure/azure-webjobs-sdk-script/files/776688/Funcrion.txt)

#### Actual behavior

It is throwing an error in the log window even though compilation is done successfully. (also see attached)
Anonymously Hosted DynamicMethods Assembly: Cannot perform runtime binding on a null reference.

#### Known workarounds

Provide a description of any known workarounds.

#### Related information 

Provide any related information 

* Programming language used 
* Links to source

Any idea what's going wrong here please?

**Comment by mathewc** [comment]
This error is coming from the "dynamic data" json deserialization. It looks like you're attempting to access members that aren't present on the deserialized object, e.g. "data.QRInfo" since the test data you're sending only has a "name" property.

Update the test data to pass valid data and it will work.

**Comment by umerjaved** [comment]
Thanks Mathew, that helped. 
Also can we control configurations such as function execution time in case my function needs to process large number of records on a certain time hence sufficient time required for Azure function execution?

**Comment by mathewc** [comment]
Closing since it sounds like the issue was bad input data.
