### ISSUE TITLE
Namespace nesting in precompiled function

### ISSUE THREAD

**Issue by sburman** [Azure/azure-webjobs-sdk-script#1203]
When using C# precompiled azure functions there seems to be some issues around namespace resolution. eg.

```
namespace AcuteCompiled.Nested
{
    public class NameFunction
    {
        public static async Task<HttpResponseMessage> Run(HttpRequestMessage req)
        {
```
If I namespace my precompiled function as above, I would expect that my function.json should read:
```
"entryPoint": "AcuteCompiled.Nested.NameFunction.Run"
```
However, this results in the following error:
```
Error:

Function ($NameFunction) Error: The function type name 'AcuteCompiled.Nested.NameFunction' is invalid.
```
However, if I *incorrectly* ignore the namespace and reference it as:
```
"entryPoint": "AcuteCompiled.NameFunction.Run"
```
It works!

I haven't tested further (I've already burned enough time) but it looks like it resolves on three parts as such:
```
{AssemblyName}.{ClassName}.{MethodName}
```
I think better namespace support would be very useful as projects expand and code organization becomes more important.

**Comment by sburman** [comment]
Apologies, I think this is because I wasn't restarting the app when I deployed a new version of my .dll. I assume it is cached somehow at app start and when I was moving files around I was getting unexpected results.

**Comment by fabiocav** [comment]
@sburman that is indeed the behavior, but with the next drop, the functions runtime will detect assembly file changes and restart in order to pick up those changes (similar to the behavior you'd experience with a standard ASP .NET application). Assembly locking issues, if you were running into them, should be addressed as well.

**Comment by sburman** [comment]
@fabiocav, this is great news regarding the upcoming changes. 

While I am here, is there a gitter or similar for this project? There is a lot of unknowns/uncertainty at the moment and it would be great for there to be a comm channel with friendly ears.

**Comment by fabiocav** [comment]
We don't have a real time channel, but that might not be a bad idea. We do try to be very responsive here, on SO and MSDN Forums, though.

**Comment by ansario** [comment]
I am getting the same error and have restarted the Function app several times. Any other ideas?
