### ISSUE TITLE
Troubleshooting Reason for a 502 Error

### ISSUE THREAD

**Issue by securityvoid** [Azure/azure-webjobs-sdk-script#1209]
I've got an azure function that takes an XML file, does some processing, and spits out another XML file. Even my simplest test file is large enough that I can't run it locally, so I'm left debugging it on Azure. ([See this issue for size related items](https://github.com/Azure/azure-functions-cli/issues/69))

This routine is returning a 502 now every time I send use it, and I'm not seeing any logs anywhere as to why. 

Googling the error shows that with App Sites this can happen due to "long-running" routines, but I'm not seeing anywhere I can validate for sure why it is happening.

Can someone point me in the direction on where I should be looking to troubleshoot this? 

The error comes back pretty quick, so it seems weird for it to be because of something "long running".

**Comment by securityvoid** [comment]
I figured out my specific issue, but did so without logs (just logical guessing and systematic testing). It did not seem to be anything special beyond a normal programming error.

I'm still interested in how/where would should look to troubleshoot 502 errors, but in this particular instance its solved.

**Comment by mathewc** [comment]
Do you have a repro for how you were able to consistently get into this state via errors in your code?

We do emit log files in your Function App file directory that you can access via Kudu. E.g. you might check log files in D:\home\LogFiles\Application\Functions\Host.

**Comment by securityvoid** [comment]
@mathewc Last entry I have in that log is from 10:30 am this morning, and this testing was early afternoon. I've had sporadic luck at best in getting any logging. I can't figure out if it never logs, or just isn't logging anywhere near real time. None of the errors from the app were in the logs.

I'll see if I can reverse what I did. I *think* it `[might have been the content-disposition error](https://github.com/Azure/azure-webjobs-sdk-script/pull/1153)`. I'm pushing out one more change that once it hits Azure I'll be able to tell for sure if that was the cause.

**Comment by securityvoid** [comment]
Doesn't look like that was the cause. I'm not really sure how I was triggering it.

**Comment by securityvoid** [comment]
I do not know what is going on here or how to debug going forward. I've gone through my code over and over again. I've even found/fixed some bugs (Nothing prevented it from working, however). However, locally the code runs just fine. When it deploys to Azure I either get "An error occurred" or a 502 message. 

Since I'm using a deploy script to WebPack everything, I've even copied the deployed code from Azure to local and ran it locally to just see if somehow with the environment its deploying differently. That same code runs without error locally.

Where do I proceed from here? There doesn't appear to be any errors generated in any logs.

**Comment by securityvoid** [comment]
BTW, trying to attach a debugger remotely seems to always fail to load the symbols, even though I changed the 2 recommended settings in Visual Studio.

Normally I code in WebStorm, but to try and get some live debugging I figured I'd at least give visual studio a go.

**Comment by securityvoid** [comment]
Okay, this is the most debugging I've found. Attatching the debugger without any symbols, and streaming logs at least gives some output (I also went through and turned all logging on of everything):

```
Exception thrown: 'System.Net.WebException' in System.dll
Exception thrown: 'System.Net.WebException' in System.dll
Exception thrown: 'System.Net.WebException' in Microsoft.WindowsAzure.Storage.dll
Exception thrown: 'Microsoft.WindowsAzure.Storage.StorageException' in Microsoft.WindowsAzure.Storage.dll
Exception thrown: 'Microsoft.WindowsAzure.Storage.StorageException' in mscorlib.dll
Exception thrown: 'System.Net.WebException' in System.dll
Exception thrown: 'System.Net.WebException' in System.dll
Exception thrown: 'System.Net.WebException' in Microsoft.WindowsAzure.Storage.dll
Exception thrown: 'Microsoft.WindowsAzure.Storage.StorageException' in Microsoft.WindowsAzure.Storage.dll
Exception thrown: 'Microsoft.WindowsAzure.Storage.StorageException' in mscorlib.dll
Exception thrown: 'System.Net.WebException' in System.dll
Exception thrown: 'System.Net.WebException' in System.dll
Exception thrown: 'System.Net.WebException' in Microsoft.WindowsAzure.Storage.dll
Exception thrown: 'Microsoft.WindowsAzure.Storage.StorageException' in Microsoft.WindowsAzure.Storage.dll
Exception thrown: 'Microsoft.WindowsAzure.Storage.StorageException' in mscorlib.dll
The thread 0x2144 has exited with code 0 (0x0).
```

**Comment by securityvoid** [comment]
Are all of those storage exceptions because logs can't be written out? My code doesn't call Azure Storage directly.

Also, do the JavaScript functions run with EdgeJS.dll?

I stopped everything, came back in; attacked the debugger while streaming the logs and ran my function.

I received an error:
```
An unhandled exception of type "System.AccessViolationException" occured in EdgeJS.dll.

Additional Information: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
```

**Comment by securityvoid** [comment]
Okay, I think I have a repo. I'm deploying now to validate exactly.

**Comment by securityvoid** [comment]
So, [I'm still having problems with logging](https://github.com/Azure/azure-webjobs-sdk-script/issues/1222), but when I came in this morning the code that worked in the CLI and failed on Azure with 502 and other errors magically was working.

Did Azure get an update last night or something?

**Comment by ahmelsayed** [comment]
yes we are in the process of updating Azure. Only some scale units have been updated so far, so you might be lucky. The CLI was in a weird land where the version of the runtime it had was ahead of what was in Azure, but with this update the version in Azure will be ahead of the one in the CLI :) 
Hopefully after this update to Azure, and another update to the CLI, they will match and will try to keep them matching moving forward.

**Comment by securityvoid** [comment]
Starting about 8pm late last night, I started getting:
```
HTTP/1.1 503 Service Unavailable
Cache-Control: no-cache
Pragma: no-cache
Content-Length: 29
Content-Type: text/plain; charset=utf-8
Expires: -1
Server: Microsoft-IIS/8.0
X-AspNet-Version: 4.0.30319
X-Powered-By: ASP.NET
Date: Thu, 23 Feb 2017 12:39:55 GMT
Connection: close

Function host is not running.
```

Restarting the app doesn't do anything. Prior to that everything was working beautifully and there were no changes to the app. I did start making a function to keep the app warm, but even disabling that doesn't recover from this.

How does one get their function app running again?

**Comment by lindydonna** [comment]
@securityvoid could you please provide your function app name either directly or indirectly?

**Comment by securityvoid** [comment]
The app is "andrew-backend". I completely deleted the webapp yesterday and recreated it. As a result at this stage I'm not longer getting the 503 messages.

**Comment by securityvoid** [comment]
BTW, I just noticed a new log SystemLog today. It shows:

`2017-02-23T23:35:41 [SmallDedicatedWebWorkerRole_IN_507] [WpEvent] Memory limit has been hit. The worker process will be shut down.`

**Comment by securityvoid** [comment]
I'm back to it saying:
`Function host is not running.`

I didn't notice any logs telling me why, but I will poke around more in the AM.

**Comment by securityvoid** [comment]
What is the proper way to get the "Function Host" running again without blowing away the whole site and recreating it? It doesn't seem that stopping the website and starting it again does anything. Should a new deploy restart it?

**Comment by lindydonna** [comment]
@securityvoid You should be able to restart just the w3wp process in Kudu. Go to kudu then process explorer. I'm checking your site logs now.

**Comment by lindydonna** [comment]
@securityvoid I discovered the issue, and we'll have to investigate why you aren't seeing the log. 

`System.ArgumentException: FunctionTimeout must be between 00:00:01 and 00:05:00.
   at Microsoft.Azure.WebJobs.Script.ScriptHost.ApplyConfiguration(JObject config, ScriptHostConfiguration scriptConfig)
   at Microsoft.Azure.WebJobs.Script.ScriptHost.Initialize()
   at Microsoft.Azure.WebJobs.Script.ScriptHost.Create(IScriptHostEnvironment environment, ScriptHostConfiguration scriptConfig, ScriptSettingsManager settingsManager)
`

Did you update host.json with a `functionTimeout` that is greater than 5 minutes?

**Comment by securityvoid** [comment]
@lindydonna Okay, I killed the w3wp process in Process Explorer which appears to respawn on a request (Whoo hoo!). This gets rid of the "Function host is not running", and I'm operational. Thank-you!

I did recently increase the max time-out on the app. I was hitting the 5 minute timeout on the very simple poller function I have. I'm very confused as to why that would take so long, but now that its running again I can see if I can isolate this further. All the poller function does is check for a JWT token. If it exists and is valid it returns "{ status : alive}". If it doesn't it returns a 403. 

I quickly looked through my logs again, and I'm not seeing that error anywhere. Which log should that be in? Maybe I somehow over looked it?

**Comment by lindydonna** [comment]
@securityvoid Yes, on a consumption plan you can only have a maximum timeout of 5 minutes. If you set it to a value greater than that, the host will fail to start.

Did you look at your host logs?  In Kudu, navigate to D:\home\LogFiles\Application\Functions\Host

**Comment by securityvoid** [comment]
I must have somehow missed it in the logs. I can definitely tell you that now as I manually change the host.json, and hit the site with the "Monitor" on I am getting a log with that error.

I definitely checked host logs before, but I had quite a few of them piling up and I must have been looking at the wrong ones.

Thank-you for your help.

**Comment by lindydonna** [comment]
Can we close this issue?

**Comment by securityvoid** [comment]
Sure
