### ISSUE TITLE
Precompiled functions - access is denied when redeploying

### ISSUE THREAD

**Issue by JonCanning** [Azure/azure-webjobs-sdk-script#1211]
Git deploy a precompiled function
Gt deploy updated binary

Error logged in deployment activity:

`Could not remove 'D:/home/site/wwwroot/DataRouting/DataRouting.dll': Access is denied.\r\n`

Workaround:
Stop the function
Redeploy
Start the function

**Comment by mathewc** [comment]
I believe this is the same issue addressed by https://github.com/Azure/azure-webjobs-sdk-script/pull/1169.  We're in the process of deploying that fix now. Right @fabiocav?

**Comment by lindydonna** [comment]
@JonCanning this should be fixed now. Restart your app if you continue to see this and you'll get the updated version.
