### ISSUE TITLE
Optional route parameters throw exception when they are omitted

### ISSUE THREAD

**Issue by nickharris** [Azure/azure-webjobs-sdk-script#1216]
Please provide a succinct description of the issue.

Optional route parameters throw exception when they are omitted

#### Repro steps

Provide the steps required to reproduce the problem

1.  function.json
Add route 
..
{
  "bindings": [
    {
      "authLevel": "function",
      "name": "req",
      "type": "httpTrigger",
      "direction": "in",
      "methods": [
        "post",
        "put",
        "delete"
      ],
      "route": "foo/{id:alpha?}"
    },
..

2. Run.csx
public static async Task<HttpResponseMessage> Run(HttpRequestMessage req, TraceWriter log, string id)
{
....
}

3. Post to func in fiddler

When id is specified works as expected
POST https://somefunc.azurewebsites.net/api/foo/abc?code=ApiKey

When id is omitted from the route fails with exception
POST https://somefunc.azurewebsites.net/api/foo?code=ApiKey

#### Expected behavior

both to work 

#### Actual behavior

Exception when optional route parameter id is not specified is per the following:

Exception while executing function: Functions.registration
Microsoft.Azure.WebJobs.Host.FunctionInvocationException: Exception while executing function: Functions.registration ---> System.InvalidOperationException: Exception binding parameter 'id' ---> System.InvalidOperationException: Binding data for 'id' is not of expected type String.
   at Microsoft.Azure.WebJobs.Host.Bindings.Data.ClassDataBinding`1.BindAsync(BindingContext context)
   at Microsoft.Azure.WebJobs.Host.Triggers.TriggeredFunctionBinding`1.<BindCoreAsync>d__8.MoveNext()
   --- End of inner exception stack trace ---
   at Microsoft.Azure.WebJobs.Host.Executors.DelayedException.Throw()
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.<ExecuteWithWatchersAsync>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.<ExecuteWithLoggingAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.<ExecuteWithLoggingAsync>d__13.MoveNext()
   --- End of inner exception stack trace ---

#### Known workarounds

none

#### Related information 

C#

**Comment by mathewc** [comment]
Yes, it looks like we have an issue in this regard for non value types like string. Note that this does work with int and other value types if you declare the parameters as nullable (e.g. int?).

A workaround is to define a POCO that captures the route parameters. This will work:

```csharp
using System.Net;

public class Input
{
    public string Id { get; set; }
}

public static async Task<HttpResponseMessage> Run(Input input, HttpRequestMessage req, TraceWriter log)
{
    log.Info("C# HTTP trigger function processed a request. " + input.Id);

    return req.CreateResponse(HttpStatusCode.OK); 
}
```

```javascript
{
  "bindings": [
    {
      "authLevel": "function",
      "name": "input",
      "type": "httpTrigger",
      "direction": "in",
      "route": "foo/{id:alpha?}"
    },
    {
      "name": "$return",
      "type": "http",
      "direction": "out"
    }
  ],
  "disabled": false
}
```

**Comment by nickharris** [comment]
using your approach works for an optional id but drops the http POST body i.e the following _var content = await req.Content.ReadAsStringAsync()_ results in an empty string rather then the content. is there a recommended workaround for both? or is it just do use a POCO and the request body rather than a route?

**Comment by mathewc** [comment]
If you post a JSON object to the function with content type application/json and define properties in your POCO that capture those JSON properties, you can capture both the body and the route params in the same object.

**Comment by nickharris** [comment]
thanks a bunch Mathew, that works for now. could you update the ticket once original issue is resolved

**Comment by mathewc** [comment]
Fixed via https://github.com/Azure/azure-webjobs-sdk/pull/1146. Will go out in next release.

**Comment by johanosventer** [comment]
@mathewc When will the next release be?  Only run into this issue today,  would rather wait for the fix if it's not too far in the future.

**Comment by fabiocav** [comment]
@johanosventer deployment should begin next week, so you should be able to see that rolling out within a week or two depending on the region your app is on.

**Comment by johanosventer** [comment]
@fabiocav Great news!
