### ISSUE TITLE
Website Home Page Replace with "Your Function App is up and running"

### ISSUE THREAD

**Issue by ctaggart** [Azure/azure-webjobs-sdk-script#1223]
The website home page is replaced with "Your Function App is up and running":
![image](https://cloud.githubusercontent.com/assets/80104/23188818/c387c9fa-f855-11e6-946c-65e05216f0be.png)

#### Repro steps

Provide the steps required to reproduce the problem

1. Deploy existing website. Ours is deploys via webdeploy
2. Follow tutorial on wiki with deployment option 1. I only deployed `QueueTrigger`.

#### Expected behavior

Website is not replaced. WebJobs dashboard shows something about the site extension or deployed function.

#### Actual behavior

Website is replaced with `Function App` website. 

#### Related information 

I originally had the website in 64-bit mode, but had to switch it to 32-bit like I mentioned in #1157.

**Comment by lindydonna** [comment]
This is by design. Azure Functions is not really designed to be used alongside a regular site, unlike Azure WebJobs. What is your scenario?

**Comment by ctaggart** [comment]
@lindydonna I was hoping to use WebJob Scripts instead of WebJobs. May be I'm confused what this azure-webjobs-sdk-script project is all about. cc @panesofglass

**Comment by lindydonna** [comment]
@ctaggart WebJob Script is really just a codename. This is the runtime that powers Azure Functions, which is documented here: https://docs.microsoft.com/en-us/azure/azure-functions/index

Creating a private site extension is mostly for people who are contributing to the project, not usually end-users.

**Comment by ctaggart** [comment]
Okay, I get it. I should have gone with option 2:
https://github.com/Azure/azure-webjobs-sdk-script/wiki#option-2-no-http-functionwebhook-support
