### ISSUE TITLE
dotnet references for .fsx & .csx scripts

### ISSUE THREAD

**Issue by ctaggart** [Azure/azure-webjobs-sdk-script#1226]
It would be much easier to write dotnet script functions if it was simpler to [reference external assemblies](https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-fsharp#referencing-external-assemblies). The dotnet core has all the functionality to download and run the assemblies. Can ya'll help bake this into scripts? I'd like to be able to do:

``` fsharp
#package "Microsoft.Azure.WebJobs@2.0.0-*"
#package "NewtonSoft.Json"
```

I added this to https://github.com/fsharp/fslang-suggestions/issues/542 also. It applies to C# as well, but not sure where to request it.

**Comment by lindydonna** [comment]
This seems like an interesting feature, but we don't plan to invent something that is Functions-specific. The right direction for this is to use precompiled assemblies, so that you can get the full benefit of existing toolchains.
