### ISSUE TITLE
Provide a way to set host ID on script host startup

### ISSUE THREAD

**Issue by lindydonna** [Azure/azure-webjobs-sdk-script#1231]
**NOTE: review [Allow host to run outside of Azure without a host id \#1297](https://github.com/Azure/azure-webjobs-sdk-script/issues/1297) for an alternate approach.**

The CLI needs to set a **default** host ID on startup, so that customers can run the same code and same host.json as on Azure. The script host is currently initialized using WebApiConfig.Initialize (see https://github.com/Azure/azure-functions-cli/blob/master/src/Azure.Functions.Cli/Actions/HostActions/StartHostAction.cs#L122) and [WebHostSettings](https://github.com/Azure/azure-webjobs-sdk-script/blob/master/src/WebJobs.Script.WebHost/App_Start/WebHostSettings.cs) does not have a host ID property. 

When running in Azure, the host ID is generated from the site name. However, it's not a good idea for the CLI to set the site environment variable, since that affects other behavior. 

If a host ID is specified in project.json, that value should take precedence.

CC @ahmelsayed

**Comment by lindydonna** [comment]
@christopheranderson FYI that this should be triaged with a high priority. We currently have a bug in the CLI where you have to restart the host sometimes, because it modifies host.json after startup. Once this feature is in place, it'll be a really quick fix in the CLI and we can turn it around right away.

**Comment by lindydonna** [comment]
Related to #1297

**Comment by christopheranderson** [comment]
Closing this since it will be addressed by the #1297 improvement
