### ISSUE TITLE
Problem POSTing over 4MB data to HTTPTrigger with Proxy turned on

### ISSUE THREAD

**Issue by NichUK** [Azure/azure-webjobs-sdk-script#1238]
When POSTing over 4MB of data (as multipart/form-data) to an Azure HTTP Trigger function, the function is not actually hit, but returns a 500 error

Following the trail in #322 #1161 and #1063 it looks like the limit should be 16MB currently, but <4MB works and >4MB doesn't even hit my function and returns a 500 error.

This appears to be Proxy problem.

Although I tried both accessing the Proxy URL and the underlying URL with the same result (failure), if I turn proxy off completely in function app settings, I can immediately upload a 15MB file to the function URL.

**Comment by safihamid** [comment]
We are adding the below to proxy site extension to be compatible with functions and limit the payload to 16MB.

 <httpRuntime  maxRequestLength="16384" />

**Comment by fabiocav** [comment]
@safihamid FYI, we'll be doing the work to increase this in the runtime soon. Adding a note to that issue so it is coordinated with you.

**Comment by NichUK** [comment]
Thanks, guys!

**Comment by safihamid** [comment]
The fix is live now. Thanks!
