### ISSUE TITLE
Script host cold-start is very slow and expensive

### ISSUE THREAD

**Issue by cgillum** [Azure/azure-webjobs-sdk-script#124]
**Setup**:
Clean, Small Azure VM without any cached ASP.NET compiled assemblies, etc.

**Trigger**:
To isolate startup time, I simply fired a cURL request to the root URL to trigger a host process startup. No actual messages were in the queue at the time to avoid mixing cold-start with actual processing.

**Scripts**:
Two scripts were defined, a basic queue trigger and an HTTP trigger. These both call into node.js.  No C# scripts involved.  As I mentioned above, these triggers did not actually run.  I assume this would only factor into the cold-start initialization.

**Observations**:
I did two tests.  The first was w/out CPU profiling to make sure I was getting pure numbers.  Startup time was 16 seconds.  cURL reported that pretty much all of this was waiting for a response.  Total machine CPU usage jumped to between 70-90%.

The second request had CPU profiling running.  I have the PerfView CPU profile available on request.

Top CPU users (in order): w3wp.exe (by a wide margin), VBCSCompiler.exe, and csc.exe.

Drilling into w3wp.exe, it seems the most of the CPU time is spent somewhere under WebJobs.Script.WebHost.dll!WebJobs.Script.WebHost.WebApiApplication.Application_Start().  If someone more skilled than I can figure out how to get the right symbols in place, we might be able to narrow it down further.

**Comment by davidebbo** [comment]
Yes, we really need to profile this and see exactly where the time is spent. Hopefully we can get good profiling numbers running on a local machine, which will make this easier to have the right PDBs, etc...

**Comment by christopheranderson** [comment]
Adding Beta milestone because we should prioritize this work

**Comment by fabiocav** [comment]
Moving out of beta milestone so it can go through triage again. If we plan to take action on this, please re-add it to beta and let's discuss the options.

**Comment by christopheranderson** [comment]
RC Justification: This issue likely has a number of smaller work items that feed out of it, but focusing on minimizing perf for rc is a priority.

**Comment by davidebbo** [comment]
Note that it's already a lot faster than it was then, though much work remains.

**Comment by christopheranderson** [comment]
Closing this as we now have improvements/features schedule for this task. Can reopen if needed.
