### ISSUE TITLE
Precompiled functions in subdirectory not picked up by Azure host

### ISSUE THREAD

**Issue by petersondrew** [Azure/azure-webjobs-sdk-script#1241]
Precompiled functions specified via scriptFile in a subdirectory, e.g. `bin/MyPrecompiledFunc.dll`, work fine with the local emulator but are not found after publishing to Azure.
#### Repro steps

1. Create a new Azure function app and delete run.csx.

2. Copy precompiled dlls to a bin folder within the function folder.

3. Reference that path in the scriptFile setting (e.g. `bin/MyPrecompiledFunc.dll`) and set the proper entryPoint.

#### Expected behavior

The function should be found by the host.

#### Actual behavior

The function is not found by the host, and prints the error below
```
The following 1 functions are in error:
MyFunction: Unable to determine the primary function script. Try renaming your entry point script to 'run' (or 'index' in the case of Node), or alternatively you can specify the name of the entry point script explicitly by adding a 'scriptFile' property to your function metadata.
```

#### Known workarounds

I found the following workaround's on SO which work for me as well:
http://stackoverflow.com/questions/42192958/c-sharp-azure-function-in-dll-doesnt-work-in-azure-but-in-emulator#answer-42201152

#### Related information 

http://stackoverflow.com/questions/42192958/c-sharp-azure-function-in-dll-doesnt-work-in-azure-but-in-emulator

**Comment by christopheranderson** [comment]
@fabiocav will take a look

**Comment by lindydonna** [comment]
@fabiocav I think we can close this issue since it's resolved with the latest functions runtime.
