### ISSUE TITLE
GET /admin/functions/MyFunc/keys can fail with a 500

### ISSUE THREAD

**Issue by davidebbo** [Azure/azure-webjobs-sdk-script#1244]
We got a report of a case where this call is consistently failing with 500 on one function. There is no logging  (that's tracked by #1243), so it's no clear what's going on.

Hopefully we can figure it out by taking closer look at the app (ref: session if 3e2e1a1512754329b8a802cbc0b0fef7).

**Comment by fabiocav** [comment]
Resolved by #1307
