### ISSUE TITLE
Dashboard Storage Table may be throttling function result updates

### ISSUE THREAD

**Issue by pgroene** [Azure/azure-webjobs-sdk-script#1245]
I run a function on a blob trigger moving millions of files from one blobstorage to another blobstorage. The function runs but in the monitor it shows far less success count then I see copied blobs. The app shows 1.133.864 events succeeded, in the appinsights logs I see 2,709,723 in the last 7 days.  

#### Repro steps

1 create a function on an blob trigger and save the blobs in another blobstorage / set up app insights to monitor the events or count the blobs in the dest blobstorage
2 add a few million files to the source blobstorage account

#### Expected behavior

success count is same as blob count in the dest blobstorage

#### Actual behavior

success count in about 1/4 of the success count

#### Known workarounds

-

#### Related information 
* Programming language used -> c#
* Links to source
code:
run.csx
```
#r "Microsoft.WindowsAzure.Storage"
using Microsoft.WindowsAzure.Storage.Blob;
using System.Configuration;

using Microsoft.ApplicationInsights;

private static TelemetryClient GetTelemetryClient()
{
    var telemetryClient = new TelemetryClient();
    telemetryClient.InstrumentationKey = ConfigurationManager.AppSettings["appinsights_key"];
    telemetryClient.TrackEvent("MeterDataMoveFile WebJobStart");
    return telemetryClient;
}

private static TelemetryClient _telemetryClient = GetTelemetryClient();
 
 
public static async Task Run(string input, string name,  Binder binder, TraceWriter log )
{
    var timer = System.Diagnostics.Stopwatch.StartNew();
    log.Info($"C# Blob trigger function processed: {name} ({input.Count()})");
    _telemetryClient.TrackEvent($"MeterDataMoveFile");

    try {
        string path = $"meter-data-input-vip-consolidated/{DateTime.UtcNow.ToString("yyyy/MM/dd/HH")}/{name}";
        log.Info($"path: {path}");

        var attributes = new Attribute[]
        {    
            new BlobAttribute(path),
            new StorageAccountAttribute("dest")
        };

        using (var writer = await binder.BindAsync<TextWriter>(attributes))
        {
            writer.Write(input);
            _telemetryClient.TrackEvent($"MeterDataMoveFile file written");
        }

        var attributesOrigin = new Attribute[]
        {    
            new BlobAttribute($"xxxx/{name}"),
            new StorageAccountAttribute("src")
        };

        var i = await binder.BindAsync<CloudBlockBlob>(attributesOrigin);
        i.Delete();
        _telemetryClient.TrackEvent($"MeterDataMoveFile file deleted");
    }
    catch (Exception e)
    {
        log.Error($"Error: {e.ToString()}");
        _telemetryClient.TrackException(e);
        _telemetryClient.TrackEvent($"MeterDataMoveFile Exception");
        throw e;
    }
    finally
    {
        timer.Stop();
        _telemetryClient.TrackMetric("MeterDataMoveFile Timer", timer.Elapsed.TotalMilliseconds);
        _telemetryClient.Flush();
    }
}
```
function.json:
```
{
  "bindings": [
    {
      "name": "input",
      "type": "blobTrigger",
      "direction": "in",
      "path": "xxxx/{name}",
      "connection": "src"
    }
  ],
  "disabled": false
}
```

**Comment by christopheranderson** [comment]
@brettsam is going to take a look. We think we might have some missing records which means it isn't showing up in the table.

**Comment by brettsam** [comment]
@pgroene -- would you mind sharing your function app name with me either directly or [indirectly](https://github.com/projectkudu/kudu/wiki/Reporting-your-site-name-without-posting-it-publicly). I should be able to query our backend logs and verify the number we're seeing matches the one in App Insights. My current theory is that you are being throttled by Azure Table Storage -- which means we're not able to update the records.

**Comment by pgroene** [comment]
@brettsam the name of the function app is: dataimportfunctionsp

**Comment by brettsam** [comment]
We were able to repro this under load. I've added some logging and could see that I was getting "The server is busy" responses back from Table storage.

You can also check your Table Storage Metrics in the dashboard and look at the Throttling Errors to see them:
![image](https://cloud.githubusercontent.com/assets/1089915/24432250/c0a15cb0-13d5-11e7-847d-80bbf1b1c622.png)

I'm going to improve the error logging experience here so that we have evidence of this in our backend logs (and you can see it if you look in host logs). That will allow us to see how widespread of an issue it is. With the move towards Application Insights for longer-term function logging, we likely won't invest in a big improvement for this specific issue. If you're interested, you can give this application insights preview a try: https://github.com/Azure/Azure-Functions/wiki/App-Insights-Early-Preview

**Comment by brettsam** [comment]
I've improved the logging here, which is likely the extent of what we'll fix.
