### ISSUE TITLE
Clients expect to still be able to manage functions even if they contain errors.

### ISSUE THREAD

**Issue by ahmelsayed** [Azure/azure-webjobs-sdk-script#1253]
If the host fails to load a function now for any error in the function (for example `Error: At least one binding must be declared.` or any other indexing errors) I still expect to be able to manage that function in that I can retrieve keys.

I know that this is by design in the host right now, so let me know if you disagree.

**Comment by davidebbo** [comment]
Related mail thread: "Console is showing message that Functions app is not available".
