### ISSUE TITLE
HttpTrigger Throttling Config

### ISSUE THREAD

**Issue by mathewc** [Azure/azure-webjobs-sdk-script#1261]
Add a host level configuration setting (and perhaps function level as well) that allows the user to set the maximum number of concurrent http requests that the host should handle at any given time.

- the host level setting would apply to ALL functions (i.e. not function specific like our existing knobs like queue BatchSize)
- when this threshold is exceeded, the host will return 429 "Too Many Requests" status along with a "Retry-After"
- In addition to an integer max requests limit, we should also allow the "Retry-After" value to be configured. We'll have an intelligent default

Such a setting will allow clients like Logic Apps to gracefully handle busy host situations. In the Logic Apps case, it handles the 429 and will retry after some time.

**Comment by mathewc** [comment]
Before we do this http specific feature, I want to give this more thought and try to generalize it in some way so that it can apply to other trigger types.

**Comment by yochay** [comment]
We need to look into applying different values to different VM (instance) sizes. Per Mathew comment, throttling is applicable for 'stream' type triggers like HTTP, where messaging types, like queue, IMHO,  don't really require specific throttling

**Comment by mathewc** [comment]
The other "automatic" triggers like queues etc. have their own trigger specific throttle knobs (e.g. BatchSize). HttpTrigger doesn't currently so it is somewhat special.
