### ISSUE TITLE
Need reliable way of waking up the runtime

### ISSUE THREAD

**Issue by davidebbo** [Azure/azure-webjobs-sdk-script#1264]
Today, we rely on hitting / to wake it up, but from Portal and Scale controller. But that fails if user enables Gateway and takes over the root.

We need to come up with an alternative API to reliably wake up the runtime. That needs to work without authentication.

**Comment by davidebbo** [comment]
Let's come up with a route proposal.

**Comment by mathewc** [comment]
API will be admin/host/ping
