### ISSUE TITLE
Scale controller should hit path other than root to wake up the runtime

### ISSUE THREAD

**Issue by davidebbo** [Azure/azure-webjobs-sdk-script#1266]
Hitting / fails if user enables Gateway and takes over the root.

This is dependent on first doing #1264.

**Comment by mathewc** [comment]
There is now a new anonymous API on the host: `admin/host/ping` that accepts POST requests, and returns a 200.

**Comment by davidebbo** [comment]
Tracked internally as this is not part of runtime.
