### ISSUE TITLE
Consolidate file watchers

### ISSUE THREAD

**Issue by fabiocav** [Azure/azure-webjobs-sdk-script#1277]
We need to consolidate our various file watchers in the runtime to minimize the number of change notification requests, which are particularly impactful  when running against Azure Files.

**Comment by fashaikh** [comment]
@fabiocav I see this issue still reproing

functionApp: appserviceemailer 
functionName: UsersRequestingContact

let me know if you need me to validate the fix .

**Comment by fabiocav** [comment]
@fashaikh the release deployment just began. This should be fully deployed by early next week.
