### ISSUE TITLE
DocumentDB Binding, No _id column

### ISSUE THREAD

**Issue by brharr** [Azure/azure-webjobs-sdk-script#1278]
Please provide a succinct description of the issue.

I have created a pretty simple POST method that is using an Output DocumentDB to actually store the JSON within. However, I am used to using the MongoDB driver for accessing the DocumentDB service which automatically creates a long string _id column for each document uploaded to a collection. This is not happening when I do the binding, is there any way to make that happen?

My function is written in Node.JS and it is based on a full CRUD Express based REST API that I built and is running against DocumentDB using the MongoDB driver connection.

Thanks,
Brian

**Comment by brettsam** [comment]
Can you give me an example of what your code looks like? After you insert a document, it will have an id automatically created for it in the database

**Comment by christopheranderson** [comment]
Closing with no answer
