### ISSUE TITLE
Function not triggered by new eventhub item after inactive period

### ISSUE THREAD

**Issue by Kimmen** [Azure/azure-webjobs-sdk-script#1284]
Originally reported in #1240, but created new issue as requested by @davidebbo .

**Issue**
My Function is not triggered by new items in the Eventhub after an inactive period of time (~20 minutes or so). I've read this has something to do with the host going into idle mode. Seems like it cannot be resumed once in idle mode. Comes alive once I inspect the Functions in the portal.

**Workaround**
I created a Timer triggered function that fires every third minute. That prevents the Host from going into idle mode.

**Support**
I cannot name my functions app name but here is an execution id according to this [guide](https://github.com/Azure/azure-webjobs-sdk-script/wiki/Sharing-Your-Function-App-name-privately):
**2017-03-08T08:03:34.250** Function completed (Success, Id=**e3b7299c-f22c-4dd3-bf17-5d6a0f55e94f**)

**Comment by Kimmen** [comment]
@davidebbo responded that I have incorrect connection string to my Eventhub:

> EventHub name should not be specified as EntityPath while using this Overload. Instead, please use 'path' parameter.

Seems odd that it works when inspecting the functions in the portal but not resuming from idle mode?

**Comment by davidebbo** [comment]
Yes, it's quirky. The reason is that two different parts of the system consume this, and we made one of them have special logic to deal with the bad connection string, while the other doesn't.

An upcoming fix will make both support it. Still, it's better to fix your connection string as suggested, which will work now.

**Comment by paulbatum** [comment]
EntityPath is now supported, closing.
