### ISSUE TITLE
Allow host to run outside of Azure without a host id

### ISSUE THREAD

**Issue by davidebbo** [Azure/azure-webjobs-sdk-script#1297]
On Azure, we generate one based on the app name, but outside Azure it's currently required. That's problematic, as it forces users to have on when they develop locally, and then they end up pushing that id to Azure, where it starts conflicting with local development. E.g. both the local and remote timer instances will be competing for the same locks, meaning timers won't behave as expected, etc.

Let's have logic to come up with a stable id regardless of where we run.

**Comment by lindydonna** [comment]
This is an interesting approach!  I had previously been thinking of a solution that would just unblock the CLI and the CLI would pass in a host ID, generating one if necessary (see https://github.com/Azure/azure-webjobs-sdk-script/issues/1231 and https://github.com/Azure/azure-functions-cli/issues/86).

**Comment by lindydonna** [comment]
@mathewc Any updates on this?  We keep getting folks bit by the this.
