### ISSUE TITLE
Provide a structured log feed at both the host and function level

### ISSUE THREAD

**Issue by lindydonna** [Azure/azure-webjobs-sdk-script#1301]
Customers expect that host-level errors will be persisted (red bubble errors). The portal has no good way to show these errors, since it would have to parse a log stream. Related portal issue: https://github.com/projectkudu/AzureFunctionsPortal/issues/608

This structure log should handle the following scenarios:
- Host level logs that will be displayed at a Function App Level
- Errors and warnings that are displayed in a tab next to Logs (see mock screenshot)

![image](https://cloud.githubusercontent.com/assets/4260261/23880832/8f335796-0813-11e7-8884-f60fa4a23609.png)

**Comment by lindydonna** [comment]
Portal resourcing is still unclear. Moving this issue into next-triaged.

**Comment by stofte** [comment]
Is any of this supposed to work? I'm seeing zero msgs in Errors and Warnings, but I get loggings saying 

   Exception while executing function: Functions.GetCards -> Script compilation failed.
