### ISSUE TITLE
Compilation Errors are very non-specific

### ISSUE THREAD

**Issue by NichUK** [Azure/azure-webjobs-sdk-script#1304]
Frequently, when there is a compilation error in a Function, the only error message supplied is:

Exception while executing function: Functions.XXXXXXX. Microsoft.Azure.WebJobs.Script: Script compilation failed.

A more precise error message would allow easier debugging of the function.

**Comment by christopheranderson** [comment]
We're going to be improving the compilation error experience as part of this issue: https://github.com/Azure/azure-webjobs-sdk-script/issues/1301

This will be more comprehensive than this recommendation, so closing for now.
