### ISSUE TITLE
Implement a secret repository backed by blob storage

### ISSUE THREAD

**Issue by fabiocav** [Azure/azure-webjobs-sdk-script#1317]
There are scenarios where the current file based repository introduces issues (e.g. access to the same secrets, with different file systems, across multiple sites).

A blob based implementation of the repository is needed to address those scenarios.

**Comment by christopheranderson** [comment]
PR: https://github.com/Azure/azure-webjobs-sdk-script/pull/1320

**Comment by fabiocav** [comment]
This was resolved by #1320
