### ISSUE TITLE
Add SendGrid Binding

### ISSUE THREAD

**Issue by jamesdixon** [Azure/azure-webjobs-sdk-script#132]
Hello, I had read somewhere that the ScriptHost should also work with WebJob extensions. Is this the case and if so, is there an example using the SendGrid extension? I took a look at the example from the extensions page, but I'm a bit unsure on how that translates to ScriptHost + Node.

Thanks in advance!

**Comment by mathewc** [comment]
Yeah, we haven't plugged in the SendGrid extension yet - we should! I'll leave this open so we can track doing that.

**Comment by jamesdixon** [comment]
:+1:
