### ISSUE TITLE
Support etags in Azure Tables input/output bindings

### ISSUE THREAD

**Issue by lindydonna** [Azure/azure-webjobs-sdk-script#1323]
Copied from a UserVoice suggestion: 
> I use python functions to read/write into Azure tables, unfortunately the etags are hidden. It would be quite useful to be able to access the eTags to ensure consistency of writes.

See https://feedback.azure.com/forums/355860/suggestions/17910307

**Comment by christopheranderson** [comment]
@lindydonna - move to SDK

**Comment by lindydonna** [comment]
This issue was moved to Azure/azure-webjobs-sdk#1073

**Comment by lindydonna** [comment]
This issue was moved to Azure/azure-webjobs-sdk#1074
