### ISSUE TITLE
Comm

### ISSUE THREAD

**Issue by spallanti** [Azure/azure-webjobs-sdk-script#1328]
Please provide a succinct description of the issue.

#### Repro steps

Provide the steps required to reproduce the problem

1. Step A

2. Step B

#### Expected behavior

Provide a description of the expected behavior.

#### Actual behavior

Provide a description of the actual behavior observed. 

#### Known workarounds

Provide a description of any known workarounds.

#### Related information 

Provide any related information 

* Programming language used 
* Links to source

**Comment by spallanti** [comment]
newcomm

**Comment by mathewc** [comment]
Not sure why this issue was created - no info was provided?
