### ISSUE TITLE
Azure Functions Redirect Header

### ISSUE THREAD

**Issue by kube** [Azure/azure-webjobs-sdk-script#1333]
I want one of my Azure Functions to do an **HTTP Redirection**.

This is the current code of the function:

    module.exports = context => {
      context.res.status(302)
      context.res.header('Location', 'https://www.stackoverflow.com')
      context.done()
    }

But it does not work.

A request sent from Postman shows the response has:

- `Status`: 200
- `Location` not set

Is this correct code? Or is it simply not allowed by Azure Functions?

**Comment by fabiocav** [comment]
@kube I have replied to your [question on SO](http://stackoverflow.com/questions/42931965/azure-functions-redirect-header) , you can also find additional samples here and here.

The code above actually does work, unless you have your binding name set to `$return`, which is what I assume you have now (you can check in the integrate tab)

Let us know if you continue to run into problems.
