### ISSUE TITLE
Surface Host Overall Health / Consecutive Error Count

### ISSUE THREAD

**Issue by mamaso** [Azure/azure-webjobs-sdk-script#1342]
Maintain a count of scripthost restarts in the ScriptHostManager that we can report through the `admin/host/status` api.

Could be surfaced in portal to help a customer see that their function app is restarting unexpectedly.

**edit** looks like we already have `consecutiveErrorCount` for the backoff strategy, can surface that

**Comment by fabiocav** [comment]
What is the goal, though? Restarts may be triggered by a few different reasons. Actual restarts are generally not for error reasons (which is what `consecutiveErrorCount` tracks), but triggered by code, metadata or dependency changes.

**Comment by mamaso** [comment]
This is somewhat handled by error count in the monitoring tab (unfortunately that seems to be broken at the moment).

Goal is to give users a better indication that their function app is unhealthy, since script host restarts affect all functions (which I would probably not assume as a user, that one broken function would negatively impact my other functions).

**Comment by mathewc** [comment]
The status endpoint will already return LastError if the host is currently in error - isn't that sufficient? The portal already shows such errors - it shows any errors returned via the status Errors collection. I don't see how a count of consecutive restarts would help?

**Comment by mamaso** [comment]
The portal doesn't show errors unless if you go to tab for the broken function, I think we should more proactively point to those broken functions.

**Comment by mathewc** [comment]
Yes, I think what you're asking for is part of https://github.com/projectkudu/AzureFunctionsPortal/issues/608 and should/would be covered as part of that. I don't think we have any changes to make here, so I recommend you close this and add any of your suggestions to that other issue.

**Comment by fabiocav** [comment]
Yes, I think there are a few issues that need to be solved, beyond just a restart or initialization error count.

A couple of the key things we need to address are:

- A good place to surface host errors information on the portal
- A reliable way to report and query error states. The status API only returns the last error and those are volatile and instance specific

Some of the work we have planned for structured logging will hopefully start helping with some of this.

**Comment by mamaso** [comment]
Yep, all sounds good! Closing this out.
