### ISSUE TITLE
Error with HttpTrigger, "The maximum message size quota for incoming messages (65536) has been exceeded."

### ISSUE THREAD

**Issue by garrardkitchen** [Azure/azure-webjobs-sdk-script#1343]
I'm getting an error when running local version of AF project via VS 2015 tooling. When I POST a body greater than 65536 bytes to a HttpTrigger it throws an error. Is there a way for me to set the MaxReceivedMessageSize property to circumvent this error?

#### Repro steps

Provide the steps required to reproduce the problem

1. POST body greater than 65536 bytes to HttpTrigger

#### Expected behavior

Not error

#### Actual behavior

Error:
```
Microsoft.Azure.WebJobs.Host: Exception binding parameter 'req'. System.ServiceModel: The maximum message size quota for incoming messages (65536) has been exceeded. To increase the quota, use the MaxReceivedMessageSize property on the appropriate binding element
```

#### Known workarounds

N/A

#### Related information 

Provide any related information 

* Using f# & HttpTrigger

Warmest regards,

Garrard.

**Comment by mathewc** [comment]
In our last release (completed yesterday) we increased the max request length to 100MB. See the release notes here: https://github.com/Azure/azure-webjobs-sdk-script/releases/tag/v1.0.10826. Can you confirm you're running the latest version?

**Comment by garrardkitchen** [comment]
Hi @mathewc, I'm running 1.0.10774.0 locally. I wouldn't know how to get the latest version installed locally.  I'm assuming I'd have to wait for an CLI update?

**Comment by mathewc** [comment]
Yes, see https://github.com/Azure/azure-webjobs-sdk-script/issues/1063 which is discussing that CLI issue

**Comment by christopheranderson** [comment]
Closing since this is tracked by the next CLI release
