### ISSUE TITLE
Output to multiple queues from Azure Function

### ISSUE THREAD

**Issue by dreadeddev** [Azure/azure-webjobs-sdk-script#1347]
Is it possible to output to multiple queues from an Azure Function by using multiple output bindings and therefore out parameters? I raise it as an issue as it doesn't seem to state either way in the documentation I've read so far. So to take and extend the MS [example ](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-storage-blob) could you do?

`{
  "bindings": [
    {
      "type": "manualTrigger",
      "direction": "in",
      "name": "input"
    },
    {
      "type": "queue",
      "name": "myQueueItemPart1",
      "queueName": "myfirstoutputqueue",
      "connection": "my_storage_connection",
      "direction": "out"
    }, {
      "type": "queue",
      "name": "myQueueItemPart2",
      "queueName": "mysecondoutputqueue",
      "connection": "my_storage_connection",
      "direction": "out"
    }
  ],
  "disabled": false
}`

If not, is this likely to be supported soon?

**Comment by davidgouge** [comment]
Hi @dreadeddev, we do this with a couple of Functions for Service Bus Queues and it works a treat.

**Comment by christopheranderson** [comment]
You can use as many input and output bindings as you want. You're only limited to having a single trigger on your function, for now. You can see an example where I do this with a queue output and a table output here: https://github.com/christopheranderson/functions-exponential-scale/blob/master/cs-exponential-scale/function.json
