### ISSUE TITLE
Does timeTrigger guarantees one running process only?

### ISSUE THREAD

**Issue by silencev** [Azure/azure-webjobs-sdk-script#1348]
I would like to know if Function App **timeTrigger** guarantees only one process running?
The setting of **function.json** is to fire every 5 minutes
```json
{
  "bindings": [
    {
      "type": "timerTrigger",
      "name": "myTestTimer",
      "schedule": "0 */5 * * * *",
      "direction": "in"
    }
  ],
  "disabled": false
}
```

If the process runs more than 5 minutes, another process get fired right after 5 minutes.
Is it possible to prevent this? 
I would like to have only one process running in this scenario.

Thanks!

**Comment by christopheranderson** [comment]
There is no way to prevent running your Function again if it is still running, but they will be running on the same machine, so they can share a common static variable. You could always have flag or something that your function checks before it starts any important logic.

FYI - consumption plan Functions are limited to running for 5 minutes, so you'd have to be using a normal app service plan to have a Function that ran longer than 5 minutes.

**Comment by Thomaswu1106** [comment]
@christopheranderson 
Does the Function app terminate process after the Function app timeout which is functionTimeout value of host.json files in WWWROOT folder? I found when the process execute over 2 hrs( our functionTimeout value in host.json), the process still showed in Kudo Process Explore but Function app console showed a new process started look like the old one dead.
Our app service plan is P1 premium looks like won't have process running limit so I'm confused for the process status when executed over timeout setting and it looks like will terminate in unknown time in my test env.
Thanks for the support!
Thomas

**Comment by mathewc** [comment]
Back to your original question - yes you should only see a single instance of your timer function running at any given time. This is clarified in the wiki here: https://github.com/Azure/azure-webjobs-sdk-extensions/wiki/TimerTrigger#scheduling:

> If your function execution takes longer than the timer interval, another execution won't be triggered until after the current invocation completes. The next execution is scheduled after the current execution completes.

**Comment by ericleigh007** [comment]
This is not what I've seen as late as Jun 11.  HOWEVER, I'm testing this in the local scripthost.

**Comment by christopheranderson** [comment]
Closing stale. Poke this if there is still an issue.
