### ISSUE TITLE
question: node 7+ support

### ISSUE THREAD

**Issue by jamesdixon** [Azure/azure-webjobs-sdk-script#1359]
Hi,

Just curious if there's planned support for Node 7+ w/ functions. Would love to take advantage of native async/await support in 7.4.

Cheers

**Comment by christopheranderson** [comment]
We've got a plan for this - https://github.com/Azure/azure-webjobs-sdk-script/issues/1319

Will hopefully be available in a few months. You could use TypeScript or babel today to do this, though that's annoying to do from portal, today. :(

**Comment by jamesdixon** [comment]
awesome 👍  thanks @christopheranderson !

**Comment by christopheranderson** [comment]
Node 8 is now supported in beta. Going forward, we'll support customer choosing their own versions, as long as it's higher than 8.4. There may be bugs until we add new versions to test-matrixes, but over all its a lot more flexible now.

**Comment by jamesdixon** [comment]
@christopheranderson fantastic! what's the best way to change versions?
