### ISSUE TITLE
Host logging endpoint

### ISSUE THREAD

**Issue by mathewc** [Azure/azure-webjobs-sdk-script#1371]
The scale controller needs a way to report errors to the runtime, so those errors are logged to our normal host log channels. E.g. if a trigger connection string is incorrect/invalid, etc.

Proposal is to add a new `admin/host/log` endpoint that accepts a POST request containing a json array of structured log entries to write. Each log entry would have the requisite json properties allowing us to translate to our existing TraceEvent log format, e.g. including properties timestamp, level, source, message, etc.

This endpoint will use the same auth model that the existing `admin/host/status` endpoint uses for internal Antares requests (see code [here](https://github.com/Azure/azure-webjobs-sdk-script/blob/dev/src/WebJobs.Script.WebHost/Controllers/AdminController.cs#L98)).

**Comment by paulbatum** [comment]
cc @brettsam

**Comment by mathewc** [comment]
This has been done
