### ISSUE TITLE
Add EventType to FunctionsLogs

### ISSUE THREAD

**Issue by mamaso** [Azure/azure-webjobs-sdk-script#1372]
@mathewc added a bunch of good stuff with HTTP request logging, host status, response details, but it makes it more difficult to follow what's happening with the host / per-function execution.

I'd like to see an event type added so that we can more easily filter out these chatty log types.

**Comment by mamaso** [comment]
related to #1387

**Comment by christopheranderson** [comment]
@fabiocav - related to https://github.com/Azure/azure-webjobs-sdk-script/issues/1387
