### ISSUE TITLE
Timeout value of 00:05:00 was exceeded by function: Functions.MyFunc.

### ISSUE THREAD

**Issue by jdneo** [Azure/azure-webjobs-sdk-script#1386]
I'm trying to setup a function app using script, steps are listed below.

#### Repro steps

Provide the steps required to reproduce the problem

1. Create dynamic function app using json template

2. Setting environment variable (some connection string) through Azure CLI 2.0

3. Create a folder as a function name under site/wwwroot/ (Kudu REST API)

4. Upload files into the created folder (through FTP)

5. run "npm install" (Kudu REST API)

My function code:

```
'use strict';

const Client = require('azure-iothub').Client;
const Message = require('azure-iot-common').Message;
const iotHubConnectionString = process.env['speech-recognition-iothub'];

module.exports = function (context, myEventHubMessage) {
    context.log(myEventHubMessage);
    if (myEventHubMessage.DeviceID) {
        const cloudClient = Client.fromConnectionString(iotHubConnectionString);
        cloudClient.open(function (err) {
            if (err) {
                console.log('Could not connect: ' + err.message);
            } else {
                console.log('Client connected');
                const message = new Message(`Pong - ${new Date().toTimeString()}`);
                cloudClient.send(myEventHubMessage.DeviceID, message, function (err, res) {
                    if (err) {
                        context.log(`Error in send C2D message: ${err}`);
                    } else {
                        context.log(`send status: ${res.constructor.name}`);
                    }
                });
            }
            context.done();
        });
    }
};
```

#### Actual behavior

Then I send some msg to my IoT Hub. The function app is keeping logging "function app start"

logs can be seen [here](https://shengtemptest.file.core.windows.net/log/iotazurefunction.log?st=2017-04-07T02%3A06%3A00Z&se=2017-04-30T02%3A06%3A00Z&sp=r&sv=2015-12-11&sr=f&sig=0Pjuhguz7cSpLfka6vLARaepo5deuXzW0GsV6Qj4NT4%3D), 

Actually, if I do nothing, the function app still keeps logging "function app start"

**Comment by mamaso** [comment]
Couple things:

Careful with the `console.log` - we won't capture that.  Needs to be `context.log`.

I'd also recommend that you create a single IoTHub client outside of function scope, you're likely running into some type of connection exhaustion due to creating a client for every function execution:
```
require('azure-iothub').Client.fromConnectionString(iotHubConnectionString);
module.exports = function(...
```

If you look at the logs, you can see there are a significant number of errors that are a result of exceeding IoTHub throughput, in addition to the timeout issues you mention.

Finally we may add support for an IoTHub binding to save you a lot of this work: https://github.com/Azure/azure-webjobs-sdk-extensions/pull/192/files

**Comment by jdneo** [comment]
Hi @mamaso. Thank you for your suggestion. I'm confused about the right way to generate the function.json file. One way I know is to use portal and click "+ function" to create a new one.

But what I need now is automatically doing this through script. So after I deploy the azure function using json template. I will using Kudu REST API to create a folder(actually the folder name is the new function' name). And upload the index.js and function.json into that file.

I tried to upload the function.json and  index.js which does not require any npm package,  After that, without doing anything else. I can observe a lot of "function started" logs, and receive timeout error after 5 min. any suggestions?

**Comment by jdneo** [comment]
Seems that after upload the function.json file, I must call the synctrigger REST api:

https://management.azure.com/subscriptions/{subscription}/resourceGroups/{group}/providers/Microsoft.Web/sites/{functionname}/functions/synctriggers?api-version=2015-08-01

Am I right?

**Comment by jdneo** [comment]
Ok, I guess I have figured out the reason of this issue. Though I'm not qiute sure if this is the real reason or not.

I have an iot hub for my test work. And I have used it to trigger an azure function. Also I have sent a lot of msgs to it.

And when I was doing the azure provision script. I used the same iot hub to trigger the azure function that provisioned through my script. It seems that the event hub thinks that the msgs I sent before were not consumed. So when the new function app is created, it will be triggered a lot of times (a lot of 'function started show in the console'). And because the function is just created, it has to spend some time to 'wake up'. So it's difficult for the function app to handle such amount of requests. Then a lot of 'Timeout' & 'Could not send message' error appear in the console

If I create a new iot hub, and binding it to a new function app, every thing is fine.

**Comment by mamaso** [comment]
@jdneo I'm surprised you got a timeout after removing the iothub package / connection - I'd suspect that you might not be calling context.done.

The large amount of queued messages is expected, if they were not all consumed from your event hub on previous function runs.

Closing this, but feel free to reopen / ask more questions if you have them.

**Comment by jdneo** [comment]
Hi @mamaso , thank you for your reply. Just one more thing to ask.

I'm confused about 'not all consumed from your event hub on previous function runs'.

Does that mean I have to open an eventhub client and receive the msg in the function app? In the [azure event hub node sdk](https://github.com/Azure/azure-event-hubs-node/blob/master/samples/javascript-eventhub-sample/simple_eventhubs_client.js), I cannot find method doing the consuming action. The sample code just receive the events. 

Just curious about this. Maybe I should ask this question in the event hub repo

**Comment by tohling** [comment]
@jdneo, could you try changing your Function to process the EventHub messages in batches?  You can do so with the following 2 steps:

1. Add "cardinality": "many" as a new property in your input binding in your function.json file.
2. Encapsulate your Function code in a FOR-loop to process an array of events instead. I changed the name of your input-binding to **myEventHubMessages** to indicate plurality.

```
'use strict';

const Client = require('azure-iothub').Client;
const Message = require('azure-iot-common').Message;
const iotHubConnectionString = process.env['speech-recognition-iothub'];

// renamed your input-binding to myEventHubMessages
module.exports = function (context, myEventHubMessages) {
  context.log(util.format("Node.js script processed %d events", myEventHubMessages.length));
  context.log("IsArray", util.isArray(myEventHubMessages));
  const cloudClient = Client.fromConnectionString(iotHubConnectionString);

  cloudClient.open(function (err) {
  if (err) {
    console.log('Could not connect: ' + err.message);
  } else {
    console.log('Client connected');
    for (i = 0; i < myEventHubMessages.length; i++)  
	{
      context.log(myEventHubMessages[i]);
      if (myEventHubMessages[i].DeviceID) {
        const message = new Message(`Pong - ${new Date().toTimeString()}`);
		cloudClient.send(myEventHubMessages[i].DeviceID, message, function (err, res) {
		  if (err) {
		    context.log(`Error in send C2D message: ${err}`);
		  } else {
		    context.log(`send status: ${res.constructor.name}`);
		  }
		});	
	  }
	}	
  }
	
  context.done();
  cloudClient.close()// not sure if this is the syntax in Node for cloudClient
};
```

A similar Function setup can be found at:
https://github.com/Azure/azure-webjobs-sdk-script/tree/dev/sample/EventHubTrigger

**Comment by mamaso** [comment]
@jdneo The event hub queues messages - if the function hasn't yet emptied that queue when you stop your function, when the function starts it will continue reading from that queue.

You don't need to do anything with the event hub client in your function app to consume messages, this happens automatically.

@tohling has a good suggestion which should improve your function throughput, helping it to keep up with the input to your event hub.

**Comment by tohling** [comment]
@mamaso, @jdneo, actually the suggestion to process the events on batches is due to the fact that I have seen this behavior before with another customer.  His Event Hub had a sustained large load of incoming messages and he would only see "Function started(...)" entries in the log with no corresponding "Function completed(...).  When he switched to batch processing, the problem went away.

I would suggest that you try processing in batch to see if the problem goes away.

**Comment by paulbatum** [comment]
Agreed about JS. I filed #429.

**Comment by jdneo** [comment]
Thank you guys! According to your suggestion, I figure out the mistakes I made:

1. context.done() should be ensured to be called

e.g.
```
cloudClient.open(function (err) {
    if (err) {
        // error handler
        context.done()
    } else {
        //success handler
        context.done()
    }
});
```
Put the context.done() inside the callback function can make the 'function complete' log always show in the last step of the function execution

2. cloudClient.close() should be called.
In my investigation, if cloudClient.close() is not called, it will encounter some problems to open the client in the next function trigger.

Thank you again!
