### ISSUE TITLE
Question: Creating Azure functions in NodeJS

### ISSUE THREAD

**Issue by kvsurii** [Azure/azure-webjobs-sdk-script#1389]
Hey, Curious to know if there is a way to create BlobTrigger Azure functions in NodeJS, and not from the Azure portal. I want to specify the storage account connections, triggers, inputs & outputs while creating this function. 
P.S - Not sure if this is the right forum to ask!

**Comment by lindydonna** [comment]
@kvsurii The best place for this kind of question is the MSDN forums (https://aka.ms/func-forum) or StackOverflow (https://aka.ms/func-so), but we can answer here. 

You can create the Function locally using the Azure Functions CLI. See a walkthrough here: https://blogs.msdn.microsoft.com/appserviceteam/2016/12/01/running-azure-functions-locally-with-the-cli/. You can also use the new Serverless Framework plugin for Azure Functions: https://serverless.com/blog/azure-functions-and-possibility/
