### ISSUE TITLE
DocumentDB input binding doesn't recognize named parameter (when using ServiceBus trigger)

### ISSUE THREAD

**Issue by nik-pinchuk** [Azure/azure-webjobs-sdk-script#1396]
Trying to use this type of queue based trigger with DocumentDB input binding like in this Azure GitHub repo: https://github.com/Azure/azure-content-nlnl/blob/master/articles/azure-functions/functions-bindings-documentdb.md

Specifically our attempt at this binding looks like this
```
{
"bindings": [
{
"type": "serviceBusTrigger",
"name": "queueTrigger",
"queueName": "fixtureids",
"connection": "fixtureids_connection",
"accessRights": "Manage",
"direction": "in"
},
{
"type": "documentDB",
"name": "inputDocument",
"databaseName": "1",
"collectionName": "fixtures",
"connection": "docdb-qtriggertest_DOCUMENTDB",
"direction": "in",
"id": "{queueTrigger}"
}
],
"disabled": false
}
```

And the function itself looking like this:

```
public static void Run(string queueTrigger, dynamic inputDocument, TraceWriter log)
{ 
log.Info(queueTrigger);
inputDocument.name = "This has changed now again.";
}
```

The part of this that doesn't work is "id": "{queueTrigger}", it doesn't map this to the actual message value on the queue (which is successfully logged in console though) and you get this: "Exception binding parameter 'inputDocument'. Microsoft.Azure.WebJobs.Host: No value for named parameter 'queueTrigger'." If we replace {queueTrigger} with hardcoded document id in the binding it does successfully retrieves and updates the document from the connected DocumentDB when new message arrives on the queue. 

Is there a missing documentation for how named parameters are populated or am I missing something altogether?

P.S. Cross-posting from azureadvisors, as advised by Donna (https://www.yammer.com/azureadvisors/#/threads/show?threadId=871546798)

**Comment by christopheranderson** [comment]
We have a hunch. Can you try to rename the "name" to something other than "queueTrigger"? You might be "overwriting" our built-in for "queueTrigger".

**Comment by paulbatum** [comment]
Closing with no further activity.
