### ISSUE TITLE
Improved host-level logging for extension failures  on startup

### ISSUE THREAD

**Issue by MikeStall** [Azure/azure-webjobs-sdk-script#1417]
If the users brings their own binding, that can introduce failures on startup. We need some means of communicating those failures (beyond kusto logs).

**Comment by christopheranderson** [comment]
@brettsam - can you confirm this is covered by your current app insights scope?

**Comment by christopheranderson** [comment]
@MikeStall - you should be able to confirm this shows up in the host logs (when the portal is open or you set the logging to "always")

App Insights is still the best solution.

**Comment by brettsam** [comment]
@MikeStall -- Do you have a good repro that I can use to make sure that the logs that you're looking for make it to App Insights? Since we log all host logs, I suspect they are. I just want to verify.

**Comment by brettsam** [comment]
Some context from our discussions. 

The plan is that any extension that fails to load or initialize will be logged and the host will continue to load and intitialize other extensions. After #1670 is in, all of the **load** scenarios should be caught and logged as expected.

However, **initialization** is handled in the WebJobs SDK here: https://github.com/Azure/azure-webjobs-sdk/blob/5d55eb1614c9146625c0179de9cdad530ea3ca17/src/Microsoft.Azure.WebJobs.Host/Executors/JobHostConfigurationExtensions.cs#L379. We'll need a separate fix to implement the proper handling and logging of initialization there. I've created https://github.com/Azure/azure-webjobs-sdk/issues/1222 to track that.
