### ISSUE TITLE
Flow auth header to bindings for on-behalf bindings

### ISSUE THREAD

**Issue by MikeStall** [Azure/azure-webjobs-sdk-script#1418]
1.	For the on-behalf scenario, the bindings need the raw auth token. Specifically, they need a signed identity that they can use for a token exchange. (an IPrinciple is not enough)
2.	The bindings should not get the raw HttpRequestMessage. That would be invasive and let them do bad things (like take dependencies on any part of the request, steal request properties, switch on query parameters, etc). 
3.	It’s nice to be consistent and not single out the auth header. It’d be nice to expose all headers, although we don’t hafve a means to do that today.  

One option is to expose headers as:
“Request[Header]Header”
So this would be “RequestAuthorizationHeader”
We might start with auth header or now, and light  up the rest later.   

(This is what https://github.com/Azure/azure-webjobs-sdk-script/pull/1402 is doing) 

If { } expressions allowed dots, we could do something really general like “{request.headers.authorization}”. But we don’t have that SDK feature.

**Comment by christopheranderson** [comment]
Vote in favor on the "dot" based way. Had other requests similar to this.

**Comment by mattchenderson** [comment]
Actually, Proxies uses the dot syntax, exactly as you have in the example above: {request.headers.authorization}

This is not yet documented due to a bug, but that is the model that that feature uses. Might be good to keep those aligned.

**Comment by mathewc** [comment]
Closing this, since it is resolved now. Right @MikeStall ?
