### ISSUE TITLE
Allow extensions to have return values on trigger 

### ISSUE THREAD

**Issue by MikeStall** [Azure/azure-webjobs-sdk-script#1422]
This is needed for DTF to do return values. We should also be able to leverage it for Http. 
This shrinks usage of IResultProcessingBinding and the hack we have here:

https://github.com/Azure/azure-webjobs-sdk-script/blob/dev/src/WebJobs.Script/Binding/GeneralScriptBindingProvider.cs#L129
_applyReturn = attribute.GetType().GetMethod("ApplyReturn", BindingFlags.Static | BindingFlags.Public | BindingFlags.NonPublic);

This is basically the script side for consuming https://github.com/Azure/azure-webjobs-sdk/issues/1104

**Comment by lindydonna** [comment]
VS tooling depends on this, see https://github.com/Azure/azure-webjobs-sdk-script/issues/1508

**Comment by MikeStall** [comment]
We have support for return values in the SDK, this part now means:
- removing the CanProcessResult stuff in Script. 
- script's IL gen wrapper today converts return values to 'out T'. Instead, it should convert to return value and let SDK bind against that. 
- This will need an update from HttpBinding. (I have a branch with that)

**Comment by cgillum** [comment]
JFYI, the Durable Functions issue blocked on this is here: https://github.com/Azure/azure-functions-durable-extension/issues/13

**Comment by lindydonna** [comment]
@cgillum Afaik this issue has been fixed, except possibly HttpBinding.

**Comment by cgillum** [comment]
@lindydonna you may be confusing this issue with https://github.com/Azure/azure-webjobs-sdk/issues/1104, which was fixed. This issue specifically tracks adding support to the scripts repo - i.e. for non-VS projects. Right now, only HttpBinding supports return value processing via some hacks. Mike can provide the details since I regularly bug him about this. :)

**Comment by MikeStall** [comment]
Right. Remaining work is described in my previous comment on this thread, https://github.com/Azure/azure-webjobs-sdk-script/issues/1422#issuecomment-316556686

**Comment by lindydonna** [comment]
@MikeStall @cgillum Thanks for the clarification. It's hard to keep track of all these details, so I appreciate these explanations. :)

**Comment by MikeStall** [comment]
This is a breaking change, so we're just checking into Core (not dev). 
The reason it's a break is that before, unused return parameters are ignored. That was mostly a side-effect of the implementation and not an explicit design choice.  
Now, unused return parameters are an indexing error.  This is behavior inherited from SDK's binding rules. 

For example, before this would succeed, even through it's most likely a user bug (mismatched httpresponse and queue trigger) 
```
  HttpResponseMessage Func ([QueueTrigger] Foo x)   
```

**Comment by MikeStall** [comment]
Fixed in /Core.
