### ISSUE TITLE
Investigate eventsource performance for high-throughput scenarios

### ISSUE THREAD

**Issue by mamaso** [Azure/azure-webjobs-sdk-script#1427]
Determine whether moving from the `WriteEvent(int eventId, params object[] args)` overload is worthwhile

See: https://msdn.microsoft.com/en-us/library/system.diagnostics.tracing.eventsource.writeeventcore(v=vs.110).aspx

**Comment by paulbatum** [comment]
Dupe of https://github.com/Azure/azure-webjobs-sdk-script/issues/1362
