### ISSUE TITLE
Error binding to blob triggers after updating function.json

### ISSUE THREAD

**Issue by amang2205** [Azure/azure-webjobs-sdk-script#1440]
Manually invoking a function to run, throws the following error: '2017-04-20T23:07:48.581 Exception while executing function: Functions.ManualTriggerCSharp4. Microsoft.Azure.WebJobs.Host: One or more errors occurred. Exception binding parameter 'image'. Microsoft.Azure.WebJobs.Host: Blob identifiers must be in the format 'container/blob'.'
The function in matter runs a pre-compiled C# function.

#### Repro steps

Provide the steps required to reproduce the problem

1. Create a new Manual Trigger function, based on C# (https://1drv.ms/i/s!AiH6U1JLlpoBoMdx11vCi3qr_JV0TQ).
2. Upload .dll file; in this case, Codermon.dll - source code available on-line (https://1drv.ms/i/s!AiH6U1JLlpoBoMdv7NuOnm7LzpYHeA)
3. Delete run.csx file (https://1drv.ms/i/s!AiH6U1JLlpoBoMdwPLT7dZI4MsXuCw)
4. Update function.json file and click 'Save' (https://1drv.ms/i/s!AiH6U1JLlpoBoMdyS_NodoSXLnxhAg)
5. The function runs (see logs) (https://1drv.ms/i/s!AiH6U1JLlpoBoMdz-JhNWlpTcfcRFw)
6. Click 'Save and run' (https://1drv.ms/i/s!AiH6U1JLlpoBoMd0MAlUswwpOkXmQQ). Rather than just running, the function returns the following exception: '[...] Exception while executing function: Functions.ManualTriggerCSharp4. Microsoft.Azure.WebJobs.Host: One or more errors occurred. Exception binding parameter 'image'. Microsoft.Azure.WebJobs.Host: Blob identifiers must be in the format 'container/blob'.'

![1](https://cloud.githubusercontent.com/assets/5773281/25256359/dabe3896-2638-11e7-926a-f171da4d754b.png)
![2](https://cloud.githubusercontent.com/assets/5773281/25256358/dabd165a-2638-11e7-8818-f4ccf48fe88a.png)
![3](https://cloud.githubusercontent.com/assets/5773281/25256361/dac17844-2638-11e7-9efe-eeceb42e63b5.png)
![4](https://cloud.githubusercontent.com/assets/5773281/25256357/dabb875e-2638-11e7-9015-59d68ff759f8.png)
![5](https://cloud.githubusercontent.com/assets/5773281/25256360/dac03b3c-2638-11e7-8ed9-cb9ff3655a73.png)
![6](https://cloud.githubusercontent.com/assets/5773281/25256362/dac42e2c-2638-11e7-8cbb-4f90ec30edcf.png)

#### Expected behavior

Run as expected and loop through existing blobs in the container.

#### Actual behavior

Provide a description of the actual behavior observed. 

#### Known workarounds

Create a new function from scratch.

#### Related information 

Provide any related information 
* using C#
* source code available on https://github.com/amang2205/Codermon/tree/master/CoderCardsWebsite

**Comment by lindydonna** [comment]
@amang2205 Ah, I think this is actually a portal bug, that I've previously observed but didn't actually file a bug for. Is it just the test tab that behaves incorrectly?

**Comment by christopheranderson** [comment]
@paulbatum - can you confirm the repro and investigate?

**Comment by amang2205** [comment]
Feel free to reach out to me if you want to me go through the steps of reproduction and see the error occurring live. Thanks.

**Comment by paulbatum** [comment]
@amang2205 So these repro steps involve turning the function into a blob triggered function right? When you hit the Save and Run button, its going to use the values in the Request Body section of the Test tab as parameters for this particular execution. So because this function is blob triggered, in this case those parameters are the path to the blob that you want to simulate a change event for.

So in your screen shot 6, I can see that the Request Body is still set to Test Value. That's the input that the error is complaining about. Change that to be a path to one of your images, e.g. "inputcontainer/paul.jpg" and then your function will run for that image.

**Comment by paulbatum** [comment]
Here is the tracking bug for improving the Test tab UI to help with cases such as blob trigger: https://github.com/projectkudu/AzureFunctionsPortal/issues/900

**Comment by paulbatum** [comment]
Closing as answered. See linked issue above.

**Comment by zhangruiskyline** [comment]
Hello, I had the same bug, where I can successfully run the azure functions in local dev, but after publish to azure cloud, it always remind me the binding issue, what is wrong?
