### ISSUE TITLE
Azure Function timer trigger not firing

### ISSUE THREAD

**Issue by onionhammer** [Azure/azure-webjobs-sdk-script#1445]
Please provide a succinct description of the issue.
Similar to #740, the azure function in question is in the same resource group as dummy124441.azurewebsites.net

The timer is set to run on this schedule ( 0 */15 * * * * ), every 15 minutes, but the last time it ran according to the invocation log is (2017-04-19T14:30:0 ...)

#### Expected behavior

I would expect the function to run every 15 minutes

#### Actual behavior

The function does not run unless I trigger it manually

**Comment by paoliniluis** [comment]
having the same issue here, although I have it schedule for everyday at a certain hour it will never fire

**Comment by davidebbo** [comment]
@paoliniluis you may be running into a different issue ([discussed here](https://social.msdn.microsoft.com/Forums/azure/en-US/394ef8a7-3f17-47c5-8443-17723c9a856e/invocation-logs-not-updating-in-portal?forum=AzureFunctions)). Where the function does execute, but the Monitor UI doesn't show the invocations. Please see that thread for workaround.

**Comment by onionhammer** [comment]
@davidebbo yes, it looks like the same issue. I do see that it's being invoked, just not appearing in the invocation log in azure anymore

**Comment by karandesai28** [comment]
Facing same issue, Function does **not** execute unless I open the function in portal. I am using consumption plan, and by that I think there is no need for Always On as the system should take care of waking up my functions whenever they need to run.

**Comment by davidebbo** [comment]
@karandesai28 please provide the app name and UTC time when you expected it to fire and it didn't.

**Comment by davidebbo** [comment]
@karandesai28 actually, please open a separate issue. The two cases in here were actually just the monitoring issue (long fixed), and the functions were in fact getting invoked. So closing this one.

**Comment by komainu85** [comment]
I'm actually experiencing this issue currently with one of my functions. Runs ever hour with this hourly schedule  "0 0 * * * *", it works for a few hours then stops. A restart starts it working again, after a few hours it stops again. Sometimes it can run twice in an hour, with a few minutes gap.
