### ISSUE TITLE
Precompiled function for HttpTrigger is referring the System.Net.Http (4.1.1.0) instead of 4.0.0.0

### ISSUE THREAD

**Issue by soninaren** [Azure/azure-webjobs-sdk-script#1454]
**Repro steps**

1. Create a new Class Library project. 
2. Add the following nuget packages 
   Microsoft.Azure.WebJobs 2.0.1-alpha1-10667
   Microsoft.Azure.WebJobs.Extensions.Http 1.0.0-alpha1-10432
3. Create a class file with the following contents 

```CSHARP
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Threading.Tasks;
using Microsoft.Azure.WebJobs;
using Microsoft.Azure.WebJobs.Extensions.Http;
using Microsoft.Azure.WebJobs.Host;


namespace Template
{
    public static class HttpTriggerCSharp
    {
        [FunctionName("HttpTriggerCSharp")]
        public static async Task<HttpResponseMessage> Run([HttpTrigger(AuthorizationLevel.%AuthLevel%, "get", "post", Route = null)]HttpRequestMessage req, TraceWriter log)
        {
            log.Info("C# HTTP trigger function processed a request.");

            // parse query parameter
            string name = req.GetQueryNameValuePairs()
                .FirstOrDefault(q => string.Compare(q.Key, "name", true) == 0)
                .Value;

            // Get request body
            dynamic data = await req.Content.ReadAsAsync<object>();

            // Set name to query string or body data
            name = name ?? data?.name;

            return name == null
                ? req.CreateResponse(HttpStatusCode.BadRequest, "Please pass a name on the query string or in the request body")
                : req.CreateResponse(HttpStatusCode.OK, "Hello " + name);
        }
    }
}
```

4. Create a function.json file with following contents HttpTriggerCsharp/Function.json

```JSON
{
  "bindings": [
    {
      "type": "httpTrigger",
      "methods": [
        "get",
        "post"
      ],
      "authLevel": "function",
      "direction": "in",
      "name": "req"
    },
    {
      "name": "$return",
      "type": "http",
      "direction": "out"
    }
  ],
  "disabled": false,
  "scriptFile": "..\\Template.dll",
  "entryPoint": "Template.HttpTriggerCSharp.Run"
}
```

5. Deploy the files to the Azure

**Errors**
The results into the following error in the portal.

> Exception while executing function: Functions.HttpTriggerCSharp. mscorlib: Exception has been thrown by the target of an invocation. Template: Method not found: 'System.Net.Http.HttpResponseMessage System.Net.Http.HttpRequestMessageExtensions.CreateResponse(System.Net.Http.HttpRequestMessage, System.Net.HttpStatusCode, !!0)'.

Few other notes on this.
1. **Microsoft.Azure.WebJobs**package has a dependency on the package. Microsoft.Extensions.Logging.Abstractions (1.1.1) resolving the dependency causes the System.Net.Http 4.1.1.0

Workaround
- Remove the reference to System.Net.Http 4.1.1.0 and add the reference to System.Net.Http (4.0.0.0).

**Comment by brettsam** [comment]
@soninaren -- you remove the reference locally and rebuild?
@fabiocav -- did you see this issue? This will affect anyone precompiling with our latest packages (which shouldn't be anyone right now), but I'm not sure what the right solution is.

**Comment by brettsam** [comment]
Actually, @soninaren, where you deploying this to an app with the current production bits? Or were you trying the latest "beta" or pre-release? If you were using prod, can you try one of the other two?

**Comment by soninaren** [comment]
I tested this with latest bits using private site extension. Binding redirect is working fine. Closing this issue.
