### ISSUE TITLE
QueueTrigger function from Quickstart shows Indexing method error

### ISSUE THREAD

**Issue by davidebbo** [Azure/azure-webjobs-sdk-script#1456]
_From @SimonGuo009 on April 25, 2017 9:47_

Environment URL: functions.azure.com
Corresbonding Ibiza URL: ms.portal.azure.com
App runtime version: ~1
Proxy runtime version: ~0.2
**Private Site Extension**: 1.0.10913

Repro steps:
1. Create a new function app.
2. Click on "+" button to open Quickstart page.
3. Choose "Data Processing" then click create. (Language does not matter)
4. Verify its Develop was opened automatically, along with the error messages.

Please refer to snapshot:
![bug2_quickstartqueuetrigger](https://cloud.githubusercontent.com/assets/18321627/25379296/266e8968-29df-11e7-8831-8dd0cba5ad00.png)

_Copied from original issue: projectkudu/AzureFunctionsPortal#1244_

**Comment by davidebbo** [comment]
We saw an issue with a very similar error yesterday in triage, but I can't seem to find it. @christopheranderson , @fabiocav?

I tried with the new build and did not see this when creating a new queue triggered function. So I'm thinking it's caused by something else and may not be a regression in the new build (though still it's bad, obviously).

**Comment by davidebbo** [comment]
_From @fabiocav on April 25, 2017 16:24_

This was the issue we looked at yesterday: https://github.com/Azure/azure-webjobs-sdk-script/issues/1446

**Comment by davidebbo** [comment]
Ok, so same error, but in that case, I think she really had a missing connection string, while here it should have been clean.

**Comment by davidebbo** [comment]
We've now confirmed that it's a regression. It happens when `connection` is set to empty, which is what the **quickstart** does (as opposed to the normal templates):

```
{
  "disabled": false,
  "bindings": [
    {
      "name": "myQueueItem",
      "type": "queueTrigger",
      "direction": "in",
      "queueName": "myqueue-items",
      "connection": ""
    }
  ]
}
```

If you do this with new build, it fails with:

```
Error:

Function ($QueueTriggerCSharp2) Error: Microsoft.Azure.WebJobs.Host: Error indexing method 'Functions.QueueTriggerCSharp2'. Microsoft.Azure.WebJobs.Host: Microsoft Azure WebJobs SDK '' connection string is missing or empty. The Microsoft Azure Storage account connection string can be set in the following ways:
 1. Set the connection string named 'AzureWebJobs' in the connectionStrings section of the .config file in the following format <add name="AzureWebJobs" connectionString="DefaultEndpointsProtocol=http|https;AccountName=NAME;AccountKey=KEY" />, or
 2. Set the environment variable named 'AzureWebJobs', or
 3. Set corresponding property of JobHostConfiguration.
Session Id: 9e440394ce974b90a2a2972c6655f11e

Timestamp: 2017-04-25T17:25:59.120Z
```

**Comment by davidebbo** [comment]
@MikeStall, @mathewc thinks this is a regression from the BYOB changes. What do you make of it?

**Comment by mamaso** [comment]
https://github.com/Azure/azure-webjobs-sdk/blob/e2fafe557738c09fdd1130517531e57570ebd3ba/src/Microsoft.Azure.WebJobs.Host/Executors/StorageAccountProviderExtensions.cs#L44

This needs to be `string.IsNullOrWhitespace`

It's related the the `IConnectionProvider` changes - before we must have kept Connection null in this case?

**Comment by MikeStall** [comment]
It looks like it was regressed in this change: https://github.com/Azure/azure-webjobs-sdk/commit/e2fafe557738c09fdd1130517531e57570ebd3ba

```
if (string.IsNullOrEmpty(connectionStringName))  
{ 
    connectionStringName = ConnectionStringNames.Storage; 
} 
```
got changed to:
```
connectionStringName = connectionStringName ?? ConnectionStringNames.Storage; 
```
So good news is this was a simple well-understood tweak. 
I have a local fix and unit test; I'm scanning through for other cases.

**Comment by paulbatum** [comment]
Closing as fixed
