### ISSUE TITLE
How to control the max concurrent calls (for a servicebus trigger)?

### ISSUE THREAD

**Issue by lindydonna** [Azure/azure-webjobs-sdk-script#1466]
_From @worldspawn on February 6, 2017 3:4_

Hello,

I was wondering how one can control the maximum number of concurrent calls a service bug trigger will run. In my case the code is hitting a sql server so theres only so much concurrency I want going on. 

Webjobs api allows you to do this when configuring the service bus however it doesn't allow control over specific triggers (just all service bus triggers) which causes you to deploy more webjobs than u would otherwise need - hope theres better control for functions.

_Copied from original issue: Azure/Azure-Functions#176_

**Comment by paulbatum** [comment]
@worldspawn there's a configuration knob for this, see here (service bus section0: https://github.com/Azure/azure-webjobs-sdk-script/wiki/host.json

One note is that these knobs are per running instance of your function app so if you're scaling out you'll also need the ability to control the max instances. We have a new setting coming for this, I can update this issue once I have some info.

**Comment by paulbatum** [comment]
@worldspawn see [here](https://github.com/projectkudu/kudu/wiki/Configurable-settings#limit-the-scaling-of-function-apps).

**Comment by paulbatum** [comment]
Closing as answered

**Comment by georgiosd** [comment]
Wasn't this updated from unbounded to 50? https://github.com/Azure/azure-functions-host/issues/2085

**Comment by paulbatum** [comment]
Nope, these are different settings.

**Comment by georgiosd** [comment]
Can you explain please? I can't quite link the two.

**Comment by paulbatum** [comment]
The number of service bus triggered executions that run concurrently has nothing to do with [ServicePointManager.DefaultConnectionLimit](https://msdn.microsoft.com/en-us/library/system.net.servicepointmanager.defaultconnectionlimit(v=vs.110).aspx). Perhaps do some more reading on `ServicePointManager.DefaultConnectionLimit`.. for example you might find [this post](https://blogs.msdn.microsoft.com/jpsanders/2009/05/20/understanding-maxservicepointidletime-and-defaultconnectionlimit/) informative.
