### ISSUE TITLE
Telemetry Initializers and processors support

### ISSUE THREAD

**Issue by christopheranderson** [Azure/azure-webjobs-sdk-script#1467]
_From @bveerendrakumar on March 25, 2017 2:1_

Hi,

I have gone through app insights support for azure functions. There are some very key functionalities that App insights support are missing/not enabled. These are very important in Enterprise scenarios.

1) Telemetry Initializers
2) Telemetry Processor
3) Managing configuration thorough AI.config or code.
4)  Telemetry Channel properties and sampling modules.

The above mentioned features are used in many Enterprise scenarios to collect consistent, reliable, business oriented and correlatable Telemetry across apps. One Enterprise scenario may cut across various components like web, services, functions, workflows like logic apps etc.. It is important for us to have consistency in collecting, using the collected telemetry to complete that Enterprise scenario.

Without giving such control which is allowed by App Insights SDK today, providing just few scenarios may not help much in Enterprise scenarios. It might just provide only engineering scenarios like monitoring and diagnostics for that function alone. But Telemetry for a function alone will not help because in Enterprise application scenarios a function is just a small piece of code.

_Copied from original issue: Azure/Azure-Functions#225_

**Comment by christopheranderson** [comment]
_From @bveerendrakumar on March 25, 2017 2:2_

Please feel free to contact me @vballa (company email) for more details or want to understand more from us on Enterprise business scenarios.

**Comment by christopheranderson** [comment]
_From @lindydonna on March 27, 2017 19:43_

CC @christopheranderson

**Comment by paulbatum** [comment]
@brettsam consider this feedback as we prepare app insights integration to go GA. Need to figure out the right balance here between extensibility and ease of use.

**Comment by brettsam** [comment]
We'll close this and track through #1579 -- a general way to wire up some key services.
