### ISSUE TITLE
Blobtrigger - Local Testing / Debugging Documentation

### ISSUE THREAD

**Issue by securityvoid** [Azure/azure-webjobs-sdk-script#1476]
I'm having a difficult time locating the documentation on debugging Blob trigger's locally. Is this possible with the CLI, or does stuff have to be deployed on Azure to test?

The main place you'd expect documentation is pretty much blank:
https://docs.microsoft.com/en-us/azure/azure-functions/functions-run-local

This is the best docs I've found so far, but it leaves Blogtrigger's absent:
https://blogs.msdn.microsoft.com/appserviceteam/2016/12/01/running-azure-functions-locally-with-the-cli/

There are a few entries in the CLI that make it sound like it maybe supported, but real examples would really help.

**Comment by paulbatum** [comment]
@lindydonna Can you take a quick look at this?

**Comment by securityvoid** [comment]
Via trial and error, I was able to determine that local debugging of blog triggers DOES work. When the Azure Functions is running locally and a blog trigger is triggered, it will trigger the blob functions locally.

I still think this could handle to be doced clearer, but it definitely works.

**Comment by securityvoid** [comment]
While the doc is being worked on, it would also be good if somewhere it was more clear if blob triggers are only triggered on the creation of new files, and the updating of files, or if it also included the deletion of files (And if there is anyway to tell the difference).

The wording that is available is a little ambiguous with exactly how it works. Actually trying this stuff, its sometimes a little difficult to tell since if your function fails, it will retry. As a result, telling the difference between a retry (which has a delay), or the result of some other action you did (e.g. delete) complicates the empirical testing of this.

Its on my list of things to do to test this more carefully, but it would be even better if it was DOCed and I didn't have to guess/test.

**Comment by lindydonna** [comment]
@securityvoid I'm working on an updated doc this week. We had a lot of churn in the CLI commands, but it's much more stable now.

I'm moving this issue to Azure-Functions, where we track dock issues.

Blob triggers are only triggered on creates and updates. Deletes are not tracked, and there is no way to distinguish between create and update (without looking at the blob metatdata itself).

In general, queue triggers with a blob input are more reliable. For an example, see https://github.com/lindydonna/CoderCardsV2/blob/master/CoderCards/CardGenerator.cs#L20

**Comment by lindydonna** [comment]
This issue was moved to Azure/Azure-Functions#310
