### ISSUE TITLE
BlobTrigger - Crashes with name pattern in Container Name

### ISSUE THREAD

**Issue by securityvoid** [Azure/azure-webjobs-sdk-script#1482]
Having a blogTrigger with name pattern within the container name part of the path crashes the CLI, and I assume the real webjobs SDK (but these do differ at times, and I never bothered deploying since it wasn't running locally). 

The error returned is:
```
An unhandled exception has occurred. Host is shutting down.
Microsoft.WindowsAzure.Storage: The remote server returned an error: (400) Bad Request.
```

#### Repro steps

1. Create a BlobTrigger such as the following:
```
{
  "disabled": false,
  "bindings": [
    {
      "name": "blobInput",
      "type": "blobTrigger",
      "direction": "in",
      "path": "a-{var1}-{var2}/{file}",
      "dataType": "binary",
      "connection":"AZURE_STORAGE_CONNECTION_STRING"
    }
  ]
}
```

2. Create a container that matches the pattern e.g.:
a-b-c

3. Run the Function App so its listening.

4. Add a file to the container you created.

NOTE: When the file is found, the CLI will crash given the error:
```
An unhandled exception has occurred. Host is shutting down.
Microsoft.WindowsAzure.Storage: The remote server returned an error: (400) Bad Request.
```

#### Expected behavior

The blogtrigger is handled properly by the proper code.

#### Actual behavior

An error is received and code is never executed:
```
An unhandled exception has occurred. Host is shutting down.
Microsoft.WindowsAzure.Storage: The remote server returned an error: (400) Bad Request.
```

#### Known workarounds

Don't use the name pattern in the part of the name that matches the container.

**Comment by paulbatum** [comment]
We need to confirm whether this is supposed to be supported or not. If not, then at least a better error handling path is necessary here.

**Comment by mamaso** [comment]
Currently, this is unsupported - blob listeners work on the assumption that they have a concrete container to listen on. Adding an error message should be an easy fix.

One strategy to enable this - at index time, enumerate containers and create a listener for each which matches the pattern. Could say that new containers are ignored until a restart, or periodically monitor for them.

However, I don't think we should go down this path unless if there's a compelling reason - containers have no size limits, so throwing all blobs in the structure `somecontainer/a-{var1}-{var2}/{file}` would have the same effect with no real drawbacks.

**Comment by securityvoid** [comment]
@mamaso If it was doced/better error message, that would be plenty good enough for me. My only frustration was in spending all the time debugging to determine it wasn't something supported. I ended up goning the route you stated as a work around, and that works just fine.
