### ISSUE TITLE
Error on renewing _masterKey when keys are on blob

### ISSUE THREAD

**Issue by ahmelsayed** [Azure/azure-webjobs-sdk-script#1483]
I sometimes see this 500 error on a `POST /admin/host/keys/_master`

```json
{
  "id": "66ff4784-59b6-4d20-a2a6-bdcd0940aab5",
  "requestId": "1f4c472a-086e-4a6f-98c8-3236077fa747",
  "statusCode": 500,
  "errorCode": 0,
  "messsage": "The remote server returned an error: (400) Bad Request. -> The remote server returned an error: (400) Bad Request."
}
```

**Comment by paulbatum** [comment]
@krolson Could this be a bad request coming from Azure storage? can you investigate?

**Comment by krolson** [comment]
@ahmelsayed was this around while there were instances of the UI open (i.e. when you were noticing this behavio: https://github.com/projectkudu/AzureFunctionsPortal/issues/1296?) or can you share any other information on this, like region or if you noticed it specifically for this master key POST or if that was the only key POST you were trying?
@fabiocav is there special handling in the keymanagement for _master key that comes to mind? The blob storage repository treatment is essentially the same for master vs any other key, so this would be a more broad issue if it's storage related.

**Comment by fabiocav** [comment]
The master key is not handled in a special way (not any different than other keys in the host secrets file). @ahmelsayed ran into this a while ago, but if we can repro and look at the actual storage exception details leading to the bad request, it might be easier to identify what is going on here.

**Comment by krolson** [comment]
I tried doing dozens of /admin/host/keys/_master POSTs on my function test site, even alternating between UI and direct requests, but they are all working. Since I haven't been able to get a repro, I was hoping to try to look at logs from when @ahmelsayed hit the issue, but didn't find anything in my limited check without a specific time, site name, or region.

**Comment by fabiocav** [comment]
@ahmelsayed I know this was a while back, but do you have storage (or application) logs for this?

**Comment by ahmelsayed** [comment]
@krolson I tried to do the same now, but couldn't get a repro either. I'll close this as no repro, and will open it again if I see the error again.
