### ISSUE TITLE
Slot and site are using the same blob key storage rather than independent keys

### ISSUE THREAD

**Issue by krolson** [Azure/azure-webjobs-sdk-script#1486]
Please provide a succinct description of the issue.

#### Repro steps

Provide the steps required to reproduce the problem

1. Created site with HttpTrigger function, then create slot create another HttpTrigger function (slot name contains a "-" character). Restart the slot.
2. Get function URL or add a new setting on the slot - it uses the same key as site. On blob only the primary site gets a secret file added for the HttpTrigger function

#### Related information 
Slot name contained a "-" character - possibly there is something strange about handling this.

**Comment by krolson** [comment]
EDIT: looks like issue is that the slot did not get WEBSITE_SLOT_NAME setting (or somehow lost it, since the blob repository sitename-slotname was created?) it's not in Environment settings.

**Comment by paulbatum** [comment]
The slot setting resetting when a restart occurs is being fixed in the next platform deployment, so closing this.
