### ISSUE TITLE
FunctionsController is not respecting IsAuthDisabled flag

### ISSUE THREAD

**Issue by ahmelsayed** [Azure/azure-webjobs-sdk-script#1487]
Repro:

1. Set IsAuthDisabled to true
2. Create a function with "Function" level authentication.
3. Call the function without keys

Expected: to work

Actual: Doesn't work

This is because request AuthLevel is set to Anonymous [here](https://github.com/Azure/azure-webjobs-sdk-script/blob/dev/src/WebJobs.Script.WebHost/Filters/AuthorizationLevelAttribute.cs#L48), and fails this check [here](https://github.com/Azure/azure-webjobs-sdk-script/blob/dev/src/WebJobs.Script.WebHost/Controllers/FunctionsController.cs#L105).

**Comment by mathewc** [comment]
So what's the problem - you want this to work? :)

**Comment by ahmelsayed** [comment]
![image](https://cloud.githubusercontent.com/assets/645740/25763056/429ceb2a-3196-11e7-84a7-2d3b41e9e2c2.png)
