### ISSUE TITLE
How to set Content-Type="application/json" in a PowerShell Http Trigger?

### ISSUE THREAD

**Issue by dfinke** [Azure/azure-webjobs-sdk-script#1496]
I'm returning JSON to the calling webhook, but it is not converting the JSON to string. I'm guessing I need to set `Content-Type="application/json"`. Is there a way to do this?

Thank you

**Comment by tohling** [comment]
Will this [sample ](http://stackoverflow.com/a/41784877/6465830)work for your use-case?

**Comment by tohling** [comment]
Here are the screenshots of tests on Postman and Invoke-WebRequest using the same sample above.

Using **Postman**:
![powershell](https://cloud.githubusercontent.com/assets/14911331/25878549/5f257c1a-34e0-11e7-8790-b4a428016495.png)

Using **Invoke-WebRequest** command:
![powershell2](https://cloud.githubusercontent.com/assets/14911331/25878524/38b589da-34e0-11e7-9867-8d3cf23ff2dd.png)

**Comment by tohling** [comment]
Closing this issue as customer noted that the issue lies somewhere else. See tweet. https://twitter.com/dfinke/status/862132600789487616
