### ISSUE TITLE
Need validation on function/parameter names

### ISSUE THREAD

**Issue by mathewc** [Azure/azure-webjobs-sdk-script#15]
We need to define the set of allowed characters, length, etc. for function names, since they are used for file names / directories, HTTP routes, etc.

**Comment by christopheranderson** [comment]
@mattchenderson, the portal will be doing some of this too, yes?

**Comment by mathewc** [comment]
Across the board, we want to put whatever naming restrictions etc. in place before RC because doing so later would be breaking.

**Comment by fabiocav** [comment]
The host **does not** create the functions, so validation will need to be put in place in the portal as well as in the Kudu API it consumes.
@ahmelsayed and @alrod , I'll document the naming restrictions and open issues in the appropriate repos to track this.
This also impacts the CLI. Is there anything else I'm missing?

**Comment by christopheranderson** [comment]
## Assumptions:
Names only contain characters allowed in ASCII

## Requirements:
 - A Function Name must only contain alphanumerical characters or '-' or '_'.
 - The parameter name for a given a Function binding must only: 
    1. contain alphanumerical characters
    2. start with a letter (i.e. [a-zA-Z])

**Comment by christopheranderson** [comment]
@fabiocav - were those requirements good enough?

**Comment by fabiocav** [comment]
Yes! This works. 

@ahmelsayed and @alrod, I'll open the issue on the portal and Kudu repos. Should this be opened anywhere else?

**Comment by christopheranderson** [comment]
@soninaren - do we need anything in binding.json for this?

**Comment by soninaren** [comment]
parameter name is already validated through regex
https://github.com/Azure/azure-webjobs-sdk-templates/blob/dev/Bindings/bindings.json#L37-L38

I don't think function name validation should be a part of binding.json or templates repo. I this should purely be a part of portal code, Since binding.json would be split to each binding. Anything common across all templates/functions should go in portal

**Comment by christopheranderson** [comment]
Function names need to start with a number/letter. Just tried a dash and it doesn't work.

**Comment by fabiocav** [comment]
@christopheranderson did we decide, for function names, what the max length should be? 
@mathewc ?

**Comment by christopheranderson** [comment]
I don't have any specific user requirements around the function names. What can the file system/WebJobs host support?

**Comment by davidebbo** [comment]
We've decided to go with the following rules for function names:

1. case insensitive, case-preserving. 
2. between 1 and 128 chars in length. 
3. regex: [A-Za-z][A-Za-z0-9_\-]{0,127}

**Comment by MikeStall** [comment]
For convenience, the C# for the regex above is:
  Regex r = new Regex(@"^[A-Za-z][A-Za-z0-9_\-]{0,127}$");

**Comment by mathewc** [comment]
When we release this, it will be a breaking change of course for people. Functions that are now running will now be in error. they'll have to be recreated.

**Comment by davidebbo** [comment]
Yes, we discussed this. That's why it's important to do this now and not post GA. We'll just explain in the release notes how people can manually fix things up by renaming some folders in Kudu.
