### ISSUE TITLE
Proxy Pass Original Host Header to Backend

### ISSUE THREAD

**Issue by chandlerkent** [Azure/azure-webjobs-sdk-script#1500]
I'm experimenting with using Functions Proxies in front of some legacy applications. Those applications often use the Host header to build URLs and do redirects. Is there a way to pass the original Host header to the backend when proxying the request?

I've tried using the `requestOverrides` feature like:

```
"requestOverrides": {
	"backend.request.headers.host": "{request.headers.host}",
	"backend.request.headers.X-ORIGINAL-HOST": "{request.headers.host}"
}
```

The backend receives the X-ORIGINAL-HOST header correctly, but the host header is not correct.

Here's an example proxy I've set up:

https://chandler-function-proxy.azurewebsites.net/app1/

This proxies to the backend Web App http://chandler-function-proxy-app1.azurewebsites.net/app1. This is just a simple Node.js script that prints out all the headers and the URL. Notice that the X-ORIGINAL-HOST header is set correct, but the host header is:

chandler-function-proxy-app1.azurewebsites.net

instead of:

chandler-function-proxy.azurewebsites.net

<details>
<summary>Full proxies.json for posterity</summary>

```
{
    "$schema": "http://json.schemastore.org/proxies",
    "proxies": {
        "chandler-function-proxy-app1": {
            "matchCondition": {
                "route": "/app1"
            },
            "backendUri": "http://chandler-function-proxy-app1.azurewebsites.net/app1",
			"requestOverrides": {
				"backend.request.headers.host": "{request.headers.host}",
				"backend.request.headers.X-ORIGINAL-HOST": "{request.headers.host}"
			}
        },
        "chandler-function-proxy-app2": {
            "matchCondition": {
                "route": "/app2"
            },
            "backendUri": "http://chandler-function-proxy-app2.azurewebsites.net/app2"
        }
    }
}
```
</details>

**Comment by omkarmore83** [comment]
Currently, we do not support overriding certain headers like _Host_. The behavior is to ignore such overrides. You can pass the original host as a custom header to the backend (they way you did in the example).

**Comment by paulbatum** [comment]
Closing as answered.
