### ISSUE TITLE
Increment "Maximum Request Size" and "Maximum Header Size" on Azure Functions?

### ISSUE THREAD

**Issue by bootsector** [Azure/azure-webjobs-sdk-script#1501]
Hi there!

I'm working with an use case where I need to be able to pass HTTP headers to an HTTP triggered Azure Functions with lengths bigger than 65KB.

How can I increase those limits?

Thanks!

#### Repro steps

1. Create a new Function (NodeJS) called HttpTriggerJS1 with the following index.js and function.json:

index.js
```
module.exports = function (context, req) {
    context.log('JavaScript HTTP trigger function processed a request.');

    if (req.query.name || (req.body && req.body.name)) {
        res = {
            // status: 200, /* Defaults to 200 */
            body: "Hello " + (req.query.name || req.body.name)
        };
    }
    else {
        res = {
            status: 400,
            body: "Please pass a name on the query string or in the request body"
        };
    }
    context.done(null, res);
};
```

function.json
```
{
  "bindings": [
    {
      "authLevel": "anonymous",
      "type": "httpTrigger",
      "direction": "in",
      "name": "req"
    },
    {
      "type": "http",
      "direction": "out",
      "name": "$return"
    }
  ],
  "disabled": false
}
```

2. Make a POST request to that endpoint containing any header with more than 65KB:

```
curl -X POST \
  https://my-functions.azurewebsites.net/api/HttpTriggerJS1 \
  -H 'cache-control: no-cache' \
  -H 'content-type: application/json' \
  -H 'postman-token: 166e5efb-3151-d7cc-d0b8-b9a683ae072e' \
  -H 'x-access-token: <YOUR_BIG_HEADER_CONTENTS_HERE>' \
  -d '{
	name: "Tester"
}'
```

#### Expected behavior

Response code 200 with the following body:

`"Hello Tester"`

#### Actual behavior

```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd">
<HTML>
    <HEAD>
        <TITLE>Bad Request</TITLE>
        <META HTTP-EQUIV="Content-Type" Content="text/html; charset=us-ascii">
    </HEAD>
    <BODY>
        <h2>Bad Request - Request Too Long</h2>
        <hr>
        <p>HTTP Error 400. The size of the request headers is too long.</p>
    </BODY>
</HTML>
```

**Comment by paulbatum** [comment]
@bootsector we recently upped the max request body size. But we haven't seen any requests for longer headers before. Can you tell us more of your scenario? Can you push your data into the request body?

**Comment by bootsector** [comment]
@paulbatum we're passing authentication tokens via HTTP headers. Depending on the user, the number of claims will increase, making the token bigger and easily trespassing Azure Functions limit of 65KB. We really need to pass all the tokens. Moving those to the request body would require a massive code refactoring both in  the backend and frontend that we would really like to avoid.

**Comment by paulbatum** [comment]
@bootsector Have you been able to successfully pass a header of size greater than 64KB to an asp.net application running on IIS (or even better, on App Service)? The research I've done so far indicates that this value is controlled by a registry key (see MaxFieldLength [here](https://support.microsoft.com/en-us/help/820129/http.sys-registry-settings-for-windows)), and the documentation indicates that 64KB is the max. You can set header limits in the request filtering config (see [here](https://www.iis.net/configreference/system.webserver/security/requestfiltering/requestlimits/headerlimits)) but as far as I can tell setting these is only helpful when you want a limit smaller than the value specified in the registry setting.

**Comment by paulbatum** [comment]
I'm closing this as my current research indicates its not possible to go beyond 64KB length headers.
