### ISSUE TITLE
Bad event hubs connection makes entire host unusable

### ISSUE THREAD

**Issue by davidebbo** [Azure/azure-webjobs-sdk-script#151]
Steps:

- Start with empty site
- Create JS http webhook and hit test to verify it's all healthy
- Create new function using EventHubTrigger template
- Click on the + sign to get at the connections, then click Add New Connection
- Create a new connection called `foo`, with value `Endpoint=sb://foo.servicebus.windows.net/;SharedAccessKeyName=mysas;SharedAccessKey=Hello`
- Complete the Function creation
- Go back to your webhook function and try to run it, and it's now busted. You get this alert:

![image](https://cloud.githubusercontent.com/assets/556238/14004955/7d674816-f11b-11e5-9ed7-7c10c14dab48.png)

The host log file looks like this:

```
2016-03-24T00:21:14.818 Reading host configuration file 'D:\home\site\wwwroot\host.json'
2016-03-24T00:21:14.929 Generating 2 job function(s)
2016-03-24T00:21:14.929 Found the following functions:
Host.Functions.EventHubTriggerNodeJS1
Host.Functions.GenericWebhookNodeJS1
2016-03-24T00:21:14.945 A ScriptHost error occurred
2016-03-24T00:21:14.945 No such host is known
```

**Comment by mathewc** [comment]
I'll take a look at this one this morning.

**Comment by mathewc** [comment]
Closing this because there is nothing that can be done in this repo to improve this futher. PR https://github.com/Azure/azure-webjobs-sdk-script/pull/167 did however improve the error message you'll see. It will now be "Microsoft.ServiceBus: No such host is known."

**Comment by davidebbo** [comment]
Much better error now!
