### ISSUE TITLE
CDS assembly load issue when referencing NuGet package

### ISSUE THREAD

**Issue by fabiocav** [Azure/azure-webjobs-sdk-script#1512]
When following the steps outlined the the [CDS documentation](https://docs.microsoft.com/en-us/common-data-service/entity-reference/cds-sdk-azure-functions-get-started), customers sporadically run into issues loading CDS assemblies.

**Comment by paulbatum** [comment]
@fabiocav can you look at this as part of the assembly loading work we have planned for august?
