### ISSUE TITLE
Function execution duration is not correct in logs

### ISSUE THREAD

**Issue by OlegShevnin** [Azure/azure-webjobs-sdk-script#1513]
Have a simple function that lasts for 10 seconds (just as an example). When several instances of the function were run in parallel and completed, log files contain incorrect information about execution duration in "Function completed (Success, Id=.... , Duration=...)" message. The duration can be much less then 10 seconds.

Seems like the root cause is **FunctionInvokerBase._stopwatch** class member is not thread-safe and is reset by each function invocation in this line https://github.com/Azure/azure-webjobs-sdk-script/blob/322ecdd36f6fa69c833489343054d77340dd4949/src/WebJobs.Script/Description/FunctionInvokerBase.cs#L129

**Comment by fabiocav** [comment]
That is indeed a bug! :) We were just chatting about that today. We'll have this addressed ASAP.
