### ISSUE TITLE
Support F# 4.1?

### ISSUE THREAD

**Issue by johlrich** [Azure/azure-webjobs-sdk-script#1523]
Thoughts on bumping FSharp.Core to latest nuget? Looks like things are set to 4.0 and with no binding redirect access, there's no way to address this ourselves unless I've missed something.

Changing binding redirect to 4.4.1.0 for the CLI caused the precompiled function app to work locally at least.

**Comment by paulbatum** [comment]
@fabiocav have you looked at this at all? Any thoughts on whether this is safe?

**Comment by johlrich** [comment]
Another package that would need to be bumped is Newtonsoft.Json, 10.0.1 fixed working with FSharp's list type in 4.1: https://github.com/JamesNK/Newtonsoft.Json/issues/1180

**Comment by fabiocav** [comment]
Moving Fsharp.Core to latest should be pretty safe. We can validate and perhaps @sylvanc can comment as well. 

For JSON.NET, since it is a major version bump, it has the potential to be impactful, but, aside from scenarios where you're binding to JSON.NET types, you'd still be able to reference higher versions and bind to those assemblies though.

**Comment by sylvanc** [comment]
Bumping `FSharp.Core` should be good. @dsyme may jump in, but I don't think there are any problems.

**Comment by ed-ilyin** [comment]
why it's postponed again?
Since there is no solution for binding redirects, it's harder and harder to keep project to work in Azure Functions

**Comment by fabiocav** [comment]
@ed-ilyin not postponed, just updated to reflect the sprint we're currently on. This unfortunately wasn't addressed in the previous sprint.

**Comment by ed-ilyin** [comment]
Please, reopen as change was reverted

**Comment by fabiocav** [comment]
This was closed  as it was a 1.0 (current runtime) item and it won't be done there. 2.0 is already on the later F# Core version (and will be on the latest available at the time of release) and we have this issue open (working through a couple of minor issues with the team) for the compiler service https://github.com/Azure/azure-webjobs-sdk-script/issues/1931
