### ISSUE TITLE
event hub checkpointing

### ISSUE THREAD

**Issue by mamaso** [Azure/azure-webjobs-sdk-script#1529]
Plumb the knob from webjobs through to functions

**Comment by paulbatum** [comment]
@MikeStall thinks we can solve this easily through the new API that was introduced with byob

**Comment by paulbatum** [comment]
also host.json schema has to be updated

**Comment by MikeStall** [comment]
The extension should call ExtensionContextConfig.ApplyConfig() 
https://github.com/Azure/azure-webjobs-sdk/blob/4bc1a89c0c5d3d3f29c54747cf40455ec3399d97/src/Microsoft.Azure.WebJobs.Host/Config/ExtensionConfigContextExtensions.cs#L127
