### ISSUE TITLE
Log File Purging

### ISSUE THREAD

**Issue by davidebbo** [Azure/azure-webjobs-sdk-script#153]
In the case of https://github.com/projectkudu/WebJobsPortal/issues/164, the site has 88MB of files in D:\home\LogFiles\Application\Functions\Host, mostly due to host restarting non-stop. We need a strategy to keep the log size under control, and purge old logs.

**Comment by mathewc** [comment]
Yes, we can put a simple purge strategy in place. Also an exponential backoff for restart attempts might also be good.

This one is also related to https://github.com/Azure/azure-webjobs-sdk-script/issues/100 - when we get to that one, my thought was to only have file logging enabled in "debug mode".

**Comment by mathewc** [comment]
In FileTraceWriter, we already have startup time logic that scans for all log files to determine the last one to log to. There we can implement a strategy - e.g. only retain the last N. We should also consider performance of this, since this is done on startup for each function logger.

**Comment by davidebbo** [comment]
I think this can wait till post-beta. Instead, let's focus on reducing occurrences of situations that cause wild logging.
