### ISSUE TITLE
Possibility to disable some metrics in Application Insights

### ISSUE THREAD

**Issue by kamil-mrzyglod** [Azure/azure-webjobs-sdk-script#1539]
Hi,

is there any possibility(or maybe plans?) to actually limit what metric is being logged with AI integration? The problem is that my functions are generating huge amount of traces, which is somehow cool, but it doesn't help much when something is wrong. 

When I look at data point volume, traces from functions are like 75% of total. I have only two triggers - TimerTrigger and QueueTrigger - so I'm afraid that when I start adding new functions, I'll be flooded by the amount of traces which will be recorded and I hit my quota.

Best regards,
Kamil

**Comment by fabiocav** [comment]
Yes, there is some information on how to do that [here](https://github.com/Azure/Azure-Functions/wiki/App-Insights-(Preview)). If there are other categories you'd like to see, please let us know as that is the kind of feedback we're looking for during the preview.

/cc @brettsam

**Comment by brettsam** [comment]
You can definitely turn on/off logging at a bunch of different levels. For example, if you want to only log errors (so you can investigate issues) but you still want aggregated metrics (success rates, avg duration, etc) you can use a setup like:

```
"logger": {
    "categoryFilter": {
      "defaultLevel": "Error",
      "categoryLevels": {
        "Host.Aggregator": "Information"
      }
    }
```

That should shrink your App Insights usage significantly.

Note that you'll currently lose most of the Live Stream in App Insights when you do this, but I'm looking to improve that in the near future.

**Comment by kamil-mrzyglod** [comment]
@brettsam Thank you, I'll check this today.

@fabiocav For know main problem for me was the amount of data being logged, once I overcome this problem, I'll be able to make some assumptions "what data is missing in my case".

**Comment by fabiocav** [comment]
Sounds great. FYI, the categories are documented on the Wiki page I've shared.

**Comment by paulbatum** [comment]
Closing as resolved.
