### ISSUE TITLE
Disable SA1200 and SA1008 from code analysis

### ISSUE THREAD

**Issue by mamaso** [Azure/azure-webjobs-sdk-script#1540]
SA1200 blocks aliasing because it treats aliasing is a 'using' directive and requires it to be moved outside of the namespace

`using SimplerName = ICollection<IEnumerable<IWhatever>>;`

SA1008 mandates certain spacing around parenthesis, so there's an error on the open paren of the tuple

`someEnumerable.Select(item => (item.prop1, item.prop2))`

@fabiocav any thoughts?

**Comment by fabiocav** [comment]
I know I've used both above... I guess I probably added a supression. I recall running into a parenthesis requirement that was a bit painful. For some of the new syntax not properly recognized by the analyzers, it would be worth opening a bug against them.

**Comment by mamaso** [comment]
SA1200 workaround is to fully qualify:

```cs
using WorkerPool = System.Collections.Generic.ICollection
    <Microsoft.Azure.WebJobs.Script.Dispatch.ILanguageWorkerChannel>;
namespace Blah {}
```

Stylecop analyzers not fully compatible with C#7 yet (https://github.com/DotNetAnalyzers/StyleCopAnalyzers/issues/2268), so 1008 and tuples are not a huge issue

`
