### ISSUE TITLE
Any workarounds for adding multiple triggers?

### ISSUE THREAD

**Issue by raghav710** [Azure/azure-webjobs-sdk-script#1544]
I experimented with sending some data to event hub on a blob trigger and it works great.
But now I would like to send data - say the blob name that was added - by waiting for triggers from multiple blob storage containers. I tried modifying the function.json to add multiple blob triggers but it failed as expected since multiple triggers aren't supported.

I would like to know whether there any workarounds for the task I'd like to accomplish.

**Comment by paulbatum** [comment]
If you want to have your same function code run for blobs in either account A or account B, the easiest thing to do this is to create multiple function.json files for each function but have them share the same code by pointing to the same script file. There's more info [here](https://github.com/Azure/azure-webjobs-sdk-script/wiki/Precompiled-functions).

**Comment by raghav710** [comment]
@paulbatum closed this since I got an answer. Please feel free to reopen it if needed for tracking or other purposes
