### ISSUE TITLE
Windows Azure Pack functions support

### ISSUE THREAD

**Issue by tbprince** [Azure/azure-webjobs-sdk-script#1546]
Hello,

we are testing functions support on Windows Azure Pack (latest update, update rollup 12) which is using 

Kudu Build - 58.51026.2494.0 (b6f512652d)
Azure App Service  - 59.0.10699.22 (rd_wskatal_stable_v2.170303-1249) 

Kudu detects our function (we tested both JS, BAT and PS1 ones) as it returns info about it in REST API endpoint (/api/functions) but when invoking public API, we always get a 404. Not matter what, we are unable to invoke the function while in SCM everything seems to be working fine.

Any hint? Maybe functions aren't supported in WAP ?

Thanks,
**Guglielmo**

**Comment by christopheranderson** [comment]
Azure Functions aren't supported in Windows Azure Pack. Our suggestion is to use WebJobs.
