### ISSUE TITLE
Dot syntax for binding data should be consistent between functions and proxies

### ISSUE THREAD

**Issue by mattchenderson** [Azure/azure-webjobs-sdk-script#1555]
The dot syntax in the [latest release](https://github.com/Azure/azure-webjobs-sdk-script/releases/tag/v1.0.11002) includes HttpTrigger support, but it is inconsistent with the existing proxies behavior.

The proxies syntax is documented [here](https://docs.microsoft.com/en-us/azure/azure-functions/functions-proxies#a-nameusing-variablesause-variables).

Let's make the experience of using both of these consistent.

**Comment by mathewc** [comment]
The syntax chosen for Functions binding expressions was made consistent with the existing platform it is built on - WebJobs SDK. That is the most important thing. However we should investigate whether we can improve the story here for proxies. I.e. make proxies more consistent with Functions.

**Comment by paulbatum** [comment]
This issue was moved to Azure/Azure-Functions#332
