### ISSUE TITLE
Azure Functions on Consumption plan not scaling correctly for functions with higher memory & CPU use

### ISSUE THREAD

**Issue by donquijotedelamancha** [Azure/azure-webjobs-sdk-script#1557]
This follows the issue explained here:
https://stackoverflow.com/questions/44180141/azure-functions-concurrency-timeout

As a summary:

- I have two functions each of them with a memory footprint of 400 to 700 MB. They run correctly in the consumption plan app when they run at different times. Each of them take CPU utilization between 70%-100%.

- I can also run both functions at the same time on separate function apps in consumption mode.

- If I run both at the same time on the same function app in consumption mode, then they never finish.

Possible reason:

I don't know how scaling in the consumption plan works but a possible reason why this is happening is that the memory & CPU footprint of a function is not taken into account in the scaling process. e.g. If a function is known to have a memory footprint higher than what is available at the running instance then add another instance and dispatch the function to the new instance.

**Comment by paulbatum** [comment]
Our best recommendation right now is to stick with the setup you have of moving the functions into different function apps. I recognize this is not ideal - but we would need https://github.com/Azure/azure-webjobs-sdk-script/issues/511 which isn't implemented yet.
