### ISSUE TITLE
VS2017 Azure Function: ServiceBusTopic Trigger loading Keys issue

### ISSUE THREAD

**Issue by ApiO** [Azure/azure-webjobs-sdk-script#1558]
Hi,

I have convert an existing project to the new project template with the "Visual Studio 2017 Tools for Azure Functions".
In my Function App project I have functions using TimeTrigger and ServiceBusTopic trigger.

After publishing, I have the following errors:

![image](https://cloud.githubusercontent.com/assets/4429857/26626575/ed4f6ad2-45f7-11e7-943d-a0454ad1c67d.png)

If I go to the "Manage" section of any function, "Function Keys" and "Host Keys" region doesn't load and the error popups came.

If I disable the ServiceBusTopic trigger functions and refresh the Function App, the others functions works and the "Manage" section of the working functions loads correctly.

Portal/Runtime issue ? I let you decide.

**Comment by fabiocav** [comment]
Investigating this. Session ID text: bc01ba5cb3994a97971534ca5c321631

**Comment by fabiocav** [comment]
Based on information from the logs, it looks like we had invalid/missing credentials for Service Bus and were getting a 401 when trying to authenticate. Can you ensure credentials are set and are accurate and retry?

@mathewc /@soninaren / @mamaso , I was under the impression one of you had done the work to ensure issues like this would be logged but not cause an initialization issue.

**Comment by mamaso** [comment]
https://github.com/Azure/azure-webjobs-sdk/pull/1100

Blocked on a few things and closed it out, though it would catch this and associate with the calling function. There's a less controversial path that doesn't use reflection to clone event handlers which could dump the errors in host logs.

**Comment by ApiO** [comment]
> Can you ensure credentials are set and are accurate and retry?

Previous credential where good.
 
After changing it to a full rights credential, I found out that generated function.json file hold a mistake:

From C# code:

```
[FunctionName("ServiceBusTopicTriggerCSharp")]
public static void Run(
	[ServiceBusTrigger(
		topicName:"{topic_name}", 
		subscriptionName:"{sub_name}", 
		access:AccessRights.Listen, 
		Connection = "{policy_name_to_valid_listen_credential}")]
	string mySbMsg, TraceWriter log)
{
	...
}
```
Generated function.json :

```
{
  "bindings": [
    {
      "type": "serviceBusTrigger",
      "connection": "{previous_connection_name}",
      "topicName": "{topic_name}",
      "subscriptionName": "{sub_name}",
      "access": "listen", <------ there
      "direction": "in",
      "name": "mySbMsg"
    }
  ] ,
  ...
}
```

Expected generation :

```
{
  "bindings": [
    {
      ...
      "accessRights": "Listen", <------ there
      ...
    }
  ],
  ...
}
```

If I manually change this setup via the portal everything work. 
For information, when editing and saving the Manage form, from the portal, the parameter is well formatted.

**Comment by soninaren** [comment]
This looks like a VS tooling issue. The generated function.json has incorrect case for accessRights property. Since runtime is not able to parse the accessRights property it is defaulting to manage which seems to cause the issue. 

Will talk to @ahmelsayed  and will fix the generation logic.

**Comment by mamaso** [comment]
Also will change the parsing to not be case sensitive in webjobs

**Comment by fabiocav** [comment]
@soninaren / @ahmelsayed is this being addressed?

Naren, I'll have this assigned to you for update.

**Comment by ahmelsayed** [comment]
@soninaren  I don't remember what this was about. Let me know if you need anything from me.

**Comment by soninaren** [comment]
This was fixed in the later version of function.json generator. I will test this and contact the VS guys to update the VSIX.

**Comment by soninaren** [comment]
This has been deployed with latest visual studio update
