### ISSUE TITLE
Give 'AzureWebJobsDashboard' property more descriptive name

### ISSUE THREAD

**Issue by kamil-mrzyglod** [Azure/azure-webjobs-sdk-script#1559]
Hi,

currently in _local.settings.json_ we have a property called _AzureWebJobsDashboard_. From my understanding(and what people connected to Azure Functions say) it allows you to disable logging data to the Monitor tab(and probably breaks the dashboard of a Function App if not provided?). 

Is it possible to somehow fix its name so it better describes its purpose? In the current shape it seems to make lots of confusion.

Best regards,
Kamil

**Comment by paulbatum** [comment]
I agree the name is not ideal but we're going to leave it as is. Over time this setting will be less important as app insights becomes the default monitoring experience.
