### ISSUE TITLE
Improve error message when using a TimeSpan string in Timer trigger

### ISSUE THREAD

**Issue by lindydonna** [Azure/azure-webjobs-sdk-script#1561]
On a Consumption plan, only CRON expressions are supported for Timer trigger. Customers may end up going down this path if they use the new VS tooling, because the doccomments in the `TimerTrigger` attribute say that TimeSpan is supported.

Suggest improving the error message to make it clear that the TimeSpan expression can only be used on an App Service Plan.

Current error:
> Function ($TimerTriggerCSharp1) Error: '00:00:01' is not a valid CRON expression.

Suggested error:

> Function ($TimerTriggerCSharp1) Error: '00:00:01' is not a valid CRON expression. Schedule expressions in the form HH:MM:SS can only be used in an App Service Plan.

**Comment by mathewc** [comment]
This error message comes from the Functions runtime here: https://github.com/Azure/azure-webjobs-sdk-script/blob/3b3e8cb8312060a475d4eb0418fafb4d80f12326/src/WebJobs.Script/Binding/CoreExtensionsScriptBindingProvider.cs#L82

Recommend we TryParse on the value and only if it is a TimeSpan do we show the TimeSpan specific error message suggested.

**Comment by soninaren** [comment]
https://github.com/Azure/azure-webjobs-sdk-script/pull/1750

**Comment by mamaso** [comment]
What is the reason that we don't allow timespan strings in functions - scale controller? @tohling how difficult would it be to enable this functionality - I think it would be nice to not have this discrepancy with webjobs

**Comment by BowserKingKoopa** [comment]
I just got bit by this today. The timespan expression works locally (run from Visual Studio). Why does the timespan expression work locally? Aren't I running the same Azure Functions runtime Azure is?
