### ISSUE TITLE
TableRequestOptions for Table Storage bindings

### ISSUE THREAD

**Issue by kamil-mrzyglod** [Azure/azure-webjobs-sdk-script#1562]
Hi,

are there plans for implementing TableRequestOptions for Table Storage? I'm aware of the fact, that there's a workaround(not providing Table Storage binding and handling the client and configuration myself), but I don't know whether I'm reinventing the wheel. 

Best regards,
Kamil

**Comment by paulbatum** [comment]
We have no plans to expose this. Your workaround is our recommended approach.
