### ISSUE TITLE
Referencing a header value in proxy

### ISSUE THREAD

**Issue by kamil-mrzyglod** [Azure/azure-webjobs-sdk-script#1567]
Hi,

We're currently using Azure Functions Proxy in following scenario:

1. Client sends a request with a following header: **Authorization: TOKEN <function-key>**
2. Proxy should rewrite a request from Authorization header to x-functions-key: <function-key>

Is this possible with the current implementation of Proxy? I haven't found any way to do so and I don't know how it'd possible to reference <function-key> to use it in the rewrite. 

Any help is much appreciated.

Best regards,
Kamil

**Comment by paulbatum** [comment]
@mattchenderson Is this possible?

**Comment by mattchenderson** [comment]
Please see [this documentation](https://docs.microsoft.com/en-us/azure/azure-functions/functions-proxies#a-nameusing-variablesause-variables) for how to leverage variables from within a proxy.

For your particular case, I'd expect something like:
```
"requestOverrides" : {
    "backend.request.headers.x-functions-key" : "{request.headers.Authorization}",
    "backend.request.headers.Authorization" : ""
}
```

**Comment by kamil-mrzyglod** [comment]
@mattchenderson Thank you for the response! Unfortunately I think I have a bit more complicated scenario.

I have following **Authorization** header: `TOKEN <this_is_a_function_key>`
I would like to rewrite to `x-function-keys: <this_is_a_function_key>` - without `TOKEN` 

I would like to reference it in the same manner as referencing a value from e.g. application settings, let's say:
`
"requestHeader": {
   "Authorization": "TOKEN <function_key>"
},
"requestOverrides" : {
    "backend.request.headers.x-functions-key" : "{function_key}",
    "backend.request.headers.Authorization" : ""
}`

something like that but I'm afraid it's not supported now(and would it be supported in the near future?)

**Comment by paulbatum** [comment]
This issue was moved to Azure/Azure-Functions#331
