### ISSUE TITLE
Fix miscategorized integration tests

### ISSUE THREAD

**Issue by fabiocav** [Azure/azure-webjobs-sdk-script#1581]
The secret repository tests `Microsoft.Azure.WebJobs.Script.Tests.Security.SecretsRepositoryTests.*` are currently miscategorized and causing the UT suite to fail. Those tests need to move to the integration test suite as they will not pass without the required build environment configuration.

**Comment by paulbatum** [comment]
@krolson Could you take a look at this?

**Comment by krolson** [comment]
Fixed in this check-in : https://github.com/Azure/azure-webjobs-sdk-script/commit/b4e71d429e40670ee1f7eb65ab3bfcb573059ae0
