### ISSUE TITLE
Route is not taking "*" or "Asterisk" as valid character for Function app http trigger.

### ISSUE THREAD

**Issue by amitxagarwal** [Azure/azure-webjobs-sdk-script#1582]
When i am trying to use "*" or "Asterisk" as a part of route for Function app http trigger it's giving http 400 bad request error.

Request URL:https://xxx.azurewebsites.net/api/products/amit/abc/*
Request Method:GET
Status Code:400 Bad Request
Remote Address:xxx.xxx.xxx.xxx:443
Referrer Policy:no-referrer-when-downgrade

In the Eventlog.xml i can see the below event.

<Data>An unhandled exception has occurred.</Data>

<Data>HttpException</Data>
<Data>
A potentially dangerous Request.Path value was detected from the client (*). at System.Web.HttpRequest.ValidateInputIfRequiredByConfig() at System.Web.HttpApplication.PipelineStepManager.ValidateHelper(HttpContext context)
</Data>

<Data>
at System.Web.HttpRequest.ValidateInputIfRequiredByConfig() at System.Web.HttpApplication.PipelineStepManager.ValidateHelper(HttpContext context)
</Data>

We need this kind of feature for function apps http triggers.

**Comment by mattchenderson** [comment]
If you're trying to set up a wildcard path in your configuration, this is the same as [ASP.NET Web API](https://docs.microsoft.com/en-us/aspnet/web-api/overview/web-api-routing-and-actions/attribute-routing-in-web-api-2). When configuring the route in your function, you would have something like "foo/{*parameterName}" and then you can call it by replacing "{*parameterName}" with the actual path you care about.

Your error message actually looks like a client error, so I'm wondering if you are trying to call the function with the asterisk character itself? If so, please note the asterisk is a [reserved character](https://tools.ietf.org/html/rfc3986#section-2.2) for URL encoding. You'll want to replace it with "%2A" when used as part of a path.

**Comment by amitxagarwal** [comment]
i want to pass the sql query as a part of the path as one of the parameters. So this SQL query will have *, <, > and all the special characters which are used in a SQL query. 

When i pass * as %2A as a part of path how will i define the route in this scenario.

**Comment by mattchenderson** [comment]
I'm not sure I understand the question. The route can be specified with variables, including wildcard variables as covered in the documentation. The value of those parameters can be anything you want, although you will need to encode special characters on the client side. Then you can decode the parameters from your function code before use.

I would generally advise against including a query as part of the path. It may be better to provide this on the query string. Even then, accepting an arbitrary SQL as an input comes with a number of security risks, so please make sure you've accounted for this in your security modeling.
