### ISSUE TITLE
EventHub connection string verification for namespace level policy

### ISSUE THREAD

**Issue by alrod** [Azure/azure-webjobs-sdk-script#1588]
Please provide a succinct description of the issue.

#### Repro steps

Provide the steps required to reproduce the problem

1. Create a new EventHub namespace
2. Set namespace policy connetion

![image](https://user-images.githubusercontent.com/2578359/26990483-8f8338be-4d0b-11e7-9262-dcf86fe38498.png)

3. Verify connection is the same as on policy page

![image](https://user-images.githubusercontent.com/2578359/26990687-6048ea66-4d0c-11e7-9a87-9709a009690b.png)

#### Expected behavior

No error message

#### Actual behavior

Runtime returns error:
![image](https://user-images.githubusercontent.com/2578359/26988828-a9be20b4-4d05-11e7-9b4d-c322c53e8f42.png)

**Comment by paulbatum** [comment]
@alrod it looks like the UI here lets you select a policy without an event hub selected... is that right? Seems like a bug if so..

**Comment by alrod** [comment]
@paulbatum  I had an issue create by you
https://github.com/Azure/azure-functions-ux/issues/1437

**Comment by paulbatum** [comment]
This is resolved.
