### ISSUE TITLE
Memory consumption when running on single core VM's

### ISSUE THREAD

**Issue by 1N50MN14** [Azure/azure-webjobs-sdk-script#1596]
According to https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-node

`When you create a function app that uses the App Service plan, we recommend that you select a single-core plan rather than a plan with multiple cores. Today, Functions runs JavaScript functions more efficiently on single-core VMs, and using larger VMs does not produce the expected performance improvements.`

So I went ahead and created a empty function app with a service plan running a single P1 instance; looking at the metrics my empty idling function app consumes about 60% of the memory on average at any given time. I currently have my scale out configuration set at 70% average CPU usage, I could probably take that up to 75-80%, still that leaves very little room for actual workload specially when considering service plans have a limited number of instances that can be consumed.

I'm assuming node's `cluster` module (https://nodejs.org/api/cluster.html) is not applicable here, is there anything else that can be accomplished within AF functions to utilize multi-core vm's?  any other tips would be appreciated.

Thanks.

**Comment by paulbatum** [comment]
The current design of functions involves using edge.js to run node.js functions. With this design there is no way to use multiple cores. Of course you could use larger VMs just to get more memory. Also if you run multiple function apps on the same plan then you will get more effective core utilization.

We have plans to move to a new model that does not use edge.js, this is part of our port to .NET core. See here for more info: https://github.com/Azure/azure-webjobs-sdk-script/issues/1319. This would address the multicore issue.
