### ISSUE TITLE
Function App script to create functions programmatically?

### ISSUE THREAD

**Issue by mikhailshilkov** [Azure/azure-webjobs-sdk-script#1597]
With VS2017 tooling, the functions are defined as static methods with attributes around parameters, e.g.

``` cs
[FunctionName("BlobTriggerCSharp")]        
public static void Run([BlobTrigger("samples-in/{name}")]Stream inBlob, 
    [Blob("samples-out/{name}")]CloudBlockBlob outBlob)
{
// ...
}
```

That is good for many scenarios, but I'm also searching for a more flexible approach to create function definitions _at runtime_.

That is I want to write a script which would go and create a number of Azure Functions, with complete binding, configuration and body based on some arbitrary logic. Let's say I have a custom interface in my application

``` cs
public interface IConvert<TI, TO>
{
    TO Convert(TI item);
}
```

and then, for each implementation of this interface in my application, I want to create an Azure Function which would listen to an Event Hub called `nameof(TI)`, will pass every event to `Convert` function and then output it to another Event Hub called `nameof(TO)`.

I could make it as sophisticated as I want, up to creating a whole DSL around my problem domain, and then interpret this DSL into a pipeline of Functions.

How would I approach such task? The only way I can think of is to use a combination of `csx` and `function.json` files generation. Or, alternatively, static class generation with appropriate attributes.

Do you have any thoughts around creating something like a `Bootstrap` static class/script, which would return a collection of Function definition objects, and then use those to setup Functions?

It can be that I'm over-complicating things and there is a straightforward way to script Function App creation in C# in such flexible way. If so, please point me into right direction.

**Comment by paulbatum** [comment]
You'd be better off having one function app that modifies another. You might be able to get some ideas of how to do this from our E2E testing infrastructure here: https://github.com/Azure/azure-webjobs-sdk-script/tree/dev/test/WebJobs.Script.Tests.E2E
