### ISSUE TITLE
POCO Json property attributes not honored on insert Newtonsoft.Json 10.0.2

### ISSUE THREAD

**Issue by nhwilly** [Azure/azure-webjobs-sdk-script#1599]
Maybe everyone else knows this except me.  Seems like it would have been mentioned before now.

My simple POCO classes have attributes such as `[JsonProperty("id")]` to make sure that case is correct in CosmosDb.

After updating to Newtonsoft.Json 10.0.2 from 9.0.1 these are being ignored during this call:

`await _client.CreateDocumentAsync(UriFactory.CreateDocumentCollectionUri(_database.Id, _collectionId), entity, ro).ConfigureAwait(false);`

All POCO properties starting with uppercase are written into the collection with uppercase property names, despite having attributes specifying otherwise.

Workaround is to drop back to 9.0.1 of Newtonsoft.Json.  Works great then.

Other facts:  I am using a repository class to make my Cosmos calls and not using bindings.  I am creating my own generic client, etc. so I can use strongly typed documents.

HTH.

**Comment by paulbatum** [comment]
This is expected behavior when using versions of JSON.NET that are newer than the current built in version. In the future we hope that support for binding redirects (tracked under https://github.com/Azure/azure-webjobs-sdk-script/issues/992) will help resolve this.

**Comment by nhwilly** [comment]
That makes perfect sense.  It just had never happened to me.  Thanks for responding...

**Comment by rprajeshpatel** [comment]
Is there a way to make it work with newtonsoft 12.0.1 version???

**Comment by kevin-secrist** [comment]
@rprajeshpatel Another potential workaround is to use [`DataMemberAttribute`](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.serialization.datamemberattribute?view=netframework-4.7.2) instead of `JsonPropertyAttribute`

**Comment by paulbatum** [comment]
@rprajeshpatel This is an old issue, please file a new issue (and make sure you fill out the details that our issue template asks for)
