### ISSUE TITLE
Finish Default INameResolver implementation

### ISSUE THREAD

**Issue by mathewc** [Azure/azure-webjobs-sdk-script#16]
The ScriptHost registers an INameResolver which supports useful things for bindings like %rand-guid% %rand-int%. We should also modify it to also pull from app settings, to support scenarios where users want to bind based on setting values. Also round out the list of auto resolved values.

**Comment by mathewc** [comment]
App settings / Env support has now been added. Just need to finish up the list of auto resolve values.

**Comment by fabiocav** [comment]
@mathewc, do you have details on what needs to be done to complete this? Happy to take a look at this item if you have more info.

**Comment by paulbatum** [comment]
Punting to post beta

**Comment by christopheranderson** [comment]
We should wrap up whatever work needs to be done here and document the various things available, as we currently haven't done a great job with that. Probably a "should-have"?

**Comment by mathewc** [comment]
Closing this. I've moved `rand-guid` into SDK core. Any other such "built in" binding parameters we should build into core SDK as well.
