### ISSUE TITLE
context.res is unfamiliar - this should look like a http/connect/express response object

### ISSUE THREAD

**Issue by danderson00** [Azure/azure-webjobs-sdk-script#160]
Most node developers will be most familiar with the http/connect/express style of response object, e.g. res.status(200).send({ }), rather than an unfamiliar, proprietary API.

**Comment by mathewc** [comment]
Yeah, this has been a TODO. Basically we have the minimum in place required, but our whole .NET/Node interop layer will be improving. There should be some existing issues for that.

**Comment by christopheranderson** [comment]
RC Justification: Given that this is likely a breaking change and is related to the consistency work, we should consider this.

**Comment by mamaso** [comment]
@christopheranderson @danderson00 @mathewc 

My proposal:

Bring in express as a dependency and provide a `express.response` object in node.  Replace `response.end` with a function that maps the `express.response` object to our existing `res` object & executes `context.done`.

A few benefits:
- we don't need to worry about keeping our shim up to date with the express api
- can simply point at the express docs
- don't break existing functions which attach `{ status: ..., body: ....}`

If we go this route, however, is there a point to route back to our http trigger?  Not sure what extra steps occur in the pipeline & if they are necessary, we could just send the response back from node code.

**Comment by mathewc** [comment]
Note that this issue applies to both req and res. Whatever improvements we make should factor in both.

Yes, that is an option. Thus far I've tried to minimize such inbuilt dependencies, but this would really be no different than our built in .NET package dependencies in the case of C# + HttpRequestMessage.

The question is whether the Express response object would expose APIs that won't work correctly in Functions or will cause issues. Also, we need to investigate the details of what the mapping code in your "end" replacement would look like.

**Comment by lindydonna** [comment]
@mamaso Have you done more work on this?  If not, we're considering moving to backlog.

**Comment by mathewc** [comment]
I'd like to get this work done along with all the other http improvements we've made.

**Comment by yvele** [comment]
@mathewc I've made a small connect adaptor for Azure Function and its working like a charm. I'm now able to use express and all middlewares that every node.js developer knows.

I'm using it like that :

```js
const app = express();
app.use(whatever);

const handler = new ConnectHandler();
handler.addRequestListener(app);

export default function handle(context) {
  handler.handleAzureRequest(context);
}
```

I should maybe consider making an open source project with that.. 😄

**Comment by mathewc** [comment]
@yvele Interesting.

I'm not seeing where your function logic is in the above example. It looks like you just call directly into `handler.handleAzureRequest`? Also, using this model, you'd be instantiating a new express app per function? Not sure if there are any negative implications to that. Express apps and middleware chains are generally created once on application startup.

**Comment by mamaso** [comment]
@lindydonna Haven't done any work, vaca + wanted more feedback / proposals.

@yvele interested to see this adapter of yours.  Also @mathewc I think that this will function as one express app thanks to require caching.

**Comment by yvele** [comment]
@mamaso @mathewc I've made an open source project from my Azure Function to Express adapter https://github.com/yvele/azure-function-express It may have some limitations (multipart upload)s but work with a basic usage (routing, basic middlewares, etc.)
