### ISSUE TITLE
 Flush the App Insights logs before restarting the host due to assembly changes

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-webjobs-sdk-script#1606]
Issue reported [here](https://social.msdn.microsoft.com/Forums/en-US/e6e0090f-e1a8-4552-963b-731ef796a425/flushing-app-insights-before-restarting-the-host?forum=AzureFunctions)

Logs are missing if host restarts due to assembly changes.

Needs investigation.

**Comment by brettsam** [comment]
The disposal of the LoggerFactory (which, in turn, flushes the client) was disabled due to another issue (#1537). That bug has been fixed, so I'll re-enable the disposal.
