### ISSUE TITLE
Use pdbgit/gitlink to get source stepping without the need for symbol servers

### ISSUE THREAD

**Issue by paulbatum** [Azure/azure-webjobs-sdk-script#1607]
Visual Studio supports stepping through source pulled from github if you inject the right data into your pdbs. The pdbgit/gitlink project makes this extremely straightforward.

https://github.com/AArnott/PdbGit

We should do the work to enable this experience for functions and webjobs (we might need another version of this issue in the webjobs sdk repo too).

**Comment by paulbatum** [comment]
cc @fabiocav

**Comment by paulbatum** [comment]
@fabiocav Something like this is now working for v2 right? Can we close this?

**Comment by fabiocav** [comment]
This was done for the WebJobs SDK. It's a quick thing, so I'll get this setup here as well.

**Comment by fabiocav** [comment]
Resolved by #2149
