### ISSUE TITLE
timer trigger didn't fire

### ISSUE THREAD

**Issue by jamesdixon** [Azure/azure-webjobs-sdk-script#1608]
A job that uses the timer trigger did not fire according to schedule. It ran after I restarted my app service instance.

#### Repro steps

I don't have any specific repro steps at this point. This job had been running like clockwork for weeks and suddenly, it decided not to run this morning.

#### Expected behavior

I'd expect the job to run according to schedule.

#### Actual behavior

The job is set to run at 9am UTC every Tuesday morning. I woke up at 3:20am MDT (should have run at 3am MDT) to find that the job had not run.

#### Known workarounds

I considered kicking the job off manually, but was concerned that it would run again and cause issues. Instead, I restarted my App Service instance and the job finally kicked off. Interestingly enough, it went into a "Never Finished" status 3 times before finally running to completion.

#### Related information 

* The runtime is installed as part of my app service instance (will be moving to the functions consumption plan soon).
* Node.js

#### Questions
* What typically causes this to happen? I'm not seeing anything in the very limited logs written.
* Is there a way to see what's scheduled for timer triggers?

**Comment by paulbatum** [comment]
Hi @jamesdixon, sorry for the delayed response.

One thing to check for - do you have any other function apps connected to the same storage account? We've seen cases where a second function app (or another slot if using the slots feature) was connected to the same storage account, and its host.json contained an explicitly set ID. In this case, the second app competes with the main function app to acquire the lock to run timers.

Has your function been running smoothly for the last week or so or have you seen the issue recur?

If you can share your function name with me directly or [indirectly](https://github.com/Azure/azure-webjobs-sdk-script/wiki/Sharing-Your-Function-App-name-privately) and the timestamp of the missed run(s) I can investigate further.

**Comment by paulbatum** [comment]
Closing inactive issue
