### ISSUE TITLE
Adding a newer Azure Storage Nuget breaks app

### ISSUE THREAD

**Issue by lindydonna** [Azure/azure-webjobs-sdk-script#1616]
From @brettsam:

1. Create a fairly ordinary QueueTrigger that uses a `CloudQueueMessage` as a parameter:

       [FunctionName("QueueTriggerCSharp")]
       public static void Run([QueueTrigger("mover-items", Connection = "AzureWebJobsStorage")] CloudQueueMessage myQueueItem, TraceWriter log)
       {
          log.Info($"C# Queue trigger function processed: {myQueueItem}");
       }

2. Update to the latest WindowsAzure.Storage nuget package
3. Run

You'll end up with unexpected errors. It looks like because the versions don't match, we don't realize that `CloudQueueMessage` is a 'known' type. So we try to deserialize the contents of the message into it, which doesn't work.

It happens in regular precompiled functions as well. I'm guessing it has to do with assembly redirects -- it can't match the types b/c they're from different assembly versions so it assumes `CloudQueueMessage` is a POCO rather than a 'known' type.

**Comment by lindydonna** [comment]
@brettsam Do you see the same issue if you use function.json with a precompiled class library?  See https://aka.ms/precompiled-functions for info on how to set up.

If so, the issue belongs in the Script repo, I think.

**Comment by lindydonna** [comment]
_From @brettsam on June 21, 2017 21:58_

Yes, it happens in precompiled functions as well. I'm guessing it has to do with assembly redirects -- it can't match the types b/c they're from different assembly versions so it assumes `CloudQueueMessage` is a POCO rather than a 'known' type.

**Comment by lindydonna** [comment]
@brettsam I've moved to script repo.

**Comment by fabiocav** [comment]
This is indeed related to unification/redirects. We don't automatically redirect higher versions  down today.

**Comment by paulbatum** [comment]
By design until #992 is supported
