### ISSUE TITLE
Add a Copy link to the Output portion of the Test panel and an option for rendering newlines as newlines

### ISSUE THREAD

**Issue by KirkMunro** [Azure/azure-webjobs-sdk-script#1620]
When testing a function using the Test panel, it would be helpful if there was a Copy link to copy the output to your clipboard. It would also be helpful if there was a way to view raw output (string) vs formatted output (where newlines actually result in new lines in the Output window rather than one long string that runs on forever).

#### Repro steps

1. Run a test of an Azure function that returns some output using the Test panel.
2. Try to copy your output if your output is anything longer than the width of the Output window. It's much harder than it should be.
3. Notice how newlines in the output are shown in string format rather than as actual new lines.

#### Expected behavior

Copying the output should be trivial, and there should be an option to render the string output so that newlines are actual new lines without function testers having to use other tools to convert the captured output into a readable format.

#### Actual behavior

The output is shown as a single string, with all information on one line, and no easy way to copy that text.

#### Known workarounds

None.

#### Related information 

None.

**Comment by paulbatum** [comment]
Good idea but does not meet the bar.

**Comment by paulbatum** [comment]
I should mention that our portal is open source too. the code is here: https://github.com/Azure/azure-functions-ux send us a PR?
