### ISSUE TITLE
Feature request: Request for better timer debug -- at least on local scripthost

### ISSUE THREAD

**Issue by ericleigh007** [Azure/azure-webjobs-sdk-script#1622]
There is what I would say is a annoyance level 2 on a scale of 1-5 that when I am debugging a timer function in Visual Studio with the Azure Function Core tools / local scripthost, using the "class library" / new function types,, I have to keep messing with the CRON setting before running it to either
- Keep it from firing when I don't want it to fire
- Keep it from firing twice and screwing up my first test that is in progress
- Make sure it fires

I wonder if you guys could consider adding some syntax in the source file, or host.json setting that says to fire the timer ONCE immediately, and then don't fire it again.  This would allow people testing local functions to reliably test something that counts on timers.

This is analogous to the website which "runs" whenever you press "run", and doesn't wait for the timer time.

What do you guys think?

-thanks
-e

**Comment by paulbatum** [comment]
Have you tried configuring the timer function to be disabled and then using the functions core tools `func run` command to run the function?

**Comment by ericleigh007** [comment]
I should have explained that I'm looking for something that is a quick iteration for F5 debugging in Visual Studio.  I don't see under that constraint that using the `func run` command would apply.

I updated my original post to make that more clear.

If you think that the `func run` command still applies to that scenario, please let me know how it would set that up.  Perhaps having that set up would make any other changes low priority, or no priority ;)

**Comment by paulbatum** [comment]
I see. While you're debugging, you could change the schedule to be very infrequent and then take advantage of the RunOnStartup property:

![image](https://user-images.githubusercontent.com/10663/27560509-422017ce-5a79-11e7-8f4e-4efac1053f19.png)

**Comment by ericleigh007** [comment]
okay, sounds like we already have what I was asking for.  I was unaware of that property.  Please excuse the interruption.

**Comment by ericleigh007** [comment]
Note that I used RunOnStartup locally, which worked well.  When that setting made it to Azure on publish, it appeared that the timer fired more often than expected.   The CRON spec is "0 0 3 * * *", which would say to me 0300 UTC, but the timer fired every 10 minutes or so.

Either RunOnStartup was the problem, or the Timer fired each time a queue function ran out of time.  I'm happy to start another issue on that if it is expected that is the cause instead.

**Comment by paulbatum** [comment]
Don't publish with RunOnStartup set to true. Just set it while you're debugging.

**Comment by ericleigh007** [comment]
Yeah, that's what I found out!  
NP
-thanks
-e
