### ISSUE TITLE
messsage typo

### ISSUE THREAD

**Issue by ahmelsayed** [Azure/azure-webjobs-sdk-script#1624]
https://github.com/Azure/azure-webjobs-sdk-script/blob/3b3e8cb8312060a475d4eb0418fafb4d80f12326/src/WebJobs.Script.WebHost/Models/ApiErrorModel.cs#L36

It's technically a breaking change to fix it.

**Comment by 1N50MN14** [comment]
+1

I was just about to open an issue on this one.
