### ISSUE TITLE
Logging errors only in Application Insights

### ISSUE THREAD

**Issue by kamil-mrzyglod** [Azure/azure-webjobs-sdk-script#1625]
I'd like to log errors only for my functions, unfortunately it seems it's not possible.

#### Repro steps

1. Create Function App and a function with Application Insights integrated

2. Use following configuration for `host.json` file:

```
{
  "logger": {
    "categoryFilter": {
      "defaultLevel": "Error",
      "categoryLevels": {
        "Host.Results": "Error",
        "Function": "Error",
        "Host.Aggregator": "Error"
      }
    },
    "aggregator": {
      "batchSize": 1000,
      "flushTimeout": "00:00:30"
    }
  },
  "applicationInsights": {
    "sampling": {
      "isEnabled": true,
      "maxTelemetryItemsPerSecond": 5
    }
  }
}
```

#### Expected behavior

Only errors are logged.

#### Actual behavior

Still traces are visible in the portal
![ai](https://user-images.githubusercontent.com/11725731/27469371-802fb6c8-57ef-11e7-963b-f75c1ebdca08.PNG)

Is it intended?

Best regards,
Kamil

**Comment by fabiocav** [comment]
This is not intended and is an issue with the current release. A [fix](https://github.com/Azure/azure-webjobs-sdk-script/pull/1573) has been put in place and that will roll out in the next deployment that is about to begin.

**Comment by kamil-mrzyglod** [comment]
@fabiocav Cool, can't wait!
