### ISSUE TITLE
Function level logging needs to be done by a single instance

### ISSUE THREAD

**Issue by fabiocav** [Azure/azure-webjobs-sdk-script#164]
When performing function level logging outside of the execution scope (e.g. reload, recompile messages) the host needs to acquire a lock or something similar so that it's only done by a single instance. 
Currently, when the function site scales to multiple instances, log output will look confusing to users since things like recompiling and reloading messages will be written multiple times (once for each instance). 
We'll need to do the same thing to prevent execution of tasks that should only run once (things like package restore, creating assembly caches once we have that, etc.)

**Comment by mathewc** [comment]
Thoughts on this one Fabio? This would be a good one to get to soon.

**Comment by christopheranderson** [comment]
We need to handle cases like intermittent errors affecting one machine.

**Comment by christopheranderson** [comment]
Might be able to argue we don't need this for rc, but I'm inclined to say the current experience is actually a bug given how confusing it can be.

**Comment by mathewc** [comment]
yes, we definitely need to fix this for RC.

**Comment by fabiocav** [comment]
Resolved by #581
