### ISSUE TITLE
WildCard Route Does Not Match Items with an Extension

### ISSUE THREAD

**Issue by securityvoid** [Azure/azure-webjobs-sdk-script#1647]
I've got a route with a wildcard at the end. When running on the local azure-core-tools it successfully handles the route both for items with and without an extension. When I deploy the same code to Azure Functions, the route only matches those items without an extension and not with an extension.

The following is my function.json:
```
{
 "disabled": false,
 "bindings": [
  {
   "name": "req",
   "type": "httpTrigger",
   "direction": "in",
   "authLevel": "anonymous",
   "methods": [
    "GET"
   ],
   "route": "{type:regex(^((dists)|(pool)))}/{*file}"
  },
  {
   "name": "res",
   "type": "http",
   "direction": "out"
  }
 ],
 "scriptFile": "index.js"
}
```

Locally this will match and handle:
/dists/main/Release
and
/dists/main/Release.gpg

When deployed to Azure Functions it handles:
/dists/main/Release

But never calls the function with:
/dists/main/Release.gpg

#### Repro steps

1. Setup an Azure Function with the following functions.json:
```
{
 "disabled": false,
 "bindings": [
  {
   "name": "req",
   "type": "httpTrigger",
   "direction": "in",
   "authLevel": "anonymous",
   "methods": [
    "GET"
   ],
   "route": "{type:regex(^((dists)|(pool)))}/{*file}"
  },
  {
   "name": "res",
   "type": "http",
   "direction": "out"
  }
 ],
 "scriptFile": "index.js"
}
```
2. Setup a simple index.js to return a response when its hit. 

e.g. index.js:
module.exports = function(context){

context.res =  {
        status: 200,
        headers: {
            "Content-Type" : "application/json"
        },
        body : { "Message" : "I hear you!"}
    };
    context.done();

}

3. Make a GET request to your function app to:
/dists/main/Release

NOTE: You get your sample response showing the Function App was called.

4. Make a GET request to your function:
/dists/main/Release.gpg

NOTE: You get the standard Function App 404 because your function is not called.

#### Expected behavior
A call to a route which ends in a wildcard will handle everything with or without an extension on that wildcard path.

#### Actual behavior
Only routes without a file extension are handled by the route.

#### Known workarounds
I can probably match the extension separately? (Haven't tried yet, but I'll work on that next)

#### Related information 
Locally where both files are handled by the route and work as expected:
Azure Functions Core Tools (1.0.0-beta.100)
Function Runtime Version: 1.0.11015.0

Programming Language: NodeJs

**Comment by securityvoid** [comment]
Is there anyway to simply setup multiple routes to the same function? That would be the easiest to workaround this, but the DOCS don't seem to suggest that's possible.

**Comment by securityvoid** [comment]
Nope it doesn't work to have two functions :-(

```
Function ($app-http-file-download-get2) Error: Microsoft.Azure.WebJobs.Host: Error indexing method 'Functions.app-http-file-download-get2'. System.Web.Http: A path segment that contains more than one section, such as a literal section or a parameter, cannot contain a catch-all parameter.
 Parameter name: routeTemplate.
```

This is extremely frustrating. I've been working on this project for weeks and this is the last bit I need working.

**Comment by fabiocav** [comment]
For the behavior you're looking for, please look at Azure Functions Proxies. That will address the issue with extensions as well as being able to map multiple routes to a single function.

**Comment by securityvoid** [comment]
I'm not sure how this is supposed to be done. It appears that a wildcard is the only method that will match across /'s, so if I have an unknown number of /'s, I have to end my route with a wildcard.

After a wildcard, you can't put any other matches, so I can't put an extension at the end.

Furthermore, I can't seem to come up with any pattern that will even match when an extension is involved.

e.g.
  "route": "{type:regex(^((dists)|(pool)))}/{file:regex(^[\\w]+$)}.{ext}"

Does not match:
GET /dists/main.abc

Even though it should.

For that matter:
  "route": "{type:regex(^((dists)|(pool)))}/main/Release.gpg

Won't even match:
/dists/main/Release.gpg

**Comment by securityvoid** [comment]
@fabiocav Okay, so reading about proxies it sounds like they essentially handle the wildcard properly?

However, since Azure Functions does not, I'll have to map it so it sends it to the function not as a URL but as a parameter or something?

e.g. /dists/main/Release.gpg would hit the proxy

And be sent to my function as:
/dists?file=main/Release.gpg

Am I understanding correctly what your suggesting? I can definitely do this to get this working, but it seems kind of silly. There should be a way to access a URL that has an extension on it.

**Comment by securityvoid** [comment]
BTW, the only reason why I need multiple routes to the function is because it doesn't handle the extensions. Otherwise I'd only need one.

**Comment by securityvoid** [comment]
Man, you guys are killing me. This URL pattern that works for functions, does not populate "type" for Proxies:

{
  "$schema": "http://json.schemastore.org/proxies",
  "proxies": {
    "RetrieveFiles": {
      "matchCondition": {
        "route": "{type:regex(^((dists)|(pool)))}/{*file}",
        "methods": [
          "GET"
        ]
      },
      "backendUri": "https://<MYAPP>.azurewebsites.net/api/filehandler?type={type}&file={file}"
    }
  }
}

File gets passed over, but the query parameter type is blank. Maybe I just did something stupid because I've had 4hrs of sleep, but it looks right to me.

**Comment by securityvoid** [comment]
@fabiocav Thank-you. I got something working. I had to take all validation out of the type to get it to show up, but now that it shows up I can proceed.

I still think the fact it doesn't work with an extension is a definite bug, but I at least have a work around getting my code working.

**Comment by paulbatum** [comment]
The issue of routes with an extension not being matched without a trailing slash is tracked here:
https://github.com/Azure/azure-webjobs-sdk-script/issues/969
