### ISSUE TITLE
If you run scripthost locally no functions get triggered

### ISSUE THREAD

**Issue by tdykstra** [Azure/azure-webjobs-sdk-script#165]
If you run the script host project locally it finds functions but never triggers them.
Running webhost works fine.

**Comment by mathewc** [comment]
Steps to do this are listed in the wiki https://github.com/Azure/azure-webjobs-sdk-script/wiki.

**Comment by mathewc** [comment]
Can you provide more details? It all works fine for me locally. Have you followed all the setup steps here: https://github.com/Azure/azure-webjobs-sdk-script/wiki?

**Comment by tdykstra** [comment]
I set it up with only the storage connection strings and limited the functions in host.json to C# timer and queue trigger.  Fabio tried the same thing on his machine and got the same result.

**Comment by mathewc** [comment]
Works on my box :) Feel free to stop by and show me.

**Comment by tdykstra** [comment]
I'll stop by tomorrow

**Comment by paulbatum** [comment]
Closing as no repro
