### ISSUE TITLE
Returning 404 from a PowerShell function

### ISSUE THREAD

**Issue by KirkMunro** [Azure/azure-webjobs-sdk-script#1650]
I originally came in here to indicate that I need to be able to return a 404 from an HTTP PowerShell function, because I have a single function whose route accepts an action as a parameter (e.g. thing/{thingId}/{action}), and since there are only two valid actions at this time, I want the function to return 404 for anything other than the two actions that are supported for that function. What I need is just like what is available for HTTP C# functions, and what Joel identified is required for PowerShell here: https://github.com/Azure/azure-webjobs-sdk-script/issues/337#issuecomment-250954074.

Is there any way to return a 404 from an HTTP PowerShell function today?

**Comment by tohling** [comment]
Could you try this?

```
# POST method: $req
$requestBody = Get-Content $req -Raw | ConvertFrom-Json
$name = $requestBody.name

# GET method: each querystring parameter is its own variable
if ($req_query_name) 
{
    $name = $req_query_name 
}

$message = "{ `"headers`":{`"content-type`":`"text/plain`"}, `"body`":`"Hello $name`", `"statusCode`": 404}"
[System.IO.File]::WriteAllText($res,$message)
```

Otherwise, you may also write a wrapper as shown [here](https://blog.tyang.org/2016/10/13/making-powershell-based-azure-functions-to-produce-html-outputs/).

**Comment by KirkMunro** [comment]
Thanks @tohling, that got me on the right path. The syntax you provided is close, but it had one issue: the message body has to be present but blank in order to simulate a 404.

Changing the second last line to this makes the PowerShell function return a 404:
```PowerShell
$message = "{ `"headers`":{`"content-type`":`"text/plain`"}, `"body`":`"`", `"statusCode`": 404}"
```
