### ISSUE TITLE
WindowsAzure.Storage package version update to 8.1.4?

### ISSUE THREAD

**Issue by justinyoo** [Azure/azure-webjobs-sdk-script#1654]
Hi, Team.

Is there a plan to update the NuGet package, [WindowsAzure.Storage](https://www.nuget.org/packages/WindowsAzure.Storage/), update to 8.1.4? Its current version used in Azure Function is 7.2.1. The main reasons that I'm asking this are:

* WindowsAzure.Storage 8.1.4 has been providing a lot of unit-testing capabilities like mocking supports, since [8.0.0](https://github.com/Azure/azure-storage-net/releases).
* Azure Functions doesn't support binding redirection discussed at #992 
* [Microsoft.Azure.WebJobs](https://www.nuget.org/packages/Microsoft.Azure.WebJobs), used in Azure Functions is 2.1.0-beta1-*,  defines its minimum requirements of WindowsAzure.Storage 7.2.1. I interpret that we can use higher version of that library.

It would be great if you guys let us know when it appears on your roadmap.

Cheers,

**Comment by paulbatum** [comment]
@fabiocav is working on getting Functions running on .NET core. He has updated to a more recent version of storage as part of this work. For example, I can see a packagereference pointing to 8.1.3 [here](https://github.com/Azure/azure-webjobs-sdk/blob/0d325efa0b000f2040d1bd64043575ad8984371a/src/Microsoft.Azure.WebJobs.Storage/WebJobs.Storage.csproj#L21). When this work ships, it will ship as a new major version of functions that users will be able to opt into. This is the path forward for moving off of storage sdk 7.x.

**Comment by justinyoo** [comment]
@paulbatum Thanks for the heads up! That would be the one I've been looking forward to seeing.

@fabiocav Is there a chance to update the particular NuGet package only before .NET Core support comes into true?

**Comment by paulbatum** [comment]
@justinyoo unfortunately no, it would be a breaking change to upgrade to a new major version of the storage sdk, so it has to go into the next major version of the functions runtime (i.e. the .net core version we just discussed).
