### ISSUE TITLE
Cannot debug Azure Function from Cloud Explorer

### ISSUE THREAD

**Issue by bc3tech** [Azure/azure-webjobs-sdk-script#1672]
Filing issue per direction [here](https://social.msdn.microsoft.com/Forums/expression/en-US/ead896df-75d0-4a4f-abec-6ff5892e9b9c/remote-debugging-azure-functions-with-vs2017-preview-3-and-latest-azure-function-tools?forum=AzureFunctions&prof=required) and despite instructions shown [here](https://blogs.msdn.microsoft.com/webdev/2016/12/01/visual-studio-tools-for-azure-functions/).

1. open azure portal
1. create new azure function (c#)
1. Open Visual Studio 2017 Preview 15.3.0
1. Ensure Azure Function Tools v0.2 (latest) installed
1. Open Cloud Explorer & find Function created in portal
1. Right click the function.
1. Observe no 'Attach debugger' option is available:
![image](https://user-images.githubusercontent.com/1967433/28138713-9d18b016-6706-11e7-8b6e-8706dfcf6311.png)

**Comment by tohling** [comment]
@bc3tech , this is a currently a known issue that is being actively investigated by the VS team that owns Cloud Explorer.  

To unblock yourself immediately, we suggest that you try to an older process that may involve a few extra steps but should work.  Here are the steps:

1.  From the Portal, under the **Overview** tab, 
     a. Download the publish credentials for your Function App.  Open the downloaded file and in its content, look for the credentials,
               i. userName
               ii. userPWD

      b.  Copy the URL to your Function App

2.	From the Portal, under **Application settings**, 
        a.  Turn on Remote Debugging
        b.  Select Remote Visual Studio Version as 2017

3.	From VS 2017 in the list of menu items, select **Debug->Attach To Process**

4.	In the Connection Target: text area, copy and paste the URL obtained from 1b followed by **:4022** as that is the port for the remote debugger for VS2017, e.g.  `myFunctionSite.azurewebsites.net:4022`

5.	You will be prompted for your credentials.  Type in the username and password that you obtained from **1ai** and **1aii**.  **NOTE:** For username it is preceded by **.\**  For instance if your username is **$myusername**, type .**\$myusername**

6.	You should now see a list of processes that you can attach to.  Select the one that has the process name **w3wp.exe** and click on the **Attach** button.

**Comment by lindydonna** [comment]
This issue was moved to Azure/Azure-Functions#393
