### ISSUE TITLE
Server Error in '/ms-ext-routing' Application

### ISSUE THREAD

**Issue by nathan011** [Azure/azure-webjobs-sdk-script#1676]
#### Investigative information
Invoke any one of the functions in the application (http binding with permission set to anonymous), and eventually a 500.0 ms-ext-routing error will occur. 

See attached detailed diagnostic info obtained from downloading the diagnostic dump from kudu.

- Timestamp (most recent occurrence): 7/13/2017, 2:29:32 PM
- Function App name: etpwebapp
- Function name(s) (as appropriate): 
    * Home
    * Future (most recent occurrence: https://etpwebapp.azurewebsites.net/future/24390)
    * Futures
    * Portfolio
    * Portfolios
    * Strategy
    * StrategyTrade
    * Strategies
- Invocation ID (most recent occurrence): 9b545770-dc2e-4da6-a376-4833d83c0d14
- US-east

#### Repro steps
Invoke any one of the functions in the application (permission is anonymous), and eventually a 500.0 ms-ext-routing error will occur. It may happen right away or may take a few minutes.

#### Expected behavior
No such error should occur.

#### Actual behavior
A http 500.0 error will occur sporadically when accessing any one of the functions. 

#### Known workarounds
Simply rerunning an identical request immediately after the error has occurred will be successful the next attempt.

#### Related information 
* Language: C#
* http binding (anon access is allowed) with a single proxy defined to route the site root
proxies.json:
{
  "$schema": "http://json.schemastore.org/proxies",
  "proxies": {
    "site_root": {
      "matchCondition": {
        "methods": [ "GET" ],
        "route": "/"
      },
      "backendUri": "https://etpwebapp.azurewebsites.net/home"
    }
  }
}

My own theory is that an unhandled exception in the host background processing is causing the web process (w3wp.exe) to terminate--see the eventlog.xml for examples of such errors--and ultimately leading to these errors.

**Comment by fabiocav** [comment]
Thank you for the detailed information!

Do you see this issue if the proxies feature is disabled?

**Comment by nathan011** [comment]
I've only used it with the proxy on, so I'm not sure, but I'll disable it
for now and see if the error still occurs.

**Comment by nathan011** [comment]
With the proxy disabled, the issue appears to be resolved.  Is there a
workaround or a fix planned for this, since I'd like to have the site root
routed to my 'home' function?--the proxy currently was the only option for
that functionality. Thanks.

**Comment by parkingboss** [comment]
I'm seeing the same error at what appears to be random intervals with about 2 dozen proxies.

**Comment by fabiocav** [comment]
@omkarmore83 @mattchenderson known issue? any workarounds?

@nathan011 Some investigation may be required here.

**Comment by mattchenderson** [comment]
@omkarmore83 has been looking at some outbound connection exhaustion problems, and that could be it if these sites are under a certain degree of load. Are you seeing this only on production?

**Comment by parkingboss** [comment]
@mattchenderson We definitely saw it in production - load of about 0.5 RPS.

**Comment by nathan011** [comment]
In production, but very light load--only a single user.

On Fri, Jul 14, 2017 at 8:48 PM, Matthew Henderson <notifications@github.com

**Comment by omkarmore83** [comment]
I will look into this. I don't this this is related to outbound connection problems.

I am seeing this in a few other function apps which have proxies enabled aswell.

<Data>InvalidOperationException</Data>
<Data>An asynchronous module or handler completed while an asynchronous operation was still pending.
		</Data>

**Comment by fabiocav** [comment]
@omkarmore83 more evidence with additional information here as well: https://stackoverflow.com/questions/45178931/server-error-if-passing-some-special-character-in-url-parameters/45179053

**Comment by omkarmore83** [comment]
@nathan011 @parkingboss 
Did you see this for requests that have special chars like (& , * , : , >) in the URL parameters failing?

**Comment by parkingboss** [comment]
@omkarmore83 We don't typically (or likely ever) have requests with those characters in the route/path...our failing requests happened without those.

**Comment by nathan011** [comment]
No. There are no routes that accept parameters with special characters in
my function app.

**Comment by omkarmore83** [comment]
Looks like the issue in the stackoverflow is unrelated with this one.  @parkingboss, @nathan011 are you able to repro this issue frequently? I can see this happening in some race condition, but would need to add a little more debug information to pin-point the exact root cause.

**Comment by nathan011** [comment]
I've re-enabled the proxy. It can be reproduced within a few minutes
usually. Just let me know when you're ready.

**Comment by omkarmore83** [comment]
Thanks @nathan011, I am working on a fix for the issue. Will update the thread once its out.

**Comment by nathan011** [comment]
Great news!--thanks!

**Comment by omkarmore83** [comment]
@nathan011 @parkingboss The fix is now live. I can see that the number of errors in all proxies has reduced significantly. please verify. Note that you may need to restart the function App for the fix to take effect (enabling of proxies does constitute as a restart)

**Comment by nathan011** [comment]
I've been unable to recreate the issue, so it looks like this one is
resolved. Nice job! And thank you!

**Comment by parkingboss** [comment]
@omkarmore83 I'm about to re-deploy an update to test this out, but sounds good so far! :)

Just curious, any background info on the underlying issue that you can give us?

**Comment by omkarmore83** [comment]
There was an race condition that could occur because of the usage of a void async method in the code to copy the stream after the backend was called. The code is not available on GitHub so cant share more details.
