### ISSUE TITLE
Need "latestruntime" API that includes latest in 2.0 version

### ISSUE THREAD

**Issue by lindydonna** [Azure/azure-webjobs-sdk-script#1685]
We have the API https://functions.azure.com/api/latestruntime which is used by the portal and az CLI to determine the latest version of the Functions runtime.

When we roll out 2.0-beta, we'd like to add a dropdown so that customers can opt-in to the 2.0 beta, right from the Function App create blade. I suggest we do this work in the **next sprint**, so we can get the portal updates in for **Ignite**.

We probably need to create a new API and deprecate this one, depending on how the current one used. I'd expect the following schema:

```json
{  "display version": "latest value"}
```

For example:

```json
{
   "1.0": "~1",
   "2.0 beta": "~2.0-beta"
}
```

CC @btardif

**Comment by paulbatum** [comment]
This issue was moved to Azure/azure-functions-ux#1595
