### ISSUE TITLE
DocumentDb whith Json.net 10.0.3 throws

### ISSUE THREAD

**Issue by juchom** [Azure/azure-webjobs-sdk-script#1689]
Using VS2017 15.3 preview 4, Create a simple Azure Function project & add a simple HttpTrigger Function.

Add DocumentDB package & Update Json.net to latest version.

Run the function and call it, it will throw this:
FunctionApp1: Method not found: 'Void Microsoft.Azure.Documents.Client.DocumentClient..ctor(System.Uri, System.String, Microsoft.Azure.Documents.Client.ConnectionPolicy, System.Nullable`1<Microsoft.Azure.Documents.ConsistencyLevel>, Newtonsoft.Json.JsonSerializerSettings)'.

Now if you set Json.net to version 6.0.8 it works fine.

Also in a console app DocumentDB with Json.net 10.0.3 is working fine.

**Comment by paulbatum** [comment]
This is by design. For functions 1.x the most recent version of newtonsoft.json you can use is 9.0.1. We hope to address this long term through [binding redirect support](https://github.com/Azure/azure-webjobs-sdk-script/issues/992).
