### ISSUE TITLE
BlobTrigger Batch binding fails to make available name pattern parameter as an env var

### ISSUE THREAD

**Issue by darbha-ram** [Azure/azure-webjobs-sdk-script#1693]
BlobTrigger Batch binding that specifies a blob name pattern to trigger on (e.g. "mycontainer/{somename}.xml") fails to make the name parameter available to the batch function as an environment variable.

In other words, if the BlobTrigger executed for mycontainer/abcd.xml, then the env var should be set like so:
somename=abcd

#### Investigative information

Please provide the following:

- Timestamp:
- Function App name: dasrsedarinput1
- Function name(s) (as appropriate): BlobTriggerBatch1
- Invocation ID:
- Region: East US

#### Repro steps
Here is the JSON of the Integration bindings for the function BlobTriggerBatch1 in Azure Function named "dasrsedarinput1":
 
{
  "bindings": [
    {
      "type": "queue",
      "name": "outputQueueItem",
      "queueName": "outqueue",
      "connection": "dasrsedar2017_STORAGE",
      "direction": "out"
    },
    {
      "type": "blobTrigger",
      "name": "inputBlob",
      "path": "input/{inputxmlname}.xml",
      "connection": "dasrsedar2017_STORAGE",
      "direction": "in"
    },
    {
      "type": "blob",
      "name": "outputBlob",
      "path": "processed/{rand-guid}.doc.txt",
      "connection": "dasrsedar2017_STORAGE",
      "direction": "out"
    }
  ],
  "disabled": false
}
1. Trigger the blobTrigger-batch by copying a file that fits the name pattern input/{inputxmlname}.xml, into the container 'input'.

2. The batch function (run.bat) will execute.  Run the command "set" inside run.bat, which will show all environment variables.  Output of the command will show that there is no variable called 'inputxmlname', though there are variables called "outputBlob" and "inputBlob".

#### Expected behavior

A listing of env vars, when the BlobTriggerBatch1 function executes, should include the var 'inputxmlname' set to the value of the file that triggered the function.  E.g. if the file was "input/abcd.xml", the var should be set like so:

inputxmlname=abcd

#### Actual behavior

There is no environment variable called "inputxmlname".

#### Known workarounds

I have not found a workaround, so there is AFAIK no way to retrieve in code the name of the file that triggered the function.

#### Related information 

<details>
<summary>Batch file Source</summary>

@echo off
echo inputxmlname %inputxmlname% > out.txt
echo inputBlob %inputBlob% >> out.txt
set >> out.txt

</details>
-->

**Comment by christopheranderson** [comment]
You need to use "%%" around environment variables, not "{}". See the docs: https://docs.microsoft.com/en-us/azure/azure-functions/functions-triggers-bindings#resolving-app-settings

You should try `"path": "input/%inputxmlname%.xml",`

**Comment by darbha-ram** [comment]
It seems you misunderstood the problem.

"inputxmlname" is not an environment variable.  Your suggestion to use "%%" for the name pattern is incorrect (it will not give the desired wildcard behavior).  It fails as expected:
        Error:
        Function ($BlobTriggerBatch1) Error: Microsoft.Azure.WebJobs.Host: Error indexing method 'Functions.BlobTriggerBatch1'. Microsoft.Azure.WebJobs.Host: '%inputxmlname%' does not resolve to a value. 
        Session Id: 8b11afe23b984f0fb269503fc745f484
        Timestamp: 2017-07-25T13:07:11.399Z

See https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-storage-blob#pattern -- it is correct to use "{}" in the path pattern.  The pattern "input/{inputxmlname}.xml" correctly triggers  function for *.xml files.  No problem there.

The problem is -- when the Batch function is triggered, there seems to be no way in the code to access what the "inputxmlname" part of triggering filename was.  (If it had been a C# or JS function, "inputxmlname" would be accessible as a param.)

For *Batch* triggers, how to access "inputxmlname" in the batch code?  I would expect an env var of that name to be set by the runtime, but see attached capture env.txt -- there is no such var.
[env.txt](https://github.com/Azure/azure-webjobs-sdk-script/files/1173508/env.txt)

Thanks.
