### ISSUE TITLE
Allow the maximum number of functions in a host to be specified/configured

### ISSUE THREAD

**Issue by ruslany** [Azure/azure-webjobs-sdk-script#170]
If we allow an unlimited number of functions per function app it could blow up in unexpected way as we have not tested this.

**Comment by davidebbo** [comment]
Do you have a limit in mind? Maybe 100?

Presumably, it could be a switch on `ScriptHostConfiguration` that we would set in WebHost.

**Comment by fabiocav** [comment]
What do we want the behavior to be when we hit this limit? 
- Would we only load up to that limit?
- How do we order/prioritize functions?
- How will the information be surfaced to users when we have functions that are not loaded?

**Comment by davidebbo** [comment]
I think we should keep this simple for now: only load up to that limit, and if easy write message to host log that limit had been readon. Use whatever ordering. In practice, I don't think any *reasonable* scenario will reach such limit (which I doubt even works well in our UI), so few users will hit this unless they're going out of their way to push limits.

**Comment by fabiocav** [comment]
Sounds good.

**Comment by fabiocav** [comment]
Closing this issue as this will no longer be implemented as part of the host.
