### ISSUE TITLE
Support the 'this' parameter for azure functions

### ISSUE THREAD

**Issue by mamaso** [Azure/azure-webjobs-sdk-script#1702]
When calling the function we don't set the 'this' parameter, see (https://github.com/Azure/azure-webjobs-sdk-script/blob/dev/src/WebJobs.Script/azurefunctions/functions.js#L93)

This should be changed to pass the user module.

https://www.reddit.com/r/AZURE/comments/6n3ldo/im_noticing_that_azure_functions_seem_to_not/

**Comment by christopheranderson** [comment]
Can we say for certain this isn't a breaking change? Is there any pattern this could break? We're close to 2.0, should we save the concern?

**Comment by christopheranderson** [comment]
@paulbatum votes this is breaking. Let's just move this to 2.0 only.

**Comment by mamaso** [comment]
Fair enough :)

**Comment by mamaso** [comment]
Moved to worker repo
