### ISSUE TITLE
Add configurationSource and generatedBy to function.json schema

### ISSUE THREAD

**Issue by lindydonna** [Azure/azure-webjobs-sdk-script#1704]
We're adding two new properties to function.json. These should be added to the JSON schema and uploaded to schemastore.

```json
"configurationSource": "attributes", // possible values are "attributes" or "config"
"generatedBy": "Microsoft.NET.Sdk.Functions-1.0.0-alpha6" // any string
```

See https://github.com/Azure/azure-functions-vs-build-sdk/issues/74

**Comment by christopheranderson** [comment]
Need to also send PR against schema store. Reassigning to Matt since it is a simple fix.

**Comment by mamaso** [comment]
I'm not sure that adding these to the function.json schema is the correct choice. To me, I see function.json as documentation for customer usability, not for our internal implementation details.

These properties are only relevant to precompiled functions users from VS tooling - in which case there is no/minimal user interaction with function.json.

On the other hand, these properties should not be used by .csx or any other language that manually edits function.json in the portal, so I would like these not to appear in autocomplete / potentially mislead them - 'attributes' is invalid for all but precompiled.

**Comment by lindydonna** [comment]
@mamaso Agree about generatedBy, but configurationSource is an interface to the user. If you build your own function.json, you'd want it.

Let's just make sure that the comment is clear that it shouldn't be used for CSX. The good news is that it will fail fast if they set the config source to "attributes"
