### ISSUE TITLE
[C#] Poor error message when binding name doesn't match function definition

### ISSUE THREAD

**Issue by lindydonna** [Azure/azure-webjobs-sdk-script#172]
When there’s an error that the binding name in function.json doesn’t match the parameter name in the C# file, you get an error like this:

`Error indexing method 'Functions.ResizeQueueTrigger'. Microsoft.Azure.WebJobs.Host: Cannot bind parameter 'blobInfo' to type BlobInfo. Make sure the parameter Type is supported by the binding. If you're using binding extensions (e.g. ServiceBus, Timers, etc.) make sure you've called the registration method for the extension(s) in your startup code (e.g. config.UseServiceBus(), config.UseTimers(), etc.).`

The first time I did this, I thought the problem was my using statement or that I had a custom class, and it took me some time to realize I just had a name mismatch.

Is it possible to show a different error message when the name is wrong?  If not, let's change the text to say that either the parameter name is wrong, or the type is not supported by the binding.

**Comment by paulbatum** [comment]
@fabiocav Is there a cheap check we can do here to make the message better?

**Comment by mathewc** [comment]
The above errror comes from the SDK core, which means that we've ignored the mismatch and generated a function anyways. Likely we can catch the mismatch early and emit an error from the script runtime, rather than generating the incorrect function.

**Comment by fabiocav** [comment]
There might be. We currently perform validation on method arguments, so we output simple error messages when bindings are defined and arguments are missing, so I want to make sure I clearly understand the problem; @lindydonna, did you have a binding or binding parameter named "blobInfo"? Or was that just the function method argument name and it differed from what you had in your function.json?

Can you share your function.json and at least your function's method signature?

**Comment by lindydonna** [comment]
I don't have the incorrect function.json anymore, but the correct one and the Run method are below. @fabiocav, I had a difference between the binding's "name" parameter and the parameter name in the method signature.

I have the correct versions below. You can repro by changing the parameter name in either function.json or the method declaration.

function.json:

```

    "bindings": [
        {
            "queueName": "resize-fun-request",
            "type": "queueTrigger",
            "name": "blobInfo",
            "direction": "in"
        },
        {
            "path": "{ContainerPrefix}-lg/{FileName}",
            "type": "blob",
            "name": "input",
            "direction": "in"
        },
        {
            "path": "{ContainerPrefix}-sm/{FileName}",
            "type": "blob",
            "name": "blobOutputSmall",
            "direction": "out"
        },
        {
            "path": "{ContainerPrefix}-md/{FileName}",
            "type": "blob",
            "name": "blobOutputMedium",
            "direction": "out"
        }
    ]
}
```

Method signature:

```

public static void Run(
    BlobInfo blobInfo,                                // from queue trigger
    Stream input,                                     // input blob, large size
    Stream blobOutputSmall, Stream blobOutputMedium,  // output blobs
    TraceWriter log) 
```

**Comment by fabiocav** [comment]
@lindydonna are you able to repro this? If so, can you provide more details?

When I have a name mismatch on the trigger, I get the expected error:
```
2016-04-05T04:40:45.953 error AF003: Missing a trigger argument named 'blobInfo'.
```
When the mismatch is with one (or more) of the bindings, I get the expected warnings:
```
2016-04-05T04:44:41.296 warning AF004: Missing binding argument named 'input'.
2016-04-05T04:44:41.296 warning AF004: Missing binding argument named 'blobOutputSmall'.
2016-04-05T04:44:41.296 warning AF004: Missing binding argument named 'blobOutputMedium'.
```
The error you're providing above is from the indexer, which means the function was successfully compiled and passed down to the SDK, but in this case, it looks like the type wasn't supported by the binding. Did you have a different trigger type? Or perhaps the names were switched so BlobInfo was passed to the wrong binding?

**Comment by lindydonna** [comment]
Now I get the additional warning, but I also get the confusing message. So, it's an improvement at least, but the error message is not great.

Here's a simpler repro.

run.csx:
```
using System;

public class BlobInformation
{
    public string FileName { get; set; }
}

public static void Run( 
    BlobInformation blobInfo,    
    Stream input,                      
    Stream blobOutputSmall,
    TraceWriter log) 
{ 
}
```

function.json, with mismatch in parameter "input":
```
{
  "bindings": [
    {
      "queueName": "resize-fun-request",
      "type": "queueTrigger",
      "name": "blobInfo",
      "direction": "in"
    },
    {
      "path": "images/{FileName}",
      "type": "blob",
      "name": "input1",
      "direction": "in"
    },
    {
      "path": "images/{FileName}",
      "type": "blob",
      "name": "blobOutputSmall",
      "direction": "out"
    }
  ],
  "disabled": false
}
```

```2016-04-08T20:48:39.039 Compiling function script.
2016-04-08T20:48:39.122 warning AF004: Missing binding argument named 'input1'.
2016-04-08T20:48:39.122 Compilation succeeded.
2016-04-08T20:48:39.711 Microsoft.Azure.WebJobs.Host: Error indexing method 'Functions.TestCSharp'. Microsoft.Azure.WebJobs.Host: Cannot bind parameter 'input' to type Stream. Make sure the parameter Type is supported by the binding. If you're using binding extensions (e.g. ServiceBus, Timers, etc.) make sure you've called the registration method for the extension(s) in your startup code (e.g. config.UseServiceBus(), config.UseTimers(), etc.).
```

**Comment by fabiocav** [comment]
The indexing error is indeed confusing (that was surfaced with some logging changes), but AF004 is the correct behavior, based on the current design. Is there a different verbiage you'd like to see?

**Comment by lindydonna** [comment]
@fabiocav AF004 is fine. For the indexing error, maybe we add a sentence after the first one: Error indexing method 'Functions.TestCSharp'. Microsoft.Azure.WebJobs.Host: Cannot bind parameter 'input' to type Stream. **Make sure your binding name and parameter name match. ** etc.

**Comment by fabiocav** [comment]
The indexing message comes directly from the WebJobs SDK, which doesn't have the binding name concept. We can probably enhance AF004 to provide more details and check if there is an orphan binding and provide a suggestion to use it.

**Comment by lindydonna** [comment]
Yeah, if AF004 somehow tells you that the next webjobs host error is related, that's enough.

**Comment by fabiocav** [comment]
@lindydonna, how does the following sound?
`Missing binding argument named '{0}'. Mismatched binding argument names may lead to function indexing errors.`

**Comment by lindydonna** [comment]
@fabiocav Yes, that would be good. The error basically helps explain the next error.
