### ISSUE TITLE
Mitigate Roslyn compiler issue for non-HTTP triggers

### ISSUE THREAD

**Issue by lindydonna** [Azure/azure-webjobs-sdk-script#1722]
We're getting more customer incidents related to the Roslyn compiler issue and triggers other than HTTP, so we need more of a fix than just https://github.com/Azure/azure-webjobs-sdk-script/issues/999. 

For an example of a CRI with an EventHub trigger, see email with subject **WA-WebSites: Occasionally getting an error in function MessageReceiver in function app "'Cannot enqueue data after PromiseNotToEnqueue’**. That incident has a stack trace that we can provide to the Roslyn team.

**Comment by christopheranderson** [comment]
@fabiocav will give us a sense of impact before we triage
