### ISSUE TITLE
Webhook type of 'generic' gives 500 error with no logs

### ISSUE THREAD

**Issue by paulbatum** [Azure/azure-webjobs-sdk-script#173]
Steps to reproduce:

1. Use C# http trigger template
2. Change webhook type to an invalid value (such as 'generic', which no longer exists)
3. Hit the API 

Expected result: Some type of reasonable error
Actual result: No error, nothing in logs, 500 with no explanation

**Comment by davidebbo** [comment]
I can't repro. Setting it to "generic" or "qqq" seems to have no effect, and the function still runs.

**Comment by mathewc** [comment]
Are you doing a POST? All the WebHooks will return 405 if its not a POST. You also have to set the Content-Type, and have a valid JSON body.

**Comment by davidebbo** [comment]
I'm assuming he's hitting Run from Portal, which is a post and sets content type. Besides he gets a 500, so clearly something else is going on.

**Comment by paulbatum** [comment]
I was doing a POST, running through fiddler.

**Comment by fabiocav** [comment]
It's a defect. I see the code path and have a fix I'll be referencing here.

**Comment by davidebbo** [comment]
So why does it work with Run button?

**Comment by fabiocav** [comment]
I didn't look through that path, I'll look to see why that works. You'll see in the simple fix referenced above that we were just returning a 500 with no additional details when we couldn't find a receiver.

**Comment by davidebbo** [comment]
I see, reason it doesn't blow up in Portal is that it doesn't go through the WebHooks library for auth (uses admin key instead). WebHooks library is what's blowing up on the unknown type.

**Comment by fabiocav** [comment]
Yes, that's exactly right.
