### ISSUE TITLE
Runtime must refuse to execute function app that has out of sync function.json

### ISSUE THREAD

**Issue by paulbatum** [Azure/azure-webjobs-sdk-script#1732]
The new code path introduced to make for a better experience when working with functions (see https://github.com/Azure/azure-webjobs-sdk-script/issues/1508) creates the opportunity for a very confusing edge case. 

Steps to reproduce:

1. Create a function app in VS using the RTM tooling.
2. Put two functions into the same class file (say one queue trigger and one timer trigger)
3. Build and deploy the function app in the consumption plan
4. Go to kudu and edit the file system of the deployed function app by deleting the function.json file for the timer trigger.
5. Refresh the portal

Ideal result: the timer trigger no longer executes (because its function.json was deleted)

good enough result: the function app refuses to load any functions, writing a detailed error about the inconsistency to the host log

actual result: the timer trigger will run in a non-deterministic fashion. If the queue is active then this will activate the function app and the timer trigger will run while that is the case. Once the queue goes idle the app will goes idle, because the scale infrastructure can't see the timer trigger.

**Comment by MikeStall** [comment]
Fixed. We will now fail to execute the function if there's no corresponding function.json.

**Comment by davidebbo** [comment]
Does *fail to execute* mean *don't execute*, or *fail with some error*?

Note that the 'even more ideal' solution here would be to have the scale controller be able to consume the attribute even if there is no function.json. But a bunch of changes are needed to get there.

**Comment by paulbatum** [comment]
The entire function app will refuse to execute. No functions will run. There will be an initialization error in the host log.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by davidebbo** [comment]
@paulbatum that's good. Better catch the inconsistency early and fail loud and clear (until we can make it just work).

**Comment by paulbatum** [comment]
Sorry I should clarify, the description I gave is what we discussed the behavior should be. Looks like from my quick scan of the change is that the specific function will fail to run with an error. Not the full app.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
