### ISSUE TITLE
F# Azure Functions don't get all values initialized

### ISSUE THREAD

**Issue by brettfo** [Azure/azure-webjobs-sdk-script#1748]
Not all F# values are initialized, possibly due to the `Run()` method being invoked via reflection.

E.g.,

``` F#
let list = []
let Run(myTimer: TimerInfo, log: TraceWriter) =
    log.Info(sprintf "value=%A" list)
```

Results in the output of `value=[]`, but placing a value inside the list causes it to be null:

``` F#
let list = [0]
let Run(myTimer: TimerInfo, log: TraceWriter) =
    log.Info(sprintf "value=%A" list)
```

Results in the output of `value=<null>`.  Similar behavior can be observed with `let list = new System.Text.StringBuilder()`.

**Workaround:**
Replace the value with a function, e.g., `let list = [0]` -> `let getList() = [0]`.

**Comment by ahmelsayed** [comment]
related: https://github.com/Azure/azure-webjobs-sdk-script/issues/1247 ?

**Comment by brettfo** [comment]
Good call, that looks like the same issue: reference types are being defaulted to `null` and value types are getting zeros.  Closing this in favor of the other.
