### ISSUE TITLE
Add support for app_offline.htm

### ISSUE THREAD

**Issue by davidebbo** [Azure/azure-webjobs-sdk-script#1753]
The primary way that VS/msdeploy avoids locked files issues during deployment is app_offline.htm. The expectation is that when this file is created at the root, the app shuts down and all locked files are released. Then when it's removed, the app restarts.

This works for ASP.NET and ASP.NET Core apps, but we currently have no support for it in functions, so that VS deployment option is a no-op.

One mitigation is that normally, Functions doesn't lock files, but that could still happen when native DLLs are in the picture.

We should see whether there is a way we can implement that by detecting that file and releasing everything.

**Comment by fabiocav** [comment]
Duplicate of #1521

**Comment by davidebbo** [comment]
Identical title too! :)
