### ISSUE TITLE
New Webhook system key enforcement breaks 3rd party binding extensions

### ISSUE THREAD

**Issue by cgillum** [Azure/azure-webjobs-sdk-script#1754]
### Summary
The [Authentication model for Extension WebHooks PR](https://github.com/Azure/azure-webjobs-sdk-script/pull/1659) which was recently deployed to production breaks the WebHook scenarios for Durable Functions and other 3rd party binding extensions.  This issue primarily focuses on Durable Functions, but the fundamental issues are expected to affect others as well.

### Context
Durable Functions allows clients to start a new orchestrator function instance using an authenticated HTTP call and the result is a set of URLs (including a `Location` header) which point to WebHook APIs implemented by the extension.  Previously these WebHook APIs were anonymously accessible, but the endpoints required the client to know the GUID of an orchestration instance in order to do anything interesting.

### Repro Steps
1. Use VS to create a new DF application
2. Publish the DF application to Azure
3. Start a new orchestrator function instances using the `HttpStart` function found in the samples
4. Get the `Location` header from the response and query it

**Expected**: Querying the URL in the `Location` header returns a success response.
**Actual**: Querying the `Location` URL returns a 401 response

### Details
The problem is that all Webhook endpoints now require a new extension-specific "system key" for authorization. Because the `Location` header doesn't include any such system key, all Webhook invocations fail with 401.

There are two issues that need a resolution:

1. Because the built-in WebHook URLs require auth, the `Location` header generated by the DF extension needs to include the system key in the query string.  However, there is no way for the extension to know what the system key is, so there is no way to generate a correct `Location` header. 
2. There is currently no way to manage system keys except to make authenticated REST calls to the function app's admin endpoint. This means customers need to use cURL/Postman/etc to generate an appropriately named system key and then manually attach that to the URLs they receive from the DF extension.

### Known workarounds
The known workaround is to have the customer revert back to an older version of the Azure Functions runtime and an older version of the DF extension (recent versions of the DF extension depend on unrelated features of the Functions runtime which were deployed at the same time).

The other workaround is to do all the manual steps mentioned earlier to provision a system key and attach it to all web hook URLs received from the extension.

**Comment by mathewc** [comment]
The runtime does auto-provisioning of extension hook keys if not present, and makes them available to the extension via the GetURL method of the extension hook provider: https://github.com/Azure/azure-webjobs-sdk-script/blob/8309e2b58008d8abed55d419f3e7e23d771f7ede/src/WebJobs.Script.WebHost/WebHooks/WebJobsSdkExtensionHookProvider.cs#L36 

So you should be able to get this URL in your extension, grab the code value and use it

**Comment by christopheranderson** [comment]
@cgillum - are you unblocked now? can this be closed?

**Comment by cgillum** [comment]
Yep. Verified that the auto-provisioning works. I will release an update of the DF extension which leverages this behavior.
