### ISSUE TITLE
Routing logic should apply precedence consitent with ASP.NET

### ISSUE THREAD

**Issue by fabiocav** [Azure/azure-webjobs-sdk-script#1756]
Currently, there's no precedence logic applied to routes based on templates. The runtime should apply the same logic used by ASP.NET when resolving routes.

**Comment by christopheranderson** [comment]
Potentially breaking, but there is debate whether it can break in practice.

**Comment by paulbatum** [comment]
This is going to naturally fixed in functions 2.x by virtue of us being able to compose cleanly with ASP.NET core routing logic. I don't think its worth making this change for 1.x.
