### ISSUE TITLE
Where do i execute a one-time per appdomain logic for adding license to third party tools

### ISSUE THREAD

**Issue by ahmelsayed** [Azure/azure-webjobs-sdk-script#1759]
_From @ShayanZafar on July 31, 2017 18:52_

Hello,

We are using a third party tool Aspose for document conversion. I want to know where i can run one-time logic for adding license information for the third party tool to work per app domain for my function. 

_Copied from original issue: Azure/azure-functions-cli#196_

**Comment by ahmelsayed** [comment]
@ShayanZafar I don't think there is a way to achieve this now. @fabiocav and @mathewc will know more.

**Comment by fabiocav** [comment]
We don't really have a "hook" that will explicitly invoke your code when an AppDomain is created, but, with that said, AppDomain creation in the runtime only happens within the context of ASP.NET, which is for the ASP.NET domain your function (and any other code you run) will execute under, so you can manage this logic with some static state and logic that is executed before you use the Aspose library that requires the licensing information to be set (e.g. by storing some static state and calling your initialization method that runs conditional on that state being set when your function executes)

**Comment by ShayanZafar** [comment]
Hey, thanks for answering,

i overcame this problem by following this article:

https://blogs.msdn.microsoft.com/appserviceteam/2017/03/16/publishing-a-net-class-library-as-a-function-app/

**Comment by fabiocav** [comment]
Closing as resolved.
