### ISSUE TITLE
The Function Apps seem to be automatically updated to the latest version of Master rather than the latest release version

### ISSUE THREAD

**Issue by akhilaj** [Azure/azure-webjobs-sdk-script#1775]
![capture](https://user-images.githubusercontent.com/5424100/29211040-409c2212-7eb4-11e7-87bd-c1ddcf88c3ac.JPG)

As shown in the screenshot we are on 1.0.11090.0 (~1) but the latest release is 1.0.11075

**Comment by christopheranderson** [comment]
This is correct, we didn't publish a release for that patch. We'll update the repo soon.
