### ISSUE TITLE
Would it be possible to introduce an option to not auto-generate a run.csx file for functions that will be deployed as DLLs

### ISSUE THREAD

**Issue by ShayanZafar** [Azure/azure-webjobs-sdk-script#1782]
Our Deployment process involves selecting the correct function file and manually deleting the run.csx file as it is not needed for our DLL deployment.

we are deploying as a class library and only need to deploy host.json, function.json and the required DLLs. could there be a checkbox or something for the function creator to not include this file out of convenience?

Perhaps this could be in the form of a template specifically for a function that is to be deployed as a Class Library?

**Comment by fabiocav** [comment]
We have a preview project (for VS 2017) targeting this scenario, have you tried that?

**Comment by ShayanZafar** [comment]
no i am still using visual studio 2015. i was also referring to creating a function via the azure portal

**Comment by ShayanZafar** [comment]
I wanted to suggest that this be added to the portal as an enhancement.

**Comment by christopheranderson** [comment]
Sorry, but today our plans are to support Functions in VS 2017 only, going forward, via the compiled Functions based project.
