### ISSUE TITLE
Upgrading to 1.0.1 CLI tools and SDK starts breaking things

### ISSUE THREAD

**Issue by leolorenzoluis** [Azure/azure-webjobs-sdk-script#1783]
After upgrading to 1.0.1 CLI tools without any code changes, I suddenly started to get the following error:

```
ResizeImage: Microsoft.Azure.WebJobs.Host: Error indexing method 'Functions.ResizeImage'. Microsoft.Azure.WebJobs.Extensions.DocumentDB: 'Id' is required when binding to a DocumentClient property.
```

The following code:

```
 [FunctionName(nameof(ResizeImage))]
        public static async Task RunAsync([BlobTrigger("profile-pictures/{name}")] CloudBlockBlob myBlob, string name, [DocumentDB(databaseName: "x", collectionName: "UserProfile", CreateIfNotExists = true)] DocumentClient client, [Blob("profile-pictures/resized-{name}", FileAccess.ReadWrite)] CloudBlockBlob resizedBlob, TraceWriter log)
```

I thought Id is optional? At least that's what the docs says.

According to the docs:

```
The properties id and sqlQuery cannot both be specified. If neither id nor sqlQuery is set, the entire collection is retrieved.
```

The generated json:

```
{
  "bindings": [
    {
      "type": "blobTrigger",
      "path": "profile-pictures/{name}",
      "direction": "in",
      "name": "myBlob"
    },
    {
      "type": "documentDB",
      "databaseName": "x",
      "collectionName": "UserProfile",
      "createIfNotExists": true,
      "direction": "out",
      "name": "client"
    },
    {
      "type": "blob",
      "path": "profile-pictures/resized-{name}",
      "direction": "inout",
      "name": "resizedBlob"
    }
  ],
  "disabled": false,
  "scriptFile": "..\\X.Functions.dll",
  "entryPoint": "X.Functions.ResizeImage.RunAsync"
}
```

I'm using 1.0.0 SDK

**Comment by brettsam** [comment]
What version of DocumentDB are you referencing? It's possible that you moved up to a version that we don't support and it's resulting in a bad error message.

**Comment by leolorenzoluis** [comment]
Originally I had the following:

```
<PackageReference Include="Microsoft.NET.Sdk.Functions" Version="1.0.0-alpha6" />
```

I upgraded now to 

```
<PackageReference Include="Microsoft.NET.Sdk.Functions" Version="1.0.0" />
```

**Comment by brettsam** [comment]
Actually -- you may be hitting some of the 'improved' signature error detection that's been added fairly recently. Can you change the attribute to just be `[DocumentDb]`? None of the other properties are needed for the `DocumentClient` parameter type. If that's the case, we must be checking the parameter type in the wrong order -- which I'll fix.

**Comment by brettsam** [comment]
Also -- do you see this error when you run locally? or just when you deploy to Azure?

**Comment by leolorenzoluis** [comment]
Hmm? If I change it to just [DocumentDb] then the generated package.json is wrong.

This is running local environment.

```
{
  "generatedBy": "Microsoft.NET.Sdk.Functions-1.0.0.0",
  "configurationSource": "attributes",
  "bindings": [
    {
      "type": "blobTrigger",
      "path": "profile-pictures/{name}",
      "name": "myBlob"
    }
  ],
  "disabled": false,
  "scriptFile": "..\\bin\\X.Functions.dll",
  "entryPoint": "X.Functions.ResizeImage.RunAsync"
}
```

Either way it now gives me the following error instead:

```
[8/14/2017 8:28:11 PM] Microsoft.Azure.WebJobs.Host: Error indexing method 'ResizeImage.RunAsync'. Microsoft.Azure.WebJobs.Host: Invalid storage account 'devstoreaccount1'. Please make sure your credentials are correct.
[8/14/2017 8:28:11 PM] Error indexing method 'ResizeImage.RunAsync'
[8/14/2017 8:28:11 PM] Microsoft.Azure.WebJobs.Host: Error indexing method 'ResizeImage.RunAsync'. Microsoft.Azure.WebJobs.Host: Invalid storage account 'devstoreaccount1'. Please make sure your credentials are correct.
[8/14/2017 8:28:11 PM] No job functions found. Try making your job classes and methods public. If you're using binding extensions (e.g. ServiceBus, Timers, etc.) make sure you've called the registration method for the extension(s) in your startup code (e.g. config.UseServiceBus(), config.UseTimers(), etc.).
[8/14/2017 8:28:11 PM] Job host started
[8/14/2017 8:28:11 PM] The following 1 functions are in error:
[8/14/2017 8:28:11 PM] RunAsync: Microsoft.Azure.WebJobs.Host: Error indexing method 'ResizeImage.RunAsync'. Microsoft.Azure.WebJobs.Host: Invalid storage account 'devstoreaccount1'. Please make sure your credentials are correct.
[8/14/2017 8:28:11 PM]
```

**Comment by brettsam** [comment]
Thanks for all the details -- I see this locally as well. I'm going to confer with some tooling experts and see if we can figure out what's going on.

**Comment by brettsam** [comment]
I found the issue and filed https://github.com/Azure/azure-functions-cli/issues/206. The easiest workaround until we have an update:

1. Go to `C:\Users\{user}\appdata\local\Azure.Functions.Cli\1.0.0`.
2. Open `func.exe.config` in notepad.
3. Find this:
```
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.Azure.Documents.Client" publicKeyToken="31bf3856ad364e35" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-1.11.0.0" newVersion="1.11.0.0" />
      </dependentAssembly>
```
4. In both places, replace `1.11.0.0` with `1.13.0.0` so you end up with:
```
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.Azure.Documents.Client" publicKeyToken="31bf3856ad364e35" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-1.13.0.0" newVersion="1.13.0.0" />
      </dependentAssembly>
```
5. Save and retry.

**Comment by leolorenzoluis** [comment]
That fixes it. Thank you!

**Comment by ThorstenHans** [comment]
If anyone is also having this issue, verify that you executed the Functions project at least on time locally. Otherwise you won't be able to find the `Azure.Functions.Cli` folder underneath `appdata\local` once you've started the functions project locally, follow the steps described by @brettsam

**Comment by ThorstenHans** [comment]
@brettsam followed all the instructions, but still ending up without having a binding defined for `[DocumentDB]`.

so the function definition looks like this

```
   public static HttpResponseMessage Run(
            [HttpTrigger(AuthorizationLevel.Function, "post")]HttpRequestMessage req,
            [DocumentDB("db", "col", CreateIfNotExists = true, ConnectionStringSetting = "AzureWebJobsDocumentDBConnectionString")] out dynamic document,
            TraceWriter log)
        {
```
the `function.json` is generated like this

```
{
  "generatedBy": "Microsoft.NET.Sdk.Functions-1.0.0.0",
  "configurationSource": "attributes",
  "bindings": [
    {
      "type": "httpTrigger",
      "methods": [
        "post"
      ],
      "authLevel": "function",
      "name": "req"
    }
  ],
  "disabled": false,
  "scriptFile": "..\\bin\\Sample.Fn.dll",
  "entryPoint": "Samaple.Fn.CreateItem.Run"
}
```

Wondering if anyone gets this up and running. It's a clean windows 10 VM with latest VS2017 and all updates installed

**Comment by ThorstenHans** [comment]
Investigated a bit more time here, it seems like there is no binding required for `[DocumentDB]` items are being created as expected without having the `binding` being defined. 

I think docs should point to that

**Comment by brettsam** [comment]
Were you expecting to see the binding in your `function.json`? When using the VS tools, all of that metadata comes from the attributes themselves so you won't see that -- we use the `"configurationSource": "attributes"` for that. You're right that [this topic](https://docs.microsoft.com/en-us/azure/azure-functions/functions-develop-vs) could probably have a callout note that explains that this is happening so it doesn't confuse people.
