### ISSUE TITLE
Enable or Remove Disabled test

### ISSUE THREAD

**Issue by mathewc** [Azure/azure-webjobs-sdk-script#1787]
There is only one disabled/skipped test in our repo currently and it was added recently. https://github.com/Azure/azure-webjobs-sdk-script/blob/64248427d51faa0a1c00a815428cdc11c35faff4/test/WebJobs.Script.Tests.Integration/DirectLoadEndToEndTests.cs#L31

We should get this test running or delete it

**Comment by MikeStall** [comment]
Don't delete it. This tests our VS tooling support.   We were hitting appveyor problems.  We should fix appveyor.

**Comment by mamaso** [comment]
What's the appveyor problem?

I find this helpful for debugging tricky issues:
https://www.appveyor.com/docs/how-to/rdp-to-build-worker/

**Comment by MikeStall** [comment]
It's fixed now. I think this was fixed by @fabiocav tweaking AppVeyor to run tests with more isolation.
