### ISSUE TITLE
Simple http function doesn't work when using code in query string

### ISSUE THREAD

**Issue by davidebbo** [Azure/azure-webjobs-sdk-script#179]
Use the following C# http function:

```c#
using System.Net;

public static HttpResponseMessage Run(HttpRequestMessage req, TraceWriter log)
{
    return req.CreateResponse(HttpStatusCode.OK, "Hello");
}
```

Request it using the `?code=` URL as a GET using the browser, or PostMan.

Result: you get a 500.

If you instead auth using `x-functions-key` (as the portal does), then it works.

Probably another funky thing going on with the WebHook library auth. @fabiocav, I know you had fixed something like this, but maybe this is different.

**Comment by davidebbo** [comment]
Oh, ignore, I had a bogus `webHookType` in there :)

**Comment by fabiocav** [comment]
Ah, I was about to ask you for your function.json so I could take a look at that. Are you running against the latest bits or what is deployed? With the fix I pushed on Friday, you should get a nice descriptive message in the function's log.

**Comment by davidebbo** [comment]
Running against Prod. Let's deploy update tomorrow morning!

**Comment by christopheranderson** [comment]
Ought to add an issue template which asks for the code sample and function.json :)  https://github.com/blog/2111-issue-and-pull-request-templates
