### ISSUE TITLE
Is there a COMPILED symbol in the C# scripting host?

### ISSUE THREAD

**Issue by nicolocodev** [Azure/azure-webjobs-sdk-script#1796]
in order to improve the experience of local development i was wondering if within Roslyn/Azure Function host exist something [like this, in F# Interactive](https://docs.microsoft.com/en-us/dotnet/fsharp/tutorials/fsharp-interactive/#differences-between-the-interactive-scripting-and-compiled-environments).

**Comment by christopheranderson** [comment]
No, this doesn't exist.
