### ISSUE TITLE
Project Microsoft.Azure.WebJobs.Script is not compatible with netcoreapp2.0

### ISSUE THREAD

**Issue by KaiWalter** [Azure/azure-webjobs-sdk-script#1798]
I get a "Project Microsoft.Azure.WebJobs.Script is not compatible with netcoreapp2.0" followed by a of similar messages after updating to .NET Core 2.0 SDK and VS2017 15.3

1. updated to released .NET Core 2.0 SDK
  `dotnet --info`
```
.NET Command Line Tools (2.0.0)

Product Information:
 Version:            2.0.0
 Commit SHA-1 hash:  cdcd1928c9

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.0\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d
```
2. updated to VS2017 15.3
3. go to some working dir
4. `git clone https://github.com/Azure/azure-webjobs-sdk-script.git`
5. `cd azure-webjobs-sdk-script`
6. `git checkout core`
7. `nuget restore .\WebJobs.Script.sln`

I'd expected that the `core` branch is based on .NET Core 2.0.

What did I miss?

**Comment by fabiocav** [comment]
What do you see if you run `dotnet restore` (or `dotnet build`) instead? That should work as expected.

**Comment by KaiWalter** [comment]
Thanks @fabiocav, I just realized that when making a fresh start this morning.
You're right, with dotnet restore + build it works.
