### ISSUE TITLE
Console host fails if AzureWebJobsDashboard is not set

### ISSUE THREAD

**Issue by ancaantochi** [Azure/azure-webjobs-sdk-script#1799]
If I start WebJobs.Script.Host without setting AzureWebJobsDashboard variable, it throws an exception:

System.InvalidOperationException: 'Microsoft Azure WebJobs SDK 'Dashboard' connection string is missing or empty. 

Because of this exception the host can't start: A ScriptHost error has occurred      
Stopping Host  

I use the console host from core branch.

**Comment by mathewc** [comment]
Fix will go out in next release. To work around, you can add the following line to your host startup code:

```csharp
config.HostConfig.DashboardConnectionString = null;
```
