### ISSUE TITLE
[Node][Table Binding] Table output binding doesn't properly grab property from HTTP trigger

### ISSUE THREAD

**Issue by christopheranderson** [Azure/azure-webjobs-sdk-script#180]
## Issue

When I use a table output binding, fed by a HTTP trigger, where the rowkey is set to `{id}`, I receive an error:

```
2016-03-28T05:24:02.940 Exception while executing function: Functions.tables-test. Microsoft.Azure.WebJobs.Host: No value for named parameter 'id'.
```

I receive this error, even though my request body was sent via a request with:
 - HTTP POST
 - content-type: application/json
 - body:
    ```
{
    "id":"c77391c5-d5d5-411d-a002-547e6b69dada",
    "name": "Azure"
}
```

I believe this is an issue with HTTP trigger not properly exposing properties, as when I tested this with a queue trigger, it worked successfully.

### index.js

```javascript
module.exports = function(context, req) {
    context.log('Node.js HTTP trigger function processed a request. RequestUri=%s', req.originalUrl);

    if (req.query.name || (req.body && req.body.name)) {
        context.res = {
            // status: 200, /* Defaults to 200 */
            body: "Hello " + (req.query.name || req.body.name)
        };
        context.bindings.table = {"start_time": (new Date()).toJSON(), "end_time": (new Date()).toJSON(), "parent_id": "1"}
    }
    else {
        context.res = {
            status: 400,
            body: "Please pass a name on the query string or in the request body"
        };
    }
    context.done();
};
```

### function.json

```JSON
{
  "bindings": [
    {
      "webHookType": "",
      "type": "httpTrigger",
      "direction": "in",
      "name": "req"
    },
    {
      "type": "http",
      "direction": "out",
      "name": "res"
    },
    {
      "tableName": "testtable",
      "partitionKey": "12345",
      "rowKey": "{id}",
      "connection": "<MYAPPSETTING>",
      "name": "table",
      "type": "table",
      "direction": "out"
    }
  ],
  "disabled": false
}
```

**Comment by christopheranderson** [comment]
After playing with the C# experience and thinking about the JS experience, I think that we're actually doing the wrong things for the table output binding for JS and C# is technically 'broken', but is actually a better user experience.

In the C# experience, we rely on `ICollector<T>` for outputting records to storage. In this case, it's up to the user's discretion what the `RowKey` and `PartionKey` is per record; not via the function.json settings.

In the Node experience, we only support a single item and the `RowKey`/`PartionKey` is set via the function.json.

This presents a problem extreme incongruity between the Node and C# experience; C# supporting many and keys are set in user code, and node the opposite. 

I think, ideally, the node experience changes to support an array of JSON objects and we no longer force users to template the keys via the `function.json` for the Table binding.

**Comment by christopheranderson** [comment]
Additionally, it is still an issue that HTTP Trigger for Node appears to be not using properties from an HTTP request body, but .NET is.

**Comment by mathewc** [comment]
Yes, the Node.js Table binding is still experimental - we have work to do there. I put some cool features in there a long time ago to explore possibilities, but I haven't iterated on it since.

I agree that it would be good to expand the set of supported binding operations to allow collections as well, but note that this applies across ALL Node.js binding support (e.g. collection support for queues, blobs, etc.)

**Comment by mathewc** [comment]
Table binding already supports collect
