### ISSUE TITLE
Colon In Http route constraint causes failure

### ISSUE THREAD

**Issue by mathewc** [Azure/azure-webjobs-sdk-script#1810]
Repro:

- create an http function with a custom route `test/{dt:datetime}`
- attempt to send a valid url including colons in the datetime value (e.g.`http://host/api/test/2017-08-18 20:06:30` ) it will cause a host failure

The same URL will work in ASP.NET, so it looks like something we're doing wrong.

**Comment by mathewc** [comment]
This can be reproed locally using the local host. Use of a colon in the URL results in an error "A potentially dangerous Request.Path value was detected from the client (:).".

**Comment by paulbatum** [comment]
I believe this is due to ASP.NET request validation. My understanding is that this validation has changed in .NET core so it will be resolved in the .NET core version of functions.
