### ISSUE TITLE
Function Runtime : Container is unhealthy. Recycling container...

### ISSUE THREAD

**Issue by Deepul** [Azure/azure-webjobs-sdk-script#1812]
Have followed the instruction to install Azure functions runtime on windows server 2016. 
-Installation went sucessfull.
i can access the portel rom url to IIS.
-i can  create the function app .
-and deploy using visual studio and all.
-Also have downloaded the azfuncrun/functions:0.latest docker image manually because it kept looping to download.
-This image is downloaded and installed.

However the container app function recycles and stops and spins another container.
-It is a simple timertrigger function with one line (defsult) to log the executions.

Please refer to the logs below.

2017/08/21 4:16:12 PM [WIN-SPLKPM61TUA] Container is Unhealthy testtesttest_5
2017/08/21 4:16:12 PM [WIN-SPLKPM61TUA] Container testtesttest is unhealthy. Recycling container...
2017/08/21 4:16:12 PM [WIN-SPLKPM61TUA] Function App 'testtesttest' is stopping...
2017/08/21 4:16:12 PM [WIN-SPLKPM61TUA] Issuing stop command to container: testtesttest_5
2017/08/21 4:16:12 PM [WIN-SPLKPM61TUA] Disposed container health check timer.
2017/08/21 4:16:12 PM [WIN-SPLKPM61TUA] Stop complete for container: testtesttest_5
2017/08/21 4:16:12 PM [WIN-SPLKPM61TUA] Function App 'testtesttest' has been stopped.
2017/08/21 4:16:12 PM [WIN-SPLKPM61TUA] Function App 'testtesttest' is starting...
2017/08/21 4:16:12 PM [WIN-SPLKPM61TUA] Provisioning container testtesttest_6
2017/08/21 4:16:53 PM [WIN-SPLKPM61TUA] Container testtesttest_6 has been created. (Id: 4bb9043e35acc52936c435f1d8cccf5ee7a7c6461a60fe7dd176080c78494c64

#### Investigative information

- Timestamp: 2017/08/21 4:16:53 pm
- Function App name: testtesttest
- Function name(s) (as appropriate): TimetTriggerCSharp1
- Invocation ID: 4bb9043e35acc52936c435f1d8cccf5ee7a7c6461a60fe7dd176080c78494c64
- Region: Runtime on premise.

#### Repro steps

Deploy function to azure runtime and try and start observe the logs.

#### Expected behavior
Log line to appear in the logs with the following code.
using System;

public static void Run(TimerInfo myTimer, TraceWriter log)
{
    log.Info($"C# Timer trigger function executed at: {DateTime.Now}");    
}

#### Actual behavior

Container starts and stops continuously without running the function.

#### Known workarounds

Run it in the Azure function (Cloud).

#### Related information 
NON

**Comment by mattsimpson001** [comment]
Having the exact same issue

**Comment by Deepul** [comment]
a) Hi i got around the issue by running this: 
 run the following in the VM power shell: 
Get-VM | Set-VMProcessor -ExposeVirtualizationExtensions $true    
Resource :  (https://github.com/Azure/Azure-Functions/issues/359)

b) And then change the trigger or refresh the function for a change to take place.
c) Wait a while while recycling of containers happens.
d) Eventually will work.
Hope it helps.

**Comment by jvano** [comment]
Yes, we use Hyper-V containers and if you run the workers on a virtual machine, you need to enable nested virtualization for Hyper-V VMs to be able to create Hyper-V containers.

**Comment by mattsimpson001** [comment]
I don't see any VMs running in Hyper-V, there is no documentation on Windows Container configuration. If I run "docker ps" I see the docker image get spun up but then keeps getting killed and recreated.
I see "Handler for GET /v1.29/containers: No such container" errors in the Event Log

**Comment by Deepul** [comment]
-Also get this error this error .../v1.29/ ...  It seems misleading error. Because even if my containers work i still get this error in the event logs.
-Although virtualization for Hyper-V VMs worked for me.
-My containers occasionally keeps spanning another containers and then after a while is stable again.

**Comment by jvano** [comment]
Hyper-V containers uses Hyper-V Technology but you won't see them in the Hyper-V management.  For more info please see: 
[https://docs.microsoft.com/en-us/virtualization/windowscontainers/manage-containers/hyperv-container](url)

Regarding the containers getting killed and recreated, please look into the functions worker in the following windows event log for more details:

- Microsoft-Windows-FunctionsRuntime/Operational

Please let us know if you find something there

**Comment by mattsimpson001** [comment]
I get a number of errors there, but also after the below errors I get "Functions Host Activation Service has started successfully!'

5002
WriteContainerLogsToDisk failed: System.FormatException: The string was not recognized as a valid DateTime. There is an unknown word starting at index 0.
   at System.DateTimeParse.Parse(String s, DateTimeFormatInfo dtfi, DateTimeStyles styles)
   at Microsoft.Functions.Runtime.Activation.Service.Containers.WindowsContainer.CaptureContainerLogsSinceTimeStamp(String[]& standardOut, String[]& standardErr)
   at Microsoft.Functions.Runtime.Activation.Service.Containers.WindowsContainer.WriteConainerLogsToDisk()

5002
System.InvalidOperationException: Operation is not valid due to the current state of the object.
   at Microsoft.Functions.Runtime.Data.FunctionManager.GetDefaultConnectionString(RoleType role)
   at Microsoft.Functions.Runtime.Data.FunctionManager..ctor(RoleType roleType)
   at Microsoft.Functions.Runtime.Activation.Service.FunctionAppOwnership.OnTimerElapsed(Object state)

**Comment by jvano** [comment]
I'm glad it finally worked.

We have just recently announced "Azure Functions Runtime" preview 2
https://blogs.msdn.microsoft.com/appserviceteam/2017/12/05/announcing-azure-functions-runtime-preview-2/

In this version we have fixed several issues including the String.FormatException. Additionally, we have  added a lot of new improvements.
