### ISSUE TITLE
Function runtime: Precompiled function issue invalid.csx

### ISSUE THREAD

**Issue by Deepul** [Azure/azure-webjobs-sdk-script#1825]
#### Investigative information
- Timestamp:   2017-08-24T12:18:47.387Z
- Function App name:   testfunction01
- Function name(s) (as appropriate):     CreateLoadFunction
- Invocation ID:       (Id: f3870072dc48944760d83add2778e352345995dfbe2a395aa7b844061511a248)
- Region:     Azure Function runtime.

#### Repro steps
1. Install Azure function runtime on a VM.
2. Deploy Pre compiled function.

#### Expected behavior
1) Pre compiled Function when deployed to Azure function runtime server should run.
2) Pre compiles function on azure function runtime should work like on Azure function app on azure.

#### Actual behavior
1) Pre compiled Function when deployed to Azure function runtime server does not run.
2) Throws an error on the screen: Error:
**ERROR:** 
We are not able to get the content for invalid.csx. Please try again later.
Timestamp: 2017-08-24T12:18:47.387Z

#### Known workarounds

-Un known.

#### Related information 

* Programming language used :   C#
* Links to source : N-A
* Bindings used : 
{
  "bindings": [
    {
      "type": "timerTrigger",
      "schedule": "0 */3 * * * *",
      "useMonitor": true,
      "runOnStartup": false,
      "direction": "in",
      "name": "myTimer"
    }
  ],
  "disabled": false,
  "scriptFile": "..\\AzureFunction_FOS.dll",
  "entryPoint": "AzureFuncCreateLoad.CreateLoadMainFunction.Run"
}

**Comment by jvano** [comment]
Hi, 

Thanks for letting us know about this, the issue has been fixed and will be available in the next preview of "Azure Functions Runtime".

The error is that the default document should be function.json but we were using invalid.csx if run.csx or index.js are not found.

If you go to view files, you will be able to select other files like function.json.

**Comment by Deepul** [comment]
Thank you for the update, i do see the function.json file .
however the main issue i have is my pre-compiled function works on Azure cloud portal but is not working on runtime vm, yet the other functions with (.csx) file are fine its just pre-compiled function. its like pre-compiled functions cannot see the entry point or cannot run dll's.

**Comment by jvano** [comment]
Thanks for info. We will make sure the pre-compiled functions work as expected for the next preview.

**Comment by fabiocav** [comment]
@jvano what version of the runtime is packaged with Azure Runtime installer? Wondering if it's a version that did not have the pre-compiled support.

**Comment by shrishrirang** [comment]
@fabiocav - The preview is based off https://github.com/Azure/azure-webjobs-sdk-script/commit/a105cb45b02a893cf3bfdbd78daf6ae4addbc91b.

**Comment by fabiocav** [comment]
The capability was there at that point (introduced in 1.0.10690).

**Comment by jvano** [comment]
We have just recently announced "Azure Functions Runtime" preview 2
https://blogs.msdn.microsoft.com/appserviceteam/2017/12/05/announcing-azure-functions-runtime-preview-2/

In this version we have fixed this issue.
