### ISSUE TITLE
Improve error message for invalid connection property

### ISSUE THREAD

**Issue by tdykstra** [Azure/azure-webjobs-sdk-script#183]
If I try to put an actual connection string in the function.json connection property for a storage trigger/binding, as a customer might assume a property with that name could take, I get a generic “object not set” error.  

Microsoft.Azure.WebJobs.Host: Error indexing method 'Functions.QueueTriggerCSharp1'. Microsoft.Azure.WebJobs.Host: Object reference not set to an instance of an object.

It might be worth catching this error and returning something more helpful like “connection property is not a valid app setting key for a storage connection string”

**Comment by mathewc** [comment]
I'm doing this in my current changeset - I didn't notice that Fabio was assigned before I started.

**Comment by mathewc** [comment]
I've added an early validation for all "connection" properties - these will now result in descriptive function validation errors in the portal:

`Connection value 'DefaultEndpointsProtocol=https;AccountName=xxx;AccountKey=yyy' is invalid.`

**Comment by fabiocav** [comment]
:+1:
