### ISSUE TITLE
Custom extensions loading

### ISSUE THREAD

**Issue by fabiocav** [Azure/azure-webjobs-sdk-script#1837]
This issue tracks the work to address #1586, #1419  and #1395

From a runtime perspective, this feature is mostly supported by two major items:
### Extensions management API

- A new host API will be exposed, allowing clients (primarily the portal) to add, remove and list extensions
- This API will handle the restore process when handled by the host
- The host will trigger a publish for the artifacts 
- A custom build tool will process the output and generate an extensions metadata file (`extensions.json`), containing references to the extension types, with assembly hints, also pushing the binaries to the `bin` folder in the Function App's root.

### Runtime/extension loading 

- The runtime **will not** perform extensions installation as part of initialization or normal execution. That will all be handled by the aforementioned API
- The runtime will check for the presence of the `extensions.json` file in the `bin` folder in the Function App's root, if present, the references will be loaded and initialized as custom extensions.

**Comment by paulbatum** [comment]
This is now in the core branch.
