### ISSUE TITLE
Functions runtime fails to start if wwwroot folder is missing

### ISSUE THREAD

**Issue by davidebbo** [Azure/azure-webjobs-sdk-script#1838]
This came from [this forum thread](https://social.msdn.microsoft.com/Forums/azure/en-US/0e98c1a2-3b8e-4d8d-8859-30bcc317a9f7/deploying-azure-function-deployment-slot-via-arm?forum=AzureFunctions).

When creating a new slot, it initially doesn't have a `wwwroot` folder. This can be reproed easily using an ARM template (as in the forum post). The reason behind this is unclear, but the runtime should be able to handle this.

Right now, it dies with:

```
System.IO.DirectoryNotFoundException : Could not find a part of the path 'D:\home\site\wwwroot\host.json'.
   at System.IO.__Error.WinIOError(Int32 errorCode,String maybeFullPath)
   at System.IO.FileStream.Init(String path,FileMode mode,FileAccess access,Int32 rights,Boolean useRights,FileShare share,Int32 bufferSize,FileOptions options,SECURITY_ATTRIBUTES secAttrs,String msgPath,Boolean bFromProxy,Boolean useLongPath,Boolean checkHost)
   at System.IO.FileStream..ctor(String path,FileMode mode,FileAccess access,FileShare share,Int32 bufferSize,FileOptions options,String msgPath,Boolean bFromProxy,Boolean useLongPath,Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path,Boolean append,Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path,Boolean append,Encoding encoding,Int32 bufferSize,Boolean checkHost)
   at System.IO.File.InternalWriteAllText(String path,String contents,Encoding encoding,Boolean checkHost)
   at System.IO.File.WriteAllText(String path,String contents)
   at Microsoft.Azure.WebJobs.Script.ScriptHost.Initialize() at C:\azure-webjobs-sdk-script\src\WebJobs.Script\Host\ScriptHost.cs : 316
   at Microsoft.Azure.WebJobs.Script.ScriptHost.Create(IScriptHostEnvironment environment,IScriptEventManager eventManager,ScriptHostConfiguration scriptConfig,ScriptSettingsManager settingsManager) at C:\azure-webjobs-sdk-script\src\WebJobs.Script\Host\ScriptHost.cs : 937
```

This then causes "Function host is not running" when hitting the app.

All we need to do is make sure the folder exists before trying to create host.json.

**Comment by alrod** [comment]
As @davidebbo mentioned in [the forum thread](https://social.msdn.microsoft.com/Forums/azure/en-US/0e98c1a2-3b8e-4d8d-8859-30bcc317a9f7/deploying-azure-function-deployment-slot-via-arm?forum=AzureFunctions) for Azure Functions appsettings should be set up as part of app creation ([sample](https://github.com/davidebbo-test/FunctionArm/blob/0f92c687b95ad55af4a74f3bef2169f8f57b8160/azuredeploy.json#L27-L61)). I verified ARM template is working for production and development slot if appsettings are defined via the properties of the app.

**Comment by antmeehan** [comment]
Hi, I'm getting the same symptoms when deploying via ARM the first time. (Getting `Function host is not running.`). However the advice to combine the appsettings into the website resource isn't a viable workaround, since I also use the MSDeploy resource to deploy the actual function app binaries. MSDeploy can often fail since the siteconfig/appSettings values can interrupt the MSDeploy process (since it restarts w3p). Hence making the separate appSettings resource (with the appropriate dependencies to ensure no disruption of MSDeploy).

Thoughts?

**Comment by davidebbo** [comment]
> However the advice to combine the appsettings into the website resource isn't a viable workaround, since I also use the MSDeploy resource to deploy the actual function app binaries. MSDeploy can often fail since the siteconfig/appSettings values can interrupt the MSDeploy process

That should not be the case. Are you seeing this while creating new apps, or updating existing apps? And if the latter, do you see this when you care changing App Settings, or only updating content?

**Comment by antmeehan** [comment]
The example I could find was for an existing app, and the ARM template was using `properties/siteConfig/connectionStrings` and we received this failure:

> Deployment was interrupted and the process running it was terminated unexpectedly, if an ARM template is used, the likely cause is a race condition. To solve the race condition, make all resources that could potentially restart the site (app settings or site config changes for example) have a dependency on MSDeploy resource. For more info please read the information here: http://go.microsoft.com/fwlink/?LinkId=808141

So I moved to a separate `connectionString` resource with the dependencies suggested in the link.

**Comment by davidebbo** [comment]
Unfortunately, that's bad guidance in the case of Function Apps. So you only saw this issue when updating an existing app, right? And when you need, were you changing connection strings, or only updating content via msdeploy?

**Comment by antmeehan** [comment]
Yes it was updating an existing app. We deploy all resources every time via ARM. This particular deployment was updating a connection string for an existing app.

**Comment by davidebbo** [comment]
Yes, I think I understand how it could happen in that case. One workaround would be to use different ARM templates for the metadata (apps settings, ...) and for the content (msdeploy provider).

e.g. here is an [example](https://github.com/davidebbo/AzureWebsitesSamples/blob/master/ARMTemplates/MSDeployOnly.json) of a template that just does content deployment.
