### ISSUE TITLE
Azure Function Time Trigger does not accept valid CRON expression.

### ISSUE THREAD

**Issue by danielok1993** [Azure/azure-webjobs-sdk-script#1840]
I have encountered a weird issue while trying to create a schedule to run on first Sunday of every month: 0 0 0 1-7 * SUN#1.  Azure Functions tell me that this construct is wrong. 

The construct is actually correct as seen here: http://cronexpressiondescriptor.azurewebsites.net/, even the linked wiki page on the documentation page mentions that use of # is valid: " '#' is allowed for the day-of-week field, and must be followed by a number between one and five. ". Can someone explain why Azure Function does not allow the use of # or is there a different way of achieving this?

#### Investigative information

- Region: UK West

#### Repro steps

1. Create new Function
2. Enter CRON with # e.g. 0 0 0 1-7 * SUN#1
3. Yellow exclamation mark in the input box saying wrong CRON expression.

#### Expected behavior

The function should accept valid CRON expression.

#### Actual behavior

The function does not allow valid CRON expression.

#### Related information 

Documentation Page Wiki: https://en.wikipedia.org/wiki/Cron#CRON_expression

**Comment by mathewc** [comment]
We gave a workaround to this already.

**Comment by davidebbo** [comment]
Just use `0 0 0 1-7 * SUN`. The fact that you only want the first Sunday is already capture in the `1-7` for the day.
