### ISSUE TITLE
BUG: Cosmos DB bindings fail to connect to database unless the name of the connection string used in the binding has a "_DOCUMENTDB" suffix in it

### ISSUE THREAD

**Issue by alexmarshall132** [Azure/azure-webjobs-sdk-script#1843]
When binding to a Cosmos DB output, the function will fail after the function has completed and the binding attempts to send the output to the Cosmos DB instance UNLESS the name of the app setting for the Cosmos DB connection string has a "_DOCUMENTDB" suffix on it (i.e. as generated by the portal, rather than manually written by hand with some other naming scheme)

#### Investigative information

Please provide the following:

- Timestamp: 8/29/2017, 1:40:34 PM MST
- Function App name: <Censored>
- Function name(s) (as appropriate): StoreBillingRateCardMeter
- Invocation ID: 6784daf5-d63a-4676-baff-613bff861747
- Region: West US

#### Repro steps

Steps required to reproduce the problem:

Example: 

1. Create a new Azure Function BY HAND writing out the function.json and project.json files.
2. Add an output binding to a Cosmos DB instance, following the instructions [here](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-documentdb#docdboutput) but call the connection string "myconnection" (or something similar)

#### Expected behavior

 - After I complete the steps and run my function, my document should be successfully saved to the Cosmos DB instance.

#### Actual behavior

Example:

- After the function runs, instead of saving my document, I get an error similar to the following, where `storageItem` is the name of the `out` parameter:

`Error while handling parameter storageItem after function returned:Request url is invalid`

#### Known workarounds

Provide a description of any known workarounds.

- Add a "_DOCUMENTDB" suffix to the name of the connection string used for the Output Cosmos DB binding

#### Related information 

* Programming language used : C#
* Links to source : <Sorry, can't>
* Bindings used : Cosmos DB as output

**Comment by mathewc** [comment]
Likely a UI issue. Suffix being appended to connection string name.

**Comment by christopheranderson** [comment]
This issue was moved to Azure/azure-functions-ux#2214

**Comment by christopheranderson** [comment]
@paulbatum

 ![shame](https://media.giphy.com/media/Ob7p7lDT99cd2/giphy.gif)
