### ISSUE TITLE
Azure Proxy behaves oddly with {*rest}

### ISSUE THREAD

**Issue by StephenCleary** [Azure/azure-webjobs-sdk-script#1851]
Encountered an odd issue today with Azure Proxies.

If I have a proxy set up like this:

```json
{
    "$schema": "http://json.schemastore.org/proxies",
    "proxies": {
        "app": {
            "matchCondition": {
                "route": "{*url}"
            },
            "backendUri": "https://stephenclearyapps.github.io/DotNetApis/"
        },
        "api": {
            "matchCondition": {
                "route": "/api/{*url}"
            },
            "backendUri": "https://%WEBSITE_HOSTNAME%/api/{url}"
        }
    }
}
```

then it works fine. A request to [the root of my AF site](https://dotnetapis2.azurewebsites.net/) forwards the request to `https://stephenclearyapps.github.io/DotNetApis/` and all is well. Requests to non-root pages (e.g., `https://dotnetapis2.azurewebsites.net/bob`) also work fine and forward to the backend URI.

But if I change the wildcard from `{*url}` to `{*rest}` (literally, that's the *only* change):

```json
{
    "$schema": "http://json.schemastore.org/proxies",
    "proxies": {
        "app": {
            "matchCondition": {
                "route": "{*rest}"
            },
            "backendUri": "https://stephenclearyapps.github.io/DotNetApis/"
        },
        "api": {
            "matchCondition": {
                "route": "/api/{*url}"
            },
            "backendUri": "https://%WEBSITE_HOSTNAME%/api/{url}"
        }
    }
}
```

then it all falls apart. My AF site then returns the stock "Your Function App is up and running" page, and I cannot get the `app` proxy to run at all. Requests to non-root pages like `https://dotnetapis2.azurewebsites.net/bob` result in a 404.

The only change was to the name of a route wildcard variable. If `rest` is some kind of a reserved word, then we'd need documentation for that, and a runtime validation with good error message would be nice, too.

**Comment by mathewc** [comment]
What version of proxies are you using?

**Comment by safihamid** [comment]
This was a bug in one of the old versions of Proxy and has already been fixed.
