### ISSUE TITLE
Breaking change with regards to binding to HttpRequestMessage in addition to another parameter in new 2017 Azure Functions runtime

### ISSUE THREAD

**Issue by Shrulik** [Azure/azure-webjobs-sdk-script#1857]
I have a pre-compiled C# project, that used to work on the "1.0.0-alpha6" version of Microsoft.NET.Sdk.Functions, but fails on "1.0.2". At least locally, haven't deployed this change yet.

The tools version, if I run via CLI is : 
Azure Functions Core Tools (1.0.2)
Function Runtime Version: 1.0.11075.0

The gist is, I have a method of the form 
```C#
public class Bla {
          public static async Task<HttpResponseMessage> Run(HttpRequestMessage req,TraceWriter logger,
            [HttpTrigger(AuthorizationLevel.Anonymous, "post", Route = "verify")] SomePoco somePoco)
 {
 }
}
```

This used to work. Now I get : 
`
A ScriptHost error has occurred
Microsoft.Azure.WebJobs.Host: Error indexing method 'Bla.Run'. Microsoft.Azure.WebJobs.Host: Cannot bind parameter 'req' to type HttpRequestMessage. Make sure the parameter Type is supported by the binding. If you're using binding extensions (e.g. ServiceBus, Timers, etc.) make sure you've called the registration method for the extension(s) in your startup code (e.g. config.UseServiceBus(), config.UseTimers(), etc.).
`
Now, I understand that if I pick one, the HttpRequestMessage or the POCO, it would work, but I used to be able to do this, and it is useful, to be able to bind both the HttpRequestMessage object and a Poco object. I of course can't add two "HttpTrigger" attribute, because that is a different error. 
You can note there is no problem with the auto binding of the TraceWriter.

I have looked at the code, and found the relevant commit.
https://github.com/Azure/azure-webjobs-sdk-script/commit/4d112b27512a507028ded133bc9fde5a4cf259d2#diff-40e58d46cf9f76db0be4532a05758ab4R151

This change seems intentional. But why ? :( @mathewc 
I use the HttpRequestMessage in addition to the POCO to get access to HTTP headers, we use for tracking requests across several servers/services and passing around JWT tokens.

**Comment by TheeJamesLee** [comment]
Hi,

It is possible to get the headers and query strings by adding these to your signature;
            IDictionary<string, string> headers,
            IDictionary<string, string> query,

So I personally use the following approach;
POCO + headers and query dictionaries 99.9% of the time... HttpRequestMessage if I need something very specific and deserialize in the body.
When using the POCO I build the exact HttpResponseMessage I need to respond rather than using the HttpRequestMessage helpers (Had a Json serialization issue, but at least this way I know 100% what's going to be sent).

There is somewhere an issue that they are working on to bring back the HttpRequestMessage and POCO, but can't find it.  However the above should give you what you're after (POCO & Headers).

**Comment by Shrulik** [comment]
@TheeJamesLee Thanks for letting me know. I sort of understand the rationale, and maybe I'm biased against it because it is more work for me, but there are probably more scenarios where we might need HttpRequestMessage in addition to POCO. 

For example, another way I use the HttpRequestMessage, and I do this for every Http trigger, is to make sure the call is made via HTTPs #1228. Removing the auto binding on HttpRequestMessage basically means the POCO binding is unusable for me.  

In any case, this is still a breaking change, added via minor version, and should at least be documented before release ( Or is it already released ? ).

**Comment by TheeJamesLee** [comment]
I believe the change existed in the first GA release 1.0.0.  It did catch me out between the alpha6 and 1.0.0.

Yes, I agree both should be possible (why it changed between the alpha6 and GA I do not know) and as I said I know I have seen an issue somewhere else in the last 2 weeks where they say that they are correcting this.  If I find it I will link it here.

**Comment by MikeStall** [comment]
This is a duplicate of https://github.com/Azure/azure-webjobs-sdk-extensions/issues/273; 
It was regressed with https://github.com/Azure/azure-webjobs-sdk-script/issues/1508, and 
we have an outstanding fix that will go in the next release: https://github.com/Azure/azure-webjobs-sdk-extensions/pull/284

**Comment by Shrulik** [comment]
@MikeStall, great , good to know. When is this expected to be released? Will this be released as a nuget package only as part of v2.1.0-beta2 ? Not sure what I'm supposed to do until then ? Revert to alpha-6 maybe.

**Comment by Shrulik** [comment]
@MikeStall Any news ?

**Comment by christopheranderson** [comment]
@MikeStall - Mike can you confirm this has been released and then close? Otherwise, assign to Sprint 7 milestone.

**Comment by mathewc** [comment]
@MikeStall is this resolved?

**Comment by Shrulik** [comment]
@mathewc - Yes, this was solved and released to the public. I can confirm, since I ran the exact same code on version 1.0.4 without any issues.

**Comment by MikeStall** [comment]
Yes, this was resolved with https://github.com/Azure/azure-webjobs-sdk-extensions/issues/273
