### ISSUE TITLE
Azure Function not triggered by the Queue until I log into the Portal

### ISSUE THREAD

**Issue by feratur** [Azure/azure-webjobs-sdk-script#1858]
Hello!

I have a simple queue-triggered Azure Function, Consumption Plan. After the 1st of September I noticed a problem: after some period of inactivity the function goes into an idle mode and it's not woken up by the incoming messages.

In Azure Storage Explorer I see messages piling up in the queue and they start getting processed only after I log into the Azure portal and select my function on the Function Apps page. Only then the messages start getting dequeued (successfully, without any exceptions).

I deployed the function manually via a Portal UI, before the 01.09.2017 it worked correctly (as far as I know). The region is West Europe, an example of invocation id and time is:

> 2017-09-04T19:14:04.661 Function started (Id=a5d49caa-dd55-4b7d-ae99-bd9a3b3be8ae)

Please let me know if you need more information to investigate the issue.

Thanks!

**Comment by paulbatum** [comment]
@feratur I'm looking at our logs and I can confirm that something happened at 2017-08-30 15:06 UTC. For about 5 days after that, our infrastructure stopped monitoring your queue length. Then it resumed for a short time and stopped again. We're investigating but we've not seen a case like this before so it may take some time. Have you made any relevant changes to your function app in the last 8 days? Adding removing functions/triggers/etc?

**Comment by feratur** [comment]
Thanks for the reply, @paulbatum ! I haven't been making changes like those you described for the last 8 days, just very simple code alterations. I've also found a related issue: [https://github.com/Azure/azure-webjobs-sdk-script/issues/1240](url) but that one is already closed.

**Comment by paulbatum** [comment]
@feratur Sorry for the delay, it took us awhile to find the bug. We've determined that the scale controller instance that was responsible for your function app got stuck in a deadlock. Your app should be back to activating as per normal (not having to open the portal). We're working on a fix, but not sure yet if we'll manage to get in into the deployment that is starting this week or if it will have to wait for the next one. In the meantime, feel free to update this thread if you see your app go back into a bad state.

**Comment by feratur** [comment]
Thank you, @paulbatum , the app now seems to be working just fine! I'll keep monitoring, please, let me know when the final fix will be deployed, so we'll feel more confident to utilize Azure Functions at a greater scale.

**Comment by gopikrishnas** [comment]
We are also getting the same issue in our function
I deployed the function manually via a Portal UI. The region is EastUS2,  
Invocation id and time is:

> 2017-09-19T14:34:03.823 Function started (Id=c19d88e3-803a-4bd4-a658-554e4c94f5a4)

**Comment by paulbatum** [comment]
@feratur The fix for the deadlock issue that was impacting your app is now deployed.
