### ISSUE TITLE
System.Net.Http package

### ISSUE THREAD

**Issue by GreenAirplane** [Azure/azure-webjobs-sdk-script#1859]
Hello,

It looks like Azure Functions runtime uses the old version of System.Net.Http package (4.3.1). There is a security advisory #4021279 related to it: https://github.com/dotnet/corefx/issues/19535. Can we have it updated in the runtime to version 4.3.2 as it has required fixes?

In addition, this issue may affect azure functions which use newer package (e.g. IdentityModel). Link to a project an example project: [IdentityModelAzureFunctionIssue](https://github.com/GreenAirplane/IdentityModelAzureFunctionIssue)

**Comment by mathewc** [comment]
The effective version that we use at runtime is 4.0.0 (we have a binding redirect to this version) which comes with the .NET Fx and is serviced at that level.

**Comment by GreenAirplane** [comment]
Hi Mathew,

Yes, the effective version is 4.0.0 and it has these security issues (please check the following link with details: https://github.com/dotnet/corefx/issues/19535). As you can see, these security issues have been fixed in 4.0.1 and 4.3.1 versions.

Feel free to try the example from my previous post to see if it works for you or if I'm wrong in my assumptions regarding the issue.

**Comment by GreenAirplane** [comment]
The library has been updated in #1863. I've tested it today and looks like everything works now.
Thanks
