### ISSUE TITLE
Add switch to disable loading of custom extensions

### ISSUE THREAD

**Issue by davidebbo** [Azure/azure-webjobs-sdk-script#1878]
Right now, we always load these three things. From the logs:

```
Loaded custom extension: BotFrameworkConfiguration from ''
Loaded custom extension: SendGridConfiguration from ''
Loaded custom extension: EventGridExtensionConfig from ''
```

These are affecting cold start, and while we're not yet smart enough to lazy load them, let's add a new switch to manually disable loading them.

**Comment by davidebbo** [comment]
In addition, we should skip this initialization if we're in warm standby mode, since it is unnecessary and could also affect things.

**Comment by mathewc** [comment]
When in standby mode, we don't really need to optimize the startup path, and we also want to exercise as much as the pipeline as possible.

**Comment by davidebbo** [comment]
Ok, so let's ignore standby, and focus on a switch that takes effect during normal operations.

**Comment by mathewc** [comment]
Dynamic loading can now be enabled via the "EnableDynamicExtensionLoading" feature flag. See the [config wiki](https://github.com/Azure/azure-webjobs-sdk-script/wiki/Configuration-Settings) for details on how to use feature flags.

**Comment by davidebbo** [comment]
Ok, so specifically, we need to set `AzureWebJobsFeatureFlags=EnableDynamicExtensionLoading` as an App Setting. Correct?
