### ISSUE TITLE
Complete not called on async ServiceBus queue trigger when return type is Task

### ISSUE THREAD

**Issue by Shrulik** [Azure/azure-webjobs-sdk-script#1886]
Version info:
Azure Functions Core Tools (1.0.2)
Function Runtime Version: 1.0.11075.0

My experience is with the local tooling, I didn't deploy this code yet.

When creating a new Function with a ServiceBus queue trigger, if the entry point method is "async"
and returns a Task, as it should, it looks like Complete is not called on the message. The function runs and succeeds, but the message remains in the queue. This does create an infinite loop, but a pretty slow one, as it looks like the default polling delay is about 6 minutes.

Also looking at the queue in the portal, one can see the messages are left active.

Here is an example of an invocation id (Id=fdaae07c-7caa-4c9f-b7b4-bdba3fed7d9e)
, if that is what the value printed in the console is, of the queue triggered function running successfully,
 but not calling complete. 

#### Repro steps

<details>
<summary>Source</summary>

```csharp
  public static class MyFunctionApp
    {
        [FunctionName("Lala")]
        public static async Task Run(
            [ServiceBusTrigger("queue-name", AccessRights.Manage, Connection = "QU_CONNECTION")]
            SimulateEventMessage simulateEventMessage, ILogger logger)
        {
 
            await Something.Run(simulateEventMessage);
                        
        }
    }
```
</details>

#### Expected behavior

I expect the messages to be completed after a successful run. Preferably after several seconds of inactivity. Obviously stopping the function host doesn't work.

#### Known workarounds

If I change the entry point method to return a void rather than Task, it works, even though I do get a warning telling me I should return a Task from an async method, which in general I agree with.

**Comment by brettsam** [comment]
Can you share the `Something.Run` method also?

**Comment by brettsam** [comment]
I know that we've had some issues with ServiceBus and the local tooling recently. If possible, can you [run through these steps](https://stackoverflow.com/questions/46269046/azure-function-structure/46289792#46289792) to use the latest Functions CLI for running from Visual Studio?

**Comment by Shrulik** [comment]
My code has a bug that almost definitely caused this, I have also updated the tooling since then, so maybe both things were required. I was sure I had another example of this, but I haven't had the time to test it yet. I will close this for now, and reopen if I can recreate the bug without me being at fault.
