### ISSUE TITLE
ServiceBus extension is not BYOB compliant 

### ISSUE THREAD

**Issue by MikeStall** [Azure/azure-webjobs-sdk-script#1891]
Ensure that ServiceBus / EventGrid extensions can be loaded via BYOB. BYOB requires:
1. a public parameterless constructor on the event configuration object so that it can dynamically create the object. 
2. the config can self-initialize from host.json.

**Comment by MikeStall** [comment]
Hit this here: https://github.com/Azure/azure-functions-vs-build-sdk/issues/97#issuecomment-323482634

**Comment by mathewc** [comment]
As part of addressing this, we should also proactively verify that all the other extensions ARE compliant. We'll be allowing people to opt in to dynamic extension loading, so we need to be sure that all the extensions work in that mode.

**Comment by paulbatum** [comment]
@alrod took care of service bus and I think @watashiSHUN did the same for eventgrid. closing.
