### ISSUE TITLE
[c#]No warnings if there are duplicate binding arguments

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-webjobs-sdk-script#190]
Repro step:
1. Create QueueTrigger C#
2. Add input binding : documentdb
3. Add output binding : documentdb

This adds documentdb input and output bindings with  "name": "document"

Expected: Warning indicating duplicate names

**Comment by mathewc** [comment]
What is the behavior at runtime in this scenario? We need to handle it well in the runtime, but the Portal needs to avoid getting people into this situation in the first place. I.e., it needs to use unique names for bindings. Recommend creating a portal bug for that.

**Comment by mathewc** [comment]
This has been fixed.
