### ISSUE TITLE
Support Connection for ServiceBus binding as well

### ISSUE THREAD

**Issue by mathewc** [Azure/azure-webjobs-sdk-script#192]
When we did multi-connection support for Queues/Blobs/Tables, we left it as a TODO to also do for ServiceBus. PR here: https://github.com/Azure/azure-webjobs-sdk-script/pull/128

We need to respect the Connection property for ServiceBus as well and emit the [ServiceBusAccount] attribute.

**Comment by paulbatum** [comment]
David and I have made the call to yank service bus from beta. This applies for the template, the trigger binding (they might need to be deleted tempoarily because i dont think we have a way to hide them right now), and we'll take this script PR post beta.

**Comment by mathewc** [comment]
I just tested this PR and it works end to end. However, if you want to take post beta that is fine.

**Comment by mathewc** [comment]
Fixed
