### ISSUE TITLE
Node - let triggers consume return values. 

### ISSUE THREAD

**Issue by MikeStall** [Azure/azure-webjobs-sdk-script#1921]
Fix return values for Node. 
This is an extension of https://github.com/Azure/azure-webjobs-sdk-script/issues/1422  
1422 fixed C# and removed the ICanProcessResult interface and some related hackery. 

Node does it differently - it handles return values by treating them as Out parameters. Ie, this : 
```
  ctx.done(null, retVal);
```
is the same as this:
```
   ctx.outBinding = retVal
```
And both generate an out parameter in C#. That means that a trigger binding doesn't receive the return value. 

Http copes with this by having a special Out binding for HTTP  that ties back to the trigger.  However, this misses the case where triggers require a return value and doesn't generalize to other triggers. .  

We should do some scheme in the function.json to specify that the return value should be applied to the trigger.   This means that the generated C# wrapper truly has a return value, and not just `out T` . 

A proposal is if the function.json binding has type = trigger type  and name = $return, then we know the binding is actually applied to the return value.

**Comment by MikeStall** [comment]
Chatted with @mathewc  - a tentative idea for function.json encoding is to add a flag to the trigger binding metadata.

**Comment by kashimiz** [comment]
Addressed by #2049 and Azure/azure-webjobs-sdk#1424.
