### ISSUE TITLE
Migrate from project.json to MSBuild (project) format

### ISSUE THREAD

**Issue by fabiocav** [Azure/azure-webjobs-sdk-script#1928]
Work item to track migration from `project.json` to the MSBuild project format for package references.

**Comment by dersia** [comment]
Just to get a better understanding for this issue, does this mean, that one as to upload a functionname.csproj file for package-references? 

If so, I think this could be very confusing, maybe it's better to come up with a new file name and just use the same structure as the MSBuild project format:

```package.references```:
```
<ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="2.0.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="2.0.0" />
  </ItemGroup>
```

and will it support conditions?

**Comment by fabiocav** [comment]
The file name is still TBD (that's why it wasn't mentioned here).

It will, _at least_, support framework target conditions.

**Comment by paraspatidar** [comment]
Can we open this issue , if the File name is still in TBD ?

**Comment by fabiocav** [comment]
This was done here: https://github.com/Azure/azure-functions-host/pull/2002

This was a dupe and unfortunately didn't get updated with that information. The file name is `function.proj`
