### ISSUE TITLE
Investigate tracewriter contention in core

### ISSUE THREAD

**Issue by mamaso** [Azure/azure-webjobs-sdk-script#1942]
https://ci.appveyor.com/project/appsvc/azure-webjobs-sdk-script-y8o14/build/2.0.11278-chnkebcd/tests

> 
> System.AggregateException : One or more errors occurred. (Index was outside the bounds of the array.) (The following constructor parameters did not have matching fixture data: TestFixture fixture)
> ---- System.IndexOutOfRangeException : Index was outside the bounds of the array.
> ---- The following constructor parameters did not have matching fixture data: TestFixture fixture

**Comment by mathewc** [comment]
Are you sure this is Core only?

**Comment by brettsam** [comment]
We no longer have TraceWriter in core, so closing this. Will reactivate if we see this again.
