### ISSUE TITLE
First request to function endpoint may result in a 404

### ISSUE THREAD

**Issue by fabiocav** [Azure/azure-webjobs-sdk-script#1944]
If the first request to the runtime (cold) is to a function endpoint, the function may not be correctly resolved, resulting in a 404.

**Comment by SimonLuckenuik** [comment]
I get that behavior 100% of the time.

**Comment by AdamAbonyi** [comment]
Me too

**Comment by snobu** [comment]
Is there a temporary workaround for this one? It's really breaking a lot of use cases, think using Functions to process an intent for an Alexa Skill - the timeout is around 5 second there and there is no retry for 404s.

**Comment by fabiocav** [comment]
This should be resolved in the next deployment.
