### ISSUE TITLE
Table storage input binding "PartitionKey" value in binding.json has no effect

### ISSUE THREAD

**Issue by soninaren** [Azure/azure-webjobs-sdk-script#195]
**Binding**
{
      "tableName": "workitems",
      "partitionKey": "AAA",
      "take": 50,
       "filter" : "true",
      "connection": "azurefunctions4316cc3b_STORAGE",
      "name": "myTable",
      "type": "table",
      "direction": "in"
   }

**Data**
PartitionKey    RowKey    Status
AAA               0001         0
AAA               0002         1
AAB               0001         0

**Result**
[{"status":"0"},{"status":"1"},{"status":"0"}]

**Comment by fabiocav** [comment]
Can you also add your sample function code here? Was this using Node?

**Comment by soninaren** [comment]
yes 

module.exports = function (context,myQueueItem ,myTable) {    
    context.log('Node.js function with table storage input:',myTable);
    context.done();
};

**Comment by mathewc** [comment]
Well, we're passing the PK to the TableAttribute we bind to (code [here](https://github.com/Azure/azure-webjobs-sdk-script/blob/master/src/WebJobs.Script/Binding/TableBinding.cs#L163)). Might be a core SDK issue. Not sure until we debug into the repro scenario.

**Comment by mathewc** [comment]
FYI - I'm going to be reviewing this entire binding and doing some rework.

**Comment by mathewc** [comment]
No repro. I'm able to specify PK/RK in my function.json, and get back the expected single record.

**Comment by soninaren** [comment]
I was getting all the records if i only mention partition key. Let me try and see i can still get a repro.

**Comment by mathewc** [comment]
Ah, I see. Yes, I see that too. I misread thinks and thought the issue was RK had no effect.
