### ISSUE TITLE
Node Http Request : Provide access to raw request body

### ISSUE THREAD

**Issue by jordanyaker** [Azure/azure-webjobs-sdk-script#1951]
With the latest release, the changes made to resolve #293 have been undone and `context.req.rawBody` is no longer accessible.

#### Repro steps

Provide the steps required to reproduce the problem:

Example: 

1. Setup a basic Node HTTP function.
2. Examine the contents of context.req or the request argument supplied to the handler.

#### Expected behavior

Find `context.req.body` as well as `context.req.rawBody`.

#### Actual behavior

Only find the `context.req.body` property.

#### Known workarounds

None.  This is probably a breaking change for many applications.

**Comment by mamaso** [comment]
@jordanyaker We're considering moving to a model where you natively handle the http request inside of node, aka you're actually operating on a Http.IncomingMessage object

This would mean that you interact with the body as a byte[] or byte stream, and could use modules such as body parser in order to handle the content.

That said, I can enable the `rawBody` property for now.

**Comment by jordanyaker** [comment]
I wouldn't hate on having to manually handle the stream.  That allows easier adaptation to a variety of scenarios and an enterprising person could easily create an NPM package to act as a middleware for people who need a default "parse and go" scenario.

In the short term, I appreciate you tackling the simple re-addition of the `rawBody` property since this is a breaking change for us (we do checksum evaluation on message bodies) .

**Comment by mamaso** [comment]
Sounds like a compromise - I'll get that into the next release and update you on future plans. Thanks for the issue / feedback!

**Comment by jordanyaker** [comment]
Thanks, @mamaso!

**Comment by mathewc** [comment]
Is this issue talking about the .NET Core preview version of the runtime? We haven't made any breaking changes to the programming model in our official version.

**Comment by mamaso** [comment]
Yep, this is in the 2.0 beta host - I'll add an appropriate label

**Comment by mathewc** [comment]
@mamaso What's the status on this?

**Comment by christopheranderson** [comment]
Note from punting: PR ready to merge

**Comment by fabiocav** [comment]
Resolved by a97d137
