### ISSUE TITLE
How to construct the authorization to use Azure function Key management API

### ISSUE THREAD

**Issue by wxtom** [Azure/azure-webjobs-sdk-script#1952]
I want to use the Key management API that mentioned in the [document](https://github.com/Azure/azure-webjobs-sdk-script/wiki/Key-management-API). But can't find a way how to construct  the authorization to use those APIs?

**Comment by wxtom** [comment]
I have got the answer from the following link.
https://stackoverflow.com/questions/46338239/retrieve-the-host-keys-from-an-azure-function-app/46436102#46436102

The key point is that we could  get a JWT with Kudu API creds

var webFunctionAppName = "functionName";
            var username = "ftpuserName";
            var password = "password";
            var base64Auth = Convert.ToBase64String(Encoding.Default.GetBytes($"{username}:{password}"));
            var apiUrl = new Uri($"https://{webFunctionAppName}.scm.azurewebsites.net/api");
            var siteUrl =new Uri($"https://{webFunctionAppName}.azurewebsites.net");
            string JWT;
            using (var client = new HttpClient())
            {
                client.DefaultRequestHeaders.Add("Authorization", $"Basic {base64Auth}"  );

                var result = client.GetAsync($"{apiUrl}/functions/admin/token").Result;
                JWT = result.Content.ReadAsStringAsync().Result.Trim('"'); //get  JWT for call funtion key
            }
            using (var client = new HttpClient())
            {
                client.DefaultRequestHeaders.Add("Authorization", "Bearer "+JWT);

                var key = client.GetAsync($"{siteUrl}/admin/functions/test/keys").Result.Content.ReadAsStringAsync().Result;
            }

**Comment by markheath** [comment]
Would be great if the docs were updated to include this information. Took me a long time to find this.
