### ISSUE TITLE
Functions: errors in function.json

### ISSUE THREAD

**Issue by CentricStraaten** [Azure/azure-webjobs-sdk-script#1966]
In the function.json document there are 2 properties (generatedBy and configurationSource) that show a _**property not allowed warning**_. Because of this warning i cannot switch to the integration Standard Editor.

Removing the 2 properties enables the Standard Editor but breaks the function.

- Timestamp: any
- Function App name: cencept-functions
- Function name(s) (as appropriate): any
- Invocation ID: 
- Region: West-Europe

West Europe
--

West Europe
--

#### Repro steps

Provide the steps required to reproduce the problem:

#### Expected behavior

Provide a description of the expected behavior.

#### Actual behavior

Provide a description of the actual behavior observed.

#### Known workarounds

Provide a description of any known workarounds.

#### Related information 

Provide any related information 

* Programming language used 
* Links to source
* Bindings used

**Comment by mathewc** [comment]
Move to portal - appears to be a portal issue.

**Comment by paulbatum** [comment]
This issue was moved to Azure/azure-functions-ux#1862

**Comment by paulbatum** [comment]
This issue was moved to Azure/azure-functions-ux#1863
