### ISSUE TITLE
Allow binding metadata to specify a Type

### ISSUE THREAD

**Issue by mathewc** [Azure/azure-webjobs-sdk-script#197]
For all languages other than C# (where the user can control the bound Type via their function signature), we need a way to allow the type to be specified in metadata. Currently we default to a particular type that will cover the 90% case (e.g. queues bind to string, blobs bind to a string, etc.). However, what if a Node.js function wants to bind to a Buffer rather than a string (e.g. in the image resize scenario)?

This might look like the below (a new "dataType" property).

```javascript
{
  "bindings": [
    {
      "type": "blobTrigger",
      "direction": "in",
      "dataType": "byte",
      "path": "samples-input/{name}"
    }
  ]
}
```

**Comment by christopheranderson** [comment]
Let's think through the right place for the type info to come through
