### ISSUE TITLE
Test Infrastructure for all languages/bindings

### ISSUE THREAD

**Issue by mathewc** [Azure/azure-webjobs-sdk-script#198]
We currently have spotty e2e coverage across all the languages and binding types, meaning we have to do manual testing to make sure we haven't broken things.

We need to get e2e tests in place for all scenarios, as well as unit tests that can efficiently test all bindings/permutations.

**Comment by christopheranderson** [comment]
RC Justification: Important for quality/reliability to have e2e tests.
