### ISSUE TITLE
Remove parameter description code duplication across C#/Script

### ISSUE THREAD

**Issue by mathewc** [Azure/azure-webjobs-sdk-script#199]
Currently CSharpFunctionDescriptionProvider overrides CreateTriggerParameterDescriptor and its logic just to override the parameter type. This is error prone - e.g. whenever we add a new trigger type we have to remember to add in multiple places.

We might instead move to a model where all this core logic stays in the base class, and there is an overrideable method to configure each parameter. This would allow the C# provider to update only what it needs.

**Comment by fabiocav** [comment]
@mathewc, @christopheranderson I'm moving this to the current milestone since it is one of the items I'll need to address as part of the work I'm doing. Please let me know if you have any concerns.

**Comment by fabiocav** [comment]
Reopened... didn't mean to close the issue.
