### ISSUE TITLE
CosmosDBTrigger: Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by sanjaybhagia** [Azure/azure-webjobs-sdk-script#1992]
When I try to execute newly created azure function with CosmosDBTrigger, I get the above exception for the function with cosmosdb trigger

#### Investigative information
**Environment:** 
Visual Studio 2017 15.3.5

**Packages referenced:** 
Marvin.JsonPatch.Dynamic" Version="1.1.0"
Microsoft.Azure.DocumentDB" Version="1.17.0"
Microsoft.Azure.WebJobs" Version="2.1.0-beta4"
Microsoft.Azure.WebJobs.Extensions.DocumentDB"
Microsoft.Azure.WebJobs.ServiceBus" Version="2.0.0"
Microsoft.NET.Sdk.Functions" Version="1.0.5" 
Newtonsoft.Json" Version="10.0.3"
System.Configuration.ConfigurationManager" Version="4.4.0"

I can't upgrade Microsoft.Azure.WebJobs package to latest version as it conflicts with ServiceBus package, so i had to bring it back to the version which worked for me. 

So if i try to upgrade Microsoft.Azure.WebJobs to v3.0.0-beta3 and ServiceBus to v2.1.0-beta4, and then build my project i get this error:

Could not load file or assembly 'Microsoft.Azure.WebJobs, Version=2.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.

#### Repro steps

Provide the steps required to reproduce the problem:

1) Create a new Azure Function Project from Visual Studio
2) Add a function (i didn't find any option for CosmosDB Binding so i created using HttpTrigger)
once the .cs file is created, replace the file with the code that i have put below. 
3) Build
4) Hit F5

#### Expected behavior
The host should run without any problem

#### Actual behavior
Host throws an error Object reference not set to an instance of an object for CosmosDBTrigger

#### Code
```csharp
namespace Rentamera.Serverless.Functions
{
    public static class AddEventInEventStore
    {
        [FunctionName("AddEventInEventStore")]
        public static void Run([CosmosDBTrigger("db", "Items",
            ConnectionStringSetting = "AzureWebJobsDocumentDBConnectionString",
            LeaseCollectionName = "leases", LeaseDatabaseName = "db"
            )]
            IReadOnlyList<Document> changeList, TraceWriter log)
        {
            if (changeList != null && changeList.Count > 0)
            {
                log.Verbose("Documents modified " + changeList.Count);
                foreach (var change in changeList)
                {
                    log.Verbose("First document Id " + change.Id);
                }
            }

        }
    }
}
```

**Comment by sanjaybhagia** [comment]
It was infact the tooling issue. I was running Azure Functions cli 1.0.0, so i updated it to 1.0.4 and it worked for me. I got this help from stackoverflow (https://stackoverflow.com/questions/46559852/cosmosdbtrigger-object-reference-not-set-to-an-instance-of-an-object/46560879#46560879).

**Comment by AldoSaucedo** [comment]
Hi @sanjaybhagia 
Are you using Microsoft.Azure.WebJobs to v3.0.0-beta3?
if so, How did you fix this error?
Could not load file or assembly 'Microsoft.Azure.WebJobs, Version=2.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.

I need Microsoft.Azure.WebJobs.Extensions.AuthTokens
[https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.AuthTokens/](url)
 but it needs Microsoft.Azure.WebJobs to v3.0.0-beta3

Thanks!
