### ISSUE TITLE
Functions Proxy with route as "add?a={a}&b={b}" is not working on Proxy version ~0.3 but same is working with Proxy Version ~0.2

### ISSUE THREAD

**Issue by brettsam** [Azure/azure-webjobs-sdk-script#1993]
Ported from an internal CRI.

From CRI: "I think maybe the latest version is not supporting the "?" in the route template as suggested here in the link it's a reserved character. Not sure though."

Sample proxies.json
```
{
    "$schema": "http://json.schemastore.org/proxies",
    "proxies": {
        "AdditionProxy": {
            "matchCondition": {
                "route": "add?a={a}&b={b}",
                "methods": [
                    "GET"
                ]
            },
            "backendUri": "https://{site].azurewebsites.net/api/Addition?code={code}&summand1={a}&summand2={b}",
            "requestOverrides": {
                "backend.request.querystring.a": "",
                "backend.request.querystring.b": ""
            }
        }
    }
}
```

**Comment by safihamid** [comment]
Going forward the proxy routes must follow the asp.net route constraints but you can easily change the above proxy to below to get the same results:

        "AdditionProxy": {
            "matchCondition": {
                "route": "add",
                "methods": [
                    "GET"
                ]
            },
            "backendUri": "https://[your site].azurewebsites.net/api/Addition",
            "requestOverrides": {
                "backend.request.querystring.summand1": "request.querystring.a",
                "backend.request.querystring.summand2": "request.querystring.b",
                "backend.request.querystring.a": "",
                "backend.request.querystring.b": ""
            }
        }

**Comment by christopheranderson** [comment]
re @safihamid: by design
