### ISSUE TITLE
HttpTrigger Request Processing

### ISSUE THREAD

**Issue by mathewc** [Azure/azure-webjobs-sdk-script#20]
Need to clean up the whole binding pipeline for incoming HttpRequests, including:

- support for body types other than json (e.g. form url encoding, etc.)
- proper content type support + content negotiation

**Comment by christopheranderson** [comment]
Might need to split this up to be less vague. Need to try to think of what breaking changes need to be done for rc, but additive changes should be reviewed. Example: Adding support for say wwwurlencoded is nice, but not a breaking change and could come in an additive update.

**Comment by mathewc** [comment]
Closing this old issue since it is too general. We've made many improvements already since we created this. We'll address required changes as they're reported in new issues.
