### ISSUE TITLE
Respect TraceLevel across all TraceWriters

### ISSUE THREAD

**Issue by mathewc** [Azure/azure-webjobs-sdk-script#201]
You can currently specify a TraceLevel in host.json (tracing.consoleLevel). We also have a knob for disabling file logging (log streaming). We need to make all these various knobs consistent, and make sure we honor them in all the TraceWriters we use in the runtime.

E.g. currently the FileTraceWriter we use for log streaming doesn't have a configurable trace level.

Ultimately we'll want portal UI allowing people to configure these trace levels, and that UI will build on these settings.

**Comment by mathewc** [comment]
Looked into this some: we need to pass the configured TraceLevel into the FileTraceWriter we're using for the host - currently we default it to Verbose. Then, we also need to review the trace calls emitted by the various invokers - most of them are Verbose, meaning once the default level is Info, we won't see anything. E.g. function starting/completed logs need to be Info level, not Verbose.

**Comment by fabiocav** [comment]
Are you also planning to have logging that is currently using the Host's trace writer also output to a trace writer passed in the host config?

**Comment by mathewc** [comment]
Huh? Please elaborate your query :)

**Comment by fabiocav** [comment]
I just re-read my question and even I can't understand what I was asking :) It has been one of those days.

Take 2:

Currently, the `ScriptHost` creates it's own trace writer based on whether file logging is enabled. All logging done by the `ScriptHost` uses that writer and **not** the trace writer passed in using the `ScriptHostConfiguration` instance provided when the `ScriptHost` is instantiated. Which makes both, testing as well as passing a `TraceWriter` from the hosting application (e.g. the Console host), difficult. Ideally we'd **also** output to that writer if provided.

I hope this makes more sense :)

**Comment by mathewc** [comment]
@fabiocav Regarding your question - I've actually removed the TraceWriter from ScriptHostConfiguration since all we were doing with that was adding it to the JobHostConfiguration tracers collection. That can be done already, and I've refactored the test code to do that.

If we have additional trace requirements, lets track those separately.
