### ISSUE TITLE
Azure Functions Proxies doesn't work with URL as "key" for proxy

### ISSUE THREAD

**Issue by christopheranderson** [Azure/azure-webjobs-sdk-script#2010]
If you provide a URL as the key for a proxy (the name for the proxy rule), it fails to load the rule with no errors.

Repro:
Provide a URL like "https://bing.com/" and the rule won't load

**Comment by safihamid** [comment]
This is actually happening if proxy name has '.' in it and we are getting a null ref exception from WebJobs Core SDK, here is the callstack:

   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.NotifyCompleteAsync(FunctionInstanceLogEntry intanceLogEntry, IDictionary`2 arguments, ExceptionDispatchInfo exceptionInfo) in D:\GIT\azure-webjobs-sdk\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 757

instanceLogEntry is null:
intanceLogEntry.LiveTimer.Stop();

@mathewc is it expected? proxy names are ok to have '.' in them.

**Comment by safihamid** [comment]
Talked to few people and proxy names should follow the same naming restrictions as function names.
Opened this against the portal: https://github.com/Azure/azure-functions-ux/issues/1878

**Comment by safihamid** [comment]
This is already fixed and deployed to prod.
