### ISSUE TITLE
Support GZip in Azure Blob Extract step

### ISSUE THREAD

**Issue by brianbruff** [Azure/azure-webjobs-sdk-script#2013]
While trying to unzip an Azure Blob to Folder I discovered that zip format is supported but now gzip (.gz)

#### Investigative information

Please provide the following:

- Timestamp:  10/9/2017, 9:21 PM
- Function App name:  CME Loader Logic App
- Function name(s) (as appropriate): Extract Archive To Folder (azure blob)
- Invocation ID: 08586940263950584433408756882
- Region: North Europe

#### Repro steps

Create a Logic App that triggers when a blob arrives in a storage account.
Upload a .gz zip file (gzip format)

#### Expected behavior

Expect file to be unzipped

#### Actual behavior
"message": "Unable to extract contents of file"

#### Known workarounds

Will create an Azure function

**Comment by christopheranderson** [comment]
This sounds like a feature for Logic Apps... Could you expand upon the issue? Is this actually a Functions issue?

**Comment by brianbruff** [comment]
ok thanks for closing, this is a logic apps issue not azure functions, apologies

**Comment by Compunick** [comment]
Hey brianbruff,  was your unzip Azure Function successful?  Will you share that code?  I have a similar issue unpacking password protected .zip with logicApp.  - Thanks
