### ISSUE TITLE
File trace writer not properly logging messages with line breaks

### ISSUE THREAD

**Issue by fabiocav** [Azure/azure-webjobs-sdk-script#2020]
Observed this with the Node worker, so there seems to be a behavior change, when running the `NodeEndToEndTests.Scenario_Logging`, but this may not be directly related to Node (or the new OOP workers logic) and some change in bahevior there might have caused the problem to surface.

When running the `logging` scenario, a log entry object is created, the runtime is currently splitting every property into its own entry, as opposed to a serializing the value as expected.

Disabling the test until this is resolved.

**Comment by christopheranderson** [comment]
Narrowing it down to us reading in the log file and the log file keeping the line endings that will come from the JSON object toString'd. 

I modified the test helper to just condense the lines into a single log to make testing easier. There was still an off by 1 issue, so I'm not sure if we originally expected an additional log or now, but we're not testing it, so just adjusted the index.
