### ISSUE TITLE
Storage table bindings failing with pre-compiled Azure Functions project

### ISSUE THREAD

**Issue by APErebus** [Azure/azure-webjobs-sdk-script#2027]
We've been using pre-compiled app to deploy our azure functions project (due to the built-in tooling not being ready in time) but we've run into an issue when adding new functions that bind to table storage.

The code was ported from existing webjobs that had the same table bindings, however it's now failing on host startup.

The errors are:

`GenericArguments[0], 'OurTableEntity', on 'Microsoft.Azure.WebJobs.Host.Tables.TableExtension+TableToIQueryableConverter`1[TElement]' violates the constraint of type parameter 'TElement'.`

and

`Can't bind Table to type 'Microsoft.WindowsAzure.Storage.Table.CloudTable'.`

For the GenericArgs issue, here's the relevant info (anonymized):

```
public class OurEntity : TableEntity
{
    //Properties are here
}
```

```
{
  "disabled": false,
  "scriptFile": "..\\bin\\OurFunctions.dll",
  "entryPoint": "OurFunctions.TheFunction.Run",
  "bindings": [
    {
      "type": "serviceBusTrigger",
      "name": "message",
      "topicName": "ourTopic",
      "subscriptionName": "ourSubscription",
      "connection": "App.ServiceBus.ConnectionString",
      "accessRights_": "Manage",
      "direction": "in"
    },
    {
      "type": "table",
      "name": "ourTable",
      "tableName": "ourEntities",
      "connection": "App.Storage.ConnectionString",
      "direction": "in"
    },
    {
      "type": "serviceBus",
      "name": "results",
      "queueName": "ourOtherQueue",
      "connection": "App.ServiceBus.ConnectionString",
      "accessRights_": "Manage",
      "direction": "out"
    }
  ]
}
```
`public static async Task Run(string message, IQueryable<OurEntity> ourEntities, IAsyncCollector<OutObj> results, TraceWriter log, CancellationToken token)`

and with the cloud table error, I'm just binding to a `CloudTable` object as an input.

My guess is that it's a WindowsAzure.Storage DLL mismatch. I downgraded to v7.2.1 and am testing it.

I'm surprised there isn't any assembly binding redirects working.

**Comment by APErebus** [comment]
Just an update, downgrading to WindowsAzure.Storage v 7.2.1 fixed the issue.

I don't consider this a resolution, just a workaround.

**Comment by dallancarr** [comment]
The latest azure function runtime pins to 7.2.1...so webjob package version 2.0.0 should be fine

**Comment by paulbatum** [comment]
Yes its expected behavior that you need to use Storage 7.x when running on functions 1.x.

**Comment by DerekLiang** [comment]
@APErebus I ran into the same issue. How do you manage to make it work? I think I don't understand what you meant by downgrade the package to 7.2.1. There is no other dll reference in the project other than Microsoft.NET.Sdk.Functions.

**Comment by dallancarr** [comment]
What version of Microsoft.NET.Sdk.Functions are you targeting?

**Comment by DerekLiang** [comment]
I am using 1.0.6 version of Microsoft.NET.Sdk.Functions.

**Comment by dallancarr** [comment]
What version mismatch are you getting? Open new issue.
