### ISSUE TITLE
C#: Dependencies-of-dependencies not resolved correctly

### ISSUE THREAD

**Issue by brettsam** [Azure/azure-webjobs-sdk-script#204]
Example: Try adding Twilio as a nuget reference and when running you'll get 'RestSharp not found' errors. This affects nuget references as well as sticking both dependencies in the private /bin directory. 

@fabiocav has a lead already on the issue -- filing this to track.

**Comment by Youngr6** [comment]
I think I'm seeing this too not using nuget - so I'm able to #r my private/bin assembly, but if that references another private bin assembly it cant load it, event if I #r it in the function.

**Comment by fabiocav** [comment]
@Youngr6,  thanks  for  reporting  that! The issue is caused by the same defect impacting @brettsam. I have a fix for it in test and will have a PR out soon.
