### ISSUE TITLE
Add logger section to host.json schema

### ISSUE THREAD

**Issue by alrod** [Azure/azure-webjobs-sdk-script#2041]
![image](https://user-images.githubusercontent.com/2578359/31680322-d3682f84-b328-11e7-8e8e-cfdf8d13a251.png)

**Comment by alrod** [comment]
Related portal issue: https://github.com/Azure/azure-functions-ux/issues/1884

**Comment by brettsam** [comment]
This is now in `dev` and `v1.x` and the schemastore PR is out: https://github.com/SchemaStore/schemastore/pull/371
