### ISSUE TITLE
EventHub output binding not generating correct Function.json

### ISSUE THREAD

**Issue by bryantharpe** [Azure/azure-webjobs-sdk-script#2050]
When trying to create an Azure function with an out parameter to EventHub it is not generating the function.json as expected. The EventHub output binding does not get added.

I've tried this on 15.3.x and 15.4.1 with similar results.

````csharp
    public static class TestFunc
    {
        [FunctionName("TestFunc")]
        public static void Run([ServiceBusTrigger("testtopic", "testsub", AccessRights.Manage, Connection = "Endpoint=sb://...")]string mySbMsg, TraceWriter log, [EventHub("MyEventHub", Connection = "Endpoint=sb://...")]out string returnValue)
        {
            returnValue = mySbMsg;

            log.Info(returnValue);
        }
    }
````

I've tried by referencing connection via an AppSetting name as well as a hard coded connection. The output json only recognizes the ServiceBusTrigger:

Generated Function.json
````json
{
  "generatedBy": "Microsoft.NET.Sdk.Functions-1.0.0.0",
  "configurationSource": "attributes",
  "bindings": [
    {
      "type": "serviceBusTrigger",
      "connection": "Endpoint=sb://...",
      "topicName": "testtopic",
      "subscriptionName": "testsub",
      "accessRights": "manage",
      "name": "mySbMsg"
    }
  ],
  "disabled": false,
  "scriptFile": "..\\bin\\Test.dll",
  "entryPoint": "Test.TestFunc.Run"
}
````

**Comment by paulbatum** [comment]
This is actually expected behavior and is true of all output bindings when you're working with VS. This is because the runtime will load and use the attributes directly. The reason the trigger is present in the json file is that we need other systems to be able to easily access this metadata to drive processes such as monitoring queue length.

Is your function failing to write to the event hub?

**Comment by bryantharpe** [comment]
Thanks for the comments. I was assuming inputs and outputs both ended up there. It was failing to write to event hub when it was running as a consumption plan. For now I changed it to an always on S1 and it's writing fine to event hub. I'm going to spend some more time looking into that, though.

Closing this issue out as the file is generated as expected.

**Comment by paulbatum** [comment]
@bryantharpe thanks for the update. I'm not aware of any issues that would likely explain the problem you encountered in the consumption plan, so please feel free to file another issue if it still repros for you.
