### ISSUE TITLE
NodeJS worker response header Content-Type is overwritten after send

### ISSUE THREAD

**Issue by nelak** [Azure/azure-webjobs-sdk-script#2053]
NodeJS worker response header Content-Type is overwritten after send.
This only happens if `; charset=utf-8` is missing

#### Repro steps

``` js
context.res.setHeader('content-type', 'text/html')
context.res.setHeader('content-length', `${Buffer.from(htmlContent).length}`)
context.res.raw(htmlContent)
```

#### Expected behavior

Returned `content-type` should be `text/html`

#### Actual behavior

Returned `content-type` should is `text/plain`

**Comment by paulbatum** [comment]
@nelak is this for functions v1 or v2?

**Comment by nelak** [comment]
@paulbatum Happens when using the v2 runtime.
My guess is that it is happening at the WebHost or further down but I was never able to find where the response passes back to the client.
