### ISSUE TITLE
When using {*code} I get: Bad Request

### ISSUE THREAD

**Issue by nduijvelshoff** [Azure/azure-webjobs-sdk-script#2054]
Hi There,

Right now I'm having issues with my routes (proxies.json), when I have a matching rule with * in it nothing works anymore. Anyone an idea of what I'm doing wrong?

```{
    "$schema": "http://json.schemastore.org/proxies",
    "proxies": {
        "Test Route": {
            "matchCondition": {
                "route": "/{code}"
            },
            "backendUri": "https://%WEBSITE_HOSTNAME%/api/UrlTester/{code}"
        }//,
        //"Let's Encrypt Support" : {
        //    "matchCondition": {
        //        "route": "/.well-known/acme-challenge/{*code}"
        //    },
        //    "backendUri": "https://%WEBSITE_HOSTNAME%/api/LetsEncrypt/{code}"
        //},
        //"Domain Redirect": {
        //    "matchCondition": {
        //        "route": "/{*shortUrl}"
        //    },
        //    "backendUri": "http://%WEBSITE_HOSTNAME%/api/UrlRedirect/{shortUrl}"
        //},
        //"Api": {
        //    "matchCondition": {
        //       "route": "/api/{*path}"
        //    },
        //    "backendUri": "http://%WEBSITE_HOSTNAME%/api/{path}"
        //}
    }
}```

Because when I uncomment one of the other rules, they all fail.

**Comment by kevbite** [comment]
Not sure if this is related to the same problem but our function app has just randomly started returning 400 Bad Requests, for example hitting this endpoint:
https://dotnetsheff-api.azurewebsites.net/api/events/next

Nothing has changed at our end, it's just magically stopped working.

Any help would be much appreciated, also all the source including proxies are up on github - https://github.com/dotnetsheff/dotnetsheff-api

**Comment by paulbatum** [comment]
@safihamid Is this related to the recent breaking change?

**Comment by safihamid** [comment]
Yes it's documented here with the workarounds https://github.com/Azure/app-service-announcements/issues/50
The upcoming runtime release of functions will fix this.

**Comment by kevbite** [comment]
@safihamid whats the ETA on delivery on the fix?

**Comment by safihamid** [comment]
This is already fixed and deployed to prod.
