### ISSUE TITLE
Nightly E2E runs have stopped running

### ISSUE THREAD

**Issue by safihamid** [Azure/azure-webjobs-sdk-script#2067]
We need to have them running off of both v1.x and dev branch.

**Comment by paulbatum** [comment]
@soninaren please chat with Fabio to find out what you need to do

**Comment by soninaren** [comment]
Mathew fixed this
https://github.com/Azure/azure-webjobs-sdk-script/commit/b2947ba1e44db2f9a9de926fe816f93a93a2fac8
https://github.com/Azure/azure-webjobs-sdk-script/commit/a2ee11c7a2bded01b1f84ea0569bb07d56c43fbd
https://github.com/Azure/azure-webjobs-sdk-script/commit/ffbcf8477cce69f8f8876dbc8c3a8ad6e64896cb
