### ISSUE TITLE
Node: Accidentally calling context.done() twice is hard to debug

### ISSUE THREAD

**Issue by brettsam** [Azure/azure-webjobs-sdk-script#207]
Is calling `context.done()` twice from a script something we can prevent? Here's my example and what happened (this is me trying to simplify a repro -- there was a lot more code so it was harder to find the issue).

    module.exports = function(context, req) {
        var fs = require('fs');
        fs.readFile(__dirname + '\\function.json.notexist', function(err, data) {
            if(err) {
                context.log('ERROR');
                context.done(err);
            }
            context.log('SUCCESS');
            context.done();
        });
    }

When you run this:

- You see a `Function started` log, but never get a corresponding `Function failed`.
- You never see any logging in the console and I see no other logs in the host or function log files.
- The function invocation doesn't appear in the dashboard at all.

Edit: Found an easier repro as soon as I saved:

    module.exports = function(context, req) {
        context.log('Running...');
        context.done();
        context.done();
    }

**Comment by davidebbo** [comment]
Agreed, a second call to `done()` should fail hard.

**Comment by mathewc** [comment]
Yes we can handle that

**Comment by fabiocav** [comment]
This ties in nicely with #158 , might be something we can also support with the same batch of changes.

**Comment by davidebbo** [comment]
#158 seems like a much more profound change which would be a breaking change, no?

**Comment by fabiocav** [comment]
We can actually make that change in a backwards compatible way (essentially, supporting the current model as well as promises) and the work is relatively simple.
