### ISSUE TITLE
Proxies broken if name contains a dot

### ISSUE THREAD

**Issue by dersia** [Azure/azure-webjobs-sdk-script#2070]
I just realized that something changed with the proxies and they stopped working for us.

After looking into the json proxies I realized at even though everything was fine, I was getting a 500 response, when calling the proxy. I tried to recreate the proxy using another path and it' worked.
Since this was just a test, I called the proxy test. After replacing the old one with the newly created one, it still was working.
At the end I replaced the name 'test' with the naming we had before 'company.proxy-name' and it started responding again with 500s. 

I then removed the dot in the name and everything was fine.

Since this was working before I went on vacation 14 days ago, I guess there was a deployment and this changed the behavior. I thing this is a bug anyway, the proxies name shouldn't have any effects on the functionality.

**Comment by paulbatum** [comment]
@safihamid same issue as the others?

**Comment by safihamid** [comment]
Yes it's documented here with the workarounds https://github.com/Azure/app-service-announcements/issues/50
The upcoming runtime release of functions will fix this.

**Comment by safihamid** [comment]
This is already fixed and deployed to prod.
