### ISSUE TITLE
Ability to run func azure functionapp fetch-app-settings with slots

### ISSUE THREAD

**Issue by willmorgan** [Azure/azure-webjobs-sdk-script#2073]
We need the ability to fetch-app-settings for a particular slot.

At the moment this does not appear to be a supported feature.

#### Investigative information

- Timestamp: 2017-10-26
- Function App version (1.0 or 2.0-beta): 1.0, I think?
- Function App name: `sdkdev-Functions-gysuvrx2lokek`
- Function name(s) (as appropriate): n/a
- Invocation ID: n/a
- Region: West Europe

#### Repro steps

1. Have a deployed Function App with some slots, where the *app settings* are defined for *each slot*.
2. Run `func azure functionapp fetch-app-settings <YOUR_FUNCTION_NAME>`
3. Observe that your slot settings, predictably, are not synchronised.
4. Try running `func azure functionapp fetch-app-settings <YOUR_FUNCTION_NAME>-<YOUR_SLOT_NAME>
5. "Can't find app with name ..."
6. etc...

#### Expected behavior

I should be able to provide a slot option like:

`func azure functionapp fetch-app-settings <YOUR_FUNCTION_NAME> --slot <YOUR_SLOT_NAME>`

#### Actual behavior

Unsupported

#### Known workarounds

Not using slots... which is a dealbreaker for us right now.

**Comment by nelak** [comment]
Also I'd like to add that it's currently not possible to publish to a specific deployment slot.
Publishing only works for the functionApp and not for the other function names.

**Comment by martinpeck** [comment]
My experience is that `func azure functionapp fetch-app-settings <FUNCTION NAME>` retrieves the slot and non-slot settings for the current (running) slot, but I agree that there's obvious way to retrieve the settings from one of the other slots.

For step 3, are you saying that *no* settings are sync'd, or that only a subset of the settings get sync'd? If it's "no settings", can you confirm that you see your function when you run...?

`func azure functionapp list`

... and if it's a subset, which are you missing (the ones marked as "slot setting" or the ones that are not)?

**Comment by martinpeck** [comment]
While it doesn't produce the local.settings.json that you're after, it's worth noting that...

`az webapp config appsettings list --name [NAME_OF_FUNCTION_APP] --resource-group mpeckfuncwithslots --slot [SLOT_NAME]`

... will retrieve the settings for your function app, by slot.

**Comment by willmorgan** [comment]
```
For step 3, are you saying that no settings are sync'd, or that only a subset of the settings get sync'd? If it's "no settings", can you confirm that you see your function when you run...?
```

It takes only the "master" function app's settings, which I would say is expected. But not the required slot.

> While it doesn't produce the local.settings.json that you're after, it's worth noting that...
>
> `az webapp config appsettings list --name [NAME_OF_FUNCTION_APP] --resource-group mpeckfuncwithslots --slot [SLOT_NAME]`

This could be useful for now. Thanks.

**Comment by christopheranderson** [comment]
This issue was moved to Azure/azure-functions-cli#353
