### ISSUE TITLE
Provide a way to change TimerTrigger schedule outside of function.json

### ISSUE THREAD

**Issue by krispenner** [Azure/azure-webjobs-sdk-script#2077]
From what I can find, there is currently no ability to change the scheduled time of a TimerTrigger based function that was generated/precompiled and published from VS2017.

Every time I want to change the schedule I need to recompile and publish the function again, if I want different schedules per environment or per deployment of the same function I am flipping the code around and re-publishing.  Maybe I'm missing something on how this can be done cleaner/properly.

- Timestamp:  October 29th, 2017
- Function App version: 2.0-beta
- Target Framework: .NET Standard 2.0

function.json
{
  "generatedBy": "Microsoft.NET.Sdk.Functions.Generator-1.0.6",
  "configurationSource": "attributes",
  "bindings": [
    {
      "type": "timerTrigger",
      **"schedule": "0 0 13 * * 1-5",**
      "useMonitor": true,
      "runOnStartup": false,
      "name": "timeTrigger"
    }
  ],
  "disabled": false,
  "scriptFile": "../bin/Jobs.AzureFunctionsHost.dll",
  "entryPoint": "Jobs.AzureFunctionsHost.Functions.RunJob1"
}

I believe this is similar to the requirements for #1331 _"Provide a way to disable a function outside of function.json"_

This was also mentioned on https://stackoverflow.com/a/46248655 and @davidebbo mentioned this was not currently possible with generated/precompiled functions and suggested an issue be submitted here; although I could not find a pre-existing issue, you can dup this one if there is one floating around somewhere.

Cheers,
kp

**Comment by davidebbo** [comment]
See #1934, which provides a solution.
