### ISSUE TITLE
Info on adding Python modules to Functions Apps is needed on the corresponding Wiki page

### ISSUE THREAD

**Issue by sergei3000** [Azure/azure-webjobs-sdk-script#2083]
There is this page in the Wiki explaining how to add a custom version of Python to a Functions Application:
https://github.com/Azure/azure-webjobs-sdk-script/wiki/Using-a-custom-version-of-Python
But it suggests a embedded version of Python, that does not include pip. So it is not clear how to use this custom version of Python, since usually some external packages are needed.
I think further explanations should be provided on that page on how to install third-party libraries like those in PyPI or somewhere else. Including how to do it with pip.

**Comment by christopheranderson** [comment]
Don't use Python in v1 today. It's bad and is getting replaced with an improved version in v2. You can track the status of that effort here: https://github.com/Azure/azure-webjobs-sdk-script/issues/335

Closing this issue since it won't impact v2 and v1 Python is deprecated.
