### ISSUE TITLE
Provide last invocation Id in Azure Function's Get Function Api

### ISSUE THREAD

**Issue by karandesai28** [Azure/azure-webjobs-sdk-script#2088]
As per [this](https://github.com/projectkudu/kudu/wiki/Functions-API) , we can get details of azure function using rest API. The response of the API includes Id, Name, Type, Location, Properties,Bindings etc. Is it possible to also include the Last Invocation Id in the response?

I am aware about ExecutionContext, and leveraging invocation Id using it. But there is no way to get the last invoked Id (or the complete list) of executed azure function via Kudu or Rest APIs. Therefore, Is it possible to add the invocation Id in the Get Function Api Response?

**Comment by christopheranderson** [comment]
We're not likely to pick this up since we'd have to have a lot of state in the runtime about the last execution, which doesn't exist and it pretty expensive. It's best to get this from your monitoring resource.

Thanks for the suggestion!

**Comment by karandesai28** [comment]
Thanks for the response. I certainly respect your decision but the use case which led me to open this issue was:
1. Inability to easily get the last execution date of the azure function via [Functions api.](https://github.com/projectkudu/kudu/wiki/Functions-API)
2. The lack of bridge between Azure Functions and [Retrieving-information-about-the-currently-running-function](https://github.com/Azure/azure-webjobs-sdk-script/wiki/Retrieving-information-about-the-currently-running-function) in context of Api.

I hope in future, there would be some better way at least to monitor last execution(s) of azure functions using Api.

**Comment by christopheranderson** [comment]
That API isn't intended to serve that purpose. That API enumerates your resources and their configuration, but not telemetry/health/etc.

I'd recommend using App Insights to query for the last executed Function. You can even query on invocationid, which allows you to bridge the info in your Execution context and your telemetry. https://docs.microsoft.com/en-us/azure/azure-functions/functions-monitoring#overview

**Comment by karandesai28** [comment]
Okay, noted. Will surely checkout the link.
Thanks for the reply.
