### ISSUE TITLE
Examples or guidelines on curl'ing keys?

### ISSUE THREAD

**Issue by trstringer** [Azure/azure-webjobs-sdk-script#2089]
Regarding [the API that allows you to work with keys](https://github.com/Azure/azure-webjobs-sdk-script/wiki/Key-management-API#function-keys-collection-resource-adminfunctionsfunctionnamekeys), I'm attempting to do a simple curl and I'm getting no output back.

Is there any published example (end to end) showing how to do this? What content, headers, etc. are required.

**Comment by christopheranderson** [comment]
You have to pass the admin key to get it. You can use the query string or header based method to pass the key. https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-http-webhook#authorization-keys
