### ISSUE TITLE
[cli] deploy internalservererror

### ISSUE THREAD

**Issue by micahasmith** [Azure/azure-webjobs-sdk-script#2090]
#### Investigative information

Please provide the following:

- Timestamp:
- Function App version (1.0 or 2.0-beta):
- Function App name: gooten-slothy
- Function name(s) (as appropriate):
- Invocation ID:
- Region: east us

#### Repro steps

`func azure functionapp publish gooten-slothy`

#### Expected behavior

uploads server funcs

#### Actual behavior

Provide a description of the actual behavior observed.

```
Publish /Users/micahsmith/printio/gooten-slothy contents to an Azure Function App. Locally deleted files are not removed from destination.
Getting site publishing info...
Creating archive for current directory...
Uploading archive...
Error uploading archive (InternalServerError).
Retry: 1 of 2
Creating archive for current directory...
Uploading archive...
Error uploading archive (InternalServerError).
Retry: 2 of 2
Creating archive for current directory...
Uploading archive...
Error uploading archive (InternalServerError).
```

**Comment by christopheranderson** [comment]
@micahasmith - do you have a sample of your project you can share? Is it Node.js based? If so, can you share your package.json?

**Comment by micahasmith** [comment]
@christopheranderson the function app name is above, you're more than welcome to jump into the codebase.

```js
{
  "name": "gooten-slothy",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "directories": {
    "test": "test"
  },
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "request": "^2.83.0",
    "sequelize": "^4.20.3",
    "tedious": "^2.0.1"
  }
}

```

**Comment by christopheranderson** [comment]
This issue was moved to Azure/azure-functions-cli#352
