### ISSUE TITLE
Improve resilience of secret file management

### ISSUE THREAD

**Issue by fabiocav** [Azure/azure-webjobs-sdk-script#2093]
When creating secret files, the runtime needs to ensure that it doesn't attempt to overwrite existing secret files and that inability to create a file (IO exceptions due to another instance or Kudu having a write lock to that file) are gracefully handled.

**Comment by paulbatum** [comment]
its possible some work was already done in this area as we had some CRIs relating to this. Chat with @fabiocav @mathewc @watashiSHUN to figure out the next steps.
