### ISSUE TITLE
Proxies throws protocol violation exception and returns 500 when user agent sends chunked transfer encoding and Proxy calls external backend.

### ISSUE THREAD

**Issue by baabel** [Azure/azure-webjobs-sdk-script#2099]
When a user agent makes an HTTP request to a Functions Proxy using **chunked transfer encoding** and the proxy makes a call to an external back end call, the Proxy throws a protocol violation exception and returns status code 500 back to the client.

#### Repro steps

Provide the steps required to reproduce the problem:

1.  Create a Function Proxy that forwards to an external service
2.  Call the Function Proxy using chunked transfer encoding

#### Expected behavior

Proxy should handle the chunked transfer encoding and be able to successfully call external service passing the correct content to the service.

#### Actual behavior

Proxy calls external service with no content, throws a protocol violation internally and returns 500 status code back to the client.

#### Known workarounds

Have both the proxies and backend functions in the same function app.

#### Related information 

Provide any related information 

c#

HTTP

**Comment by safihamid** [comment]
The fix is in Function runtime versions 1.0.11388  or higher which is being deployed now. might take few more days to be available across all stamps.
