### ISSUE TITLE
Encrypt Secrets at rest

### ISSUE THREAD

**Issue by mathewc** [Azure/azure-webjobs-sdk-script#21]
For host/function secret keys, we need to encrypt them at rest on the file system

**Comment by christopheranderson** [comment]
RC justification: Security 👍

**Comment by christopheranderson** [comment]
Consider including mutli-key support in this design, if it can be done without putting encryption at risk.

https://github.com/Azure/azure-webjobs-sdk-script/issues/270

**Comment by fabiocav** [comment]
Assigned myself to this.

**Comment by fabiocav** [comment]
The work for this is mostly complete, but we're blocked on the API design to allow the portal to work with the secrets.
