### ISSUE TITLE
Apply Timeout value to Direct Load functions

### ISSUE THREAD

**Issue by mathewc** [Azure/azure-webjobs-sdk-script#2105]
Currently we apply the FunctionTimeout value configured via host.json (or the default value if not specified) by generating a corresponding `[FunctionTimeout(T)]` attribute on the generated wrapper class. The problem is that for direct load functions we're not generating wrappers, so this value will not be applied.

One way to address this is to add a top level `JobHostConfiguration.FunctionTimeout` value to core SDK, to compliment the class/method attributes we already have. This will then allow us to directly map our host.json value to the host config value, allowing the default timeout to take effect for direct load functions as well.

Note that in addition to the time value, we also need to consider the ThrowOnTimeout/TimeoutWhileDebugging values.

**Comment by MikeStall** [comment]
We could handle all of these properties by just adding a JobHostConfiguration.DefaultTimeout property of type TimeoutAttribute.

**Comment by MikeStall** [comment]
Fix checked into SDK and Script v1.
