### ISSUE TITLE
V1 runtime should not fail all any /admin requests if the host is not running

### ISSUE THREAD

**Issue by ahmelsayed** [Azure/azure-webjobs-sdk-script#2114]
The only API that depends on the host being up is the invoke function. All other /admin APIs don't need that. 

This is only relevant for v1 runtime, as #2005 handles that for v2

**Comment by mathewc** [comment]
Yes, we have special handling for the `admin/host/status` endpoint, but some of the other admin apis like keys we're not allowing through in host error conditions.
