### ISSUE TITLE
Minor issues with contributor onboarding guide

### ISSUE THREAD

**Issue by SteveALee** [Azure/azure-webjobs-sdk-script#2120]
@christopheranderson 

A couple of minor observations

* It's common to have a CONTRIBUTING file in the project root. I guess it could just contain the wiki page URL
* @azurefunctionsteam is not a twitter account you call tweet. it's a list. Should be @azurefunctions.

Cheers

**Comment by christopheranderson** [comment]
- [x] Fix Azure Functions twitter account link
- [ ] Add CONTRIBUTING file
