### ISSUE TITLE
Application Insights no longer displaying ServiceBus message body in request telemetry

### ISSUE THREAD

**Issue by ahmelsayed** [Azure/azure-webjobs-sdk-script#2127]
_From @sadgit on November 2, 2017 10:54_

Telemetry records the 'TriggerReason' as "New ServiceBus message detected on 'Topic/Subscriptions/Subscription'."

BUT

No longer displays the message body; it used to be available, searchable and filterable

_Copied from original issue: Azure/Azure-Functions#573_

**Comment by brettsam** [comment]
This was deliberately done to prevent arbitrary data from being auto-logged in Application Insights. Some teams have different role-based permissions for App Insights logs than they do for other production services so we decided to limit the data that we automatically log. 

You still have the ability to use an `ILogger` from within your function and log out all the parameter details that you want, which gives you more control over what you allow through to App Insights.

You can see some other reasoning in the PR here: https://github.com/Azure/azure-webjobs-sdk/pull/1355.

**Comment by sadgit** [comment]
Fair point that I had missed
