### ISSUE TITLE
Allow redirect HTTP request to HTTPS from proxies

### ISSUE THREAD

**Issue by ahmelsayed** [Azure/azure-webjobs-sdk-script#2128]
_From @prabhakarreddy1234 on October 26, 2017 9:13_

Similar to a rewrite rule to force https in web.config, expecting same in function proxies.

Something similar to this if possible.
```
requestOverrides": {
        "backend.request.host.scheme": "https"
}
```

_Copied from original issue: Azure/Azure-Functions#569_

**Comment by codeitcody** [comment]
This works for me (November 2017):

In the Azure portal, go to your function app.

> Platform features > Custom Domains > toggle **HTTPS Only** to 'On'.

Anyone using HTTP will receive a *301 Moved Permanently* and be redirected to the HTTPS endpoint. You do not need to actually add a new hostname/domain to toggle this feature. This appears to work with both consumption and app service plans.

**Comment by safihamid** [comment]
Yes Platform features > Custom Domains > toggle HTTPS Only to 'On'. is our recommended way. and you don't need to have a custom domain to enable this feature.

**Comment by LarsSimonsen** [comment]
I have a CDN with a custom domain pointing to a Function App (Proxies). When I enable HTTPS Only on the Function App, the client is redirected to HTTPS on the Function App, not HTTPS on the custom domain attached to my Akamai CDN. And the CDN doesn't support HTTPS Only. Please consider reopening.

**Comment by safihamid** [comment]
@LarsSimonsen One workaround here would be to configure your custom domain in App Service rather than CDN then 'Https Only' would work with custom domains as well.

**Comment by SajalGolas** [comment]
> I have an Akamai CDN with a custom domain pointing to a Function App (Proxies). When I enable HTTPS Only on the Function App, the client is redirected to HTTPS on the Function App, not HTTPS on the custom domain attached to my CDN. And the CDN doesn't support HTTPS Only.
> 
> If matchCondition had a parameter for protocol (HTTP/HTTPS) or port number, that would make it possible to set up a rule for this. Please consider reopening.

I'm also facing this same issue. Did you resolved the issue ?

**Comment by SajalGolas** [comment]
> @LarsSimonsen One workaround here would be to configure your custom domain in App Service rather than CDN then 'Https Only' would work with custom domains as well.

Hi safihamid,
I want the benefits of CDN for faster response. How can i enable http to https redirection at Akamai CDN level or function proxy level
