### ISSUE TITLE
Runtime doesn't pick up code changes if you change trigger after at least 1 run

### ISSUE THREAD

**Issue by davidebbo** [Azure/azure-webjobs-sdk-script#213]
This is a port of https://github.com/projectkudu/AzureFunctions/issues/267 (by @Tuesdaysgreen), which is really a runtime issue:

1. Click Quickstart
2. Choose timer trigger template and close the tutorial
3. Add context.log("hello") to beginning of function
4. Execute the function **(this seems to be important)**
4. Go to "integrate" tab, remove timer trigger, and add an http trigger
5. Go back to dev tab and change log statement to context.log("hello 2")
6. Run the function

When you check the log output, you'll see that it outputs "hello" instead of "hello 2".

If you check index.js for that function, it has the updated value, but it seems like the runtime isn't picking it up.

**Comment by davidebbo** [comment]
I also repro this consistently. It repros each time I remove and re-add the http binding. Then if you change and save the code once more, issue goes away.

**Comment by fabiocav** [comment]
I can test this with C#, but just in case you already have; is this with Node only?

**Comment by davidebbo** [comment]
Will test now. For Node repro, one thing I noticed is that on the first Save after re-adding the binding, we don't get the usual notification, e.g. normally you get:

    2016-04-01T23:33:10.974 Script for function 'HttpTriggerNodeJS1' changed. Reloading.

So for whatever reason, the runtime is just not listening for changes.

**Comment by davidebbo** [comment]
It does **not** repro with C#.

**Comment by mathewc** [comment]
I'll look into it, and try to get a fix out for PR by tomorrow afternoon. I tried to repro it when Elliot showed me the other day but I couldn't get it. I don't think people delete their triggers and add new ones very often, so I don't think this is affecting many people, but I'll still fix it ASAP.

**Comment by davidebbo** [comment]
Agreed, it's not highest pri. Strange, though.

**Comment by mathewc** [comment]
While I can also get a steady repro in the portal of this, unfortunately I can't do the same locally as I was hoping, to get it under the debugger. Likely some kind of timing issue triggered only by the pattern of file updates Kudu performs as opposed to local file operations (I know there are FileWatcher event differences).

I'll probably have to figure out what could cause this by inspection, and try a few updates manually via private site extension.

**Comment by fabiocav** [comment]
Remote debugging was my friend when dealing with issues I could only reproduce when hosted.
