### ISSUE TITLE
Add singleton support to node

### ISSUE THREAD

**Issue by tony-gutierrez** [Azure/azure-webjobs-sdk-script#2130]
https://github.com/Azure/azure-webjobs-sdk/issues/1429#issuecomment-344346805

Need to be able to specify singleton functions in the node env.

**Comment by paulbatum** [comment]
This is not isolated to node. For example, you can't write a csx function that runs in singleton mode. The work to expose this for node and other languages is tracked by https://github.com/Azure/azure-webjobs-sdk-script/issues/912 so I'm closing this as a dupe.
