### ISSUE TITLE
runtime shouldn't shutdown on invalid host.json configuration.

### ISSUE THREAD

**Issue by ahmelsayed** [Azure/azure-webjobs-sdk-script#2135]
if a configuration is not valid, log an error and fall back to default values

**Comment by mathewc** [comment]
Why would we do this? It's best to fail on invalid input, rather than log/ignore.

**Comment by ahmelsayed** [comment]
that's different between service vs framework in my opinion.

The project is towing the line between the 2, but I think the 'host' part of the runtime should be treated like a service. It should reject invalid inputs and use default values otherwise. I think the host shuts down for many recoverable\ignorable situations.

**Comment by paulbatum** [comment]
@ahmelsayed the main issue i have is how does the user discover that one of their configuration values aren't being used? I feel like this could create issues that are really hard to diagnose.

Also considering the fact that the admin APIs will now continue to work even when the host isnt started.. I'm not sure this is a real problem anymore?

Reopen with a specific example where you think it would be helpful if you disagree.
