### ISSUE TITLE
Runtime ~2 System.Linq.Expressions warning

### ISSUE THREAD

**Issue by dersia** [Azure/azure-webjobs-sdk-script#2145]
We recently moved to the beta Runtime and all works so far really great for us.

There is a warning showing up when Newtonsoft.Json is referenced, though it doesn't harm so far, I thought it makes sense keep track of this for the next release.

Updating to Linq.Expressions 4.2.0.0 for the runtime should solve this warning:
```warning CS1701: Assuming assembly reference 'System.Linq.Expressions, Version=4.0.10.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' used by 'Newtonsoft.Json' matches identity 'System.Linq.Expressions, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' of 'System.Linq.Expressions', you may need to supply runtime policy```

```run.csx(47,54): warning CS1701: Assuming assembly reference 'System.Linq.Expressions, Version=4.0.10.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' used by 'Newtonsoft.Json' matches identity 'System.Linq.Expressions, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' of 'System.Linq.Expressions', you may need to supply runtime policy```

**Comment by fabiocav** [comment]
@dersia dependencies will be continuously updated with every release leading up to GA.

**Comment by dersia** [comment]
@fabiocav I know, this ticket is just for tracking that warning

**Comment by paulbatum** [comment]
My understanding is that this has been fixed in the latest release of functions v2.
