### ISSUE TITLE
Feature request: variable console verbosity

### ISSUE THREAD

**Issue by snobu** [Azure/azure-webjobs-sdk-script#2148]
It would be really handy to have a `--loglevel info|error|debug` flag that you can pass to `func host start`.

Sometimes things in the console become way too messy when all you're looking for is a `context.log()` line. The default could still be debug, or we could print something like

>IMPORTANT: To get more verbosity pass `--loglevel debug`

early on `func host start`.

All log levels should include `error`, you never want to accidentally suppress errors... probably.

**Comment by paulbatum** [comment]
So you can manage this through host.json, check the options under tracing. See here for info:
https://github.com/Azure/azure-webjobs-sdk-script/wiki/host.json

If you'd still like to open a feature request to allow the log level to be specified when running func host start, file a new bug in this repo:
https://github.com/azure/azure-functions-cli
