### ISSUE TITLE
Fix ngen for runtime

### ISSUE THREAD

**Issue by MikeStall** [Azure/azure-webjobs-sdk-script#2174]
Our azure deployment is not pulling ngen bits.  This can cause a 10s delay in cold-start. 

Using FusLog, we narrowed it down to this error: 
Attempting to use native image D:\Windows\assembly\NativeImages_v4.0.30319_32\System\ea3c7ced77afec169e141c94f239c5c2\System.ni.dll.
ZAP: An ngen image of an assembly which is not loaded as domain-neutral cannot be used in multiple appdomains - abandoning ngen image. The assembly will be JIT-compiled in the second appdomain. See System.LoaderOptimization.MultiDomain for information about domain-neutral loading.
Discarding native image.

**Comment by MikeStall** [comment]
This is completely influenced by the binding redirects in the web.config. 

Notes from Jan Kotas:

> Binding redirect for any framework assembly disable sharing for all framework assemblies in the domain.
>  
> Domain sharing is implemented as optimization that kicks in only when you are on the golden path. Having binding redirects for framework assemblies gets you off the golden path.

We may need Framework 4.7.2 to fix this.

**Comment by fabiocav** [comment]
This is being addressed with release [1.0.11490](https://github.com/Azure/azure-webjobs-sdk-script/releases/tag/v1.0.11490)
