### ISSUE TITLE
CosmosDB DocumentClient Output Bindings

### ISSUE THREAD

**Issue by TPoise** [Azure/azure-webjobs-sdk-script#2175]
Hi,

Love Azure Functions as well as CosmosDB.  In order to do more advanced things with Cosmos, we create our own instance of DocumentClient.  However, this doesn't scale very well can will cause socket exhaustion very quickly for us ("An attempt was made to access a socket in a way forbidden by its access permissions").  As told in other issues here on Github, using the DocumentClient input binding will help solve this issue for input scenarios.  However from the docs, and experimentation, there's no way to get a DocumentClient instance for output scenarios.

#### Expected behavior

Should be able to create an output binding that can I can cast into a DocumentClient and use this as a pre-warmed singleton instance of the connection to CosmosDB

Example method signature would be something like:
```csharp
public static Task Run(MyPoco poco,  DocumentClient cosmosClient)
{
       
       cosmosClient.Upsert(poco);

}
```
#### Actual behavior

No way to perform the scenario now.

#### Known workarounds

Create your own instance, which can lead to port exhaustion.

**Comment by christopheranderson** [comment]
This issue was moved to Azure/azure-webjobs-sdk-extensions#362
