### ISSUE TITLE
Scaling issue with Azure Function Proxy

### ISSUE THREAD

**Issue by OShevnin-Quest** [Azure/azure-webjobs-sdk-script#2177]
Was experimenting with load testing proxies, and noticed an interesting behaviour.
Scaling doesn't work for proxy requests, unless I add a basic Azure Function to the Function App.

Steps to reproduce:
1. Created a new Function App with a single proxy function inside. Turned on AI integration for monitoring.
2. Performed "tons" of requests to the proxy function for few minutes. 
3. Real-time monitoring in AI was always displaying a single host instance.

Then, added a basic HTTP trigger function to the same Azure Function App. (can be any other trigger as well, I guess)

4. Performed "tons" of requests to the proxy function for few minutes, again. 
5. The proxy started scaling generating new instances and balancing the load.

Seems like some bug in proxy function scaling logic.

**Comment by safihamid** [comment]
Thanks much for reporting this issue. this was a recent regression in our code. I fixed it in kudu and will be deployed with the next deployment of kudu aka scm site.

**Comment by OShevnin-Quest** [comment]
cool. Thank you
