### ISSUE TITLE
Method not found returned for Java HttpTrigger with binary data

### ISSUE THREAD

**Issue by jeffhollan** [Azure/azure-webjobs-sdk-script#2179]
Can't seem to find a way to successfully pass in binary data to Java function with HttpTrigger. Always says no method signature found regardless of combinations.

**Repro Steps**
1. Create Function app using Maven tools for Java
2. Add the `datatype = "binary"` attribute for the HttpTrigger and change the type to `Byte[]`, `byte[]`, or `HttpRequestMessage<byte[]>`
3. Make sure method is valid and try to return any type
4. AFter running and executing the script errors with method not found

**Other notes**
Verified that the function.json file being generated looks accurate.  Samples below:

function.json
```
{
  "scriptFile" : "../helloworld2-1.0-SNAPSHOT.jar",
  "entryPoint" : "io.hollan.hello.Function.hello",
  "bindings" : [ {
    "type" : "httpTrigger",
    "name" : "req",
    "direction" : "in",
    "dataType" : "binary",
    "authLevel" : "anonymous",
    "methods" : [ "get", "post" ]
  }, {
    "type" : "http",
    "name" : "$return",
    "direction" : "out"
  } ],
  "disabled" : false
}
```

```java
package io.hollan.hello;

import com.microsoft.azure.serverless.functions.annotation.*;
import com.microsoft.azure.serverless.functions.*;

/**
 * Azure Functions with HTTP Trigger.
 */
public class Function {
    @FunctionName("hello")
    public String hello(@HttpTrigger(name = "req", methods = {"get", "post"}, authLevel = AuthorizationLevel.ANONYMOUS, dataType = "binary") Byte[] req,
                                     final ExecutionContext context) {
        context.getLogger().info("Java HTTP trigger processed a request.");

        return "foo";
    }
}
```

**Comment by JunyiYi** [comment]
This is exactly the way you could pass binary data. But make sure your content type is `application/octet-stream`:
```
curl --request POST --header "Content-Type:application/octet-stream" --data-binary "@LICENSE.txt" http://localhost:7071/api/hello
```

**Comment by paulbatum** [comment]
@jeffhollan does this work for you? Trying to understand if Junyi's reply addresses the issue.

**Comment by christopheranderson** [comment]
This issue was moved to Azure/azure-functions-java-worker#44
