### ISSUE TITLE
Azure Timer Function Not Firing

### ISSUE THREAD

**Issue by bjh1977** [Azure/azure-webjobs-sdk-script#2181]
As with #1445..

My function did not fire at 09:10am on either Saturday or Sunday as expected.

- Function App version (1.0 or 2.0-beta): 1.0.11388.0
- Function App name: asinttest-FA-CostMgmt-dev381
- Function name(s) (as appropriate): GetConsumptionDataTimerTrigger
- Invocation ID: 8d9e7e89-9914-4f1f-bdae-7f29d59d109f (last successful, when logged in to portal)
- Region: North Europe

**Repro:**  
1. Log in to portal just before function is due to fire
2. Witness function fire
3. Go home for the weekend
4. Log in on Sunday evening to find it has not fired, as confirmed by no entry in my database, nothing in the invocation logs.
5. Change cron schedule to fire 5 minutes hence, and the function will fire.

**Expected:**
I expected the function to fire at 09:10 UTC both today (Sunday) and yesterday. 

**Actual:**
The function had not fired.

**Related:**
- I'm using a consumption plan, which I'd expected to do the job perfectly, but obviously it is no good if the function will only fire if the application has to be warmed up first.
- I have not set WEBSITE_TIME_ZONE, as referenced in #995 and #1160
- The cron schedule was set to 0 10 9 * * * until I changed it to 0 16 21 * * * to test it.

<details>
<summary>function.json</summary>

```json
{
  "generatedBy": "Microsoft.NET.Sdk.Functions.Generator-1.0.6",
  "configurationSource": "attributes",
  "bindings": [
    {
      "type": "timerTrigger",
      "schedule": "0 10 9 * * *",
      "useMonitor": true,
      "runOnStartup": false,
      "name": "myTimer"
    }
  ],
  "disabled": false,
  "scriptFile": "../bin/AzureFunctions.dll",
  "entryPoint": "AzureFunctions.GetConsumptionDataTimerTrigger.Run"
}
```
</details>

**Comment by davidebbo** [comment]
@bjh1977 how did you create the Functions in the first place? Was it via Portal, or some other deployment technique?

**Comment by bjh1977** [comment]
I wrote the functions in Visual Studio and built the solution into a web deploy package.  Then I deployed them via an ARM template.

**Comment by davidebbo** [comment]
Dup of https://social.msdn.microsoft.com/Forums/en-US/07b7cab1-09e2-4c6e-9fd1-3561ae0c6ca4/azure-timer-function-not-firing?forum=AzureFunctions, so let's use that one. Please make sure you always include back links when cross posting to avoid duplicating investigation efforts. Thanks!
