### ISSUE TITLE
Unclear UX for Event Grid binding

### ISSUE THREAD

**Issue by nirmash** [Azure/azure-webjobs-sdk-script#2184]
When creating an event grid binding the name of the Event Subscription in Event Grid has to match the name of the Functions trigger for it to work. There is no place in the UX that stipulates this requirement and Ideally we will have the name auto-populated when the user selects "create new". Minimal fix would be to add some text to the binding UX definition screen.

**Comment by jeffhollan** [comment]
Were you able to get a repro? Saw mail from Shun. Let me know and I can help assign it.

**Comment by christopheranderson** [comment]
This issue was moved to Azure/azure-functions-ux#2213
