### ISSUE TITLE
Question - Does watchDirectories watch for function.json as well?

### ISSUE THREAD

**Issue by tomkerkhove** [Azure/azure-webjobs-sdk-script#2194]
I'd like to use this structure in my codebase:
- /Triggers/MyFunction1/function.json
- /Triggers/MyFunction2/function.json

However, it looks like this is not supported out of the box.

According to the [documentation](https://docs.microsoft.com/en-gb/azure/azure-functions/functions-host-json#watchdirectories), this is what `watchDirectories` does:
> A set of shared code directories that should be monitored for changes. Ensures that when code in these directories is changed, the changes are picked up by your functions.

Does that mean that it's looking for assemblies only or also for function.json?
Does it fix my scenario above?

**Comment by jeffhollan** [comment]
Today the only supported file structure is a single folder at the base directory with a function.json.  This would be a new feature request for a recursive search for function.json (while `watchDirectories` is simply about triggering a restart, not where things are loaded from).  In meantime I would suggest using naming conventions on the base folders themselves.  At this time we don't have any plans to change the watchDirectories behavior or implement a recursive function app search behavior

**Comment by tomkerkhove** [comment]
Too bad but thanks for letting me know!
