### ISSUE TITLE
Doc Enhancement: Function.json

### ISSUE THREAD

**Issue by securityvoid** [Azure/azure-webjobs-sdk-script#2196]
Based on my reading here I seem to recall that additional parameters are valid now within the function.json such as "script" and "entrypoint". However, I do not see these extra parameters documented within the documentation:
https://docs.microsoft.com/en-us/azure/azure-functions/functions-triggers-bindings
https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-node
https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-http-webhook#trigger---configuration

Is this full schema documented somewhere that I'm not finding? If not, is it possible to get this documented?

**Comment by paulbatum** [comment]
The schema is here:
http://json.schemastore.org/function

**Comment by securityvoid** [comment]
Thank-you. It would probably be REALLY useful for others if that was referenced from the official Microsoft Documentation. Its great that this stuff is on GitHub, but it takes some digging for someone to find an issue like this.

**Comment by paulbatum** [comment]
@securityvoid makes sense, I filed https://github.com/Azure/Azure-Functions/issues/633 for the doc improvement
