### ISSUE TITLE
Investigate missing FunctionName in FunctionsLogs table

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-webjobs-sdk-script#2199]
Sample Kusto query:
FunctionsLogs | where FunctionName == "" | take 10 | project AppName , FunctionName , Summary , Details 

Sample of the Summary column from the above query:
Executing 'Functions.FunctionName' (Reason='', Id=SomeGUID)

Summary column mentions the functionName but the value is missing in FunctionName column

**Comment by brettsam** [comment]
My removal of TraceWriter will change this -- the function name should be included for these logs. #2182

I believe that this will be fixed by this change-- 'Executing/Executed' logs should now have the function name.

**Comment by pragnagopa** [comment]
Fix checked in to V1 and Removal TraceWriter in V2 fixed this issue in V2.
