### ISSUE TITLE
Support passing using POCOs, JObject and WebHook specific type as HTTP trigger argument

### ISSUE THREAD

**Issue by fabiocav** [Azure/azure-webjobs-sdk-script#220]
When working with WebHooks, users should expect to write the following:
``` csharp
public Task Run(WebHookHandlerContext input) 
{
...
}
```

And to simplify the process, when working with WebHook receiver that expose strongly typed payloads (e.g. InstagramNotification, KuduNotification, etc.)

``` csharp
public Task Run(KuduNotification input) 
{
...
}
```

**Comment by mathewc** [comment]
What additional capabilities does WebHookHandlerContext enable? Note that since we own the WebApi handler, using the type from a user method might seem strange - it's not an actual http handler after all. But if it provides important additional capabilities it might make sense.

Note that we should be consistent in the other languages, e.g. Node.js. I.e., we should expose the same set of new properties/capabilities to the Node function context as well.

**Comment by fabiocav** [comment]
Passing the WebHookHandlerContext gives the function the ability to easily pull the payload using `GetDataOrDefault<T>` or `TryGetData<T>`, while also providing access to the request, the request context, actions and other state related to the WebHook request.

It would also be pretty simple to pass the context, and although the function itself isn't an actual `IWebHookHandler`, it makes sense that it would act like one, and make sense for our `DelegatingWebHookHandler` to delegate the WebHook processing to the function, but if we don't see value in passing it, we can reduce the scope and pass the just the payload (based on the argument type). This would provide parity with the current Node implementation.

**Comment by mathewc** [comment]
It might make sense, I just want to be sure there aren't any hidden gotchas - e.g. the context also has a Response property that when set in the context of an IWebHookHandler does certain things - we need to rationalize that with our HTTP pipeline. I also want to make sure we make our WebHooks across languages as consistent as possible.

**Comment by fabiocav** [comment]
Agreed. We can scope this down to the payload type for now. I'll spend some time investigating the impact of exposing the context. You're correct that setting the response in the context has special meaning, where it would short circuit the WebHook processing pipeline and use that as the response. The first wouldn't matter much in our case, but I need to investigate the later.

**Comment by fabiocav** [comment]
Changed the scope and updated the description to match. We'll not be passing the `WebHookHandlerContext` with this change.

**Comment by mathewc** [comment]
This is resolved now, right?

**Comment by fabiocav** [comment]
Yes, it is. Closing.
