### ISSUE TITLE
New portal UI breaks V2 extensions

### ISSUE THREAD

**Issue by dersia** [Azure/azure-webjobs-sdk-script#2208]
Runtime V2 brings new extension installation for triggers like EventHubTrigger.

Before the new portal UI was online, the portal UI checked for installed extensions in the functions app and if it wasn't installed there was a box with a link to install the missing extension, which called the API to install the missing extension.

The new portal UI doesn't provide the opportunity install missing extensions, nor does it check if the extension is installed. Right now there is no way through the portal to create a EventHub-Triggered function for V2 Runtime.

A workaround is to call the API through Postman to install the extension, but I'm not sure if the API is documented anywhere.

**Comment by paulbatum** [comment]
This issue was moved to Azure/azure-functions-ux#2150
