### ISSUE TITLE
[C#] Enable loading additional script files into my function

### ISSUE THREAD

**Issue by fabiocav** [Azure/azure-webjobs-sdk-script#221]
Enable loading additional `.csx` script files into my function, bringing that code into the same compilation context.

This would leverage the `#load` directive and allow users to load files deployed in the same directory as their function script using the following syntax:
``` csharp
#load "MyOtherFile.csx"
```

#### Additional details/ideas
- Once this is added, shared script files (located in a folder outside of the script folder) would also be supported, using standard path syntax (e.g. `#load "..\shared\MyOtherFile.csx"`) . Should we make that a first class concept? Support a different syntax for shared file references?

**Comment by davidebbo** [comment]
Is `#load` some new concept you created, or part of .csx syntax?

**Comment by davidebbo** [comment]
Ok, I read through https://msdn.microsoft.com/en-us/magazine/mt614271.aspx and I see it's part of .csx.

**Comment by fabiocav** [comment]
Yes, this is part os the C# Script/csx syntax. Used by C# Interactive and other projects that use the same format.
