### ISSUE TITLE
Azure Functions .net core doesn't work with EF core

### ISSUE THREAD

**Issue by borlip** [Azure/azure-webjobs-sdk-script#2226]
Azure Functions based on latest VS 2017 template doesn't work with EF core.

#### Investigative information

Please provide the following:

- Localhost
- Starting Host (HostId=borispc-1658624930, Version=2.0.11353.0, ProcessId=23336, Debug=False, Attempt=0, FunctionsExtensionVersion=)
- VS 2017 Version 15.5.1

#### Repro steps

Provide the steps required to reproduce the problem:

1. Create a new Azure Functions .net core with httptrigger from a template 
2. Add dependency on Microsoft.EntityFrameworkCore.SqlServer (2.0.1)
3. Create a simple class deriving from DbContext (no need to reference this class from the function)
4. Launch debugger
5. Fails with the following error:

#### Expected behavior

No Errors 

#### Actual behavior

Provide a description of the actual behavior observed.

Error message in console
[14/12/2017 1:02:17 AM] Function1: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.

#### Known workarounds

no

#### Related information 

Provide any related information 

* Programming language used 
* Links to source
* Bindings used

**Comment by dersia** [comment]
This is also related to https://github.com/Azure/Azure-Functions/issues/625 right now the cli for V2 is limited to Runtime 1.0.6, which has a dependency to AspNetCore, Mvc and EFCore 2.0.0.

If you use EFCore 2.0.0 it should be fine for now.

See this comment: https://github.com/Azure/Azure-Functions/issues/625#issuecomment-351563570

**Comment by borlip** [comment]
Oh my gosh! This is so ridiculous! How is this stuff even being released?

Thanks for your help!

**Comment by MisinformedDNA** [comment]
@dersia If I look through all the dependencies of Runtime 1.0.6, I don't see AspNetCore or EFCore referenced. If I want to inherit from DbContext, I need to add a dependency to EFCore 2.0.0 first.

> right now the cli for V2 is limited to Runtime 1.0.6, which has a dependency to AspNetCore, Mvc and EFCore 2.0.0.
