### ISSUE TITLE
Node.js : YQL is not working

### ISSUE THREAD

**Issue by arafato** [Azure/azure-webjobs-sdk-script#223]
Hi--, 
there is a strange behavior with Azure Cloud Functions when using the YQL package of Node.js like so:
```
var YQL = require('yql');
module.exports(context, myTimer) {
   new YQL.exec('some query', function (response) {
     // this code is never reached, function never terminates 
     context.done();
   });
}
```
If I execute the same code through the web-based console of the Azure portal, everything works fine. Any clues why this is happening? Thanks!

**Comment by christopheranderson** [comment]
Did you add the package to your node_modules folder?

**Comment by arafato** [comment]
Yes I did. I've traced it down to one particular call within the YQL library: something seems to go wrong when YQL is doing a HTTP(s) request via the module 'request'. This is where the function gets stuck for some reason. 
As I said, if I invoke the same code on the KUDU console (via npm test -> I've written a unit test that also executes YQL.exec) everything works fine. Strange, isn't it?

**Comment by arafato** [comment]
Yes I did. I've traced it down to one particular call within the YQL library: something seems to go wrong when YQL is doing a HTTP(s) request via the module 'request'. This is where the function gets stuck for some reason. 
As I said, if I invoke the same code on the KUDU console (via npm test -> I've written a unit test that also executes YQL.exec) everything works fine. Strange, isn't it?

**Comment by christopheranderson** [comment]
We think we have a fix for this. We'll test against it soon.

**Comment by mathewc** [comment]
@christopheranderson What was the fix for this?

**Comment by brettsam** [comment]
PR #486 works around this issue (see #241 for more details). If you want to get things working before this change is deployed to production, you can add this to the your code before you make the call to YQL: `process.nextTick = global.setImmediate;`
