### ISSUE TITLE
How to start triggered job in code?

### ISSUE THREAD

**Issue by joshidp** [Azure/azure-webjobs-sdk-script#2235]
Hi,

I have created a JobHost and when I do host.RunAndBlock(); it runs the function method and the main thread is blocked for eternity.  When I use host.Start() it immediately comes out of the main thread.

Please suggest how to start and wait for the function to complete and then exit the main thread?

Thanks

**Comment by dallancarr** [comment]
It sounds like you want to manually trigger the function either from the portal or via code.

**Comment by joshidp** [comment]
Yes. You are correct. How should I use job host in this case?

**Comment by dallancarr** [comment]
You can have it blocking and initiate via http.

**Comment by joshidp** [comment]
How can have JobHost as blocking? RunAndBlock blocks it for forever and Start doesn't wait for the function to complete. Any sample would be highly appreciated.

Thanks

**Comment by christopheranderson** [comment]
We don't have any mechanism today to trigger one Function from another without making an HTTP request or some intermediate messaging service (queues). You can use HTTP triggered Functions and have them call each other. If it can by async, I'd recommend using Storage Queues.
