### ISSUE TITLE
Improve error message received when running against stopped storage emulator

### ISSUE THREAD

**Issue by paulbatum** [Azure/azure-webjobs-sdk-script#2237]
The VS templates for functions allow users to use the storage emulator. However if the user attempts to run the functions without the storage emulator running, they get a non obvious error:

```
The listener for function 'Function1' was unable to start.
The listener for function 'Function1' was unable to start. mscorlib: One or more errors occurred. Microsoft.Azure.WebJobs.Host: Invalid storage account 'devstoreaccount1'. Please make sure your credentials are correct
```

For more info see:
https://github.com/Azure/azure-webjobs-sdk-script/issues/2183#issuecomment-352276986

In this case we should print a helpful message such as "Please verify that the Azure Storage Emulator is running."

**Comment by kashimiz** [comment]
Observed in both V1 and V2.
