### ISSUE TITLE
Azure Function CLI breaks binding redirect for Microsoft.IdentityModel.Clients.ActiveDirectory

### ISSUE THREAD

**Issue by mmaitre314** [Azure/azure-webjobs-sdk-script#2240]
I am hitting a binding-redirect failure in my C# Azure Function:

```
[12/19/2017 9:07:02 PM] A ScriptHost error has occurred
[12/19/2017 9:07:02 PM] Exception while executing function: Master6. TestFunctionStreamWarmPath: Could not load file or assembly 'Microsoft.IdentityModel.Clients.ActiveDirectory, Version=3.17.2.31801, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. Could not find or load a specific file. (Exception from HRESULT: 0x80131621). System.Private.CoreLib: Could not load file or assembly 'Microsoft.IdentityModel.Clients.ActiveDirectory, Version=3.17.2.31801, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
```

I tried putting binding redirects in place in my function code but the event `AppDomain.CurrentDomain.AssemblyResolve` does not fire. Using `Assembly.LoadWithPartialName("Microsoft.IdentityModel.Clients.ActiveDirectory")` to debug the load failure, it returns version `3.16.0.14` which comes from Azure Function CLI instead of my project: `C:\Users\mmaitre\AppData\Local\Azure.Functions.V2.Cli\2.0.1-beta\Microsoft.IdentityModel.Clients.ActiveDirectory.dll`

How can I tell the Host to load my version of that DLL and not its own?

#### Investigative information

Please provide the following:

- Timestamp: 12/19/2017 9:07:02 PM
- Function App version (1.0 or 2.0-beta): 2.0.1-beta
- Function App name: TestStreamWarmPath
- Function name(s) (as appropriate): Master
- Invocation ID: <none> (local debugging)
- Region: <none> (local debugging)

#### Repro steps

Provide the steps required to reproduce the problem:
1. Hit F5 in Visual Studio

#### Expected behavior

No exception and the DLL gets loaded from `bin\Debug\netstandard2.0\bin`.

#### Actual behavior

Function fails to start.

#### Known workarounds

Maybe downgrading the package version to align my project with the Azure Function CLI. The CLI version is much older though.

#### Related information 

* Programming language used: C#
* Bindings used: `TimerTrigger`

**Comment by christopheranderson** [comment]
This issue was moved to Azure/azure-functions-cli#351
