### ISSUE TITLE
Regular throughput troughs in Azure functions requests per second.

### ISSUE THREAD

**Issue by JamesDuggan** [Azure/azure-webjobs-sdk-script#2242]
Running an Azure function in Consumption Plan mode and seeing regular troughs in throughput. This is after stripping out all external dependencies such that function execution is predictable, as in, receive single event from event hub, create a new event hub message, and write back to (source) event hub via IAsyncCollector parameter.

A timeline of function requests per sec is attached to StackOverflow question https://stackoverflow.com/questions/47712535/regular-throughput-troughs-in-azure-functions-requests-per-second

#### Investigative information

Please provide the following:

- Timestamp: 2017-12-07T23:45:21.8Z
- Function App version (1.0 or 2.0-beta):
- Function App name: 
- Function name(s) (as appropriate): 
- Invocation ID: b673d913-fd92-4bbf-b9e0-b603e327b288
- Region: EUW

**Comment by christopheranderson** [comment]
//cc @paulbatum

**Comment by paulbatum** [comment]
@JamesDuggan Sorry it looks like we missed this issue over the break and unfortunately the timeframe as fallen outside of the retention window for the logs we would use to investigate this.

Absent any log analysis, my general advice is you start with applying some of the recommendations in this post: https://blogs.msdn.microsoft.com/appserviceteam/2017/09/19/processing-100000-events-per-second-on-azure-functions/

Specifically:
1. Disable the webjobs dashboard 
2. Make sure you set your partition count appropriately (it acts as an upper limit on how many VMs can process your function concurrently)
3. Use batching (write your function to take `EventData[]` instead of `EventData`)

**Comment by JamesDuggan** [comment]
That looks a really useful post.

Since the behaviour is easy to recreate I will redo and then apply the recommendations in the post, and then feedback.

Immediately I see that batching will be problematic. By design I require the function to perform a single discrete action based on a single event hub message. It is clear to me why batching will improve overall performance. Not clear to me why it would impact the regular troughs in requests/sec that I see.

Thanks

**Comment by JamesDuggan** [comment]
I have looked into throughput uplift by disabling the web jobs dashboard and increasing the event hubs partition count. There is a clear uplift when I disable the web jobs dashboard. Not so for increasing event hubs partition count. Using "summarize VMCount=dcount(cloud_RoleInstance)" I get a result of 1. 

I have tried 4 and 10 partitions. I have upgraded from basic to standard. Each to no avail. How should Event Hubs / Azure Functions be configured?

Timestamp: 
     From 2018-01-29T20:35:19.408Z to 2018-01-29T22:00:00.000Z
Invocation ID: 55aba460-497c-4833-b7b0-6bec8dc70f68
Region: EUW

Thanks

James

**Comment by paulbatum** [comment]
I looked at our logs. High level, it looks like there was not enough load to trigger the system to scale out. The way to think about the partitions is they put an upper limit on how far the system -could- scale if it decided it was necessary. 

Are the performance results you got from your last run, with dashboard disabled, satisfactory?

**Comment by JamesDuggan** [comment]
What I am hearing is that all I have to do is configure the default Event Hubs consumer with, for example, 10 partitions. Azure Functions can then under load scale out to max 10 VMs. That makes a lot of sense. 
The performance I have been getting has been fine. This has really been about understanding throughput troughs and how to iron them out.

**Comment by paulbatum** [comment]
Great. From that perspective, it sounds like we can close this issue since the webjobs dashboard was the main cause. Do you agree?

**Comment by JamesDuggan** [comment]
Agreed

**Comment by JamesDuggan** [comment]
I have look at partitions and scale out. What I am seeing is the number of VMs being set at function app start / restart and not scale according to workload. 
For example:
2 VMs for small workload 
   from 2018-01-30T13:26:25.153Z to 2018-01-30T13:30:00.000Z
   invocation id: c234ba57-384c-4521-bbbf-8c09064920a4

I then restarted the function app and regardless of increase in workload the VM count stubbornly remains at 1

2x workload
   from 2018-01-30T13:51:38.885Z to 2018-01-30T14:00:00.004Z
   invocation id: 163c38c5-e55c-4690-974a-d6c21d9278bc

8x workload
   from 2018-01-30T14:00:38.95Z to 2018-01-30T14:10:00.004Z
   invocation id: 0535d0ff-16e8-46a7-8592-ce1ddf42dd0b

**Comment by JamesDuggan** [comment]
I am going to close this.
