### ISSUE TITLE
C# Functions with out parameters can't be made async

### ISSUE THREAD

**Issue by mistakenot** [Azure/azure-webjobs-sdk-script#2246]
Apologies if this is not in the correct place.

I'm creating C# Functions via the Azure Portal. One function I've created receives an Http Post Request, creates an entity in Table Storage, then finally fires off an email using a SendGrid output.

The function signature looks like this:
```
public static HttpResponseMessage Run(
    HttpRequestMessage req, 
    ICollector<ApiKeyRow> apiKeyTable,
    TraceWriter log,
    out Mail message)
{
    ...
```
Where `apiKeyTable` is the Table Storage table I'm writing to.

Something that I've noticed is that because the SendGrid integration uses an `out` parameter, the function can no longer be `async`, which means I'm having to block on reading the Http request.

Was this an active design decision? Are there advantages to using an `out` parameter for the SendGrid integration that you couldn't of achieved by using something like a `ICollector<Mail>` parameter? Or am I using this the wrong way?

Thanks for you help.

**Comment by christopheranderson** [comment]
This is a C# functionality issue, not Functions. We didn't make the decision to not allow out parameters in C# functions. See this MSDN article discussing return types. You can see that it is generally not allowed in C# with async methods. https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/async/#BKMK_ReturnTypesandParameters

**Comment by fabiocav** [comment]
To add, to work around the limitation, you can follow the same approach you're following with table (using ICollector or IAsyncCollector) with SendGrid as well. Which would allow you to have a fully async function.

**Comment by mistakenot** [comment]
Thanks, didn't know that.
