### ISSUE TITLE
Running the 2.0.1-beta.20 Functions Runtime via dotnet.exe throws AccessViolationException

### ISSUE THREAD

**Issue by fabiocav** [Azure/azure-webjobs-sdk-script#2289]
_From @bzhu94 on January 4, 2018 2:12_

#### Repro steps

Repro Machine: WNVM 24597 (might be deallocated within a few days from when this issue was posted)

Provide the steps required to reproduce the problem

1. Install the latest preview Visual Studio with the Azure and Web Development workloads on a Windows 7 machine (this issue might repro for OS's, which I have not yet tried.)

2. Create a new Azure Functions project. This dialog should pop up. Select Azure Functions v2 in the dropdown and Http trigger in the template picker below:

![image](https://user-images.githubusercontent.com/8541576/34547532-99c145ac-f0b0-11e7-8154-a7ba2a2455b7.png)

3. Build the project.

4. Have the 2.0.1-beta.20 Functions runtime folder somewhere on disk.

5. Run the command `dotnet "YourPathToRuntimeFolder\Azure.Functions.Cli.dll" host start --port 7071 --pause-on-error` on a normal cmd prompt. 

#### Expected behavior

The runtime should run indefinitely (until we exit the command or close the command prompt window)

#### Actual behavior

The runtime exits out after initializing like so: 

![image](https://user-images.githubusercontent.com/8541576/34547596-1ebb534c-f0b1-11e7-98fd-542b134e073a.png)

#### Known workarounds

None

#### Related information 

When debugging via Visual Studio, the exception is:

`System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.`

The stack trace:

```
 	[Managed to Native Transition]	
>	Microsoft.Azure.WebJobs.Script.dll!Microsoft.Azure.WebJobs.Script.Rpc.JobObjectRegistry.JobObjectRegistry()	Unknown
 	Microsoft.Azure.WebJobs.Script.dll!Microsoft.Azure.WebJobs.Script.Rpc.ProcessRegistryFactory.Create()	Unknown
 	Microsoft.Azure.WebJobs.Script.dll!Microsoft.Azure.WebJobs.Script.ScriptHost.Initialize()	Unknown
 	Microsoft.Azure.WebJobs.Script.dll!Microsoft.Azure.WebJobs.Script.ScriptHost.Create(Microsoft.Azure.WebJobs.Script.IScriptHostEnvironment environment, Microsoft.Azure.WebJobs.Script.Eventing.IScriptEventManager eventManager, Microsoft.Azure.WebJobs.Script.ScriptHostConfiguration scriptConfig, Microsoft.Azure.WebJobs.Script.Config.ScriptSettingsManager settingsManager, Microsoft.Azure.WebJobs.Script.ILoggerFactoryBuilder loggerFactoryBuilder, Microsoft.Azure.WebJobs.Script.Description.ProxyClientExecutor proxyClient)	Unknown
 	Microsoft.Azure.WebJobs.Script.dll!Microsoft.Azure.WebJobs.Script.ScriptHostFactory.Create(Microsoft.Azure.WebJobs.Script.IScriptHostEnvironment environment, Microsoft.Azure.WebJobs.Script.Eventing.IScriptEventManager eventManager, Microsoft.Azure.WebJobs.Script.Config.ScriptSettingsManager settingsManager, Microsoft.Azure.WebJobs.Script.ScriptHostConfiguration config, Microsoft.Azure.WebJobs.Script.ILoggerFactoryBuilder loggerFactoryBuilder)	Unknown
 	Microsoft.Azure.WebJobs.Script.dll!Microsoft.Azure.WebJobs.Script.ScriptHostManager.RunAndBlock(System.Threading.CancellationToken cancellationToken)	Unknown
 	Microsoft.Azure.WebJobs.Script.WebHost.dll!Microsoft.Azure.WebJobs.Script.WebHost.WebScriptHostManager.RunAsync.AnonymousMethod__0()	Unknown
 	System.Private.CoreLib.dll!System.Threading.Tasks.Task.InnerInvoke()	Unknown
 	System.Private.CoreLib.dll!System.Threading.Tasks.Task..cctor.AnonymousMethod__276_1(object obj)	Unknown
 	System.Private.CoreLib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state)	Unknown
 	System.Private.CoreLib.dll!System.Threading.Tasks.Task.ExecuteWithThreadLocal(ref System.Threading.Tasks.Task currentTaskSlot)	Unknown
 	System.Private.CoreLib.dll!System.Threading.Tasks.Task.ExecuteEntryUnsafe()	Unknown
 	System.Private.CoreLib.dll!System.Threading.Tasks.Task.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()	Unknown
 	System.Private.CoreLib.dll!System.Threading.ThreadPoolWorkQueue.Dispatch()	Unknown
 	System.Private.CoreLib.dll!System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()	Unknown
```

_Copied from original issue: Azure/azure-webjobs-sdk#1489_

**Comment by fabiocav** [comment]
The stack points to an issue with JobObject creation in the language extensibility feature code.

Might be a Windows 7- issue, needs investigation.

**Comment by paulbatum** [comment]
@bzhu94 do you have a repro of this on windows 10? I intend to close this as won't fix if its a windows 7 specific issue.

**Comment by paulbatum** [comment]
Closing due to a lack of further information. Please reopen and/or comment if there is up to date repro information for this on Windows 10.
