### ISSUE TITLE
Q: Why is suave referenced? 

### ISSUE THREAD

**Issue by forki** [Azure/azure-webjobs-sdk-script#23]
I noticed that you reference a couple of libs that are far more common in the F# world (suave, FsPickler, fsharp.core - see https://github.com/Azure/azure-webjobs-sdk-script/blob/master/src/WebJobs.Script.Host/packages.config), but you don't seem to use these yet. 

Are you planning to create a F# specific version?

**Comment by mathewc** [comment]
Thanks for reminding me to remove those old references :)

Previously we were referencing the beta WebHooks extension (in the [extensions repo](https://github.com/Azure/azure-webjobs-sdk-extensions)). However in the current design, we now handle HTTP accessibility / WebHooks in a better way. The beta WebHooks extension is using a self-host HTTP listener implemented in F# to get around  Azure WebApp sandbox restrictions.

**Comment by mathewc** [comment]
Addressed by https://github.com/Azure/azure-webjobs-sdk-script/commit/588538c83a53c3d66f75fbf84bf1b91b1b51935f
