### ISSUE TITLE
Proxies suddenly stopped working, returning 404

### ISSUE THREAD

**Issue by mlowijs** [Azure/azure-webjobs-sdk-script#2315]
After using proxies for a couple of weeks, they suddenly stopped working. Every request is now returning 404. The backend URLs work fine when called directly.

#### Investigative information

- Timestamp: 2018-01-16 08:45+01:00 (ongoing)
- Function App version (1.0 or 2.0-beta): 1.0 (same issue in beta)
- Function App name: ddwdfun01
- Function name(s) (as appropriate): all proxies
- Invocation ID: unknown
- Region: westeurope

#### Repro steps

1. Send a POST request to `https://ddwdfun01.azurewebsites.net/id/Connect/Token`.
2. Send a POST request to `http://ddwdsfc01.westeurope.cloudapp.azure.com:9050/Connect/Token`

#### Expected behavior

In step 1, when called without any headers or body, a HTTP 400 response (Bad Request) should be observed with body `{"error":"invalid_client"}`. This can be verified in step 2.

#### Actual behavior

After step 1, a HTTP 404 error is returned with no body.

#### Known workarounds

None.

### Related information:
My `proxies.json` file:

```js
{
    "$schema": "http://json.schemastore.org/proxies",
    "proxies": {
        "IdentityServer": {
            "matchCondition": {
                "route": "/id/{*path}"
            },
            "backendUri": "http://ddwdsfc01.westeurope.cloudapp.azure.com:9050/{path}"
        },
        "Auth": {
            "matchCondition": {
                "route": "/auth/{*path}"
            },
            "backendUri": "http://ddwdsfc01.westeurope.cloudapp.azure.com:9051/{path}"
        },
        "Organizations": {
            "matchCondition": {
                "route": "/org/{*path}"
            },
            "backendUri": "http://ddwdsfc01.westeurope.cloudapp.azure.com:9052/{path}"
        },
        "Core": {
            "matchCondition": {
                "route": "/core/{*path}"
            },
            "backendUri": "http://ddwdsfc01.westeurope.cloudapp.azure.com:9053/{path}"
        }
    }
}
```

**Comment by mlowijs** [comment]
Found it. The `X-Ms-Ext-Routing` header does not seem to be passed to the backend URL anymore, which I was using to execute some hack code to fix the request URL path:

```csharp
app.Use((context, next) =>
{
    if (context.Request.Headers.ContainsKey("x-ms-ext-routing"))
        context.Request.Path = new PathString(context.Request.Path.Value.Replace("%2F", "/"));

    return next();
});
```

**Comment by safihamid** [comment]
Yes x-ms-ext-routing was an implementation detail and we no longer use it with the latest release. you should not have taken a dependency on that :-).
