### ISSUE TITLE
host.json is not published to Azure

### ISSUE THREAD

**Issue by Anufriev** [Azure/azure-webjobs-sdk-script#2322]
#### Investigative information

- Function App version 1.0
- Microsoft.NET.Sdk.Functions 1.0.7

#### Repro steps

1. Create .NET 4.7 Function app
2. Update host.json. For example,
`{
  "queues": {
    "maxPollingInterval": 2000,
    "visibilityTimeout": "00:00:30",
    "batchSize": 2,
    "maxDequeueCount": 5,
    "newBatchThreshold": 1
  }
}`
3. Publish to azure via VS 2017 15.5.4

#### Expected behavior

funcname.scm.azurewebsites.net/dev/wwwroot should contain my host.json file.

#### Actual behavior

funcname.scm.azurewebsites.net/dev/wwwroot doesn't contain my host.json file.

**Comment by paulbatum** [comment]
@Anufriev I tried reproducing this a few times with no success. My environment details match what you listed:

- v1 Function app
- net 4.7
- Microsoft.NET.Sdk.Functions 1.0.7
- VS 15.5.4

Here are the rest of my details:
- Functions and Web Jobs Tools 15.0.40108
- published to a brand new function app created through the azure portal

When I publish, I can see host.json in the log:
```
 Publish Started
  FunctionApp26 -> C:\Users\pbatum\source\repos\FunctionApp26\bin\Release\net47\bin\FunctionApp26.dll
C:\Users\pbatum\.nuget\packages\microsoft.net.sdk.functions\1.0.7\build\netstandard1.0\Microsoft.NET.Sdk.Functions.Build.targets(32,5): warning :  [C:\Users\pbatum\source\repos\FunctionApp26\FunctionApp26.csproj]
  FunctionApp26 -> C:\Users\pbatum\source\repos\FunctionApp26\obj\Release\net47\PubTmp\Out\
C:\Users\pbatum\.nuget\packages\microsoft.net.sdk.functions\1.0.7\build\netstandard1.0\Microsoft.NET.Sdk.Functions.Publish.targets(142,5): warning :  [C:\Users\pbatum\source\repos\FunctionApp26\FunctionApp26.csproj]
  Updating file (pbfuncapp26\bin\FunctionApp26.dll).
  Updating file (pbfuncapp26\bin\FunctionApp26.pdb).
  Updating file (pbfuncapp26\Function1\function.json).
  Updating file (pbfuncapp26\functionsSdk.out).
  Updating file (pbfuncapp26\host.json).
  Publish Succeeded.
```


Can you let me know whether you are still reproing with the same version of the tools and a brand new function app?

**Comment by paulbatum** [comment]
Also please paste the output from your publishing log as I did above.

**Comment by Anufriev** [comment]
@paulbatum I'm sorry for the delay.
I have found the root of the trouble.

I don't know why and how but my VS added section Update=host.json 2 times.
And 2th section is very strange.

`<None Update="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    `

It started to work as expected after I removed 2th section.
