### ISSUE TITLE
SecretManagerTests intermittently fail

### ISSUE THREAD

**Issue by christopheranderson** [Azure/azure-webjobs-sdk-script#2324]
There is a race condition in our tests where some tests set the InstanceId property in the Configuration object which interferes with the SecretManagerTests.

**Comment by fabiocav** [comment]
Yes. Known issue with the tests. Haven't addressed because we were supposed to refactor how that is working with the DI features, but that was delayed.

**Comment by christopheranderson** [comment]
I've got a fix out. See #2325

**Comment by fabiocav** [comment]
Will take a look. But hadn't bothered fixing it because it was going to be throw away.

**Comment by christopheranderson** [comment]
It wastes a lot my time retrying builds, so I spent 30 minutes figuring out what code path caused it. Simple fix. Just avoid using the singleton SettingsManager

**Comment by fabiocav** [comment]
Looked at it and that's fine for this specific issue, but doesn't address the root cause. We've put a couple of targeted fixes like this in a couple of different tests, but that works around the problem and introduces fragility with shared state.
