### ISSUE TITLE
Fix ServiceBus attribute binding

### ISSUE THREAD

**Issue by alrod** [Azure/azure-webjobs-sdk-script#2329]
https://github.com/Azure/azure-webjobs-sdk-script/blob/v1.x/src/WebJobs.Script/Binding/ServiceBusScriptBindingProvider.cs was removed in V2.

We need to make sure ServiceBus binding works properly with "binding.json" definition.

**Comment by fabiocav** [comment]
Mind adding some details about the issue?

**Comment by alrod** [comment]
PR: https://github.com/Azure/azure-webjobs-sdk/pull/1497
