### ISSUE TITLE
Mobile tables binding with authentication

### ISSUE THREAD

**Issue by soninaren** [Azure/azure-webjobs-sdk-script#233]
moving the issue over from templates repo.

https://github.com/Azure/azure-webjobs-sdk-templates/issues/135

 > From: @ggailey777
>  Consider that I have an existing easy table that I am using with my mobile apps, which I have protected with authentication because an API key IS NOT a security token since it's getting distributed with my mobile apps onto devices and it can be obtained.
>  
>  How can I get my Azure Function to access my easy table by using authentication, or will this never be a supported scenario?
>  
>  From: @fabiocav 
>  Currently, it can't. The API key exposed by Functions is to support integration scenarios with trusted systems and it is to be kept private/secure. The API key support added to easy tables is to validate requests from Azure Functions. We should not recommend using either of those keys on any mobile or other distributed client applications.
>  Keep in mind that mobile clients can continue to use the Mobile Apps APIs following the standard authentication process. Enabling API key use on a particular table doesn't mean that the clients need to use that key for auth.
>  Easy Auth support and improving how the tokens flow to work into easy tables is definitely the goal, but those are backlog items at this point.

**Comment by paulbatum** [comment]
Should we close this? As explained by @fabiocav the API key the function is using to authenticate with the easy table should stay private and not be on the device. Is there a concrete scenario that is currently blocked?

**Comment by ggailey777** [comment]
@paulbatum @fabiocav just to confirm. If I have a table endpoint that I have secured with, say, Microsoft Account, I can still access it using the API key from a function and I do not have to supply an OAuth token? If that is the case, we can close this issue.

**Comment by mattchenderson** [comment]
Still need to provide an OAuth token in this case. With AAD we would do this using a service principal or a delegated access flow. For the social providers, a server-side-only key would be an option. As mentioned above, you'd never want this bundled in the client.

**Comment by ggailey777** [comment]
So it sounds like I can't have the same table endpoint used by both mobile clients and functions.

**Comment by fabiocav** [comment]
You can. I think we should probably have some documentation/samples on that, but you can have an endpoint behave as it normally does from an auth perspective **and** accept the API key when called from functions, allowing that to go through.

**Comment by ggailey777** [comment]
@fabiocav yes, it would probably be good to have an example like this. Glad to hear that the scenario works. You can close the issue, unless you want to use it to track samples/docs.

**Comment by mattchenderson** [comment]
Clarifying on my comment above - the API key flow we have would work since it introduces a dummy user. I had forgotten this and was thinking we still had an API key authorization level, which is not the case. So if you have user level authentication, you could use a service principal (functions), an actual user principal (mobile client), or an API key (functions).

**Comment by mathewc** [comment]
So based on the above, it sounds like we can close this issue. Please reopen if this is not the case.
