### ISSUE TITLE
Service Bus Trigger Only creates new Subscription If AccessRights=Manage

### ISSUE THREAD

**Issue by mandarsj** [Azure/azure-webjobs-sdk-script#2332]
I am writing Azure function listening to Azure Service Bus topics. and seeing strange behaviour. 

If I have service Bus connection string with only "Listen" Rights and use it as Connection setting in Service Bus trigger. I always get error, saying "Endpoint not found."

If I use Manage access permissions, then subscription is created and it works great.

Surely If client has only Listen Permissions, it should be able to create new subscription?

**Comment by brettsam** [comment]
`Manage` is required to make changes to Service Bus (like creating subscriptions). See this list for the required rights: https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-sas#rights-required-for-service-bus-operations
