### ISSUE TITLE
Logs not appearing in Application Insights

### ISSUE THREAD

**Issue by brettsam** [Azure/azure-webjobs-sdk-script#2335]
Spun this off from another post by @KZeronimo.

How do we wire in Application Insights Logging Provider for ILogger - trying to avoid using Telemetry Client directly and we can't seem to get this to work

This snippet runs and we can see logs in Application Insights for function execution start and function executed successfully but we have no idea where log.Log(LogLevel.Trace, 0, state, null, Formatter) is being written

Here is the expanded snipped

```
 public static class AzureFunctionsLogging
    {
        [FunctionName("Logging")]
        public static void Run([TimerTrigger("0 */1 * * * *")]TimerInfo myTimer, ILogger log)
        {
            var state = new Dictionary<string, object> {
                    {"CorrelationId", 1} ,
                    {"Message", "This is a custom log message"}
                };

            log.Log(LogLevel.Trace, 0, state, null, Formatter);
        }

        internal static string Formatter<T>(T state, Exception ex)
        {
            if (ex != null)
            {
                return ex.ToString();
            }

            var stateDictionary = state as Dictionary<string, object>;
            if (stateDictionary != null && stateDictionary.TryGetValue("Message", out object message))
            {
                return message.ToString();
            }
            return string.Empty;
        }

    }
```

**Comment by brettsam** [comment]
@KZeronimo -- what does your host.json look like? Are you changing anything in the `logger` section?

```
"logger": {
        "categoryFilter": {
            "defaultLevel": "Information",
            "categoryLevels": {
                "Host": "Error",
                "Function": "Error",
                "Host.Aggregator": "Information"
            }
        }
    }
```

By default, only `Information` and above log levels will be logged. `Trace` is the most verbose level, so it's likely getting filtered out. Try logging with `LogLevel.Information` and see if it shows up.

LogLevel details: https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?tabs=aspnetcore2x#log-level

**Comment by KZeronimo** [comment]
@brettsam we were getting filtered out by _categoryLevels -> Function being set to Error_ - now we have the following which works as expected

```
{
  "logger": {
    "categoryFilter": {
      "defaultLevel": "Information",
      "categoryLevels": {
        "Host.Results": "Error",
        "Function": "Trace",
        "Host.Aggregator": "Information"
      }
    },
    "aggregator": {
      "batchSize": 1000,
      "flushTimeout": "00:00:30"
    }
  },
  "applicationInsights": {
    "sampling": {
      "isEnabled": true,
      "maxTelemetryItemsPerSecond": 5
    }
  }
}
```

In addition, we found these 3 resource were helpful as well [ILogger Wiki](https://github.com/Azure/azure-webjobs-sdk-script/wiki/ILogger), [Azure-Functions App Insights Wiki](https://github.com/Azure/Azure-Functions/wiki/App-Insights), [Monitor Azure Functions](https://docs.microsoft.com/en-us/azure/azure-functions/functions-monitoring)

Thank you for your help

**Comment by cmeiklejohn** [comment]
It's unclear from the thread -- was there ever a resolution to getting this working with .NET 4.6.1?  I only saw that @KZeronimo has it working with .NET 4.7.  I'm also running into the same issue:

```
Microsoft.Azure.WebJobs.Host: Error indexing method 'EventHubsFunctions.Process3'. Microsoft.Azure.WebJobs.Host: Cannot bind parameter 'log' to type ILogger. Make sure the parameter Type is supported by the binding. If you're using binding extensions (e.g. ServiceBus, Timers, etc.) make sure you've called the registration method for the extension(s) in your startup code (e.g. config.UseServiceBus(), config.UseTimers(), etc.).
```

**Comment by cmeiklejohn** [comment]
Oops, I believe I left this comment on the wrong thread.
