### ISSUE TITLE
"The function runtime is unable to start"

### ISSUE THREAD

**Issue by sergsalo** [Azure/azure-webjobs-sdk-script#2344]
We frequently receive this error for our function:

> The function runtime is unable to start.
> 
> Session Id: fd5ade68ca494eb7af2b281c468c5b15
> Timestamp: 2018-01-23T00:48:44.670Z

We have 12 triggers and our app is on consumption plan. I wonder what the issue might be - too many functions? It works sporadically... app sometimes just terminates.

**Comment by mathewc** [comment]
Can you please share details as per https://github.com/Azure/azure-webjobs-sdk-script/wiki/Sharing-Your-Function-App-name-privately so we can investigate?

**Comment by sergsalo** [comment]
the name of the function is ampmonitoring-dev-westus

**Comment by sergsalo** [comment]
I believe there is some issue with my subscription... it worked in different subscription. I'll close this one.

**Comment by Anufriev** [comment]
Hi! I have got the same error 2 times.
It happens when my function app tries  to use queue from another azure region.

**Comment by giemch** [comment]
We're getting this today for one of our function apps. Unfortunately there doesn't appear to be anything in the logs, so I'm unable to do the share your private function tip. Luckily this function isn't in production yet, but if this happens in production are we pretty much SOL? I tried restarting, but didn't help. Seems like another instance of the function app should be spun up on a new vm automatically when this happens. Are there benefits to using app service plan vs consumption plan in that regard?

**Comment by paulbatum** [comment]
It should not be possible for you to get this error without there being additional details in the log. Have you got app insights enabled? If not please enable it and then look at the contents of the `traces` table.

If you are still unable to diagnose please file a new issue with the information in our issue template so we can look at our logs and investigate.

**Comment by giemch** [comment]
@paulbatum Yes, AI is enabled and I looked at the traces table, but there's nothing with a severity level > 1 in the past 7 days. We opened a ticket (118040517948607) with support today. Thanks.

**Comment by giemch** [comment]
@paulbatum It was failing because there was an IP restriction set. We had a single entry pointing to our APIM instance IP. Are there some additional Azure IP(s) that needs to be included in the whitelist?

**Comment by giemch** [comment]
@paulbatum Sorry, I'll move this to a new issue.
