### ISSUE TITLE
Azure Functions Costs

### ISSUE THREAD

**Issue by stap123** [Azure/azure-webjobs-sdk-script#2349]
Hi guys,

Not sure if this is the correct place to ask this but I've run out of google results to read.

Is there a way to see how much an individual function is costing to run  within the month? I want to know (on average is fine) how much it costs to run function A compared to function B. I can't seem to find out where this information is located.  I love the idea behind Functions but without being able to quantify the costs I'll be unable to get buy in from anyone.

Any help would be much appreciated.

**Comment by brettsam** [comment]
We don't currently have the ability to show you per-function billing. However, you could try to create two function apps, each with one function and compare those. You can access your function execution units here: https://stackoverflow.com/questions/41128329/how-can-i-programmatically-access-azure-functions-usage-metrics.

Adding more granular billing details is logged here, so I'll close this one as a dupe: https://github.com/Azure/azure-webjobs-sdk-script/issues/1451.
