### ISSUE TITLE
Refactor invokers to avoid directly using IBinder

### ISSUE THREAD

**Issue by fabiocav** [Azure/azure-webjobs-sdk-script#236]
Creating this issue to track the work to refactor the invokers to work similar to the way the C# invoker works and avoid the calls to `BindAsync`.

**Comment by christopheranderson** [comment]
Is this still in progress? @fabiocav Is this important for RC?

**Comment by fabiocav** [comment]
Yes, it is. I've merged the extensibility changes into my work and I'm finalizing a couple of things that were broken in the process. I need to follow up with @mathewc as we have some issues that require updates to the core WebJobs SDK and won't be able to match the current functionality without those (things like named parameters and binding data don't work as expected). We need to make a decision on how we'll handle and prioritize this work to understand whether or not we'll target RC for this change. I would like for that to be the case.

**Comment by mathewc** [comment]
Yes, I think whatever work we do will be for RC. I want to get the core SDK work done to enable this (add an Http binding extension, support JObject across bindings, etc.).

**Comment by fabiocav** [comment]
This work has been put on hold since the some of the key driving factors have been addressed by other changes. Closing issue.
