### ISSUE TITLE
HttpTrigger missing

### ISSUE THREAD

**Issue by grahamehorner** [Azure/azure-webjobs-sdk-script#2362]
I've installed a AzureFunctions Runtime on a local development system and I'm able to access the web portal; however the UI is missing the HttpTrigger ? 

https://github.com/Azure/azure-webjobs-sdk-script/wiki/Azure-Functions-runtime-2.0-known-issues

**Comment by pragnagopa** [comment]
I just created a V2 FunctionApp from portal and I can see HTTPTrigger in the UI.   If you have published function app from Visual Studio,  the content is read only and this is by design.

**Comment by grahamehorner** [comment]
@pragnagopa I'm a local deployment of AzureFunctions Runtime Preview 2; not AzureFunctions get a little confusing, but I've seen some resources online stating the HTTP Triggers are installed; but I have it on good authority that HTTP Trigger are not currently supported with AzureFunctions Runtime Preview 2 ?
