### ISSUE TITLE
Allow for extending currently registered logger providers

### ISSUE THREAD

**Issue by kamil-mrzyglod** [Azure/azure-webjobs-sdk-script#2365]
Hi,

Are there any ideas/ongoing work regarding extending `ILoggerFactory`, so it's possible to pass a custom logger to be used along with already registered ones?

Currently there's `ILogger` interface available, which can be used instead of `TraceWriter`, but still one is unable to use any other kind of logging solution besided in-built monitor and Application Insights.

I'm aware of the fact, the it's possible to provide a custom extension and use it along with a function - I'd like to know whether it's the only possibility for now?

Best regards,
Kamil

**Comment by pragnagopa** [comment]
We are tracking an an tracking item for this issue: #1579. Here is a related [issue](https://github.com/Azure/Azure-Functions/issues/293) that has information on using ILogger instead for TraceWriter.
