### ISSUE TITLE
Improve ScriptHost Function "Swapability"

### ISSUE THREAD

**Issue by mathewc** [Azure/azure-webjobs-sdk-script#237]
This would require a bunch of work in the core SDK. Currently whenever function metadata changes, it requires us to restart the ScriptHost. This is because in the core SDK, functions are indexed and listeners are started on process startup, and that function set is immutable for the lifetime of the process. That makes sense for classic SDK scenarios.

For Functions however, we'd like more flexibility - we'd like to be able to add/remove functions from the host on the fly, without restarting the host.

**Comment by christopheranderson** [comment]
Is this something which would help mitigate cold start issues? I'm thinking it's only a dev time thing, not necessarily a produciton env thing. Thoughts?

**Comment by mathewc** [comment]
Yeah, it's mainly a dev time thing. Likely this isn't needed for RC - it's an improvement we can make later if needed. Also, it would be quite a bit of work.

**Comment by christopheranderson** [comment]
Cool. Let's punt.

**Comment by mathewc** [comment]
Closing this. We don't need an open issue to track this. We don't have any plans to do this any time soon, and we can reopen this if/when we decide we need to do this.
