### ISSUE TITLE
How to start from source control?

### ISSUE THREAD

**Issue by TheBlueSky** [Azure/azure-webjobs-sdk-script#240]
Hello everyone,

Is there any documentation that describes how to start from source control instead of using the portal.

I tried to replicate the files and folders structure in a git repository and pushed it to my Azure Function, but I got some "mscorelib" error. It seems that the portal does other stuff behind the scene that are not documented... or are they?

**Comment by christopheranderson** [comment]
It's planned, but not done yet. You can checkout a video that covers some details [here](https://channel9.msdn.com/Events/Build/2016/T692); specifically, the 7 minute mark.

As far as your issue goes, are you trying to use NuGet packages or other binaries?

**Comment by mathewc** [comment]
Closing this since this is a doc question/issue.

**Comment by TheBlueSky** [comment]
@christopheranderson, no I'm not using NuGet packages. In fact, I'm using Node.js and pushed all the modules to the remote repository; i.e., my Function repository.
@mathewc, where can I post documentation related issues, requests, questions, and so on?

**Comment by mathewc** [comment]
Our MSDN forum is here: https://social.msdn.microsoft.com/Forums/azure/en-US/home?forum=AzureFunctions
