### ISSUE TITLE
Process crash due to shared file access exceptions

### ISSUE THREAD

**Issue by cgillum** [Azure/azure-webjobs-sdk-script#244]
I'm running a simple scenario where I add a bunch of items to a queue and having a trivial C# function process the messages. I'm only ever running on a single VM. Periodically, it seems the host process crashes, and I see the following in my eventlog.xml:

> An unhandled exception occurred and the process was terminated.
> 
> Application ID: /LM/W3SVC/1961040831/ROOT
> 
> Process ID: 3472
> 
> Exception: System.IO.IOException
> 
> Message: The process cannot access the file 'D:\home\LogFiles\Application\Functions\Host\bd51ad17-edf1-4601-9cd8-dba2800743e4-6dd04c4de4.log' because it is being used by another process.
> 
> StackTrace:    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
>    at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
>    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
>    at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
>    at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
>    at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding)
>    at System.IO.File.InternalAppendAllText(String path, String contents, Encoding encoding)
>    at System.IO.File.AppendAllText(String path, String contents)
>    at Microsoft.Azure.WebJobs.Script.FileTraceWriter.AppendLine(String line)
>    at Microsoft.Azure.WebJobs.Script.FileTraceWriter.Trace(TraceEvent traceEvent)
>    at Microsoft.Azure.WebJobs.Host.CompositeTraceWriter.InvokeTraceWriters(TraceEvent traceEvent)
>    at Microsoft.Azure.WebJobs.Host.CompositeTraceWriter.Trace(TraceEvent traceEvent)
>    at Microsoft.Azure.WebJobs.Host.Loggers.TraceWriterFunctionInstanceLogger.LogFunctionCompletedAsync(FunctionCompletedMessage message, CancellationToken cancellationToken)
>    at Microsoft.Azure.WebJobs.Host.Loggers.CompositeFunctionInstanceLogger.&lt;LogFunctionCompletedAsync&gt;d__8.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.&lt;TryExecuteAsync&gt;d__1.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.Azure.WebJobs.Host.Executors.TriggeredFunctionExecutor`1.&lt;TryExecuteAsync&gt;d__0.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.Azure.WebJobs.Host.Queues.Listeners.QueueTriggerExecutor.&lt;ExecuteAsync&gt;d__1.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.Azure.WebJobs.Host.Queues.Listeners.QueueListener.&lt;ProcessMessageAsync&gt;d__11.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at Microsoft.Azure.WebJobs.Host.Timers.BackgroundExceptionDispatcher.&lt;&gt;c__DisplayClass1.&lt;Throw&gt;b__0()
>    at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
>    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
>    at System.Threading.ThreadHelper.ThreadStart()

Seems like a recent regression since I didn't have this problem last week.

**Comment by mathewc** [comment]
Thanks for reporting. Strange - we're doing locking around all our file writes: https://github.com/Azure/azure-webjobs-sdk-script/blob/master/src/WebJobs.Script/FileTraceWriter.cs#L89

**Comment by cgillum** [comment]
It's also strange because it seems the callstack doesn't match the code, based on what you just showed me.  Specifically, the failure happens under AppendLine(), but in the code you just pointed me to AppendLine doesn't actually do any I/O.

Is there any way to find out which version has been deployed to Azure?

**Comment by mathewc** [comment]
AppendLine was changed two releases ago (in [this commit](https://github.com/Azure/azure-webjobs-sdk-script/commit/60c80e0a3b025edb6b954c2eb807421ce675fe6a)) to do buffering of writes to a ConcurrentQueue - it doesn't do file operations any more (we flush on background thread).

Perhaps you are running old bits in your site, perhaps via a private SiteExtension?

**Comment by cgillum** [comment]
No, I'm definitely not using a SiteExtension, but it does appear that I'm somehow on an old build.  Is there an assembly version or something I can look at to confirm?  This is a private Antares deployment, so I don't know whether it affects public Azure, but my understanding is that all environments get the same bits.

**Comment by cgillum** [comment]
Looks like I actually *was* using a private site extension.  There was a D:\home\SiteExtensions\Functions directory in my app and those were the bits being loaded. I stopped the site, deleted that directory, started the site again, and now I'm using the latest bits.  Not exactly sure how that happened, but for now I'm going to assume this is not a real product issue.

**Comment by mathewc** [comment]
:)
