### ISSUE TITLE
Tooling: Create Yeoman Generator for Function.json

### ISSUE THREAD

**Issue by SyntaxC4** [Azure/azure-webjobs-sdk-script#245]
Considering the finite number of Triggers and Input/Output Bindings, it should be simple to create a Yeoman generated to help scaffold a Function.json file for a local development scenario. There was some feedback in the //Build content regarding this:

> If using source control integration, is it required to create all the files from scratch by hand, or is it somehow possible to create a "starter project" based on an existing function? Are these files exportable somehow? -- [Trond Hindenes](https://channel9.msdn.com/Events/Build/2016/T692#c635954623601842988)

**Comment by christopheranderson** [comment]
I've been thinking about tooling, so I'll factor this into my planning.

**Comment by christopheranderson** [comment]
We have a Yeoman generator now.
