### ISSUE TITLE
Enhance system parameter binding

### ISSUE THREAD

**Issue by fabiocav** [Azure/azure-webjobs-sdk-script#251]
We need to enhance the system parameter binding in two ways:
1. Making sure we're avoiding name collisions. This could be done either by inspecting function parameter names or making sure we use special names that would not allow function compilation (we can also introduce reserved names, which would cause a function compilation error, but we should avoid that if possible)
2. Allow function to use system parameter types. If the function uses an argument that matches a system parameter type (e.g. `ExecutionContext` or `HttpRequestMessage`, in the proper HTTP context), we need to properly bind those parameters.

**Comment by christopheranderson** [comment]
@fabiocav - if you don't think this belongs in backlog, let us know.

**Comment by mathewc** [comment]
Since this might involve adding some naming restrictions, we should do this before GA

**Comment by mathewc** [comment]
Regarding name collisions, we just had a report of this here: https://github.com/Azure/azure-webjobs-sdk-script/issues/504. The user tried to add a parameter named "context" and that resulted in a collision with our system "context" parameter.

**Comment by mathewc** [comment]
I think we've done all the work necessary here. We now prefix system parameters with "_" https://github.com/Azure/azure-webjobs-sdk-script/blob/dev/src/WebJobs.Script/ScriptConstants.cs#L22.
