### ISSUE TITLE
Table Input filter property not properly applying template

### ISSUE THREAD

**Issue by christopheranderson** [Azure/azure-webjobs-sdk-script#260]
## Issue

The filter property for Table Input doesn't apply handlebar templates, like most fields do. 

i.e. filter: "UserId eq {userId}" with input {"userId": 1} doesn't turn into "UserId eq 1"

I get this error:

```
Exception while executing function: Functions.queue-test. Microsoft.WindowsAzure.Storage: The remote server returned an error: (400) Bad Request. System: The remote server returned an error: (400) Bad Request.
```

## Repro

I've tried this with both Queue Trigger and Http Trigger. Here's an example for Queue Trigger

### index.js

```javascript
module.exports = function (context, myQueueItem, users) {
    context.log('Node.js queue trigger function processed work item', myQueueItem);
    context.log(myQueueItem.userid);
    context.log(users);
    context.done();
};
```

### broken function.json

```json
{
  "bindings": [
    {
      "queueName": "items",
      "connection": "<APP SETTING>",
      "name": "myQueueItem",
      "type": "queueTrigger",
      "direction": "in"
    },
    {
      "tableName": "users",
      "partitionKey": "",
      "take": 50,
      "filter": "userid eq {userid}",
      "connection": "<APP SETTING>",
      "name": "users",
      "type": "table",
      "direction": "in"
    }
  ],
  "disabled": false
}
```

### working function.json (that isn't using a template in filter property)

```json
{
  "bindings": [
    {
      "queueName": "items",
      "connection": "<APP SETTING>",
      "name": "myQueueItem",
      "type": "queueTrigger",
      "direction": "in"
    },
    {
      "tableName": "users",
      "partitionKey": "",
      "take": 50,
      "filter": "userid eq 1",
      "connection": "<APP SETTING>",
      "name": "users",
      "type": "table",
      "direction": "in"
    }
  ],
  "disabled": false
}
```

**Comment by mathewc** [comment]
What are "handlebar" templates?

**Comment by christopheranderson** [comment]
The brackets `{}` e.g. `"path": "images-original/{name}"`; aka. mustache brackets. 

There is a common templating library known as handlebars which is similar which is why I used handlebars. - http://handlebarsjs.com/

**Comment by mathewc** [comment]
Nobody on our team has ever called these "handlebar"s to my knowledge - I was ribbing you because I thought you made a typo :)

Anyhow, this is an easy fix for us. You can see in the code here we're doing template binding only on the pk/rk: https://github.com/Azure/azure-webjobs-sdk-script/blob/dev/src/WebJobs.Script/Binding/TableBinding.cs#L45. We can do for filter as well.

**Comment by christopheranderson** [comment]
Cool. Current milestone? :)

**Comment by mathewc** [comment]
Sure.
