### ISSUE TITLE
Adding Rowkey setting to function.json for Table storage produces errors.

### ISSUE THREAD

**Issue by soninaren** [Azure/azure-webjobs-sdk-script#261]
Getting the following error on adding the row key to function.json
Table entity types must provide a default constructor

**Comment by fabiocav** [comment]
@mathewc happy to look at this for C# as it happens on a different path there (when the attribute is constructed) and the fix is pretty clear/straight forward. Perhaps we can split this issue.

**Comment by benmccallum** [comment]
I'm still getting this. Literally just created a new function in the portal, added an input integration of Azure Table Store and put in a RowKey and PartitionKey of my choosing. I have no data in the table, could that be the issue? This is really non-intuitive and has wasted so much of my time...

Maybe my scenario is broken and I'm not understanding how things should work here. My scenario is that my function accepts a "url" param on the querystring. I first check if this "url" has been tested before in the inputTable (Azure Table Storage) and return that, else run the test (long-running) and add/cache the result in the outputTable (same table name). Is that the right way to use these bindings?
