### ISSUE TITLE
Build.cmd fails with Nuget restore issue.

### ISSUE THREAD

**Issue by isaacabraham** [Azure/azure-webjobs-sdk-script#263]
Just pulled the latest version of master, getting the following error on calling build.cmd

```
Microsoft (R) Build Engine version 14.0.24720.0
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 16/04/2016 13:11:45.
Project "C:\Users\Isaac\Source\Repos\azure-webjobs-sdk-script\WebJobs.Script.proj" on node 1 (default targets).
RestorePackages:
  Restoring NuGet packages...
  "tools\NuGet.exe" restore WebJobs.Script.sln -PackagesDirectory packages -NonInteractive -Verbosity quiet -ConfigFile .nuget\NuGet.Config
EXEC : warning : Unable to find version '1.0.0-alpha-10268' of package 'Microsoft.Azure.WebJobs.Extensions.EasyTables'. [C:\Users\Isaac\Source\Repos\azure-webjobs-sdk-script\WebJobs.Script.proj]
  Unable to find version '1.0.0-alpha-10268' of package 'Microsoft.Azure.WebJobs.Extensions.EasyTables'.
C:\Users\Isaac\Source\Repos\azure-webjobs-sdk-script\WebJobs.Script.proj(69,5): error MSB3073: The command ""tools\NuGet.exe" restore WebJobs.Script.sln -PackagesDirectory packages -NonInteractive -Verbosity quiet -ConfigFile .nuget\NuGet.Config" exited with code 1.
Done Building Project "C:\Users\Isaac\Source\Repos\azure-webjobs-sdk-script\WebJobs.Script.proj" (default targets) -- FAILED.

Build FAILED.

"C:\Users\Isaac\Source\Repos\azure-webjobs-sdk-script\WebJobs.Script.proj" (default target) (1) ->
(RestorePackages target) -> 
  EXEC : warning : Unable to find version '1.0.0-alpha-10268' of package 'Microsoft.Azure.WebJobs.Extensions.EasyTables'. [C:\Users\Isaac\Source\Repos\azure-webjobs-sdk-script\WebJobs.Script.proj]


"C:\Users\Isaac\Source\Repos\azure-webjobs-sdk-script\WebJobs.Script.proj" (default target) (1) ->
(RestorePackages target) -> 
  C:\Users\Isaac\Source\Repos\azure-webjobs-sdk-script\WebJobs.Script.proj(69,5): error MSB3073: The command ""tools\NuGet.exe" restore WebJobs.Script.sln -PackagesDirectory packages -NonInteractive -Verbosity quiet -ConfigFile .nuget\NuGet.Config" exited with code 1.

    1 Warning(s)
    1 Error(s)

Time Elapsed 00:00:04.42
```

**Comment by ahawes-clarity** [comment]
Same here.

**Comment by isaacabraham** [comment]
We figured out why this is. It's because the NuGet packages on Myget are not being retained.

I'm not sure what the development process bring targeted is but currently, because packages are not being retained, any commit older than e.g. 24 hours (?) won't build. Basically this is not that unlike the recent NPM issue.

Could the team explain why this? It took me about an hour to figure this out - I simply assumed that no one would operate in this way and didn't even think to check if NuGet packages weren't available at first.

**Comment by fabiocav** [comment]
This is likely the result of a change to rename the EasyTable extension to MobileTable (#246). The package was probably prematurely removed and until those changes make their way into master, you should be able to build the dev branch, which points to the updated package.
@brettsam can you confirm that the package has been deleted?

**Comment by isaacabraham** [comment]
@fabiocav The package isn't showing on MyGet, yes. My question was more why you're deleting packages off MyGet. Package repositories shouldn't remove packages (as the recent NPM business proved ;-) - and we're now in a position where every commit that references the EasyTable extension won't build.

Can the EasyTable package be undeleted?

**Comment by fabiocav** [comment]
@isaacabraham, the reason is what I was trying to cover :) Perhaps that wasn't as clear.
That is by no means standard practice, and the package should have been unlisted, not removed. @brettsam is already looking at re-listing the package, but in the meantime, the alternative is to work with the dev branch that has the updated references.

**Comment by isaacabraham** [comment]
ah, ok. Yes, we moved onto dev branch (which is where the next issue came from re: CA errors!). We did then get another problem with the build - my laptop is out of action today so I can't report the exact error - @forki can you remember what the problem was?

**Comment by brettsam** [comment]
It looks like master still depends on EasyTables 10268 -- I've relisted it.

**Comment by isaacabraham** [comment]
@brettsam nice one. It sounds like it wasn't just unlisted but actually deleted somehow as nuget wouldn't even restore it. You probably want to allow people to do that to keep old commits valid.

**Comment by fabiocav** [comment]
@isaacabraham, now that @brettsam has relisted the package, this should resolve the issue, so I'll be closing this. Please feel free to re-open if you continue to experience problems and thanks for reporting this!

**Comment by forki** [comment]
Did you say you "unlisted" (not removed permanently) and that made nuget
restore fail? OMFG

**Comment by fabiocav** [comment]
@forki, I'm afraid this one is on us :(
The package was deleted, as opposed to unlisted (which would have allowed a restore to work), so it was our fault.

**Comment by forki** [comment]
That's actually very good to hear. Then it's not a more general issue.
Thanks for making this clear.
