### ISSUE TITLE
Multi-Key support for Functions

### ISSUE THREAD

**Issue by ruslany** [Azure/azure-webjobs-sdk-script#270]
If Function can use only one key then it cannot authenticate different sources securely.

**Comment by mathewc** [comment]
Yes, this is actually some work I was already planning to be able to support key rolling. I'm thinking in the function secrets files, I'll allow **arrays** of key values to be specified. In a key rolling scenario, that would enable you to have an old and new key, and to migrate people with a grace period before removing the old key. This would also address your scenario.

**Comment by davidebbo** [comment]
Yes, we've talked about supporting arrays in there from the early days, but just didn't get to it in Preview.

**Comment by mathewc** [comment]
The plan is to support multiple named keys per function (as Fabio suggested above). For WebHooks this will map naturally to ASP.NET WebHook config, which also supports multiple keys per function.

**Comment by fabiocav** [comment]
Updated PR #662 with all the implementation details. Please provide feedback if there are any concerns.

**Comment by fabiocav** [comment]
The work for this is mostly complete, but we're blocked on the API design to allow the portal to work with the secrets.

**Comment by fabiocav** [comment]
Multikey support was implemented in #662 and will be released in 0.7 (initially, behind a feature toggle)
