### ISSUE TITLE
Malformed host.json or function.json kills the host

### ISSUE THREAD

**Issue by davidebbo** [Azure/azure-webjobs-sdk-script#28]
While host is running, if I make a bad save to `host.json` (e.g. forget closing brace), the whole WebHost dies and doesn't recover after fixing the file. Same goes for `function.json`. At that point, the whole process needs a restart.

I think problem is that the exception ends up exiting the do/while loop in `RunAndBlock`.

We need to make this more resilient.

**Comment by mathewc** [comment]
Addressed by https://github.com/Azure/azure-webjobs-sdk-script/commit/10e57bd5c0604e1cfd72b096d7db83eb0c903b77. I verified that the host now recovers from various exceptions/errors, including malformed host.json.
