### ISSUE TITLE
Provided Azure Storage assembly is very old

### ISSUE THREAD

**Issue by lindydonna** [Azure/azure-webjobs-sdk-script#286]
I got an error resolving GetBlobReference, accessing the assembly using #r "Microsoft.WindowsAzure.Storage".  When I manually added the NuGet for the AzureStorage, version 7.0.0, the error went away:

```error CS1061: 'CloudBlobContainer' does not contain a definition for 'GetBlobReference' and no extension method 'GetBlobReference' accepting a first argument of type 'CloudBlobContainer' could be found (are you missing a using directive or an assembly reference?) ```

**Comment by christopheranderson** [comment]
This is already being tracked inside the SDK repo. We'll rev this later on. Closing this for now.
