### ISSUE TITLE
DocumentDB binding not handling binding parameters

### ISSUE THREAD

**Issue by mathewc** [Azure/azure-webjobs-sdk-script#288]
For non C# languages, the DocumentDB binding is not correctly handling binding parameters. Originally reported on SO [here](https://stackoverflow.com/questions/36786784/how-do-i-use-documentdb-bindings-for-queue-triggers-of-json).

I was able to repro this with the below metadata and code. The issue is DocumentDbBinding.BindAsync is not applying binding data when resolving the attribute.

```javascript
{
  "bindings": [
    {
      "queueName": "test",
      "connection": "azurefunctionse6d83f73_STORAGE",
      "name": "myQueueItem",
      "type": "queueTrigger",
      "direction": "in"
    },
    {
      "name": "doc",
      "type": "documentdb",
      "databaseName": "ItemDb",
      "collectionName": "ItemCollection",
      "id": "{id}",
      "connection": "mathewctest_DOCUMENTDB",
      "direction": "in"
    }
  ],
  "disabled": false
}


module.exports = function (context, item) {
    var doc = context.bindings.doc;
    
    context.log('Read document ', doc);
    context.done();
};
```

**Comment by mathewc** [comment]
Same issues exist for the MobileTableBinding and NotificationHubBinding.

**Comment by brettsam** [comment]
@mathewc -- Could the RuntimeBindingContext take care of this for us? (I'm probably wrong as to where the resolution occurs). Right now if I use a string like `{QueueTrigger}` in node it resolves fine at runtime -- I even have an E2E test that does this. So something is doing that resolution automatically for us -- is it an easy change to have it resolve JSON property names like this as well?

**Comment by mathewc** [comment]
For now just follow the example of QueueBinding/BlobBinding and the others. For non-C# languages we're doing late binding which requires this. We're investigating improvements, but that will take a while.

**Comment by mathewc** [comment]
@brettsam Is this fixed now in your latest binding updates? I think the core bindings above now support auto resolve?

**Comment by brettsam** [comment]
This change has to happen in Script, not Extensions (it works for C#). I had talked with @fabiocav a couple weeks ago and he suggested waiting for the new Invoker pattern which would provide this functionality for free, so I bumped this down my priority list. If that's still a ways off, I may reconsider and fix it in script sooner.

**Comment by mathewc** [comment]
Since its a really easy fix (all the other bindings are supporting this), I would have just addressed it a long time ago to get the user scenarios working. We can refactor behind the scenes later.

**Comment by brettsam** [comment]
At the time we were (hopefully) a week or so away from getting it for free, which would have meant adding some code and then deleting it a couple of days later. At that point it made sense to wait. I was just informed that things are likely still a ways off (which I didn't realize). I'll fix this soon.
