### ISSUE TITLE
DocumentDB input binding - support advanced queries for retrieval

### ISSUE THREAD

**Issue by edevil** [Azure/azure-webjobs-sdk-script#289]
Currently we can only fetch one document, through its ID, at each invocation. It would be great if we could specify a query that would run based on HTTP trigger parameters. Something like this:

```
SELECT *
FROM volcanoes v
WHERE ST_DISTANCE(v.Location, { 
    "type": "Point", 
    "coordinates": [QPARAM1, QPARAM2] 
    }) < 100 * 1000
AND v.Type = QPARAM3
AND v["Last Known Eruption"] = "Last known eruption from 1800-1899, inclusive"
```

**Comment by mathewc** [comment]
Not exactly the first class query support you're asking for, but you can bind to the DocumentClient in a C# functin (e.g. `[DocumentDB] DocumentClient client`) and execute queries using that.

**Comment by edevil** [comment]
That's great, but I'm using Python... Is the documentdb client available somewhere in the Python context as well? Thanks.

**Comment by mathewc** [comment]
Ah Python - it's always a question when we get issues as to what language if the bug hasn't specified. No it is not available in Python. To get query capabilities like this for non-C# languages, we'd have to do something like we've done for the Table binding. [Here's a sample](https://github.com/Azure/azure-webjobs-sdk-script/blob/master/sample/QueueTrigger-Python/function.json#L15) showing a table query specified in metadata in a Python script.

**Comment by brettsam** [comment]
This is on the (internal) feature list -- but we'll track it here going forward. The plan is to support SQL strings that we'll run against your configured DocDB. Very similar to what Mathew linked to above.

**Comment by edevil** [comment]
Good to hear. Please make them accept parameters from the request.

**Comment by mathewc** [comment]
This came up in SO recently here: http://stackoverflow.com/questions/40968323/can-i-get-all-the-documents-from-documentdb-in-azure-funtions-without-specifying. We should really expand this binding soon to support pulling in multiple documents.

**Comment by markrey** [comment]
+1

**Comment by brettsam** [comment]
This is now supported with #1280 (https://github.com/Azure/azure-webjobs-sdk-extensions/pull/182 in Extensions). Documentation coming soon.

**Comment by brettsam** [comment]
Documentation on `SqlQuery` (which maps to `sqlQuery` in Functions) can be found here: https://github.com/Azure/azure-webjobs-sdk-extensions/blob/dev/README.md#documentdb
