### ISSUE TITLE
New binding - Azure SQL Server

### ISSUE THREAD

**Issue by edevil** [Azure/azure-webjobs-sdk-script#291]
New feature - An Azure SQL server binding with a supplied query.

**Comment by mathewc** [comment]
Thanks for the suggestion - A SQL binding extension is something that we've discussed for a while.

Can you move this issue to https://github.com/Azure/azure-webjobs-sdk-extensions? This repo doesn't define any actual WebJobs SDK bindings - those are all defined in the azure-webjobs-sdk and azure-webjobs-sdk-extenisons repos.
