### ISSUE TITLE
Nested JSON gets turned into nested arrays.

### ISSUE THREAD

**Issue by alexanderweiss** [Azure/azure-webjobs-sdk-script#3]
A queue message containing nested JSON get the nested properties turned into arrays.

The following queue message:
> {"method":"foo","attr":{"templateName":"verify-user","templateContent":[],"detail":{"tags":["one","two"]},"check":false}}

Will output the following:
> Node.js queue trigger function processed work item {"method":"foo","attr":[[[]],[[]],[[[[[],[]]]]],[[]]]}

When using the following function:
> module.exports = function (context) {
    context.log('Node.js queue trigger function processed work item ' + JSON.stringify(context.email))
}

**Comment by mathewc** [comment]
Thanks for reporting - fixed via the attached commit.

**Comment by mathewc** [comment]
Fix is included in this release: https://github.com/Azure/azure-webjobs-sdk-script/releases/tag/v0.0.1-alpha1-10007

**Comment by alexanderweiss** [comment]
Thanks for the work. Really very useful project!
