### ISSUE TITLE
Http trigger for node.js WebJob

### ISSUE THREAD

**Issue by lavbox** [Azure/azure-webjobs-sdk-script#30]
I have written a  node.js  WebJob with [WebHook trigger](https://github.com/Azure/azure-webjobs-sdk-script/tree/master/sample/WebHook-Generic). It's not documented how to trigger a node.js function.
Using [WebJob Extensions SDK](https://github.com/Azure/azure-webjobs-sdk-extensions) we could do that using the following URL scheme

https://{site}.scm.azurewebsites.net/api/continuouswebjobs/{job}/passthrough/{class}/{function}

**Comment by mathewc** [comment]
In this repo, we've moved away from the model where we were using the WebHook trigger for http triggered functions. Instead we now have lightweight web app (see WebJobs.Script.WebHost) that acts as the http head and manages functions and dispatches to them.

To see this in action, set WebJobs.Script.WebHost as the startup project and run it locally. You can then make a POST request to `http://localhost:28549/api/webhook-generic?code=1388a6b0d05eca2237f10e4a4641260b0a08f3a5` with content-type=application/json and the function will run.

This is a new model we're working on, so unfortunately there isn't much documentation yet as far as how to deploy these components. We'll address that soon. Basically the idea is that you can deploy the WebHost as a site extension, so in your WebApp root, only the script files need to exist.

**Comment by mathewc** [comment]
Please see the updated Deployment section in the Wiki where I explain the new model and how you can depoy it. Once you do that, you can use http/webhook functions using the new model. The samples directory shows some [webhook samples](https://github.com/Azure/azure-webjobs-sdk-script/tree/master/sample/WebHook-GitHub).
