### ISSUE TITLE
Remove old metric ETW event from MetricsEventManager

### ISSUE THREAD

**Issue by akurmi** [Azure/azure-webjobs-sdk-script#301]
We need to emit both, old and new ETW events till the corresponding ETW listeners are moved to the new event. Once these ETW listeners are updated, we can remove the old ETW event.

**Comment by mattchenderson** [comment]
[Triage]: @akurmi Is this something you are planning to do?

**Comment by mathewc** [comment]
Yes, Ashish will be doing this.

**Comment by akurmi** [comment]
Yes, I will remove it once it's not needed. This fix would reduce the number of ETW events we emit currently.

**Comment by mathewc** [comment]
Waiting on ANT 56 for this
