### ISSUE TITLE
Consider adding context.trace (or context.verbose)

### ISSUE THREAD

**Issue by mathewc** [Azure/azure-webjobs-sdk-script#304]
C# functions can bind to a TraceWriter which allows logging at different levels (log.Info, log.Verbose, etc.).

Currently Node only supports context.log which we map to an Info level trace. It would be good to have a way for Node to write Verbose traces as well.

**Comment by mathewc** [comment]
Open to suggestions on the API. context.trace might not be the right thing, since Node console.trace writes a stack trace as well.

**Comment by mattchenderson** [comment]
[Triage]: Dale might have some additional insight here

**Comment by christopheranderson** [comment]
I've seen a few models for this. Just going to throw them out there.

1. There is the model where log is just a collection of the logging methods. This is inline with other logging libraries work. I'm worried about the breaking change and how long the code is becoming. `context.log.verbose('blah blah');`, which is equivalent to `context.log[level]('blah blah');`

2. There is a model where log can be passed the level. We then look to see if it's 1 string or 2 strings. If you just pass a single string, it's the default. If you pass the second string, you get the corresponding level. `context.log('hello world'); //defaults to info` and `context.log('hello world', 'verbose');`

3. I think there is another option which composes well with 2 which is - `context.warn('blah blah');` is just sugar for `context.log('blah blah', 'warn');`. I don't think this is necessary for all levels (like trace), but might be good for err, warn, info, verbose.

**Comment by mathewc** [comment]
I like the proposed option #1 above. Specifically I think we should:

- continue to have context.log('xxx') log to level info as it does now
- add context.log.verbose(), context.log.warn(), context.log.error()
- change our Node bridge code [here](https://github.com/Azure/azure-webjobs-sdk-script/blob/dev/src/WebJobs.Script/Description/Node/NodeFunctionInvoker.cs#L288) so that it takes a level and a message.
- handle the mapping in our node adapter layer [here](https://github.com/Azure/azure-webjobs-sdk-script/blob/dev/src/WebJobs.Script/Content/Script/functions.js), e.g. adding the context.log.xxx functions here and have them all map into the single log
