### ISSUE TITLE
Loading issues with private assemblies deployed in shared locations

### ISSUE THREAD

**Issue by fabiocav** [Azure/azure-webjobs-sdk-script#305]
When private assemblies are deployed in *shared mode* (i.e. locations outside of the bin sub directory in the function folder), there are two issues loading the assemblies:

1. The base/working directory is the private assembly directory (`bin`), which makes relative resolution one folder deeper than typically expected
2. Indirect dependencies fail to resolve as the resolver defaults to the private function assembly folder

**Comment by fabiocav** [comment]
@mattchenderson @Azure/azure-functions-admins FYI, moving this to the current milestone as it is blocking customer scenarios. Please let me know if you have any concerns.

**Comment by davidebbo** [comment]
Yeah, we should tackle this.

**Comment by mathewc** [comment]
Agreed :)
