### ISSUE TITLE
Blob outputs application/octet stream with Node.js

### ISSUE THREAD

**Issue by stevenfollis** [Azure/azure-webjobs-sdk-script#307]
Hello, 

New to Functions but loving the capabilities.  Perhaps I'm missing a step, but I'm attempting to interact with blobs using Node.js and running into a problem.  

I setup a function with a blob trigger and blob output binding, identically to this [sample](https://github.com/Azure/azure-webjobs-sdk-script/tree/master/sample/BlobTrigger).  The function triggers on the new blob when I upload a .jpg, but the output file is not a .jpg - it's a tiny ~15B file of Content-Type "application/octet-stream". 

Do I need to explicitly set the Content-Type in my Node.js code?

Worth noting that a simple .txt file was output as expected with a Content-Type of "text/plain" and can be opened in Notepad, whereas a medium sized .docx file is also being output as an application/octet-stream file.

Thanks for the help!

**Comment by mathewc** [comment]
Yes this is a known issue that we'll be addressing soon. It is tracked by https://github.com/Azure/azure-webjobs-sdk-script/issues/197. Currently Node functions convert all inputs to string, so that is why your data is being munged.

**Comment by stevenfollis** [comment]
Ah! Ok thanks for the heads up. Wasn't sure if it was something I was doing wrong.
