### ISSUE TITLE
Status: 404 not found

### ISSUE THREAD

**Issue by arafato** [Azure/azure-webjobs-sdk-script#308]
Hi there, 

in my current function app, I'm  not able to run newly created functions anymore. Every time I get the error `Status: 404 not found` in the UI (right next to the output field). Any clue what might cause this? I have only created 4 functions from the built-in templates. Thanks!

Best regards
--Oliver.

**Comment by davidebbo** [comment]
Can you clarify what kind of Functions you are creating? Specifically, try creating an http trigger function. Do you get a 404 when you click Run? What about if grab the URL (with the code) and request it in the browser?

**Comment by arafato** [comment]
I'm trying to create an http trigger function. After creation, whenever I click on 'Run' this message appears. Also, if I grab the URL and try to invoke it in the browser I get a 404 error. Here's the response header:
```
HTTP/1.1 404 Not Found
Cache-Control: no-cache
Pragma: no-cache
Content-Length: 0
Expires: -1
Server: Microsoft-IIS/8.0
X-AspNet-Version: 4.0.30319
X-Powered-By: ASP.NET
Date: Thu, 28 Apr 2016 18:04:17 GMT
```

**Comment by davidebbo** [comment]
Is this with the same function app as #309, or a different one?

**Comment by arafato** [comment]
No, it's with a different Function App.

**Comment by davidebbo** [comment]
Sorry for the slow response. If you're still seeing this,can you share your Function App name, either directly or [indirectly](https://github.com/projectkudu/kudu/wiki/Reporting-your-site-name-without-posting-it-publicly)? This will help us investigate. Thanks!

**Comment by arafato** [comment]
I've already deleted it. Thanks!

**Comment by mathewc** [comment]
Closing since it appears the repro app has been deleted.

**Comment by JagatjyotiMohanty007** [comment]
I am facing same issue Status: 404 Not Found
testing part of function App

**Comment by davidebbo** [comment]
@JagatjyotiMohanty007 this is an extremely old issue, and what you're seeing is likely not related. Please open a new issue with full details on your scenario. Thanks!
