### ISSUE TITLE
Status: 502 Bad Gateway

### ISSUE THREAD

**Issue by arafato** [Azure/azure-webjobs-sdk-script#309]
Hi there, 

all of a sudden, whenever I select a function in my function app, I get a red error message box saying:
```
Error:
You may be experiencing an error. If you're having issues, please post them here
Session Id: cf4f501caa9d4c2caad82e888a2cc8b3
Timestamp: 2016-04-28T11:59:39.927Z
```
Below that, right next to the output window there is another error message saying: `Status: 502 Bad Gateway.` The HTTP triggered functions can still be invoked via their HTTP endpoint, though. Any ideas? Thanks!

Best regards
--Oliver.

**Comment by davidebbo** [comment]
It looks like something crashed around that time, taking the host down. Did it recover shortly after, or has it been in that state ever since?

**Comment by arafato** [comment]
It's been in that state ever since.

**Comment by christopheranderson** [comment]
Could you share your function.json/code? Does this still repro?

**Comment by arafato** [comment]
Yes, that problem is still there. 
Here is the link to the repository:
`https://github.com/arafato/azure-news-explorer-api`

My function app consists of two functions: `news` and `news-import`, where `news` is http triggered and called from the single page application below. 
The frontend is hosted here:
`http://azurenewsexplorer.azurewebsites.net/`
A cold start of a function call takes incredibly long, around 15 seconds. After the initial call everything is fine. Don't know if this has something to do with the error message. Also `news-import` (which is time triggered) is never called.

function.json of news:
```
{
  "bindings": [
    {
      "webHookType": "",
      "name": "req",
      "type": "httpTrigger",
      "direction": "in"
    },
    {
      "name": "res",
      "type": "http",
      "direction": "out"
    }
  ],
  "disabled": false
}
```

function.json of news-import
```
{
  "bindings": [
    {
      "schedule": "0 0 12 * * *",
      "name": "myTimer",
      "type": "timerTrigger",
      "direction": "in"
    }
  ],
  "disabled": false
}
```

**Comment by davidebbo** [comment]
What you describe sounds different from how the issue started.

If I reason correctly, initial issue was that functions were running fine via direct http call, but were failing with a popup when clicking run from portal.

Now you report what appears like two new issues:

- cold start being slow, which is sort of a known issue (though 15s seems longer than it should be)
- timer function not getting triggered. That sounds bad, and probably worth tracking separately

Are you still seeing the Bad Gateway issue as well?

**Comment by arafato** [comment]
Yes, the Bad gateway issue is still there. 
I've also posted the other issues (cold start, timer function) since it might be related to the error popup / bad gateway.

**Comment by arafato** [comment]
To add to this: here's the ARM template I'm using to provision the Function App. 
[](https://github.com/arafato/funcy-azure/blob/master/lib/templates/project/f-resources-arm.json)
It's still possible to call a deployed function (http-triggered), however, it's not possible to run it from the portal.

**Comment by ahmelsayed** [comment]
It looks like the CORS settings for the backend site were removed. You have to allow the functions portal to talk to your app explicitly by having `https://functions.azure.com` in the list of CORS URLs.

**Comment by arafato** [comment]
That fixed it, thanks! I wasn't aware that this is actually related to the portal.
