### ISSUE TITLE
ScriptHost Site Extension crashing site

### ISSUE THREAD

**Issue by jamesdixon** [Azure/azure-webjobs-sdk-script#319]
Hi,

I've followed the directions in option 1 to install the Script Host as a private site extension. Unfortunately, whenever I do this, it crashes my API. I can't seem to find anything in the logs before this happens.

Note that as soon as I delete the private extension and restart the server, everything works again.

Any recommendations on debugging this?

Thanks,
James

**Comment by jamesdixon** [comment]
Did some additional investigating and I'm not sure the API crashes, but it becomes unavailable. For example, I have an endpoint `/ping`, that I use for basic health monitoring. When attempting to hit this after the site has started, I just get a 404. 

When running using the extension, are WebJobs the only thing allowed to be run on the web server or something?

**Comment by davidebbo** [comment]
Note that the instructions on https://github.com/Azure/azure-webjobs-sdk-script/wiki are overly complicated, and were written at a time where we didn't have Functions app. If you already have a Functions app and just want to use a private Function runtime, use these steps: https://github.com/Azure/azure-webjobs-sdk-script/wiki/Deploying-the-Functions-runtime-as-a-private-site-extension

And yes, when using a Functions app, the Functions runtime takes over the web root, but that is true whether you use private bits or not.
