### ISSUE TITLE
ApiHub SDK Package doesn't add Assembly reference

### ISSUE THREAD

**Issue by mathewc** [Azure/azure-webjobs-sdk-script#326]
I noticed this while fixing the nuspec version for ApiHub in the Extensions repo (commit [here](https://github.com/Azure/azure-webjobs-sdk-extensions/commit/05c2815b8c8081ce84d44240be50f7a143eff7c9)). Logging this issue here for lack of a better place. The ApiHub SDK package needs to be fixed and the new version pulled into Functions.

I've been fixing up the packages across the repos so they work properly - people should be able to add a reference to *Microsoft.Azure.WebJobs.Script* and have all the required references for running added.
Repro:

* Create a new console app
* Add package **Microsoft.Azure.ApiHub.Sdk"**
* The required reference to **Microsoft.Azure.ApiHub.Sdk.dll** hasn't been added to the csproj

**Comment by mathewc** [comment]
@galiniliev

**Comment by galiniliev** [comment]
fixed with https://github.com/Azure/azure-apihub-sdk/commit/9b014fa61123361f1782b434618aec49c5eb43be

**Comment by mathewc** [comment]
When will this be released to nuget?

**Comment by galiniliev** [comment]
Emil is working on table integration. It will be picked with that
