### ISSUE TITLE
HttpTrigger: Request object needs to be part of bindingdata

### ISSUE THREAD

**Issue by soninaren** [Azure/azure-webjobs-sdk-script#334]
Right now only httpRequest Body is available to be used as named parameter in function.json. We need to have the request object or atleast Request URI and Query string available to used as named parameters to support rich HttpTrigger scenarios.

**Comment by mathewc** [comment]
You can already access this information on the context. Try `context.req` which has properties like `body`, `rawBody`, `originalUrl`, 'method`, `query`, `headers`, etc.

**Comment by fabiocav** [comment]
@mathewc, isn't this done? We need to handle query strings for C#

**Comment by christopheranderson** [comment]
@mathewc what fabio asked ^^

Would this be something we should consider for rc?
