### ISSUE TITLE
clarifications

### ISSUE THREAD

**Issue by jamesdixon** [Azure/azure-webjobs-sdk-script#34]
Hi,

I'm working on getting this deployed and having some issues, so just wanted to clarify a few things from the Deployment section of the wiki:

- the wiki says "You deploy all this to a Continuous WebJob as you would normally for a regular WebJobs SDK job." I'm following [Amit Apple's instructions](http://blog.amitapple.com/post/74215124623/deploy-azure-webjobs/#.Vs_ocZMrIUF) for where to store jobs. That said, would these jobs go in the `continuous` folder even though they are triggered (queue for example)?

- is `run.cmd` supposed to live in `wwwroot/`? and if so, do the only contents need to be `.\bin\WebJobs.Script.Host.exe`?

I copied the simple QueueTrigger example, but it keeps saying the status is `Pending Restart`, hence my questions above. Thinking something may be wrongly configured.

Thanks in advance!
James

**Comment by mathewc** [comment]
I'm going to update/fix the deployment steps this morning based on recent changes. I'll point you to then when I'm done :)

**Comment by jamesdixon** [comment]
@mathewc thank you! much appreciated!

**Comment by mathewc** [comment]
I've made a first stab at updating the deployment steps. See: https://github.com/Azure/azure-webjobs-sdk-script/wiki#deployment.

**Comment by jamesdixon** [comment]
Hi again, @mathewc. I'm still not 100% clear on the deployment instructions, so again just wanted to clarify to make sure what I'm doing is correct:

1. Add connection strings to the web app
2. Add `host.json` and any web jobs to the `D:\HOME\SITE\WWWROOT\App_Data/jobs/continuous/` folder
3. Add the WebJobs.Script.Host files to the `D:\HOME\SITE\WWWROOT\bin` directory
4. Create a `run.cmd` file in `D:\HOME\SITE\WWWROOT` that executes the script host

Thanks and sorry to be a pain!

James

**Comment by mathewc** [comment]
Nothing gets put in App_Data/jobs/continuous - put everything in the exact paths I indicated in the wiki :) To clarify, the Kudu job runner is not running these script functions - this is an entirely new model. Give it a try and let me know if you have any issues.

**Comment by mathewc** [comment]
You're right, I screwed up the instructions. I've corrected them, and added some screen shots. Let me know it that works for you :)

**Comment by jamesdixon** [comment]
@mathewc haven't tried the new instructions out yet, but they are definitely super-clear now. thanks for the updates!
