### ISSUE TITLE
EventHub Trigger does not run if Azure Functions blade is closed

### ISSUE THREAD

**Issue by greggerca** [Azure/azure-webjobs-sdk-script#340]
Hi there,
Should an EventHub-triggered Azure Function continue to run if I close my Azure Function blade / logging environment?

So far, if I browse away from my Azure Function while it's running, the data stops flowing.
I tried adding a cron-based trigger to my function, but that didn't work / help.
Thanks for any insight...
TTFN
Gregg

**Comment by mathewc** [comment]
Definitely it should keep running. Is your function running in a Dynamic plan or Classic plan? If classic, make sure it is Basic or Standard, and has **Always On** turned on. When running under the Dynamic plan, the infrastructure will handle that for you.

Also, can you share your function app name, either directly or [indirectly](https://github.com/projectkudu/kudu/wiki/Reporting-your-site-name-without-posting-it-publicly)? This will help us investigate.

**Comment by mathewc** [comment]
May be related to https://github.com/Azure/azure-webjobs-sdk-script/issues/336.

**Comment by greggerca** [comment]
Hi there,
Yes, it looks exactly like issue #336. I'm using Event Hubs as a trigger, but that's the only difference.
I can't click "Always On" because the only service plan listing I can find is "Free" way over in the "Scale Up" blade. I had assumed that Azure Functions were billed differently.

Azure Functions says it is billed "per invocation" rather than being a regular Azure Web Site. So, do you get double-billed (Azure Function invocations + Azure Web Site tier) just to make your Azure Function work?

I mean, I intend for it to be "Always On" (or "On every few minutes" - it doesn't really need to be triggered at EVERY EventHub write - but you can't currently cron an Event Hub)... but I had thought the point of Azure Functions was to not maintain more infrastructure than you need just to shovel some data from one place to another...

Thanks for explaining the issue!
TTFN
Gregg

**Comment by greggerca** [comment]
OK, I see what the issue was. I didn't create a "New" plan - I used one I already had going to reduce the clutter in my subscription. So I never saw the Dynamic vs. Classic selection.

It sounds like that will fix everything - including the billing!
Thanks!

**Comment by navilwayne** [comment]
Hi Folks
I am facing the same issue for last 2 weeks. I have a Event Hub Trigger function app with **consumption plan**. It was working, when I open the portal in UI & continue to run for 3-4 hours , after that it automatically sleeps, when no request coming to event hub.
 Next day when request come again , it is not triggering, until I open portal.

I have to swap forcefully from Consumption Plan to App Service Plan to run this.

When we can expect fix for Consumption Plan????

Thanks.

**Comment by gibran** [comment]
Hi folks

I am with the same problem related by @navilwayne.

There is a expectation to solve it?

Thanks.

**Comment by KaiWalter** [comment]
Hello

count me in. I got the same problem.

Thanks
Kai

**Comment by navilwayne** [comment]
Hi Kai
Please refer below link & solved ur problem:
Azure Function Not Triggering by Event Hub #122

U have to remove entity path from connection string in last. Then it will work.
