### ISSUE TITLE
Dynamic Pricing Plans and Resource Groups

### ISSUE THREAD

**Issue by arafato** [Azure/azure-webjobs-sdk-script#341]
Hello--, 
I've noticed that the portal won't let me create more than one Dynamic Pricing Plan per resource group. Since the portal also won't let me assign a second Function App to an existing Dynamic Pricing Plan there seems to be a maximum of one dynamically priced Function App per resource group. Is this true? Can you share the rationale behind that decision? Grouping different Function Apps (each dynamically priced) with different memory sizes and requirements respectively into one resource group doesn't seem to be far off. Thanks!

**Comment by arafato** [comment]
Just checked: it's possible to create two dynamic pricing plans within the same resource group. 
So above problem seems to be an issue with the portal. Not sure if this should be filed as a bug?

**Comment by davidebbo** [comment]
I'll talk to the Portal owners about this. It does seem like a unnecessary limitation.

**Comment by davidebbo** [comment]
Closing here since it's not part of this code, but I did talk to them about it and they'll fix.
