### ISSUE TITLE
[TableBinding-Node] Table storage output binding doens't retain Boolean property of the JSON object

### ISSUE THREAD

**Issue by soninaren** [Azure/azure-webjobs-sdk-script#342]
Passing the following json in the output binding creates an entity in the table storage with all columns as string where as `completed` should be of type boolean in table storage.

```JSON
{
    "item": "todo item 1",
    "completed": false
}
```

**Comment by mathewc** [comment]
Hmmm. We're using the Storage SDK `EntityProperty.CreateEntityPropertyFromObject` method to do schematization. I wonder if it is doing this conversion (our code is [here](https://github.com/Azure/azure-webjobs-sdk-script/blob/dev/src/WebJobs.Script/Binding/TableBinding.cs#L172)).

Regardless, I'm doing a big binding pipeline overhaul right now, and I'll look into this at the same time.
