### ISSUE TITLE
Functions executions stats

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-webjobs-sdk-script#344]
Functions executions stats on the Kudu site: I've noticed that stats for functions that are no longer around still kept. Those not going to be removed automatically and no way to purge those ghost functions either.

**Comment by davidebbo** [comment]
@mathewc we talked about this before. I know this is how the WebJobs SDK behaves, but in the context of functions, it's problematic. We need to find a way to easily get rid of data pertaining to deleted functions. Either that or optionally keep them in some 'archive' hive. But they should not show up in the top level list in the dashboard.

**Comment by mathewc** [comment]
This is already tracked by https://github.com/Azure/azure-webjobs-sdk/issues/684

**Comment by mathewc** [comment]
Closing this since its a duplicate. Please use the issue I linked above.
