### ISSUE TITLE
Nicer UX when host.json is malformed

### ISSUE THREAD

**Issue by develohpanda** [Azure/azure-webjobs-sdk-script#347]
Reopening #28 to an extent - although the host is no longer killed, I still don't know why my function stops working.

Reproduction steps:
- Configure CI for your function app in Azure
- Add function, and a host.json file that is blank or has invalid json, the push to trigger automatic deployment.
- Extra step: disconnecting CI after a bad check-in of host.json

Current behavior:
- After deployment, when browsing the function app within Azure, this error notification is shown.
![image](https://cloud.githubusercontent.com/assets/4312346/15013912/bbde0b32-1256-11e6-854e-56defd9438b2.png)
- The call to https://[functionApp].azurewebsites.net/admin/host/status returns 200 with the following response:
	```{"errors":["Newtonsoft.Json: Error reading JObject from JsonReader. Path '', line 1, position 1."]}```
- When trying to invoke any function from the Azure portal, 503 is returned.
- Disconnecting CI leaves the function app eternally broken (as there is no way to modify host.json from portal?), giving same error as above, and prevents code compiles, etc.

Minimal expected behavior:
- More informative error message as to why/where the error is. eg. "host.json contains invalid json and could not be parsed" (I spent a very long time narrowing this down)

**Comment by mathewc** [comment]
Are you actually pushing an invalid host.json file? When you see this error, is the file on disk actually invalid?

If this is a parse issue, the CI aspect of your repro shouldn't be needed - you should be able to repro by making the file invalid directly.

**Comment by davidebbo** [comment]
How the file gets there is not relevant. So CI is fine as one way to repro, and so is just hacking the file directly. What matters is that the resulting error is better with the fix.

**Comment by mathewc** [comment]
Yep, agreed - was just trying to figure out if the file was getting malformed due to a race condition or something.

**Comment by mathewc** [comment]
Merged, thanks :) I addressed my minor test comments above in a follow up commit.
