### ISSUE TITLE
Wiki Images

### ISSUE THREAD

**Issue by mathewc** [Azure/azure-webjobs-sdk-script#35]
Don't delete this issue. It is used to host Wiki images as per the technique described [here](http://blog.davidebbo.com/2014/11/using-issues-for-github-pages-screenshots.html)

**Comment by mathewc** [comment]
![image](https://cloud.githubusercontent.com/assets/1056548/13377631/b5552974-dd97-11e5-9467-a3e58da0b681.png)

**Comment by davidebbo** [comment]
That's actually a patented trick, and there are royalties ;)

**Comment by mathewc** [comment]
Thanks David :)

**Comment by mathewc** [comment]
![image](https://cloud.githubusercontent.com/assets/1056548/13377653/c2deb30c-dd98-11e5-8d11-ef969542c2ff.png)

**Comment by mathewc** [comment]
![ver](https://cloud.githubusercontent.com/assets/1056548/18138545/1d2a5b26-6f62-11e6-8c08-f70c71e12f04.PNG)

**Comment by mathewc** [comment]
![capture](https://cloud.githubusercontent.com/assets/1056548/18138710/e22a3b44-6f62-11e6-8f75-0032a9a97509.PNG)

**Comment by mathewc** [comment]
![capture](https://cloud.githubusercontent.com/assets/1056548/18138748/170c65c6-6f63-11e6-8e35-435e9ebb7bd5.PNG)

**Comment by mathewc** [comment]
![capture](https://cloud.githubusercontent.com/assets/1056548/23677333/9439c7cc-0334-11e7-875b-17e69b1b4a77.PNG)
