### ISSUE TITLE
WebHook-Azure-CSharp Sample is broken

### ISSUE THREAD

**Issue by mathewc** [Azure/azure-webjobs-sdk-script#350]
This sample doesn't compile. If you set the ScriptHost as the startup project, you'll see that this function fails and doesn't get loaded. The errors are:

run.csx(2,1): error CS0006: Metadata file 'Microsoft.AspNet.WebHooks.Receivers.Azure' could not be found
run.csx(10,27): error CS0246: The type or namespace name 'AzureAlertNotification' could not be found (are you missing a using directive or an assembly reference?)
run.csx(8,17): error CS0234: The type or namespace name 'AspNet' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?)

Since this sample was added to test a scenario, I wonder if we don't have an actual product issue?

**Comment by fabiocav** [comment]
@mathewc I'm unable to repro this. The same function is also invoked by the end-to-end tests and passes. Can you repro?

**Comment by mathewc** [comment]
Fabio resolved the mystery - When running the ScriptHost (not the WebHost) the ASP.NET WebHooks are of course not registered, and we don't expect any HttpFunctions to work. What confused me was that this was a compilation error.
