### ISSUE TITLE
Rename "source" function metadata property

### ISSUE THREAD

**Issue by mathewc** [Azure/azure-webjobs-sdk-script#351]
This property allows people to indicate the entry script for a function, if the convention based resolution doesn't work for them.

Rather than "source", we should name this "script", "entry", or"primary". Should also make sure the property value can contain the file name w/o extension (I think extension is required currently).

**Comment by davidebbo** [comment]
`scriptFile` would I think make it clearer that the value is referring to filename.

**Comment by davidebbo** [comment]
Make sure Kudu is changed accordingly
