### ISSUE TITLE
Event Hubs Output gives an error about EntityPath

### ISSUE THREAD

**Issue by christopheranderson** [Azure/azure-webjobs-sdk-script#360]
I'm getting the following error when I'm running with an event hub output.

> 
> Error:
>  
> Microsoft.ServiceBus: EventHub name should not be specified as EntityPath while using this Overload. Instead, please use 'path' parameter. Parameter name: entityPath. 
>  
> Session Id: 90c305521048467aaac3d27c62a8c6fb
>  
> Timestamp: 2016-05-18T00:32:35.610Z

I've done nothing but follow the default UX in the integrate tab and add the IAsyncCollector code to the HTTP Template C#

Code:

```csharp
using System.Net;

public static async Task<HttpResponseMessage> Run(HttpRequestMessage req, TraceWriter log, IAsyncCollector<string> output)
{
    log.Info($"C# HTTP trigger function processed a request. RequestUri={req.RequestUri}");

    // parse query parameter
    string name = req.GetQueryNameValuePairs()
        .FirstOrDefault(q => string.Compare(q.Key, "name", true) == 0)
        .Value;

    // Get request body
    dynamic data = await req.Content.ReadAsAsync<object>();

    // Set name to query string or body data
    name = name ?? data?.name;
 
    await output.AddAsync("hello world");
 
    return name == null
        ? req.CreateResponse(HttpStatusCode.BadRequest, "Please pass a name on the query string or in the request body")
        : req.CreateResponse(HttpStatusCode.OK, "Hello " + name);
}
```

Function.json

```json
{
  "bindings": [
    {
      "authLevel": "function",
      "name": "req",
      "type": "httpTrigger",
      "direction": "in"
    },
    {
      "name": "res",
      "type": "http",
      "direction": "out"
    },
    {
      "type": "eventHub",
      "name": "output",
      "path": "chrande-test-eh",
      "connection": "chrande-test-EH",
      "direction": "out"
    }
  ],
  "disabled": false
}
```

**Comment by mathewc** [comment]
Has this binding ever worked with C# to your knowledge? I see that all the e2e tests in the script repo are Node examples. They're working. @MikeStall Do you know what might be wrong?

**Comment by christopheranderson** [comment]
+ @fabiocav 

I thought that we were making process towards removing the differences between the languages such that we end up in these situations? Is this work still in progress?

**Comment by mathewc** [comment]
Note that I'm not saying there is a language difference, I'm just pointing out that we have e2e tests running successfully in Node, so I'm not sure why this isn't working for you (assuming your EventHub is set up correctly, connection setting value is correct, etc.)

For reference, the binding code for both C# and all other languages is here: https://github.com/Azure/azure-webjobs-sdk-script/blob/dev/src/WebJobs.Script/Binding/EventHubBinding.cs. In the working Node example (the BindAsync code) we're binding to an IAsyncCollector as you are.

**Comment by fabiocav** [comment]
@christopheranderson, the work is still in progress. A lot slower than hoped as we've been attending to other issues, but trying to make progress on that.

**Comment by christopheranderson** [comment]
Move this to core SDK - this is an error with exception handling of invalid connection strings.

**Comment by christopheranderson** [comment]
Closing this now.
