### ISSUE TITLE
Find alternative to project.json

### ISSUE THREAD

**Issue by davidebbo** [Azure/azure-webjobs-sdk-script#363]
Now that the Core team is moving away from project.json, it makes little sense for us to continue to use it. We should discuss the best alternative, which may simply be the good old packages.config.

**Comment by fabiocav** [comment]
There are some issues with that (and that's one of the main reasons we went with project.json), but yes, we need to chat and discuss where we want to go. It would be good to better understand where they're going as the capabilities exposed by project.json won't go away, it will just be *moved* and wherever it ends up being, we can take adopt them there.

**Comment by davidebbo** [comment]
Yes, this is more of a marker than something we need to act on right away. They will actually not move away from it until after RTM of their runtime, because this file is considered to be part of their tooling, which won't RTM till quite a bit later.

Let's just see where this goes, and react accordingly.

**Comment by christopheranderson** [comment]
@fabiocav - given that moving away from this is likely a breaking change, what's the impact of staying with this post-rtm?

**Comment by fabiocav** [comment]
We can make this happen in a non-breaking way. We don't really have clarity on the approach we'd need to follow to replace what we currently do and don't expect we'd need to do that before RTM. To answer your question, there isn't a huge impact and we have much higher priority items.

**Comment by fabiocav** [comment]
This has been done for V2.

**Comment by fabiocav** [comment]
PR for reference: https://github.com/Azure/azure-webjobs-sdk-script/pull/2002
