### ISSUE TITLE
Feature Planning: first class Java support

### ISSUE THREAD

**Issue by christopheranderson** [Azure/azure-webjobs-sdk-script#366]
This is a tracking item for first class Java support. We'll be tracking the requirements and issues for first class Java support via this item. Feel free to leave comments about features/design patterns. 

We may also discuss general JVM support for languages like Scala, but that's not certain yet.
## Function format

**TBD**
## Data Type formats

**TBD**
## Version & Package management

**TBD**
## Testing/CI

**In progress**
### Remote debugging

 **TBD**
### Local debugging

**TBD**
## Hot runtime

**TBD**
## Compilation

**TBD**

**Comment by nikos** [comment]
Is there any timeline you have in mind from your product road map when Java support will arrive on Azure Functions?

/cc #224

**Comment by christopheranderson** [comment]
It'll likely be included in our next planning cycle, but can't say for sure until we start writing it.

**Comment by kevin-wang-cy** [comment]
Any progress so far, seem it had been left it there for a long time without progress?

**Comment by christopheranderson** [comment]
This is out now! Sorry we didn't update this issue as we were going along. All Java issues should go here now: https://github.com/Azure/azure-functions-java-worker
