### ISSUE TITLE
Add home page to function runtime

### ISSUE THREAD

**Issue by davidebbo** [Azure/azure-webjobs-sdk-script#373]
Today, hitting the root responds with a 204 (no content), which is pretty nasty when done through a browser. Let's add some kind of root page like we have for mobile sites and blank web apps that tells the user what it's all about.

**Comment by mathewc** [comment]
Yeah, that was always my intent, we've just never gotten around to it :)

**Comment by davidebbo** [comment]
@mattchenderson can you enlist the help of designers, etc... to help come up with some pretty page? Thanks!

**Comment by tcjustin** [comment]
Could it be possible to let the user set their own static content for the home page, or better yet support routing at the root level (see my comment on #389). Otherwise I'd actually rather have a generic 204 on that page in case my users happen to figure out the API url I'm using.

**Comment by fabiocav** [comment]
Here's a proposal for the initial experience:
https://htmlpreview.github.io/?https://github.com/fabiocav/fabio-random/blob/master/index.html

With the new routing feature, the ability to override the base/root route will be added, which would give users the ability to override this with a function.

**Comment by mathewc** [comment]
I think we should get this in. I would change "serverless event driven experience" to "serverless event driven platform".

**Comment by michaelz84** [comment]
@fabiocav, I tested the version 0.7 routing and it works great. You mentioned the base/root routing above. Is this already possible and if yes, how exactly?

An empty string for the "routePrefix" in host.json works, but "route" in function.json does not work with an empty string.

Would be great to have the possibility for base/root routing. Thanks for all your work!

**Comment by lindydonna** [comment]
@lindydonna will approve the text

**Comment by fabiocav** [comment]
@mikezks with the last update, as you have found, you can have your function exposed at the base/root path, but not yet handle the default route. We'll definitely consider adding that ability in a future update, but just wanted to get the routing support out ASAP.

**Comment by mikezks** [comment]
@fabiocav I see, thanks for answering this.
I'll open a new issue to address the possible new feature "Customize default Route".

**Comment by faultylee** [comment]
I read from a few places that `AzureWebJobsDisableHomepage` is working, but I still get `HTTP 204 No Content` when I turn it on. I've also tried adding below to proxies. Did I missed something?
```
        "landingpage": {
            "matchCondition": {
                "route": "*"
            },
            "backendUri": "https://myfunction.azurewebsites.net/api/StaticFileServer?file=index.html"
        }

```

**Comment by davidebbo** [comment]
@faultylee if you get 204 no content after disabling the home page, it means the flag is working as designed. Can you clarify what you were expecting?

**Comment by faultylee** [comment]
@davidebbo I was hoping to serve a page directly from one of the function. Not sure if this is what "Customized default route" that mikezks mentioned. I got a bit confused when going through #813, #848, which seems to indicate I can achieve that, or not yet?

**Comment by davidebbo** [comment]
This issue is not about customizing the home page, but about having a *standard* default home page, which we've now had for a year (which is why it is closed).

I think you're asking about *customizing* the home page, which is discussed in #848. So that's probably where you want to be :)

**Comment by faultylee** [comment]
Noted, thanks @davidebbo

**Comment by mikezks** [comment]
@faultylee, you can follow @anthonychu's [blog post](https://anthonychu.ca/post/azure-functions-static-file-server/) on how to serve static files with Azure Functions. I have a static website online which uses a similar config and runs completely as Azure Function (I use Blob Storage and Azure Functions Proxies to serve the website).

But keep in mind that Functions are not designed for this use case and be aware that there may be side effects a normal webserver would not show (e.g. longer initial load time in case of cold starts, etc.). Also do not expect that ASP.NET (MVC) can be used within this config. Nevertheless a currently popular use case like serving SPA is possible and even server-side rendering of SPA should be realizable.

**Comment by faultylee** [comment]
@mikezks Thanks, that's exactly what I'm using and I do understand the shortcoming.

**Comment by enghch** [comment]
I would hope that support for running ASP.NET (MVC) pages from Azure Functions is a supported scenario. When you need a quick page rendered and your traffic is extremely sparse (like one hit per day), waiting two or three seconds for a page load is not a problem.
