### ISSUE TITLE
Import System.Configuration assembly by default

### ISSUE THREAD

**Issue by davidebbo** [Azure/azure-webjobs-sdk-script#374]
This came up [here](http://stackoverflow.com/questions/37215069/azure-functions-database-connection-string/37215710?noredirect=1#comment62247557_37215710).

Scenario is trying to access an app setting or connection string, e.g.

    var conn = System.Configuration.ConfigurationManager.ConnectionStrings["MyConn"].ConnectionString;

Currently this requires `#r"System.Configuration"`.

Note that I don't think we should auto import the namespace. Just the assembly.

**Comment by mathewc** [comment]
@fabiocav Want to get this one in quick?
