### ISSUE TITLE
AuthorizationLevel - where to get Admin key?

### ISSUE THREAD

**Issue by arafato** [Azure/azure-webjobs-sdk-script#375]
Hi--, 

the popup of AuthorizationLevel at the portal says that the admin key is in the host secrets file. To my understanding the host secrets file of a function is located at `https://my-project.scm.azurewebsites.net/api/vfs/data/functions/secrets/MyFunction.json`. Independently of what I choose as authorization level (function, anonymous, admin), however, the key is always the same. Where exactly is that host secrets file and where can I find the admin key, respectively? Thanks!

Best regards
--Oliver.

**Comment by davidebbo** [comment]
It's in `https://my-project.scm.azurewebsites.net/api/vfs/data/functions/secrets/host.json`. Note that you'll find two keys in there:

1. `masterKey`: access to all functions, regardless of auth level
2 `functionKey`: access to all functions, unless their auth level is set to `admin`

**Comment by arafato** [comment]
Thanks @davidebbo ! Is there also an API available to get these values?

**Comment by davidebbo** [comment]
I don't think we have a first class API for those, but the 'vfs' API should get you going.

**Comment by joymon** [comment]
Where is the recommended place to store some secret keys in Azure functions. I would see we can keep in App level settings, function level as well as admin. My scenario is to have a Azure function talk to github api using github token. Currently I have one function in the app. If recommendation is at function level, please help me with API.

**Comment by mathewc** [comment]
Update: Keys now have a first class UI in the Functions portal. You can access keys (including admin key) under the Manage tab for any function.

@joymon The right place to store secrets like this is in the Function App App Settings accessible in the portal. This is where we store all the various connection strings for storage, etc. You can add settings and access them via code as environment variables.
