### ISSUE TITLE
Log message looks messed up when an exception happens

### ISSUE THREAD

**Issue by davidebbo** [Azure/azure-webjobs-sdk-script#378]
Create a C# http func and add this code at the top to cause a null ref:

    string s = null;
    int n = s.Length;

When you run it, you get this:

    2016-05-22T22:02:30.329 Exception while executing function: Functions.TestNullRef. Microsoft.Azure.WebJobs.Script: One or more errors occurred. ƒ-TestNullRef#ℛ*ca929718-0ade-492b-bec6-341db5396d74#10-0: Object reference not set to an instance of an object.

Note the strange characters and guid in there, which look messy. I suspect some of it may be due to the automatic class name generated by csx, but we should see whether there is anything we can do about it.

**Comment by mathewc** [comment]
Yes, that funky name is the name of the generated assembly. Our error reporting drills into nested exceptions and formats them as Source: Message. In this case the Source is the dynamic assembly name. I verified locally: `function.DeclaringType.Assembly.GetName().Name` for this error yields "ƒ-HttpTrigger-CSharp#ℛ*9f68e571-38dc-4f3c-93d9-d21c43f2c5db#3-0"

**Comment by fabiocav** [comment]
That is correct. We prefix the default Roslyn generated assembly name (what starts with #ℛ) with our function name (the ƒ- + name part)

**Comment by davidebbo** [comment]
We could potentially filter that out. Not highest pri, but it does look dirty as the guid is meaningless to the user and sort of takes over the string.

**Comment by mathewc** [comment]
Let's just do something easy if we can, otherwise just close this out until users complain about it.
