### ISSUE TITLE
Traffic Manager Integration

### ISSUE THREAD

**Issue by arafato** [Azure/azure-webjobs-sdk-script#379]
Hi--, 

is integration of Azure Functions with Traffic Manager (TM) supposed to work? I've just tried it out, however, TM is not able to resolve the endpoints. Thanks!

Best regards
--Oliver.

**Comment by davidebbo** [comment]
At this time, Function Apps in the Dynamic sku have a limitation that they don't support custom host names. It lets you register them but they don't actually work, which I think is why TM is not working.

This is something that we're planning to enable, but will take a few iteration. That logic sits outside of the GitHub code base, but it's ok to track it here.

**Comment by christopheranderson** [comment]
Assigning to myself to track

**Comment by christopheranderson** [comment]
Need to chat with platform folks to see if this will be around for rc. Might change milestone to help me track.

**Comment by DarinMacRae** [comment]
Just ran into this one myself. Any status update on this? I'm using ~0.6.

**Comment by AndyMDoyle** [comment]
Any update on this now Azure Functions has hit release?

**Comment by DKincer** [comment]
*bump* Checking if there is an update on this issue. Currently publishing an Azure Function takes it offline. Need to set up a priority traffic manager to divert from East to West during a publish

**Comment by lindydonna** [comment]
This issue was moved to Azure/Azure-Functions#214
