### ISSUE TITLE
QueueTrigger function stop firing

### ISSUE THREAD

**Issue by justinneff** [Azure/azure-webjobs-sdk-script#392]
I have a function setup to run a node.js script using a QueueTrigger on a storage queue. On at least 3 different occasions now, the function app has stopped processing the messages in the queue when they arrive. I find out about it after I get reports that stuff has not updated. When I look at the queue in visual studio, I will usually see 20 to 30 messages sitting out there. The messages do not appear to be running and failing because they never get moved to the poison queue.

I have found that by restarting the Function App in the Azure Portal the function will start processing the messages again and it will be fine for a while.

The latest instance started happening sometime before noon yesterday, May 24. I have not kept up the frequency of the previous occurrences but the previous instance was at least a week ago or more. So I do not know for sure how often it is happening, but it has happened enough to raise concern.

**Comment by mathewc** [comment]
Is your function running in a Dynamic plan or Classic plan? If classic, make sure it is Basic or Standard, and has Always On turned on.

Also, can you share your function app name, either directly or [indirectly](https://github.com/projectkudu/kudu/wiki/Reporting-your-site-name-without-posting-it-publicly)? This will help us investigate.

One more thing: the approximate time where you saw this happen could help track it down.

**Comment by justinneff** [comment]
@mathewc, it is running on a Classic plan tier S3. I did not have Always On turned on for the function app. I have turned it on now. We are still in development and early beta testing for the product that the function app is used for so it makes sense that there would be sporadic periods of time with queue messages to process.

You can find the function app in the App Service Plan with dummy392.azurewebsites.net. Just look for one named the "-functions".

As for timing, it seems to have happened again this morning so it stopped again sometime between 10 AM yesterday and 7 AM this morning.

My gut tells me that it stopped because it got unloaded due to Always On being turned off. Is there a way I can verify that or is that something that you would have to verify?

**Comment by mathewc** [comment]
Yes, it was most certainly because of Always On not being turned on. In the Dynamic plan, we take care of keeping things running, but in Classic plans, Always On must be on otherwise you'll get idled out. Same guidance is in place for classic WebJobs (details [here](https://azure.microsoft.com/en-us/documentation/articles/web-sites-configure/)).

**Comment by mathewc** [comment]
FYI - we've verified that when new Function Apps are created in Classic Plan Always On is now enabled by default. That was a recent change.

**Comment by mathewc** [comment]
Closing this. Please reopen if you see any further issues not that Always On is enabled.
