### ISSUE TITLE
Can't enable logging to the storage

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-webjobs-sdk-script#397]
Tried to enable storage based logging. When saving changes/configuration for Logs, get the following error

```
Failed to update web app logs settings.

Failed to update web app logs settings for [functions app name]. There was an error processing your request. Please try again in a few moments.
```

Details:
TIME Thursday, May 26, 2016, 10:10:30 AM
CORRELATION IDS 8da84782-a547-4f03-af56-7d0d48f4c9a2

**Comment by SeanFeldman** [comment]
Anyone? I've tried today again, and still no luck. Exception is thrown.

**Comment by davidebbo** [comment]
Can you clarify what kind of logging you are referring to (e.g. Application logging, Web Server logging), and how you are trying to do it (e.g. Porta, PowerShell, ...)? Thanks.

**Comment by SeanFeldman** [comment]
Application logging.

**Comment by SeanFeldman** [comment]
From portal (Ibiza).

**Comment by christopheranderson** [comment]
David found the root cause for this and the fix is deploying in the next couple weeks.

**Comment by davidebbo** [comment]
Yes. Actually, it should already be fixed in South East Asia, but not yet in West US and West Europe.

**Comment by SeanFeldman** [comment]
I'm in west-us :(

**Comment by davidebbo** [comment]
Still, in case you want to validate that it all works using a test Function App :)

**Comment by mathewc** [comment]
So has this issue been fixed so we can close this?

**Comment by SeanFeldman** [comment]
I believe it was.

**Comment by danbueno20** [comment]
I have this issue happening in Southeast Asia region.  What is the root cause?  I am seeing the same result mentioned above.  CorrelationId: cdc0afb7-baa5-4278-a725-53aafa237c1b
