### ISSUE TITLE
Trigger based function was not executed

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-webjobs-sdk-script#398]
Schedule was set to to every 24 hours using "24:00:00" format.
I keep a file with the last stamp execution and May 16th was the last execution date.

**Comment by mathewc** [comment]
Are you saying that the `schedule` property is using "24:00:00", a time span expression rather than a cron expression? Also are you on the Dynamic Plan or Classic plan?

**Comment by SeanFeldman** [comment]
Correct. It's using timespan and it's on dynamic hosting plan.

**Comment by mathewc** [comment]
All right, here's the issue. While the WebJobs SDK supports the TimeSpan format, Functions does not - it only supports the cron format. I meant to add a bug to lock that down, but I forgot to get to that.

**Comment by SeanFeldman** [comment]
Will do.
