### ISSUE TITLE
Disallow TimeSpan TimerTrigger format

### ISSUE THREAD

**Issue by mathewc** [Azure/azure-webjobs-sdk-script#400]
See: https://github.com/Azure/azure-webjobs-sdk-script/issues/398

**Comment by SeanFeldman** [comment]
@mathewc can I ask why to disallow rather than allow?

**Comment by SeanFeldman** [comment]
Documentation says it's a go: https://azure.microsoft.com/en-us/documentation/articles/functions-bindings-timer/#format-of-schedule-expression

> To trigger every 15 seconds:

> "schedule": "00:00:15",
> "runOnStartup": false,

**Comment by mathewc** [comment]
Yeah, the doc is out of sync with the actual implementation. Who you gonna trust, the doc, or the guy who wrote all the code? ;)

I actually wish I never added support for the TimeSpan format in the TimerTrigger to begin with. W.r.t functions, the reason for disallowing is because it complicates our schedule management to have multiple ways of scheduling. We're actually only honoring valid cron expressions currently, which is the issue you reported.

**Comment by SeanFeldman** [comment]
Understand. The disconnect between doco and code is definitely not good :)
At least the portal will no longer accept TimeSpans :)

**Comment by mathewc** [comment]
We've also fixed the doc: https://github.com/Azure/azure-content-pr/pull/25325. That update will go live soon.
