### ISSUE TITLE
The blob output binding settings can't use some characters in the blob name.

### ISSUE THREAD

**Issue by buchizo** [Azure/azure-webjobs-sdk-script#410]
I can't set some characters (E.g.  '[', ']') for blob output binding.

Example: https://gist.github.com/buchizo/2f8ac640a21cd78920eccbfd7e0d267d

I was upload file to the incontainer. ( E.g. 2011923500042[1].jpg )
After uploaded, error occurred in function app as follows: 

`2016-05-29T19:20:41.766 Exception while executing function: Functions.BlobTriggerCSharp1. Microsoft.Azure.WebJobs.Host: Exception binding parameter 'outputBlob'. Microsoft.Azure.WebJobs.Host: The given blob name '2011923500042[1].jpg' contain illegal characters. A blob name cannot the following characters: '\', '[' and ']'.
`

I guess output binding is not the appropriate escape processing.

**Comment by christopheranderson** [comment]
This is likely a WebJobs SDK issue, not script.

**Comment by mathewc** [comment]
Yes, this is coming from the core SDK ([here](https://github.com/Azure/azure-webjobs-sdk/blob/master/src/Microsoft.Azure.WebJobs.Host/Blobs/BlobClient.cs#L67) in the source). [Here](https://github.com/Azure/azure-webjobs-sdk/blob/master/src/Microsoft.Azure.WebJobs.Host/Blobs/BlobClient.cs#L13) in the code, it is mentioned that these were restrictions that were in place in 2014 when the code was written.

However, from reading the [current naming guidelines](https://msdn.microsoft.com/library/azure/dd135715.aspx?f=255&MSPPError=-2147217396) it says a blob can contain "any combination of characters".

So we should update our checks here. While we're at it, we should check any naming restrictions we have in place for queues, tables, service bus as well. Once this core SDK work is done, we should make sure the Functions portal regex's are correct as well (they should be already).

**Comment by mathewc** [comment]
Fixed via https://github.com/Azure/azure-webjobs-sdk/pull/764
