### ISSUE TITLE
Nested JSON array in queue messages causes binding templates to fail on Node.js

### ISSUE THREAD

**Issue by lediur** [Azure/azure-webjobs-sdk-script#412]
**Summary**: If a queue trigger's message text is JSON with an array of objects, the Host fails to bind the JSON's object properties.

---

I ran into this issue when trying to write a function with a queue trigger that gets data and writes it to blob storage.

I have a `function.json` like this:

```json
{
    "bindings": [
        {
            "name": "queueInput",
            "type": "queueTrigger",
            "direction": "in",
            "queueName": "test",
            "connection": "AZURE_STORAGE_CONNECTION_STRING"
        },
        {
            "name": "testOutput",
            "type": "blob",
            "direction": "out",
            "path": "test/{test}.json",
            "connection": "AZURE_STORAGE_CONNECTION_STRING"
        }
    ]
}
```

and a very simple `index.js`
```js
module.exports = function(context, queueInput) {
    context.log(queueInput);
    context.log(queueInput.test);

    context.done(null, { testOutput: queueInput });
}
```

If I pass in a json string like:

```json
{
    "test": "testing"
}
```

the function runs without issue and creates a blob at the path specified.

However, if I pass in a json like:

```json
{
    "test": "testing",
    "nested": [ { "nesting": "yes" } ]
}
```

I get this error:
```
2016-05-30T02:57:58.375 Function started (Id=407a2ad1-78f7-4676-b1c5-accde8066d04)
2016-05-30T02:57:58.375 { test: 'testing', nested: [ { nesting: 'yes' } ] }
2016-05-30T02:57:58.375 testing
2016-05-30T02:57:58.375 Function completed (Failure, Id=407a2ad1-78f7-4676-b1c5-accde8066d04)
2016-05-30T02:57:58.391 Exception while executing function: Functions.test. Microsoft.Azure.WebJobs.Host: No value for named parameter 'test'.
```

**Comment by davidebbo** [comment]
Yes, this repros as you describe, and there seems to be a bug in there. Basically, it seems we fail to evaluate `{test}` when the array prop is there.

It repros with just:

```json
{
    "test": "testing",
    "foo": []
}
```

But if you change `"foo": []` to `"foo": {}` or `"foo": ""`, the it doesn't repro.

Quite odd. @mathewc, what do you make of this?

**Comment by mathewc** [comment]
Strange. I'll have to debug into it to find out what is going on. Might be a core SDK issue, not sure yet.

**Comment by mathewc** [comment]
Fixed, thanks for reporting.
