### ISSUE TITLE
Source control integration with local git fails with ARM template

### ISSUE THREAD

**Issue by arafato** [Azure/azure-webjobs-sdk-script#416]
Hi---,

I'm using the following ARM template to automatically provision a function app:
[https://github.com/arafato/funcy-azure/blob/master/lib/templates/project/f-resources-arm.json](https://github.com/arafato/funcy-azure/blob/master/lib/templates/project/f-resources-arm.json) 

In order to integrate with local git version control, I set the parameters `scmType` to `LocalGit` and the `repoUrl` parameter to `<projectname>.scm.azurewebsites.net`.

When executed the first time, the following resource deployment operation fails: `Microsoft.Web/sites/sourcecontrols/write`
The error message is:
```
statusCode:Conflict
statusMessage:{"status":"Failed","error":{"code":"ResourceDeploymentFailure","message":"The resource operation completed with terminal provisioning state 'Failed'."}}
```
The function app, however, is successfully deployed. Using [https://resources.azure.com/](https://resources.azure.com/), I see that for some reason `scmType` is set to `ExternalGit`.

When I execute the same template again now, all deployment operations succeed (including local git integration).  I can also see the Git clone URL in the portal, etc.
Any idea what might cause this behavior? Thanks!

Best regards
--Oliver.

**Comment by davidebbo** [comment]
If you only want local git (i.e. you `git push` directly from local machine to Azure), you should completely omit the `sourcecontrols` section. That section is only for deploying the site from an external repo like GitHub or Bitbucket.

**Comment by davidebbo** [comment]
As an aside, your template can be simplified quite a bit. See my sample [here](https://github.com/davidebbo-test/FunctionsSamples/blob/master/azuredeploy.json). e.g.

- you can omit the serverfarm altogether if you want it to be dynamic
- you don't need to set most of the properties like `hostNameSslStates` for the site
