### ISSUE TITLE
Log tailing API?

### ISSUE THREAD

**Issue by arafato** [Azure/azure-webjobs-sdk-script#417]
Hi--, 

is there an API/SDK (couldn't find one at http://azure.github.io/azure-sdk-for-node/) for getting the logs of a function run as displayed in the portal? Thanks!

Best regards
--Oliver.

**Comment by davidebbo** [comment]
Yes, this is done via the [Kudu Log Streaming API](https://github.com/projectkudu/kudu/wiki/Diagnostic-Log-Stream). Let us know if you have issues with it.

**Comment by arafato** [comment]
Works!
For those interested, here's a simple integration using Node.js which outputs the stream to `stdout`
```
const request = require('request');

let username = 'your-username',
     password = 'your-password',
     url = 'https://' + username + ':' + password + '@your-project.scm.azurewebsites.net/logstream';

request.get(url).pipe(process.stdout);
```
