### ISSUE TITLE
Phantomjs possible with Azure functions?

### ISSUE THREAD

**Issue by Theovanlaar** [Azure/azure-webjobs-sdk-script#421]
Within webjobs this was not possible due to GDI API. Read that Azure functions has to deal with the same limitations as App service. Still, are there plans to make this work within Azure Functions?

Thanks

**Comment by davidebbo** [comment]
The sandbox is identical (details [here](https://github.com/projectkudu/kudu/wiki/Azure-Web-App-sandbox)), so from that standpoint, what is allowed and not allowed does not deviate from WebJobs or Web Apps. At this point there is no firm timeframe for this support.

Closing here as it is not Functions specific.
