### ISSUE TITLE
Calling non-http function endpoints via their https endpoints

### ISSUE THREAD

**Issue by arafato** [Azure/azure-webjobs-sdk-script#423]
Hi--, 

is it possible to call non-http triggered functions (e.g. blob-triggered) using their https endpoints?  `https://management.azure.com/subscriptions/<subscriptionId>/resourceGroups/<resourceGroup>/providers/Microsoft.Web/sites/<functionapp-name>/functions?api-version=2015-08-01` gives me a list and according endpoints of **all** functions. However, calling a non-http triggered function through its https endpoint results in a 404 (not found).  Thanks!

Best regards
--Oliver.

**Comment by davidebbo** [comment]
You can do this on the runtime endpoint, e.g.

    POST https://{functionapp}.azurewebsites.net/admin/functions/{function}

To authenticate, there are two ways:

1. pass `code={masterkey}` in the query string
2. pass a `x-functions-key:{masterkey}` header

master key can be obtained via vfs API on scm endpoint, e.g. /api/vfs/data/Functions/secrets/host.json

This is not a very clean story. I think we need to improve this.

**Comment by arafato** [comment]
Thanks @davidebbo !

**Comment by arafato** [comment]
How would you actually pass input bindings in such a request? 
Using `curl` I've tried to pass it to a blob-triggered function as follows:
```
curl https://{project-name}.azurewebsites.net/admin/functions/BlobTriggerNodeJS1?code={code} -d "myBlob=foobar" -X POST
```
The log output gives me
```
Exception while executing function: Functions.BlobTriggerNodeJS1. Microsoft.Azure.WebJobs.Host: Exception binding parameter 'myBlob'. Microsoft.Azure.WebJobs.Host: Unable to convert trigger to IStorageBlob.
```
I've also tried to pass the data as `-d {"myBlob":"foobar"}` but it gets me the same error message. Any clues? Thanks!

**Comment by davidebbo** [comment]
It should work with json payload. Maybe you're just missing the content type?

Try clicking run in the portal while using the Chrome F12 tools. You'll see the exact request it's sending.

**Comment by arafato** [comment]
Thanks @davidebbo, using the developer tools did it! :-)

**Comment by mathewc** [comment]
Closing this unless there is something more we need to do here.
