### ISSUE TITLE
How to set MaxDequeueCount with ARM \ Node.js

### ISSUE THREAD

**Issue by morsh** [Azure/azure-webjobs-sdk-script#424]
Hi,
I want to change the default values for:
BatchSize, MaxDequeueCount and MaxPollingInterval.

I have a function app that's deployed via ARM and uses continuous deployment to deploy Node.js code from GitHub.

How can I change those settings without using C#?

Thanks,
Mor Shemesh

**Comment by mathewc** [comment]
You can set those values via your **host.json** config file. Please see the wiki page [here](https://github.com/Azure/azure-webjobs-sdk-script/wiki/host.json) for more info.

**Comment by morsh** [comment]
@mathewc Thank you for the fast reply!
