### ISSUE TITLE
Normalize casing for Node Function BindingData

### ISSUE THREAD

**Issue by mathewc** [Azure/azure-webjobs-sdk-script#426]
For Node functions, we make the entire BindingData bag available via `context.bindingData`. For example, this provides access to things like the triggering blob path, etc. as below.

However, these values are currently **case sensitive** - we simply add the values as is to the binding data object. The core SDK uses upper case for this, so you have to type `context.BlobTrigger` rather than `context.blobTrigger` as you'd expect.

We should figure out the best way to normalize this casing.

```javascript
module.exports = function (context, myBlob) {
    context.log('Node.js blob trigger function processed blob:', myBlob);
    context.log('Blob path: ', context.bindingData.BlobTrigger);
    context.done();
};
```

**Comment by christopheranderson** [comment]
Let's do this for GA since it's an API change

**Comment by mathewc** [comment]
I think we should just camel case any pascal cased properties before adding them to binding data. That is simpler and less confusing than trying to try to play games with proxy objects etc. to avoid breaking changes.
