### ISSUE TITLE
Remove RowKey and Partition key from function.json for azure table storage output binding

### ISSUE THREAD

**Issue by soninaren** [Azure/azure-webjobs-sdk-script#428]
Discussed with @christopheranderson, The idea is to make the change in the runtime, to allow table storage output binding to not have rowkey and patitionkey. Once this change is done, we are planning to remove the UI for Rowkey and partionkey from table storage output binding.

The reason for this change is that it is a quite confusing, the function.json properties will be effective when there is single record in output binding, but not when multiple records are added.

**Comment by mathewc** [comment]
I don't understand the ask. We support PK/RK for singleton bindings, but they aren't required. You can also bind to a table and output multiple entities. Example here: https://github.com/Azure/azure-webjobs-sdk-script/blob/dev/test/WebJobs.Script.Tests/TestScripts/Node/TableOut
