### ISSUE TITLE
C# Function Compilation Hanging

### ISSUE THREAD

**Issue by mathewc** [Azure/azure-webjobs-sdk-script#429]
Starting from a standard C# HttpTrigger template, make a few modifications and verify you get successful compilation output. Now try changing the code to the below  function (note that the function erroneously declares two return types). This will cause compilation to hang, and I was also seeing some out of memory errors. E.g., my function output showed "Compiling function script" but nothing after.

```csharp
using System.Net;

public static void HttpResponseMessage Run(HttpRequestMessage req, TraceWriter log)
{
    log.Info($"C# HTTP trigger function processed a request.  RequestUri={req.RequestUri}");

    return req.CreateResponse(HttpStatusCode.OK);
}
```

I think this might be a class of bugs, because I can also see the same result with:

```csharp
using System.Net;

public static async HttpResponseMessage Run(HttpRequestMessage req, TraceWriter log)
{
    log.Info($"C# HTTP trigger function processed a request.  RequestUri={req.RequestUri}");

    return req.CreateResponse(HttpStatusCode.OK);
}
```

**Comment by kmh0237** [comment]
I am seeing the recompiler not even trying to compile C# functions, when there is no error.  I reduced mine down to as simple as I could make it and it still wasn't compiling:

public static void Run(string mySbMsg, TraceWriter log)
{
}

I will only get this message maybe 1/30 times, if that:
2016-06-10T14:24:11.099 Compiling function script.
2016-06-10T14:24:12.298 Compilation succeeded.
2016-06-10T14:25:04.184 Function compilation error

I basically can't modify my C# function on the fly with this issue, beacuse it never triggers a recompile.  Never saw any out of memory error you mentioned though

**Comment by fabiocav** [comment]
@kmh0237 I'm finishing up some tests in order to commit the fix for the problem reported by @mathewc, which was caused by an exception preventing the log output detailing the compilation error, but what you're seeing sounds like a problem with the change detection process. Could you share your Function App name so we can investigate?

**Comment by kmh0237** [comment]
Our function url is https://seedpro-fn-dev.scm.azurewebsites.net/api/functions/GsfmPersonnel if you are looking to investiage.  Not sure how you are going to view it, so let me know if you need any more info than that.  This was working for me as of about 1-2 days ago, then suddenly stopped working for all our functions.
