### ISSUE TITLE
Support maxParallelExecutionsPerInstance property in host.json

### ISSUE THREAD

**Issue by davidebbo** [Azure/azure-webjobs-sdk-script#430]
While I understand how `BatchSize`/`NewBatchThreshold` work together, my concern is that their semantic is too tricky, and that we’ll constantly need to explain how it works. In particular, the fact the max parallel execution is the _sum_ of `BatchSize` and `NewBatchThreshold` is very counter intuitive.

I’d like to propose an alternate model that would make things much clearer to users. The primary flag that users should care about is `maxParallelExecutionsPerInstance`. Arguably, it’s the only one that we should expose. The way it works is that we keep starting new parallel executions until we have that number running. The fact that internally we might start them in batches is more of an implementation detail that probably doesn’t affect things all that much. If we have reasonable batch defaults, then it’s pretty irrelevant to the user.

**Comment by mathewc** [comment]
Anything we do here would be done in the core SDK, so I think this suggestion should be moved there.

**Comment by davidebbo** [comment]
https://github.com/Azure/azure-webjobs-sdk/issues/747
