### ISSUE TITLE
Object Definitions documentation

### ISSUE THREAD

**Issue by jamesdixon** [Azure/azure-webjobs-sdk-script#438]
First off, great work!

Is there a good place to find some sort of documentation on what's available within the `context` objects and whatever other object is passed into the job? For example, a timer job is passed a `context` and `timerInfo` object in the examples.

I'm asking as I'm looking to create a general set of Node mocks that can be used during testing.

Thanks!

**Comment by mathewc** [comment]
Unfortunately not really yet, thanks for pointing this out. We do have the Node developer reference [here](https://azure.microsoft.com/en-us/documentation/articles/functions-reference-node/). We do need to improve this I agree :)

As we work towards GA we'll start solidifying these APIs, and before GA you can expect some breaking changes. We'll clean it up and get it documented, but for now, the best doc might be the [source code](https://github.com/Azure/azure-webjobs-sdk-script/blob/dev/src/WebJobs.Script/Description/Node/NodeFunctionInvoker.cs#L253) that actually creates the Node context object :)

**Comment by mathewc** [comment]
In general, we need to provide more documentation/examples on all the various bindings and how to use them from C#/Node, etc.

**Comment by christopheranderson** [comment]
These have been added to the docs under the bindings - for instance: here is DocDB's https://github.com/projectkudu/AzureFunctionsPortal/issues/360

If you find anything which is still missing, feel free to open specific bugs.
