### ISSUE TITLE
Edge.JS Access Violations

### ISSUE THREAD

**Issue by mathewc** [Azure/azure-webjobs-sdk-script#442]
We're occassionaly seeing the Edge.js AV exception from time to time (see Edge issue we logged [here](https://github.com/tjanczuk/edge/issues/383)). Below is the error logged to `eventlog.xml`.

```xml
<Event>
    <System>
        <Provider Name=".NET Runtime"/>
        <EventID>1026</EventID>
        <Level>0</Level>
        <Task>0</Task>
        <Keywords>Keywords</Keywords>
        <TimeCreated SystemTime="2016-06-15T21:04:17Z"/>
        <EventRecordID>698472453</EventRecordID>
        <Channel>Application</Channel>
        <Computer>RD000D3A308A72</Computer>
        <Security/>
    </System>
    <EventData>
        <Data>
Application: w3wp.exe Framework Version: v4.0.30319 Description: The process was terminated due to an unhandled exception. Exception Info: System.AccessViolationException at EdgeJs.Edge.NodeStart(Int32, System.String[]) at EdgeJs.Edge.
            <Func>b__1() at System.Threading.ThreadHelper.ThreadStart_Context(System.Object) at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean) at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean) at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object) at System.Threading.ThreadHelper.ThreadStart()

            </Data>
        </EventData>
    </Event>
```

**Comment by davidebbo** [comment]
So we're sometimes seeing it outside of the App Domain cycle scenario (which never happens in Azure)? If so, that's bad news. Maybe that's the reason behind the occasional 503s we see in Azure?

**Comment by mathewc** [comment]
In all my Function Apps I'm deploying private site extensions, forcing stops/starts, etc., so I'm not sure if unusual usage patterns like that are the cause, or if this can be reproed by normal users. I also don't know the frequency. We basically need to attempt to get a repro.

**Comment by davidebbo** [comment]
Right, if you deploy private site ext, then you'd be exposed to AppDomain restart. It may not be the same root cause as the 503 we all see occasionally in Prod. That one is nasty.

**Comment by christopheranderson** [comment]
Need to investigate if we can see this in production or if it is related to private site extensions.

**Comment by mathewc** [comment]
Closing this for now, since I saw this in the context of my own Function App that I was deploying private site extensions to, forcing restarts, etc.
