### ISSUE TITLE
System Level Event Instrumentation

### ISSUE THREAD

**Issue by mathewc** [Azure/azure-webjobs-sdk-script#451]
We should use the `IMetricsLogger` to instrument key areas of the runtime to emit events that we can monitor. E.g., any time the Host crashes, interesting SQM events, etc

`IMetricsLogger.LogEvent` is the method that can be used to log such events. WebHostMetricsLogger is the Functions implementation that logs to ETW, using the existing event pipeline.

**Comment by christopheranderson** [comment]
Should have a discussion to gather which data we want to gather. For instance:
* Crashes
* Compilation time
* Performing certain tasks

**Comment by mathewc** [comment]
We'll also want to ensure we log a correlation ID that allows us to tie file logs we emit (that customers see) to our system logs. E.g. ideal is to be able to show the ID in the portal when an error happens, and we can search based on that.

**Comment by mathewc** [comment]
Adding myself to this, since I'm going to do the work to instrument the runtime in the right places. Hosam can then plug his event writing into the TraceWriter I create.
