### ISSUE TITLE
Add the ability to Exclude Functions

### ISSUE THREAD

**Issue by mathewc** [Azure/azure-webjobs-sdk-script#452]
A proposal PR is [here](https://github.com/Azure/azure-webjobs-sdk-script/pull/441) for this feature.

**Comment by christopheranderson** [comment]
:shipit:

**Comment by mathewc** [comment]
Merged: https://github.com/Azure/azure-webjobs-sdk-script/commit/3e7309f0fbc131ba49e7b61ec04bda493be07619
