### ISSUE TITLE
Make "connection" NameResolver behavior consistent

### ISSUE THREAD

**Issue by mathewc** [Azure/azure-webjobs-sdk-script#454]
For "connection" properties the value provided must be an app setting name. We then "auto resolve" this to the app setting value at runtime. We do this for properties in general as well, but only if those values request resolution via %% syntax (see example below). We actually DONT allow you to specify the %% on the connection property value. This is somewhat inconsistent, and some users have commented (see [SO post](http://stackoverflow.com/questions/37877609/azure-functions-can-environment-variables-be-used-in-function-json/37885029?noredirect=1#comment63436274_37885029)).

We should probably support %% syntax for connection properties as well, perhaps changing our default portal logic to start injecting them for the value, once the runtime allows them. Note that any changes here will require updates to the portal picker as well.

```javascript
{
    "bindings": [
        {
            "type": "eventHubTrigger",
            "name": "input",
            "direction": "in",
            "connection": "AzureWebJobsEventHubReceiver",
            "path": "%AzureWebJobsEventHubPath%",
            "consumerGroup": "$Default"
        },
        {
            "type": "eventHub",
            "name": "output",
            "direction": "out",
            "connection": "AzureWebJobsEventHubSender",
            "path": "%AzureWebJobsEventHubPath%"
        }
    ]
}
```

**Comment by mathewc** [comment]
However, the reason it is the way it is now is because unlike other values that we allow raw values for (values that won't be auto resolved), for connection we do not  - the value must ALWAYS be the name of an app setting. Indeed, according to NameResolver rules, if %MyConnection% was specified, it actually means to name resolve the %MyConnection% value to get the name of the connection app setting name (a double indirection).

So I'm not sure now whether we should really change this - let's discuss.

**Comment by christopheranderson** [comment]
Suggestion: %% is ignored in "connection" so it remains semantically similar without having to understand the difference (for people doing best practice). Needs more discussion.

**Comment by brettsam** [comment]
To summarize the current state of things -- from the WebJobs perspective, you can have a string property that will be handled in one of the following ways:

1. it can be a literal and have no replacements performed
2. it can have all '%token%' strings replaced
3. it can be treated as the entire string is a token to be replaced (to prevent people from checking in secrets). I recently changed a bunch of WebJob Extension properties that use this pattern to end with `Setting` as a convention.

If we think that preventing secret check-in is valuable (I do) -- then we need a way to restrict some properties from ever being treated as literals. And we need to make it clear (docs maybe?) that some properties, notably 'connection', behave this way.

Whether we also allow them to be wrapped in %% is another question -- we could just auto-strip any trailing or ending %% as Chris suggests before we try to resolve. I guess if you really want to use '%%' in your app settings, then you'd need to double them up.

I do wonder if that is just begging for subtle little differences popping up from extensions (that may or may not use our helpers to do this) -- and whether it's worth it. Someone poking around by wrapping 'connection' in '%%' may think 'Oh okay then I can remove %% to use a literal!'. But then that doesn't do what they expect based on the other properties. It feels easier to just say 'This is a setting property, meant to indicate a setting name. We look it up directly'. Our errors could make the rules clear that if we can't find a setting after calling Resolve().

My vote would be to improve the error messages and docs in the interest of keeping the behavior simpler. I'd also wonder if we need to separate scenario 1 and 2 above -- is there any reason that we shouldn't just always try to replace? Then we can explain in wiki/docs/etc that we have two kinds of properties...

Linking some related issues:

- https://github.com/projectkudu/AzureFunctionsPortal/issues/117 (this has obviously confused me in the past)
- https://github.com/Azure/azure-webjobs-sdk/issues/653

**Comment by mathewc** [comment]
@brettsam I believe we're done with this work.
