### ISSUE TITLE
Timer function doesn't get triggered every hour

### ISSUE THREAD

**Issue by estruyf** [Azure/azure-webjobs-sdk-script#456]
Hi,

I have an Azure function which gets triggered every hour (normally it should only be four times a day). The cron job is configured as follows: "0 0 */1 * * *".

If you check the attached screenshot, you'll see that the job doesn't run every hour. At 12:00 everything is ok, because then I configured the function. At 13:21 the job started a bit later because another job got triggered (http trigger). That seems to have woken up the timer function and so it successfully ran.

Function didn't get executed at 15:00. At 16:00 I logged on to the Azure portal, again this have woken up the timer function. 

At 19:20 again the same HTTP trigger function got called. Same story all over.

Is this issue coming from the fact that by default the always-on functionality is turned off?

![snip_20160623220143](https://cloud.githubusercontent.com/assets/2900833/16318290/c79ad3e2-398e-11e6-82c0-86faade6d4e2.png)

**Comment by davidebbo** [comment]
Is you function app Dynamic or in Classic mode? If Classic, what sku is it using? e.g. Free/Shared/Basic/Standard

**Comment by estruyf** [comment]
Configured in dynamic mode.

**Comment by davidebbo** [comment]
Hmmm, then it doesn't make sense. Normally, there is no need for Always On in dynamic (in fact, it's not even available). Your Function App should be kept running automatically to take care of timers.

Could you share the Function App name? You can create a test one with the same issue if you prefer not to share your main one.

**Comment by estruyf** [comment]
Function app name: functionsf9516c96 - TimerTriggerNodeJS2 is the function in which I configured the test.

**Comment by cgillum** [comment]
You mentioned that there is also an HTTP trigger in this function app. We recently discovered a bug that can cause similar problems when a function app contains timer triggers as well as other trigger types.

Could you try creating a separate function app which contains only your timer trigger function(s) and see if that makes it more reliable?

**Comment by brettsam** [comment]
@cgillum / @estruyf -- Do you still see this happening?

**Comment by SeanFeldman** [comment]
Still an issue.

**Comment by brettsam** [comment]
Thanks for the report @SeanFeldman. The fix for this hasn't been deployed yet but will be soon. We'll update this issue when it's deployed and see if anyone is still seeing the problem.

**Comment by brettsam** [comment]
The fix is is now deployed so I'll close this issue. If anyone continues to see this, please reactivate so we can investigate.

**Comment by JoeBrockhaus** [comment]
@brettsam I'm seeing similar odd behavior with this trigger - rather than *not* triggering, it's triggering more than 1 time every hour - usually 2 or 3 times within a minute or so. 

My FuncApp only has 2 functions, both configured to trigger every hour, using `TimerTrigger("0 0 * * * *")`
It's on a Consumption Plan. 

I've previously had RunOnStartup = true, which seems like it might explain why the most recent execution in the screenshot fired a 4th, seemingly random time .. this would be when I navigated to the Function App in the Portal. (Seems odd this would 'wake-up' the app, but 🤷‍♂️ )

![image](https://user-images.githubusercontent.com/5933609/27408049-7747544e-56a0-11e7-86f0-56454f452cdf.png)

**Comment by brettsam** [comment]
@JoeBrockhaus -- thanks for the report. If you continue seeing this with your newest deployment, can you open up a new issue (and feel free to mention me so I get pinged right away). If you can give a timerange and your function app name (either directly or [indirectly](https://github.com/projectkudu/kudu/wiki/Reporting-your-site-name-without-posting-it-publicly)), that'd help me look through our logs to see if I can figure out what's happening.

**Comment by JoeBrockhaus** [comment]
thanks @brettsam these latest updates (1.0.0-alpha6) and disabling RunOnStartup, look to have brought it back to the single execution.
