### ISSUE TITLE
Parsing array to singleton objects is not working

### ISSUE THREAD

**Issue by jsiegmund** [Azure/azure-webjobs-sdk-script#460]
As described in our conversation [here](http://stackoverflow.com/questions/38006649/configuring-notification-tag-for-azure-function/38016828?noredirect=1#comment63498613_38016828), I'm having trouble with an Azure Function parsing the input coming from an event hub. 

The input is as follows: 
`[{"deviceid":"repsaj-neptune-win10pi","readingtype":"temperature1","reading":22.031614503139451,"threshold":23.0,"time":"2016-06-22T09:38:54.1900000Z"}]`

The data in the event hub is coming from Azure Stream Analytics. If I understand correctly, when my Function accepts a singleton class instance the above should automatically be parsed to one singleton item. This is not the case, instead I'm getting: 

> 2016-06-24T18:25:16.830 Exception while executing function: Functions.submerged-function-ruleout. Microsoft.Azure.WebJobs.Host: Exception binding parameter 'inputMessage'. Microsoft.Azure.WebJobs.Host: Binding parameters to complex objects (such as 'RuleMessage') uses Json.NET serialization. 1. Bind the parameter type as 'string' instead of 'RuleMessage' to get the raw values and avoid JSON deserialization, or 2. Change the queue payload to be valid json. The JSON parser failed: Cannot deserialize the current JSON array (e.g. [1,2,3]) into type 'Submission#0+RuleMessage' because the type requires a JSON object (e.g. {"name":"value"}) to deserialize correctly. To fix this error either change the JSON to a JSON object (e.g. {"name":"value"}) or change the deserialized type to an array or a type that implements a collection interface (e.g. ICollection, IList) like List that can be deserialized from a JSON array. JsonArrayAttribute can also be added to the type to force it to deserialize from a JSON array.

I also tried changing the parameter type to an array instead, this doesn't work either. For more info see SO question.

**Comment by mathewc** [comment]
So what you're saying is that the actual JSON data for each of your events is an array, rather than a JSON object? If that is the case, I can see how the binding would not work. It can either map to a **singleton** in which case it expects the event data to be a JSON object, or a **batch** of events, in which case the runtime will fetch batches of events from the hub and pass them to your function in one go. However in this case, we still currently expect each of those messages to be a JSON object.

Do you control the ingest of these events into your hub? Can you make them JSON objects rather than arrays?

**Comment by christopheranderson** [comment]
Related? https://github.com/Azure/azure-webjobs-sdk-script/issues/458

**Comment by jsiegmund** [comment]
That's correct, the precise input which the function gets from the event hub is: 

`[{"deviceid":"repsaj-neptune-win10pi","readingtype":"temperature1","reading":22.031614503139451,"threshold":23.0,"time":"2016-06-22T09:38:54.1900000Z"}]`

So that's an array with one single element. The data comes from: 

IoT Hub => Stream Analytics Query => Event Hub => Function

I've checked the output for the ASA job, which is set to output JSON data in Array format. I guess it always produces an array even if there's only one item to output. The other option I have there is "line seperated", so I tried that one instead which actually works. But I think that's due to the fact that at the moment the ASA job is not producing more than one item at a time. When I input the following manually, it fails again:

`{"deviceid":"repsaj-neptune-win10pi","readingtype":"temperature1","reading":22.031614503139451,"threshold":23.0,"time":"2016-06-22T09:38:54.1900000Z"}
{"deviceid":"repsaj-neptune-win10pi","readingtype":"temperature1","reading":22.031614503139451,"threshold":23.0,"time":"2016-06-22T09:38:54.1900000Z"}`

In my opinion, the array formatting is actually better than line seperated and should be parsed correctly into an array of POCO's by the runtime when the function accepts this as a parameter, even if there's only one item in there.

**Comment by mathewc** [comment]
Our binding (actually all the Functions/WebJobs bindings) when binding to a POCO type expects payload to be a JSON singleton, not an array. Same goes for queue bindings, etc. The array support for the EventHub binding is for retrieving multiple events in a batch, not deserializing single event arrays into objects.

The right way forward for your scenario is to either bind to the raw `EventData` or to a string. You can then handle the event data yourself. These binding options are detailed here: https://github.com/Azure/azure-webjobs-sdk/wiki/EventHub-support

**Comment by jsiegmund** [comment]
Hi Mathew,

I understand this. But it was your advise to change to a POCO because I wanted to set the TagExpression property of the binding to some data origination from my input object. So on the one hand I should use a POCO, but on the other hand there is no way to deserialize the input the event hub generates (which I cannot change) into POCO's.

I'm more than happy to switch back to handling the raw string and converting it to an array of objects myself, but how do I then set the TagExpression?

**Comment by mathewc** [comment]
Yes, when you're not binding to a POCO, you'll loose the parameter binding allowing you to bind to message properties from the POCO parsed from the event. ASA is complicating this pipeline - I'd check with them to see if you can't get them to output a singleton in the event payload.

However, there is an advanced way you can get things to work, using our dynamic `IBinder` support. See an example below. Basically, IBinder allows you to bind to the underlying WebJobs SDK attribute for the binding (in your case it would be `NotificationHubAttribute`). The below example news up the BlobAttribute specifying the path, and writes the output.

```csharp
using System;
using Microsoft.Azure.WebJobs;

public static void Run(string myQueueItem, IBinder binder, TraceWriter log)
{
    var attribute = new BlobAttribute("test/ibinder");
    var textWriter = binder.Bind<TextWriter>(attribute);
    textWriter.Write("testing");
    
    log.Info($"C# Queue trigger function processed: {myQueueItem}");
}
```

In our case, I think you'd need something like the below. Note that using `IAsyncCollector` means you need to declare your function as async. Then you can process your input array, new up Notification instances setting all the notification properties you want, and call `notifications.AddAsync(notificaiton)` for each. When the function returns, all the notifications will be sent.

```csharp
var attribute = new NotificationHubAttribute
{
    ConnectionStringSetting = "<appsetting>",
    HubName = "<hubname>"
};
var notifications = binder.Bind<IAsyncCollector<Notification>>(attribute);
```

**Comment by jsiegmund** [comment]
Any pointers as where to find the NotificationHubAttribute class? I need a reference but I have no clue to which namespace.

**Comment by mathewc** [comment]
Yes, that is the attribute. To get this to compile, you need to add a #r reference to **Microsoft.Azure.WebJobs.Extensions.NotificationHubs** (the assembly where the attribute lives). However, there is an issue which makes that somewhat difficult. That assembly isn't part of our "default set", so you can't simply do: `#r "Microsoft.Azure.WebJobs.Extensions.NotificationHubs"` as you'd expect. Either you'd have to add a package reference to the Nuget package containing the NH extension, or use the full path `#r "D:\Program Files (x86)\SiteExtensions\Functions\0.3.10261\bin\Microsoft.Azure.WebJobs.Extensions.NotificationHubs.dll"` into the Functions runtime bin dir.

Neither of these options are great. I've logged bug #472 so we can improve this.

**Comment by jsiegmund** [comment]
Ok. I've added the reference which solved the compiler error. I've introduced the IBinder parameter, set the NotificationHubAttribute with the correct connectionstring and hub name, all is well. The messages are being added to the collection, but nothing happens after the function exists. 

I removed the old notification hub binding to see whether that would make a difference which it doesn't. So there's no errors any more, everything seems to be OK but no messages are being sent. Any ideas on how to proceed?

**Comment by mathewc** [comment]
Can you please share your code?

**Comment by jsiegmund** [comment]
The code is not pretty at the moment, but here it is: https://gist.github.com/jsiegmund/e3ddc1d1783423d6f1787a4b0575ee4c

**Comment by mathewc** [comment]
I believe your issue is that you're not awaiting on IAsyncCollector.AddAsync. It's async, so you'll have to change your method signature to async. If you do that, you'll have to change your blob binding from `out string` to something like Stream or TextWriter and write to that.

Another option you could try is to bind to ICollector rather than IAsyncCollector.

**Comment by jsiegmund** [comment]
When I change to:

`IAsyncCollector<Notification> notifications = await binder.Bind<IAsyncCollector<Notification>>(attribute);`

The error changer to:

`run.csx(40,51): error CS1061: 'IAsyncCollector<Notification>' does not contain a definition for 'GetAwaiter' and no extension method 'GetAwaiter' accepting a first argument of type 'IAsyncCollector<Notification>' could be found (are you missing a using directive or an assembly reference?)`

So I tried option 2:

`ICollector<Notification> notifications = binder.Bind<ICollector<Notification>>(attribute);`

Also had to change from AddAsync to Add, then compiling works. But now when I execute:

`Exception while executing function: Functions.submerged-function-ruleout. mscorlib: Exception has been thrown by the target of an invocation. Microsoft.Azure.NotificationHubs: Value cannot be null.
Parameter name: connectionString.`

So it says the connectionstring isn't set, but I did specify it in the NotificationHubAttribute class and have double checked it's set (and valid). So I'm not sure why it would say that.

**Comment by jsiegmund** [comment]
Still haven't been able to resolve this (I left it aside for a while). After upgrading to the latest version of the runtime, the error has changed: 

Exception while executing function: Functions.submerged-function-ruleout. mscorlib: Exception has been thrown by the target of an invocation. Microsoft.Azure.WebJobs.Host: 'Endpoint=sb://repsaj-neptune-notifications.servicebus.windows.net/;SharedAccessKeyName=DefaultFullSharedAccessSignature;SharedAccessKey=xxx' does not resolve to a value.

No clue what to do with that.

**Comment by mathewc** [comment]
That error indicates that you're incorrectly attempting to put an actual connection string in your function.json file for a "connection" property. This property should be the name of an **app setting** that contains the value of the connection string. This indirection is for security reasons, to avoid people putting their secrets in their source code.
