### ISSUE TITLE
nodejs Function calling NotificationHubService fails

### ISSUE THREAD

**Issue by ontopo** [Azure/azure-webjobs-sdk-script#461]
Callback never fires when using a NotificationHubService created an in Azure Function. 

`var NotificationHubService = require('azure-sb').NotificationHubService;`
`var hubName = "[name]";`
`var connectionString = "[Endpoint=sb://]";`
`var notificationHubService = new NotificationHubService(hubName, connectionString);`
`module.exports = function (context, input) {`
`    var installationId = "[id]";`
`    notificationHubService.getInstallation(installationId , function (e,r) {`
`        context.log('done');    `   
`        context.done();`
`    });`
`}`

**Comment by pragnagopa** [comment]
I can repro this issue. 
getInstallation is only available in the latest azure-sb npm package version: 0.10.2 

Following works outside of function app:
var azure = require('azure-sb');
var notificationHubService = azure.createNotificationHubService('hubName','ConnectionString');
var installationId = 'id'; 
notificationHubService.getInstallation(installationId , function (err, res) {
        if (err) {
           context.log('error');
         }
        context.log('getInstallation done', installationId);
        context.done();
  });
Callback is not invoked

**Comment by brettsam** [comment]
Neither @pragnagopa nor I were able to repro this on the latest Functions build with the latest azure-sb package. The NH operations come back quickly as expected. Please reactivate if you're able to still repro this.
