### ISSUE TITLE
Continuous integration syncing after clicking "No" 

### ISSUE THREAD

**Issue by jsiegmund** [Azure/azure-webjobs-sdk-script#463]
Not entirely sure whether this is the proper place to log this one, let me know if it's not. I've set-up contiuous integration for my Azure Functions. Configured a github repo as a source. When I now click sync, it asks me: 

"Are you sure you want to retrieve and deploy contents from your GitHub repository?"

I wasn't completely sure the first time, so I clicked 'No' but to my surprise it started syncing anyhow. Ended up with a green checkbox so everything seems to be fine, but I didn't expect it to sync after clicking No.

**Comment by mathewc** [comment]
I've moved this to the Kudu repo here: https://github.com/projectkudu/kudu/issues/2066
