### ISSUE TITLE
Renaming/Deleting function.json does not stop timer trigger

### ISSUE THREAD

**Issue by suwatch** [Azure/azure-webjobs-sdk-script#464]
I just tested with timer trigger (not sure if apply to others).   If I changed the content of function.json (say change scheduler and set disabled to true), the change took effect automatically.   However, if I renamed or deleted the function.json, the timer continue to run.   My apology if already duplicated issue somewhere.

**Comment by mathewc** [comment]
I just tried this in prod and I can't repro it. I also tried locally as well - when a function.json file is deleted, we correctly restart the host, removing the timer function.

Can you provide a repro for this?

**Comment by mathewc** [comment]
No repro. If you keep seeing this and have a repro, please reopen :)
