### ISSUE TITLE
need a way to retrieve event hub message headers

### ISSUE THREAD

**Issue by reyang** [Azure/azure-webjobs-sdk-script#465]
For eventHubTrigger, is there a way to get the event hub message headers? Currently only the message payload is provided – while there are a lot of useful information from the headers I wish to retrieve.
Also, it'll be very helpful if there is an example of how to properly handle error - for example, if exception happened while trying to process the event, instead of removing the event from the service bus, leave it and have a chance to retry. This would require access to the retry count, lease time, etc.

**Comment by mathewc** [comment]
In the case of C# functions, you can bind to the raw SB messaging `EventData` Type as described in the wiki [here](https://github.com/Azure/azure-webjobs-sdk/wiki/EventHub-support). I assume `EventData` has all the information on an event you would require.

**Comment by reyang** [comment]
NodeJS, however I will also be interested to know if there is a C# example.

**Comment by MikeStall** [comment]
@reyang - 

1. "if exception happened while trying to process the event, instead of removing the event from the service bus, leave it and have a chance to retry. "  Eventhub is a high throughput system; to keep up with the volume, we receive the events in a batch and checkpoint the entire batch. We don't have support for granular checkpointing. Is this essential for your scenarios? 

2. We can promote some of the properties directly to the "binding data" so that it can be accessible from other languages. We already do this for PartitionContext. 
When you refer to "headers", which properties on EventData / PartitionContext exactly are you interested in accessing?

**Comment by xscript** [comment]
@MikeStall to answer your 2nd question, we want to access [EventData.SystemProperties](https://msdn.microsoft.com/en-us/library/azure/microsoft.servicebus.messaging.eventdata.systemproperties.aspx). Property keys we want to access are:
- iothub-connection-device-id
- iothub-connection-auth-method
- iothub-connection-auth-generation-id

And I think people might also would like to access [EventData.Properties](https://msdn.microsoft.com/en-us/library/azure/microsoft.servicebus.messaging.eventdata.properties.aspx) for custom properties in their event data. Although we don't have such requirement yet, it is giving more flexibility to user when dealing with complicated scenarios.

**Comment by mathewc** [comment]
We also need to add the ability for people to set EventData properties like PartitionKey etc. for output bindings. Currently for languages like Node.js.

**Comment by mathewc** [comment]
Addressed via https://github.com/Azure/azure-webjobs-sdk-script/pull/1337. You can now access all the EventData properties via `context.bindingData`.

**Comment by mathewc** [comment]
See wiki page here for more info: https://github.com/Azure/azure-webjobs-sdk-script/wiki/Trigger-Binding-Data

**Comment by reyang** [comment]
Great, thank you! 👍

**Comment by vjrantal** [comment]
> See wiki page here for more info: https://github.com/Azure/azure-webjobs-sdk-script/wiki/Trigger-Binding-Data

A small improvement proposal to the code in above page. There is line `id = input[i].value;`, but I believe that should be `id = events[i].value;` to match the way the argument is named.

Also, should this be already in production? I created a new function, but with a quick look, the `bindingData` property did not contain `propertiesArray` and `systemPropertiesArray`.

**Comment by vjrantal** [comment]
Tested again today and now the properties were there - thanks!

@mathewc The small error in the sample code seems to still be there (see my previous comment).
