### ISSUE TITLE
Storage errors when using Functions and unable to execute

### ISSUE THREAD

**Issue by Xaniff** [Azure/azure-webjobs-sdk-script#466]
I created a new Functions instance last night and just started from the HTTP Get trigger template. I looked through the interface, which I found to load very slowly and started noticing that I was getting repeated errors that'd stack along the right side of the screen. I've attached a picture of these below.

On top of that, even if I make no changes to the function, it doesn't appear to work. Perhaps I'm missing a publish button somewhere, but if I visit the function URL made available to me, I get a 503 Service Unavailable error. 

Again, this is with either no or few changes made to the default script available. I'm using Chrome 51.0.2704.103 m and have experienced this over three instances that span a re-log into Portal, several browser reloads and a reboot of my own machine to no avail.

![pageerrors](https://cloud.githubusercontent.com/assets/2238529/16457222/49c8bca8-3de0-11e6-930a-3ba32a018eb7.PNG)

**Comment by mathewc** [comment]
Hmmm, I just tried to repro this by creating a new Function App and Http function, and ran into no issues. Are you still experiencing issues? There is no "publish" button - when making code changes in the portal all you need to do is hit "Save" and the function updates will be live.

If you're still having issues, please provide the exact repro steps and your function source code (assuming you've modified from the default template).

**Comment by Xaniff** [comment]
If I load up the Functions app I've already got, I immediately start getting these issues again.

I created a new one with the following steps:

1) Create new Functions app
2) Specify name, existing resource group, existing storage account
3) Load Function app
4) See "Get started quickly" screen and select "Webhook + API" and C#. Click Create this function.
5) See error appear (and so far it has yet to actually show the function screen now).

![image](https://cloud.githubusercontent.com/assets/2238529/16462868/df04632c-3df8-11e6-8078-3b62665b4b73.png)

**Comment by Xaniff** [comment]
@mathewc I just attempted to create a new Functions app again with a new resource group and a new storage account and it was significantly more responsive and looks as though it's working fine. Is there potentially an issue with using a hot Blob Storage account compared to whatever sort it the instance creates on its own?

**Comment by davidebbo** [comment]
@Xaniff what do you mean by a "*hot* Blob Storage account"?

**Comment by Xaniff** [comment]
@davidebbo Was originally using the hot blob storage account as described at https://azure.microsoft.com/en-us/documentation/articles/storage-blob-storage-tiers/ 

Having gotten this to work successfully when I let the Functions app instantiate the storage account itself, it looks like it's a problem of Functions allowing me to specify storage accounts that aren't actually supported (since it looks like Functions needs access to the table storage).

**Comment by mathewc** [comment]
Functions needs a **full** storage account (queues/blobs), and it seems that your "hot blob" account is **only for blobs**, so that won't work with Functions. That was the issue.

**Comment by Xaniff** [comment]
@mathewc I'd recommend making that a mention when instantiating the Functions app since it didn't otherwise put any blockers up to me selecting the blob-only storage accounts (unless you can otherwise restrict that filter to only show full storage accounts).

**Comment by mathewc** [comment]
Agreed - I've just opened a Portal issue for this: https://github.com/projectkudu/AzureFunctionsPortal/issues/427. Thanks :)
