### ISSUE TITLE
Putting spaces in function name, while allowed, results in inaccessible function

### ISSUE THREAD

**Issue by Xaniff** [Azure/azure-webjobs-sdk-script#467]
Let's say I make a function called "String Generator". The Function URL provided for the function will end in "/api/String Generator?code=xyz". Of course, when you visit this, it will be transformed to "/api/String%20Generator?code=xyz" and won't actually execute the function at all.

Resolution:
Could you either:

1) Provide the ability to specify the output pathname to the function (so you can have human-readable function names in the Portal)
2) Not allow spaces to be used in the Function name?

**Comment by mathewc** [comment]
The space issue was actually just fixed in the release we rolled out yesterday. If you upgrade your Function App to 0.3 it will work. I just verified myself.

**Comment by Xaniff** [comment]
Indeed it is working with 0.3 - thanks!
