### ISSUE TITLE
Nuget packages for Functions are not restored when deployed from CI

### ISSUE THREAD

**Issue by jakkaj** [Azure/azure-webjobs-sdk-script#469]
I created a new function and uploaded to GitHub (https://github.com/jakkaj/JWTFunctions/tree/master/JWTWithJWKValidator) and linked it to my function app CI build. 

I made a change to trigger a deployment and the function failed to build with missing assembly references. It would seem that the upload from CI did not trigger a Nuget package restore.

I went in to Kudu and made a small change to the project.json file which caused a package restore to fire after which the function worked as expected. 

Of note: adding packages after the first initial restore works. Also of note is that my function app had another working, non-source control created function already.

**Comment by fabiocav** [comment]
Issue #312 tracks this. In the meantime, you can use this Kudu deployment script to handle package restore at deployment time: https://github.com/fabiocav/webjobs-scripts-samples/tree/master/DeploymentScript 
You can find information on how to use the script here: https://github.com/projectkudu/kudu/wiki/Customizing-deployments

**Comment by jakkaj** [comment]
Thanks Fabio - missed that one somehow. 

Cheers, 

Jordan.
