### ISSUE TITLE
Need to improve Extension assembly loading

### ISSUE THREAD

**Issue by mathewc** [Azure/azure-webjobs-sdk-script#472]
See issue #460 for details. We should find a way to automatically include extension assemblies in the default resolution set, allowing them to be easily `#r`'ed. Currently we've been explicitly adding each to a white list as we onboard them.

I think we should extend [ExtensionSharedAssemblyProvider](https://github.com/Azure/azure-webjobs-sdk-script/blob/dev/src/WebJobs.Script/Description/DotNet/ExtensionSharedAssemblyProvider.cs) so that it automatically adds the extension assembly (i.e. the assembly where the `ScriptBindingProvider` was sourced from).

**Comment by mathewc** [comment]
Or, perhaps we could add an assembly provider that will automatically resolve any assemblies from the runtime bin dir. We could register that "catch all" resolver last.

**Comment by fabiocav** [comment]
We need to discuss how we'd want to expose this. The initial implementation was opt-in by design, as we need to be careful about the shared assemblies we expose. Exposing every host dependency as a shared assembly would complicate versioning and increase the impact of runtime updates on functions.

**Comment by mathewc** [comment]
What do you suggest as a design? We need to make it easy for people to reference our built in assemblies. E.g, in our bin dir, we have all the extension assemblies they need to reference. If they #r one of those we should be able to resolve it.

**Comment by fabiocav** [comment]
That should be true for some the core assemblies we want to expose (and support), but exposing everything the host depends means that even changing dependencies meant for internal use (e.g. Autofac, Edge, Roslyn assemblies, etc.) would be a potential breaking change.
This will likely also change as we move forward with the extensibility model implementation, as extensions and their dependencies won't necessarily be in the host's bin folder.
I have some ideas on this and will work on documenting a design so we can enhance the experience.

**Comment by mathewc** [comment]
If we don't make it easy for people to reference SDK assemblies, the alternative is that people will use project.json which is harder, and also opens the door for dll hell, since they'll be referencing a specific version of an assembly, which may differ from the one actually being used by the runtime, leading to conflicts.

**Comment by fabiocav** [comment]
Agreed. We just need to be careful on how we approach this so we don't lead people down the wrong path. The story is already a little better now after your last round of changes since the shared assemblies set is no longer completely managed by the host and every extension can add to that set. We just need to make sure that's easy to do, but I still believe we need this to be an opt-in thing.
