### ISSUE TITLE
Assebly loader fails to load retargetable assemblies

### ISSUE THREAD

**Issue by fabiocav** [Azure/azure-webjobs-sdk-script#478]
The `ResolveAssembly` handler does not properly handle retargetable and redirected assemblies, causing load failures when functions depend on those assemblies.

**Comment by fabiocav** [comment]
@Azure/azure-functions-triage got a fix for this together while troubleshooting a reported issue. Since the PR has bee submitted, I'm assigning this to the next milestone, but feel free to change if you have objections.

**Comment by mathewc** [comment]
Your call on the milestone. Let's just get it in if you're confident on the fix.
