### ISSUE TITLE
cron expression format

### ISSUE THREAD

**Issue by jamesdixon** [Azure/azure-webjobs-sdk-script#482]
Hi, 

I read in #329 that you use the NCrontab format, specifically the 6 field format. When I view the documentation, I'm not seeing a 6th field -- just 5.

I'm trying to set a trigger to kick off every Monday at 1am using the following expression: `0 1 * * 1`.

Unfortunately, I'm seeing the following error: `'0 1 * * 1' is not a valid CRON expression.`

Thanks,
James

**Comment by mathewc** [comment]
Yes, we use 6 fields. What documentation are you referring to?

**Comment by jamesdixon** [comment]
https://github.com/atifaziz/NCrontab

Maybe I'm missing something?

**Comment by mathewc** [comment]
CronTabSchedule.Parse takes an options that allows us to declare that we want seconds. See our TimerTrigger code here: https://github.com/Azure/azure-webjobs-sdk-extensions/blob/master/src/WebJobs.Extensions/Extensions/Timers/Scheduling/CronSchedule.cs#L22.

He chose to focus his doc on the more common 5 field format I guess.

**Comment by jamesdixon** [comment]
Thanks, @mathewc! That did the trick 👍
