### ISSUE TITLE
%rand-guid% behavior is broken

### ISSUE THREAD

**Issue by mathewc** [Azure/azure-webjobs-sdk-script#487]
The binding refactors we released in the last 0.3 update ended up inadvertently breaking this. Recent changes were introduced to `BindingMetadata` to pre-resolve all metadata properties at index time, meaning out bindings that use %rand-guid% won't get a unique ID per invocation.

**Comment by everyonce** [comment]
Thanks!

**Comment by mathewc** [comment]
FYI: We're planning on getting this fix out by end of week.

**Comment by scottzilla** [comment]
Was this ever pushed out?

**Comment by mathewc** [comment]
Yes it was fixed. As part of the fix, the syntax has changed. In a binding expression, you should use {rand-guid} rather than %rand-guid%, e.g.:

```javascript
{
    "bindings": [
        {
            "type": "queueTrigger",
            "direction": "in",
            "name": "input",
            "queueName": "scenarios"
        },
        {
            "type": "blob",
            "name": "blob",
            "direction": "out",
            "path": "{Container}/{rand-guid}"
        }
    ]
}
```
