### ISSUE TITLE
Run webjob from the same virtualenv as website

### ISSUE THREAD

**Issue by sxamit** [Azure/azure-webjobs-sdk-script#5]
I am trying to run webjob python script and unable to import packages. All the packages are installed in wwwroot/env (the web site virtual env). How can I activate the virtualenv from the webjob?

**Comment by mathewc** [comment]
Can you try using the full path to your packages as in [this SO post](http://stackoverflow.com/questions/33525301/import-numpy-in-python-webjob-on-azure)?

**Comment by sxamit** [comment]
I added the line :
execfile('D:/home/site/wwwroot/env/Scripts/activate_this.py', dict(__file__='D:/home/site/wwwroot/env/Scripts/activate_this.py'))

to the start of my py file
