### ISSUE TITLE
Override default settings for Service Bus entities

### ISSUE THREAD

**Issue by christopheranderson** [Azure/azure-webjobs-sdk-script#501]
We have some default settings we use for Service Bus for how we set up the Queue/Topic. We should consider exposing that as configurable via host.json for folks who want to change them.

**TBD** Which settings should be exposed?

**Comment by mathewc** [comment]
We already do have a host.json config section for the ServiceBus knobs - see https://github.com/Azure/azure-webjobs-sdk-script/wiki/host.json. These knobs map to the underlying ServiceBusConfiguration here: https://github.com/Azure/azure-webjobs-sdk/blob/master/src/Microsoft.Azure.WebJobs.ServiceBus/Config/ServiceBusConfiguration.cs.

Functions already supports maxConcurrentCalls. I'm adding support for prefetchCount now (it was left out).

**Comment by mathewc** [comment]
Closing this since I think we have all the knobs we need. Please reopen if you think there are more that should be added, though that would be a core SDK issue to start with.
