### ISSUE TITLE
Invoking function in portal: "Unable to convert trigger to IStorageQueueMessage."

### ISSUE THREAD

**Issue by brettsam** [Azure/azure-webjobs-sdk-script#502]
I keep sporadically getting this error message when I set up a QueueTrigger (appears to affect both C# and Node). When I try to Run it from the portal, I'll sometimes get this error message: 
`Exception while executing function: Functions.QueueTriggerCSharp1. Microsoft.Azure.WebJobs.Host: Exception binding parameter 'myQueueItem'. Microsoft.Azure.WebJobs.Host: Unable to convert trigger to IStorageQueueMessage.`

Then, without changing anything in the code or request body, it'll start working again if I:
- restart the site
- switch to another function and then switch back

Since I'm not sure how to trigger the error, I haven't been able to come up with a solid repro or workaround. I'll update this if I find a way to reliably repro.

**Comment by stephlocke** [comment]
Hi, I'm getting this issue. Is there are an ETA for correction and a workaround in the interim?

----
My code that's getting the issue

run.csx
```
using System;
public static void Run(string myQueueItem, dynamic inputDocument, 
TraceWriter log)
{
    log.Info($"C# Queue trigger function processed: {myQueueItem}");
    log.Info(inputDocument);
}
```

function.json
```
{
  "bindings": [
    {
      "name": "myQueueItem",
      "type": "queueTrigger",
      "direction": "in",
      "queueName": "docdbsuccess",
      "connection": "xxx_STORAGE"
    },
    {
      "type": "documentDB",
      "name": "inputDocument",
      "databaseName": "ItemDb",
      "collectionName": "xxx",
      "id": "{queueTrigger}",
      "connection": "xxx_DOCUMENTDB",
      "direction": "in"
    }
  ],
  "disabled": true
}
```

project.json
```
{
  "frameworks": {
    "net46":{
      "dependencies": {
        "Microsoft.Azure.DocumentDB": "1.9.3"
      }
    }
   }
}
```

**Comment by mathewc** [comment]
@davidebbo and I have also seen this often. I think it is related to https://github.com/projectkudu/AzureFunctionsPortal/issues/501, with the underlying issue being that during Portal invoke sessions an empty payload is being sent for the message, hence the conversion error.

I think you can reproduce this by deleting the Run box contents, or setting it to an empty json block like {}

**Comment by davidebbo** [comment]
I don't think you can reproduce it manually. When in that state, the portal sends bad data in a format that's not normally possible.

In any case, to work around, just re-enter the relevant data in the test data box.

**Comment by mathewc** [comment]
@ahmelsayed Has the portal fix for this been deployed?

**Comment by ahmelsayed** [comment]
it's in dev, so it's on https://functions-next.azure.com. It hasn't be pushed to prod yet

**Comment by brettsam** [comment]
Hey @ahmelsayed -- this is fixed and in prod now, right? If not, I'll re-open.
