### ISSUE TITLE
Can't get the function ID

### ISSUE THREAD

**Issue by buchizo** [Azure/azure-webjobs-sdk-script#504]
Currently, the function app can't get function ID. I would like to get function ID. Example, If I write any files using the function ID as follows:
xxxx_&lt;function id&gt;.log

If I can use function ID in file name, that association will be easy to function log table data.

**Comment by christopheranderson** [comment]
Could you be more specific? Function ID is the function name. 

Do you mean execution ID?

**Comment by buchizo** [comment]
@christopheranderson Yes, It means execution ID.

**Comment by mathewc** [comment]
You can access the invocation ID in a Node function via `context.bindingData.InvocationId`. In a CSharp function, you can access it by adding an `ExecutionContext executionContext` parameter as follows:

```csharp
public static void Run(string input, ExecutionContext context, TraceWriter log)
{
    log.Info($"InvocationId: {context.InvocationId}");
}
```

**Comment by buchizo** [comment]
@mathewc Great! Thanks a lot. :)

**Comment by buchizo** [comment]
@mathewc Is supported ExecutionContext in csx, just now? I got error as follows: 
Microsoft.Azure.WebJobs.Host: Error indexing method 'Functions.HttpTriggerCSharp1'. mscorlib: An item with the same key has already been added.

* Runtime version: Latest (~0.4)
* However JavaScript is success (context.bindingData.invocationId)

**Comment by mathewc** [comment]
Change the parameter name from "context" to something else, e.g. "executionContext" and it works. The bug is that we have an internal system parameter named "context" already. We'll address that issue.

**Comment by buchizo** [comment]
@mathewc works fine! Thanks.

**Comment by niemyjski** [comment]
Is there any way to get the id without referencing any azure packages? I'd love to have Run(string id, MyModel data, CancellationToken token)
