### ISSUE TITLE
CLI: templates.json staged in repo

### ISSUE THREAD

**Issue by suwatch** [Azure/azure-webjobs-sdk-script#514]
When creating a new function, this new file `templates.json` (70kb) shows up on the repo.   Maybe, .gitignores it, or put it somewhere outside repo folder so it won't get commit with repo.

**Comment by ahmelsayed** [comment]
this is a yeoman generator bug. /cc @hhawkins

**Comment by suwatch** [comment]
Can we redirect to other non repo folder?  If not, would you consider .gitignores?  People see this file staged and may wonder to whether commit with or without it.   

It would be perfect if people can just `func new` then `git commit -a -m ...` w/o worrying about other function-unrelated files.

**Comment by hhawkins** [comment]
The current issue is the way the generator and request is setup in order to utilize the json file. I'm currently looking into a way for it to either place it in a different place or to not download the file altogether so that the file won't be in the way.

**Comment by ahmelsayed** [comment]
yes, ideally you'd just keep the file in memory and never write it to disk

**Comment by hhawkins** [comment]
Got you. I just committed and published a fix that no longer does this.
