### ISSUE TITLE
httpTrigger generate "Status: 502 Bad Gateway" when setting errors from mssql in res.body

### ISSUE THREAD

**Issue by reges-davud** [Azure/azure-webjobs-sdk-script#520]
Ran into 502 errors today implementing mssql for querying Azure MSSQL.  The feedback from the logs are pretty much non existent for these errors, but managed to figure it out and below are sample code that generated the error. Ran a query against a table that didn't exist.

```javascript
const sql = require('mssql');
const config = require('../db.config');

module.exports = (context, req) => {
    new sql.connect(config).then(() => {
        new sql.Request()
        .query('SELECT * FROM table_dosent_exist').then((recordset) => {
            context.res = { body: recordset };
            context.done();
        }).catch((err) => {
            context.res = {
                status: 500,
                body: err
            };
            context.done();
        });
    }).catch((err) => {
        context.res = {
            status: 500,
            body: err
        };
        context.done();
    });
};
```

The response in the output window from within the function app portal is ```There was an error running function (getTest). Check logs output for the full error.``` If I run the same code in a node/express project the error I get is the following
```json
{
  "name": "RequestError",
  "message": "Invalid object name 'table_dosent_exist'.",
  "code": "EREQUEST",
  "number": 208,
  "lineNumber": 1,
  "state": 1,
  "class": 16,
  "serverName": "xxxxxxxx",
  "procName": "",
  "precedingErrors": []
}
```

What solved it for me was to change ```body: err``` to ```body: JSON.parse(JSON.stringify(err))```. Obviously this is not the optimal solution, but either I have misunderstood something or there's a possible improvment.

Cheers, Davud

**Comment by christopheranderson** [comment]
//cc @mathewc 

I think this might be a runtime issue - it looks like the runtime is barfing when given a object it can't serialize to JSON. @mathewc - I thought we had added some protections here, but I could be wrong. Maybe we just did it for context.log?

**Comment by mathewc** [comment]
The err object returned from the mssql module gets serialized with 4 properties: code (string), message (string), (name) string, and constructor (function). We receive this error object as an ExpandoObject from Edge.js, and our conversion code blows up on it for some reason with a FatalExecutionEngineError.

**Comment by jamesvsshark** [comment]
I am seeing a similar issue with using mongoose/mongodb api with Cosmos on Azure function. Data that cant be serialized is throwing 502 - Web server received an invalid response while acting as a gateway or proxy server.

Only if I JSON.stringify the req body it works fine.
