### ISSUE TITLE
Make connection selection blade pop out more obvious when waiting for user input

### ISSUE THREAD

**Issue by christopheranderson** [Azure/azure-webjobs-sdk-script#523]
## Problem:

In the usability review, users were not immediately aware that the functions editor window was waiting for input from the storage selector blade. They were staring at the spinning wheel next to the input that appears after you click + new.

## Proposed solution: 

When the selector blade pops out, we'll darken the functions editor and put a spinner in the middle of the screen until input is received, with a message on what we're waiting for. This should provide more context that we're waiting on an input.

### Functions User

 - I can tell that there is input needed from me that is on a different blade for the integrate tab.

## Requirements:

 - The functions portal should darken with a centered spinner when waiting for input from a different blade for connection selection on the integrate tab.
 - The functions portal should allow me to cancel connection selection from the darkened overlay
 - The functions portal should provide some textual context on why it is darkened and spinning
 - The functions portal should stop displaying the darkened display with spinner when the input is received and ready for user input again.

## Mockups:

 TDB - @christopheranderson will deliver mockups for this and several other items

**Comment by ahmelsayed** [comment]
wrong repo?

**Comment by christopheranderson** [comment]
Yes... just realized I'm in the wrong repo....

**Comment by christopheranderson** [comment]
Wrong repo
