### ISSUE TITLE
Investigate potential data loss during function stress run

### ISSUE THREAD

**Issue by akurmi** [Azure/azure-webjobs-sdk-script#524]
See internal thread on this

**Comment by christopheranderson** [comment]
Could you please add details here as well?

**Comment by akurmi** [comment]
This shouldn't be assigned to me. This should be assigned to someone who has a good understanding of the runtime.

**Comment by mathewc** [comment]
I think the ask from triage for you was to provide more concrete details. This issue isn't descriptive enough and isn't actionable at all for anyone as it stands now.

**Comment by mathewc** [comment]
Closing this since there are no details or repro steps.
