### ISSUE TITLE
ServiceBus Queue Receiver processing items serially

### ISSUE THREAD

**Issue by sudsy** [Azure/azure-webjobs-sdk-script#528]
I set up a contrived test case that sleeps for 10 seconds before returning to experiment with Azure functions before possible deployment.

My function is https://pvlfunctions.scm.azurewebsites.net/api/functions/packetprocessor

I fire 100 items into the service bus queue but the function processes them serially with only one instance firing up. I have tried altering the service bus defaults but with no luck. 

I am on the dynamic plan and all that I read suggests that 10 instances should fire up on the default settings. Not sure what is going wrong here.

**Comment by christopheranderson** [comment]
This is a known issue. We don't have dynamic scale turned on yet for Service Bus and Event Hub. Service Bus will be deployed soon. Created a Known Issues page to help track this - https://github.com/Azure/AzureFunctions/wiki/Known-Issues

**Comment by mathewc** [comment]
To clarify, you should be seeing concurrent processing on the single instance, since by default we configure the ServiceBus **MaxConcurrentCalls** to 16. But what Chris said is correct regarding us spinning up multiple Function App instances to handle the load.

**Comment by sudsy** [comment]
Thanks,

Our real workload is cpu intensive so I created some other tests
calculating primes as a proxy.

I guess because the cpu doesn't yield, these 100 items are essentially
processed serially.

I have tried triggering the jobs with storage quues and http triggers and
while the results were better, the performance is still very poor.

I know this issue is not the place to discuss it so if you want to redirect
me to somewhere more appropriate to share my results, I can do so.

**Comment by davidebbo** [comment]
@sudsy it turns out there is another issue that you were likely running into when you were testing with Thread.Sleep(). See #548 for details.

**Comment by brettsam** [comment]
Assigning to @fabiocav since he already owns #548.

**Comment by fabiocav** [comment]
@sudsy this should be fixed. Please let us know if you continue to run into issues.

**Comment by sudsy** [comment]
Cheers. It might be a little while before I can work on this again but will
do.

**Comment by mathewc** [comment]
@sudsy FYI it's fixed in our 0.6 release which will be rolling out this week.
