### ISSUE TITLE
Suggestion: Environment provider abstraction

### ISSUE THREAD

**Issue by suwatch** [Azure/azure-webjobs-sdk-script#531]
It would be good to have Environment provider abstraction.
  - This is good for mocking and testing.   No need to munch with Environment.SetEnvironment() where it could be issue if left over.
  - It is also a point where we could decide to cache or reset the cache if env is dynamically changed (think standby mode in Azure and environment injection).

**Comment by mathewc** [comment]
Tracked by https://github.com/Azure/azure-webjobs-sdk-script/issues/677
