### ISSUE TITLE
Support certificates in dynamic app service

### ISSUE THREAD

**Issue by theMichaelB** [Azure/azure-webjobs-sdk-script#538]
It is not currently possible (unless I'm doing it wrong!) to use a certificate in Functions unless you use an App Service VM. 

It would be useful to have a comparison table of what is / isn't possible with a dynamic plan (unless I've just not found it yet!)

**Comment by christopheranderson** [comment]
I'll look into whether we support this/can support this. 

Good feedback on comparison table.

**Comment by christopheranderson** [comment]
@theMichaelB - I just found out that we'll be enabling this in a deployment this month. Stay tuned.

**Comment by christopheranderson** [comment]
SSL certs are now supported, but client certificates are not yet supported.

**Comment by fashaikh** [comment]
👍  Need this... Loading cert from the file system for now.

**Comment by Pankaj-Patro** [comment]
Any idea when this will be supported. Its been a year now.

**Comment by paulbatum** [comment]
@Pankaj-Patro Its supported now. Looks like we forgot to close this issue.

**Comment by joeythomaschaske** [comment]
Any documentation on how to use this? I've been searching but no dice.

**Comment by paulbatum** [comment]
@joeythomaschaske try this (same should work for functions):
https://docs.microsoft.com/en-us/azure/app-service/app-service-web-ssl-cert-load

**Comment by joeythomaschaske** [comment]
@paulbatum 

I logged an issue with the documentation for that article. There should be examples for each language azure functions supports. I'm unable to find any documentation on how to use them for node.js

My current solution is keeping the certificates in a separate folder I read from in my function and attach them to the http agent.

**Comment by paulbatum** [comment]
I agree with you samples would help. However I don't think there is anything specific here for functions. If you can find working instructions for how to load certificates from the windows cert store in nodejs, it should work in functions.

**Comment by paulbatum** [comment]
Maybe this npm package can help? 
https://www.npmjs.com/package/win-ca
