### ISSUE TITLE
Expose ExecutionId through context object

### ISSUE THREAD

**Issue by akurmi** [Azure/azure-webjobs-sdk-script#539]
I couldn't find executionId (that can be used for identifying a specific log entry in 'AzureFunctionsLogTable' table) in Node context object:
https://azure.microsoft.com/en-us/documentation/articles/functions-reference-node/#context-object 

Exposing executionId would allow customers to correlate output items/their custom logs with the logs in 'AzureFunctionsLogTable'.

**Comment by christopheranderson** [comment]
It is exposed but not documented right now:

```
 "bindingData": {
  ...
  "InvocationId": "17437a87-6bea-43e9-ae6a-c4bc1869f99b"
 }
```

**Comment by mathewc** [comment]
Correct. Related issue here: https://github.com/Azure/azure-webjobs-sdk-script/issues/504
