### ISSUE TITLE
Leverage core SDK Singleton for BlobLease management

### ISSUE THREAD

**Issue by mathewc** [Azure/azure-webjobs-sdk-script#540]
We have some custom blob lease logic added to get singleton behavior for log writing, etc. We should leverage the existing (currently internal) APIs in the WebJobs SDK to do this, since that code has been around for a while and is well tested. https://github.com/Azure/azure-webjobs-sdk/blob/master/src/Microsoft.Azure.WebJobs.Host/Singleton/SingletonManager.cs

**Comment by fabiocav** [comment]
Spent some time investigating this yesterday and it would require more changes than initially anticipated. We'll postpone this work and keep the current implementation in the script host.
