### ISSUE TITLE
Function with Thread.Sleep call gets serialized execution behavior

### ISSUE THREAD

**Issue by davidebbo** [Azure/azure-webjobs-sdk-script#548]
Create a queue triggered function with this code:

```
using System;

public static void Run(string myQueueItem, TraceWriter log)
{
    log.Info($"C# Queue trigger function processed: {myQueueItem}");
    System.Threading.Thread.Sleep(5000);
    log.Info($"Done");
}
```

Then add 10 items to the queue.

Result: they get processed sequentially, taking 50 seconds to complete.

**Comment by davidebbo** [comment]
One very odd thing is that if you add an output queue param, it no longer repros. e.g. out the output binding and change the code to:

```
using System;

public static void Run(string myQueueItem, out string outputQueueItem, TraceWriter log)
{
    log.Info($"C# Queue trigger function processed: {myQueueItem}");
    System.Threading.Thread.Sleep(5000);
    log.Info($"Done");
    
    outputQueueItem = $"'{myQueueItem}' Processed at {DateTime.Now}";
}
```

Result: all queue items get processed concurrently.

Also, using an async Sleep allows concurrency (even without the out param).

**Comment by mathewc** [comment]
I tried to repro outside of Functions in core SDK and it does not repro there. I believe the issue may be related to our [Task handling in the function generator])https://github.com/Azure/azure-webjobs-sdk-script/blob/dev/src/WebJobs.Script/Description/FunctionGenerator.cs#L123).

**Comment by fabiocav** [comment]
Since this function is synchronous anyway, awaiting the invoker's result would still block this thread. How does the SDK schedule its work and manage concurrency?

**Comment by fabiocav** [comment]
@davidebbo this has been fixed with a change in the core SDK.
