### ISSUE TITLE
Function host is not running.

### ISSUE THREAD

**Issue by samuelkilada** [Azure/azure-webjobs-sdk-script#551]
Hello,

First I wanted to say thank you for the work you are putting into this sdk. The documentation is a bit sparse, but it is in beta.

Regarding that, should I be trying to use this on my site or is it too early? When is the official release candidate expected? I followed all of the steps for Option 1 (HTTP Function/WebHook support) using the latest beta version and my site will no longer load. I just get:

Function host is not running.

If I remove the Functions site extension from the folder the site will load. This is an Azure Website (or Web App) on nodeJs. I really need this because I need asynchronous, on-demand tasks that I can execute when needed. I have an existing web job that runs continually doing tasks from a queue, but that's not enough because I also need the capability to call these functions that can return a callback to main server on user requests.

It would seem that the error suggests that the extension is indeed loading, but it's not able to find the host. I put the host.json file in my main project root (which ends up at wwwroot when I do a git push). I also put the sample httpTrigger folder in the project root.

Thanks!

**Comment by mathewc** [comment]
Hmmm, that error indicates that the site extension is loading, but a host startup error has occurred. Can you check for error logs under D:\home\LogFiles\Application\Functions? That should tell us where things are going wrong.

**Comment by samuelkilada** [comment]
Oh, that's interesting. Do you mean then that you would create a new web app using functions entirely separate from your main site and access it via the web trigger or other triggers? To use it on the same site, should I do option 2 from the install instructions to install it as a web job in the project directory?

I checked the logs but I've not seen anything useful at that folder except index.html, which contains nothing helpful.

**Comment by samuelkilada** [comment]
I tried adding it by following option 2 and I believe it is running. However, I can't test it because there's no documentation anywhere on manual triggers and I need a manual trigger so I can invoke a function and get a callback on the main server (queue trigger won't work for this). Any pointers (unless I'm totally going down the wrong path)?

**Comment by mathewc** [comment]
Yes, for http support Functions needs to own the site entirely. Option 2 is a standard Continuous WebJobs approach. I put a sample together for that [here](https://github.com/Azure/azure-webjobs-sdk-script-samples/tree/master/WebJobScript).

Can you please provide more details on your scenario and exactly what you're trying to accomplish?

**Comment by samuelkilada** [comment]
Thanks for the sample link, I'll have to check it out. Basically, I am working on a new web app and when doing some loading testing concluded that I needed to move things to an external process, even though they are being done asyncronously. Rather than simply launching child processes in node, I thought I'd look into what on demand web jobs can do, and found this library. But I can't just use queues. I need the server to call a web job and then return a callback so it can return a response to a user's request. The httptrigger api made sense for this, but since I can't use that without creating a separate app I need to use what will work for my use case, and based on the name manual trigger sounds like it will work. But I haven't found any example of a manual trigger (including in your sample, though it does look helpful). Hope that makes sense.

All I want is to be able to move tasks to an external place outside the main server process to keep it from blocking on cpu intensive stuff, and to be able to scale well, which is why web jobs sound like the best option. But the catch is need communication with the web job and a callback when the task is complete!

**Comment by samuelkilada** [comment]
I'm getting nowhere fast...I noticed that functions is available within the Azure portal so I decided to go that route. I create a new web app and can use the web api just fine now. However, there are some issues that are not explained anywhere. For example, I want to stream a file to a function so it can first resize the file, then upload it to blob storage, then send back a response. However, I cannot pipe the file from the req because req.pipe and req.on are not functions, probably because req is not a regular request object in Azure functions. Is streaming data impossible then? Thanks.

**Comment by mathewc** [comment]
You are correct - there is no streaming currently. The req object in our Node programming model is currently data only. We have open issues tracking improvements in this area, but this is the current state of things. So for large payloads, you might consider a design where the data is instead written to blob storage and the request contains only a pointer to the blob to be processed. I.e. your web app could upload the original image to blob, send a pointer to the image to be resized to the function, and the function resizes it.

**Comment by samuelkilada** [comment]
Thanks Mathew, I think that's what I'm going to do. I'll go ahead and close this issue because the original error was a result of me trying to combine a function app with my existing app. "Option 1" seems to only work when you have an app that is dedicated to functions.
