### ISSUE TITLE
Default setting writes too much to disk, causing major perf degradation

### ISSUE THREAD

**Issue by davidebbo** [Azure/azure-webjobs-sdk-script#557]
@christopheranderson was running a large scale test, and we found that most of the time was being spent writing log files to the slow Azure Files drive. After we turned that off via host.config, the throughput shot through the roof.

So clearly, we need to reduce the logging. Maybe setting the default to Warning would go a long way. Though of course it would affect the developer experience, so we need to do it in a smart way.

**Comment by mathewc** [comment]
Possibly related to https://github.com/Azure/azure-webjobs-sdk-script/issues/100. The idea there was to use optimal settings outside of portal debug sessions.
