### ISSUE TITLE
Not picking up the new CRON and running on previous schedule only. Even disable cannot stop it from running.

### ISSUE THREAD

**Issue by rohitk710** [Azure/azure-webjobs-sdk-script#558]
I accidentally set my code to run every 15 seconds. Now, no matter what CRON expression I am giving it is not updating only. Even Disable feature in **Manage** tab of the azure function is not making it stop. The only way I am able to stop it is deleting the **TimerInfo** parameter or deleting the Timer parameter from **Integrate** tab. In that case the compilation starts failing and the code stops. What is the expected behavior here? Shouldn't the disable button stop the function execution. And what is the ETA for it to pick the new Schedule provided to it by CRON expression?

**Comment by mathewc** [comment]
That definitely should not be happening - a schedule change once saved should take effect immediately. Do you have a consistent repro for this? Are you saying that after forcing the function to recompile, the new schedule was then used?

**Comment by rohitk710** [comment]
An update. I did nothing different today morning. Not even a single change i made. All i did was instead of using App Service Editor i used the normal function console provided on azure portal and it worked.

Though it worked here are what were some issues I saw :
1. Even if i was giving a wrong CRON expression shouldn't the execution stop? Because it continuously ran for two days.
2. Also, about the disable button on the portal. I have an azure function to send mail. I clicked on disable since i was not able to fix the schedule issue but then after a couple of day i could see some 53K mails in my folder. Isn't the disable function supposed to function from execution?

**Comment by mathewc** [comment]
What do you mean specifically by "App Service Editor"?

The function execution should always be in sync with your CRON schedule. If your schedule is invalid, the function should not be running.

Regarding the disable button: yes, it should immediately disable the function. I tried this myself just now and it works for my TimerTrigger - the timer stops immediately. The way this works is we write a `"disabled": true` value to the function.json metadata file for your function, and that causes a host restart. The host will then skip that disabled function.

**Comment by brettsam** [comment]
@mathewc  -- "App Service Editor" is Monaco.
I've been playing with this in the editor this morning and not been able to reproduce the problem. It seems like we somehow missed the updates to the function.json file -- I'm going to see if I can figure out if that's true (and why it happened).

**Comment by brettsam** [comment]
https://github.com/Azure/azure-webjobs-sdk-extensions/issues/149 has been checked in and the new nuget is now in Script (#684). It's not yet in production, but I believe the issue here is the same.
