### ISSUE TITLE
Create a heartbeat for long running functions (similar to IMetricsLogger.BeginEvent() and IMetricsLogger.EndEvent())

### ISSUE THREAD

**Issue by akurmi** [Azure/azure-webjobs-sdk-script#561]

**Comment by mathewc** [comment]
The core SDK already does some of this so the Dashboard can track function/host activity. See https://github.com/Azure/azure-webjobs-sdk/blob/master/src/Microsoft.Azure.WebJobs.Host/Executors/HeartbeatFunctionExecutor.cs. However, that info is tracked in blob storage.

**Comment by christopheranderson** [comment]
Same story as the other bug like this. Closed unless we find that the bug reoccurs.
