### ISSUE TITLE
Fuction App (Service Bus Topic Trigger) - fails to deserialize with ContentType is "application/json"

### ISSUE THREAD

**Issue by rababued** [Azure/azure-webjobs-sdk-script#567]
when posting a BrokeredMessage to a Servicebus Topic with ContentType = "application/json"
var message = new BrokeredMessage(JsonConvert.SerializeObject(model))
{
    ContentType = "application/json"
};

...I am seeing this exception in the log
Microsoft.Azure.WebJobs.Host: Exception binding parameter 'mySbMsg'. mscorlib: **Unable to translate bytes [98] at index 61 from specified code page to Unicode.**

**Comment by brettsam** [comment]
I see we have a test that uses a `MemoryStream` rather than a `string` to create the message. I tried that and it worked:

    var value = JsonConvert.SerializeObject(model);
    MemoryStream ms = new MemoryStream();
    StreamWriter sw = new StreamWriter(ms);
    sw.Write(value);
    sw.Flush();
    ms.Seek(0, SeekOrigin.Begin);
    var message = new BrokeredMessage(ms)
    {
        ContentType = "application/json"
    };

@MikeStall / @mathewc -- I tried fiddling around with passing an actual JSON string in but it never seemed to work when we deserialized. Do you know if there's a way for that to work, or is the above the best approach?

**Comment by brettsam** [comment]
Actually, I just tried to pass my model in directly without serializing first and that seemed to work. My model looked like:

        [DataContract]
        public class MyModel
        {
            public string Text { get; set; }
        }

I think this may ultimately be a SB behavior scenario. @rababued please feel free to re-open if you think there's a bigger issue here or these solutions don't work for you.

**Comment by mathewc** [comment]
Yeah, all of our samples historically have used the Stream approach, e.g. [here](https://github.com/Azure/azure-webjobs-sdk-samples/blob/master/BasicSamples/ServiceBus/Program.cs#L48). That allows SB to do its proper encoding.
