### ISSUE TITLE
Multiple Functions with EventHub triggers not using their consumer groups

### ISSUE THREAD

**Issue by danbueno20** [Azure/azure-webjobs-sdk-script#570]
I have three, eventhub-triggered functions that are configured to use separate consumer groups.  If all three are active, only one function gets executed per event.  In the storage blob where the leases are kept, I only see one of the consumer groups.  I disabled the function that uses that group.  I added another event and a different function handled the event.  The files with leases for the incorrect consumer group were updated.

**Comment by christopheranderson** [comment]
@christopheranderson - will attempt to repro this so we can debug it

**Comment by danbueno20** [comment]
Tried this again with all new resources and it still fails to execute both functions.  Is there anything else I can do to help identify/work through this issue?

**Comment by MikeStall** [comment]
@danbueno20  - how are you specifying the consumer groups? I'm trying to piece together a basic repro for this.

**Comment by danbueno20** [comment]
The configuration looks like this:

`{
    "bindings": [ {
        "type": "eventHubTrigger",
        "name": "eventMessage",
        "direction": "in",
        "path": "eventHubPath",
        "connection": "ConnectionName",
        "consumerGroup": "consumergroupone"
    } ],
    "disabled": false
}`

The second function is the same, but with a different consumer group name.  The leases in the storage account blob is where I'm verifying that only one consumer group is being used.

**Comment by MikeStall** [comment]
Thanks - I can see it.
