### ISSUE TITLE
Using Nuget packages in scripts newer than those used by the host can cause issues

### ISSUE THREAD

**Issue by brettsam** [Azure/azure-webjobs-sdk-script#573]
Background: We build with DocDB 1.7.1, while 1.9.2 is the newest release. We have a BindingRedirect to 1.7.0.

Scenario: In my script, I add a package.json that uses 1.9.2 and specify a DocumentClient as a parameter. That parameter is passed to me as null. Only changing my package.json to 1.7.1 can get it to work.

This uses an ExactType binding -- so it looks like the script is asking for DocumentClient 1.9.0, which does not match the compiled type 1.7.0, so it doesn't match things up correctly. It's very hard to tell that's the problem. 

Note: using a lower version in the package.json (like 1.6.3) works fine -- the BindingRedirect takes care of that.

**Comment by mathewc** [comment]
Do you have a proposed fix?

**Comment by brettsam** [comment]
Just some brainstorming. @fabiocav probably has some ideas as well --

1. Throw a descriptive error if we detect a reference higher than we have a BindingRedirect for?
2. Can we hook into AssemblyResolve and do our own redirection?

**Comment by brettsam** [comment]
@fabiocav -- this just came up again today. Not sure if we have a valid solution, but you can end up with really confusing errors if you pull a newer version of an assembly than we use.

**Comment by cliffyq** [comment]
any updates on this one?

**Comment by brettsam** [comment]
We've been discussing this a lot lately as precompiled functions hit this quite often. We'll use this issue to track the fix.

There's not a great solution to make things 'just work' if you move a nuget package ahead of what the host expects*, but we should be able to emit a better error when this happens. We have enough metadata about the binding and the loaded types to detect a version mismatch.

\* For example, if we redirect you back to our older referenced version, it *may* work, but you also may be depending on a new API or a bug fix in the newer version, leading to more confusing errors.

**Comment by tomkerkhove** [comment]
This is actually blocking us from migrating..

**Comment by brettsam** [comment]
I'm going to close this as a duplicate since there's a larger, more encompassing issue that we're using to track (see the discussion there as well): #992.
I want to make sure that we capture everyone's input and don't have them spread throughout multiple issues.
