### ISSUE TITLE
PS Based functions add a new line to output!

### ISSUE THREAD

**Issue by mathewc** [Azure/azure-webjobs-sdk-script#574]
I have this function:

$requestBody = Get-Content $req -Raw | ConvertFrom-Json

#If a validation token is present, we need to respond within 5 seconds.
if ($req_query_validationToken -ne $null)
{
    Out-File -Encoding Ascii $res -inputObject $req_query_validationToken
}
    

It has to return the validationToken back to Microsoft Graph API when it gets a query that contains "validationToken", such as:

$res = Invoke-WebRequest -Uri "https://graphhelper.azurewebsites.net/api/PSwebhooks?code=xxxxx6w9fxhx6k5986m9yq6s8fi94opzxxx&validationToken=ZTI0MzNkMGQtZDNiOS00MWY3LWI1ZTktMzc1Y2JiNDNkYmNl" -Method Post

but it Microsoft Graph API does not accept the response.

From testing in PowerShell. it seems that the output has been added a "new line":

StatusCode        : 200
StatusDescription : OK
Content           : ZTI0MzNkMGQtZDNiOS00MWY3LWI1ZTktMzc1Y2JiNDNkYmNl
                    
RawContent        : HTTP/1.1 200 OK
                    Pragma: no-cache
                    Content-Length: 50
                    Cache-Control: no-cache
                    Content-Type: text/plain; charset=utf-8
                    Date: Fri, 12 Aug 2016 13:41:44 GMT
                    Expires: -1

I think this is the issue for my current usecase.

Can it be changed to not add this new line ? (if I am right)

Thanks for a great service!

**Comment by mathewc** [comment]
Original issue here: https://github.com/Azure/azure-webjobs-sdk-templates/issues/285

**Comment by JakobGSvendsen** [comment]
Hey! thanks for moving to correct forum.

actually I discovered that it is Out-File who adds a new line. In PS5.0 there is a new -nonewline paramters, but the functions are running PS4.0.

In PS4.0 I did this workaround:
[io.file]::WriteAllText($res,"test")

**Comment by mathewc** [comment]
Looks like your workaround got truncated. Can you please share?

@tohling What do we have to do to move to PS 5.0?

**Comment by JakobGSvendsen** [comment]
oh it did.

    [io.file]::WriteAllText($res, $req_query_validationToken)

**Comment by mathewc** [comment]
Closing this for now since there is nothing we can do in this runtime to address this. Currently the VMs running Functions have PS 4.0 installed. Until that is upgraded (those discussions are happening - it will happen eventually :)), we're on 4.0.
