### ISSUE TITLE
How to rename a function?

### ISSUE THREAD

**Issue by alaatm** [Azure/azure-webjobs-sdk-script#583]
I let the portal create a function for me and it defaulted to `TriggerCSharp1` How do I rename this?

**Comment by fabiocav** [comment]
@alaatm currently, there's no portal support for rename, but you can do so by renaming the folder containing your function in Kudu.
To open Kudu, go to https://<functionappname>.scm.azurewebsites.net , click on **Debug Console** > **CMD** and go to site\wwwroot, where you'll see your function folders. Renaming those folders will change your function names.

**Comment by alaatm** [comment]
After changing the folder name, I now get 404 Not Found when posting to new URL. Any clue how to fix that?

**Comment by alaatm** [comment]
A restart seem to have solved the issue

**Comment by mathewc** [comment]
Note that while you might be able to get things to work by renaming yourself manually, it's currently not a supported feature, so you may run into issues (e.g. like having to restart).

We have a work item https://github.com/projectkudu/AzureFunctionsPortal/issues/198 addressing this.
