### ISSUE TITLE
How to customize URL?

### ISSUE THREAD

**Issue by alaatm** [Azure/azure-webjobs-sdk-script#584]
Can we customize the function URL? for example, the default is:

`https://<app-name>.azurewebsites.net/api/<function-name>?code=123`

I assigned a custom domain name for this app as follows:
`https://api.<app-name>.com`

How can I make the url as follows
`https://api.<app-name>.com/<function-name>?code=123`

instead of
`https://api.<app-name>.com/api/<function-name>?code=123`

**Comment by christopheranderson** [comment]
This is coming with an upcoming feature. You can see this PR for details - https://github.com/Azure/azure-webjobs-sdk-script/pull/490
