### ISSUE TITLE
updating multiple DocumentDB documents from azure function

### ISSUE THREAD

**Issue by bman654** [Azure/azure-webjobs-sdk-script#585]
Hi,

It looks like the current DocumentDB binding is optimized for receiving a single document as input and updating or creating a single document as output.

I'm wanting to write an azure function that is triggered via HTTP and then creates/updates multiple documents and am not sure how to get access to the DocumentDB connection.

In C#, I think I can declare a `DocumentClient` parameter and then create my documents that way?

But what about in nodeJS?  Is there a way to get access to the client in NodeJS?  Or do I just need to connect to the DB myself from within my nodeJS function?

**Comment by mathewc** [comment]
Yes, in C# you can bind to the `DocumentClient`. However, you can also accomplish what you're asking for by binding do `IAsyncCollector<JObject>` or `ICollector<JObject>`. Then in your function you call the `AddAsync`/`Add` method to add documents.

In Node, you don't have access to the `DocumentClient`, but you should be able to assign an array of documents to your output binding and that should work.

@brettsam Can clarify and add more details if necessary.

**Comment by bman654** [comment]
Thanks I'll try the array method.  I've tried to find the source for the nodeJS DocumentDB binding but only found C# source.  If you could point me to the JS bindings, I can probably answer these questions myself :stuck_out_tongue:

**Comment by mathewc** [comment]
The underlying extensions for all this stuff live in this repo: https://github.com/Azure/azure-webjobs-sdk-extensions. That wiki page gives some examples of what DocumentDB and the other bindings support, as does the samples project, e.g. https://github.com/Azure/azure-webjobs-sdk-extensions/blob/master/src/ExtensionsSample/Samples/DocumentDBSamples.cs. I just looked and unfortunately those samples/doc don't show any IAsyncCollector examples :( We'll fix that.

As far as Node documentation, you're right that we're behind on all that. We've got some issues logged to address this, e.g. https://github.com/Azure/azure-webjobs-sdk-script/issues/438.

**Comment by mathewc** [comment]
Closing this since I believe your scenario is supported already. Please reopen if you find issues, thanks.

**Comment by jbrozena22** [comment]
@mathewc can you elaborate on this:

> In Node, you don't have access to the DocumentClient, but you should be able to assign an array of documents to your output binding and that should work.

I can't find an example in node that shows how you can bind to multiple database items from an azure function. For instance, if a client sent an array of document IDs, I'd like to bind to each of those documents so I can return each of their results. 

Thanks.
