### ISSUE TITLE
HttpTrigger & DocumentDB Binding Input not recognizing GET parameter, Azure Function

### ISSUE THREAD

**Issue by dustensalinas** [Azure/azure-webjobs-sdk-script#587]
Azure Function
Upon retrieval of single document on a node based trigger, unable to retrieve document via a GET request.  Post works fine.

Binding:
{
  "bindings": [
    {
      "authLevel": "anonymous",
      "type": "httpTrigger",
      "direction": "in",
      "name": "req",
      "methods": [
        "get",
        "post"
      ]
    },
    {
      "type": "http",
      "direction": "out",
      "name": "res"
    },
    {
      "type": "documentDB",
      "name": "inputDocument",
      "databaseName": "<...>",
      "collectionName": "<...>",
      "connection": "<...>",
      "id": "{documentId}",
      "direction": "in"
    }
  ],
  "disabled": false
}

POST
{
"documentId": "testid"
}
2016-08-17T16:48:29.878 Function completed (Success, Id=3b9bb3c0-dff5-425c-aee2-6b6c0511828e)

GET : /api/HttpTriggerNodeJS2?documentId=testid
2016-08-17T16:46:27.886 Exception while executing function: Functions.HttpTriggerNodeJS2. Microsoft.Azure.WebJobs.Host: No value for named parameter 'documentId'

**Comment by mathewc** [comment]
Support for pulling binding data from the query string was only just added recently. It's sitting in our dev branch and will go out with our next release :) See https://github.com/Azure/azure-webjobs-sdk-script/issues/334 and its associated commit for details.
