### ISSUE TITLE
Partition Key is not case insensitive (Node)

### ISSUE THREAD

**Issue by christopheranderson** [Azure/azure-webjobs-sdk-script#588]
If the table item has "PartitionKey" as a property, we get a weird error about a blank partition key. The error goes away if I change it to "partitionKey". There is no reason for us to be case sensitive here, I believe. Even if we need to be, the error needs to nice about it.

I think the issue is here in the code - we don't consider case when removing the ParititionKey from the entity - https://github.com/Azure/azure-webjobs-sdk-script/blob/dev/src/WebJobs.Script/Binding/TableBinding.cs#L238

**Comment by mathewc** [comment]
Can you provide a repro please?

**Comment by christopheranderson** [comment]
This fails:
```
module.exports = function(context, input) {
    context.bindings.output = {
       "PartitionKey": "foo",
       "RowKey":"bar"
    }
}
```

This works:
```
module.exports = function(context, input) {
    context.bindings.output = {
       "partitionKey": "foo",
       "rowKey":"bar"
    }
}
```
