### ISSUE TITLE
C# TextWriter Log needs to be written to Streaming Logs

### ISSUE THREAD

**Issue by christopheranderson** [Azure/azure-webjobs-sdk-script#59]
## Issue

When using .csx, we can bind a `TextWriter log` and make calls like `log.Verbose("Foobar")` and the streaming log does not write the records to the console.

## Expected behavior

It should write the logs to the streaming logs (i.e. "Verbose: Foobar"), as does the Node experience.

## Mitigation attempted

I attempted to add the following to host.json, but it did not address the issue:

```JSON
    "tracing": {
      "consoleLevel": "Verbose"
    }
```

**Comment by mathewc** [comment]
There is a special file TraceWriter that the other script invokers log to, that writes to files, which are then directed to streaming logs. What needs to happen is the trace writer passed in to the user method needs to be wrapped with a trace writer that also writes to files, similar to the way NodeFunctionInvoker implements log on the script context.
