### ISSUE TITLE
Allow binding to HTTP headers

### ISSUE THREAD

**Issue by brettsam** [Azure/azure-webjobs-sdk-script#591]
Can we expand binding to headers as well as the body and query string? Example -- someone has a third party library that sends requests with an id in the header. It'd be nice if they can bind to that directly --  http://stackoverflow.com/questions/39036629/for-azure-documentdb-input-binding-is-there-a-way-to-get-the-document-id-from-t

**Comment by mathewc** [comment]
Perhaps. As part of merging in the http routing work, we'll also be expanding binding data to include route parameters, so we'll be doing more work in this area :)

**Comment by mathewc** [comment]
Closing this, since I don't think we should allow binding to headers. If we get customer asks for this, we can revisit.

**Comment by brettsam** [comment]
Can you explain why we shouldn't do this? This issue was created due to a customer ask, which seemed like a pretty reasonable scenario, so it'd be good to capture the reasons to close it.

**Comment by mathewc** [comment]
Sorry, I missed the SO link above.  Unlike the route and query parameters, the headers collection can contain a lot of superfluous stuff that I don't think want to dump into the binding data bag.

I'll open this back up and assign back to triage so we can discuss further.
