### ISSUE TITLE
Powershell: Write-Host throws an error

### ISSUE THREAD

**Issue by brettsam** [Azure/azure-webjobs-sdk-script#592]
If I do this: `Write-Host "hello"`, I get this error:

`Write-Host : A command that prompts the user failed because the host program or the command type does not support user interaction. Try a host program that supports user interaction, such as the Windows PowerShell Console or Windows PowerShell ISE, and remove prompt-related commands from command types that do not support user interaction, such as Windows PowerShell workflows.
at run.ps1: line 1`

**Comment by mathewc** [comment]
I assume you're trying to write some debug output to logs, not to an output binding? @tohling what is the right way to do that?

**Comment by brettsam** [comment]
Correct -- just trying to write out to the logs. I can get around it by just using a string by itself `"hello"` but thought others may be using `Write-Host`, especially if they're trying to re-use existing scripts.

**Comment by mathewc** [comment]
You mean to write a console entry, you just put a string "hello" on a single line?

**Comment by brettsam** [comment]
Yeah -- here's my script that logs:
```
for($i=1; $i -le 10; $i++)
{
    "powershell running " + $i
    Start-Sleep -s 1
}
```

**Comment by mathewc** [comment]
Probably by design, but we'll let Ling confirm

**Comment by tohling** [comment]
Yes, you will not be able to use Write-Host as Functions operate in a multi-tenant environment and PowerShell commands will not be able to interact directly with the host.  Use Write-Output instead.

**Comment by christopheranderson** [comment]
Close by design

**Comment by johnnliu** [comment]
Why do I find this AFTER I spend 2 hours bashing my head :'(  
Let's put that in the documentation.

![image](https://cloud.githubusercontent.com/assets/1279372/19759388/81f62cb8-9c78-11e6-81c3-946fdeea2911.png)

**Comment by tohling** [comment]
@johnnliu, yes we will provide a more comprehensive set of documentation soon.  Thank you for your patience.
