### ISSUE TITLE
CLI: reduce the number of tips in some cases

### ISSUE THREAD

**Issue by davidebbo** [Azure/azure-webjobs-sdk-script#594]
Every time I run my function, I get:

```
D:\tmp\NewFuncAppLocal>func run MyCsHttp
Response Status Code: OK
"Hello!"
Tip: run func list functionapps to list function apps in your azure subscription.
Tip: run func list storageaccounts to list storage accounts in your azure subscription.
Tip: run func list secrets to list secrets locally on your machine.
```

The 3 tips can quickly get old. :) I'd argue that the run command should not give tips for any additional commands.

**Comment by mathewc** [comment]
Tip: don't write so many tips :)

**Comment by ahmelsayed** [comment]
Actually it only displays the tips for a given command 5? Times in 3 hours? 

I have everything in place for it to track commands history and display smart tips, they are just not very smart right now. 

Also it can query f.a.c for updates to the tips. I was imagining the blu displaying updates like **new: now F# is supported**

**Comment by davidebbo** [comment]
Sure enough, after doing it 5 times, it goes away...
