### ISSUE TITLE
Promise.resolve().then() not working

### ISSUE THREAD

**Issue by bierdybard** [Azure/azure-webjobs-sdk-script#596]
Functions ~0.4
Node 5.9.1

Hello,

`then()` on immediately resolved Promises (ES6-native) does not seem to be working. For example:

    function getTicket(ticketNumber) {
        if(cache[ticketNumber] !== undefined) {
            return Promise.resolve(cache[ticketNumber]);
        } else {
            return new Promise((resolve, reject) => {
                 // stuff here that validly resolves the Promise
            });
        }
    }

    getTicket(1234).then((ticket) => {
        // do stuff here
    });

If the ticket does not yet exist in the cache, a Promise is returned and resolved at a later time. This works correctly and the `then()` method is called. However, if the ticket does exist in the cache, an immediately resolved Promise is returned with the cached value; `then()` never fires in Azure Functions. This can be tested with something as simple as `Promise.resolve('test').then(val => { context.log(val); });`. The expected behavior is that 'test' is logged; however this never happens.

In order to narrow out a Node.js version error I tried this on a clean Node.js 5.9.1 install locally, and it worked as expected.

**Comment by christopheranderson** [comment]
Brett, could you look into this. Might be related to nextTick?

**Comment by mathewc** [comment]
@mamaso This is fixed now, right?

**Comment by mamaso** [comment]
yep
