### ISSUE TITLE
Not possible to create dynamic function in existing resource group via portal

### ISSUE THREAD

**Issue by theMichaelB** [Azure/azure-webjobs-sdk-script#597]
I realise this might not be the responsibility of this team, but you're likely closer to the people who are at the very least. 

If you try to create a new Functions app via the Portal, once you select the existing resource group drop down the dynamic / classic 'App Service Plan' dropdown disappears to be replaced with a standard 'New App Service Plan' blade.

**Comment by christopheranderson** [comment]
Thanks for reporting! :)

This is a known issue and we're tracking it on our portal repo: https://github.com/projectkudu/AzureFunctionsPortal/issues/256

Should be solved soonish. We're waiting on the updates to our API to deploy, then we'll update portal.

Closing this as a duplicate.
