### ISSUE TITLE
Need to finish the F# Samples

### ISSUE THREAD

**Issue by mathewc** [Azure/azure-webjobs-sdk-script#601]
I fixed the samples as a follow up to get them compiling (see https://github.com/Azure/azure-webjobs-sdk-script/commit/6c1f57463c97b6a5b6e41d10ae100d570ad5dc02) so the Sample app could successfully load. 

However, it remains to test each of them one by one to make sure they actually work, since we'll be pointing users to these as examples. I know some of them appear broken, and one I had to mark "excluded" because it doesn't compile.

**Comment by fabiocav** [comment]
Interesting. With what I'm seeing, I'm actually wondering if there was a merge issue. I'll review those tomorrow.

**Comment by mathewc** [comment]
Yeah, a bunch of the json files were way out of date, using wrong trigger names, etc. They would have only compiled months ago, which lead me to believe the samples haven't actually been run.

**Comment by fabiocav** [comment]
Odd. I'm pretty sure those were updated at some point, so I'm suspecting something got lost in the process. I'll review those today.

**Comment by lindydonna** [comment]
CC @sylvanc and @dsyme

**Comment by dsyme** [comment]
@fabiocav I think @sylvanc has updated these samples in October?

**Comment by fabiocav** [comment]
I think @sylvanc worked on the templates (which are definitely more important). The samples this issue is referring to are these: https://github.com/Azure/azure-webjobs-sdk-script/tree/dev/sample

**Comment by dsyme** [comment]
OK. The missing ones for F# appear to be

* [ ] Bot-FSharp
* [ ] HttpTrigger-FSharp-CustomRoute	
* [ ] HttpTrigger-FSharp-Poco
* [ ] ManualTrigger-FSharp
* [ ] SendGrid-FSharp

So we're around 80% done :) Thanks

**Comment by mathewc** [comment]
I'd rather not add an F# sample for each of these - our samples are already pretty unmanageable at this point. That sample project wasn't meant to be exhaustive - it's meant to be a showcase/playground - something that is easily runnable to play with the product. Note that to keep startup times down so the sample app is actually usable, I marked the FSharp samples as "excluded" in their function.json files.

I created this issue a while ago because when I looked initially many didn't compile/run. So this issue is really about **just going through the samples and making sure they look as they should and run correctly**.

**Comment by dsyme** [comment]
@mathewc OK, thanks

>  Note that to keep startup times down so the sample app is actually usable, I marked the FSharp samples as "excluded" in their function.json files.

It's possible we don't even need the F# samples in the sample app since the F# documentation on the website is quite good.  How prominent is the sample app on the learning paths?  We want to make F# people get to a good collection of F# samples - but perhaps it doesn't need to be in this repo?  Instead we could put the F# samples in http://github.com/fsprojects as an F# community project and link to it on the learning paths?  That way the F# community could contribute to and maintain the samples?

**Comment by mathewc** [comment]
The samples aren't really part of any official documentation/learning resources, It's just something that us devs do. E.g. an easy way to fire up some functions locally and debug through / demo. So we generally have good coverage of all features, but not exhaustive.
