### ISSUE TITLE
ManualTrigger input binding data doesn't work with Scripts (Batch, Bash, etc)

### ISSUE THREAD

**Issue by brettsam** [Azure/azure-webjobs-sdk-script#602]
I couldn't figure out a way to get data from a manual trigger into any of my script tests. The BindingData appears to be there, but I suspect that because there's no input binding discovered, none of the other actions are taken to pass the data to the script.

**Comment by mathewc** [comment]
Can you give me an example of what doesn't work? I'll look into it today.

**Comment by brettsam** [comment]
In the portal, set up a Windows Batch function with a Manual Trigger named 'input'. Then try this:

```
SET /p input=<%input%
echo %input%
```

If you invoke via the 'Run' button on the portal with some data, you'll get `Exception while executing function: Functions.EmptyBatch1. Microsoft.Azure.WebJobs.Script: The syntax of the command is incorrect`. Switching to QueueTrigger (for example), works.
