### ISSUE TITLE
[Node.js] Application is not restarting after node_modules deployment

### ISSUE THREAD

**Issue by yvele** [Azure/azure-webjobs-sdk-script#608]
When only changes are made within the root node_modules folder, files are deployed but the application is not restarted.

To force restart of the application I added a final step to my deploy.sh :

```bash
touch "$DEPLOYMENT_TARGET/host.json"
```

It's working but it looks kind of a hack.

1. Why is [azure-something] not watching for changes within node_modules folder? Should [azure-something] watch node_modules?
2. Is there a way to restart the application within my deploy script? (see [this question](https://www.bountysource.com/issues/36658865-is-it-possible-to-trigger-restart-for-httpplatfrom-via-kudu-deployment-script))

-----

Context :
- Using **Azure Function** with **Node.js**
- Building my application on my own CI machine : The builds already includes all dependencies in node_modules
- The build is deployed on Azure with git
- Default deploy strict is making an `npm install --production` and because I already have all my dependencies in ma build, I made a custom deploy script that skips the `npm install`

My structure looks like :

```none
function1/
    function.json
    index.js
function2/
    function.json
    index.js
node_modules/
.deployment
deploy.sh
host.json
package.json
```

----

Originally opened on projectkudu/kudu : https://github.com/projectkudu/kudu/issues/2109
@davidebbo points me out that this issue is more relevant here on azure-webjobs-sdk-script

**Comment by mathewc** [comment]
Yes, we're currently not watching for file changes in the root node_modules folder. We should. As it stands now, we watch for changes under each function directory recursively, as well as watching for host.json changes. Thanks for reporting this - we'll address ASAP.

**Comment by mathewc** [comment]
Thanks for reporting. Fixed by https://github.com/Azure/azure-webjobs-sdk-script/pull/613. We'll get this out with our next release in a week or so.
