### ISSUE TITLE
Remove discrepancy between query string token in plain http vs WebHook

### ISSUE THREAD

**Issue by davidebbo** [Azure/azure-webjobs-sdk-script#61]
Currently, WebHooks use `code=...` (coming from WebHook SDK), while plain http use `key=...` (coming from our own logic).

One way or another, let's find a way to make them be the same.

**Comment by mathewc** [comment]
I'm planning on creating a pull request against the WebHooks SDK to make it configurable. I investigated but didn't want to do url rewrite on our side, because the SDK error messages would still mention 'code' which would confuse our users.

**Comment by davidebbo** [comment]
As long as we can push for a new version of WebHooks SDK to be published promptly, that would be a good approach. So `key` everywhere.

**Comment by mathewc** [comment]
So further investigation shows that the 'code' nomenclature is spread throughout many of the SDK WebHook receiver implementations. It's a pattern, not a one off to tweak/configure. See [here](https://github.com/aspnet/WebHooks/search?utf8=%E2%9C%93&q=%27code%27). Therefore, we probably should just bite the bullet and follow suit, using a 'code' query parameter for our key values as well.

**Comment by christopheranderson** [comment]
+1 - this is likely the right thing to do for debug-ability
