### ISSUE TITLE
F# compilation warning (FS988)

### ISSUE THREAD

**Issue by fabiocav** [Azure/azure-webjobs-sdk-script#616]
When compiling F# functions using the script host, users will see the following compilation warning:
`2016-08-27T20:47:24.600 D:\local\Temp\tmp3604.fsx(4,72): warning FS988: Main module of program is empty: nothing will happen when it is run`

This doesn't apply in the context of Azure Functions and we should consider suppressing `FS988` to avoid confusion. 

@dsyme / @tpetricek any concerns about having `FS988` suppressed when compiling/running in the Azure Functions host?

**Comment by dsyme** [comment]
No concerns, though I believe the problem is the use of a ``.EXE`` extension [here](https://github.com/Azure/azure-webjobs-sdk-script/blob/dev/src/WebJobs.Script/Description/FSharp/FSharpCompiler.cs#L118).  We should try a ``.DLL`` extension.  I don't know of any specific reason why that won't work (though maybe there was one, since I would normally have used ``.DLL`` by default)

**Comment by dsyme** [comment]
Oh, IIRC the use of a .DLL extension may change the name of the implicit module/static class into which the function is compiled

**Comment by dsyme** [comment]
> When compiling F# functions using the script host

@fabiocav Could you write out the repro steps for this?  Is "compiling using the script host" something that end-users of the portal can do, or just developers in this repo?

Thanks
Don

**Comment by fabiocav** [comment]
This is when end-users compile their F# functions in the portal. We display all the compilation output in the output window. Outside of the portal, any change to your function file would trigger the compilation process.

**Comment by fabiocav** [comment]
The original issue summary was poorly worded and I can see how it was confusing.

Any function compilation will generate that warning, which is not an issue in our case, so something we could suppress.
