### ISSUE TITLE
Ensure WebHost Monitors for Graceful Shutdown

### ISSUE THREAD

**Issue by mathewc** [Azure/azure-webjobs-sdk-script#62]
When the WebJobs SDK is running under Kudu SCM, it handles this via a signal file that the Kudu process manager “touches”, and the SDK is watching that to perform graceful shutdown.

Since we’re not running under Kudu we’ll have to handle this ourselves. The SDK already has graceful shutdown plumbed properly, so we’ll just need to signal it a the right time.

**Comment by fabiocav** [comment]
Reviewing the need to actually make any changes as this might already be covered by making use of the QueueBackgrounWorkItem API that takes a `CancellationToken`:
https://github.com/Azure/azure-webjobs-sdk-script/blob/master/src/WebJobs.Script.WebHost/App_Start/AutofacBootstrap.cs#L46

**Comment by fabiocav** [comment]
I actually see that there is one small change we need to make, which is to wait on that token in the run loop. I'll work on that, but that's a much smaller change than we originally anticipated.
