### ISSUE TITLE
Deserialization in Function ignoring base classes from other library

### ISSUE THREAD

**Issue by danbueno20** [Azure/azure-webjobs-sdk-script#626]
I'm not sure if this is a Functions issue or a Newtonsoft.Json issue.  It works in a regular project, so I'm guessing Functions.

We have a `public interface IVersionedEvent` and a `public abstract class VersionedEvent : IVersionedEvent` in a project called Infrastructure.  In a Domain project we have a `public abstract class SegmentEvent : VersionedEvent` and a `public class SegmentAdded : SegmentEvent`.  When deserializing a `SegmentAdded` object, the Function gets an exception when trying to cast that instance to an `IVersionedEvent`.  Getting the type of `SegmentAdded`, its `BaseType` chain and interfaces show correctly.  I logged some `is` checks and saw the following:

- `parsedEvent is SegmentAdded`: `true`
- `parsedEvent is SegmentEvent`: `true`
- `parsedEvent is VersionedEvent`: `false`
- `parsedEvent is IVersionedEvent`: `false`

If I instantiate a SegmentAdded event directly (not deserialized), the results are all `true`.  Could this be some sort of assembly issue?  The casting error message says the correct type names for the parsed object and `IVersionedEvent`.  We updated the libraries and it worked for a bit and then started failing again.  We have multiple functions with their own copies of the same libraries.  We recently started updating our libraries' versions so older ones wouldn't interfere with newer ones (i.e. a function couldn't recognize a new class that hadn't been defined in an older version).  All versions have those 4 definitions, however. Let me know if anything is unclear.

**Comment by mathewc** [comment]
Can you provide us with a repro?

**Comment by danbueno20** [comment]
Well, I've tried creating a separate repro solution that mimics what we have, but have not been successful.  It appears that when the host restarts, the problem goes away for a while.  We are still seeing potential cache/version issues when updating functions as well, so I don't know if sharing our actual function and DLLs would be helpful yet.  If we can find something consistently reproducible in the next few days, I'll provide it.  Otherwise, should I just close this issue?

**Comment by christopheranderson** [comment]
Without a repro, we'll just close this for now. Feel free to provide one and we'll reopen. :)
