### ISSUE TITLE
Enabling Authentication / Authorization prevents non-HTTP triggers from running

### ISSUE THREAD

**Issue by cgillum** [Azure/azure-webjobs-sdk-script#627]
**Repro steps**
1. Create a function app with a queue trigger in the Dynamic plan
2. Enable Authentication / Authorization on a web app
3. Set "Action to take when request is not authenticated" to "Log in with XXX"
4. Configure the XXX provider and then save changes
5. Populate the queue with messages

**Expected**
Queue messages get picked up and function runs.

**Actual**
Queue messages never get picked up and function never runs.

**Workaround**
if you manually browse to the function app and log in with valid credentials, then you'll notice that the messages get picked up.

This is because the Authentication / Authorization feature is blocking attempts to wake up the Functions host. To mitigate this, the Authentication / Authorization feature plans to allow anonymous access to the **/.platform/keep-alive** endpoint for function apps. The functions host then needs to listen on this endpoint and return a success response (i.e. HTTP 200).

**Comment by cgillum** [comment]
We did more investigation into this, and it appears to be a regression that was introduced in version ~0.4 of the Functions SDK. I verified by updating the FUNCTIONS_EXTENSION_VERSION app setting to ~0.3 and saw that non-HTTP triggers started running without any issues, even when Authentication / Authorization was enabled.

I suggest we can figure out what changed in the web host between ~0.3 and ~0.4 to cause the regression and then fix it accordingly.

**Comment by fabiocav** [comment]
The change was  related to the standby support added to 0.4, where the host initialization was moved from Application_Start.
A new issue was created by @suwatch #647 and the initialization will be moved back to ensure the host runs when the application starts.
