### ISSUE TITLE
Move from portal to git

### ISSUE THREAD

**Issue by garrardkitchen** [Azure/azure-webjobs-sdk-script#629]
I have created functions in the portal and now want to develop them locally (e.g. vscode).  My question is this.... how do I push these extant functions to git (bitbucket)?  I see that the sync process basically pulls (deploys) changes from git to the portal which doesn't really help me when initially I want the code to go the other way.  

Warmest regards,

Garrard.

**Comment by dsyme** [comment]
I was also wondering about this

**Comment by ahmelsayed** [comment]
the gesture for doing this at the moment is to:

1. clone your function app
2. push it to github, bitbucket, etc 
3. setup continuous integration to that repo, that'll do a simple no-op initial deployment, then you will be only pushing to the repo. 
For now we disable editing in the UX if you have source control configured to avoid conflicts. I'm working on a way to get portal UX for local development as well as better local debugging and editing experience in vscode.

If you want to follow progress, follow these 2 PRs #453, #477. I know the former is closed, but I'll open a similar one today or Monday.

**Comment by garrardkitchen** [comment]
Hi @ahmelsayed,

I appreciate your suggestion.  Is there a download option somewhere or will I have to cut and paste the contents of all the files into new files on my desktop?

Warmest regards,

Garrard.

**Comment by ahmelsayed** [comment]
```typescript
`https://${yourFunctionAppName}.scm.azurewebsites.net/api/zip/site/wwwroot`
```
should download all of your functionapp content in a zip. I was planning on adding a link to that in the portal, but haven't had a chance to do, feel free to open a bug on this repo https://github.com/projectkudu/AzureFunctionsPortal to track it.

**Comment by garrardkitchen** [comment]
Excellent!  Thanks @ahmelsayed!
