### ISSUE TITLE
Advice on how to update & delete row from Azure Storage Table 

### ISSUE THREAD

**Issue by garrardkitchen** [Azure/azure-webjobs-sdk-script#632]
I see via c# / f# langues you can both query (IQueryable) & insert (ICollector) rows into Azure Storage Table.  Are there any examples (or documentation) on how to update & delete from an Azure Storage Table?

Warmest regards,

Garrard.

**Comment by azyl-scnsoft** [comment]
Hi @garrardkitchen 

You need to use CloudTable as input binding, then you can manage entities by executing corresponding operations
`    var operation = TableOperation.Replace(entity);
    await entityTable.ExecuteAsync(operation);
`

**Comment by mathewc** [comment]
Yeah, the underlying Table bindings support query/add, but not update semantics. Recommend doing what @azyl-scnsoft suggests. Here's a handy [cheat sheet](http://go.microsoft.com/fwlink/?LinkID=524028&clcid=0x409) for the bindings.

**Comment by garrardkitchen** [comment]
Thanks @azyl-scnsoft and @mathewc, this did the trick and thanks too for the cheat sheet @mathewc.
