### ISSUE TITLE
Azure Functions - Portal deletes file when trying to rename

### ISSUE THREAD

**Issue by alaatm** [Azure/azure-webjobs-sdk-script#634]
**Steps to repro:**
1. Open a function.
2. Click View files to open files tab.
2. Select a js file.
3. Click the button with pencil icon. The selected filename becomes editable.
4. Press enter (As in you changed your mind and no longer want to rename).

**Expected behavior:**
File name remains the same.

**Actual behavior:**
File disappears. If you FTP into your function, you'll notice the file is gone.

**Functions ver 0.5**

**Comment by ahmelsayed** [comment]
that's pretty bad, sorry about that. should be fixed in https://github.com/projectkudu/AzureFunctionsPortal/commit/77f213500021238547308a97b079d579062c7010. I'll push it to production today
