### ISSUE TITLE
Improve error message for SendGrid binding when incorrectly configured

### ISSUE THREAD

**Issue by azyl-scnsoft** [Azure/azure-webjobs-sdk-script#640]
#### Repro steps

1. Create new SendGrid function from C# samples
2. Try to execute the function

Provide the steps required to reproduce the problem

1. Step A

2. Step B

#### Expected behavior

Function is called and an email is sent

#### Actual behavior

Indexing error appears:

> Cannot bind parameter 'sgMessage' to type SendGridMessage&. Make sure the parameter Type is supported by the binding. If you're using binding extensions (e.g. ServiceBus, Timers, etc.) make sure you've called the registration method for the extension(s) in your startup code (e.g. config.UseServiceBus(), config.UseTimers(), etc.).

**Comment by mathewc** [comment]
I just tried myself starting from scratch with the default template and it works flawlessly for me. Please provide your repro code so we can see what might be wrong - it looks like you've modified the code.

**Comment by azyl-scnsoft** [comment]
@mathewc  
Turned out that I didn't set AzureWebJobsSendGridApiKey app setting. 
Even so, it's strange to get such non-informative error.
SendGridExtensionConfig raises InvalidOperationException with appropriate error message when it cannot find the key, but it seems that the exception is swallowed somewhere.

**Comment by mathewc** [comment]
For Functions, we don't even register the SendGrid extension if the host level config isn't present - that's the issue. Code [here](https://github.com/Azure/azure-webjobs-sdk-extensions/blob/master/src/WebJobs.Extensions.SendGrid/Bindings/SendGridScriptBindingProvider.cs#L46). Since you don't have an API key, the host hasn't registered SendGrid at all, hence the binding error.

I'll re-title this issue to serve as a suggestion to improve this somehow - perhaps we can detect this better.

**Comment by azyl-scnsoft** [comment]
@mathewc  
I compared Twilio and SendGrid config providers. When configuring SendGrid, InvalidOperationException is thrown from Initialize method, whereas in Twilio config the key validator is registered in RegisterBindingRules.
So the issue with SendGrid can be fixed by moving key validation to RegisterBindingRules.

**Comment by mathewc** [comment]
Addressed by @brettsam in https://github.com/Azure/azure-webjobs-sdk-script/commit/a269bd36bcbfd51844c2987b9fe5bd091666df8f. @brettsam I believe this is addressed by your changes?
