### ISSUE TITLE
Twilio binding fails with auth params in function.json

### ISSUE THREAD

**Issue by azyl-scnsoft** [Azure/azure-webjobs-sdk-script#641]
#### Repro steps

1. Create new C# empty function

2. Add twilio binding with SID and Auth Key settings 

3. Add function out SMSMessage argument

#### Expected behavior

Function compiled successfully

#### Actual behavior

Indexing error occurs:

 > Microsoft.Azure.WebJobs.Host: Error indexing method 'Functions.ManualTriggerCSharp1'. Microsoft.Azure.WebJobs.Host: 'KEY_VALUE_GOES_HERE' does not resolve to a value.

#### Known workarounds

Remove SID and Key settings from function.json and add  AzureWebJobsTwilioAccountSid and AzureWebJobsTwilioAuthToken to web app settings

**Comment by azyl-scnsoft** [comment]
I checked twilio extension source code and it's turned out that accountSid and authToken are decorated with AutoResolveAttribute(false) and are not actual values, but app settings names that store the values.

**Comment by mathewc** [comment]
Right - for security reasons we don't want to support putting secrets into function.json. It's always indirect via app settings. You'll find that to be the case with all the other bindings as well, for connection strings, etc.
