### ISSUE TITLE
PDF Generation, does it work now?

### ISSUE THREAD

**Issue by ctolkien** [Azure/azure-webjobs-sdk-script#642]
For a long time generating PDF's on Azure App Services has been very difficult. This post also outlines which PDF services don't work:

https://github.com/azure/azure-webjobs-sdk-script/wiki

Well, I've just given `wkhtmltopdf` another shot recently, and lo and behold, when on a Basic+ plan, it does indeed work (previously, it would render but without any font glyphs).

Is this now a supported scenario?

**Comment by davidebbo** [comment]
I don't believe anything has changed to the sandbox. But if you find that wkhtmltopdf works on Basic/Standard, I can updated https://github.com/projectkudu/kudu/wiki/Azure-Web-App-sandbox#unsupported-frameworks accordingly. There are other scenarios that work only in Basic+ (and have for a while). Maybe the knowledge that wkhtmltopdf doesn't work goes back to before that general Basic+ changes were in?

**Comment by ctolkien** [comment]
Hrrmm.. Well something has definitely changed at some point...

I've just also tried Rotativa - a wrapper around wkhtmltopdf to produce PDF's from MVC Views, and it too, also worked. Previously we had the same issue with not rendering font glyphs.

Checking the dates of issues such as https://github.com/webgio/Rotativa/issues/87 this didn't work in 2015. So I'm not sure when changes were actually rolled out?

Is probably worthwhile revisiting all PDF scenarios to see what is supported.

**Comment by davidebbo** [comment]
I've asked the sandbox experts if anything has changed. I believe the changes that relaxed the sandbox in Basic or higher Plan go back to late 2014. However, it's not clear in the issue you point to whether the user had in fact tried Basic+.

**Comment by davidebbo** [comment]
Sure enough, there was an additional change a few months ago that enabled WebKit support, which likely enabled wkhtmltopdf. I've updated the wiki.

**Comment by mathewc** [comment]
@ctolkien What is your scenario exactly out of curiosity? What are you writing a function to do?

**Comment by ctolkien** [comment]
@mathewc we have a payroll application we've been trying to port to Azure App Services which generates PDF based payslips from Razor views (among other things) which are emailed out to employees. These are currently generated in the context of the website itself (which has it's own issues, it's a slow process), running on a VM outside of Azure.

Previous attempts at running the same code insider Azure App Services have resulted in the same "no fonts displayed" issue. 

Our most recent porting effort was using Azure Functions and trailing a number of different PDF generation techniques - some nodejs based, when I blindly trialled running wkhtml2pdf.exe directly, which indeed worked.

Solution we're heading towards now has the website render the views to strings and dump them into blob storage along with a queue message with metadata about the payslip. Our function watches this queue, picks up the blob, writes the html to disk, uses wkhtml2pdf.exe to convert it to a pdf, and then fires out the email. It then sticks the PDF back in a new blob for safe keeping.

**Comment by webgio** [comment]
@ctolkien easier solution would have been to create PDF using a HTTP API... Perhaps you know we have a pretty good solution for "Rotativa as a Service"...

**Comment by ctolkien** [comment]
@webgio I'm aware of your service (I've spoken to you on twitter about it :)) we hit blocks getting a dependency on a 3rd party approved for this particular client as the PDF's were generating contain payroll and other personal information.

The good news out of all of this however is that Rotativa now "just works" on Azure Web Apps

**Comment by TOuhrouche** [comment]
There is unfortunately no way to generate PDFs in an Azure Web app service. This is mainly because of the restrictions this setup enforces on users. This is being said, we have successfully managed to make this work on Cloud Services instead where you have more control over the application (you are even given access to the VM where the cloud service runs)

**Comment by AmilkarDev** [comment]
Hi @ctolkien  ,  You said that "The good news out of all of this however is that Rotativa now "just works" on Azure Web Apps" , but It didn't work for me , does anyone has an idea if it works now in azure on asic plan ?

**Comment by ctolkien** [comment]
@AmilkarDev  - It should - when you say it "doesn't work", what is the issue? Our previous problems were to do with font glyphs not rendering.

**Comment by AmilkarDev** [comment]
am trying to use rotativa on azure basic plan , it throws an 500 error internal server error

**Comment by TOuhrouche** [comment]
Hi,
You need to be on standard or higher plan to run Rotativa. 
The basic plan has a more restrictive sandbox and won't allow you to successfully ran Rotativa. 


Regards,
Tahar

**Comment by davidebbo** [comment]
Actually, the looser sandbox starts with Basic, not Standard. So I would not expect Standard to help if it doesn't work in Basic. See [wiki](https://github.com/projectkudu/kudu/wiki/Azure-Web-App-sandbox) for details, and see the references to 'Basic'.
