### ISSUE TITLE
Error during deployment ~0.5 : remote: No available node.js version matches application's constraint of >=6.4.0

### ISSUE THREAD

**Issue by yvele** [Azure/azure-webjobs-sdk-script#643]
#### Repro steps

1. Using Azure Function ~0.5
2. Having a package.json having `"engines": { "node": ">=6.4.0" }`
2. Deploying a Node.js v6.4.0 Azure Fonction with git

#### Expected behavior

Node.js v6.4.0 should be on the server as [0.5 release note](https://github.com/Azure/azure-webjobs-sdk-script/releases/tag/v1.0.0-beta1-10398) says :

> Moved to Node.js 6.4.0

#### Actual behavior

Error during deployment 

```
remote: Looking for app.js/server.js under site root.
remote: Node.js versions available on the platform are: 0.6.20, 0.8.2, 0.8.19, 0.8.26, 0.8.27, 0.8.28, 0.10.5, 0.10.18, 0.10.21, 0.10.24, 0.10.26, 0.10.28, 0.10.29, 0.10.31, 0.10.32, 0.10.40, 0.12.0, 0.12.2, 0.12.3, 0.12.6, 4.0.0, 4.1.0, 4.1.2, 4.2.1, 4.2.2, 4.2.3, 4.2.4, 4.3.0, 4.3.2, 4.4.0, 4.4.1, 4.4.6, 4.4.7, 5.0.0, 5.1.1, 5.3.0, 5.4.0, 5.5.0, 5.6.0, 5.7.0, 5.7.1, 5.8.0, 5.9.1, 6.0.0, 6.1.0, 6.2.2, 6.3.0.
remote: An error has occurred during web site deployment.
remote: select node version failed
remote: Missing server.js/app.js files, web.config is not generated
remote: No available node.js version matches application's version constraint of '>=6.4.0'. Use package.json to choose one of the available versions.
remote: 
remote: Error - Changes committed to remote repository but deployment to website failed.
```

#### Known workarounds

Actually using Node.js v6.3.0 in my package.json

```
"engines": {
  "node": ">=6.3.0"
}
```
`iisnode.yml` will be `nodeProcessCommandLine: "D:\Program Files (x86)\nodejs\6.3.0\node.exe"`

#### Related information 

* Programming language used : Node.js v6.4.0
* Application Settings : `WEBSITE_NODE_DEFAULT_VERSION = 4.1.2` (wtf?)

**Comment by davidebbo** [comment]
Indeed, the problem is that we're missing the latest Node on the server. We will add this later this week.

Though I am a bit confused about one thing: normally, a Function App repo should not be treated as a Node app by Kudu, since it really isn't a Web App (e.g. it doesn't need a web,config). Do you have a custom deployment script? Can you share a sample repo that has this behavior?

**Comment by yvele** [comment]
Yes I have a custom deployment script. My deployment script is based on **KUDU Deployment Script Version: 1.0.8**, here is the end of the file :

```bash
##################################################################################################################################
# Deployment
# ----------

echo Handling node.js deployment with custom script.

# 1. KuduSync
if [[ "$IN_PLACE_DEPLOYMENT" -ne "1" ]]; then
  "$KUDU_SYNC_CMD" -v 50 -f "$DEPLOYMENT_SOURCE" -t "$DEPLOYMENT_TARGET" -n "$NEXT_MANIFEST_PATH" -p "$PREVIOUS_MANIFEST_PATH" -i ".git;.hg;.deployment;deploy.sh"
  exitWithMessageOnError "Kudu Sync failed"
fi

# 2. Select node version
selectNodeVersion

# 3. Retart application (hack)
touch "$DEPLOYMENT_TARGET/host.json"

# X. Install npm packages
# if [ -e "$DEPLOYMENT_TARGET/package.json" ]; then
#   cd "$DEPLOYMENT_TARGET"
#   eval $NPM_CMD install --production
#   exitWithMessageOnError "npm failed"
#   cd - > /dev/null
# fi

##################################################################################################################################
echo "Finished successfully."
```

I'm only disabling node installation (as my repo is already shipped with dependencies) and touching host.json to fix https://github.com/Azure/azure-webjobs-sdk-script/issues/608

**Comment by davidebbo** [comment]
We now have Node v6.5 available, which should address the original issue.

**Comment by yvele** [comment]
@davidebbo Thanks, I'm gonna give it a try 👍
