### ISSUE TITLE
Output Binding Blob Storage

### ISSUE THREAD

**Issue by ctolkien** [Azure/azure-webjobs-sdk-script#645]
According to these docs:
https://azure.microsoft.com/en-us/documentation/articles/functions-bindings-storage/#storageblobbindings

The following types should be bindable for blobs for writing:

* TextWriter  - works
* Stream - works
* CloudBlobStream - works
* ICloudBlob - fails - `Cannot bind blob to ICloudBlob using access Write.`
* CloudBlockBlob - fails - `Cannot bind blob to CloudBlockBlob using access Write.`
* CloudPageBlob - fails - `Cannot bind blob to CloudPageBlob using access Write.`

**Comment by azyl-scnsoft** [comment]
@ctolkien 
last three types support only ReadWrite access, so binding should be "inout"

You can also use this quick reference
http://go.microsoft.com/fwlink/?LinkID=524028&clcid=0x409

**Comment by ctolkien** [comment]
Ahh ok, the docs to me read differently. There are ones listed as `input` only and `output` only. I'd assumed the ones without mentioning either `input` or `output` could be used as either - not requiring `intout`.

**Comment by azyl-scnsoft** [comment]
@ctolkien  
Agreed. There is no mention about such binding in the documentation. 
I learned about 'inout' only after looking into the source code.

**Comment by fabiocav** [comment]
`inout` are supported by the runtime, but there's no UI support in the portal yet. You can use them by manually editing the binding direction in the raw `function.json` file.

**Comment by mathewc** [comment]
FYI: We're tracking portal improvements for this here: https://github.com/projectkudu/AzureFunctionsPortal/issues/431
