### ISSUE TITLE
Brand new Azure Function have WEBSITE_NODE_DEFAULT_VERSION set to 4.1.2 (instead of 6.4.0)

### ISSUE THREAD

**Issue by yvele** [Azure/azure-webjobs-sdk-script#646]
#### Repro steps

Using Azure Portal
1. Migrate an existing Azure Function from `~0.4` to `~0.5`
2. Create a brand new Azure Function (`~0.5`)
#### Expected behavior

Migrated and brand new Azure Functions should have similar **Application Settings**
#### Actual behavior

Migrated and brand new Azure Functions (both on `~0.5`runtime) have different **Application Settings**

Migrated (from `~0.4` to `~0.5`) have **WEBSITE_NODE_DEFAULT_VERSION** set to **6.4.0**

```
AzureWebJobsDashboard => DefaultEndpointsProtocol=https;AccountName=XXX;AccountKey=XXX
AzureWebJobsStorage => DefaultEndpointsProtocol=https;AccountName=XXX;AccountKey=XXX
FUNCTIONS_EXTENSION_VERSION => ~0.5
AZUREJOBS_EXTENSION_VERSION => beta
WEBSITE_CONTENTAZUREFILECONNECTIONSTRING => DefaultEndpointsProtocol=https;AccountName=XXX;AccountKey=XXX
WEBSITE_CONTENTSHARE => XXX
WEBSITE_NODE_DEFAULT_VERSION => 6.4.0
```

Brand new (`~0.5`) have **WEBSITE_NODE_DEFAULT_VERSION** set to **4.1.2**

```
AzureWebJobsDashboard => DefaultEndpointsProtocol=https;AccountName=XXX;AccountKey=XXX
AzureWebJobsStorage => DefaultEndpointsProtocol=https;AccountName=XXX;AccountKey=XXX
FUNCTIONS_EXTENSION_VERSION => ~0.5
AZUREJOBS_EXTENSION_VERSION => beta
WEBSITE_NODE_DEFAULT_VERSION => 4.1.2
```
#### Known workarounds

The application is still working with **WEBSITE_NODE_DEFAULT_VERSION** set to **4.1.2** but I'm a bit confused.. what is this setting? Why is it set to 4.1.2? Should I change it?
#### Related information

Provide any related information 
- Programming language used : Node.js (6.3.0)
- Related to https://github.com/Azure/azure-webjobs-sdk-script/issues/643 ?

**Comment by christopheranderson** [comment]
This is likely a bug in our portal. We'll update this when we have the right Node.js version on the box.

**Comment by paulbatum** [comment]
Confirmed fixed in prod.
