### ISSUE TITLE
The host doesn't generate the secret files for functions

### ISSUE THREAD

**Issue by ahmelsayed** [Azure/azure-webjobs-sdk-script#648]
Please provide a succinct description of the issue.

#### Repro steps

Provide the steps required to reproduce the problem

1. Create a new http function

#### Expected behavior

I expect the host to generate a `D:\home\data\Functions\secrets\<functionName>.json`

#### Actual behavior

File is not generated

#### Known workarounds

Use the function key in `D:\home\data\Functions\secrets\host.json` or create my own

**Comment by mathewc** [comment]
For functions secrets we've never created them when the function is created - only when a function is invoked for the first time (code [here](https://github.com/Azure/azure-webjobs-sdk-script/blob/dev/src/WebJobs.Script.WebHost/SecretManager.cs#L64)).

We could modify our startup logic such that it initializes secrets for any new functions if there aren't already secrets present.

**Comment by davidebbo** [comment]
@ahmelsayed how is the portal getting the secret? Is that through Kudu API? If so, having the runtime create the secrets on startup would not work reliably, as there is no guarantee that we'll go through that sequence by the time you call Kudu.

**Comment by ahmelsayed** [comment]
I can poll the secrets is they are not there and we expect them to be.

**Comment by fabiocav** [comment]
Closing this as this will no longer be an issue when consuming secrets through the secret management API. Please let me know/reopen if there are any concerns.
