### ISSUE TITLE
Timeout improvement: don't restart site if CancellationToken handled properly

### ISSUE THREAD

**Issue by brettsam** [Azure/azure-webjobs-sdk-script#655]
If you have a function handling the CancellationToken properly that exits soon after we cancel the token, we shouldn't really have to restart the application. We could find a way to wait a short time (the timeout grace period), then check if the function Task had completed yet. If it had, we can just continue on. If it was still running we would then restart the site as we do today.

**Comment by mathewc** [comment]
I don't understand - if a timeout expires and we've cancelled the token, why don't we want to enforce the timeout rules and throw an exception if they've asked for it?

**Comment by brettsam** [comment]
We asked for the exception to be thrown so we can handle it in a custom way. In this case, we want to let C# functions have a chance to handle the token and continue on. The experience is much nicer.

There's a chance they fired off infinite threads from within the function, but that will likely be rare and the benefits for C# are pretty nice.

**Comment by fabiocav** [comment]
Yeah. This gives users the ability to write *well behaved* functions that will handle cancellation gracefully and avoid impacting other work.

**Comment by mathewc** [comment]
I see, yes.
