### ISSUE TITLE
F# Error using Jil library

### ISSUE THREAD

**Issue by nicolocodev** [Azure/azure-webjobs-sdk-script#659]
I'm using the [Jil](https://www.nuget.org/packages/Jil/) package and getting a *weird* error.

#### Repro steps

1. Add this dependency on `project.json`
```json
"Jil":"2.14.5"
```
2. Push the changes and see the following log message:
`commandLineArgs(1,1): error FS215: Multiple references to 'mscorlib.dll' are not permitted`

#### Related information 

I've tested the library on F# Scripts locally and works well, no errors:

```fsharp
#I "../packages"
#r "Jil.2.14.5/lib/net45/Jil.dll"
#r "Sigil.4.6.1/lib/net45/Sigil.dll"
open Jil
type Person = {
    Name : string 
}
let n = {Name = "Nicolas"}
Jil.JSON.Serialize(n)
```
Why is this library causing this?

**Comment by RaulMo7** [comment]
Hipster xD

**Comment by fabiocav** [comment]
Package references are automatically added to your function, so you should not have to specify explicit references to them.
