### ISSUE TITLE
Node process isolation

### ISSUE THREAD

**Issue by dennis-yemelyanov** [Azure/azure-webjobs-sdk-script#667]
It seems by default functions runtime tries to execute multiple instances of the function in the same process. Is there some config that can be set to isolate each function invocation by always running it in a new process? There are couple of reasons the default behavior is sub-optimal for us:

1. If the host goes down due to some issue in one instance (unhandled node exception or some other error), it affects all other instances running on the same host (they have to be retried, which is not always possible etc.)
2. Some modules that the function depends on have global variables that are shared between different function invocations, which is also undesirable.

I understand that executing a function every time in a separate process may cost more, but in this case achieving high reliability is more important than potential extra cost or slightly lower performance.

**Comment by mathewc** [comment]
No there is no way to do this currently - we run functions in a shared process model only right now.

One potential workaround would be to use our BAT/Bash support which is out of process (new process per invocation). Outside of the perf drawbacks to this, the programming model won't be as rich as it is for in process Node.

**Comment by dennis-yemelyanov** [comment]
Thank you, I'll look at the batch support. It seems like basic bindings are supported (such as queue input), are there other potential issues due to the limited programming model? (Especially some tricky ones that won't show up at development time)

Also it looks like the Node.exe version installed in the system is really old (v0.10.28). Is there a way to update it? (DebugConsole doesn't seem to have enough permissions)

**Comment by mathewc** [comment]
Our VMs have node 6.3.0 installed which is pretty recent.

**Comment by dennis-yemelyanov** [comment]
Hmm executing "node -v" in the Debug Console prints v0.10.28 (installed in D:\Program Files (x86)\nodejs\0.10.28). There is also another one at D:\Program Files (x86)\nodejs, but it seems even older (v0.6.20). Did I miss some other location?

**Comment by mathewc** [comment]
Try setting the `WEBSITE_NODE_DEFAULT_VERSION` app setting (details [here](https://azure.microsoft.com/en-us/documentation/articles/nodejs-specify-node-version-azure-apps/)).

**Comment by dennis-yemelyanov** [comment]
That one is already set to 6.4.0. Anyway I can probably specify the full path to 6.3.0 explicitly.
