### ISSUE TITLE
Improve SendGrid extension so that it can be set per function

### ISSUE THREAD

**Issue by lindydonna** [Azure/azure-webjobs-sdk-script#669]
Currently, the SendGrid binding requires an app setting for the entire Function App, which is less usable than a setting per function. Related to #640.

**Comment by mathewc** [comment]
Addressed by @brettsam in https://github.com/Azure/azure-webjobs-sdk-script/commit/a269bd36bcbfd51844c2987b9fe5bd091666df8f
