### ISSUE TITLE
System.Net.Http: The format of value 'application/json; charset=utf-8' is invalid.

### ISSUE THREAD

**Issue by yvele** [Azure/azure-webjobs-sdk-script#670]
#### Repro steps

Provide the steps required to reproduce the problem

```js
context.res = {
  headers : { "Content-Type" : "application/json; charset=utf-8" },
  body    : '{"foo":"bar"}',
  status  : 200
};
context.done();
```

#### Expected behavior

`application/json; charset=utf-8` is a valid `content-type` header and there should be no error.

I have a valid JSON string and I would like to pass it directly with the `content-type`

#### Actual behavior

Error after function execution :
> Exception while executing function: Functions.test. System.Net.Http: The format of value 'application/json; charset=utf-8' is invalid.

#### Known workarounds

Not setting `content-type`and passing json as poco in body :
```js
context.res = {
  headers : {},
  body    : { foo: "bar" },
  status  : 200
};
context.done();
```

#### Related information 

* Programming language used : JavaScript with Node.js

**Comment by christopheranderson** [comment]
This is due to how we create the HTTP response and interpret the `content-type` header here: https://github.com/Azure/azure-webjobs-sdk-script/blob/2b30ea32f25ee7c529923755f335b5c686c78399/src/WebJobs.Script/Binding/HttpBinding.cs#L152

```csharp
case "content-type":
    response.Content.Headers.ContentType = new MediaTypeHeaderValue(header.Value.ToString());
    break;
```

We're using MediaTypeHeaderValue which doesn't support `; charset=utf-8` for whatever reason. You can remove that offending bit, and it should work.

@mathewc - could we look at why `MediaTypeHeaderValue` doesn't like the charset in the setting? This is the standard way of setting this header for many scenarios. I've gotten this question before and I think it's likely that other folks hit this, given the ubiquity of setting the charset directly on the content-type header. ([W3 on setting content encoding](https://www.w3.org/International/articles/http-charset/index)).

**Comment by yvele** [comment]
@christopheranderson Thanks. But I can't **not set** charset as a workaround. By actually don't setting content-type at all in the Azure Function handler (and set a POJO in the body) the "Azure Function runtime" will set it automagically to `application/json; charset=utf-8`. The problem with this workaround is that :

- Under the hood I'm using the populars [connect](https://github.com/senchalabs/connect) and [express](https://github.com/expressjs/express) which are manipulating the body as an already stringified JSON (within a [buffer](https://nodejs.org/api/buffer.html))
- I need to explicitely set the full content-type header

Do you have any clue on an eventual MediaTypeHeaderValue fix?

PS: W3 says

> It is very important to always label Web documents explicitly. HTTP 1.1 says that the default charset is ISO-8859-1. But there are too many unlabeled documents in other encodings, so browsers use the reader's preferred encoding when there is no explicit charset parameter.

> The line in the HTTP header typically looks like this:

> `Content-Type: text/html; charset=utf-8`

**Comment by yvele** [comment]
@christopheranderson  Oh.. Should this not be labelled more a bug than an improvement? Explicitly setting `content-type`is quite vital : 

W3 :

> It is very important to always label Web documents explicitly. HTTP 1.1 says that the default charset is ISO-8859-1. But there are too many unlabeled documents in other encodings, so browsers use the reader's preferred encoding when there is no explicit charset parameter.

> The line in the HTTP header typically looks like this:

> `Content-Type: text/html; charset=utf-8`

**Comment by mathewc** [comment]
@yvele Agreed. I just fixed this in https://github.com/Azure/azure-webjobs-sdk-script/commit/fabcfc371add772f6791b30673e30f8578f7b287 and it will go out with our next release. Thanks.

**Comment by yvele** [comment]
@christopheranderson Just to let you know that I replaced my workaround with yours :

> We're using MediaTypeHeaderValue which doesn't support ; charset=utf-8 for whatever reason. You can remove that offending bit, and it should work.

And things went mad..

I removed `charset` part from `content-type` having only `application/json`

Running my Azure Function in **Azure Portal** I get :
```none
Status  : 404 Not Found
Output  : eyJlcnJvciI6Ik5vdCBGb3VuZCIsImNv
```

Running it with my **own client** I get :
```none
Status  : 200 OK
Output  : eyJmb28iOiJiYXIifQ==
```

Where `eyJmb28iOiJiYXIifQ` looks being [a bit of a JWT](https://www.google.fr/search?q=eyJmb28iOiJiYXIifQ).. 

@mathewc  Something funny is happening.. :suspect:

I'm rolling back to my own workaround.. waiting for the next release..

**Comment by PaulHuizer** [comment]
I know this is closed, but same issue exist for `text/html; charset=utf-8`

**Comment by jdepling** [comment]
The same issue exists for `"application/json;v=2"` I am unable to pass in the version through the media type which is a perfectly valid scenario.

**Comment by Clockwork-Muse** [comment]
For that matter, attempting to set the header to `application/json; charset=utf-8` in the Java runner is yielding a 406 status (setting it to `application/json` seems to be overriden)
