### ISSUE TITLE
We need a "SettingsManager" service

### ISSUE THREAD

**Issue by mathewc** [Azure/azure-webjobs-sdk-script#677]
We have many places in the code where we're pulling values from the environment directly (e.g. [here](https://github.com/Azure/azure-webjobs-sdk-script/blob/dev/src/WebJobs.Script.WebHost/Diagnostics/MetricsEventManager.cs#L27)) and caching them statically. This causes problems for our app "warmup" feature, which relies on being able to hot swap in environment settings.

In addition to addressing that issue, it will also facilitate unit testing, mocking, etc.

**Comment by lindydonna** [comment]
This is a requirement for warm workers, good to have otherwise.

**Comment by christopheranderson** [comment]
@tohling & @fabiocav  - What's the status of this?

**Comment by fabiocav** [comment]
@tohling had to change focus but is coming back to this. We should have this soon.

**Comment by fabiocav** [comment]
This has been resolved by #765
