### ISSUE TITLE
NuGet packages should be preferred over the implicit built-in dlls

### ISSUE THREAD

**Issue by jeremymeng** [Azure/azure-webjobs-sdk-script#681]
Please provide a succinct description of the issue.
#### Repro steps

Provide the steps required to reproduce the problem
1. Create a Webhook/HTTP request function from C# template
2. Add a project.json with the following content

``` javascript
{
  "frameworks": {
    "net46":{
      "dependencies": {
        "System.Reflection.Metadata": "1.3.0"
      }
    }
   }
}
```
1. Add the following code in the function

``` csharp
    log.Info(typeof(System.Reflection.Metadata.AssemblyDefinition).Assembly.FullName);
    log.Info(typeof(System.Reflection.Metadata.AssemblyDefinition).Assembly.CodeBase);
```
#### Expected behavior

System.Reflection.Metadata.dll from the NuGet package is loaded at runtime.
#### Actual behavior

The built-in System.Reflection.Metadata.dll is loaded.  The log shows

```
2016-09-13T22:22:00.375 System.Reflection.Metadata, Version=1.4.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
2016-09-13T22:22:00.375 file:///D:/Program%20Files%20(x86)/SiteExtensions/Functions/0.5.10398/bin/System.Reflection.Metadata.DLL
```
#### Known workarounds

None
#### Related information

Provide any related information 
- Programming language used C#

**Comment by ahmelsayed** [comment]
I don't this is possible with the current architecture. you can't load 2 different DLL versions in the same process. (ignoring AppDomains since we will eventually move to .NET Core, which doesn't have app domains)

**Comment by fabiocav** [comment]
We do support multiple side-by-side versions but as @ahmelsayed mentions above, because of the nature of the hosting environment/runtime, there are some limitations.
We'll triage and update this issue when we have more information.

**Comment by christopheranderson** [comment]
@fabiocav - if we change this, will it result in a breaking change? (Placing in rc until you tell me it won't be)

**Comment by fabiocav** [comment]
No. This should already be the default behavior. Just haven't had the bandwidth to look at this yet, but will aim to have an update this week.

**Comment by lindydonna** [comment]
@fabiocav Please prioritize the investigation of this issue as rc:must-have

**Comment by fabiocav** [comment]
A lot of work has happened, issued identified and closed since this was last updated. I'm closing this issue as the behavior has been validated. The assembly binding should behave as described above, except for assemblies currently redirected by the runtime.
