### ISSUE TITLE
Is there way to run a timer based function connected to Event Hubs?

### ISSUE THREAD

**Issue by motifmike** [Azure/azure-webjobs-sdk-script#683]
The event hub trigger is executed every time a single event is sent. I'd like to perform various operations on a batch of data from event hub based on a time interval, is there a way to set this up? There wasn't an option to use Event Hubs as an input when choosing a timer based function. 

I saw that there is an archive option on event hubs which will put the data into a blob every X minutes or Y MB in size. I figured I could use a blob trigger for when those created. However, in retrieving that data, I'm not sure how exactly to parse out my data easily: 
```
2016-09-14T18:41:53.190 Objavro.codecnullavro.schema�{"type":"record","name":"EventData","namespace":"Microsoft.ServiceBus.Messaging",
"fields":[{"name":"SequenceNumber","type":"long"},
{"name":"Offset","type":"string"},
{"name":"EnqueuedTimeUtc","type":"string"},
{"name":"SystemProperties","type":{"type":"map","values":["long","double","string","bytes"]}},
{"name":"Properties","type":{"type":"map","values":["long","double","string","bytes"]}},
{"name":"Body","type":["null","bytes"]}]}
�^|�Q�w���9�}�����1922536(9/14/2016 6:40:50 PM�{"Temperature":"37.0","Humidity":"0.4"}
�^|�Q�w���9�}�����1922672(9/14/2016 6:40:50 PM�{"Temperature":"37.0","Humidity":"0.4"}
�^|�Q�w���9�}�����1922808(9/14/2016 6:40:50 PM�{"Temperature":"37.0","Humidity":"0.4"}
�^|�Q�w���9�}�����1922944(9/14/2016 6:40:51 PM�{"Temperature":"37.0","Humidity":"0.4"}
�^|�Q�w���9�}�����1923080(9/14/2016 6:40:51 PM�{"Temperature":"37.0","Humidity":"0.4"}
�^|�Q�w���9�}��

```
Even if that does work, I was concerned about the 10,000 blob limit documented here: 
https://azure.microsoft.com/en-us/documentation/articles/functions-bindings-storage/

In a 24 hour period @ 1 min archive intervals we are already at 1,400 blobs. The recommendation is then to use a queue trigger. However I don't see any way to use Event Hubs with a queue trigger in this way.

**Comment by mathewc** [comment]
Depending on which language you're using, our EventHub trigger can receive a batch of messages. @MikeStall can provide more info on that.

**Comment by mikejohanson000** [comment]
I am using nodejs as the language, i noticed the settings in the host.json:
```
// Configuration settings for 'eventHub' triggers. (Optional)
    "eventHub": {
      // The maximum event count received per receive loop. The default is 1000.
      "maxBatchSize": 1000,
      // The default PrefetchCount that will be used by the underlying EventProcessorHost.
      "prefetchCount": 100,
    },
```
However, I only ever seem to get one message a time as they come in.

**Comment by mathewc** [comment]
Yes, those settings control EH throughput, but don't control the data type that your script receives. Currently for Node we don't have a way for you to receive an array/batch of messages unfortunately. That's a TODO tracked by existing issue https://github.com/Azure/azure-webjobs-sdk-script/issues/618.

**Comment by motifmike** [comment]
Oh, Sorry I didn't see that. But, this it sounds like the batch is possible for C#?

**Comment by MikeStall** [comment]
We have more EH documentation on the wiki at https://github.com/Azure/azure-webjobs-sdk/wiki/EventHub-support 

Yes, it's possible in C#. Change your binding to an array type and you'll receive a batch. 

This issue will be solved by 618. You can receive events in a single batch via an array binding, but we can't specify the array binding in JScript (that's 618). 


@motifmike - there's no good way to combine timer triggers and reading event hubs. EventHub is its own trigger, and you can only pick 1 trigger. This is a little defferent than say blob where you can have  a Blob Input separate form a Blob trigger.

**Comment by motifmike** [comment]
Ok I follow you. Thanks!  In terms of the second part of my question, in regards to utilizing the archive feature of Event Hubs, that seems to solve the issue of the single record and receiving a batch of records at a time in azure functions. Any thoughts about the 10,000 blob limitation? Is there any focus to utilize a different trigger for blobs other than the logs?

**Comment by MikeStall** [comment]
@motifmike  - we're making some improvements to blob listening (see https://github.com/Azure/azure-webjobs-sdk/issues/786 for example). But blob listening is ultimately going to be limited since the underlying Azure Storage platform does not support blob listening notifications. Hence, we have to approximate with various clever forms of polling.

**Comment by mathewc** [comment]
Batch support for Node EventHub trigger functions has been added in https://github.com/Azure/azure-webjobs-sdk-script/commit/53977df26cbaab9765ae1d107b3460d41ae52c38.

**Comment by motifmike** [comment]
Woohoo!
