### ISSUE TITLE
Rename/move debug sentinel file

### ISSUE THREAD

**Issue by davidebbo** [Azure/azure-webjobs-sdk-script#685]
I just noticed this D:\home\LogFiles\Application\Functions\debug file, though I'm not sure how long it's been there. We should either clean this up, or give it a name/content that makes it clearer why it's there.

**Comment by mathewc** [comment]
It's our sentinel file that we "touch" to put the runtime into Debug mode (e.g. file logging). Got a better name in mind? I think this name is fine.

**Comment by davidebbo** [comment]
Let's rename it to 'EnableDebugLogging.txt'. Not only it's more descriptive, but it's unique enough that they can search the web and find more info about it.

**Comment by mathewc** [comment]
I don't like that name, and giving it a .txt extension implies there's useful content in there for people to look at, which there isn't. This really isn't a file that users should ever concern themselves with. 

I'll think about a less in your face location for it to live so it flies under the radar and people don't wonder about it. Perhaps I'll move it into the `LogFiles\Application\Functions\Host` folder and name it **debug_sentinel**. When the file is created, I can also write "This is a marker file used to control runtime debug mode".
