### ISSUE TITLE
Possible Pulse regression due to event logging changes

### ISSUE THREAD

**Issue by paulbatum** [Azure/azure-webjobs-sdk-script#686]
I installed the most recent build of the functions host to try out the new MDS logging (using a private site extension) and now pulse (access it from function -> monitor -> live event stream) doesn't show any activity for my function app.

**Comment by mathewc** [comment]
Likely not related. What drives Pulse? I added a completely new event stream. I didn't modify existing events.

**Comment by paulbatum** [comment]
Pulse is driven by ETW events but I dont have the details. Can you quickly verify whether you are getting the same behavior as me? Go to a function app running the prod bits and confirm that you see events, then go to another one with a private build and confirm pulse is busted...

**Comment by mathewc** [comment]
Closing this since you confirmed that this isn't an issue anymore?

**Comment by mathewc** [comment]
Fixed in https://github.com/Azure/azure-webjobs-sdk-script/commit/8562d8ad270a1e9458ed3eaa1e51948b5fa8f012
