### ISSUE TITLE
Azure Storage Table output binding gives error for Powershell

### ISSUE THREAD

**Issue by ustimon** [Azure/azure-webjobs-sdk-script#687]
Azure Storage Table output in Powershell gives exception when using standard Powershell commandlets to write, i.e. Out-File of Add-Content. The problem seems to be in the method "Utility.IsJson", which return false in case the binding file represents the valid JSON but contains empty line in the end of file (\r\n). That empty end line is attached by default when using powershell commandlets.

#### Repro steps

1. Create a new empty powershell function.
2. Add the Azure Storage Table output, i.e. the following binding:
{
      "type": "table",
      "name": "outputTable",
      "tableName": "outTable",
      "partitionKey": "Test",
      "rowKey": "{rand-guid}",
      "connection": "AzureWebJobsStorage",
      "direction": "out"
    }
3. Write the simple function that tries to output an object to the table, i.e. the following:

$tableData = [PSObject]@{
	Name = "MyName1"
}
$tableData = $tableData | ConvertTo-Json
$tableData | Out-File $outputTable -Encoding UTF8

#### Expected behavior

A new row should be added to the azure storage table

#### Actual behavior

The function execution completes, but the following exception is written to the log:

Exception while executing function: Functions.EmptyPowerShell1. Microsoft.Azure.WebJobs.Script: Unable to cast object of type 'System.String' to type 'Newtonsoft.Json.Linq.JObject'.

#### Known workarounds

It works if one use the following line in the script

[IO.File]::WriteAllText($outputTable, $tableData)

instead of this:

$tableData | Out-File $outputTable -Encoding UTF8

**Comment by mathewc** [comment]
This is related to known issue here: https://github.com/Azure/azure-webjobs-sdk-script/issues/574. In general, we can't solve the newline issue, until Azure moves to Powershell 5.0, you'll have to employ this workaround.

In this specific case however, I think we can just update our Utility.IsJson to trim whitespace before doing its determination. That would make your scenario work I believe.

**Comment by mathewc** [comment]
I took a look - this issue isn't a trailing newline, its that you're encoding as UTF8, and the BOM character is causing json deserialization to fail. If you instead use `$tableData | Out-File $outputTable -Encoding Ascii` it will work.

**Comment by mathewc** [comment]
Fixed in https://github.com/Azure/azure-webjobs-sdk-script/commit/9d3f881fbc47f04cf12d15fd5705b06ee8e9c0ce
