### ISSUE TITLE
.NET TraceListener is not working with Azure Functions

### ISSUE THREAD

**Issue by yantang-msft** [Azure/azure-webjobs-sdk-script#688]
We’re trying write a TraceListener within Azure Function that can intercept the traces and send to somewhere else, ElasticSearch for example. However, the listener below can’t intercept any traces.

``` csharp
using System;
using System.Diagnostics;
using System.Diagnostics.Tracing;

public static void Run(string input, TraceWriter log)
{
    log.Info($"C# manually triggered function called with input: {input}");
    var listener = new MyListener(log);

    Trace.TraceError("This is a message from trace . . . Error Level.");
    Trace.WriteLine("This is a message from trace . . . The write line method.");
}

public class MyListener : TraceListener
{
    private TraceWriter _log;

    public MyListener(TraceWriter log)
    {
        Trace.Listeners.Add(this);
        this._log = log;
        _log.Info("MyListener is initialized");
    }

    public override void Write(string message)
    {
        _log.Info("MyListener message received: " + message);
    }

    public override void WriteLine(string message)
    {
        _log.Info("MyListener message received: " + message);
    }
}
```
#### Expected behavior

"MyListener" can intercept traces and print the message in the log-streaming service
#### Actual behavior

Nothing shows up

**Comment by davidebbo** [comment]
One thing I noticed is that even without registering my own listener, if I turn on Application tracing to file system and do a Trace.TraceError(), it doesn’t seem to write anything under LogFiles\Application, as it normally does for .NET Web Apps. The way this normally works is that we have trace listeners registered in rootweb.config, and they monitor D:\home\site\diagnostics\settings.json (which is set correctly).

We need to investigate what's breaking this in a Function App.

**Comment by robertmuehsig** [comment]
Just a "dumb" question: I have a precompiled .exe that I invoke in Azure Functions and I have this Trace at the start:
Trace.TraceInformation("Console App started.");

Nothing happens - is this related to the bug or do I just miss something?

**Comment by christopheranderson** [comment]
This is an .exe you're invoking via PowerShell or something?

**Comment by robertmuehsig** [comment]
@christopheranderson Via a run.bat file

**Comment by solvingJ** [comment]
Is there any new information regarding the original issues reported by @yantang-msft and @davidebbo here?

**Comment by davidebbo** [comment]
Ok, so I see what's going on: calls to `Trace.TraceError` (and others) are subject to conditional compilation because those methods have `[Conditional("TRACE")]` on them. Normally, `TRACE` is defined by default when building from VS, e.g.

![image](https://cloud.githubusercontent.com/assets/556238/23146835/27e9adc2-f78f-11e6-9d94-fb05cd42da81.png)

But here the compilation is done dynamically using Roslyn, and no one is defining this. So the calls don't get compiled at all.

**Comment by davidebbo** [comment]
Turns out there is a very simple way to enable this: just add this line at the top of your function:

    #define TRACE

**Comment by robertmuehsig** [comment]
I have the following csx:

#define TRACE

using System;

public static void Run(TimerInfo everyDay, TraceWriter log)
{
    log.Info($"Sloader run.csx invoked at: {DateTime.Now}");    

    System.Diagnostics.Trace.TraceInformation("Hello World!");

    Sloader.Engine.SloaderRunner.AutoRun().GetAwaiter().GetResult();

    log.Info($"Sloader run.csx done at: {DateTime.Now}");    

}

"Sloader..." is included via a NuGet package and inside the lib I use Trace.Trace..., but I can't see any trace - even the Hello World is not visible in the log:

017-02-21T23:18:26.229 Function started (Id=4260982d-91bb-4ca2-b2a5-4671e922ffe0)
2017-02-21T23:18:26.385 Sloader run.csx invoked at: 2/21/2017 11:18:26 PM
2017-02-21T23:18:32.121 Sloader run.csx done at: 2/21/2017 11:18:32 PM
2017-02-21T23:18:32.121 Function completed (Success, Id=4260982d-91bb-4ca2-b2a5-4671e922ffe0)

Do I miss something?

(BTW: Is there a good alternative to .GetAwaiter().GetResult(); )

**Comment by davidebbo** [comment]
I think there are maybe different issues here. The one tracked here is what OP @yantang-msft raised, where he was registering his own trace listener and it wasn't getting called. I tested that exact scenario with the `#define TRACE` and it worked for me. Can you try that?

If it's a different scenario that's not working, let's use a separate issue.
