### ISSUE TITLE
Memory usage increases over time for repeated C# compilations

### ISSUE THREAD

**Issue by paulbatum** [Azure/azure-webjobs-sdk-script#696]
When working with C# functions, every compilation step adds significantly to the overall memory usage of the host process. I have observed 30-40mb private memory increases per compilation. This is likely due to the fact that the host is loading a new assembly for every compilation but is unable to unload assemblies from previous compilations.

Steps to reproduce:
1. Create a C# function
2. Open the process explorer in kudu console to view the memory usage of the host process.
3. Edit the C# function, save, observe memory usage, repeat.

**Comment by davidebbo** [comment]
Mostly fixed by #697. Things to keep in mind:

1. You'll still see memory go up until GC kicks in
2. There are likely still small leaks due to an additional assemblies being loaded each time, but it should be extremely small compared to what you saw before
