### ISSUE TITLE
webjob version for Functions 0.5.10398

### ISSUE THREAD

**Issue by jamesdixon** [Azure/azure-webjobs-sdk-script#698]
Hi,

Usually, there is a WebJobs.Script.Host.zip file available for each release. I'm not seeing it in the latest. Is there a way to obtain this?

Thanks!
James

**Comment by fabiocav** [comment]
We'll update the release with the ZIP as soon as possible, but in the meantime, you can grab that from the build artifacts here: https://ci.appveyor.com/project/appsvc/azure-webjobs-sdk-script-y8o14/build/1.0.10398/artifacts

**Comment by fabiocav** [comment]
The file has been added. Thanks for opening this!

**Comment by jamesdixon** [comment]
Thanks, @fabiocav !
