### ISSUE TITLE
Github webhook no longer working (X-Hub-Signature does not match)

### ISSUE THREAD

**Issue by owainc** [Azure/azure-webjobs-sdk-script#702]
Following the video https://azure.microsoft.com/en-gb/documentation/videos/create-a-web-hook-or-api-azure-function/ will result in the webhook failing - the response from the service being:

```
    {"Message":"The WebHook signature provided by the 'X-Hub-Signature' header field does not match the value expected by the 'GitHubWebHookReceiver' receiver. WebHook request is invalid."}
```

#### Repro steps

Follow along with the video, after creating the webhook in Github the first request will fail, as will subsequent ones.

#### Known workarounds

Use a standard webhook with `code` querystring value, however this does mean the message body is not validated.

**Comment by owainc** [comment]
Thought for a minute I'd submitted to the wrong project, but https://github.com/Azure/Azure-Functions points here.

**Comment by mathewc** [comment]
I'm unable to repro thsi. I just went to our production portal, created a new NodeJS GitHub WebHook for issue comments, and commented on an issue. My function was invoked successfully.

**Comment by owainc** [comment]
OK just went through process again and realized when I pasted the GitHub secret in this comment there was leading/trailing white space - removing this fixed my problem (:facepalm).

OSX 10.11.6, Firefox if it's of interest to anyone on the UI side.
