### ISSUE TITLE
Invalid binding parameters cause host crash

### ISSUE THREAD

**Issue by fabiocav** [Azure/azure-webjobs-sdk-script#71]
Invalid binding parameters cause the host to crash.

This should only impact C#, since it passes the bindings to the WebJobs SDK in the target function. 

Example: blob output binding with path: "some-container-name/{invalidparam}"

**Comment by mathewc** [comment]
Fixed via https://github.com/Azure/azure-webjobs-sdk-script/commit/333d05ac3e31f4dc16ee4b4913b6e5fa83f9353c
