### ISSUE TITLE
ScriptHost fails to initialize FileSystemWatcher if host log folder does not exist

### ISSUE THREAD

**Issue by azyl-scnsoft** [Azure/azure-webjobs-sdk-script#712]
FileSystemWatcher requires an existing hostlog folder path passed to ctor in order  to be instantiated. Without having this folder created in advance, script host initialization fails with the next error: 
```
The directory name C:\\Users\\user\\AppData\\Local\\Temp\\Functions\\Host is invalid.
```
and requires the folder to be created manually.
Probably the check is missing here

Steps to reproduce: 
1) Delete Host folder that is located at C:\\Users\\YOUR_USER\\AppData\\Local\\Temp\\Functions\\Host if it exists
2) Compile ScriptHost project
3) Run Microsoft.Azure.WebJobs.Script.Host.exe

Expected result
Folder is created and host is started

Actual result
Host failed to start. 
Internal exception is thrown:
```
The directory name C:\\Users\\user\\AppData\\Local\\Temp\\Functions\\Host is invalid.
```

**Comment by mathewc** [comment]
How are you initializing your ScriptHost? I.e., what is your repro? :)

**Comment by azyl-scnsoft** [comment]
@mathewc 
My bad. Added steps to reproduce to the description.

**Comment by soninaren** [comment]
@azyl-scnsoft: I was not able to reproduce this. Deleting the host just folder recreates it for me.
Looks like the folder is recreated through the code preset here.
https://github.com/Azure/azure-webjobs-sdk-script/blob/dev/src/WebJobs.Script/Diagnostics/FileTraceWriter.cs#L40-L43

**Comment by soninaren** [comment]
Closing this, Please re-open if you are still seeing this issue.
