### ISSUE TITLE
Add a HostVersion column to MDS output

### ISSUE THREAD

**Issue by paulbatum** [Azure/azure-webjobs-sdk-script#713]
We need the ability to filter the function logs in MDS by host version. Today this information is in the summary text for the Starting Host event but you can't really use that as a filter.

**Comment by mathewc** [comment]
Can you give an example of what type of improved query this would enable? How would you use this?

**Comment by davidebbo** [comment]
An example is trying to scan all the failures that people are hitting. After doing an update with what we think is a fix, having the version in there would help filter to make sure that the error doesn't happen with the new one.

**Comment by fabiocav** [comment]
Tracking timed events/metrics by version is another reason (e.g. average startup by version)

**Comment by pragnagopa** [comment]
PR is code reviewed. Blocked on testing it E2E as this requires an update to MDS config and Antares private stamp deployment
