### ISSUE TITLE
Empty template should not result in host error

### ISSUE THREAD

**Issue by lindydonna** [Azure/azure-webjobs-sdk-script#718]
Moved from https://github.com/projectkudu/AzureFunctionsPortal/issues/575 

@mathewc Why does the host require there to be at least one binding?  It's a bad user experience since it pops up the red dialog.

**Comment by lindydonna** [comment]
@mathewc Says that this would be somewhat involved to fix it at the host level, since one trigger needs to be defined. This is fundamental in how the SDK & Script runtimes work

To investigate: can we fake it and make it a manual trigger when there's no trigger/binding declared?

**Comment by lindydonna** [comment]
If it's involved, we can investigate changing the template.

**Comment by christopheranderson** [comment]
We're going to fix this from the templates experience. Closing this one.
