### ISSUE TITLE
error FS39: The value or constructor '{functionName}' is not defined 

### ISSUE THREAD

**Issue by garrardkitchen** [Azure/azure-webjobs-sdk-script#719]
Hi,

I'm getting an error FS39: The value or constructor '{functionName}' is not defined if {functionName} is in a separate file that is brought in via the #load command.

I'm following instructions via Reusing .fsx code - https://azure.microsoft.com/en-gb/documentation/articles/functions-reference-fsharp/

**api-function-do-struff\run.fsx**

```
...
#load "..\Shared\ParameterUtil.fsx"
let json = generateJson(input)         <---error FS39: The value or constructor 'generateJson' is not defined
...
```

**Shared\ParameterUtil.fsx**

```
...
let generateJson (input:string) = 
    input
...
```

I have observed similar issues when containing types that inherit from TableEntity that too are in a separate file and brought in via #load command.

**Workaround**

```
...
let json = ParameterUtil.generateJson(input)
...
```

Warmest regards,

Garrard.

**Comment by lindydonna** [comment]
@fabiocav please investigate and we can re-triage if needed

**Comment by brettsam** [comment]
@soninaren -- can you see if this still repros with the latest bits?

**Comment by dsyme** [comment]
@garrardkitchen This is by design. You need to qualify the function by the module name. To avoid that, use ``[<AutoOpen>]`` on the module in the file you are loading

**Comment by dsyme** [comment]
@lindydonna  @christopheranderson Please close this, thanks (if you like, add @sylvanc and myself as issue-maintainers to this repo so we can close/tag F#-related issues)
