### ISSUE TITLE
CLI: nuget restore does not seem to be run locally

### ISSUE THREAD

**Issue by GuillaumeSalles** [Azure/azure-webjobs-sdk-script#720]
I have a C# function that run perfectly well when hosted on azure but fail at the compilation when I run it locally. It seems that azurefunctions (from npm) does not restore the nuget packages correctly. 
#### Repro steps
1. Create a C# function that depend on a specific nuget package. Or clone this repo :  https://github.com/GuillaumeSalles/azure-function-sandbox
2. func run {function-name}
#### Expected behavior

Function is executed correctly.
#### Actual behavior

FunctionInvocationException with inner exception CompilationErrorException.

I can provide the full stack-trace if you want.

Don't hesitate if you want more information.

**Comment by lindydonna** [comment]
Might be related to the version of the functions host that is packaged with the CLI (verify that it's 0.5)

**Comment by lindydonna** [comment]
@ahmelsayed To verify that this works with the latest host

**Comment by lindydonna** [comment]
Closing as this issue should now be resolved as NuGet is now shipped with the CLI.
