### ISSUE TITLE
Incorrect times in system logs "timestamp"

### ISSUE THREAD

**Issue by fabiocav** [Azure/azure-webjobs-sdk-script#722]
Timestamps are not correctly set in the events we write to system logs , so we're unable to sort them chronologically. All events have a batch timestamp. Unclear where batching is coming from.

**Comment by mathewc** [comment]
Before adding anything new, we should find out why the existing PreciseTimestamp/Timestamp properties aren't working as expected. These are system provided and should just work. We're not doing any batching or anything on our side.

**Comment by fabiocav** [comment]
Updated the title and description to accurately describe the issue.

**Comment by christopheranderson** [comment]
@fabiocav - What's the status of this?

**Comment by fabiocav** [comment]
Will follow up on this as it seems to be a problem with the way the ETW events are consumed.

**Comment by lindydonna** [comment]
@paulbatum Please advise @pragnagopa on when this change should go out.

**Comment by pragnagopa** [comment]
From MDS documentaion:
PreciseTimeStamp:	​The time the event was logged if the query is not an aggregation. 
TIMESTAMP:  Time rounded to the duration your are pushing the data to storage. Use PreciseTimeStamp for the time the event is logged.

For FunctionsLogs, MDS columns PresciseTimeStamp and TimeStamp have same values. Needs further investigation

**Comment by pragnagopa** [comment]
Verified that TimeStamp in ETW events matches the precise timestamp. Investigating if runtime is doing any kind of batching before writing the events.

**Comment by mathewc** [comment]
I believe we handled this in Zumo logs via a TimeCreated column?

**Comment by pragnagopa** [comment]
Yes. We can do the same for Function logs.

**Comment by pragnagopa** [comment]
67fcd7b5d69ea447a97b06224dcdec014aca73e8 added new column eventCreatedAt. 
Note: New columns will only show up in MDS after checking fix for #885
