### ISSUE TITLE
How to query AzureFunctionsLogTable to get in progress activity?

### ISSUE THREAD

**Issue by stephlocke** [Azure/azure-webjobs-sdk-script#724]
I'd like to be able to query this table directly, without going to the GUI (currently trialling running 10 s2 instances and 100 active functions is tough to review on the portal or kudu). However, this query returns an awful lot of rows. 

```
PartitionKey eq 'I' and FunctionName eq 'functionname' and RawStatus eq 'Running'
```

How should the log table be queried to get the In Progress values?

**Comment by mathewc** [comment]
@MikeStall should be able to help

**Comment by MikeStall** [comment]
We actually have an internal C# client library over these tables which lives in the same repro as the SDK.    I'd encourage using this over raw table queries. 

We have several tables:
- a table of exact function invocations.  (pk="I", rk="function instance guid") 
- a table or recent function invocations (pk="R", rk = includes function name + timestamp) 
We don't have indexes based on function status. 

I'd recommend querying recent functions, and then filtering on status.  Although we just recently adding "Running" status. 

https://github.com/Azure/azure-webjobs-sdk/blob/master/src/Microsoft.Azure.WebJobs.Logging/LogFactory.cs 
  
CloudTable table = ...
ILogReader reader = Microsoft.Azure.WebJobs.Logging.LogFactory.NewReader(table);


And then in ILogReader (https://github.com/Azure/azure-webjobs-sdk/blob/master/src/Microsoft.Azure.WebJobs.Logging/ILogReader.cs ) 

Call GetFunctionDefinitions(), and then call GetRecentFunctionInstances() per each definition.

**Comment by mathewc** [comment]
Note that the **Microsoft.Azure.WebJobs.Logging** library is not strictly internal. We do publish it on our myget feed, instructions here: https://github.com/Azure/azure-webjobs-sdk/wiki/%22Nightly%22-Builds.

**Comment by mathewc** [comment]
Closing this since I don't think there is an issue. Any further issues should be logged in the core SDK repo where the logging component lives [here](https://github.com/Azure/azure-webjobs-sdk/issues).
