### ISSUE TITLE
Host does not restart when renaming a function folder

### ISSUE THREAD

**Issue by davidebbo** [Azure/azure-webjobs-sdk-script#725]
Steps:
- Create new anonymous http function
- Request it from browser
- Using Kudu Console, rename the function folder under `D:\home\site\wwwroot`
- Request it from browser using original name: it still works!
- Request it from browser using new name: 404

Seems we miss the file change notifications and don't restart the host when we should.

**Comment by mamaso** [comment]
Looks to be this condition in the script host onfilechanged handler: we handle a change in directory count (add/delete but not rename)

[`Directory.EnumerateDirectories(ScriptConfig.RootScriptPath).Count() != _directoryCountSnapshot`](https://github.com/Azure/azure-webjobs-sdk-script/blob/059a6c18625ee617f08a0c0c8a162b33e234e5f1/src/WebJobs.Script/Host/ScriptHost.cs#L1096)
