### ISSUE TITLE
First class App Insights integration

### ISSUE THREAD

**Issue by paulbatum** [Azure/azure-webjobs-sdk-script#727]
Today it is possible to integrate Azure Functions with Visual Studio Application Insights by manually referencing the app insights SDK and updating your function code to send metric/event/exception data. Unfortunately this is lots of work, error prone, and still won't capture everything (e.g. if an error occurred while flushing an output, this will occur after execution has left user code and won't be captured by any user catch block).

Ideally, Azure Functions users could turn on first class app insights support, perhaps built on top of a rich host level eventing model as discussed in #281. 

More discussion is required to figure out exactly what behavior needs to be configurable and what should be turned on by default once the customer enables the integration.

**Comment by anthonychu** [comment]
It would be great if a basic version of this can be added soon. For instance, if an instrumentation key is provided (app setting or in host.json), fire function execution events (success/failure, duration) and exceptions into App Insights. That would be a great start. The existing tooling in the functions portal for viewing metrics and exceptions are difficult to use, especially for apps that have a lot of invocations.

AWS Lambda will apparently have something similar soon with their X-Ray integration.

**Comment by murraybauer** [comment]
+1

**Comment by garrardkitchen** [comment]
+1

**Comment by abatishchev** [comment]
+2

**Comment by paulbatum** [comment]
A quick update - we're beginning work on this. Expect more activity on this topic in February.

**Comment by dewanymca** [comment]
Can you please provide an update on this as we are eagerly waiting on this?

**Comment by christopheranderson** [comment]
Great progress. We've got private deployments running with Application Insights and the experience is a huge improvement, very excited. We'll be sharing some information how to use the private bits soon, but hopefully will have it fully integrated in the next 2-3 months.

**Comment by brettsam** [comment]
If you're interested, we have an early preview of Application Insights integration available. See here for details: https://github.com/Azure/Azure-Functions/wiki/App-Insights-Early-Preview

**Comment by mathewc** [comment]
Can this issue be closed now?

**Comment by asvyat** [comment]
Yes, thanks.

Sent from my Windows Phone
________________________________

**Comment by christopheranderson** [comment]
@mathewc - it depends on if we want to wait until it's GA or not. I don't have a strong opinion on how to manage that.

**Comment by brettsam** [comment]
We'll open new issues to address moving AI support to GA.

**Comment by paulbatum** [comment]
I filed a top level issue for tracking the GA here:
https://github.com/Azure/Azure-Functions/issues/388
