### ISSUE TITLE
Remove Blob Lease lock Verbose logs

### ISSUE THREAD

**Issue by mathewc** [Azure/azure-webjobs-sdk-script#728]
We should stop emitting the following Verbose logs:
- core SDK Singleton manager logs when acquiring/renewing leases
- host lock logs emitted by ScriptHost when acquiring/renewing our host level lock

If you turn on verbose logging for ScriptHost (and have a Timer function running) you'll see that actual useful logs are swamped by these logs. They're emitted very frequently.

They really don't add any value. Note that we don't emit any Verbose logs when performing other background tasks like polling blobs, queues, etc., and these lease management operations fall into that same category.

**Comment by mathewc** [comment]
@fabiocav For signoff on my my plan to remove his lease logs as well :) I'm hoping we can get these changes in for the next release, since it will clear up our logs.

**Comment by fabiocav** [comment]
Although it is nice to have the ability to see logs indicating that those components are behaving as expected, those activities fall into a level below the other events currently logged as verbose, which doesn't exist today. For now, I agree that it's a good idea to have those removed.

**Comment by mathewc** [comment]
@brettsam Is this work done? I know you made some changes to core SDK - I don't think those have been pulled in yet?

**Comment by brettsam** [comment]
Not done yet. I just had a bug where it was amazingly useful to have these logs generated. I don't think all of them are necessary but I'll need to go back and figure out which ones we want to keep.

**Comment by mathewc** [comment]
While they were useful for your bug, the do completely swamp our logs :)

**Comment by christopheranderson** [comment]
This is likely not a high risk breaking change, but removing logs that are visible by users is a breaking change. If we're going to do this, I feel we should do it before rc or have a flag to opt in, etc. Won't fight too hard on this, honestly, but just trying to apply a common set of principles.

**Comment by brettsam** [comment]
Changing verbose logs is considered a breaking change? I have a feeling we're going to be tweaking logs like crazy as we get more debugging investigations going (I have some improvements queued up right now, for example, including this one). I don't think we can have people relying on the exact wording, shape, or frequency of the logs we write out because they may change at any time.

**Comment by fabiocav** [comment]
@brettsam I think we just need to move forward with this and yank that log. We're primarily talking about the host lock lease output.

**Comment by mathewc** [comment]
@brettsam No, changing/adding/removing logs is not a breaking change. We can do that whenever we want. I'm fine with just yanking these.

**Comment by brettsam** [comment]
Sorry, I was completely misreading this issue. I thought I was added to it to fix the Core (not Script), which my PR above does, and that Fabio was doing the Script part. I'm not sure why I thought that. I'll tackle this ASAP.

**Comment by brettsam** [comment]
#925 addresses this for script (already merged)
https://github.com/Azure/azure-webjobs-sdk/issues/896 addresses it for core (soon to be merged)

**Comment by mathewc** [comment]
@brettsam This can be closed now, right?
