### ISSUE TITLE
Optimize Host Running Check in request handler

### ISSUE THREAD

**Issue by mathewc** [Azure/azure-webjobs-sdk-script#732]
Repro steps provided by @davidebbo. E.g. provision a Function App with an invalid storage account (e.g. a storage host that doesn't exist). Then make an HttpRequest to the app - requests will time out after 30 seconds, due to our "is host running" logic [here](https://github.com/Azure/azure-webjobs-sdk-script/blob/dev/src/WebJobs.Script.WebHost/Handlers/WebScriptHostHandler.cs#L51).  If the host is in an error state, we should allow this handler to return quickly.

I think we just need to modify the wait check to be `while (!scriptHostManager.IsRunning && scriptHostManager.LastError == null && (timeWaited < _hostTimeoutSeconds))` so we only enter the wait loop on initial startup or when restarting. If we know we're in error, we can return quickly.

**Comment by lindydonna** [comment]
RC if we can get it in

**Comment by soninaren** [comment]
fixed in https://github.com/Azure/azure-webjobs-sdk-script/commit/be59bd0d159e8143a783f878f7f41d734dd076d3
