### ISSUE TITLE
Allow declarative binding with parameters that are within a function

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-webjobs-sdk-script#736]
For example, when output binding is a blob, to be able to specify a binding that contains multiple parts known at the run time of the function. E.g:

`/audits/{receiver}/{date}/{business-message-id}

where

`receiver`, `date`, and `business-message-id` are determined from the payload

**Comment by mathewc** [comment]
I think I've answered this question on SO: http://stackoverflow.com/questions/39855409/how-do-i-use-ibinder-to-perform-dynamic-bindings-in-my-c-sharp-function

**Comment by SeanFeldman** [comment]
There are follow up questions, on the SO thread though 😉

**Comment by mathewc** [comment]
I've clarified that post to address your questions
