### ISSUE TITLE
Add max queue value to wiki host.json page

### ISSUE THREAD

**Issue by stephlocke** [Azure/azure-webjobs-sdk-script#738]
The maximum batch size for a queue that can be used in a host.json file is 32 (the max number of records retrievable from a queue in one call). If the number used is greater than this, errors occur behind the scenes. 

As such it would be good to add a minor addition to the [host.json wiki page](https://github.com/Azure/azure-webjobs-sdk-script/wiki/host.json) to let people know that the default is 16, and the max is 32.

i.e.
```
      // The number of queue messages to retrieve and process in
      // parallel (per job function). The default is 16.
      "batchSize": 16,
```
becomes
```
      // The number of queue messages to retrieve and process in
      // parallel (per job function). The default is 16, and the max is 32.
      "batchSize": 16,
```

**Comment by mathewc** [comment]
Done :)
