### ISSUE TITLE
Using IBinder in conjunction with Storage Blob Output

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-webjobs-sdk-script#739]
This is not documented here and feels that there are conflicting requirements.
Storage Blob Output has a `Path` parameter that is required
![image](https://cloud.githubusercontent.com/assets/1309622/19027080/13ff418c-88ea-11e6-9ce9-df7e67c68dd3.png)
Yet for the binder to specify a file name this is not needed ([sample](http://stackoverflow.com/questions/36428165/generating-names-for-output-blobs-for-an-azure-function)).

Considering there's no documentation on this in Azure Functions documentation, nor there's an inline documentation on the Integration tab/pane (IBinder is not even listed as a Blob output supported type), how should it work?

**Comment by mathewc** [comment]
In `IBinder` scenarios the binding is completely dynamic, driven by imperative code in your function. You should not include a corresponding binding in `function.json` for the I`Binder` parameter. E.g. using `IBinder`, your function can actually bind multiple times iteratively to many different targets and types of targets, so it doesn't map in the same way as regular parameter bindings.

`IBinder` is an advanced feature that we haven't documented well yet (or at all). I agree that doc needs to catch up in this area, and it will.

**Comment by SeanFeldman** [comment]
Thank you @mathewc for clarification. Porting certain functionality from the webjobs world is not always straight forward. This case is one of those. I'll remove the declarative binding and try it.

:+1: for documentation commitment. Would it make sense to keep the issue till the feature is documented? Perhaps there's a `doco` label for such issues?

cc @christopheranderson

**Comment by mathewc** [comment]
Likely we'll close this issue and open a doc bug in the right repo - we'll decide in triage. We only want to keep open issues in this repo for things that are actionable in this repo.

**Comment by SeanFeldman** [comment]
@mathewc sounds fair. Perhaps linking this issue from then new one in the appropriate repo? That way could track it. Thank you.

**Comment by mathewc** [comment]
Moved to https://github.com/Azure/Azure-Functions/issues/2
