### ISSUE TITLE
Azure Function with Timer trigger not firing

### ISSUE THREAD

**Issue by valeriob** [Azure/azure-webjobs-sdk-script#740]
I've configured a function with a timer trigger "0 30 11 * * *"
it just does not fire when it should

![azure function](https://cloud.githubusercontent.com/assets/1522516/19033937/3b8d6ab8-8961-11e6-943e-31d787149599.PNG)

**Comment by brettsam** [comment]
Are you running this in Dynamic or Classic mode? If Classic, do you have 'Always On' configured?

**Comment by valeriob** [comment]
I dont know what Dynamic is, but if you refer to the Managed Pipeline version i'm in Integrated mode.
And i can't turn Always on ON

![image](https://cloud.githubusercontent.com/assets/1522516/19043253/b0d32b7c-898f-11e6-91ef-71663699b525.png)

**Comment by brettsam** [comment]
*Dynamic* plan documentation can be found here: https://azure.microsoft.com/en-us/documentation/articles/functions-scale/#dynamic-service-plan
For *Classic* plans, 'Always On' is only available in Basic or Standard mode. Some docs on that: https://azure.microsoft.com/en-us/documentation/articles/web-sites-configure/ 

At this time, you can only choose between *Dynamic* and *Classic* plans at app-creation time:
![image](https://cloud.githubusercontent.com/assets/1089915/19043549/77692746-8945-11e6-869f-5f34abf0a44d.png)

**Comment by valeriob** [comment]
Ok i'll check on it, but it's quite confusing that you can enable a timer trigger and it does not work...

**Comment by valeriob** [comment]
Ouch the price !
That's a real shame, basic starts from 50€ a month, like a vm, to just run a task 2 seconds every day it's not very convenient compared to aws lambda

**Comment by brettsam** [comment]
A *Dynamic* plan is what you're looking for, then -- you only pay when it runs. See the link above for the explanation.

**Comment by valeriob** [comment]
Ok i guess i'll have to create the functions again, thanks !

**Comment by davidebbo** [comment]
Yes, Dynamic is definitely what you want, and the cost will be minimal (most likely zero if you run once a day).

**Comment by onionhammer** [comment]
This is happening for me; there is no option in application settings for 'always on', the function is enabled, the schedule is set for every 15 minutes (0 */15 * * * *), but the function hasnt run for 15 hours.

Note this used to work ;)

**Comment by davidebbo** [comment]
@onionhammer the issue above related to using this in non-Consumption plan, and not having Always On enabled. If you are seeing this in Consumption, it should just work. If it doesn't please open a separate issue, and include your Function App name, directly or [indirectly](https://github.com/projectkudu/kudu/wiki/Reporting-your-site-name-without-posting-it-publicly). Also, include a sample UTC time where you expected it to fire and it didn't.
