### ISSUE TITLE
$return not working for C# HttpFunctions

### ISSUE THREAD

**Issue by mathewc** [Azure/azure-webjobs-sdk-script#741]
Try to map the http response of a standard C# http function as follows:

``` json
{
    "bindings": [
        {
            "type": "httpTrigger",
            "name": "req",
            "direction": "in",
            "methods": [ "get" ]
        },
        {
            "type": "http",
            "name": "$return",
            "direction": "out"
        }
    ]
}
```

You'll get an error:

{
  "Message": "An error has occurred.",
  "ExceptionMessage": "'System.Threading.Tasks.Task HttpTrigger-CSharp(System.Net.Http.HttpRequestMessage, Microsoft.Azure.WebJobs.Host.TraceWriter, Microsoft.Azure.WebJobs.ExecutionContext, System.Net.Http.HttpResponseMessage ByRef)' can't be invoked from Azure WebJobs SDK. Is it missing Azure WebJobs SDK attributes?",
  "ExceptionType": "System.InvalidOperationException",
  "StackTrace": "   at Microsoft.Azure.WebJobs.JobHost.ResolveFunctionDefinition(MethodInfo method, IFunctionIndexLookup functionLookup)\r\n   at Microsoft.Azure.WebJobs.JobHost.<CallAsyncCore>d__a.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()\r\n   at Microsoft.Azure.WebJobs.Script.ScriptHost.<CallAsync>d__49.MoveNext() in C:\code\Git\Azure\azure-webjobs-sdk-script\src\WebJobs.Script\Host\ScriptHost.cs:line 169\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()\r\n   at Microsoft.Azure.WebJobs.Script.WebHost.WebScriptHostManager.<HandleRequestAsync>d__20.MoveNext() in C:\code\Git\Azure\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\WebScriptHostManager.cs:line 104\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n

**Comment by brettsam** [comment]
@fabiocav @mathewc -- What do you guys think we should do here? It looks like HttpTriggers have this notion of an `IResultProcessingBinding` that no other triggers use. It looks like that was to handle this unique return-value case that only DotNet+Http supported. So I can't write an HttpTrigger like:

    public static void Run(HttpRequestMessage req, out HttpResponseMessage res, TraceWriter log)

My first thought was to remove this special-casing for DotNet+Http now that there's a built-in way to handle `$return`. But that'd break everybody that's not using `$return` today.

Should we just ignore the parameter name completely for DotNet+Http? It doesn't seem like we pay attention to it anywhere.

**Comment by fabiocav** [comment]
The above should still work. Although currently only used by HTTP, the `IResultProcessingBinding` mechanism is not bound and/or specific to HTTP, so we're not really special casing HTTP there.

It would be pretty simple to either bypass the processing when $return is mapped or for the handler to be smart enough to know it shouldn't process the return if itself was mapped to $return. 
I would lean towards the second option, as we've already seen a couple of scenarios where it is useful to have both.

Btw, I'm happy to take that on as I'm familiar with this logic and this seems more important than what I currently have on my backlog 😏

**Comment by brettsam** [comment]
I wasn't able to get an `out HttpResponseMessage` to work -- I get `Cannot bind parameter 'res' to type HttpResponseMessage&. Make sure the parameter Type is supported by the binding.`

`IResultProcessingBinding` looks like it's only used by HTTP. That's what I meant by 'special-cased'. If it was removed for some reason, it wouldn't affect other bindings.

Yeah, do you want to take it? The idea was for me to get my hands into some of this stuff, but I'm getting pulled elsewhere at the moment :-)

**Comment by fabiocav** [comment]
Happy to look at this.

**Comment by mathewc** [comment]
Hopefully we can get rid of the IResultProcessingBinding concept

**Comment by fabiocav** [comment]
We'll have to think about how we want to approach removing that interface/logic as it would be a breaking change. 
We'd likely also have to turn the HTTP output binding into a proper binding.
