### ISSUE TITLE
"Getting started" dev guide?

### ISSUE THREAD

**Issue by isaacabraham** [Azure/azure-webjobs-sdk-script#742]
Is there a getting started guide anywhere to getting the code in here running locally? I've tried hacking things together so that I can test out bits locally - but before I start spending more time on this, is there a simple guide? I've tried getting the console host to work, and gotten relatively far but not all the way - clearly this must be possible.

I'd ideally like to test out calling functions arbitrarily if possible but through "real" triggers if necessary. 

Cheers

**Comment by fabiocav** [comment]
Most of the information available is currently found in the Wiki: https://github.com/Azure/azure-webjobs-sdk-script/wiki

**Comment by mathewc** [comment]
Have you checked here: https://github.com/Azure/azure-webjobs-sdk-script/wiki? That page is intended to have all that you need, though it might be out of date in places. Let us know what needs to be improved :)

**Comment by isaacabraham** [comment]
OK - thanks for that. The problem I had was that I was pointing to a script subfolder, which doesn't have a host.json by default. The SDK seems to create an empty host file, but this then silently fails because there's no id property specified in the host.json. Even then, it didn't pick up the function. However, adding the folder to the list of functions in the original host.json included in the repo then did work.

**Comment by isaacabraham** [comment]
Also - placing a project.json in a function folder fails by default for me because kudu isn't available on the local machine (C:\Program Files (x86)\siteextensions\kudu) in ``PackageManager.ResolveNuGetPath()``, although it seems to just silently fail (in terms of console output etc.).

**Comment by christopheranderson** [comment]
Closing this since we have something to start with - feel free to file additional issues as you find them.
