### ISSUE TITLE
Any thoughts of a stable release roadmap?

### ISSUE THREAD

**Issue by yvele** [Azure/azure-webjobs-sdk-script#746]
Have you any ideas on when the first sable/production ready Azure Function will be officially released❓

**Comment by christopheranderson** [comment]
We're shooting for this year. Wrapping up features and getting our docs/marketing stuff in shape now.

**Comment by yvele** [comment]
@christopheranderson Thanks for your response.. Can we keep this issue open and us it :

- For users to ask questions about the first stable release
- For Azure team to keep us updated

Thanks

**Comment by mathewc** [comment]
Closing this issue - we only want to use issues in this repo to track actual work items, not as a way for release notifications, etc. @christopheranderson can comment on the best place to receive notificaitions, info, etc..
