### ISSUE TITLE
Need to move Table binding into core WebJobs SDK

### ISSUE THREAD

**Issue by mathewc** [Azure/azure-webjobs-sdk-script#753]
To get cross language support, we have a Table binding in this repo [here](https://github.com/Azure/azure-webjobs-sdk-script/blob/dev/src/WebJobs.Script/Binding/TableBinding.cs) that bridges all the required functionality to the core SDK table binding. Basically it is mapping `IAsyncCollector<JObject>` which is what script wants to deal with to `IAsyncCollector<ITableEntity>` which is what core SDK supports.

We need to move all this into the core SDK as first class JObject support. Table is the last example of a non first-class binding. This will enable us to remove a lot of code from script, and will normalize things so Table is treated just like all our other extension bindings. Success will be being able to remove the script binding, and adding table to our existing script binding provider [here](https://github.com/Azure/azure-webjobs-sdk-script/blob/dev/src/WebJobs.Script/Binding/WebJobsCoreScriptBindingProvider.cs#L59).

I think this is **important to do for GA** because it might result in minor breaking changes, so better to do now.

**Comment by MikeStall** [comment]
I have a fix is underway. 
I'm using the new binding factory  approach that we used if [Queue]. 
I'm just using it to add new bindings, not replace the exisitng [Table] bindings. A lot of subtle behavior there. I filed https://github.com/Azure/azure-webjobs-sdk/issues/887  to track the full swap over.

**Comment by mathewc** [comment]
What do you mean by "add new bindings"? I don't like the idea of having a duplicate public binding or new table attribute type.

**Comment by MikeStall** [comment]
Right - I should have said "new binding rules".  Same attribute, staying consistent. Just supporting:
   [Table] IAsyncCollector<JObject>
   [Table] JObject
