### ISSUE TITLE
C# function changes not recognised after save

### ISSUE THREAD

**Issue by martin195** [Azure/azure-webjobs-sdk-script#756]
Please provide a succinct description of the issue.
#### Repro steps

Provide the steps required to reproduce the problem
1. Use off-the-shelf C# function (mode: standard, auth: function)
2. Added id & start GET parameters
#### Expected behavior

After any change to the code, change to be reflected in output
#### Actual behavior

Changes not reflected. Same results in both function test utility and direct browser request.
#### Known workarounds

Create a new function for every change
#### Related information

Browser unrelated - tested same function with Chrome, Firefox & Edge.

Although updated code is shown, save does not appear to compile the changes.

Edit: Changing the memory allocation does force a recognition of changes.

**Comment by christopheranderson** [comment]
Do those steps repro everytime? Could you also share your site name with us via this [link] (https://github.com/projectkudu/kudu/wiki/Reporting-your-site-name-without-posting-it-publicly) and UTC timestamp of a repro?

**Comment by martin195** [comment]
The app is in the same account as this dummy account: c4test748. I don't have an exact timestamp, the event occurred around 10/10/2016 10:30 BST. Since the clearing the issue by changing the memory allocation, we haven't been able to replicate the issue.

**Comment by davidebbo** [comment]
Ok, so that's 10/10/2016 9:30 UTC, right? I looked at the logs one hour before and after (internal log link for other Azure dev reference: https://jarvis-west.dc.ad.msft.net/E96C0AD9).

In that time range, I see a fair number of changes to the function, some resulting in successful compilation and some in compile errors.

So it doesn't seem to be a case of failing to detect changes to the files.

@martin195 does that match what you observed/did at that time?

Here are the specific change events (and remember these are UTC and not BST):

```
10-10-2016 08:36:59
Script for function 'Netcode' changed. Reloading.
run.csx(9,62): error CS1002: ; expected

10-10-2016 08:39:05
Script for function 'Netcode' changed. Reloading.
Compilation succeeded.

10-10-2016 09:06:38
Script for function 'Netcode' changed. Reloading.
Compilation succeeded.

10-10-2016 09:07:09
Script for function 'Netcode' changed. Reloading.
run.csx(22,26): error CS0103: The name 'start' does not exist in the current context

10-10-2016 09:08:00
Script for function 'Netcode' changed. Reloading.
Compilation succeeded.

10-10-2016 09:13:09
Script for function 'Netcode' changed. Reloading.
Compilation succeeded.

10-10-2016 09:13:26
Script for function 'Netcode' changed. Reloading.
Compilation succeeded.

10-10-2016 09:40:29
Script for function 'Netcode' changed. Reloading.
Compilation succeeded.

10-10-2016 10:13:35, 10-10-2016 10:14:16, 10-10-2016 10:20:48
Script for function 'Netcode' changed. Reloading.
Compilation succeeded.

10-10-2016 10:22:08
Script for function 'Netcode' changed. Reloading.
run.csx(2,1): error CS0006: Metadata file 'System.Web.Http' could not be found
run.csx(12,23): error CS0103: The name 'Request' does not exist in the current context

10-10-2016 10:22:42
Script for function 'Netcode' changed. Reloading.
run.csx(6,22): error CS1002: ; expected
run.csx(13,23): error CS0103: The name 'Request' does not exist in the current context

10-10-2016 10:26:15
Script for function 'Netcode' changed. Reloading.
run.csx(7,22): error CS1002: ; expected
run.csx(2,1): error CS0006: Metadata file 'System.Collections.Specialized' could not be found
run.csx(31,5): error CS0246: The type or namespace name 'NameValueCollection' could not be found (are you missing a using directive or an assembly reference?)
run.csx(31,42): error CS0246: The type or namespace name 'NameValueCollection' could not be found (are you missing a using directive or an assembly reference?)

10-10-2016 10:26:33
Script for function 'Netcode' changed. Reloading.
run.csx(8,22): error CS1002: ; expected

10-10-2016 10:27:03
Script for function 'Netcode' changed. Reloading.
Compilation succeeded.

10-10-2016 10:27:43
Script for function 'Netcode' changed. Reloading.
Compilation succeeded.
```

**Comment by davidebbo** [comment]
If you see this again, can you capture the invocation ID of the execution that's running stale code? Basically, grab whatever you see in the log for that one run. That will help us better correlate. Thanks!

**Comment by ShayanZafar** [comment]
I still get this problem. I resolved it by restarting the Function Application using Azure UI.
