### ISSUE TITLE
Validate that ~x.x.x functions properly

### ISSUE THREAD

**Issue by christopheranderson** [Azure/azure-webjobs-sdk-script#758]
We need to test that the ~x.x.x version choosing logic behaves as anticipated.

Proposed user scenarios to test against:
1. ~x should keep me on the latest x._._ build
   - ~1 app setting -> available versions [0.7.1, 1.1.0, 1.1.1, 1.2.0, 1.2.1, 2.0.0] -> choose 1.2.1
   - ~0 app setting -> available versions [0.7.1, 1.1.0, 1.1.1, 1.2.0, 1.2.1, 2.0.0] -> choose 0.7.1
   - ~2 app setting -> available versions [0.7.1, 1.1.0, 1.1.1, 1.2.0, 1.2.1, 2.0.0] -> choose 2.0.0
2. ~x.y should keep me on the latest x.y._ build
   - ~1.1 app setting -> available versions [0.7.1, 1.1.0, 1.1.1, 1.2.0, 1.2.1, 2.0.0] -> choose 1.1.1
3. ~x.y.z should keep me on the x.y.z build 
   - 1.1.0 app setting -> available versions [0.7.1, 1.1.0, 1.1.1, 1.2.0, 1.2.1, 2.0.0] -> choose 1.1.0

**Comment by davidebbo** [comment]
To save time, we should focus on (1), as that's where we'll be after 1.x. (2) is what we already use, and (3) is essentially useless.

**Comment by christopheranderson** [comment]
Agreed (1) is most important.

(3) is potentially useful if we ever have a customer impacting change in a patch version, accidentally. I hope we don't have to use it. I'm not dug in that we have to test it, just enumerating the scenarios that exist.

I'll leave it up to you on what testing is sufficient or not. I just need to know these scenarios work, especially (1).

**Comment by davidebbo** [comment]
On second read, your ~1.1.0 example is incorrect. It should match 1.1.1 and not 1.1.0. Those range syntaxes can be tricky! See https://github.com/npm/node-semver

Here, I think you're looking for an exact match, and you can simply say 1.1.0 (no tilde). And I know that case works as we use it frequently for Kudu.

**Comment by davidebbo** [comment]
I verified all the scenarios and it works great.

The only bug I found is that ~1.1.0 ends up matching 1.1.0 and not 1.1.1, which is what you initially thought it should do (but is not correct per spec). Anyway, it's not an interesting scenario, so not a tangible concern.

So we're good to go!
