### ISSUE TITLE
Split Function tests into Unit and Functional 

### ISSUE THREAD

**Issue by MikeStall** [Azure/azure-webjobs-sdk-script#769]
Split WebJobs.Script.Tests into 2 separate test dlls: 
1.  “Unit tests” – that  work with default VS2015 install and only require an azure storage account. (arguably that's not a 100% pure unit test; but I think it's a practical concession)
2.  “End-to-end tests” that require the all the external setup here:  https://github.com/Azure/azure-webjobs-sdk-script/wiki 

SDK has a similar split. 
The external setup is over a dozen steps, each requiring some degree of domain knowledge across a large variety of domains.  It also leads to a lot of false negatives. And it will only get worse as we get more integrations & languages.  It’d be nice to have some core set of tests that should always work.  

It also encourages some good behavior:
1.  Unit tests should always be 100% no excuses. There’s no external setup / false negatives that would cause us to lower expectations. That means we get some degree of bedrock.  
2.  It encourages us to mock and make things more testable so that they show up in Unit test instead of End-2-end.  For example, ApiHub has a great mode that lets you mock on file system (easy) instead of requiring a real live Dropbox connection (hard). So we could actually get some ApiHub tests into the Unit test portion.

**Comment by mathewc** [comment]
As part of this work, we should also create a rational folder structure and naming conventions for tests. Currently it's pretty haphazard.

**Comment by mathewc** [comment]
This is done now.
