### ISSUE TITLE
CLI: don't require "id" property in host.json

### ISSUE THREAD

**Issue by lindydonna** [Azure/azure-webjobs-sdk-script#776]
The CLI currently requires an "id" attribute in host.json, it should instead initialize the host with a stable host ID (machine name, for instance). This is is important for the Visual Studio tooling to work correctly.

**Comment by mathewc** [comment]
It can't be a random ID - it needs to be a stable ID since a lot of storage artifacts behind the scenes are tied to it.

**Comment by ahmelsayed** [comment]
I'm using `$"{Environment.MachineName}-{Path.GetFileName(Environment.CurrentDirectory)}"`
