### ISSUE TITLE
Can't build solution under VS2015 Update 3 Community

### ISSUE THREAD

**Issue by uhfath** [Azure/azure-webjobs-sdk-script#778]
Followed tutorial from here: https://azure.microsoft.com/en-us/documentation/articles/functions-run-local/
Cloned the repo (tried "dev" and "master" branches, and different commits from them), opened solution, tried to build it:

> Severity  Code    Description Project File    Line    Suppression State
> Error   CS1061  'ErrorRecord' does not contain a definition for 'ScriptStackTrace' and no extension method 'ScriptStackTrace' accepting a first argument of type 'ErrorRecord' could be found (are you missing a using directive or an assembly reference?) WebJobs.Script  E:\Projects\azure-webjobs-sdk-script-dev\src\WebJobs.Script\Description\PowerShell\PowerShellFunctionInvoker.cs 186 Active
> Error   CS1729  'RuntimeException' does not contain a constructor that takes 3 arguments    WebJobs.Script  E:\Projects\azure-webjobs-sdk-script-dev\src\WebJobs.Script\Description\PowerShell\PowerShellFunctionInvoker.cs 69  Active
> Error   CS1061  'ErrorRecord' does not contain a definition for 'ScriptStackTrace' and no extension method 'ScriptStackTrace' accepting a first argument of type 'ErrorRecord' could be found (are you missing a using directive or an assembly reference?) WebJobs.Script  E:\Projects\azure-webjobs-sdk-script-dev\src\WebJobs.Script\Description\PowerShell\PowerShellFunctionInvoker.cs 186 Active
> Error   CS0006  Metadata file 'E:\Projects\azure-webjobs-sdk-script-dev\src\WebJobs.Script\bin\Debug\Microsoft.Azure.WebJobs.Script.dll' could not be found WebJobs.Script.WebHost  E:\Projects\azure-webjobs-sdk-script-dev\src\WebJobs.Script.WebHost\CSC 1   Active
> Error   CS0006  Metadata file 'E:\Projects\azure-webjobs-sdk-script-dev\src\WebJobs.Script\bin\Debug\Microsoft.Azure.WebJobs.Script.dll' could not be found WebJobs.Script.Host E:\Projects\azure-webjobs-sdk-script-dev\src\WebJobs.Script.Host\CSC    1   Active
> Error   CS0006  Metadata file 'E:\Projects\azure-webjobs-sdk-script-dev\src\WebJobs.Script.WebHost\bin\Microsoft.Azure.WebJobs.Script.WebHost.dll' could not be found   WebJobs.Script.Tests    E:\Projects\azure-webjobs-sdk-script-dev\test\WebJobs.Script.Tests\CSC  1   Active
> Error   CS0006  Metadata file 'E:\Projects\azure-webjobs-sdk-script-dev\src\WebJobs.Script\bin\Debug\Microsoft.Azure.WebJobs.Script.dll' could not be found WebJobs.Script.Tests    E:\Projects\azure-webjobs-sdk-script-dev\test\WebJobs.Script.Tests\CSC  1   Active
> Error       The command ""E:\Projects\azure-webjobs-sdk-script-dev\tools\NuGet.exe" pack "obj\Debug\WebJobs.Script.nuspec" -p Configuration=Debug -o "bin\Debug\NuGet" -Properties "NuGetPackageId=Microsoft.Azure.WebJobs.Script;NuGetPackageVersion=1.0.0-beta1;PackageEULA=http://www.microsoft.com/web/webpi/eula/aspnetcomponent_rtw_enu.htm;WebJobsPackageVersion=1.0.0-beta1" -NoPackageAnalysis" exited with code 1.    Packages            

Also tried to clean and rebuild. Same results. The nuget packages got restored (at least it said so), but nothing else happens.
Is there some step that is needed to be taken? Or perhaps i read the docs wrong?
Specifically installed Azure SDK from the link in the docs.

**Comment by lindydonna** [comment]
We'll investigate why the build doesn't just work. However, the local development article needs to be updated, there's a much easier way now, using the Azure Functions CLI. Documentation is still pending. To install, do the following:

npm install -g azurefunctions
npm install -g yo
npm install -g generator-azurefunctions

You need to install the last two, due to this bug: #790 

There is some minimal documentation here: https://www.npmjs.com/package/azurefunctions, more is coming soon.

**Comment by uhfath** [comment]
Thanks. I already tried using Azure Functions CLI.
It also didn't work out-of-the-box, but was much easier to fix (just changed a few paths).

**Comment by fabiocav** [comment]
@uhfath thanks for your patience with this. We've been heads down working on some critical features and hope to spend time improving the out of the box dev experience for contributors and people playing with the bits soon.

**Comment by lindydonna** [comment]
@uhfath We've updated the Functions CLI, it's now the NPM package [azure-functions-cli](https://www.npmjs.com/package/azure-functions-cli). If you find any bugs, please file them in this repo and add a "CLI: " prefix. Thanks!

**Comment by uhfath** [comment]
Nice! Thanks!
I'll sure take a look.
