### ISSUE TITLE
Timeout too short when debugging azure functions via cli

### ISSUE THREAD

**Issue by ZainRizvi** [Azure/azure-webjobs-sdk-script#788]
Timeout too short when debugging azure functions via cli
#### Repro steps

Launch an azure function in debug mode and pause the function before it finishes executing (use a breakpoint or something).  Very soon the cli will time out with the error:

```
C:\Code\FunctionsTest\node_modules\.bin>func run testFunction --debug
Error: A task was canceled.
You can run the same command passing --cli-dev and report an issue on https://github.com/azure/azure-webjobs-sdk-script/issues
```
#### Expected behavior

The cli keeps waiting for the function to return
#### Actual behavior

The cli times out saying "a task was canceled"
#### Known workarounds

Debug the function and return execution really fast.
#### Related information
- Programming language used: CSharp

**Comment by lindydonna** [comment]
This is not specific to the CLI, assigning to @brettsam

**Comment by christopheranderson** [comment]
@ZainRizvi - when you say "very soon", do you mean seconds or minutes?

**Comment by lindydonna** [comment]
@brettsam Is this related to the 5 minute timeout?

**Comment by lindydonna** [comment]
@ahmelsayed Please work with @brettsam to test his fix.

**Comment by brettsam** [comment]
Yeah, it's related to the timeout. We have a `timeoutWhileDebugging` flag that is hard-coded to `true`. I've made that `false` but wasn't able to figure out how to generate a CLI build to test it out. @ahmelsayed -- any pointers?

**Comment by ZainRizvi** [comment]
@christopheranderson I didn't time it but it seemed to be somewhere between 30 seconds to a minute. 

"Very soon" meant that the console would timeout before I was able to complete a reasonable debugging session, so I wouldn't be able to see the output of my session on the console.
