### ISSUE TITLE
Let users update secrets like connection strings when using the cli

### ISSUE THREAD

**Issue by ZainRizvi** [Azure/azure-webjobs-sdk-script#794]
Feature request:

Please allow us the update secrets like connection strings to custom values using the cli.  That'll let us use one set of credentials when debugging/developing our function, and a different set once we publish them to prod.

**Comment by paulbatum** [comment]
@ahmelsayed Isn't this already possible with the set command?

**Comment by lindydonna** [comment]
@ZainRizvi I'm also going to create an issue to allow the .secrets file to be edited un-encrypted. I also have a CLI proposal that I'll send to you for your feedback.

**Comment by ZainRizvi** [comment]
@lindydonna Nice. Sounds like you're trying to do something similar to the [.Net Core Secret Manager](http://docs.asp.net/en/latest/security/app-secrets.html#secret-manager). 

And if that's not what you're planning, the Secret Manager is a pretty good implementation of this feature :)

It saves the secrets in an unencrypted json file, and there's also a command line interface to update the secrets

**Comment by lindydonna** [comment]
@ZainRizvi Nice pointer, that sounds like a good approach.

**Comment by lindydonna** [comment]
Included in this issue: https://github.com/Azure/azure-webjobs-sdk-script/issues/638
