### ISSUE TITLE
When running csx locally, breakpoints require "require source to match" be disabled

### ISSUE THREAD

**Issue by lindydonna** [Azure/azure-webjobs-sdk-script#796]
There's a bug that repros only when a BOM is not present in a .csx file.

Steps to repro:

1. Install azurefunctions CLI:

     - npm install -g azurefunctions
     - npm install -g yo
     - npm install -g generator-azurefunctions

2. Create new function `Http1`. Use C# HTTP trigger

   - mkdir MyFunction
   - cd MyFunction
   - func init
   - func new

3. Run in debugger

   - func run Http1 --debug

**Comment by fabiocav** [comment]
This issue can also be observed in remote debugging scenarios
