### ISSUE TITLE
Release deployment on Azure Portal

### ISSUE THREAD

**Issue by michaelz84** [Azure/azure-webjobs-sdk-script#798]
Two days ago Functions 0.7.10532 (1.0.0-beta1-10532) was released. Could you please provide an estimate when the Azure Portal will be updated to this version? Currently 0.6 is the highest version available.

In general:
Is it possible to retrieve the detailed version number which is used by the Azure Portal?
Is it possible to test a new azure-webjobs-sdk-script release within the Azure Portal which is not yet officially deployed?

Thanks for your amazing work on Azure Functions!

**Comment by mathewc** [comment]
Sometime early next week we'll update the portal. We have final testing to do for the new portal updates to handle the new http routing support. There's nothing stopping you from moving to the new runtime version now if you wish - however if you use the new http routing, the URI for http functions shown in the portal won't be correct until the portal UI updates. That won't affect the actual runtime functionality of your http functions though - they'd still work.

You can move yourself forward using the instructions [here](https://github.com/Azure/azure-webjobs-sdk-script/wiki/Function-Runtime-Versioning).

**Comment by michaelz84** [comment]
@mathewc, thanks a lot for your quick reply!

I just tried to follow your instructions and it works now for me. I already switched the App Settings to ~0.7 but was confused that the UI stated that 0.6 was the lastest available version.

Just tested the routing and it works as described for version 0.7.
Thanks a lot! :)
