### ISSUE TITLE
Add project.lock.json file to .gitignore

### ISSUE THREAD

**Issue by christopheranderson** [Azure/azure-webjobs-sdk-script#800]
If the lock file is committed, it won't trigger a nuget restore. We should include ignoring it in the .gitignore.

**Comment by fabiocav** [comment]
Yes. This is by design. @lindydonna captured the .gitignore item in her latest proposal and *might* already have an issue (Donna?)

**Comment by lindydonna** [comment]
Duplicate of https://github.com/Azure/azure-webjobs-sdk-script/issues/775
