### ISSUE TITLE
Warn before overwriting any files with func init

### ISSUE THREAD

**Issue by christopheranderson** [Azure/azure-webjobs-sdk-script#801]
When you `func init`, it will overwrite any existing files (such as gitignore). We should warn before we overwrite existing files.

**Comment by paulbatum** [comment]
Should we just skip any overwrite operations? Are there scenarios where we would want an overwrite to occur?

**Comment by ahmelsayed** [comment]
I update the behavior to always skip if file exists. Also to check if we are already in a git repo before init`ing a new one
