### ISSUE TITLE
Make it easy to get function working directory and other context

### ISSUE THREAD

**Issue by fabiocav** [Azure/azure-webjobs-sdk-script#803]
Today, getting environment information in managed functions (like the current directory) is very cumbersome. We need to investigate a way to make this more convenient.

**Comment by lindydonna** [comment]
+1 on this. I had to use some really hacky workarounds in order to write code that works both locally with the CLI and on Azure. I ended up creating an environment variable SITE_PATH where I set to "." when running locally and site\\wwwroot on Azure.

**Comment by alrod** [comment]
Customer asking for function name:
https://social.msdn.microsoft.com/Forums/en-US/aa67dbf0-7e02-46b1-80a1-27d278b14ec0/simple-way-to-get-name-of-function-app?forum=AzureFunctions

**Comment by fabiocav** [comment]
@lindydonna @christopheranderson I'm clearing the milestone on this so we can chat about this item on the next triage meeting.

**Comment by davidebbo** [comment]
Dup of #415?

**Comment by davidebbo** [comment]
Another customer asking for function name [here](https://social.msdn.microsoft.com/Forums/azure/en-US/6a03750d-ea58-4b42-b343-466a83aadb8a/how-to-get-a-function-name-on-the-runtime-in-c-function?forum=AzureFunctions).
