### ISSUE TITLE
Add routePrefix documentation (update host.json sample in wiki)

### ISSUE THREAD

**Issue by yvele** [Azure/azure-webjobs-sdk-script#804]
Thank you for [0.7](https://github.com/Azure/azure-webjobs-sdk-script/releases/tag/v1.0.0-beta1-10532) new release with custom routes ✨ 

One of the new features is :

> allow for the default "api" route prefix to be customized or completely removed via host.json

Please update [host.json sample in wiki](https://github.com/Azure/azure-webjobs-sdk-script/wiki/host.json) with :

```json5
{
    "http": {
        // The default value is "api".  An empty string will completely remove the prefix.
        "routePrefix": "api"
    }
}
```

Sources :

- Sample: https://github.com/Azure/azure-webjobs-sdk-script/blob/dev/sample/host.json
- Empty string: https://github.com/Azure/azure-webjobs-sdk-script/issues/373#issuecomment-255604004

**Comment by mathewc** [comment]
I'm planning on writing up some detailed instructions for http in general in our wiki. I'll address this as well when I do that.

There are some other host level knobs that we've added recently that aren't included in our existing host.json/function.json doc. I'll work to address those as well.

**Comment by mathewc** [comment]
I've created a wiki page [here](https://github.com/Azure/azure-webjobs-sdk-script/wiki/Http-Functions), and I also updated the host.json wiki page.

**Comment by yvele** [comment]
Awesome @mathewc ! Thanks 👍

**Comment by wesmc7777** [comment]
That [wiki page](https://github.com/Azure/azure-webjobs-sdk-script/wiki/Http-Functions) describes updating function.json to customize routePrefix.

Pretty sure this should be host.json instead.  This was the only way I was able to get it to work.  Thanks

**Comment by mathewc** [comment]
Oops, fixed. Thanks:)
