### ISSUE TITLE
The ErrorTrigger firing too many times, when multiple messages are received.

### ISSUE THREAD

**Issue by chris-mason-zuto** [Azure/azure-webjobs-sdk-script#806]
If a single message is sent., the expected behaviour happens.  The error trigger is fired once per sent message. 

If I send 10 messages at the same time, the error trigger is fired 3 times per message. Total 30 times. 

1 message = 1 ErrorTrigger fired.
2 messages =  6 ErrorTriggers fired
5 messages = 15 ErrorTriggers fired
10 messages = 30 ErrorTriggers fired

#### Repro steps
Using Service Bus explorer send 10 messages at once.

#### Expected behavior
The ErrorTrigger should be fired 10 times.

#### Actual behavior
The ErrorTrigger is fired 30 times.

#### Related information 
I have tried version 1.0.1 and 2.0.0-beta1 WebJobs.extensions.
I have tried numerous different message amounts and it always multiplys by 3.
I have turned off retrying of failed messages.
The correct number of messages are going in and the correct amount are going on the dead letter queue.
The EventSubscriptionToNotificationTopic method is called the correct number of times.

If I send one message:
Exception thrown: 'System.Exception' in WebJob.exe
Error 94591d32-e94f-4232-ae60-a643af47fc22

If i send 1 message then straight away another message:
Exception thrown: 'System.Exception' in WebJob.exe
Error 020c1fb6-614b-46fb-8077-d5286db19577

Exception thrown: 'System.Exception' in WebJob.exe
Error 966514bb-933d-44ce-af31-28435d84050d
Error 3e802d0b-e9c2-45f8-81b3-c11fce93dc2d
Error c1a8d762-0336-4c2b-9833-0f74c370ef92

The second message has fired ErrorTriggert 3 times.

Executing: 'WebJob.EventSubscriptionToNotificationTopic' - Reason: 'New ServiceBus message detected on 'eventtopic/Subscriptions/NotificationSub'.'
Executed: 'ErrorTrigger.HandleError' (Succeeded)
Executing: 'ErrorTrigger.HandleError' - Reason: 'Error trigger fired'
Executed: 'ErrorTrigger.HandleError' (Succeeded)
Executing: 'ErrorTrigger.HandleError' - Reason: 'Error trigger fired'
Executed: 'ErrorTrigger.HandleError' (Succeeded)
Executing: 'ErrorTrigger.HandleError' - Reason: 'Error trigger fired'

If i remove the ErrorTrigger and replace it witha  try catch then i get the correct number of erros logged.

Exception thrown: 'System.Exception' in WebJob.exe
Error 6203dc14-7294-48cb-b7ae-84a1896c9c0a
Exception thrown: 'System.Exception' in WebJob.exe
Error 9cf0c0c6-d00b-4967-9765-dbfb66e9ab02
Exception thrown: 'System.Exception' in WebJob.exe
Error 7fd1d966-00f8-41ba-afd7-62e5ac9008ac

Sample code attached.
[Code.txt](https://github.com/Azure/azure-webjobs-sdk-script/files/547531/Code.txt)

**Comment by paulbatum** [comment]
ErrorTrigger lives in the extensions repo. Moved:
https://github.com/Azure/azure-webjobs-sdk-extensions/issues/166
