### ISSUE TITLE
Include more assemblies in host by default

### ISSUE THREAD

**Issue by paulbatum** [Azure/azure-webjobs-sdk-script#81]
I shouldn't need to do a private binary drop of Microsoft.Azure.WebJobs.dll and Newtonsoft.Json.dll to be able to use these from a function. Can we include these two by default?

**Comment by davidebbo** [comment]
The runtime already uses these, so we have them. The trick is to make them easily loadable by the C# script.

**Comment by fabiocav** [comment]
The metadata resolver already handles automatic assembly references and there is already a set of assemblies referenced by default (the WebJobs host being one of them) so we can easily add the ones mentioned above. We can also automatically inject imports so we don't have to add a using for some of the namespaces, which I've been wanting to do for the host assembly so we can eliminate the using clause that is needed just to use the TraceWriter as an argument.
