### ISSUE TITLE
[Node] HTTP response with a native Buffer object results gives base64

### ISSUE THREAD

**Issue by yvele** [Azure/azure-webjobs-sdk-script#814]
#### Repro steps

``` js
context.res.body = Buffer.from("using a buffer");
```

PS: I also set `content-type` to `application/json; charset=utf-8`
#### Expected behavior

A or B?
##### A. Decoded buffer

Decoded buffer should be output

``` text
using a buffer
```

This solution is maybe the best as you are already planing to add ExpressJS style API for HTTP responses: https://github.com/Azure/azure-webjobs-sdk-script/pull/781 https://github.com/Azure/azure-webjobs-sdk-script/issues/160
##### B. An explicit error message

Should throw an explicit error message like a [TypeError](https://nodejs.org/api/errors.html#errors_class_typeerror)

> TypeError : Response body should be string
#### Actual behavior

HTTP output is: `dXNpbmcgYSBidWZmZXI=`
#### Known workarounds

``` js
context.res.body = JSON.parse(Buffer.from("using a buffer"));
```
#### Related information

I'm using my own small [connect adaptor](https://github.com/yvele/azure-function-express) for Azure Function (working like a charm) that allows me to use express and all available middlewares. That's why I found this issue.. some middlewares are directly dealing with Buffers

edit: confirmed by @mamaso that buffer should be supported

**Comment by mamaso** [comment]
We definitely have some work to do with content negotiation in node, was just talking about this with @fabiocav yesterday.  I'll play around with this scenario in express & functions and figure out a consistent behavior

**Comment by yvele** [comment]
@mamaso I was much more thinking about throwing a [TypeError](https://nodejs.org/api/errors.html#errors_class_typeerror)

**Comment by yvele** [comment]
With an Express adapter: https://github.com/yvele/azure-function-express no need to worry about content negotiation :wink:

**Comment by yvele** [comment]
👍
