### ISSUE TITLE
Input names aren't surfaced as env variables in batch files

### ISSUE THREAD

**Issue by davidebbo** [Azure/azure-webjobs-sdk-script#82]
As we saw, this no longer seems to work. e.g. with 

```json
{
  "bindings": [
    {
      "type": "blobTrigger",
      "name": "original",
      "direction": "in",
      "path": "images-original/{name}"
    },
    {
      "type": "blob",
      "name": "resized",
      "direction": "out",
      "path": "images-resized/{name}"
    }
  ]
}
```

and

```
echo %original%
```

`original` is empty.

**Comment by mathewc** [comment]
Yeah, I looked into this and know what is going on. Currently trigger input is accessed via stdin, not env. That doesn't work for scenarios like this. I think what I'm going to do is remove the stdin pattern and make all inputs/outputs file based, which is more consistent anyways.

**Comment by davidebbo** [comment]
I see. That's why `%original%` is not set, but `%resized%` is.

Moving away from stdin/stdout pattern might make sense.

For http, is the stdin pattern already gone? I see current template (which works) just has:

    echo Please pass a name on the query string > %res%

Is 'res' a file in that case?

**Comment by davidebbo** [comment]
I guess then the pattern for http is to use `>>` for append, e.g.

	echo First line >> %res%
	echo Second line >> %res%

This already seems to work well, and I like it.

**Comment by mathewc** [comment]
This has been fixed.
