### ISSUE TITLE
CLI: rename azfunc npm alias to azfun

### ISSUE THREAD

**Issue by lindydonna** [Azure/azure-webjobs-sdk-script#831]
We **currently** have the following aliases:
- func
- azurefunctions
- azfunc

Unfortunately, func sounds a lot like a different word, and the NPM experts tell me that it should be `azure-functions`.

Let's replace with the following:
- func
- azure-functions
- **azfun** (no "c")

**Comment by lindydonna** [comment]
@paulbatum Is my understanding of npm naming correct?  Is it `azure-functions` or `azurefunctions`?  Maybe it doesn't matter, since azfun is way easier to type

**Comment by paulbatum** [comment]
Yes, my understanding of npm conventions is to use dashes to separate words.

**Comment by ahmelsayed** [comment]
actually this is already fixed. It's azfun in the existing package on npm
