### ISSUE TITLE
CLI: Windows 10 profile with username incl. space causes errors

### ISSUE THREAD

**Issue by mikezks** [Azure/azure-webjobs-sdk-script#837]
#### Repro steps
1. Use Windows 10 profile with a username which includes a space. e.g. "Jane Doe".
2. Install CLI like described here: https://www.npmjs.com/package/azure-functions-cli
3. Start function: func run Func1 -f file.json
#### Expected behavior

I assume the local server should start and execute the function code, but it has never worked for me. (see https://github.com/Azure/azure-webjobs-sdk-script/issues/822)
#### Actual behavior

The following error dialog shows up:
![functions-error1](https://cloud.githubusercontent.com/assets/23002661/19767782/b3006c7a-9c54-11e6-80ab-0c9b8c901715.png)
This means: The path could not be found. Verify that you used the correct name and repeat the procedure.

CLI shows the following:
![functions-error2](https://cloud.githubusercontent.com/assets/23002661/19767823/ecc154a6-9c54-11e6-9f05-ea54567cf497.png)
#### Known workarounds

Use a profile with a username without spaces.

**Comment by lindydonna** [comment]
See also https://github.com/Azure/Azure-Functions/issues/52
