### ISSUE TITLE
CLI: Ensure -version output uses npm and host version

### ISSUE THREAD

**Issue by lindydonna** [Azure/azure-webjobs-sdk-script#839]
Currently always outputs "Azure Functions CLI 0.1". We should output both the host semver and the npm package version.

**Comment by mikezks** [comment]
There are still issues with the listed versions. Could you please reopen this issue to track this.

``func`` command shows:
- ``Azure Functions Cli (1.0.0-beta.5)`` although ``beta.8`` is installed.
- ``Function Runtime Version: 1.0.0.0`` and not the specific runtime version details (e.g. ``1.0.10690``).

**Comment by lindydonna** [comment]
@mikezks You're right--I actually created a new issue to track: https://github.com/Azure/azure-webjobs-sdk-script/issues/1070

I'm going to keep this issue closed, because the new one is assigned to a milestone.
