### ISSUE TITLE
Non-descriptive error when using an invalid connection string key name

### ISSUE THREAD

**Issue by lindydonna** [Azure/azure-webjobs-sdk-script#841]
I used a connection string name in my function.json that did not exist in my app setting, and got the error *_Error indexing method 'Functions.AvatarPhotoProcess'. Microsoft.Azure.WebJobs.Host: Value cannot be null. Parameter name: dataAccount. *_
#### Repro steps
1. In function.json:

```
    {
      "type": "blobTrigger",
      "name": "image",
      "path": "avatar-input/{filename}.jpg",
      "connection": "functionfaff300ba605_STORAGE",
      "direction": "in"
    },
```
1. No app setting for `functionfaff300ba605_STORAGE`
#### Expected behavior

Popup saying that connection string `functionfaff300ba605_STORAGE` does not exist
#### Actual behavior

Error popup:

> Function ($AvatarPhotoProcess) Error: Microsoft.Azure.WebJobs.Host: Error indexing method 'Functions.AvatarPhotoProcess'. Microsoft.Azure.WebJobs.Host: Value cannot be null. Parameter name: dataAccount. 
> Session Id: 5d970591e0424c438a5933fefa795299
> Timestamp: 2016-10-28T02:00:56.475Z

The portal also become unresponsive, I'm opening an issue for that

**Comment by mathewc** [comment]
Note that this is a core SDK fix.

**Comment by gartdan** [comment]
+1 on fixing this :) My first interaction with the VS Tools, it took me a while to figure out that the actual error was a missing connection string in appsettings.json (I didn't realize the actual error until I found this issue).

**Comment by paulbatum** [comment]
@soninaren this looks similar to the null ref on storage account issue that you are already looking at.

**Comment by soninaren** [comment]
yes, i have the fix validated here https://github.com/Azure/azure-webjobs-sdk/commit/93ce37f6cdca62c5b4f9245dcb112352af8031ac

**Comment by soninaren** [comment]
Fixed in here https://github.com/Azure/azure-webjobs-sdk/pull/946

**Comment by soninaren** [comment]
Closing this one since we have an issue on core SDK https://github.com/Azure/azure-webjobs-sdk/issues/927
