### ISSUE TITLE
[Moved to Portal] Show detailed runtime version in Azure Portal

### ISSUE THREAD

**Issue by mikezks** [Azure/azure-webjobs-sdk-script#842]
[Feature] request

As described in [Wiki](https://github.com/Azure/azure-webjobs-sdk-script/wiki/Function-Runtime-Versioning) it is possible to select a different Azure Functions Portal runtime version than the default one by changing FUNCTIONS_EXTENSION_VERSION.

Currently it is not possible to figure out which detailed version is the default one and which version is the latest available for testing resp. it is not possible to figure out if the lastest release on github is already selectable in Azure Portal.

Currently, if I choose to switch to a higher version than the default one the "Function app settings" UI shows: "Runtime version: ~0.8. A newer version is available (~0.7)."
Although version 0.9 has not been released yet the portal shows "Runtime version: ~0.9. A newer version is available (~0.7).", if I set FUNCTIONS_EXTENSION_VERSION to "~0.9".

It would be helpful to have a UI page that shows all available versions including the lastest and the default version. This page should get updated automatically as a new version gets deployed to Azure Portal.

e.g. Functions 0.8.10564 (1.0.0-beta1-10564)

**Comment by davidebbo** [comment]
Until there is an easy way to see this, I just documented the hard way: https://github.com/Azure/azure-webjobs-sdk-script/wiki/Function-Runtime-Versioning#how-to-determine-which-exact-version-you-are-running.

But yes, we should make this easier.

**Comment by mikezks** [comment]
Thanks for your quick answer, @davidebbo. This already helps.
It's fabulous how quick all of you are answering our requests!

**Comment by mikezks** [comment]
Quick & dirty - an Azure Function which shows the installed versions, bold the currently used one:

C# HTTP Trigger
``run.csx``
```c#
using System.Net;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using System.IO;

public static async Task<HttpResponseMessage> Run(HttpRequestMessage req, TraceWriter log)
{
    var dirArray = Directory.GetDirectories(@"D:\Program Files (x86)\SiteExtensions\Functions\");
    var configFile = String.Join("", File.ReadAllLines(@"D:\local\Config\applicationhost.config"));
    var result = "";
    var currentVersion = false;

    foreach (string dir in dirArray) {
        if (configFile.Contains(new DirectoryInfo(dir).Name))
            currentVersion = true;
        result = result + (currentVersion ? "<b>" : "") + new DirectoryInfo(dir).Name + (currentVersion ? "</b>" : "") + "<br />";
        currentVersion = false;
    }
        
    var response = new HttpResponseMessage(HttpStatusCode.OK);
    response.Content = new StringContent(result);
    response.Content.Headers.ContentType = new MediaTypeHeaderValue("text/html");

    return response;
}
```

**Comment by davidebbo** [comment]
Thanks for Sharing. Note that the status API returns the host version, per #403. So portal could easily just call this API.

As an aside, this issue really belongs on https://github.com/projectkudu/AzureFunctionsPortal/issues.
