### ISSUE TITLE
Settings: host.json vs. environment variable/app settings

### ISSUE THREAD

**Issue by mikezks** [Azure/azure-webjobs-sdk-script#843]
[Question]

Some settings are defined in host.json others as environment variable/app setting.
I suggest to discuss whether it makes sense to move some of the settings to host.json for RC.

e.g.:
FUNCTIONS_EXTENSION_VERSION
AzureWebJobsDisableHomepage

**Comment by fabiocav** [comment]
@mikezks this is a great question!

There are a few reasons why some settings are implemented as app settings vs host.json settings, as there are some key differences between the two approaches.

*Some* (not all) of the reasons are:

- App settings can be sticky to a slot, which means that when deployment slots are fully supported, which is planned, you could have some settings that apply to your dev and staging environment, but not production as you swap, even though the files are the same. `host.json` defined settings will be applied after a swap (e.g. you may want to disable the homepage in production, but not in your staging/dev environments, same with compilation optimization, as it makes sense to have your functions compiled in debug mode by default in dev, but not in prod)
- App settings trigger a function app restart. Sometimes that is desirable, other times it isn't.
- App settings are more easily managed by the site administrator. So if there are settings knobs that are more geared towards ongoing administration, they're more easily managed by that persona there.
- App settings are secure (encrypted). If the setting contains sensitive information, it won't go in the `host.json`

There are a few other reasons and others will likely add to my list above, but the decision as to where a particular setting goes is not arbitrary and is based on several factors (e.g. its intended use, how often it changes, the persona most likely responsible for that setting, whether its contents are sensitive, whether we should have the ability to have it differ between slots, local hosting and dev considerations, etc.). That doesn't mean that we don't (or won't) get it wrong 😄, so it's great to hear feedback if the way a particular setting is exposed doesn't make sense, but we try to carefully consider how to expose each one of them.

By the way, the *FUNCTIONS_EXTENSION_VERSION* is a bit of a special setting, as this is **not** Azure Functions specific and instructs the App Service infrastructure to install (and what version) extensions on that site. You can learn more about it here: https://github.com/projectkudu/kudu/wiki/Azure-Site-Extensions

Again, thanks for the question and if you ever think there's a setting that doesn't make sense exposed one way or the other, please get the discussion started so we can evaluate based on scenarios we might not have anticipated.

**Comment by fabiocav** [comment]
By the way, @davidebbo has discussed having an inheritance model, where settings could be defined in `host.json` but overriden in app setting if needed. This is something we'll likely support in the future and would give you the best of both worlds.

**Comment by mikezks** [comment]
Kudos for this detailed explanation!
This makes perfect sense to me and therefore I currently see no reason to move any of the settings. @davidebbo's idea sounds promising.
