### ISSUE TITLE
Question on Event Model

### ISSUE THREAD

**Issue by arafato** [Azure/azure-webjobs-sdk-script#845]
Hi everybody, 

I have a question regarding the event model how Azure Functions get data from event sources such as Blob Storage or Event Hub.
Is there a push / pull event model similar to AWS Lambda, for example?

**Example 1: Triggering an event based on a uploaded file on Blob Storage:**
Is this event pushed to Azure Functions? Is there a retry limit in case the event gets lost or the Azure Functions fails to execute? Are events from Blob Storage ordered?

**Example 2: Reading / Processing messages from EventHub**
Are messages from EventHub pushed to Azure Functions or is the Azure Functions runtime actively pulling messages from the EventHub? Is this done in batches or is a function triggered for every message? Is there a retry limit in case the function fails to execute? Is message delivery in order?

Thanks!
--Oliver.

**Comment by mathewc** [comment]
Azure Storage doesn't currently support a push model, so currently we rely on efficient polling algorithms. We're working with the storage team to get a push model in place, but those changes will be transparent to Functions users. To answer your question, our blob trigger ensures that the blob will eventually get processed - the blob event will not get lost.

For your EventHubs question, we're using the EventHubs Event. Details on the underlying EventHubs binding can be found [here](https://github.com/Azure/azure-webjobs-sdk/wiki/EventHub-support). We use the EventHubs EventProcessorHost to pull events, and we do checkpointing only when events are processed successfully. Code for that is [here](https://github.com/Azure/azure-webjobs-sdk/blob/master/src/Microsoft.Azure.WebJobs.ServiceBus/EventHubs/EventHubListener.cs#L86).
