### ISSUE TITLE
CLI: Deploy Azure Function via Kudu or FTP

### ISSUE THREAD

**Issue by mikezks** [Azure/azure-webjobs-sdk-script#846]
[Feature] request

The [npm website](https://www.npmjs.com/package/azure-functions-cli) shows how to deploy a local Azure Function to Azure Portal.

At least for beginners who do not have a CI scenario with github configured, it would be easier to deploy via Kudu or FTP.

It would be helpful to include such a tutorial in the npm website (maybe with [kudusync](https://www.npmjs.com/package/kudusync)?).

**Comment by lindydonna** [comment]
Investigate using Kudu VFS API

**Comment by ahmelsayed** [comment]
This issue was moved to Azure/azure-functions-cli#8
