### ISSUE TITLE
Dynamic Function Apps: runtime as a private site extension

### ISSUE THREAD

**Issue by mikezks** [Azure/azure-webjobs-sdk-script#847]
[Feature] request

[Wiki](https://github.com/Azure/azure-webjobs-sdk-script/wiki/Deploying-the-Functions-runtime-as-a-private-site-extension) shows how to use a custom runtime as a private site extension.

This works for Classic Functions Apps only.
It would be great to have this option for Dynamic Function Apps as well.

**Comment by fabiocav** [comment]
This is by design. There are some limitations when running a private extension in the dynamic environment and this is not something that will be supported in the near future.
