### ISSUE TITLE
Remove: "Dynamic pricing tier is not allowed in this resource group" limitation

### ISSUE THREAD

**Issue by sjkp** [Azure/azure-webjobs-sdk-script#851]
Please provide a succinct description of the issue.

#### Repro steps

Provide the steps required to reproduce the problem

1. Deploy an Azure function using an ARM template with a Dynamic SKU

2. See the deployment fail with the error "The Dynamic pricing tier is not allowed in this resource group"

#### Expected behavior

The ARM template was deployed without error. 

#### Actual behavior

The deployment fails. 

#### Known workarounds

Retry the deployment, but you might have to retry many times to actually hit a scale unit that does support the Dynamic SKU. 

#### Related information 
This wiki post by @davidebbo states that eventually this limitation will be lifted (but when is eventually the post is 1,5 month old. I thought scale units was patched on a monthly basis. 
https://github.com/Azure/Azure-Functions/wiki/Creating-Function-Apps-in-an-existing-Resource-Group

**Comment by davidebbo** [comment]
Questions:

- Are you deploying to an existing resource group or a new one?
- If existing, does it have regular Web App?
- If not, does your template contain both Dynamic and regular Web Apps?

**Comment by sjkp** [comment]
It is a fresh resource group. It is part of an automated provisioning process. 
The template contains classic service plan too. 
We tried to make the dynamic plan dependent on the classic to force arm to use a scale unit that supports the dynamic sku by deploying it first. Didn't seems to have any effect.

**Comment by davidebbo** [comment]
> We tried to make the dynamic plan dependent on the classic to force arm to use a scale unit that supports the dynamic sku by deploying it first.

Wait, you want the other way around! :) i.e. the Dynamic plan needs to be created first, and you'll never run into this issue.

**Comment by sjkp** [comment]
I just tried again with the classic plan being dependent on the dynamic plan (which is what I meant to write in my earlier comment). I'm pretty sure we that tried the exact same thing some time ago without it working, so we disregarded it back then and was hoping for a real fix. 

But nevertheless it is working reliably now with the dependsOn trick, so I'm happy.   

Here's some snippets from the template: 
 {
      "type": "Microsoft.Web/serverfarms",
      "apiVersion": "2015-04-01",
      "name": "[variables('dynamicAppServicePlanName')]",
      "location": "[resourceGroup().location]",
      "properties": {
        "name": "[variables('dynamicAppServicePlanName')]",
        "computeMode": "Dynamic",
        "sku": "Dynamic"
      }
},
{
     "type": "Microsoft.Web/serverfarms",
     "apiVersion": "2015-08-01",
     "name": "[variables('appServicePlanName')]",
     "location": "[resourceGroup().location]",
     "dependsOn": [
       "[resourceId('Microsoft.Web/serverfarms', variables('dynamicAppServicePlanName'))]" 
     ],
     "sku": {
       "name": "[parameters('appServicePlanSize')]",
       "tier": "[parameters('appServicePlanSku')]",
       "capacity": 1
     }
},

**Comment by davidebbo** [comment]
Yes, it really should work 100% reliably with such dependency. If you hit a case where it fails, we'll investigate the sequence that led to that. But in theory it's not possible :)

Closing this. Note that the restriction *will* disappear later.

**Comment by ebashmakov** [comment]
I stuck with the same error. I was using this template https://github.com/Azure/azure-quickstart-templates/tree/master/101-function-app-create-dynamic and got the following error (deploying to a new resource group): 

```json
{
  "Code": "Conflict",
  "Message": "The pricing tier 'Dynamic' is not allowed in this resource group. Use this link to learn more: http://go.microsoft.com/fwlink/?LinkId=825764",
  "Target": null,
  "Details": [
    {
      "Message": "The pricing tier 'Dynamic' is not allowed in this resource group. Use this link to learn more: http://go.microsoft.com/fwlink/?LinkId=825764"
    },
    {
      "Code": "Conflict"
    },
    {
      "ErrorEntity": {
        "Code": "Conflict",
        "Message": "The pricing tier 'Dynamic' is not allowed in this resource group. Use this link to learn more: http://go.microsoft.com/fwlink/?LinkId=825764",
        "ExtendedCode": "04114",
        "MessageTemplate": "The pricing tier '{0}' is not allowed in this resource group. Use this link to learn more: http://go.microsoft.com/fwlink/?LinkId=825764",
        "Parameters": [
          "Dynamic"
        ],
        "InnerErrors": null
      }
    }
  ],
  "Innererror": null
}
```

@davidebbo do you have an idea how to solve this? I also tried a template generated by Azure portal (it's a bit different) but still I get the same error.

**Comment by davidebbo** [comment]
@ebashmakov There was a new incident that was causing this and is now resolved. Can you try again?

**Comment by ebashmakov** [comment]
@davidebbo it worked! thanks!
