### ISSUE TITLE
Improve the function create experience via Template on CLI

### ISSUE THREAD

**Issue by adrianhall** [Azure/azure-webjobs-sdk-script#856]
Certain templates (e.g. the Nodejs-HttpTriggerCRUD(GET)) don't work out of the box - need to clean them up.

**Comment by christopheranderson** [comment]
@soninaren - this probably should move to templates repo?

**Comment by mathewc** [comment]
Unless we have e2e tests that are verifying each of the GA templates we ship, we won't be able to have confidence that they actually work. I think we should ensure that we have tests in place for all of them.

**Comment by soninaren** [comment]
We have vendors testing all the core templates, We can extend the OGF's to test all templates.

**Comment by soninaren** [comment]
Updating the title after chat with @adrianhall. HttpTriggerCRUD templates work out of the box via UI but not via CLI

**Comment by soninaren** [comment]
Related issue on CLI
https://github.com/projectkudu/generator-azurefunctions/issues/2
