### ISSUE TITLE
HostId must be changed to derive from WEBSITE_HOSTNAME

### ISSUE THREAD

**Issue by fabiocav** [Azure/azure-webjobs-sdk-script#857]
When hosted on Azure, the HostId currently derives from the WEBSITE_SITE_NAME setting. This setting will be the same across deployment slots, leading to conflicts when that feature is enabled.

We should be using the WEBSITE_HOSTNAME setting instead (which will be something like <site_slot_name>.azurewebsites.net).

**Comment by mathewc** [comment]
Need to fix other places that are also using this same logic, e.g. ScaleController, Kudu, Mike's Logging stuff.

**Comment by fabiocav** [comment]
@davidebbo , @cgillum, @tohling and @MikeStall adding you guys so you're aware.

I'll make this change to the runtime, but wanted to make sure you guys can address the other components mentioned by @mathewc.

**Comment by MikeStall** [comment]
I think logging is a non-issue here and you *don't*  need an updated log dll. 
- For the writer, Logging has these values passed in via the LogFactory parameters. That callsite exists in Script.  
- For the reader, the portal will pass the host id through and filter on that. The portal will pick up whatever host id is passed from script.

**Comment by fabiocav** [comment]
@tohling and @cgillum, this change was made and, for the primary site, will behave exactly as it did before. The only difference will be when running on a deployment slot, as the host ID will have the slot name.
