### ISSUE TITLE
Support key management with deployment slots

### ISSUE THREAD

**Issue by christopheranderson** [Azure/azure-webjobs-sdk-script#859]
## Problem

Key Management currently doesn't work with deployment slots (the keys get swapped with the file system, so they have to be the same everywhere...).

### (Default experience) Each slot gets their own set of keys, sticky to their slot

**Story:**

1. Existing conditions:
     - User has a Function App named `bango`
     - User has a HTTP trigger named `rocky`
     - `rocky` has a key - `choco:666`
3. User creates a new slot named `bango-dev`.
4. User then goes to existing HTTP trigger, `rocky`, in `bango-dev`
     - `rocky (dev)` has a new, default key for this slot
     - `rocky (dev)` doesn't have key - `choco:666`
5. User creates a new secret, `lemon:12345`, on `rocky (dev)`, in `bango-dev`.
6. User writes some new code in `rocky (dev)`
7. User does a swap from dev to prod
8. User goes to existing HTTP trigger, `rocky`, in production slot, `bango`.
    - `rocky` has a key - `choco:666`
    - `rocky` does not have `lemon` as a key.
    - `rocky` has new code, written previously in `rocky (dev)

**Requirements:**

- Keys should be sticky to a slot, by default
- Keys should be stored in a blob container in the WebJobs Host Storage Account
- Each slot that the user creates should get its own secrets blob container, by default
- The secrets container should be based on `WEBSITE_HOSTNAME` (directly or indirectly), by default

### (Shared keys) Two or more slots want to share a set of keys

**Story:**

1. Existing conditions:
     - User has a Function App named `bango`
     - User has a HTTP trigger named `rocky`
     - `rocky` has a key - `choco:666`
3. User creates a new slot named `bango-preprod`.
4. User creates an app setting named `FunctionSecretsContainer` with a value of `Bango-prod-123` in `bango` and `bango-preprod`, sticky to their slots
4. User then goes to existing HTTP trigger, `rocky`, in `bango-preprod`
     - `rocky (preprod)` has key - `choco:666`
5. User creates a new secret, `lemon:12345`, on `rocky (preprod)`, in `bango-preprod`.
6. User does a manual sync from the deployment tab to `bango-preprod`
7. User does a swap from preprod to prod
8. User goes to existing HTTP trigger, `rocky`, in production slot, `bango`.
    - `rocky` has key - `choco:666`
    - `rocky` has key - `lemon:12345`
    - `rocky` has new code from manual deployment sync
 
**Requirements**

- Secrets blob containers should use the `FunctionSecretsContainer` environment variable for their name, when present the environment variable is present

## Notes

- There are other, lower priority scenarios, such as when you WANT to swap secrets with you swap, etc. that are covered by the previous scenarios functionality (specifically, the app setting enables quite a bit of control), but aren't critical, so aren't spelled out.
- Some requirements dig a bit technical, so feel free to push back. Given the app settings, blobs, etc. I felt it was appropriate I discussed some of them.

/cc @dariagrigoriu @fabiocav

**Comment by christopheranderson** [comment]
Note: default experience isn't likely to happen first, because it requires migration. We'll start with the app setting driven model.

**Comment by fabiocav** [comment]
Will you be moving this to next?

**Comment by fabiocav** [comment]
@christopheranderson cleaning up some of the issues. This has been delivered, but I'm not sure if everything here has been addressed. Are we good to close?
