### ISSUE TITLE
CLI: Update azurefunctions package with a warning pointing to the new one

### ISSUE THREAD

**Issue by lindydonna** [Azure/azure-webjobs-sdk-script#862]
- Change the readme of the npm package `azurefunctions` to point to the real CLI:
   
   `This package has been superseded by azure-functions-cli`

- Update content of the package to display warning after installation: 

   `WARNING: This package has been superseded by azure-functions-cli, use that instead`

**Comment by ahmelsayed** [comment]
https://www.npmjs.com/package/azurefunctions
