### ISSUE TITLE
backspace key is the worst

### ISSUE THREAD

**Issue by johnnliu** [Azure/azure-webjobs-sdk-script#865]
Please provide a succinct description of the issue.

#### Repro steps

Provide the steps required to reproduce the problem

Type some code.

Click logs

Decide to delete some code and press backspace.

#### Expected behavior

Nothing happens.

#### Actual behavior

Code changes all lost as browser navigates back to previous page.

#### Known workarounds

Dig out your backspace key and throw it into Mt Doom.

#### Related information 

Chrome has signalled they will remove backspace as a navigation for back arrow.

But Azure Functions shouldn't let me navigate back, or shouldn't let me navigate without a dialog that says I have unsaved content.

**Comment by fabiocav** [comment]
Moved this issue to the portal repository.
