### ISSUE TITLE
Cannot fetch secrets

### ISSUE THREAD

**Issue by ZainRizvi** [Azure/azure-webjobs-sdk-script#866]
Cannot fetch function secrets from Azure

** Repro steps **

Create a new function in the portal
Set it to deploy via local git
Clone the git locally
Fetch secrets

Here are the commands I tried and the outputs:

C:\Code\YoutubeAutoDownloader>func help fetch secrets --cli-dev
Unable to find option secrets on help

Azure Functions CLI 0.1

C:\Code\YoutubeAutoDownloader>func fetch Secrets YoutubeAutoDownloader
Error: Object reference not set to an instance of an object.
You can run the same command passing --cli-dev and report an issue on https://github.com/azure/azure-webjobs-sdk-script/issues

C:\Code\YoutubeAutoDownloader>func fetch Secrets
Error: Object reference not set to an instance of an object.
You can run the same command passing --cli-dev and report an issue on https://github.com/azure/azure-webjobs-sdk-script/issues

C:\Code\YoutubeAutoDownloader>start https://github.com/azure/azure-webjobs-sdk-script/issues

C:\Code\YoutubeAutoDownloader>func help fetch Secrets --cli-dev
Unable to find option Secrets on help

Azure Functions CLI 0.1

Tip: run func init to get started.

**Comment by christopheranderson** [comment]
@ahmelsayed - Could you take a quick look at what might be causing this?

**Comment by lindydonna** [comment]
@ZainRizvi @ahmelsayed  It looks like a verb parsing bug, but @ahmelsayed is fixing the verb structure as part of a rename overhaul. I could repro when didn't pass the function app name, but once I did, it worked fine.

```
C:\git-repos> func fetch secrets
Error: Object reference not set to an instance of an object.

C:\git-repos> func fetch secrets ilovefunctions
Loading AzureWebJobsDashboard = *****
```

**Comment by ahmelsayed** [comment]
yes sorry about that. I won't be fixing this as it'll be obsolete with https://github.com/Azure/azure-webjobs-sdk-script/issues/638

**Comment by ZainRizvi** [comment]
Cool. Any ETA on #638? :)

**Comment by ahmelsayed** [comment]
I'll keep you in suspense™

on a serious note, I'm hoping to have 90% done by tomorrow maybe EOD today if servicing isn't too bad, and mostly done early next week.
