### ISSUE TITLE
C# script can't used dynamic

### ISSUE THREAD

**Issue by davidebbo** [Azure/azure-webjobs-sdk-script#87]
e.g. running the following C# http func:

```c#
using System;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Threading.Tasks;
using System.Diagnostics;
using Microsoft.Azure.WebJobs.Host;

public static HttpResponseMessage Run(HttpRequestMessage req, TraceWriter log)
{
    dynamic d = req;
    if (d.foo == null) {
        
    }

    var res = new HttpResponseMessage(HttpStatusCode.OK)
    {
        Content = new StringContent("Hello")
    };
    
    return res;
}
```

Fails with

    run.csx(12,9): error CS0656: Missing compiler required member 'Microsoft.CSharp.RuntimeBinder.CSharpArgumentInfo.Create'

Based on http://stackoverflow.com/questions/22864790/using-system-dynamic-in-roslyn, the fix is to reference `Microsoft.CSharp.dll`. I don't think we're carrying the assembly right now, so we may need to include it.

**Comment by fabiocav** [comment]
Yes, I ran into that as well. To validate that it works, you should be able to do a #r "Microsoft.CSharp" and try again.

**Comment by davidebbo** [comment]
Yes, this does make it work! But I do think we should auto add the ref, as it's very hard to go from the error to knowing you need to add this.

**Comment by fabiocav** [comment]
Sounds good. I'll make that change
