### ISSUE TITLE
SendGrid Subject and Body Inconsistent

### ISSUE THREAD

**Issue by mmcconnell1618** [Azure/azure-webjobs-sdk-script#883]
**Please provide a succinct description of the issue.**

A function that is EventHub triggered and has SendGrid bindings added manually sometimes sends email with the default subject and body and other times with the programmatically set subject and body. The event hub has 4 partitions. The SendGrid API key is set via an App Config Setting.

**Provide the steps required to reproduce the problem**

1) Create an EventHub triggered function
2) Add SendGrid bindings to the function
3) Add an "app settings" variable containing the SendGrid Key (directly adding the key in Functions fails)
3) Add default Subject and Body (as required)
4) Add code to programmatically set subject and body in the function
5) Let the function execute messages from the EventHub

#### Expected behavior

Every message should be using the programmatically set subject and body

#### Actual behavior

Most messages get the default subject and body but some intermittently get the correct programmatically set ones.

#### Known workarounds

None known

#### Related information 

Base template was C# EventHub triggered function. SendGrid code and bindings were added to that template.

**Comment by mmcconnell1618** [comment]
Example Code:
====================================
#r "SendGrid"

using System;
using SendGrid.Helpers.Mail;
using Microsoft.Azure.WebJobs.Host;

public static void Run(string myEventHubMessage, out Mail message, TraceWriter log)
{
    message = new Mail();
    string [] parts = myEventHubMessage.Split(',');
    if (parts.Length > 2)
    {
        if(parts[1] != "200")
        {
            log.Info($"The code : {parts[1]} and The reason : {parts[2]} ");
            try
            {
                message.Subject = $"Azure API Management Security Event Trigger - Error {parts[1]}";
                Content content = new Content
                {
                    Type = "text/plain",
                    Value = $"Azure API Management Security Event Triggered - Error Code {parts[1]}, Error : {parts[2]}"
                };

                message.AddContent(content);    
            }
            catch
            (Exception ex)
            {
                log.Info(ex.Message);
            }
        }
        else
        {

        }
    }
}

**Comment by mathewc** [comment]
You have conditional logic in your function that only programatically sets the subject/content based on event properties. Are you sure it isn't the case that this conditional logic isn't the cause of the variability you're seeing? For an output message we only default the Mail properties if your code hasn't set them (code [here](https://github.com/Azure/azure-webjobs-sdk-extensions/blob/master/src/WebJobs.Extensions.SendGrid/Bindings/SendGridHelpers.cs#L42)).

@brettsam Any other ideas?

**Comment by fabiocav** [comment]
I think what @mathewc describes above is the likely cause. A good way to test this out would be to move the instantiation of your message to your try/catch block (initialize it with `null`) and perhaps log when your condition is not met. As in those cases no email would be sent at all.

**Comment by mmcconnell1618** [comment]
I believe @mathewc is probably correct. I will check with my customer tomorrow and see if we can resolve this by either changing setting the message parameter to null, using an ICollection<> out param or just returning a value from the function instead.

Thanks for your help! I'll let you know how it goes.

**Comment by mmcconnell1618** [comment]
The customer set the message to "null" by default and only set it as a new object right before setting properties to send. This has resolved their issue.

Thanks for all your help!
