### ISSUE TITLE
func init failure

### ISSUE THREAD

**Issue by simra** [Azure/azure-webjobs-sdk-script#887]
func init fails.
It took some fiddling to get --cli-dev to work, since it doesn't recognize an implicit working directory.
Git wasn't in my path, and I thought that might be the issue but it fails even when git is present in the path.

```
c:\GitHub\AzureFunctions>func init
Writing .gitignore
Writing host.json
Writing .secrets
Error: The system cannot find the file specified
You can run the same command passing --cli-dev and report an issue on https://github.com/azure/azure-webjobs-sdk-script/issues

c:\GitHub\AzureFunctions>func init --cli-dev
Unable to parse option Folder

Azure Functions CLI 0.1
Usage: func init [Options]

   <folder>    (Required)
   --vsc       Version Control Software. Git or Hg
   --help      Show this help



c:\GitHub\AzureFunctions>func init . --cli-dev
Writing .gitignore
Writing host.json
Writing .secrets
System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at WebJobs.Script.Cli.Common.Executable.<RunAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at WebJobs.Script.Cli.Verbs.InitVerb.<RunAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at NCli.ConsoleApp.<RunAsync>d__5`1.MoveNext()
```

#### Repro steps

Provide the steps required to reproduce the problem

1. npm i -g azurefunctions

2. npm i -g generator-azurefunctions yo

3. func init

#### Expected behavior

`func init` should succeed.

#### Actual behavior

Apparently an exe can't be found but I don't know which one.

#### Known workarounds

Unknown

#### Related information 

npm 3.10.8
node 6.9.1
git 2.6.2.windows.1

**Comment by lindydonna** [comment]
The Azure Functions CLI is now at https://www.npmjs.com/package/azure-functions-cli

**Comment by lindydonna** [comment]
@simra One question: how did you find the "azurefunctions" package? I'm trying to make sure I'm fixing the source links so people can find the latest.

**Comment by s1monfarrow** [comment]
I've had exactly the same issue, same circumstances and the same exception. The only difference is a slightly more recent version of node.

**Comment by lindydonna** [comment]
@s1monfarrow Does this bug reproduce with the new package at https://www.npmjs.com/package/azure-functions-cli?  The azurefunctions package is the old one and will be replaced with just a stub soon.

**Comment by s1monfarrow** [comment]
That's the one I used.

Simon

**Comment by lindydonna** [comment]
@s1monfarrow Can you post the exact process you followed and the exception?

**Comment by s1monfarrow** [comment]
This was what I did:

npm i -g azure-functions-cli
mkdir functest
cd functest
func init

Writing .gitignore
Writing host.json
Writing appsettings.json
System.ComponentModel.Win32Exception (0x80004005): The system cannot find the fi
le specified
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startIn
fo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at WebJobs.Script.Cli.Common.Executable.<RunAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at WebJobs.Script.Cli.Actions.LocalActions.InitAction.<RunAsync>d__5.MoveNext
()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at WebJobs.Script.Cli.ConsoleApp.<RunAsync>d__4`1.MoveNext()

**Comment by shankarvrp** [comment]
I have got the exact same issue, with the latest package.

**Comment by simra** [comment]
Hi, sorry for the delayed response. I wanted to point you to the tutorial that first surfaced the issue for me. If I get a chance to circle back I'll try to repro these steps and see if it's still not working. 
Link: http://gregshackles.com/getting-started-with-azure-functions-and-f/

**Comment by lindydonna** [comment]
@s1monfarrow Thanks for the additional details, we'll investigate.

We should have fixed the issue, but do you have a space or other non-ascii character in your current directory that you're running func init from?

**Comment by lindydonna** [comment]
@simra Yes, that blog post is using a much older version of the functions CLI. Try the steps in this blog post: https://blogs.msdn.microsoft.com/appserviceteam/2016/12/01/running-azure-functions-locally-with-the-cli/

**Comment by lindydonna** [comment]
@s1monfarrow looking into it further, I think the problem is that the Functions CLI is trying to run git init. A git repo is not strictly required. I'll file an issue to track the fact that it should show a nicer message if that's the error. 

You should still be able to create and run functions just fine.

**Comment by paulbatum** [comment]
@lindydonna I see you filed the discussed CLI issue. Can this issue be closed?

**Comment by lindydonna** [comment]
@paulbatum Yes, I think so. @s1monfarrow, please watch issue https://github.com/Azure/azure-webjobs-sdk-script/issues/1053 for the fix.
