### ISSUE TITLE
CLI: Should be able to invoke the run command of the CLI without installing globally

### ISSUE THREAD

**Issue by seesharprun** [Azure/azure-webjobs-sdk-script#900]
This could be a case of **user error** but I thought I would post.

I'm trying to invoke the *azurefunctions* CLI without installing it globally using the following steps:

#### Repro steps

1. Install the CLI locally ``npm install --save azurefunctions@0.2.5``

1. Install Yeoman locally ``npm install --save yo@1.8.4``

1. Invoke the CLI ``node node_modules\azurefunctions\lib\main.js init``

1. Invoke the CLI ``node node_modules\azurefunctions\lib\main.js new``

1. Invoke the CLI ``node node_modules\azurefunctions\lib\main.js run``

#### Expected behavior

I expect all commands to work the same as invoking them globally using ``func``.

#### Actual behavior

The **init** command will fail if you forget to install the peerDependency because it is not *enforced*. This is fine.

The **run** command fails outright with an error message indicating a component is missing.
> Windows cannot find 'C:\Users\\[username\]\Documents\Visual'. Make sure you typed the name correctly, and then try again.

#### Related information 

I am testing on *Windows*.

Again, this may be because I am making a simple mistake.

**Comment by seesharprun** [comment]
I completely forgot but this is important to me because I am writing a **tasks.json** and **launch.json** for for *Visual Studio Code* to launch and deploy AzureFunctions from within the editor.

**Comment by lindydonna** [comment]
The latest version of the Azure Functions CLI is actually at https://www.npmjs.com/package/azure-functions-cli

However, it is not a true Node module, as it packages a Windows executable. That's why you need to install it globally. We also have an issue where paths with spaces cause problems, see https://github.com/Azure/azure-webjobs-sdk-script/issues/837

**Comment by seesharprun** [comment]
This is awesome information! I saw the Windows executables and was secretly hoping there was a path forward. Will this ever be a Node module or at-least a cross platform .NET executable?

There's a lot of value add being able to invoke the CLI as a module and use it in VSCode tasks/launch files. As a dev team lead, I can guarantee that anyone on my team can run my project using the same version.

**Comment by lindydonna** [comment]
We will move to a .NET core assembly, but I can't share a timeline, unfortunately. Thanks for sharing your scenario--this is really helpful.

What languages are you predominantly using?  Node.js?

**Comment by seesharprun** [comment]
Most of my applications are currently in **Node.js**. Your answer resolved my issue.

Thanks!
