### ISSUE TITLE
User-agent in request Object is truncated for nodejs app

### ISSUE THREAD

**Issue by prashanthmadi** [Azure/azure-webjobs-sdk-script#913]
User-agent in request Object is truncated for nodejs app

Code:
    context.log(req.headers);

Output :
```
2016-11-11T19:20:51.513 { connection: 'Keep-Alive',
  accept: 'text/html',
  'accept-encoding': 'gzip',
  'accept-language': 'en-US',
  host: 'testfuncappm.azurewebsites.net',
  'max-forwards': '10',
  'user-agent': 'Mozilla/5.0',
  'upgrade-insecure-requests': '1',
  'x-liveupgrade': '1',
  'x-original-url': '/api/HttpTriggerNodeJS1…
………………………………………
}
```

#### Expected behavior

Here is Request bin output from same browser :  http://requestb.in/1ho30ok1?inspect
```
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36
```

**Comment by lindydonna** [comment]
@mathewc Please close when it is released.

**Comment by prashanthmadi** [comment]
@lindydonna @mathewc  How can i get these new changes in my existing function app ? 

I'm using latest function app Runtime (~0.9)

**Comment by lindydonna** [comment]
@prashanthmadi This should be ready by tomorrow.

**Comment by prashanthmadi** [comment]
Thanks @lindydonna

**Comment by mathewc** [comment]
Guys, this isn't actually in the 1.0 release package. It didn't make it in time - it won't be out until our next bugfix release.

**Comment by lindydonna** [comment]
I'm reopening so that we close when this is released.

**Comment by lindydonna** [comment]
@prashanthmadi I spoke too soon earlier--you'll get the fix soon, in the next bugfix release.
