### ISSUE TITLE
Azure Function: Error setting python version

### ISSUE THREAD

**Issue by mitchelldean** [Azure/azure-webjobs-sdk-script#919]
#### Repro steps
1. Goto Function App Settings
2. Configure App Settings
3. Default python version is off, can set to either 2.7 or 3.4

#### Expected behavior
With the setting to Off it is using python2.7, I want to set it to 3.4 

#### Actual behavior
Setting to 2.7 or 3.4 results in 404 errors on the function

#### Known workarounds
None, have to set it back to Off

#### Related information 
C# and python
https://github.com/mitchelldean/azurefunctiontest

**Comment by mitchelldean** [comment]
C# and python examples used, none work after setting a python version
https://github.com/mitchelldean/azurefunctiontest

**Comment by davidebbo** [comment]
Dup of #519. A possible workaround is mentioned there.
