### ISSUE TITLE
Creating a new Azure Functions app does not use the latest runtime

### ISSUE THREAD

**Issue by lukemerrett** [Azure/azure-webjobs-sdk-script#920]
Creating a new Azure Functions app does not use the latest runtime

#### Repro steps

1. Login to https://portal.azure.com
2. Ensure you have an App Service Plan in West Europe on F1 Free Tier
3. Create a new Function App using the App Service Plan with a new Resource Group and Storage Account
4. Wait for the Function App to be deployed
5. Go to the new Function App

#### Expected behavior

Function App deployed with the latest runtime version (~0.9 at time of writing)

#### Actual behavior

Shown message

>  A new version of Azure Functions is available. To upgrade visit Function App Settings. Learn more

Deployed with runtime version: ~0.8.

#### Known workarounds

The runtime version can be upgraded by going to Function App Settings; however this is an extra step required when creating the Function App from the UI

#### Related information 

Confirmed on 14/11/2016 at 12:13 on a Pay as you Go account

**Comment by lindydonna** [comment]
This will be fixed shortly. However, you should use a Dynamic app service plan rather than a Free app service plan. The Dynamic plan has a generous free grant and all triggers are supported. On Free, only http triggers will work reliably.

**Comment by lukemerrett** [comment]
@lindydonna good advice thank you.  If I choose a Dynamic plan (has this now been renamed to "Consumption Plan"?) will it use the latest runtime version?

**Comment by paulbatum** [comment]
Confirmed that the production environment now picks up the latest version (i.e. ~1).

**Comment by lindydonna** [comment]
@lukemerrett For your existing Function Apps, you can use the upgrade button on the settings page. Otherwise, new Function Apps will automatically pick up the latest version, as @paulbatum confirmed.
