### ISSUE TITLE
HttpPUT(CRUD)-FSharp Sample does not run successfully

### ISSUE THREAD

**Issue by lukemerrett** [Azure/azure-webjobs-sdk-script#921]
The HTTP PUT sample script in F# for putting items received over a HTTP endpoint into table storage does not run on creation.

#### Repro steps

1. Go to an existing Function App on the Azure UI
2. Click "+ New Function"
3. Under the "Language" dropdown choose F#
4. Click the "HttpPUT(CRUD)-FSharp" sample
5. Use the default settings provided and click "Create"
6. Open the new Function and click the "Develop" tab
7. Click Save then click Run

#### Expected behavior

The function, as it is based off an unmodified sample, should work as expected, inserting the sample data already specified in the Test section of the Develop UI into Table Storage.

#### Actual behavior

Below is the unmodified sample Test data that comes with the script:

![image](https://cloud.githubusercontent.com/assets/1067457/20264833/6a61ccc4-aa65-11e6-91b8-dfe7d0159ead.png)

We receive a "400 - Bad Request" with the reason "A non-empty Name must be specified.".  As seen above a name has been specified.  I have tried changing this to Pascal case "Name" to no avail.

It appears the JSON is not being read in successfully through the script.  If you change the "run.fsx" script to the following the JSON data is being received, just not correctly deserialised:

```fsharp
open System
open System.Net
open System.Net.Http
open Microsoft.WindowsAzure.Storage.Table

type Person() =
    inherit TableEntity()
    member val Name: string = null with get, set

let Run(person: string, outTable: CloudTable, log: TraceWriter) =
    let response = new HttpResponseMessage(HttpStatusCode.OK)
    response.Content <- new StringContent(person)
    response
```

#### Known workarounds

Add a new "project.json" file to the Function's file listing with this content:

```json
{
  "frameworks": {
    "net46":{
      "dependencies": {
        "Newtonsoft.Json": "9.0.1"
      }
    }
  }
}
```

Change the "run.fsx" script to: 

```fsharp
#r "System.Net.Http"
#r "Microsoft.WindowsAzure.Storage"

open System
open System.Net
open System.Net.Http
open Microsoft.WindowsAzure.Storage.Table
open Newtonsoft.Json

type Person() =
    inherit TableEntity()
    member val Name: string = null with get, set

let Run(person: string, outTable: CloudTable, log: TraceWriter) =
    let personObj = JsonConvert.DeserializeObject<Person>(person)

    if String.IsNullOrEmpty(personObj.Name) then
        let response = new HttpResponseMessage(HttpStatusCode.BadRequest)
        response.Content <-
            new StringContent("A non-empty Name must be specified.")
        response
    else
        log.Info(sprintf "PersonName=%s" personObj.Name)
        let updateOperation = TableOperation.InsertOrReplace(personObj)
        let result = outTable.Execute(updateOperation)
        new HttpResponseMessage(enum<HttpStatusCode>(result.HttpStatusCode))
```

Save and Re-run; the data will now be created correctly in Table Storage.

#### Related information 

Confirmed on 14/11/2016 at 12:23 on a Pay as you Go account

**Comment by lindydonna** [comment]
@soninaren Can you confirm that this one will be fixed or hidden?

**Comment by paulbatum** [comment]
Confirmed this template is currently hidden. Moving to next milestone so we can fix and bring it back.

**Comment by lukemerrett** [comment]
@paulbatum Is the code in this repository, if I send you a PR fixing them would that help bring the samples back sooner?

**Comment by soninaren** [comment]
@lukemerrett 
The code is still present in the dev branch. We have a runtime fix coming in for this, the Newtonsoft.Json packcage should resolve without project.json after the fix is deployed. We can bring in the sample back once the runtime fix is deployed. 

here is the PR for the runtime fix incase you were curious https://github.com/Azure/azure-webjobs-sdk-script/pull/893.

**Comment by soninaren** [comment]
The F# Templates have been temporarily moved to FSharpTemplates branch https://github.com/Azure/azure-webjobs-sdk-templates/tree/FSharpTemplates

**Comment by soninaren** [comment]
Fixed in here https://github.com/Azure/azure-webjobs-sdk-templates/pull/378
