### ISSUE TITLE
HttpGET(CRUD)-FSharp Sample does not run successfully

### ISSUE THREAD

**Issue by lukemerrett** [Azure/azure-webjobs-sdk-script#922]
The HTTP GET sample script in F# for getting items from table storage does not work without modification.

#### Repro steps

1. Go to an existing Function App on the Azure UI
2. Click "+ New Function"
3. Under the "Language" dropdown choose F#
4. Click the "HttpGET(CRUD)-FSharp" sample
5. Use the default settings provided and click "Create"
6. Open the new Function and click the "Develop" tab
7. Click Save then click Run

Note: ensure you have a table in the storage account that has some matching data.  This can be achieved using the fixes suggested here: https://github.com/Azure/azure-webjobs-sdk-script/issues/921.

#### Expected behavior

The function, as it is based off an unmodified sample, should work as expected, pulling back a list of entries from table storage.

#### Actual behavior

Below is the unmodified sample Test data that comes with the script:

![image](https://cloud.githubusercontent.com/assets/1067457/20265204/9ddad9e0-aa67-11e6-91d7-8fffb96532cd.png)

We receive a "500 Internal Server Error" with the message "An error has occurred".  

The log messages here prove the data is being pulled out of table storage, but not being sent down to the client:

```
2016-11-14T12:40:51.302 Function started (Id=3f47d74f-584d-48a5-b852-2635e278a507)
2016-11-14T12:40:51.349 Name: Azure
2016-11-14T12:40:51.349 Function completed (Success, Id=3f47d74f-584d-48a5-b852-2635e278a507)
```

#### Known workarounds

Modify the "run.fsx" script to the following:

```fsharp
#r "System.Net.Http"
#r "Microsoft.WindowsAzure.Storage"

open System.Linq
open System.Net
open System.Net.Http
open Microsoft.WindowsAzure.Storage.Table

type Person() =
    inherit TableEntity()
    member val Name: string = null with get, set

let Run(req: HttpRequestMessage, inTable: IQueryable<Person>, log: TraceWriter) =
    let names = query {
                    for person in inTable do
                    select person
                } |> Seq.fold(fun acc person -> acc + (sprintf "%s " person.Name)) ""

    req.CreateResponse(HttpStatusCode.OK, names)
```

The save and re-run.  The data will be serialised into a basic string for the response.

#### Related information 

Confirmed on 14/11/2016 at 12:38 on a Pay as you Go account

**Comment by lindydonna** [comment]
@soninaren Can you confirm that this one will be fixed or hidden?

**Comment by paulbatum** [comment]
Confirmed this template is currently hidden. Moving to next milestone so we can fix and bring it back.

**Comment by lukemerrett** [comment]
@paulbatum Is the code in this repository, if I send you a PR fixing them would that help bring the samples back sooner?

**Comment by soninaren** [comment]
@lukemerrett the code is still present in the dev branch of the templates repository.
https://github.com/Azure/azure-webjobs-sdk-templates/tree/dev/Templates/HttpGET(CRUD)-FSharp

Please go ahead and send the PR against the dev branch. We can merge it in once approved and should be able to bring this sample back.

**Comment by soninaren** [comment]
The F# Templates have been temporarily moved to FSharpTemplates branch https://github.com/Azure/azure-webjobs-sdk-templates/tree/FSharpTemplates

**Comment by soninaren** [comment]
fixed in here https://github.com/Azure/azure-webjobs-sdk-templates/pull/378. The template is available again
