### ISSUE TITLE
C# Queue trigger metadata fails with error when trying with sample queue data

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-webjobs-sdk-script#923]
Please provide a succinct description of the issue.

#### Repro steps

Provide the steps required to reproduce the problem

1. Create QueueTrigger C#

```
public static void Run(string myQueueItem, 
    DateTimeOffset expirationTime, 
    DateTimeOffset insertionTime, 
    DateTimeOffset nextVisibleTime,
    string queueTrigger,
    string id,
    string popReceipt,
    int dequeueCount,
    TraceWriter log)
{
    log.Info($"C# Queue trigger function processed: {myQueueItem}\n" +
        $"queueTrigger={queueTrigger}\n" +
        $"expirationTime={expirationTime}\n" +
        $"insertionTime={insertionTime}\n" +
        $"nextVisibleTime={nextVisibleTime}\n" +
        $"id={id}\n" +
        $"popReceipt={popReceipt}\n" + 
        $"dequeueCount={dequeueCount}");
}
```

2. Click run with sample queue data

#### Expected behavior

queueTrigger=sample queue data
expirationTime=11/21/2016 6:07:40 PM +00:00
insertionTime=11/14/2016 6:07:40 PM +00:00
nextVisibleTime=11/14/2016 6:17:42 PM +00:00
id=null
popReceipt=null
dequeueCount=0

#### Actual behavior
Exception while executing function: Functions.QueueTriggerCSharp1. Microsoft.Azure.WebJobs.Host: One or more errors occurred. Exception binding parameter 'id'. Microsoft.Azure.WebJobs.Host: Binding data for 'id' is not of expected type String.

* Programming language used  : C#
* Links to source

**Comment by mathewc** [comment]
The above code works fine with an actual queue message. This is only an issue if attempting to use these queue message property bindings when not triggering via an actual queue message. Since these bindings require an actual queue message, they won't work with sample data.

**Comment by pragnagopa** [comment]
67fcd7b5d69ea447a97b06224dcdec014aca73e8 added new column eventCreatedAt. 
Note : New columns will not show up in MDS until #885 is checked in

**Comment by niemyjski** [comment]
I'm also seeing this with just trying to get this simple example from working from a queue message
