### ISSUE TITLE
CLI: Host stuck on Waiting for Singleton lock

### ISSUE THREAD

**Issue by Nosmadas** [Azure/azure-webjobs-sdk-script#932]
When running func function run the cli never gets past waiting for singleton lock.

#### Repro steps

1. npm i azure-functions-cli
2. Create a new c# trigger function app using yeoman.
3. func function run x
4. A new terminal opens and cycles "waiting for singleton lock"
5. Original terminal prints "Error calling function x: ServiceUnavailable"

#### Expected behavior

???

#### Actual behavior

![image](https://cloud.githubusercontent.com/assets/14331314/20344302/1fa34736-abea-11e6-98c6-880960b99599.png)

![image](https://cloud.githubusercontent.com/assets/14331314/20344314/29d5ebc8-abea-11e6-80fa-4d533eec5ee2.png)

#### Related information 
C# timer template generated with yeoman.
Win10
Node v6.3.1

**Comment by Nosmadas** [comment]
Updated CLI today - now getting this.

![image](https://cloud.githubusercontent.com/assets/14331314/20456111/6344b2ea-ae65-11e6-8356-0043a6c7fff4.png)

**Comment by lindydonna** [comment]
@Nosmadas The error about FunctionEnvelope[] is very confusing but really you just need a value for AzureWebJobsStorage in appsettings.json. The error message will be improved in https://github.com/Azure/azure-webjobs-sdk-script/issues/1069.
