### ISSUE TITLE
Timer Trigger for no longer fires

### ISSUE THREAD

**Issue by douglasware** [Azure/azure-webjobs-sdk-script#940]
A function app configured to trigger once per day worked reliably until 11/13/2016 but is no longer triggering. Bindings are:

```
{
  "bindings": [
  {
      "name": "jobTimer",
      "type": "timerTrigger",
      "direction": "in",
      "schedule": "0 0 23 * * *"
    }
  ],
  "disabled": false
}
```

It was originally version 0.6 but is now 1.0.
Function can be invoked manually and works.
Service plan is Basic 1 Small.

**Comment by davidebbo** [comment]
Do you have 'Always On' enabled on the Function App?

**Comment by douglasware** [comment]
Yes

**Comment by christopheranderson** [comment]
Closing no repro until we've got a better thing to investigate
