### ISSUE TITLE
Are there any plans for generic Open ID Connect Provider support?

### ISSUE THREAD

**Issue by mclark1129** [Azure/azure-webjobs-sdk-script#941]
We don't use any of the pre-configured providers to manage authentication in our system.  Are there plans to open up authentication to support a generic OIDC provider, and optionally restrict functions by scope or access claims?

**Comment by mattchenderson** [comment]
We are in the process of evaluating both of these. You may want to vote for the following item on our feedback site: https://feedback.azure.com/forums/355860-azure-functions/suggestions/13286541-enable-custom-3rd-party-authentication-providers

**Comment by lindydonna** [comment]
Closing this issue since it's already tracked on UserVoice.
