### ISSUE TITLE
Node.js HTTP triggered function cannot return XML

### ISSUE THREAD

**Issue by dprothero** [Azure/azure-webjobs-sdk-script#942]
When you set the Content-Type header to 'text/xml' and the body to some valid XML, the actual response of the function is `<string xmlns="http://schemas.microsoft.com/2003/10/Serialization/">[escaped xml here]</string>`

#### Repro steps

```
module.exports = function (context, req) {
    context.log('JavaScript HTTP trigger function processed a request.');

    context.res.set('Content-Type', 'text/xml');
    context.res.body = '<?xml version="1.0" encoding="UTF-8"?><Response><Message>Hi there!' + 
        '</Message></Response>';
    context.done();
};
```

`function.json`:
```
{
  "bindings": [
    {
      "authLevel": "function",
      "type": "httpTrigger",
      "direction": "in",
      "name": "req"
    },
    {
      "type": "http",
      "direction": "out",
      "name": "res"
    }
  ],
  "disabled": false
}
```

#### Expected behavior

I would expect the Content-Type header to be text/xml and the body of the response to contain my XML and nothing else.

#### Actual behavior

The actual response of the function is `<string xmlns="http://schemas.microsoft.com/2003/10/Serialization/">[escaped xml here]</string>`

#### Known workarounds

If I set the Content-Type to 'text/html', it leaves my XML body unmolested. The content type isn't right, but Twilio will accept text/html. Other use cases requiring XML output may not have this workaround.

**Comment by paulbatum** [comment]
See https://github.com/Azure/azure-webjobs-sdk-script/issues/965. This scenario is enabled by using the isRaw flag. Sample from the linked issue:

``` js
  context.res = {
            status: 200,
            body: '<root>body</root>',
            headers: {
                'Content-Type': 'text/xml'
            },
            isRaw: true
        }
```
