### ISSUE TITLE
Azure Function runtime exception "Method not found" at method call in referenced assembly

### ISSUE THREAD

**Issue by pollax** [Azure/azure-webjobs-sdk-script#944]
I've written an Azure Function which is supposed to listen for a Blob storage event, receives the input (which is a blob) and then creates a new Azure Media Services IAsset and then copies the blob to the storage account used by Media Services.

The code is compiling and the function is triggered when a new blob is discovered. However, when copying the blob from one place to the other I receive a Method Not Found exception for ICloudBlob.StartCopyFromBlob(Uri source). 

Here are the log entries:

2016-11-17T15:34:12.721 Function started (Id=bf43ed91-6758-4a6e-a6dd-39359971cb20)  
2016-11-17T15:34:13.317 Function completed (Failure, Id=bf43ed91-6758-4a6e-a6dd-39359971cb20)  
2016-11-17T15:34:13.333 Exception while executing function: Functions.QueueTriggerCSharp1. mscorlib: Exception has been thrown by the target of an invocation. QueueTriggerCSharp1: Method not found: 'System.String Microsoft.WindowsAzure.Storage.Blob.ICloudBlob.StartCopyFromBlob(System.Uri, Microsoft.WindowsAzure.Storage.AccessCondition, Microsoft.WindowsAzure.Storage.AccessCondition, Microsoft.WindowsAzure.Storage.Blob.BlobRequestOptions, Microsoft.WindowsAzure.Storage.OperationContext)'.

The code for executing the copying is more or less copied from the samples on Media Services here: https://docs.microsoft.com/en-us/azure/media-services/media-services-copying-existing-blob

I've included the dependencies in a project.json file:
```json
{
  "frameworks": {
    "net46":{
      "dependencies": {
        "windowsazure.mediaservices.extensions": "3.8.0.2",
        "WindowsAzure.Storage":"4.3.0"
      }
    }
   }
}
```

Here's the code:
```c#
using Microsoft.WindowsAzure;
using Microsoft.WindowsAzure.MediaServices.Client;
using Microsoft.WindowsAzure.Storage;
using Microsoft.WindowsAzure.Storage.Auth;
using Microsoft.WindowsAzure.Storage.Blob;
using System.Threading;

public static void Run(CloudBlockBlob sourceBlob, TraceWriter log)
{
    var mediaServicesClientId = CloudConfigurationManager.GetSetting("MediaServicesClientId");
    var mediaServicesClientSecret = CloudConfigurationManager.GetSetting("MediaServicesClientSecret");
    var storageAccountName = CloudConfigurationManager.GetSetting("StorageAccountName");
    var storageAccountKey = CloudConfigurationManager.GetSetting("StorageAccountKey");

    var _context = new CloudMediaContext(new MediaServicesCredentials(mediaServicesClientId, mediaServicesClientSecret));
    var _destinationStorageAccount = new CloudStorageAccount(new StorageCredentials(storageAccountName, storageAccountKey), true);

    // Create a new asset. 
    IAsset asset = _context.Assets.Create("asset-" + Guid.NewGuid(), AssetCreationOptions.None);

    IAccessPolicy writePolicy = _context.AccessPolicies.Create("writePolicy", TimeSpan.FromHours(24), AccessPermissions.Write);
    ILocator destinationLocator = _context.Locators.CreateLocator(LocatorType.Sas, asset, writePolicy);

    CloudBlobClient destBlobStorage = _destinationStorageAccount.CreateCloudBlobClient();

    // Get the asset container URI and Blob copy from mediaContainer to assetContainer. 
    string destinationContainerName = new Uri(destinationLocator.Path).Segments[1];

    CloudBlobContainer assetContainer = destBlobStorage.GetContainerReference(destinationContainerName);
    assetContainer.CreateIfNotExists(BlobContainerPublicAccessType.Off);

    var assetFile = asset.AssetFiles.Create(sourceBlob.Name);
    var success = CopyBlob(sourceBlob, assetContainer, log);
    // TODO: handle failure
    assetFile.ContentFileSize = sourceBlob.Properties.Length;
    assetFile.Update();
    
    asset.Update();

    destinationLocator.Delete();
    writePolicy.Delete();
}

private static bool CopyBlob(ICloudBlob sourceBlob, CloudBlobContainer destinationContainer, TraceWriter log)
{
    var signature = sourceBlob.GetSharedAccessSignature(new SharedAccessBlobPolicy
    {
        Permissions = SharedAccessBlobPermissions.Read,
        SharedAccessExpiryTime = DateTime.UtcNow.AddHours(24)
    });

    ICloudBlob destinationBlob = destinationContainer.GetBlockBlobReference(sourceBlob.Name);

    if (destinationBlob.Exists())
    {
        log.Warning($"Destination blob '{destinationBlob.Uri}' already exists. Skipping.");
        return true;
    }
    else
    {
        // Display the size of the source blob.
        log.Info($"{sourceBlob.Properties.Length}");

        log.Info($"Copy blob '{sourceBlob.Uri}' to '{destinationBlob.Uri}'");
        destinationBlob.StartCopyFromBlob(new Uri(sourceBlob.Uri.AbsoluteUri + signature));

        CopyStatus cs;
        while (true)
        {
            // The StartCopyFromBlob is an async operation, 
            // so we want to check if the copy operation is completed before proceeding. 
            // To do that, we call FetchAttributes on the blob and check the CopyStatus. 
            destinationBlob.FetchAttributes();
            cs = destinationBlob.CopyState.Status;
            if (cs != CopyStatus.Pending)
            {
                log.Info($"Copy finished with status {cs}");
                break;
            }
            //It's still not completed. So wait for some time.
            Thread.Sleep(1000);
        }

        // Display the size of the destination blob.
        log.Info($"{destinationBlob.Properties.Length}");
        return cs == CopyStatus.Success;
    }
}
```

**Comment by fabiocav** [comment]
@pollax the runtime is likely applying its assembly redirects and loading a newer version of the storage SDK than what you're referencing.

This hopefully address the issue and validate this theory:

1. Remove the `project.json` reference to `WindowsAzure.Storage` (4.3.0 is also a pretty old version)
2. Add a reference directive to the top of your function code: `#r "WindowsAzure.Storage"`
3. Change your `CopyBlob` signature to work with `CloudBlockBlob` instead of `ICloudBlob`
4. Replace the call to `StartCopyFromBlob` to `StartCopyAsync` (https://msdn.microsoft.com/en-us/library/azure/mt423420.aspx)

**Comment by pollax** [comment]
Yes, your theory was correct.
Updating the `WindowsAzure.Storage` reference in `project.json` to the latest version and adjusting the code accordingly fixed the issue.

However, since I have other references in my `project.json` that also have `WindowsAzure.Storage` as a dependency, I could not add the `#r "WindowsAzure.Storage"` directive, it complained about that.

**Comment by lindydonna** [comment]
@fabiocav Please follow up on the remaining question, then close

**Comment by paulbatum** [comment]
@fabiocav Ping!

**Comment by fabiocav** [comment]
@pollax, we have the appropriate binding redirects and the references should be properly resolved, so I'm curious about the error you have received. If you can share details about the packages you were referencing and the error you were seeing, I'll investigate to see what is happening there.

Closing this issue since the original problem has been mitigated.

**Comment by rabrahamOpti** [comment]
@fabiocav Adding the reference directive `#r "WindowsAzure.Storage"` results in an error:

> [run.csx] Metadata File "WindowsAzure.Storage" could not be found.

**Comment by fabiocav** [comment]
@rabrahamOpti this issue was closed as mitigated over a year ago, can you please open a new issue with details about the problem you're seeing as well as the information requested in the issue template?

**Comment by rabrahamOpti** [comment]
@fabiocav I created an issue for a related issue: https://github.com/Azure/azure-functions-host/issues/2830
