### ISSUE TITLE
Secrets folder generated in function app folder when doing F5 from VS

### ISSUE THREAD

**Issue by paulbatum** [Azure/azure-webjobs-sdk-script#945]
Steps to reproduce:

1. Get the VS tooling for Azure Functions
2. File -> New Project -> Azure Functions
3. Add a new http function
4. hit F5

Expected result: No secrets folder is added to my project
Actual result: secrets folder is added to my project

CLI tooling version: 1.0.0-beta.6

**Comment by lindydonna** [comment]
This also appears to cause the Functions host to restart, because it sees new files in the project tree.
