### ISSUE TITLE
Empty sample data file generated in function app folder on F5 in VS

### ISSUE THREAD

**Issue by paulbatum** [Azure/azure-webjobs-sdk-script#946]
Steps to reproduce:

1. Get the VS tooling for Azure Functions
2. File -> New Project -> Azure Functions
3. Add a new http function
4. hit F5

Expected result: No extra file is generated, my function folder already has a sample.dat file
Actual result: an empty data\functions\sampledata\HttpTriggerCSharp.dat is generated

CLI tooling version: 1.0.0-beta.6

**Comment by lindydonna** [comment]
@ahmelsayed Will investigate why this is happening, might need the script host folks to weigh in

**Comment by EisenbergEffect** [comment]
Os the `.dat` file needed at all, or can it be deleted?

**Comment by paulbatum** [comment]
@EisenbergEffect when you're testing a function through the azure portal, the .dat file is where the test data is stored. This bug represents an issue from a while ago where this file was being generated even in non portal scenarios. You can always delete this file. The only reason to keep it is if you want to be able to return to the function in the portal at a later time, and test executing it with the same test data you used earlier.

**Comment by EisenbergEffect** [comment]
Cool. Thanks for the explanation @paulbatum I just started playing with functions today, so I've got a lot to learn 😄
