### ISSUE TITLE
Can't use ICloudBlob or CloudBlockBlob for output bindings

### ISSUE THREAD

**Issue by markheath** [Azure/azure-webjobs-sdk-script#952]
I'm trying to use `ICloudBlob` or `CloudBlockBlob` for blob output bindings. According to [docs](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-storage-blob) this should be supported.

I get the error:

    Cannot bind blob to CloudBlockBlob using access Write

or 

    Cannot bind blob to ICloudBlob using access Write

My function is in F#, but I've tried C# as well and got the same error. Possibly related to [this issue](https://github.com/Azure/azure-webjobs-sdk-script/issues/89)

Example C# repro:

    #r "Microsoft.WindowsAzure.Storage"
    using Microsoft.WindowsAzure.Storage.Blob;

    public static void Run(Stream myBlob, string name, TraceWriter log, CloudBlockBlob outputBlob)
    {
        log.Info($"C# Blob trigger function Processed blob\n Name:{name} \n Size: {myBlob.Length} Bytes");
    }

````
{
  "bindings": [
    {
      "name": "myBlob",
      "type": "blobTrigger",
      "direction": "in",
      "path": "samples-workitems/{name}",
      "connection": "AzureWebJobsDashboard"
    },
    {
      "type": "blob",
      "name": "outputBlob",
      "path": "outcontainer/{rand-guid}",
      "connection": "AzureWebJobsDashboard",
      "direction": "out"
    }
  ],
  "disabled": false
}
````

**Comment by christopheranderson** [comment]
Workaround: If you set direction for the "outputBlob" binding to "inout", this should be enabled. We'll be working to make it easier to add inout via the UX to prevent these issues.

**Comment by paulbatum** [comment]
Related: https://github.com/Azure/azure-webjobs-sdk-script/issues/49

Closing this as workaround provided.

**Comment by markheath** [comment]
thanks. A little unintuitive, but working now.

**Comment by mikhailshilkov** [comment]
How to achieve the same with the new Visual Studio 2017 Preview (2) API? How do I mark `CloudBlockBlob` parameter as inout with attributes?

**Comment by fabiocav** [comment]
@mikhailshilkov the binding attribute exposes a constructor that accepts a `FileAccess` value, for `inout` bindings, you just need to pass `FileAccess.ReadWrite` using that constructor.

**Comment by mikhailshilkov** [comment]
@fabiocav Thanks. I was confused because [cheat sheet](https://jhaleyfiles2016.blob.core.windows.net/public/Azure%20WebJobs%20SDK%20Cheat%20Sheet%202014.pdf) mentions Read/Write as default mod for `CloudBlockBlob`, so I thought it wasn't enough.

**Comment by leolorenzoluis** [comment]
I'm still getting the error..

```
 Microsoft.Azure.WebJobs.Host: Only the 'Read' FileAccess mode is supported for blob container bindings.
```

The parameter  I have is

```
Blob("x", FileAccess.ReadWrite)] CloudBlobContainer resizedBlob
```

**Comment by nzigel** [comment]
@leolorenzoluis maybe the container name "x" is too short and you don't have a markup for the blob name

[Blob("outputcontainer/{name}", FileAccess.ReadWrite, Connection = "AzureWebJobsStorage")]CloudBlockBlob outputBlob

worked for me
