### ISSUE TITLE
External HTTP Request within Azure Functions Timeout in 21 secs

### ISSUE THREAD

**Issue by justinyoo** [Azure/azure-webjobs-sdk-script#957]
Hi, Team.

I'm using Azure Storage Queue Trigger (C#) function. Within the function it calls an HTTP request to get RSS feed. However, when it sends the request, first two always fails in 21 secs with timeout error and the third attempt gets the feed. Here's the log:

> 2016-11-21T10:30:26.005 Function started (Id=0291ee18-d53d-46fc-b241-f84245151d8b)
> 2016-11-21T10:30:26.005 Player queue received.
> 2016-11-21T10:30:47.590 Function completed (Failure, Id=0291ee18-d53d-46fc-b241-f84245151d8b)
> 2016-11-21T10:30:47.590 Exception while executing function: Functions.GetPlayerFeedQueueTrigger. System: Unable to connect to the remote server. System: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond xxx.xxx.xxx.xxx:443. _(masked IP address)_

Not sure, if any settings can prevent this timeout error or not.

**Comment by christopheranderson** [comment]
Hey Justin, could you please share your code or your Function App name/function for us to investigate?

**Comment by justinyoo** [comment]
Sure thing.

The function calling the RSS feed is: [https://github.com/justinyoo/Tennis/blob/dev/src/Tennis.Functions/GetPlayerFeedQueueTrigger/run.csx](https://github.com/justinyoo/Tennis/blob/dev/src/Tennis.Functions/GetPlayerFeedQueueTrigger/run.csx)

The function calls a method in a private assembly to populate the RSS feed data. At the end of the method calling pipeline, the RSS feed is populated by using this method:
[https://github.com/justinyoo/Tennis/blob/dev/src/Tournaments.Services/SyndicationFeedWrapper.cs#L23](https://github.com/justinyoo/Tennis/blob/dev/src/Tournaments.Services/SyndicationFeedWrapper.cs#L23)

What I'm just wondering here is if we can control, in Azure Functions side, the timeout occurring from a remote server or not. I think it's a sort of an issue related to settings/configuration.

**Comment by lindydonna** [comment]
To help isolate the problem, please go to the Kudu console and just do a `curl` to your feed. The problem could be the server hosting the feed or the App Service sandbox, but we need more information to narrow it down.

**Comment by justinyoo** [comment]
@lindydonna I've already applied timeout to 60 secs within my code, which seems to be reasonably long. But it still complains. Let me try your approach and I'll get back to you.

**Comment by justinyoo** [comment]
@lindydonna I've run `curl --url http://something/feed` and got 5mins timeout message on KUDU console. At the same time I call the URL through a web browser, it's fine. The first `curl` call was fine but any subsequent calls all failed.

**Comment by justinyoo** [comment]
@lindydonna Is Azure Functions instance and its KUDU instance using the same public outbound IP address? I'm suspecting if the feeding website might block the IP address or not.

**Comment by lindydonna** [comment]
@justinyoo Yes, both Kudu and Azure Functions will be making the call the exact same way. Since it is failing in Kudu, the problem is not specific to Functions at all. I recommend posting an issue on the Azure Websites forum to get help there. https://social.msdn.microsoft.com/forums/azure/en-US/home?forum=windowsazurewebsitespreview

**Comment by rfpaula** [comment]
Hi @justinyoo, 

I am having a similar timeout problem. Did you find the cause of problem?

Thank you,
Rodrigo

**Comment by justinyoo** [comment]
@rfpaula It turned out Azure Functions did nothing wrong with this. The target website actually blocked the HTTP request call from their side.

**Comment by rfpaula** [comment]
@justinyoo thanks for your help. I'll look for some block on the target.

**Comment by shivaprasadsn** [comment]
did you get it resoloved?
