### ISSUE TITLE
Set response body to a buffer from Node.js function

### ISSUE THREAD

**Issue by paulbatum** [Azure/azure-webjobs-sdk-script#958]
See https://github.com/Azure/azure-webjobs-sdk-script/issues/942 for context. There is a need to be able to set the body directly, without any conversion due to content type. Using a buffer is a natural way to do this. Something like:

```
module.exports = function (context, req) {
    context.log('JavaScript HTTP trigger function processed a request.');
    context.res.set('Content-Type', 'text/xml');
    context.res.body = Buffer.from('<?xml version="1.0" encoding="UTF-8"?><Response><Message>Hi there!' + 
        '</Message></Response>');
    context.done();
};
```

**Comment by mathewc** [comment]
This is related to existing https://github.com/Azure/azure-webjobs-sdk-script/issues/814

**Comment by yvele** [comment]
@mathewc Any work around on how to simply set a **raw body**?

Since ~1.0 my application is broken..

I can't set a string because of https://github.com/Azure/azure-webjobs-sdk-script/issues/965 and I can't set a buffer because of https://github.com/Azure/azure-webjobs-sdk-script/issues/814.. Am I stuck?

**Comment by christopheranderson** [comment]
I propose we use a flag instead. I'd argue this is more idiomatic for Javascript. A flag like `isRaw` would be quite clear on its functionality. 

My main worry with the proposed Buffer approach is the added complexity of forcing people to convert to buffer each time they want raw, and to covert to an object/string themselves, if they have a buffer and don't want raw. Plus, it is harder to explain/document than a flag.

There are not a lot of common patterns for response handling. Most libraries that play in this area are very opinionated and mostly say "Use our response object, or use the plain response object (which we don't officially support, but you can use if you must)" (KoaJS), but Koa still does this with a flag. I think a better place to look, though, is to some of the behaviors of body formatting in libraries like request - https://www.npmjs.com/package/request . In request, they have a "json" flag, to treat the contents like JSON and set the appropriate content type on the request. There is some wizardry of trying to guess the content based on the value given, but I've found this to be buggy/hard to understand when I use request, and I always set the flags themselves properly.

**Comment by yvele** [comment]
@christopheranderson Anyway.. raw response what working before 1.0 [and not anymore](https://github.com/Azure/azure-webjobs-sdk-script/issues/965).. that's not serious.

**Comment by paulbatum** [comment]
See https://github.com/Azure/azure-webjobs-sdk-script/pull/871.

**Comment by paulbatum** [comment]
Easier to just close this as a dupe of https://github.com/Azure/azure-webjobs-sdk-script/issues/814
