### ISSUE TITLE
Allow specifying node function argument type

### ISSUE THREAD

**Issue by mamaso** [Azure/azure-webjobs-sdk-script#960]
It'd be nice to be able to specify argument type for node (perhaps in function.json)

For example, event hub trigger can support single object or multiple arrays in c#, but this isn't possible in node (always stuck with default type).

**Comment by fabiocav** [comment]
`DataType` does provide that for some of the bindings.

**Comment by mamaso** [comment]
Ah, nvmd looks like you're right.  Cardinality would handle that in this case
