### ISSUE TITLE
project.json in a "Shared" Directory Won't Restore NuGet Packages

### ISSUE THREAD

**Issue by justinyoo** [Azure/azure-webjobs-sdk-script#963]
Hi, Team.

I wonder if this is by design or not. I have a `Shared` directory in my Azure Functions app, which stores private assemblies and common `.csx` files to be used across all functions. That `Shared` folder also contains `project.json` to restore NuGet packages commonly used by all functions. However, it doesn't seem to be restoring relevant NuGet packages.

Wonder if this is an intended behaviour or not. According to the document, [Best Practices for Azure Functions](https://docs.microsoft.com/en-us/azure/azure-functions/functions-best-practices#dont-mix-test-and-production-code-in-the-same-function-app), it gives me an implication, if I provide `project.json` into the `Shared` folder, all declared NuGet packages in it would be automatically restored.

Could you clarify this, please?

Cheers,

**Comment by fabiocav** [comment]
Justin, that is not currently a supported scenario. The restore is currently scoped per function, so you'd still need to have those packages there.
One alternative for what you're describing is to actually have your dependency as a nuget package (which could be in MyGet or even on the file system with a custom source setup in nuget.config) and have the additional package dependencies specified there. 
I intend to have a quick post on the approach above soon.

**Comment by justinyoo** [comment]
@fabiocav Thanks for the clarification!
