### ISSUE TITLE
Cannot perform runtime binding on a null reference

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-webjobs-sdk-script#971]
A function feeding of a `queueTrigger` bound to an auto-generated queue `webjobs-blobtrigger-poison` gets invoked once correctly (argument for a queue message contains data) and is invoked for the second time with a null message.

Log file output
``` 
2016-11-22T21:28:57.816 Function started (Id=675dbc96-85a1-4c6f-a87b-c165a20ffe09)
2016-11-22T21:28:57.816 C# Queue trigger function received: {
  "Type": "BlobTrigger",
  "FunctionId": "Host.Functions.CreateThumbnail",
  "BlobType": "BlockBlob",
  "ContainerName": "sample-images",
  "BlobName": "test.txt",
  "ETag": "\"0x8D4131E8E7D591D\""
}
2016-11-22T21:28:57.816 Function completed (Success, Id=675dbc96-85a1-4c6f-a87b-c165a20ffe09)
2016-11-22T21:32:08.875 Function started (Id=efd91564-89b8-4c98-9557-64bd10ae426b)
2016-11-22T21:32:08.875 C# Queue trigger function received:
2016-11-22T21:32:08.875 Function completed (Failure, Id=efd91564-89b8-4c98-9557-64bd10ae426b)
2016-11-22T21:32:08.906 Exception while executing function: Functions.NotifyAboutFailure. Anonymously Hosted DynamicMethods Assembly: Cannot perform runtime binding on a null reference.
```

#### Repro steps

1. Create Function A to generate a poisonous  message using blob trigger
2. Create Function B to handle messages from a poisonous message queue

#### Expected behavior

Function to be invoked once only

#### Actual behavior

Invoked more than once

#### Related information 

* Programming language used: C#
* Functions version: 1

**Comment by SeanFeldman** [comment]
It looks like it's happening periodically and consistently all the time 😞 
![image](https://cloud.githubusercontent.com/assets/1309622/20546650/e83ea3dc-b0d3-11e6-9cdc-72050984005d.png)

Does that mean it "wastes" the free execution pool as well?

**Comment by christopheranderson** [comment]
You can disable your function for now to prevent it from running. Mathew is taking a look at trying to repro it to better understand what might be happening.

**Comment by SeanFeldman** [comment]
Yep, already did that.
Go @mathewc!

**Comment by mamaso** [comment]
@SeanFeldman I'm unable to reproduce this with a BlobTrigger that throws and a QueueTrigger bound to the webjobs-blobtrigger-poison in C#.

Can you give me more specifics:
 - is the bug still occurring? if so, is it consistent or intermittent?
 - are you running on consumption?
 - can you supply function code which causes the repro?

**Comment by SeanFeldman** [comment]
Can't reproduce it anymore after upgrading Functions.
Will close. If it happens again, will reopen.
