### ISSUE TITLE
remove func new from CLI and recommend folks install yo themselves

### ISSUE THREAD

**Issue by christopheranderson** [Azure/azure-webjobs-sdk-script#974]
Func new is the only reason we install yo directly. Yo is slow to install and it also has some long start up times that we're covering up by including it in our CLI.  

I propose that we remove the func new support for now, and just tell folks to install yo and the generator directly.  This gives us a faster install time and less frustration with yo being broken/slow in weird ways that are unrelated to our core CLI.

If we get more requests/demand/scenarios for doing func new in our CLI, we can look at a better, more performant implementation.

**Comment by lindydonna** [comment]
Closing since we're going to revisit func new and yeoman dependency.
