### ISSUE TITLE
"Method not found Exception" on an Azure Function

### ISSUE THREAD

**Issue by santinf** [Azure/azure-webjobs-sdk-script#976]
Hello,

I have two Azure functions hosted on a "Classic Plan".
Both are :  
- Written using C#
- Reference an external business DLL using #r "MyDll.dll"
- Have no compilation / package restore problems

When I restart my host
- I manualy run **function A**
- A succeed
- I manualy run **function B**
- B has a Method not found Exception on the first method call of my "MyDll.dll".

> 2016-11-23T17:53:43.200 Exception while executing function: Functions.FunctionB. mscorlib: Exception has been thrown by the target of an invocation. FunctionB: Method not found: 'Void BizDll..ctor(System.Guid, args)'.

Then i restart my host
- I manualy run **function B**, before **function A**
- B succeed
- I manualy run **function A**
- A has a Method not found Exception on the first method call of my "MyDll.dll" (different method from A because business logic is different).

Do you know how to solve this issue?

Regards,

Florent.

**Comment by fabiocav** [comment]
@santinf this points to that assembly being a different binary in each function, but having the same assembly identity.

There are a couple of ways you can go about this:
1. Make sure you properly version the assemblies when you make changes to it
2. If you expect the 2 functions to share the same exact logic (i.e. the assemblies are supposed to be the same), you may want to consider removing the assembly from each function's bin folder, creating a shared folder on the root of your function app (e.g. sharedassemblies) and modifying the reference to ```#r "../sharedassemblies/MyDll.dll". This approach will make this dependency a bit easier to manage.

**Comment by santinf** [comment]
Thank you @fabiocav .

I tried (2) with a shared directory
- I copied all my business DLL in shared
- I reference them throw #r "../shared/biz.dll"
- My business DLL are well load.

When my function invoke the shared DLL, all the assemblies they used and referenced throw nuget are no longer loaded.

For exemple, I have a 
`"2016-11-24T17:30:08.438 Exception while executing function: Functions.A. mscorlib: Exception has been thrown by the target of an invocation. mscorlib: Could not load file or assembly 'Microsoft.Azure.SqlDatabase.ElasticScale.Client, Version=1.3.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified."`

In my Azure A function and B function project.json I have this kind of configuration 👍 
```
{
  "frameworks": {
        "net46": {
              "frameworkAssemblies": {
                "System.Data": "4.0.0.0"
      }
        }
  },
  "dependencies": {
    "Microsoft.Extensions.Configuration": "1.0.0",
    "Microsoft.Extensions.Configuration.Abstractions": "1.0.0",
    "Microsoft.Extensions.Configuration.Json": "1.0.0",
    "Sendgrid": "8.0.4",
    "WindowsAzure.Storage": "7.2.0",
    "Newtonsoft.Json": "9.0.1",
    "Microsoft.Azure.SqlDatabase.ElasticScale.Client": "1.3.3",
    "EntityFramework": "6.1.3",
    "EntityFramework.Functions": "1.3.1"
  }
}

How can i shared a project.json dependencies configuration between Azure functions?
```
