### ISSUE TITLE
Different behaviour when body is missing

### ISSUE THREAD

**Issue by cloudkite** [Azure/azure-webjobs-sdk-script#978]
#### Repro steps

given the following function.json

```
{
  "entryPoint": "handler",
  "bindings": [
    {
      "type": "httpTrigger",
      "direction": "in",
      "name": "req",
      "methods": [ "get" ],
      "route": "embed/{appId}",
      "authLevel": "anonymous"
    },
    {
      "type": "http",
      "direction": "out",
      "name": "$return"
    }
  ],
  "disabled": false
}
```

and the following handler

```
export function handler(ctx, req) {
  return Promise.resolve({
    status: 302, headers: { Location: '/new_url' }
  })
}
```

#### Expected behavior

redirect to `/new_url`

#### Actual behavior

returns status `200`, with JSON body: `{ status: 302, headers: { Location: '/new_url' } }`

#### Known workarounds

adding an empty body causes the redirect to be followed

```
export function handler(ctx, req) {
  return Promise.resolve({
    body: '', status: 302, headers: { Location: '/new_url' }
  })
}
```

Is this behaviour intentional? Seems very confusing

**Comment by mamaso** [comment]
Yep, it's intentional, though this should probably be changed.

We inspect the returned json for a body property, and if it exists then we treat the returned object as a response object, otherwise we treat it as the body itself.

**Comment by cloudkite** [comment]
Thanks for clarifying! Would personally prefer it to always treat object as response object, for consistency sake. But don't think its a major issue either way

**Comment by yvele** [comment]
@cloudkite I agree with your consistency remark.. Azure Function HTTP response needs a single simple interface.. no magic behaviour (https://github.com/Azure/azure-webjobs-sdk-script/issues/965, https://github.com/Azure/azure-webjobs-sdk-script/issues/814)
@mamaso What if someone want to actually return a json with a `body` property?..

**Comment by mamaso** [comment]
@cloudkite I agree that it's simpler to reason about without the magic.  However, in simple scenarios the magic is correct and makes for concise code.

@yvele 
```
{
  // treated as response object
  body: {
    body: ... // the actual body property
  }
}
```

**Comment by yvele** [comment]
@mamaso I know.

I'm talking about side effect when someone is using the "magic" interface and for whatsoever reason a `body` property can appear over the time or dynamically.. The poor guy will have hard time to figure out what is happening.. and will lose some hairs in debugging with this unpredictable behaviour.. 

Maintainability..!

**Comment by mamaso** [comment]
@yvele I agree with you, if I could make the change I would, but unfortunately it's the current behavior and we need to support it.  In a next major version we will evaluate how much of this 'magic' we keep around.

**Comment by yvele** [comment]
@mamaso Ok 👍 

PS: Still in beta and already [technical dept](https://en.wikipedia.org/wiki/Technical_debt) :neutral_face:

**Comment by fabiocav** [comment]
@yvele We've moved out of beta with 1.0, that's the challenge with breaking changes, which can only happen on the next major release and even then, have to carefully evaluated.

**Comment by paulbatum** [comment]
@mamaso There is no further action here. Can you file a new issue with a breaking label describing the change we would ideally make in the next major version and assign to the backlog milestone and then close this.

**Comment by mamaso** [comment]
Added the new issue, we'll revisit for next major release.

**Comment by cloudkite** [comment]
@mamaso @fabiocav another argument for removing this behaviour is that there is currently no way to send a valid 204 request.

**Comment by mamaso** [comment]
@cloudkite it's possible via `context.res.sendStatus(204)` or `context.res = {
  status: 204,
  body: undefined
}`

**Comment by cloudkite** [comment]
@mamaso didn't realise you can do body: undefined, thanks!
