### ISSUE TITLE
Azure Functions: Function magically works without adding a dependency to "HtmlAgilityPack"

### ISSUE THREAD

**Issue by lucabol** [Azure/azure-webjobs-sdk-script#981]
Subscription id: 818e194a-9bee-486f-9854-03b3be61170b
Function App name: FollowTheGuru
The dll refernced below is from [here](https://github.com/lucabol/FollowTheGuru)

#### Repro steps

a.	The function is BugCoreSupport1
b.	It references bin2bug\Guruloader.dll which is compiled against net46, such dll uses HtmlAgilityPack
c.	There is no project.json file in BugCoreSupport1 folder to declare a dependencies from HtmlAgilityPack

#### Expected behavior

Fails with an error message saying that it doesn't recongnize types defined in HtmlAgilityPack.

#### Actual behavior

The function works.

**Comment by fabiocav** [comment]
@lucabol was the function actually executing methods depending on types coming from that assembly?

BTW, thanks for sharing a repo! that's very helpful.

**Comment by lucabol** [comment]
Yes, FetchDisplayPortfolioAsync loads an html file and parses it using HtmlAgilityPack types. You can follow the call [here](https://github.com/lucabol/FollowTheGuru/blob/master/GuruLoader/GuruLoader.cs). The fact that it works (aka prints out the values) means that the whole operation has worked fine.

**Comment by fabiocav** [comment]
If it uses types from that assembly and it works, that assembly is coming from somewhere 😃 

If you open Kudu > Process explorer > right click on th non-scm w3wp process and go to properties you can look at the handles tab and look for that assembly to see where it was loaded from.

**Comment by lucabol** [comment]
Restarting the service, as you asked me to do in the other issue, makes this function throw an error, as expected. The assembly is then not in the handles for the process, still as expected. I don't think I understand how it all hangs together. Are the function not isolated from each other? If a .net restore happens on function A, does it have an effect on function B?

**Comment by fabiocav** [comment]
There's no process or app domain isolation between functions within the same function app. Assemblies are loaded in different contexts depending on how you're referencing them (private, shared or packages) to meet the expectations (also allowing for side-by-side version loading). Things like statics are also shared between functions in the same Function App  . If you need complete isolation, the only way to achieve that is by having the functions in separate function apps.

**Comment by lucabol** [comment]
I see. I guess my expectations were incorrect. The fact that there is a project.json for each function and a suggestion to add a /bin directory for each function throughout the docs, made me assume that the unit of isolation is the function.
