### ISSUE TITLE
Azure Functions: Log messages out of date (from hours ago)

### ISSUE THREAD

**Issue by lucabol** [Azure/azure-webjobs-sdk-script#983]
![functionlogbusted](https://cloud.githubusercontent.com/assets/1370774/20599795/73a43cac-b250-11e6-89f0-ede37b94f32b.JPG)
After some errors in the application the log gets out of sync and shows old messages instead of newer ones. 
Notice the date of the log message compared to the date on my screen. I have executed this function multiple times today and yesterday.

It happens often on the following function:

Subscription id: 818e194a-9bee-486f-9854-03b3be61170b
Function App name: FollowTheGuru
Function name: CheckGurusUpToDate

**Comment by lindydonna** [comment]
Closing in favor of https://github.com/projectkudu/AzureFunctionsPortal/issues/818
