### ISSUE TITLE
Retrieve the LoaderExceptions property for more information error

### ISSUE THREAD

**Issue by JonCanning** [Azure/azure-webjobs-sdk-script#985]
Reference FSharp.Data in project.json and put these lines at the top of the Run.fsx

```
open FSharp.Data
let work = async { return Array.empty<JsonValue> }
```

Recompilation is triggered but no success message is returned.
Running the function produces this error
`Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.'

**Comment by stefan-akelius** [comment]
Can confirm. I'm getting the same error for my F# functions.

**Comment by fabiocav** [comment]
Thank you for the repro! This is helpful! I have added some information to the other issue you've opened as well.

**Comment by fabiocav** [comment]
To make sure the information is here as well:

> Yes, you can set your FUNCTIONS_EXTENSION_VERSION app setting to ~0.9 in the meantime.
I was also able to repro this, so we'll have a fix out ASAP

**Comment by fabiocav** [comment]
Validated fix. This will be addressed in our next deployment.

**Comment by jonathanfishbein1** [comment]
I'm getting this error now.

` The following 3 functions are in error:
[0] PostNewRouteProblem: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
[0] PutRouteProblemAndUser: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
[0] PutUser: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.`

All three of these functions are referencing a .dll I broke off from the main library.  The functions as well as the library are written in F#.  Before I broke off the functionality into a separate .dll I wasn't getting this error

**Comment by JonCanning** [comment]
I've seen this again recently too, and got around it my building on a PC instead of my Mac. However, a colleague with a Mac does not get this problem, and I tried a different PC and it happened, so right now I have no idea!

**Comment by fabiocav** [comment]
The Mac scenario is currently in preview only and may not be very reliable.

Are you seeing the exact message? Is this happening locally only? And with a repro similar to what is described above?

**Comment by jonathanfishbein1** [comment]
I'm not sure if you're asking me, but let me add I'm using

` "azure-functions-core-tools": "^1.0.0-beta.100",`

**Comment by jonathanfishbein1** [comment]
This is happening again and I forget what I did last time to fix it.  I wound up on this page again!

now I'm using 

dotnet core 2.1.4
node v9.5.0
"azure-functions-core-tools": "^2.0.1-beta.22"
