### ISSUE TITLE
Support for .NET Core

### ISSUE THREAD

**Issue by zeroskyx** [Azure/azure-webjobs-sdk-script#987]
Currently only .NET 4.6 is supported which is a bit strange since .NET Core was especially designed for cloud scenarios with small footprints and many projects are headed that way currently.
Please enable first class support for .NET Core.

**Comment by paulbatum** [comment]
Hi @zeroskyx! We have been discussing .NET core support for Azure Functions quite a bit recently now that our GA milestone is behind us. One of the biggest advantages to doing this work is it would enable cross platform local development (right now https://www.npmjs.com/package/azure-functions-cli only supports Windows). 

However there is some subtlety to this - for example we could support running locally on .NET Core but continue to run your functions on NET 4.6 in Azure. Could you expand on exactly what you would like to see? For example do you want your functions to execute in Azure using .NET Core? If so, why specifically? Real world customer motivations will help us prioritize the different aspects of this work item.

**Comment by zeroskyx** [comment]
Hi Paul,

I did send you a mail with further details.

Thanks and best regards
-Simon

**Comment by paulbatum** [comment]
Tracked by https://github.com/Azure/Azure-Functions/issues/98. Closing this issue as a dup, new issues will be created for the individual work items.
