### ISSUE TITLE
CLI Timer fails on run 

### ISSUE THREAD

**Issue by TonyAbell** [Azure/azure-webjobs-sdk-script#993]
Steps
--

* func init
* func new  
(Select timer template, and give it a name of timer)
* func run timer

Error
--
> A ScriptHost error has occurred
> Stopping Host
> Unable to retrieve functions list: No MediaTypeFormatter is available to read an object of type 'FunctionEnvelope[]' from content with media type 'text/plain'.

Language 
--
I have tried this on the following languages, with the same results for each one.
* C#
* F#
* JS 

 @ahmelsayed

**Comment by lindydonna** [comment]
@TonyAbell Did you have a value for AzureWebJobsStorage in appsettings.json?  This is likely a poor error message that needs to be improved.

**Comment by desinole** [comment]
I had the same issue with a brand new TimerTrigger project. Setting the "AzureWebJobsStorage" value to "UseDevelopmentStorage=true" in the appsettings.json file fixed it

**Comment by lindydonna** [comment]
@ahmelsayed's proposal: 
1) Test to see if local storage emulator works ok for common scenarios
2) Inject this value (and print a warning to the console) if AzureWebJobsStorage is null

**Comment by lindydonna** [comment]
Error message issue will be fixed with https://github.com/Azure/azure-webjobs-sdk-script/issues/1069

**Comment by ahmelsayed** [comment]
This issue was moved to Azure/azure-functions-cli#6
